/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-4.8 and Fable-5
-/
import GQ2.SectionEight.ScalarCount
import GQ2.Roe.AdmissibleLimit
import GQ2.FinitelyGenerated

/-!
# `Γ_R` source-data supply: topological finite generation and the scalar character count

The two `Γ_R` source obligations that are **independent of the R30 pro-2 coordinate**, i.e. rows
ii.1 and ii.2 of the SourceData recon memo (`docs/orchestration/roe-r30-recon.md`).  Each is an
exact byte-for-byte clone of its `Γ_A` original, with the same carrier spelling, so that the R30
`SourceData` structure and R32's `main_presentation` instantiation can plug `Γ_R` into the A-slot:

* **(recon row ii.1)** `GQ2.gammaR_topologicallyFinitelyGenerated` — the clone of
  `GQ2.gammaA_topologicallyFinitelyGenerated` (`GQ2/FinitelyGenerated.lean`).  Same
  `∃ s : Finset (GammaR : Type), (Subgroup.closure ↑s).topologicalClosure = ⊤` shape (the
  `hfgA`/`prop_8_9_aux` `hfg` argument of the lanes).  The four free generators of `F₄` survive the
  quotient `F₄ ↠ F₄ ⧸ N_R = Γ_R`, so `Γ_R` is topologically finitely generated by
  `GQ2.IsTopologicallyFinGen.of_surjective` at the quotient projection — verbatim the `Γ_A`
  argument with `N_A` replaced by `N_R` (`GQ2.NR`, R3 `GQ2/Roe/GammaR.lean`).

* **(recon row ii.2)** `GQ2.lemma_8_2_R` — the clone of `GQ2.SectionEight.lemma_8_2_gammaA`
  (`GQ2/SectionEight/ScalarCount.lean`): `Nat.card (ContinuousMonoidHom Γ_R 𝔽₂) = 8`, fed to
  `prop_8_9_aux`'s `hscalar`, `prop_8_9_of`, and `rStage_phase`.  Route mirrored end-to-end:
  characters of `Γ_R` are `F₄`-generator values killing `N_R` (`GQ2.SectionEight.charEquiv` /
  `cmhEquivFun`, reused), and killing `N_R` is exactly killing `τ` (`ker_char_NR_le_iff`, the port
  of `GQ2.SectionEight.ker_char_NA_le_iff`).  The **only** Roe-specific ingredient is the backward
  step: in an exponent-2 abelian quotient the Roe wild relation `r_R` degenerates — mod 2 the
  ledger `r_R = x₀⁻¹ · (x₀⁻³τ)^{ω₂} · x₁²` (R1 `Marking.wildValueR_comm`, `GQ2/Roe/Words.lean`)
  reads `−4·χ(x₀) + χ(τ) ≡ χ(τ)`, vacuous once `χ(τ) = 0`.  This is `Marking.wildRelR_of_comm2`,
  the Roe counterpart of `GQ2.SectionEight.Marking.wildRel_of_comm2`, and it lets
  `GQ2.isAdmissibleUR_iff_NR_le` (R3 `GQ2/Roe/AdmissibleLimit.lean`) certify `ker c ⊇ N_R`.  That
  leaves the free `𝔽₂³` of `σ, x₀, x₁`-values: `2³ = 8`.

Both declarations become `SourceData` field values for R30/R32.  No new axioms (`#print axioms` at
the standard three throughout); all counting scaffolding is reused, never re-proved.

**Module-system note.** Unlike its `GQ2/Roe/*` siblings this file is deliberately *not* a `module`
(plain `import`, no `@[expose] public section`): it depends on `GQ2.SectionEight.ScalarCount`, and
the whole `GQ2/SectionEight/` chain is non-`module`, so a `module` header here fails to elaborate
with `cannot import non-`module` GQ2.SectionEight.ScalarCount from `module``.  Same resolution as
the sibling `GQ2/Roe/Prop23.lean`, which reaches into the same non-`module` §2/§8 stack.  Importing
the `module` files `GQ2.Roe.AdmissibleLimit` / `GQ2.FinitelyGenerated` from here is fine — the
restriction is one-directional.  R30's `GQ2/SourceData.lean` will inherit the same constraint.
-/

open CategoryTheory ProfiniteGrp

namespace GQ2

open SectionEight

/-! ## (recon row ii.1) `Γ_R` is topologically finitely generated

Verbatim clone of `GQ2.gammaA_isTopologicallyFinGen` / `GQ2.gammaA_topologicallyFinitelyGenerated`
(`GQ2/FinitelyGenerated.lean`), routed through the `Γ_R` quotient projection `F₄ ↠ Γ_R`. -/

/-- **`Γ_R` is topologically finitely generated** (the predicate form).  Clone of
`GQ2.gammaA_isTopologicallyFinGen`: the free profinite group `F₄` is topologically finitely
generated (`isTopologicallyFinGen_freeProfiniteGroup`), and this passes along the continuous
surjection `F₄ ↠ F₄ ⧸ N_R = Γ_R` (`IsTopologicallyFinGen.of_surjective`). -/
theorem gammaR_isTopologicallyFinGen : IsTopologicallyFinGen (GammaR : Type) := by
  haveI : IsClosed (NR : Set (FreeProfiniteGroup (Fin 4))) := NR_isClosed
  exact isTopologicallyFinGen_freeProfiniteGroup.of_surjective (quotientMk NR).toMonoidHom
    (quotientMk NR).continuous_toFun (quotientMk_surjective NR)

/-- **(recon row ii.1)** **`Γ_R` is topologically finitely generated**, in exactly the
`∃ s : Finset _, …` shape consumed as the `hfgA`/`hfg` argument of the §8/§9 lanes and by R32's
`main_presentation` instantiation — the same statement shape and carrier spelling `(GammaR : Type)`
as its `Γ_A` original `GQ2.gammaA_topologicallyFinitelyGenerated` (`GQ2/FinitelyGenerated.lean`). -/
theorem gammaR_topologicallyFinitelyGenerated :
    ∃ s : Finset (GammaR : Type),
      (Subgroup.closure (s : Set (GammaR : Type))).topologicalClosure = ⊤ :=
  gammaR_isTopologicallyFinGen

/-- **Stress test / cross-check**: `Γ_R` and `Γ_A` are topologically finitely generated by the
*same* mechanism — the image of `F₄`'s four free generators — so the predicate holds for both
candidate groups (the wild relation is irrelevant to finite generation). -/
theorem gammaR_and_gammaA_isTopologicallyFinGen :
    IsTopologicallyFinGen (GammaR : Type) ∧ IsTopologicallyFinGen (GammaA : Type) :=
  ⟨gammaR_isTopologicallyFinGen, gammaA_isTopologicallyFinGen⟩

/-! ## (recon row ii.2) The `Γ_R` scalar character count `|Hom_cont(Γ_R, 𝔽₂)| = 8`

Clone of `GQ2.SectionEight.lemma_8_2_gammaA` (`GQ2/SectionEight/ScalarCount.lean`), reusing the
generic counting scaffolding `charEquiv` / `cmhEquivFun` / `vecEquiv` and porting the single
source-specific lemma `ker_char_NA_le_iff` to `ker_char_NR_le_iff`. -/

/-- `𝔽₂` has two elements (local copy: `GQ2.SectionEight.card_M2` is private to `ScalarCount`). -/
private lemma card_M2 : Nat.card (Multiplicative (ZMod 2)) = 2 := by
  rw [Nat.card_congr Multiplicative.toAdd, Nat.card_zmod]

section WildRelRComm

variable {A : Type*} [Group A]

/-- **The Roe wild relation follows from `τ = 1` in an exponent-2 abelian group** — the Roe
counterpart of `GQ2.SectionEight.Marking.wildRel_of_comm2`.  The `ω₂`-ledger collapses:
`powOmega2 = id` on involutions, conjugations and commutators are trivial, so
`r_R = (x₀^σ)⁻¹ · (x₀⁻³τ)^{ω₂} · x₁² · [x₁, y₁]` reduces to `x₀⁻¹ · (x₀⁻³τ) · x₁²`, and with
`τ = 1`, `x₀² = x₁² = 1` this telescopes to `1` (mod 2 the ledger `−4·χ(x₀) + χ(τ)` is vacuous
once `χ(τ) = 0`; cf. R1 `Marking.wildValueR_comm`, `GQ2/Roe/Words.lean`).  For scalar characters
the hypothesis `τ = 1` is free — the tame relation already forces it
(`GQ2.SectionEight.Marking.tameRel_iff_of_comm2`). -/
lemma Marking.wildRelR_of_comm2 (hcomm : ∀ a b : A, a * b = b * a)
    (h2 : ∀ a : A, a * a = 1) (t : Marking A) (hτ : t.τ = 1) : t.WildRelR := by
  have hpow : ∀ a : A, powOmega2 a = a := powOmega2_eq_self_of_sq h2
  have hconj : ∀ x g : A, conjP x g = x := conjP_of_comm hcomm
  have hcommP : ∀ x y : A, commP x y = 1 := commP_of_comm hcomm
  have hinv : ∀ x : A, x⁻¹ = x := fun x => inv_eq_of_mul_eq_one_right (h2 x)
  have hx0sq : t.x₀ ^ 2 = 1 := by rw [pow_two]; exact h2 t.x₀
  -- with `τ = 1` and exponent 2, `a = (x₀⁻³τ)^{ω₂}` collapses to `x₀`
  have haR : t.aR = t.x₀ := by
    rw [Marking.aR, hpow, hτ, mul_one, hinv, show (3 : ℕ) = 2 + 1 from rfl, pow_add, pow_one,
      hx0sq, one_mul]
  have hcR : t.cR = 1 := by rw [Marking.cR, hcommP]
  have hx1 : t.x₁ ^ 2 = 1 := by rw [pow_two]; exact h2 t.x₁
  show t.wildValueR = 1
  rw [Marking.wildValueR, hconj, haR, hcR, mul_one, hx1, mul_one, inv_mul_cancel]

end WildRelRComm

/-- **The kills-`N_R` criterion**: a character of `F₄` kills `N_R` iff it kills `τ`.  Port of
`GQ2.SectionEight.ker_char_NA_le_iff`, swapping the tame-relator membership `tameRelator_mem_NR`
(R3 `GQ2/Roe/AdmissibleLimit.lean`), `IsAdmissibleUR`, the Roe exponent-2 collapse
`Marking.wildRelR_of_comm2`, and the admissible-opens characterization
`GQ2.isAdmissibleUR_iff_NR_le`.  Forward: `N_R` contains the tame relator, whose `𝔽₂`-image is
`c(τ)`.  Backward: `ker c` is then `R`-admissible (generation automatic, tame is the `τ`-kill, and
in an exponent-2 abelian quotient both the Roe wild relation and the 2-core are unconditional), so
`N_R ≤ ker c`. -/
theorem ker_char_NR_le_iff
    (c : ContinuousMonoidHom (FreeProfiniteGroup (Fin 4)) (Multiplicative (ZMod 2))) :
    NR ≤ c.toMonoidHom.ker ↔ c univMarking.τ = 1 := by
  constructor
  · intro hNR
    have htame : c univMarking.tameRelator = 1 := by
      have := hNR tameRelator_mem_NR
      rwa [MonoidHom.mem_ker] at this
    rw [Marking.tameRelator, map_mul, map_inv, map_pow,
      show c (conjP univMarking.τ univMarking.σ)
          = (c univMarking.σ)⁻¹ * c univMarking.τ * c univMarking.σ from by
        rw [conjP, map_mul, map_mul, map_inv]] at htame
    have hM2 : ∀ s t : Multiplicative (ZMod 2),
        s⁻¹ * t * s * (t ^ 2)⁻¹ = 1 → t = 1 := by
      decide
    exact hM2 _ _ htame
  · intro hτ
    -- the kernel, as an open normal subgroup
    have hker_open :
        IsOpen ((c.toMonoidHom.ker : Subgroup _) : Set (FreeProfiniteGroup (Fin 4))) := by
      have hset : ((c.toMonoidHom.ker : Subgroup _) : Set (FreeProfiniteGroup (Fin 4)))
          = c ⁻¹' {1} := Set.ext fun g => by simp [MonoidHom.mem_ker]
      rw [hset]
      exact (isOpen_discrete ({1} : Set (Multiplicative (ZMod 2)))).preimage
        c.continuous_toFun
    set U : OpenNormalSubgroup (FreeProfiniteGroup (Fin 4)) :=
      { toSubgroup := c.toMonoidHom.ker, isOpen' := hker_open } with hU
    -- the quotient has order dividing 2, hence is exponent-2 abelian
    haveI : Finite (FreeProfiniteGroup (Fin 4) ⧸ U.toSubgroup) := by
      exact Finite.of_equiv _
        (QuotientGroup.quotientKerEquivRange c.toMonoidHom).symm.toEquiv
    have hcard : Nat.card (FreeProfiniteGroup (Fin 4) ⧸ U.toSubgroup) ∣ 2 := by
      calc Nat.card (FreeProfiniteGroup (Fin 4) ⧸ U.toSubgroup)
          = Nat.card c.toMonoidHom.range :=
            Nat.card_congr (QuotientGroup.quotientKerEquivRange c.toMonoidHom).toEquiv
        _ ∣ Nat.card (Multiplicative (ZMod 2)) := Subgroup.card_subgroup_dvd_card _
        _ = 2 := card_M2
    have h2q : ∀ y : FreeProfiniteGroup (Fin 4) ⧸ U.toSubgroup, y * y = 1 := by
      intro y
      have horder : orderOf y ∣ 2 := (orderOf_dvd_natCard y).trans hcard
      rw [← pow_two]
      exact orderOf_dvd_iff_pow_eq_one.mp horder
    have hcommq : ∀ y z : FreeProfiniteGroup (Fin 4) ⧸ U.toSubgroup, y * z = z * y :=
      mul_comm_of_exp_two h2q
    -- `ker c` is `R`-admissible
    have hτq : (univMarking.map (QuotientGroup.mk' U.toSubgroup)).τ = 1 := by
      show QuotientGroup.mk' U.toSubgroup univMarking.τ = 1
      exact (QuotientGroup.eq_one_iff _).mpr (MonoidHom.mem_ker.mpr hτ)
    have hadm : IsAdmissibleUR U := by
      refine ⟨generates_univMarking_map U, ?_,
        Marking.wildRelR_of_comm2 hcommq h2q _ hτq, ?_⟩
      · exact (Marking.tameRel_iff_of_comm2 hcommq h2q _).mpr hτq
      · intro g
        refine ⟨1, ?_⟩
        ext
        rw [SubgroupClass.coe_pow, OneMemClass.coe_one,
          show (2 : ℕ) ^ 1 = 2 from rfl, pow_two]
        exact h2q _
    exact (isAdmissibleUR_iff_NR_le U).mp hadm

/-- **(recon row ii.2)** **Lemma 8.2, Roe source**: `|Hom_cont(Γ_R, 𝔽₂)| = 8`.  Byte-for-byte
clone of `GQ2.SectionEight.lemma_8_2_gammaA` (`GQ2/SectionEight/ScalarCount.lean`) with `N_A`
replaced by `N_R`: characters of `Γ_R` are `F₄`-generator values killing `N_R`
(`GQ2.SectionEight.charEquiv` / `cmhEquivFun`), and killing `N_R` is exactly killing `τ`
(`ker_char_NR_le_iff` — the tame relator forces it, and conversely `c(τ) = 1` gives both relations
in exponent-2 abelian quotients).  That leaves the free `𝔽₂³` of `σ, x₀, x₁`-values.  Same carrier
spelling `GammaR` and statement shape as the `Γ_A` original, as required by R30/R32. -/
theorem lemma_8_2_R :
    Nat.card (ContinuousMonoidHom GammaR (Multiplicative (ZMod 2))) = 8 := by
  have e := (charEquiv NR).trans
    ((Equiv.subtypeEquiv cmhEquivFun (fun c => ker_char_NR_le_iff c)).trans vecEquiv)
  exact (Nat.card_congr e).trans (by rw [Nat.card_prod, Nat.card_prod, card_M2])

/-- **Stress test / cross-check**: the Roe scalar character count equals the `Γ_A` count (both
`2³ = 8`) — the mod-2 abelian ledger sees no difference between the two wild relations. -/
theorem lemma_8_2_R_eq_gammaA :
    Nat.card (ContinuousMonoidHom GammaR (Multiplicative (ZMod 2)))
      = Nat.card (ContinuousMonoidHom GammaA (Multiplicative (ZMod 2))) := by
  rw [lemma_8_2_R, SectionEight.lemma_8_2_gammaA]

end GQ2

/-! ### Paper-tag ledger (Roe note `paper/roe-presentation-verification.tex`; hand-maintained)

  * eq. (1.1) = ⟦eq:defwords⟧
  * eq. (1.2) = ⟦eq:relators⟧
  * Definition 1.1 = ⟦def:GammaR⟧
  * SourceData recon rows ii.1 (t.f.g.) / ii.2 (#Hom = 8): `docs/orchestration/roe-r30-recon.md`
-/
