/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-4.8 and Fable-5
-/
import GQ2.Sanity
import GQ2.Words
import GQ2.Omega2
import GQ2.AppendixB
import GQ2.Zhat
import GQ2.DiscreteModule
import GQ2.Cohomology
import GQ2.CohomologyDevissage
import GQ2.CupProduct
import GQ2.CupSymmetry
import GQ2.FreeProfinite
import GQ2.ProfiniteQuotient
import GQ2.ProfinitePresentation
import GQ2.Tame
import GQ2.FiniteGroupLemmas
import GQ2.Subdirect
import GQ2.Reconstruction
import GQ2.Statement
import GQ2.GammaA
import GQ2.Foundations
import GQ2.Foundations.Axioms
import GQ2.Foundations.Interfaces
import GQ2.EulerCharacteristic
import GQ2.MaxProP
import GQ2.MaxProPCohomology
import GQ2.Demushkin
import GQ2.HilbertSymbol
import GQ2.DyadicSquares
import GQ2.HilbertSymbolDyadic
import GQ2.HilbertSymbolNecessity
import GQ2.HilbertSymbolSufficiency
import GQ2.HilbertSymbolDyadicClose
import GQ2.Kummer
import GQ2.Reciprocity
import GQ2.MuN
import GQ2.TateDuality
import GQ2.EvensKahn
import GQ2.KummerSurjectivity
import GQ2.Orientation
import GQ2.FinitelyGenerated
import GQ2.BoundaryFrame
import GQ2.TameQuotient
import GQ2.SectionThree
import GQ2.ProPAbelianization
import GQ2.Prop32
import GQ2.TameTwoQuotient
import GQ2.TameOrientationWitness
import GQ2.SectionThreeMarked
import GQ2.AdmissibleLimit
import GQ2.Prop23
import GQ2.FoxHeisenberg
import GQ2.FoxHeisenberg.Basic
import GQ2.FoxHeisenberg.Heisenberg
import GQ2.FoxHeisenberg.Traced
import GQ2.FoxHeisenberg.WildRow
import GQ2.FoxHeisenberg.HessianRow
import GQ2.Devissage
import GQ2.Devissage.Naturality
import GQ2.Devissage.ElemDualPack
import GQ2.Devissage.EvalPairings
import GQ2.Devissage.Chi1
import GQ2.Devissage.SelfDual
import GQ2.Devissage.LESCore
import GQ2.Devissage.LESExact
import GQ2.Devissage.LESMaster
import GQ2.Devissage.GeneratesBridge
import GQ2.QuadraticFp2
import GQ2.GaussCount
import GQ2.GaussSigns
import GQ2.GaussSignsRamified
import GQ2.TameSimple
import GQ2.Corestriction
import GQ2.OrbitData
import GQ2.Block.Module
import GQ2.SectionSix
import GQ2.HilbertLedger
import GQ2.Transgression
import GQ2.LocalLiftingDuality
import GQ2.SectionSeven
import GQ2.SectionSeven.Basic
import GQ2.SectionSeven.Decorations
import GQ2.SectionSeven.Prop74Step1
import GQ2.SectionSeven.ModuleCore
import GQ2.SectionSeven.Prop74
import GQ2.SectionEight
import GQ2.SectionEight.Fourier
import GQ2.SectionEight.Covers
import GQ2.SectionEight.ScalarCount
import GQ2.SectionEight.Partition
import GQ2.SectionEight.Recursion
import GQ2.AffineTLift
import GQ2.VCocycle
import GQ2.RadicalEdge.Bridge
import GQ2.Phase140.Obstruction
import GQ2.VLiftCount
import GQ2.KeystoneDelta
import GQ2.KeystoneDelta.AtomCalculus
import GQ2.KeystoneDelta.ThetaExtraction
import GQ2.KeystoneDelta.AffineAssembly
import GQ2.KeystoneDelta.Keystone
import GQ2.GaussZ.Reduction
import GQ2.GaussZ.Local
import GQ2.Shapiro.Deepness
import GQ2.Phase140.Assembly
import GQ2.Prop89Close
import GQ2.MStageCount
import GQ2.MStageCountGammaA
import GQ2.MStageCountGammaR
import GQ2.SectionNine
import GQ2.Block.Enrichment
import GQ2.Block.HeadDat
import GQ2.GaussZ.FinalD
import GQ2.SourceData
import GQ2.ThmFourTwo
import GQ2.DeepPart
import GQ2.DeepPart.QuadraticFp2
import GQ2.DeepPart.MuTwoPolarDual
import GQ2.DeepPart.Q0locLayer
import GQ2.DeepPart.HermitianCount
import GQ2.LocalKummer
import GQ2.RegularSummand
import GQ2.KappaNormalForm
import GQ2.HomCounting
import GQ2.UnitFiltration
import GQ2.UnitFiltrationTop
import GQ2.KummerFiltration
import GQ2.AdmissibleCount
import GQ2.DeepDuality
import GQ2.DeepDualityK
import GQ2.DeepCount
import GQ2.UnramifiedNorm
import GQ2.GaloisCosetNorm
import GQ2.UnitNormIndex
import GQ2.DimAssembly
import GQ2.DimClose
import GQ2.ResidueLift
import GQ2.UnramifiedBridge
import GQ2.CorestrictionCohomology
import GQ2.OrbitVanish
import GQ2.RegularIsometry
import GQ2.OrbitDecomp
import GQ2.Shapiro.Read
import GQ2.VanishClose
import GQ2.DetRamified
import GQ2.PropOneOne
import GQ2.ZtwoPowering
import GQ2.FrattiniCriterion
import GQ2.AnabelianBridge
import GQ2.PropOneOneAssembly
import GQ2.Shapiro.Ledger
import GQ2.WordCohBridge
import GQ2.RadicalEdge.GammaA
import GQ2.SectionTen
import GQ2.SectionTenSources
import GQ2.PresentationLiteral
import GQ2.RStage.GammaA
import GQ2.CardH2GammaA
import GQ2.Phase140.GammaA
import GQ2.QuadraticAdjoin
import GQ2.InvolutionVanish
import GQ2.InvolutionSplice
import GQ2.GaussZ.Final
import GQ2.GaussZ.CoordGammaA
import GQ2.IotaBridge
import GQ2.IotaGammaA
import GQ2.GaussZ.RelatorGammaA
import GQ2.GaussZ.FinalGammaA
import GQ2.GaussZ.GammaAD
import GQ2.RamifiedPack
import GQ2.UnramifiedQuadraticNorms
import GQ2.UnitFiltrationCounts
-- Roe-candidate verification (GQ2/Roe/, see docs/orchestration/roe-verification-plan.md)
import GQ2.Roe.Words
import GQ2.Roe.GammaR
import GQ2.Roe.AdmissibleLimit
import GQ2.Roe.Tame
import GQ2.Roe.Prop23
import GQ2.Roe.Stokes
import GQ2.Roe.OrientationRoot
import GQ2.Roe.Sanity
import GQ2.Roe.DRPresentation
import GQ2.Roe.DRAbelianization
import GQ2.Roe.CrossedDerivation
import GQ2.Roe.DRWordCoh
import GQ2.Roe.DRDemushkin
import GQ2.Roe.MarkedMatching
import GQ2.Roe.MarkedPro2
import GQ2.Roe.MaxPro2Bridge
import GQ2.Roe.FoxBasic
import GQ2.Roe.WildRow
import GQ2.Roe.NormalForms
import GQ2.Roe.Hessian
import GQ2.Roe.ChiR
import GQ2.Roe.Labute.TwoCentralTower
import GQ2.Roe.Labute.Levelwise
import GQ2.Roe.Labute.SpanFoundation
import GQ2.Roe.Labute.GradedLie.SpanIdentities
import GQ2.Roe.Labute.GradedLie.SpanStep
import GQ2.Roe.Labute.GradedLie.SpanBase
import GQ2.Roe.Labute.GradedLie.SpanAssembly
import GQ2.Roe.Labute.GradedLie.Magnus
import GQ2.Roe.Labute.StageLemma.Congruence
import GQ2.Roe.Labute.StageLemma.Defect
import GQ2.Roe.Labute.StageLemma.DigitToolkit
import GQ2.Roe.Labute.StageLemma.CrossedDerivation
import GQ2.Roe.Labute.StageLemma.StageOne
import GQ2.Roe.Labute.StageLemma.StageTwo
import GQ2.Roe.Labute.StageLemma
import GQ2.Roe.Labute.Assembly
import GQ2.Roe.Gauss
import GQ2.Roe.TrivialSelfDual
import GQ2.Roe.Devissage.TracedRows
import GQ2.Roe.Devissage.Naturality
import GQ2.Roe.Devissage.EvalPairings
import GQ2.Roe.Devissage.Chi1
import GQ2.Roe.Devissage.SelfDual
import GQ2.Roe.Devissage.LESCore
import GQ2.Roe.Devissage.LESExact
import GQ2.Roe.Devissage.LESMaster
import GQ2.Roe.Devissage.GeneratesBridge
import GQ2.Roe.Devissage
import GQ2.Roe.DevissageInduction
import GQ2.Roe.DualityAssembly
import GQ2.Roe.Supply
import GQ2.RStage.GammaR
import GQ2.WordCohBridgeR
import GQ2.Roe.CorrectionR
import GQ2.Roe.CoverLiftR
import GQ2.WordCoh2R
import GQ2.MixedBObsR
import GQ2.IotaGammaR
import GQ2.LedgerGammaR
import GQ2.HalfTorsorGammaR
import GQ2.Phase140.GammaR
import GQ2.GaussZ.KappaR
import GQ2.GaussZ.RelatorGammaR
import GQ2.GaussZ.CoordGammaR
import GQ2.GaussZ.GammaRD
import GQ2.Roe.Main

-- Dyadic campaign (general 2-adic fields) — see docs/dyadic/
import GQ2.Dyadic.Word.Blocks
import GQ2.Dyadic.Word.Syntax
import GQ2.Dyadic.Word.Eval
import GQ2.Dyadic.Word.WordCoh
import GQ2.Dyadic.Word.Fox
import GQ2.Dyadic.Word.FoxCert
import GQ2.Dyadic.Word.Stokes
import GQ2.Dyadic.Word.StokesDual
import GQ2.Dyadic.Word.Hessian
import GQ2.Dyadic.Word.Phase
import GQ2.Dyadic.Word.NpcBridge
import GQ2.Dyadic.Certificates.MpcJet
import GQ2.Dyadic.Word.Export
import GQ2.Dyadic.Branches
import GQ2.Dyadic.Words.Alphabet
import GQ2.Dyadic.Words.N0
import GQ2.Dyadic.Words.Npc
import GQ2.Dyadic.Words.M0
import GQ2.Dyadic.Words.L
import GQ2.Dyadic.Words.Mpc
import GQ2.Dyadic.SelectedWords
import GQ2.Dyadic.SelectedEta
import GQ2.Dyadic.SemanticSelected
import GQ2.Dyadic.FieldBranchSelector
import GQ2.Dyadic.RamifiedI
import GQ2.Dyadic.Certificates.N0Fox
import GQ2.Dyadic.Certificates.N0
import GQ2.Dyadic.Certificates.LFox
import GQ2.Dyadic.Certificates.M0Fox
import GQ2.Dyadic.Certificates.NpcFox
import GQ2.Dyadic.Certificates.MpcFox
import GQ2.Dyadic.Certificates.M0
import GQ2.Dyadic.Certificates.L
import GQ2.Dyadic.Certificates.Npc
import GQ2.Dyadic.Certificates.M0Assembly
import GQ2.Dyadic.Certificates.Mpc
import GQ2.Dyadic.Certificates.MpcStokes
import GQ2.Dyadic.FieldData
import GQ2.Dyadic.FieldDataEven
import GQ2.Dyadic.CertificateMain
import GQ2.Dyadic.SourceDataRN
import GQ2.Dyadic.Count.Spike
import GQ2.Dyadic.Count.Routine
import GQ2.Dyadic.Count.ProTwo
import GQ2.Dyadic.Count.Wild
import GQ2.Dyadic.Count.WildDischarge
import GQ2.Dyadic.Count.Compare
import GQ2.Dyadic.Count.RStage
import GQ2.Dyadic.Count.LocalDuality
import GQ2.Dyadic.Count.Presentation
import GQ2.Dyadic.Count.Resolve
import GQ2.Dyadic.Count.Frozen
import GQ2.Dyadic.Count.Scalar
import GQ2.Dyadic.Count.HTwo
import GQ2.Dyadic.Count.HTwoModule
import GQ2.Dyadic.Count.HTwoModuleGlobal
import GQ2.Dyadic.Count.HTwoModuleNaturality
import GQ2.Dyadic.Count.HTwoModuleHeisenberg
import GQ2.Dyadic.Count.HTwoModuleMixed
import GQ2.Dyadic.Count.HTwoModuleReflection
import GQ2.Dyadic.Count.HTwoModuleAssembly
import GQ2.Dyadic.Count.HTwoModuleFlexible
import GQ2.Dyadic.Count.HTwoModuleEquiv
import GQ2.Dyadic.Instances.KSupply
import GQ2.Dyadic.Instances.KAnalytic
import GQ2.Dyadic.Instances.QTwo
import GQ2.Dyadic.Instances.NpcCore
import GQ2.Dyadic.Instances.Cores
import GQ2.Dyadic.Instances.MpcCoreUnit
import GQ2.Dyadic.Instances.Sqrt2
import GQ2.Dyadic.Instances.Sqrt5
import GQ2.Dyadic.Instances.Sqrt10
import GQ2.Dyadic.Instances.SqrtNeg2
import GQ2.Dyadic.Instances.N0Exact
import GQ2.Dyadic.Instances.LExact
import GQ2.Dyadic.Instances.M0Exact
import GQ2.Dyadic.Instances.NpcExact
import GQ2.Dyadic.Instances.MpcExact
import GQ2.Dyadic.Instances.Fields
import GQ2.Dyadic.ResidueNormBridge
import GQ2.Dyadic.ResidueLocalFieldBridge
import GQ2.Dyadic.RamificationInertiaBridge
import GQ2.Dyadic.Instances.SqrtNeg10
import GQ2.Dyadic.LiftingDualityG
import GQ2.Dyadic.Instances.LSourceComparison
import GQ2.Dyadic.Instances.LSourceComparisonCard
import GQ2.Dyadic.Instances.LFlexibleH2
import GQ2.Dyadic.Instances.LFlexibleH2Naturality
import GQ2.Dyadic.Instances.LWordDelta
import GQ2.Dyadic.Instances.LWordExact
import GQ2.Dyadic.Instances.LDeltaComparison
import GQ2.Dyadic.Instances.LH2ComparisonDevissage
import GQ2.Dyadic.Instances.GammaLH2RightExact
import GQ2.Dyadic.Instances.GammaLAsphericityRightExact
import GQ2.Dyadic.Instances.LComparisonSquares
import GQ2.Dyadic.Instances.LSourceEulerCard
import GQ2.Dyadic.Instances.LSourceDualityAdapter
import GQ2.Dyadic.Instances.LSourceComposition
import GQ2.Dyadic.Instances.LScalarTrace
import GQ2.Dyadic.Instances.GammaLUniversalFox
import GQ2.Dyadic.Instances.LTrivialTargetFox
import GQ2.Dyadic.Instances.LHeisenbergResolver
import GQ2.Dyadic.Instances.LUniformHeisenbergResolver
import GQ2.Dyadic.Instances.LRoeStokesBridge
import GQ2.Dyadic.Instances.LRoeStokesDuality
import GQ2.Dyadic.Instances.LEvenQStokes
import GQ2.Dyadic.Instances.LRamifiedHessian
import GQ2.Dyadic.Instances.LRamifiedStokes
import GQ2.Dyadic.Instances.GammaLActionImage
import GQ2.Dyadic.Instances.GammaLSimpleSource
import GQ2.Dyadic.Instances.GammaLH2Surjectivity
import GQ2.Dyadic.Instances.GammaLSimpleDualReduction
import GQ2.Dyadic.Instances.GammaLSimpleDualSurjectivity
import GQ2.Dyadic.Count.HTwoModuleAsphericity
import GQ2.Dyadic.Count.HTwoRelationModule
import GQ2.Dyadic.Count.HTwoRelationModuleCokernel
import GQ2.Dyadic.Count.HTwoRelationModuleCokernelCounterexample
import GQ2.Dyadic.Count.HTwoRelationModuleGlobal
import GQ2.Dyadic.Count.HTwoRelationModuleRefined
import GQ2.Dyadic.Count.HTwoRelationModuleVectorwise
import GQ2.Dyadic.Count.HTwoRelationModuleInverse
import GQ2.Dyadic.Count.HTwoRelationBasis
import GQ2.Dyadic.Count.HTwoStronglyFree
import GQ2.Dyadic.Count.HTwoRelationFox
import GQ2.Dyadic.Count.HTwoFoxStronglyFree
import GQ2.Dyadic.Instances.GammaLRelatorRealization
import GQ2.Dyadic.Instances.GammaLRelatorRealizationQTwo
import GQ2.Dyadic.Instances.GammaLTateDirect
import GQ2.Dyadic.Instances.GammaLTateProviderCore
import GQ2.Dyadic.Instances.GammaLTateRightExact
import GQ2.Dyadic.Instances.GammaLScalarH2Surjectivity
import GQ2.Dyadic.Instances.GammaLSimpleDirectSurjectivity
import GQ2.Dyadic.Instances.GammaLActionImage
import GQ2.Dyadic.Instances.GammaLActionImageDevissage
import GQ2.Dyadic.Instances.GammaLAnalyticLeaves
import GQ2.Dyadic.Instances.GammaLDeterminantBridge
import GQ2.Dyadic.Instances.GammaLUnramifiedPhase
import GQ2.Dyadic.Instances.GammaLGraphHessian
import GQ2.Dyadic.Instances.GammaLGraphNormalForm
import GQ2.Dyadic.Instances.GammaLDeterminantUnramified
import GQ2.Dyadic.Instances.GammaLDeterminantRamified
import GQ2.Dyadic.Instances.GammaLRamifiedPhase
import GQ2.Dyadic.Instances.GammaLRamifiedGraphPhase
import GQ2.Dyadic.Instances.GammaLRelationModuleResolver
import GQ2.Dyadic.Instances.GammaLRelationModuleGlobal
import GQ2.Dyadic.Instances.GammaLRelationModuleRefined
import GQ2.Dyadic.Instances.GammaLRelationBasis
import GQ2.Dyadic.Instances.GammaLStronglyFree
import GQ2.Dyadic.Count.H2SplitRightExact
import GQ2.Dyadic.Count.H2SylowTransfer
import GQ2.Dyadic.Count.H2MaxProTwoTransport
import GQ2.Dyadic.Count.MaxProTwoSubgroupCriterion
import GQ2.Dyadic.Count.H2MaxProTwoInflationCriterion
import GQ2.Dyadic.Count.H2ProTwoScalarCDTwo
import GQ2.Dyadic.Count.H3OneRelatorAsphericity
import GQ2.Dyadic.Count.H3FiniteLevelFoxBoundary
import GQ2.Dyadic.Count.ContinuousCochainFiniteLevel
import GQ2.Dyadic.Count.CompletedModTwoGroupAlgebra
import GQ2.Dyadic.Count.CompletedModTwoFoxBoundary
import GQ2.Dyadic.Count.CompletedRankOneFox
import GQ2.Dyadic.Count.H3FiniteBarFoxAssembly
import GQ2.Dyadic.Count.H3CompatibleFoxInjectivity
import GQ2.Dyadic.Count.H3AugmentationFiltration
import GQ2.Dyadic.Count.H3FiniteStronglyFreeNoGo
import GQ2.Dyadic.Count.H3CompletedFoxReduction
import GQ2.Dyadic.Count.H3AugmentationSeparation
import GQ2.Dyadic.Count.H3SqRowInitialForms
import GQ2.Dyadic.Instances.GammaLSylowRightExact
import GQ2.Dyadic.Count.DemushkinCDTwoCounterexample
import GQ2.Dyadic.Instances.GammaLSylowPreimageDevissage
import GQ2.Dyadic.Instances.GammaLDirectAsphericity
import GQ2.Dyadic.Instances.GammaLImageAsphericity
import GQ2.Dyadic.Instances.GammaLDirectRegression
import GQ2.Dyadic.Instances.GammaLDualityBoundary
import GQ2.Dyadic.Instances.GammaLEulerH2Surjectivity
import GQ2.Dyadic.Instances.GammaLRealizationRoute
import GQ2.Dyadic.Instances.GammaLReconstruction
import GQ2.Dyadic.Instances.GammaLSylowPreimageProTwo
import GQ2.Dyadic.Instances.GammaLSylowPreimageSchreier
import GQ2.Dyadic.Instances.GammaLSylowPreimageInflationCriterion
import GQ2.Dyadic.GammaRHom
import GQ2.Dyadic.SourceTransport
import GQ2.Dyadic.Count.Lifts
import GQ2.Dyadic.Count.Variation
import GQ2.Dyadic.Count.Separation
import GQ2.Dyadic.GaussZ.FinalDK
import GQ2.Dyadic.Count.Separating
import GQ2.Dyadic.Count.Marking
import GQ2.Dyadic.TameQuotientK
import GQ2.Dyadic.TameBoundary
import GQ2.Dyadic.MarkedCore.Cores
import GQ2.Dyadic.MarkedCore.HandleMix
import GQ2.Dyadic.MarkedCore.HandleMixEquiv
import GQ2.Dyadic.MarkedCore.HandleMixFrame
import GQ2.Dyadic.MarkedCore.HandleMixClear
import GQ2.Dyadic.MarkedCore.HandleMixInst
import GQ2.Dyadic.MarkedCore.CoreMix
import GQ2.Dyadic.MarkedCore.ClearWide
import GQ2.Dyadic.MarkedCore.Variance
import GQ2.Dyadic.MarkedCore.CoreMixM
import GQ2.Dyadic.MarkedCore.MScaling
import GQ2.Dyadic.MarkedCore.MScalingHandles
import GQ2.Dyadic.MarkedCore.M
import GQ2.Dyadic.MarkedCore.N
import GQ2.Dyadic.MarkedCore.CoVDischarge
import GQ2.Dyadic.MarkedCore.Certificate
import GQ2.Dyadic.MarkedCore.CompactCoV
import GQ2.Dyadic.MarkedMaxProTwo
import GQ2.Dyadic.ProTwoReciprocity
import GQ2.Dyadic.PrincipalUnitTorsion
import GQ2.Dyadic.PrincipalUnitCompletion
import GQ2.Dyadic.DepthPower
import GQ2.Dyadic.MaxProTwoCohomology
import GQ2.Dyadic.MarkedRecipBundle
import GQ2.Dyadic.OrientedTameBundle
import GQ2.Dyadic.Recursion.Frame
import GQ2.Dyadic.Recursion.Numerics
import GQ2.Dyadic.Recursion.Covers
import GQ2.Dyadic.Recursion.Partition
import GQ2.Dyadic.Recursion.Recursion
import GQ2.Dyadic.Recursion.InputsRN
import GQ2.Dyadic.Recursion.Block
import GQ2.Dyadic.Recursion.PropSevenFour
import GQ2.Dyadic.Recursion.BlockFormFields
import GQ2.Dyadic.Recursion.BlockEnrichment
import GQ2.Dyadic.Recursion.BlockHeadDat
import GQ2.Dyadic.Recursion.Kappa
import GQ2.Dyadic.Recursion.Terminal
import GQ2.Dyadic.Recursion.Induction
import GQ2.Dyadic.Recursion.MStageCount
import GQ2.Dyadic.Recursion.MasterCount
import GQ2.Dyadic.Recursion.Bridge
import GQ2.Dyadic.Recursion.RStage
import GQ2.Dyadic.Recursion.BlockRStage
import GQ2.Dyadic.Recursion.Splice
import GQ2.Dyadic.Recursion.Phase140
import GQ2.Dyadic.Recursion.Phase140Assembly
import GQ2.Dyadic.Recursion.Prop89Close
import GQ2.Dyadic.Recursion.ClosedRN
import GQ2.Dyadic.SourceDataN
import GQ2.Dyadic.ThmFourTwoN
import GQ2.Dyadic.ThmFourTwoRN
import GQ2.Dyadic.CertificateSupplyRN
import GQ2.Dyadic.CertificateSupplyFamilyRN
import GQ2.Dyadic.Parameters
import GQ2.Dyadic.FinitelyGeneratedK
import GQ2.Dyadic.Projectivity
import GQ2.Dyadic.LocalGauss.EulerShapiro
import GQ2.Dyadic.LocalGauss.Q0
import GQ2.Dyadic.LocalGauss.PairingK
import GQ2.Dyadic.LocalGauss.Unramified
import GQ2.Dyadic.LocalGauss.DeepPackage
import GQ2.Dyadic.LocalGauss.OrbitVanishK
import GQ2.Dyadic.LocalGauss.ReadPerOrbitK
import GQ2.Dyadic.LocalGauss.InvolutionSpliceK
import GQ2.Dyadic.LocalGauss.VanishCloseK
import GQ2.Dyadic.LocalGauss.Ramified
import GQ2.Dyadic.LocalGauss.Main
import GQ2.Dyadic.SqCore.Cores
import GQ2.Dyadic.SqCore.InitialForm
import GQ2.Dyadic.SqCore.Rank3
import GQ2.Dyadic.SqCore.PivotLemma
import GQ2.Dyadic.SqCore.Certificate
import GQ2.Dyadic.LabuteInterface
import GQ2.Dyadic.OrientationCorrection
import GQ2.Dyadic.NpcJet.Defs
import GQ2.Dyadic.NpcJet.Omega
import GQ2.Dyadic.NpcJet.Seams
import GQ2.Dyadic.NpcJet.Main
import GQ2.Dyadic.NpcJet.Handles
import GQ2.Dyadic.Instances.GammaLFoxCounterexample
import GQ2.Dyadic.Instances.GammaLRelationCharacterVectorwise
import GQ2.Dyadic.Instances.GammaLRelationCharacterTrivialAction
import GQ2.Dyadic.Instances.GammaLScalarKernelRelationStep
import GQ2.Dyadic.Main
