/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-4.8 and Fable-5
-/
import GQ2.Dyadic.Recursion.Frame
import GQ2.Dyadic.Projectivity
import GQ2.SectionNine.Terminal

/-!
# §9 terminal-case infrastructure at the `K`-boundary (dyadic campaign, ticket SD-R2)

Clone of the **`b`-typed layer** of `GQ2/SectionNine/Terminal.lean` (879 ln), re-typed at the
general `K`-boundary `boundarySubgroupQ q nuP` with `Ttame → Tq q` and `PiBd → P` (the abstract
marked pro-2 slot, SD1 memo §2.2).

## What is reused rather than cloned (most of the model)

Boundary-free, hence consumed by import — no clone needed (SD-R1 measured 50/879 `b`-typed
lines here, and the count holds up):

* the terminal group theory: `scalarStack_centralized_of_coprime` (:44),
  `exists_normal_odd_pow_mem_of_cyclic` (:63),
  `exists_normal_odd_twoQuotient_of_cyclic_quotient` (:97), `sz_odd_complement` (:171),
  **`lemma_9_2_core` (:237)** — the Lemma 9.2 structure theorem itself;
* the fibre-product layer: `odd_subgroup_le_ker_of_expTwo` (:374), the whole **`L92` bundle**
  (:395) with `lamQ`, `fibreSub`, `toFibre`, `fibreMulEquiv` (:500), `thetaBarQ` (:507),
  `discreteTopology_Q` (:536), `mkCH` (:555);
* `precompEquiv` (:712) — pure hom-set transport, no boundary.

Seven of the model's `private` helpers are copied verbatim with a `K` suffix, because `private`
puts them out of reach (the `GQ2/Dyadic/Recursion/BlockHeadDat.lean` precedent): `lamQ_mk`
(:433), `fibreMulEquiv_apply` (:503), `thetaBarQ_mk` (:511), `piY_symm` (:541), `mk_symm`
(:548), `mkCH_apply` (:558), `lamQ_surjective` (:464).  All are one- to four-liners and
entirely boundary-free.

`ker_pro2A` (:852) is **not** cloned: it is the `Γ_A` instantiation (`prop_3_10_gammaA` and the
four marked topological generators), i.e. `ℚ₂`-side supply data, not spine.

## Parameterization delta versus the `ℚ₂` model

| model | clone | note |
|---|---|---|
| `BoundaryFrame H E` | `BoundaryFrameK q P H E` | SD-R1's frame layer |
| `boundarySubgroup` | `boundarySubgroupQ q nuP` | |
| `tameSigma`/`tameTau` | `tqSigma q`/`tqTau q` | head dichotomy at `T_q` |
| `SectionThree.gen_ttame_quotient` | `GQ2.Dyadic.gen_tq_quotient` | F3 |
| `tame_relation` | `GQ2.Dyadic.tame_rel_map_q` | F3, at `^ q` |
| `Tame.zpowers_normal_of_tame` | `tame_zpowers_normal_pow` | PJ1 leaf |
| `Tame.tame_odd_order` | `tame_odd_order_pow` (`q ≠ 0`, `Even q`) | PJ1 leaf |
| `PiBd` | `(P : ProfiniteGrp)` + `hP : IsProP 2 ↥P` | abstract slot |
| `nuTwo_surjective` | `hnuP : Function.Surjective nuP` | memo §2.2: a hypothesis of the cloned lemma, not a record field (both instantiations have it for free) |

The two `q`-hypotheses `q ≠ 0`, `Even q` enter **only** through `tame_two_nilpotentK`, i.e.
only via the head's 2-nilpotency; nothing else in the terminal lane sees the exponent.

The pro-2 layer (`pro2Iso`/`compPro2Equiv`, model :729-786) is **slot-opaque**, as the memo's
§2.2(1) predicted: it needs precisely "a pro-2 `P` with `pro2 : Γ ↠ P` whose kernel is
`proPKernel 2 Γ`", so `hP : IsProP 2 ↥P` replaces the `PiBd`-specific
`isProP_maxProPQuotient (G := profinitePresentation {piRelator})` and nothing else moves.

Plain-import (memo §5).

Axioms: none beyond std-3.  Print check performed for every declaration in this file: each
prints `[propext, Classical.choice, Quot.sound]`, equal to its model's print — hence a subset.
-/

namespace GQ2.Dyadic

open GQ2 GQ2.SectionNine

variable {H E : Type} [Group H] [TopologicalSpace H] [DiscreteTopology H] [Finite H]
  [CommGroup E] [TopologicalSpace E] [DiscreteTopology E] [Finite E]

variable {q : ℕ} {P : ProfiniteGrp} {nuP : ContinuousMonoidHom P Ztwo}

/-! ## Tame 2-nilpotency at a general residue cardinality -/

/-- **Tame 2-nilpotency at `q`** (Lemma 3.1 structural content).  Clone of
`GQ2.SectionNine.tame_two_nilpotent` (`GQ2/SectionNine/Terminal.lean:130`) with the relation at
`t ^ q`: a finite group generated by `s, t` with `s⁻¹ t s = t ^ q` (`q` even, nonzero) has a
normal subgroup of odd order with 2-group quotient.

The two swaps are PJ1's leaves (`GQ2/Dyadic/Projectivity.lean`) — `tame_zpowers_normal_pow` for
`Tame.zpowers_normal_of_tame` and `tame_odd_order_pow` for `Tame.tame_odd_order`; the
cyclic-quotient half of the proof never sees the exponent and is verbatim. -/
theorem tame_two_nilpotentK {G : Type*} [Group G] [Finite G] {s t : G} (hq0 : q ≠ 0)
    (hqe : Even q) (hgen : Subgroup.closure {s, t} = ⊤) (h : s⁻¹ * t * s = t ^ q) :
    ∃ N : Subgroup G, ∃ _ : N.Normal, Odd (Nat.card N) ∧ IsPGroup 2 (G ⧸ N) := by
  haveI hCnorm : (Subgroup.zpowers t).Normal := tame_zpowers_normal_pow hgen h
  have hCodd : Odd (Nat.card (Subgroup.zpowers t)) := by
    rw [Nat.card_zpowers]; exact tame_odd_order_pow (orderOf_pos s).ne' hq0 hqe h
  have hcyc : IsCyclic (G ⧸ Subgroup.zpowers t) := by
    set φ := QuotientGroup.mk' (Subgroup.zpowers t) with hφ
    have hsup : Subgroup.zpowers t ⊔ Subgroup.zpowers s = ⊤ := by
      rw [eq_top_iff, ← hgen, Subgroup.closure_le]
      intro x hx
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
      rcases hx with rfl | rfl
      · exact SetLike.mem_coe.2 (Subgroup.mem_sup_right (Subgroup.mem_zpowers _))
      · exact SetLike.mem_coe.2 (Subgroup.mem_sup_left (Subgroup.mem_zpowers _))
    have htmk : φ t = 1 := by
      rw [hφ, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]; exact Subgroup.mem_zpowers t
    have htop : Subgroup.zpowers (φ s) = ⊤ := by
      have hm := congrArg (Subgroup.map φ) hsup
      rwa [Subgroup.map_sup, MonoidHom.map_zpowers, MonoidHom.map_zpowers, htmk,
        Subgroup.zpowers_one_eq_bot, bot_sup_eq,
        Subgroup.map_top_of_surjective _ (QuotientGroup.mk'_surjective _)] at hm
    exact ⟨⟨φ s, fun x => htop.ge (Subgroup.mem_top x)⟩⟩
  exact exists_normal_odd_twoQuotient_of_cyclic_quotient (Subgroup.zpowers t) hCodd hcyc

/-- **The head of a `K`-boundary-framed target is 2-nilpotent.**  Clone of
`GQ2.SectionNine.head_two_nilpotent` (`GQ2/SectionNine/Terminal.lean:342`): `H` is a finite
quotient `α : T_q ↠ H`, so its marked generators generate and satisfy the `q`-th power
relation, and `tame_two_nilpotentK` applies.  This discharges the `M` hypothesis of the
(reused) `lemma_9_2_core` from the `K`-frame. -/
theorem head_two_nilpotentK (hq0 : q ≠ 0) (hqe : Even q) (F : BoundaryFrameK q P H E) :
    ∃ M : Subgroup H, ∃ _ : M.Normal, Odd (Nat.card M) ∧ IsPGroup 2 (H ⧸ M) :=
  tame_two_nilpotentK hq0 hqe
    (gen_tq_quotient F.alpha.toMonoidHom F.alpha.continuous_toFun F.alpha_surjective)
    (tame_rel_map_q F.alpha.toMonoidHom)

/-! ## The seven copied `private` helpers of `L92`

Each is the model's line-for-line; all are boundary-free and degree-blind. -/

section L92Helpers

omit [TopologicalSpace H] [DiscreteTopology H] [Finite H] [CommGroup E] [TopologicalSpace E]
  [DiscreteTopology E] [Finite E]

variable {Y : Type} [Group Y] [Finite Y] (D : L92 H Y)

/-- Copy of the `private` `L92.lamQ_mk` (`GQ2/SectionNine/Terminal.lean:433`). -/
@[simp] private theorem lamQ_mkK (y : Y) :
    D.lamQ (QuotientGroup.mk y) = QuotientGroup.mk' D.M (D.piY y) := rfl

/-- Copy of the `private` `L92.fibreMulEquiv_apply` (`Terminal.lean:503`). -/
@[simp] private theorem fibreMulEquiv_applyK (y : Y) :
    (D.fibreMulEquiv y : H × D.Q) = (D.piY y, QuotientGroup.mk y) := rfl

/-- Copy of the `private` `L92.thetaBarQ_mk` (`Terminal.lean:511`). -/
@[simp] private theorem thetaBarQ_mkK {E' : Type} [Group E'] (θ : Y →* E')
    (hE2 : ∀ e : E', e ^ 2 = 1) (y : Y) :
    D.thetaBarQ θ hE2 (QuotientGroup.mk y) = θ y := rfl

/-- Copy of the `private` `L92.piY_symm` (`Terminal.lean:541`). -/
private theorem piY_symmK (z : D.fibreSub) :
    D.piY (D.fibreMulEquiv.symm z) = (z : H × D.Q).1 := by
  have h := fibreMulEquiv_applyK D (D.fibreMulEquiv.symm z)
  rw [MulEquiv.apply_symm_apply] at h
  exact ((Prod.ext_iff.mp h).1).symm

/-- Copy of the `private` `L92.mk_symm` (`Terminal.lean:548`). -/
private theorem mk_symmK (z : D.fibreSub) :
    (QuotientGroup.mk (D.fibreMulEquiv.symm z) : D.Q) = (z : H × D.Q).2 := by
  have h := fibreMulEquiv_applyK D (D.fibreMulEquiv.symm z)
  rw [MulEquiv.apply_symm_apply] at h
  exact ((Prod.ext_iff.mp h).2).symm

/-- Copy of the `private` `L92.mkCH_apply` (`Terminal.lean:558`). -/
@[simp] private theorem mkCH_applyK [TopologicalSpace Y] (y : Y) :
    D.mkCH y = (QuotientGroup.mk y : D.Q) := rfl

/-- Copy of the `private` `L92.lamQ_surjective` (`Terminal.lean:464`). -/
private theorem lamQ_surjectiveK : Function.Surjective D.lamQ := by
  intro z
  obtain ⟨y, hy⟩ := (QuotientGroup.mk'_surjective D.M).comp D.hpi z
  exact ⟨QuotientGroup.mk y, by rw [lamQ_mkK]; exact hy⟩

end L92Helpers

/-! ## The (144) correspondence at the `K`-boundary -/

section Correspondence

open scoped Pointwise

variable {Y : Type} [Group Y] [TopologicalSpace Y] [DiscreteTopology Y] [Finite Y]
variable {Γ : Type} [Group Γ] [TopologicalSpace Γ]

/-- **The Q-count set** at the `K`-boundary.  Clone of `GQ2.SectionNine.QLifts`
(`GQ2/SectionNine/Terminal.lean:566`). -/
def QLiftsK (F : BoundaryFrameK q P H E) (T : MarkedTarget H E Y) (hE2 : ∀ e : E, e ^ 2 = 1)
    (D : L92 H Y) (b : ContinuousMonoidHom Γ ↥(boundarySubgroupQ q nuP)) : Type :=
  { g : ContSurj Γ D.Q //
    (∀ γ, D.lamQ (g.1 γ) = QuotientGroup.mk' D.M (F.alpha (b γ).val.1)) ∧
    (∀ γ, D.thetaBarQ T.thetaY hE2 (g.1 γ) = F.psiBar (b γ).val.2) }

/-- Reconstruction of a boundary lift from a Q-lift via the fibre product.  Clone of
`GQ2.SectionNine.qliftHom` (`Terminal.lean:574`). -/
noncomputable def qliftHomK (F : BoundaryFrameK q P H E) (D : L92 H Y)
    (b : ContinuousMonoidHom Γ ↥(boundarySubgroupQ q nuP)) (g : ContSurj Γ D.Q)
    (h1 : ∀ γ, D.lamQ (g.1 γ) = QuotientGroup.mk' D.M (F.alpha (b γ).val.1)) :
    ContinuousMonoidHom Γ Y where
  toMonoidHom := D.fibreMulEquiv.symm.toMonoidHom.comp
    (((F.alpha.toMonoidHom.comp ((MonoidHom.fst (Tq q) P).comp
      ((boundarySubgroupQ q nuP).subtype.comp b.toMonoidHom))).prod g.1.toMonoidHom).codRestrict
      D.fibreSub (fun γ => (h1 γ).symm))
  continuous_toFun := by
    haveI hdQ : DiscreteTopology D.Q := D.discreteTopology_Q
    haveI : DiscreteTopology (H × D.Q) := inferInstance
    haveI : DiscreteTopology D.fibreSub := inferInstance
    have hφ : Continuous fun γ : Γ =>
        (⟨(F.alpha (b γ).val.1, g.1 γ), (h1 γ).symm⟩ : D.fibreSub) :=
      Continuous.subtype_mk ((F.alpha.continuous_toFun.comp (continuous_fst.comp
        (continuous_subtype_val.comp b.continuous_toFun))).prodMk g.1.continuous_toFun) _
    exact (continuous_of_discreteTopology (f := D.fibreMulEquiv.symm)).comp hφ

@[simp] private theorem qliftHomK_piY (F : BoundaryFrameK q P H E) (D : L92 H Y)
    (b : ContinuousMonoidHom Γ ↥(boundarySubgroupQ q nuP)) (g : ContSurj Γ D.Q)
    (h1 : ∀ γ, D.lamQ (g.1 γ) = QuotientGroup.mk' D.M (F.alpha (b γ).val.1)) (γ : Γ) :
    D.piY (qliftHomK F D b g h1 γ) = F.alpha (b γ).val.1 := by
  rw [qliftHomK]
  exact piY_symmK D _

@[simp] private theorem qliftHomK_mk (F : BoundaryFrameK q P H E) (D : L92 H Y)
    (b : ContinuousMonoidHom Γ ↥(boundarySubgroupQ q nuP)) (g : ContSurj Γ D.Q)
    (h1 : ∀ γ, D.lamQ (g.1 γ) = QuotientGroup.mk' D.M (F.alpha (b γ).val.1)) (γ : Γ) :
    (QuotientGroup.mk (qliftHomK F D b g h1 γ) : D.Q) = g.1 γ := by
  rw [qliftHomK]
  exact mk_symmK D _

/-- The reconstructed lift is **surjective** (the second `coprime_fiber_product`).  Clone of
`GQ2.SectionNine.qliftHom_surjective` (`Terminal.lean:609`).

The model's appeal to `nuTwo_surjective` becomes the hypothesis `hnuP` (memo §2.2): at both
degree-`n` instantiations `nuP` is surjective for free. -/
theorem qliftHomK_surjective (F : BoundaryFrameK q P H E) (D : L92 H Y)
    (b : ContinuousMonoidHom Γ ↥(boundarySubgroupQ q nuP)) (hb : Function.Surjective b)
    (hnuP : Function.Surjective nuP) (g : ContSurj Γ D.Q)
    (h1 : ∀ γ, D.lamQ (g.1 γ) = QuotientGroup.mk' D.M (F.alpha (b γ).val.1)) :
    Function.Surjective (qliftHomK F D b g h1) := by
  haveI : Finite H := Finite.of_surjective D.piY D.hpi
  have hHsurj : Function.Surjective fun γ : Γ => F.alpha (b γ).val.1 := by
    intro h
    obtain ⟨t, ht⟩ := F.alpha_surjective h
    obtain ⟨p, hp⟩ := hnuP (nuTq q t)
    obtain ⟨γ, hγ⟩ := hb ⟨(t, p), hp.symm⟩
    refine ⟨γ, ?_⟩
    show F.alpha (b γ).val.1 = h
    rw [hγ]; exact ht
  have hcop : Nat.Coprime (Nat.card (QuotientGroup.mk' D.M).ker) (Nat.card D.lamQ.ker) := by
    rw [QuotientGroup.ker_mk']
    have hpg : IsPGroup 2 (D.lamQ.ker) := fun x => by
      obtain ⟨k, hk⟩ := D.hQ2 (x : D.Q)
      exact ⟨k, by ext1; push_cast; exact hk⟩
    obtain ⟨k, hk⟩ := hpg.exists_card_eq
    rw [hk]
    have hnd : ¬ (2 : ℕ) ∣ Nat.card D.M := by have := Nat.odd_iff.mp D.hModd; omega
    exact ((Nat.prime_two.coprime_iff_not_dvd.mpr hnd).symm).pow_right k
  set hHomM : Γ →* H := F.alpha.toMonoidHom.comp ((MonoidHom.fst (Tq q) P).comp
    ((boundarySubgroupQ q nuP).subtype.comp b.toMonoidHom)) with hHomMdef
  set J := (hHomM.prod g.1.toMonoidHom).range with hJdef
  have hJsub : ∀ p ∈ J, (QuotientGroup.mk' D.M) p.1 = D.lamQ p.2 := by
    rintro p ⟨γ, rfl⟩
    exact (h1 γ).symm
  have hJA : Function.Surjective fun p : J => (p : H × D.Q).1 := by
    intro h
    obtain ⟨γ, hγ⟩ := hHsurj h
    exact ⟨⟨(hHomM γ, g.1 γ), γ, rfl⟩, hγ⟩
  have hJB : Function.Surjective fun p : J => (p : H × D.Q).2 := by
    intro c
    obtain ⟨γ, hγ⟩ := g.2 c
    exact ⟨⟨(hHomM γ, g.1 γ), γ, rfl⟩, hγ⟩
  intro y
  have hz : (QuotientGroup.mk' D.M) (D.fibreMulEquiv y : H × D.Q).1
      = D.lamQ (D.fibreMulEquiv y : H × D.Q).2 := (D.fibreMulEquiv y).2
  obtain ⟨γ, hγ⟩ := GQ2.FiniteGroup.coprime_fiber_product (QuotientGroup.mk' D.M) D.lamQ
    (QuotientGroup.mk'_surjective _) (lamQ_surjectiveK D) hcop J hJsub hJA hJB _ hz
  refine ⟨γ, D.fibreMulEquiv.injective (Subtype.ext ?_)⟩
  rw [fibreMulEquiv_applyK, qliftHomK_piY, qliftHomK_mk]
  exact hγ

/-- **Forward map** of the (144) correspondence.  Clone of `GQ2.SectionNine.blToQ`
(`Terminal.lean:657`). -/
def blToQK (F : BoundaryFrameK q P H E) (T : MarkedTarget H E Y) (hE2 : ∀ e : E, e ^ 2 = 1)
    (D : L92 H Y) (hDpi : D.piY = T.piY)
    (b : ContinuousMonoidHom Γ ↥(boundarySubgroupQ q nuP))
    (x : BoundaryLiftsK b F T) : QLiftsK F T hE2 D b := by
  refine ⟨⟨D.mkCH.comp x.1.1, (QuotientGroup.mk'_surjective _).comp x.1.2⟩, ?_, ?_⟩
  · intro γ
    have hbl : T.piY (x.1.1 γ) = F.alpha (b γ).val.1 := congrArg Prod.fst (x.2 γ)
    show D.lamQ (D.mkCH (x.1.1 γ)) = QuotientGroup.mk' D.M (F.alpha (b γ).val.1)
    rw [mkCH_applyK, lamQ_mkK, hDpi, hbl]
  · intro γ
    have hbl : T.thetaY (x.1.1 γ) = F.psiBar (b γ).val.2 := congrArg Prod.snd (x.2 γ)
    show D.thetaBarQ T.thetaY hE2 (D.mkCH (x.1.1 γ)) = F.psiBar (b γ).val.2
    rw [mkCH_applyK, thetaBarQ_mkK, hbl]

/-- **Backward map** of the (144) correspondence.  Clone of `GQ2.SectionNine.qToBl`
(`Terminal.lean:672`). -/
noncomputable def qToBlK (F : BoundaryFrameK q P H E) (T : MarkedTarget H E Y)
    (hE2 : ∀ e : E, e ^ 2 = 1) (D : L92 H Y) (hDpi : D.piY = T.piY)
    (b : ContinuousMonoidHom Γ ↥(boundarySubgroupQ q nuP))
    (hb : Function.Surjective b) (hnuP : Function.Surjective nuP)
    (g : QLiftsK F T hE2 D b) : BoundaryLiftsK b F T := by
  refine ⟨⟨qliftHomK F D b g.1 g.2.1, qliftHomK_surjective F D b hb hnuP g.1 g.2.1⟩,
    fun γ => ?_⟩
  refine Prod.ext ?_ ?_
  · show T.piY (qliftHomK F D b g.1 g.2.1 γ) = F.alpha (b γ).val.1
    rw [← hDpi, qliftHomK_piY]
  · show T.thetaY (qliftHomK F D b g.1 g.2.1 γ) = F.psiBar (b γ).val.2
    rw [← thetaBarQ_mkK D T.thetaY hE2, qliftHomK_mk]
    exact g.2.2 γ

/-- **(A) The (144) correspondence** at the `K`-boundary (source-generic).  Clone of
`GQ2.SectionNine.boundaryLifts_equiv_qlifts` (`Terminal.lean:686`). -/
theorem boundaryLiftsK_equiv_qliftsK (F : BoundaryFrameK q P H E) (T : MarkedTarget H E Y)
    (hE2 : ∀ e : E, e ^ 2 = 1) (D : L92 H Y) (hDpi : D.piY = T.piY)
    (b : ContinuousMonoidHom Γ ↥(boundarySubgroupQ q nuP)) (hb : Function.Surjective b)
    (hnuP : Function.Surjective nuP) :
    Nat.card (BoundaryLiftsK b F T) = Nat.card (QLiftsK F T hE2 D b) := by
  apply Nat.card_congr
  refine ⟨blToQK F T hE2 D hDpi b, qToBlK F T hE2 D hDpi b hb hnuP, fun x => ?_, fun g => ?_⟩
  · -- left_inv
    apply Subtype.ext; apply Subtype.ext
    show qliftHomK F D b (blToQK F T hE2 D hDpi b x).1 (blToQK F T hE2 D hDpi b x).2.1 = x.1.1
    ext γ
    have hpi : F.alpha (b γ).val.1 = D.piY (x.1.1 γ) := by
      rw [hDpi]; exact (congrArg Prod.fst (x.2 γ)).symm
    apply D.fibreMulEquiv.injective; apply Subtype.ext
    simp only [fibreMulEquiv_applyK, qliftHomK_piY, qliftHomK_mk]
    exact Prod.ext hpi rfl
  · -- right_inv
    apply Subtype.ext; apply Subtype.ext; ext γ
    exact qliftHomK_mk F D b g.1 g.2.1 γ

end Correspondence

/-! ## Source-independence at the abstract pro-2 slot

`precompEquiv` (`Terminal.lean:712`) is boundary-free and reused by import.  Everything below
replaces `PiBd` by the abstract slot `P` and the `PiBd`-specific pro-2 witness by the
hypothesis `hP : IsProP 2 ↥P`; the proofs are otherwise verbatim. -/

section SourceIndependence

variable {Γ : Type} [Group Γ] [TopologicalSpace Γ] [IsTopologicalGroup Γ]
  [CompactSpace Γ] [T2Space Γ] [TotallyDisconnectedSpace Γ]

/-- The factoring of `pro2 : Γ ↠ P` through the maximal pro-2 quotient of `Γ`.  Clone of
`GQ2.SectionNine.pro2FactorHom` (`Terminal.lean:729`) at the abstract slot. -/
noncomputable def pro2FactorHomK (hP : IsProP 2 P) (pro2 : ContinuousMonoidHom Γ P) :
    ContinuousMonoidHom (maxProPQuotient 2 Γ) P :=
  (maxProPHomEquiv hP).symm pro2

omit [T2Space Γ] in
private theorem pro2FactorHomK_maxProPMk (hP : IsProP 2 P) (pro2 : ContinuousMonoidHom Γ P)
    (γ : Γ) : pro2FactorHomK hP pro2 (maxProPMk 2 Γ γ) = pro2 γ :=
  DFunLike.congr_fun ((maxProPHomEquiv hP).apply_symm_apply pro2) γ

/-- The maximal pro-2 quotient of `Γ` **is** the slot `P`, via a pro-2 quotient map whose kernel
is exactly `proPKernel 2 Γ`.  Clone of `GQ2.SectionNine.pro2Iso` (`Terminal.lean:741`). -/
noncomputable def pro2IsoK (hP : IsProP 2 P) (pro2 : ContinuousMonoidHom Γ P)
    (hsurj : Function.Surjective pro2) (hker : pro2.toMonoidHom.ker = proPKernel 2 Γ) :
    ContinuousMulEquiv (maxProPQuotient 2 Γ) P :=
  continuousMulEquivOfBijective (pro2FactorHomK hP pro2)
    ⟨by
        rw [injective_iff_map_eq_one]
        intro x hx
        obtain ⟨γ, rfl⟩ := quotientMk_surjective (proPKernel 2 Γ) x
        have hx' : pro2 γ = 1 := by rw [← pro2FactorHomK_maxProPMk hP pro2 γ]; exact hx
        exact (quotientMk_eq_one_iff _).mpr (hker ▸ MonoidHom.mem_ker.mpr hx'),
      fun p => by
        obtain ⟨γ, rfl⟩ := hsurj p
        exact ⟨maxProPMk 2 Γ γ, pro2FactorHomK_maxProPMk hP pro2 γ⟩⟩

omit [T2Space Γ] in
private theorem pro2IsoK_maxProPMk (hP : IsProP 2 P) (pro2 : ContinuousMonoidHom Γ P)
    (hsurj : Function.Surjective pro2) (hker : pro2.toMonoidHom.ker = proPKernel 2 Γ) (γ : Γ) :
    pro2IsoK hP pro2 hsurj hker (maxProPMk 2 Γ γ) = pro2 γ :=
  pro2FactorHomK_maxProPMk hP pro2 γ

/-- **Precomposition with the pro-2 quotient map** is a bijection of hom-sets into a pro-2
group.  Clone of `GQ2.SectionNine.compPro2Equiv` (`Terminal.lean:764`). -/
noncomputable def compPro2EquivK (hP : IsProP 2 P) (pro2 : ContinuousMonoidHom Γ P)
    (hsurj : Function.Surjective pro2) (hker : pro2.toMonoidHom.ker = proPKernel 2 Γ)
    {Q : Type} [Group Q] [TopologicalSpace Q] [IsTopologicalGroup Q] [CompactSpace Q] [T2Space Q]
    [TotallyDisconnectedSpace Q] (hQ : IsProP 2 Q) :
    ContinuousMonoidHom P Q ≃ ContinuousMonoidHom Γ Q :=
  (precompEquiv (pro2IsoK hP pro2 hsurj hker)).trans (maxProPHomEquiv hQ)

omit [T2Space Γ] in
private theorem compPro2EquivK_apply_apply (hP : IsProP 2 P) (pro2 : ContinuousMonoidHom Γ P)
    (hsurj : Function.Surjective pro2) (hker : pro2.toMonoidHom.ker = proPKernel 2 Γ)
    {Q : Type} [Group Q] [TopologicalSpace Q] [IsTopologicalGroup Q] [CompactSpace Q] [T2Space Q]
    [TotallyDisconnectedSpace Q] (hQ : IsProP 2 Q) (ψ : ContinuousMonoidHom P Q) (γ : Γ) :
    compPro2EquivK hP pro2 hsurj hker hQ ψ γ = ψ (pro2 γ) := by
  show ψ (pro2IsoK hP pro2 hsurj hker (maxProPMk 2 Γ γ)) = ψ (pro2 γ)
  rw [pro2IsoK_maxProPMk]

variable {Y : Type} [Group Y] [TopologicalSpace Y] [DiscreteTopology Y] [Finite Y]

/-- **The common Q-count set on the slot `P`** (source-free).  Clone of
`GQ2.SectionNine.CommonLifts` (`Terminal.lean:784`). -/
def CommonLiftsK (F : BoundaryFrameK q P H E) (T : MarkedTarget H E Y)
    (hE2 : ∀ e : E, e ^ 2 = 1) (D : L92 H Y) (nuP : ContinuousMonoidHom P Ztwo) : Type :=
  { g : ContSurj P D.Q //
    (∀ x : ↥(boundarySubgroupQ q nuP),
        D.lamQ (g.1 x.val.2) = QuotientGroup.mk' D.M (F.alpha x.val.1)) ∧
    (∀ π : P, D.thetaBarQ T.thetaY hE2 (g.1 π) = F.psiBar π) }

omit [T2Space Γ] in
/-- **(B) Source-independence** (per source) at the `K`-boundary.  Clone of
`GQ2.SectionNine.qlifts_equiv_commonLifts` (`Terminal.lean:794`) — verbatim, with the
`PiBd`-specific pro-2 witness replaced by `hP`. -/
theorem qliftsK_equiv_commonLiftsK (hP : IsProP 2 P) (F : BoundaryFrameK q P H E)
    (T : MarkedTarget H E Y) (hE2 : ∀ e : E, e ^ 2 = 1) (D : L92 H Y)
    (b : ContinuousMonoidHom Γ ↥(boundarySubgroupQ q nuP)) (hb : Function.Surjective b)
    (pro2 : ContinuousMonoidHom Γ P) (hpro2 : Function.Surjective pro2)
    (hbpro2 : ∀ γ, (b γ).val.2 = pro2 γ)
    (hker : pro2.toMonoidHom.ker = proPKernel 2 Γ) :
    Nat.card (QLiftsK F T hE2 D b) = Nat.card (CommonLiftsK F T hE2 D nuP) := by
  haveI hdQ : DiscreteTopology D.Q := D.discreteTopology_Q
  haveI : Finite D.Q := inferInstance
  have hQ : IsProP 2 D.Q := isProP_of_isPGroup D.hQ2
  set E' := compPro2EquivK hP pro2 hpro2 hker hQ with hE'def
  have happly : ∀ (ψ : ContinuousMonoidHom P D.Q) (γ : Γ), E' ψ γ = ψ (pro2 γ) := by
    intro ψ γ; rw [hE'def]; exact compPro2EquivK_apply_apply hP pro2 hpro2 hker hQ ψ γ
  apply Nat.card_congr
  refine ⟨fun g => ⟨⟨E'.symm g.1.1, ?_⟩, ?_, ?_⟩, fun g => ⟨⟨E' g.1.1, ?_⟩, ?_, ?_⟩, ?_, ?_⟩
  · -- toFun surjective
    intro c
    obtain ⟨γ, hγ⟩ := g.1.2 c
    exact ⟨pro2 γ, by rw [← happly (E'.symm g.1.1) γ, E'.apply_symm_apply]; exact hγ⟩
  · -- toFun H-condition (indexed by ∂bd)
    intro x
    obtain ⟨γ, hγ⟩ := hb x
    have hx1 : (E'.symm g.1.1) x.val.2 = g.1.1 γ := by
      rw [show x.val.2 = pro2 γ by rw [← hγ]; exact hbpro2 γ,
        ← happly (E'.symm g.1.1) γ, E'.apply_symm_apply]
    rw [hx1, g.2.1 γ, hγ]
  · -- toFun θ-condition (indexed by the slot)
    intro π
    obtain ⟨γ, hγ⟩ := hpro2 π
    have hπ : (E'.symm g.1.1) π = g.1.1 γ := by
      rw [← hγ, ← happly (E'.symm g.1.1) γ, E'.apply_symm_apply]
    rw [hπ, g.2.2 γ, hbpro2 γ, hγ]
  · -- invFun surjective
    intro c
    obtain ⟨π, hπ⟩ := g.1.2 c
    obtain ⟨γ, hγ⟩ := hpro2 π
    exact ⟨γ, by rw [happly g.1.1 γ, hγ]; exact hπ⟩
  · -- invFun H-condition (per γ)
    intro γ
    rw [happly g.1.1 γ]
    have h := g.2.1 (b γ)
    rw [hbpro2 γ] at h
    exact h
  · -- invFun θ-condition (per γ)
    intro γ
    rw [happly g.1.1 γ, g.2.2 (pro2 γ), hbpro2 γ]
  · -- left_inv
    intro g; apply Subtype.ext; apply Subtype.ext; exact E'.apply_symm_apply g.1.1
  · -- right_inv
    intro g; apply Subtype.ext; apply Subtype.ext; exact E'.symm_apply_apply g.1.1

end SourceIndependence

/-! ## The `n = 1` refl-bridges (memo §0, probe P1) -/

section RegressionN1

variable {Y : Type} [Group Y] [TopologicalSpace Y] [DiscreteTopology Y] [Finite Y]
variable {Γ : Type} [Group Γ] [TopologicalSpace Γ]

omit [DiscreteTopology Y] in
/-- At `n = 1` the `K`-side Q-count set **is** the model's — `rfl`. -/
theorem qLiftsK_eq (F : BoundaryFrameK 2 PiBd H E) (T : MarkedTarget H E Y)
    (hE2 : ∀ e : E, e ^ 2 = 1) (D : L92 H Y)
    (b : ContinuousMonoidHom Γ ↥(boundarySubgroupQ 2 nuTwo)) :
    QLiftsK F T hE2 D b = QLifts F.toBoundaryFrame T hE2 D b := rfl

omit [DiscreteTopology Y] in
/-- At `n = 1` the `K`-side common (source-free) count set **is** the model's — `rfl`. -/
theorem commonLiftsK_eq (F : BoundaryFrameK 2 PiBd H E) (T : MarkedTarget H E Y)
    (hE2 : ∀ e : E, e ^ 2 = 1) (D : L92 H Y) :
    CommonLiftsK F T hE2 D nuTwo = CommonLifts F.toBoundaryFrame T hE2 D := rfl

end RegressionN1

end GQ2.Dyadic
