/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-5
-/
import GQ2.Dyadic.Word.Eval
import GQ2.AdmissibleLimit
import GQ2.BoundaryFrame

/-!
# `Γ_R` as an admissible limit (dyadic campaign, ticket GR1)

The campaign's `Γ_R` is **not** the bare two-relator profinite presentation.  The governing
document (`dyadic-presentation-simplification-campaign.md` §3) is explicit:

> A candidate presentation always means an **admissible** presentation: the closed normal
> subgroup generated by the wild generators `x_i` is required to be pro-2.  **A bare two-relator
> profinite quotient is not interchangeable with this definition.**

and `docs/dyadic/plan.md` §1 states the target as

  `Γ_R = ⟨σ, τ, x₀ … x_n ∣ τ^σ = τ^{q_K}, R = 1, ⟪x₀,…,x_n⟫-closure pro-2⟩_prof`,

the pro-`2` clause being *part of the definition*.  Until this file, the Lean `GammaR` was
`profinitePresentation (gammaRelators n q R)` — the bare object — and CB-W duly proved that its
wild part is **never** pro-`2` (`Count/Wild.lean` §4), hence that `WordCertificate` was an empty
type.  That refutation is correct and is retained, retargeted to `GammaBare` below: it is the
record of why the definition had to change.

## What this file lands

* **§1–§2** the relator words and the wild letters, upstairs in `F = F(σ, τ, x₀ … x_n)`
  (moved verbatim from `TameBoundary.lean` §4, which now imports them).
* **§3** `IsAdmissibleU` — an open normal `U ≤ F` is `R`-**admissible** when the two relators
  die in `F ⧸ U` *and* the normal closure of the wild letters there is a `2`-group — and
  `N_R = ⋂ {U ∣ U admissible}`, `Γ_R = F ⧸ N_R`.  This is the dyadic transcription of the `ℚ₂`
  precedent `GQ2.NA` / `GQ2.GammaA` (`GQ2/GammaA.lean:211`), whose `IsAdmissibleU` likewise
  carries the `Marking.Pro2Core` clause.
* **§4** the limit machinery, transcribed from `GQ2/AdmissibleLimit.lean`: the family is
  nonempty (`isAdmissibleU_top`), closed under `⊓` (`isAdmissibleU_inf`, which *reuses* the
  `ℚ₂` file's generic `isPGroup_normalClosure_image_inf`), and every open normal above `N_R`
  contains an admissible one (`exists_isAdmissibleU_le`, compactness) hence is itself admissible
  (`isAdmissibleU_of_NR_le`).  The payoff is `isPGroup_two_wildNormalClosure`: **every** finite
  continuous quotient of `Γ_R` has `2`-group wild normal closure — precisely the input of CB-W's
  criterion `Count.isProP_wildPartR_iff_pro2Core`, which discharges `hwild`.
* **§5** the universal property.  `NR_le_ker_of_isOpen` / `NR_le_ker` / `gammaLift`: a
  relator-killing continuous hom out of `F` descends to `Γ_R` **iff it is admissible**, i.e. iff
  it also satisfies the wild-`2` clause.  Two clauses-for-free lemmas cover the two consumers:
  `isPGroup_map_normalClosure_of_forall_eq_one` (the tame specialization kills the wild letters)
  and `isPGroup_two_wildMap_of_isProP` (a pro-`2` target satisfies the clause automatically).
* **§6** `GammaBare` — the **old** definition, kept under its own name, together with
  `wildPartBare` and the comparison map `GammaBare ↠ Γ_R`.  `Count/Wild.lean` §1–§6 and
  `Count/Routine.lean` §6 are retargeted to it, so both refutations survive as theorems.

## ⚠ Interface note: which universal property survives

`GammaBare` satisfies the **plain** presentation property — *every* relator-killing marking of a
finite discrete group extends over it (`presentationLift`).  `Γ_R` satisfies the **restricted**
one: a relator-killing marking extends over `Γ_R` iff it *additionally* has `2`-group wild
normal closure (`NR_le_ker_of_isOpen`, and `exists_openNormal_not_admissible`-style failures are
exactly CB-W's `ℤ/3` quotients).  Any consumer asking for the plain clause — CB-1's
`IsMarkedPresentation` clause (iii) in `Count/Compare.lean` — must ask for the restricted form
at `Γ_R`.  This is a deliberate consequence of the correction, not an oversight: the plain form
is *equivalent* to the bare presentation, and the bare presentation is the object CB-W refuted.

## Axiom posture

Every declaration is `sorry`-free and introduces **no** axiom; the headline `#print axioms` are
the standard three.  `hwild` is an axiom on the *arithmetic* side (B10 / AX4) and is **not** one
here — see `Count/WildDischarge.lean`.
-/

namespace GQ2.Dyadic

open scoped Pointwise

/-! ## §0 Generic `p`-group transfer lemmas

Three one-screen facts about `Subgroup.map` and `IsPGroup` that the limit argument uses over and
over.  None mentions the alphabet; they are stated for bare groups. -/

section PGroupTransfer

variable {p : ℕ} {G H H' : Type*} [Group G] [Group H] [Group H']

/-- **Transfer along a smaller kernel.**  If `K`'s image under `f₁` is a `p`-group and `f₂` kills
everything `f₁` kills, then `K`'s image under `f₂` is a `p`-group.  This replaces the
quotient-of-a-quotient isomorphism in every step below: the two homs need not be comparable as
maps, only as kernels. -/
theorem isPGroup_map_of_ker_le {K : Subgroup G} (f₁ : G →* H) (f₂ : G →* H')
    (hker : f₁.ker ≤ f₂.ker) (h : IsPGroup p (K.map f₁)) : IsPGroup p (K.map f₂) := by
  rintro ⟨_, y, hy, rfl⟩
  obtain ⟨k, hk⟩ := h ⟨f₁ y, ⟨y, hy, rfl⟩⟩
  have h1 := congrArg Subtype.val hk
  rw [SubgroupClass.coe_pow, OneMemClass.coe_one] at h1
  refine ⟨k, Subtype.ext ?_⟩
  rw [SubgroupClass.coe_pow, OneMemClass.coe_one, ← map_pow]
  exact hker (MonoidHom.mem_ker.mpr (by rw [map_pow]; exact h1))

/-- A normal closure whose generators all die is itself killed, so its image is trivial — the
wild-`2` clause, for free, whenever the wild letters go to `1`. -/
theorem isPGroup_map_normalClosure_of_forall_eq_one {S : Set G} (f : G →* H)
    (hS : ∀ s ∈ S, f s = 1) : IsPGroup p ((Subgroup.normalClosure S).map f) := by
  have hle : Subgroup.normalClosure S ≤ f.ker :=
    Subgroup.normalClosure_le_normal fun s hs => MonoidHom.mem_ker.mpr (hS s hs)
  rintro ⟨_, y, hy, rfl⟩
  refine ⟨0, Subtype.ext ?_⟩
  rw [SubgroupClass.coe_pow, OneMemClass.coe_one, pow_zero, pow_one]
  exact MonoidHom.mem_ker.mp (hle hy)

/-- Inside a `p`-group every subgroup is a `p`-group — the wild-`2` clause, for free, whenever
the target is a `2`-group. -/
theorem isPGroup_map_of_isPGroup (hH : IsPGroup p H) (K : Subgroup G) (f : G →* H) :
    IsPGroup p (K.map f) := hH.to_subgroup _

end PGroupTransfer

/-! ## §1 The relator words

Moved verbatim from `TameBoundary.lean` §4 so that the definition of `Γ_R` can live below them.
Every statement is unchanged; downstream files see the same names in the same namespace. -/

section Relators

variable {n q : ℕ}

/-- The tautological marking of the free profinite group on the general alphabet. -/
noncomputable def freeMarking (n : ℕ) : Marking n ((FreeProfiniteGroup (Generator n)) : Type) :=
  ⟨FreeProfiniteGroup.of⟩

@[simp] theorem freeMarking_apply (n : ℕ) (g : Generator n) :
    freeMarking n g = FreeProfiniteGroup.of g := rfl

/-- The tame relator `τ^σ · (τ^q)⁻¹` on the alphabet `{σ, τ, x₀, …, x_n}`. -/
noncomputable def tameRelatorGen (n q : ℕ) : FreeProfiniteGroup (Generator n) :=
  conjP (FreeProfiniteGroup.of (Generator.tau (n := n)))
      (FreeProfiniteGroup.of (Generator.sigma (n := n)))
    * ((FreeProfiniteGroup.of (Generator.tau (n := n))) ^ q)⁻¹

/-- The relator set of `Γ_R`: the tame relation at `q` and the wild word `R`. -/
noncomputable def gammaRelators (n q : ℕ) (R : PWord (Generator n)) :
    Set (FreeProfiniteGroup (Generator n)) :=
  {tameRelatorGen n q, (freeMarking n).eval R}

/-- The wild letters `x₀, …, x_n`, upstairs in the free profinite group.  Their normal closure is
what the pro-`2` clause of the definition constrains. -/
noncomputable def wildFree (n : ℕ) : Set (FreeProfiniteGroup (Generator n)) :=
  Set.range fun i : Fin (n + 1) => FreeProfiniteGroup.of (Generator.wild i)

theorem image_wildFree {H : Type*} [Group H] (f : ((FreeProfiniteGroup (Generator n)) : Type) →* H) :
    f '' wildFree n = Set.range fun i : Fin (n + 1) => f (FreeProfiniteGroup.of (Generator.wild i)) := by
  rw [wildFree, ← Set.range_comp]
  rfl

end Relators

/-! ## §2 Admissibility

The dyadic transcription of `GQ2.IsAdmissibleU` (`GQ2/GammaA.lean:206`).  Two differences from
the `ℚ₂` original, both cosmetic:

* the `Generates` clause is dropped.  It is *automatic* for the canonical quotient `F ⧸ U`
  (density of the abstract free group in its completion — `ℚ₂`'s `generates_univMarking_map`),
  and it is used in the `ℚ₂` file only to force surjectivity in `NA_le_ker`, a role played here
  by `isPGroup_map_of_ker_le`, which needs no surjectivity at all;
* the pro-`2` clause is phrased with `Subgroup.map` rather than `normalClosure ∘ image`.  The two
  agree (`Subgroup.map_normalClosure`, quotient maps being surjective — `isAdmissibleU_iff`), and
  the `map` form composes: `map (g ∘ f) = map g ∘ map f` is what makes §0's transfer lemma
  applicable without ever building an isomorphism of quotients. -/

section Admissible

variable {n q : ℕ} {R : PWord (Generator n)}

/-- An open normal subgroup `U ≤ F` is **`R`-admissible** if the canonical finite quotient
`F ⧸ U` satisfies the two relations of `Γ_R` *and* the normal closure of the images of the wild
letters is a `2`-group.  Open normal subgroups are exactly the kernels of continuous homs to
finite discrete groups, so this encodes the class of admissible finite quotients of the packet's
`Γ_R`; `NR_le_ker` is the certificate. -/
def IsAdmissibleU (n q : ℕ) (R : PWord (Generator n))
    (U : OpenNormalSubgroup (FreeProfiniteGroup (Generator n))) : Prop :=
  (∀ r ∈ gammaRelators n q R, r ∈ U.toSubgroup) ∧
    IsPGroup 2 ((Subgroup.normalClosure (wildFree n)).map (QuotientGroup.mk' U.toSubgroup))

/-- The pro-`2` clause in the `ℚ₂` file's `Marking.Pro2Core` shape. -/
theorem isAdmissibleU_iff (U : OpenNormalSubgroup (FreeProfiniteGroup (Generator n))) :
    IsAdmissibleU n q R U ↔
      (∀ r ∈ gammaRelators n q R, r ∈ U.toSubgroup) ∧
        IsPGroup 2 (Subgroup.normalClosure
          ((QuotientGroup.mk' U.toSubgroup) '' wildFree n)) := by
  rw [IsAdmissibleU, Subgroup.map_normalClosure _ _ (QuotientGroup.mk'_surjective _)]

/-- **`N_R`**: the intersection of the kernels of all `R`-admissible finite quotients of `F`,
encoded as the intersection of all `R`-admissible open normal subgroups.  The `ℚ₂` precedent is
`GQ2.NA` (`GQ2/GammaA.lean:211`). -/
noncomputable def NR (n q : ℕ) (R : PWord (Generator n)) :
    Subgroup (FreeProfiniteGroup (Generator n)) :=
  ⨅ U : {U : OpenNormalSubgroup (FreeProfiniteGroup (Generator n)) // IsAdmissibleU n q R U},
    U.1.toSubgroup

instance NR_normal (n q : ℕ) (R : PWord (Generator n)) : (NR n q R).Normal :=
  Subgroup.normal_iInf_normal fun U => U.1.isNormal'

theorem NR_isClosed (n q : ℕ) (R : PWord (Generator n)) :
    IsClosed ((NR n q R) : Set (FreeProfiniteGroup (Generator n))) := by
  unfold NR
  rw [Subgroup.coe_iInf]
  exact isClosed_iInter fun U => U.1.toOpenSubgroup.isClosed

theorem NR_le_of_isAdmissibleU {U : OpenNormalSubgroup (FreeProfiniteGroup (Generator n))}
    (hU : IsAdmissibleU n q R U) : NR n q R ≤ U.toSubgroup :=
  iInf_le (fun V : {V : OpenNormalSubgroup (FreeProfiniteGroup (Generator n)) //
    IsAdmissibleU n q R V} => V.1.toSubgroup) ⟨U, hU⟩

end Admissible

/-! ## §3 `Γ_R`, the admissible limit -/

section GammaRDef

variable {n q : ℕ} {R : PWord (Generator n)}

/-- **`Γ_R = ⟨σ, τ, x₀, …, x_n ∣ τ^σ = τ^{q_K}, R = 1, ⟪x₀,…,x_n⟫ pro-2⟩_prof`** (plan §1,
draft eq. 1.1): the marked quotient `F ⧸ N_R` — the largest quotient of the free profinite group
on the alphabet all of whose finite quotients are `R`-admissible.

⚠ The pro-`2` clause is **part of the definition**, exactly as for `Γ_A` (`GQ2/GammaA.lean:226`).
The bare two-relator presentation is `GammaBare` (§6), and it is a *different* group: CB-W's
`Count.not_isProP_two_wildPartBare` shows its wild part is never pro-`2`. -/
noncomputable def GammaR (n q : ℕ) (R : PWord (Generator n)) : ProfiniteGrp :=
  haveI : IsClosed ((NR n q R) : Set (FreeProfiniteGroup (Generator n))) := NR_isClosed n q R
  profiniteQuotient (NR n q R)

/-- The projection `F(σ, τ, x₀, …, x_n) ↠ Γ_R`, typed at the bundled carrier. -/
noncomputable def gammaMk (n q : ℕ) (R : PWord (Generator n)) :
    ContinuousMonoidHom ((FreeProfiniteGroup (Generator n)) : Type) ((GammaR n q R) : Type) :=
  quotientMk (NR n q R)

theorem gammaMk_surjective (n q : ℕ) (R : PWord (Generator n)) :
    Function.Surjective (gammaMk n q R) := quotientMk_surjective _

theorem gammaMk_eq_one_iff {g : ((FreeProfiniteGroup (Generator n)) : Type)} :
    gammaMk n q R g = 1 ↔ g ∈ NR n q R := quotientMk_eq_one_iff _

/-- The image of a generator letter in `Γ_R`. -/
noncomputable def gammaGen (n q : ℕ) (R : PWord (Generator n)) (g : Generator n) : GammaR n q R :=
  gammaMk n q R (FreeProfiniteGroup.of g)

/-- `Γ_R` marked by its own generators. -/
noncomputable def gammaMarking (n q : ℕ) (R : PWord (Generator n)) :
    Marking n ((GammaR n q R) : Type) := ⟨gammaGen n q R⟩

@[simp] theorem gammaMarking_apply (g : Generator n) :
    gammaMarking n q R g = gammaGen n q R g := rfl

theorem gammaMarking_eq_map : gammaMarking n q R = (freeMarking n).map ⇑(gammaMk n q R) := rfl

/-- **The relators die in `Γ_R`**: every admissible `U` contains them, hence so does `N_R`. -/
theorem mem_NR_of_mem_gammaRelators {r : FreeProfiniteGroup (Generator n)}
    (hr : r ∈ gammaRelators n q R) : r ∈ NR n q R := by
  rw [NR, Subgroup.mem_iInf]
  rintro ⟨U, hU⟩
  exact hU.1 r hr

/-- The presented-group interface `relator_quotientMk_eq_one` used to supply, at the corrected
definition. -/
theorem relator_gammaMk_eq_one {r : FreeProfiniteGroup (Generator n)}
    (hr : r ∈ gammaRelators n q R) : gammaMk n q R r = 1 :=
  gammaMk_eq_one_iff.mpr (mem_NR_of_mem_gammaRelators hr)

end GammaRDef

/-! ## §4 The limit argument

`GQ2/AdmissibleLimit.lean`'s four steps, transcribed.  Step 2's arithmetic core — the subdirect
`2`-core bound — is *reused* from that file (`isPGroup_normalClosure_image_inf`); it is already
stated for an arbitrary group, set and pair of normal subgroups, so nothing about it is `ℚ₂`.

The output, `isPGroup_two_wildNormalClosure`, is the hypothesis of CB-W's
`Count.isProP_wildPartR_iff_pro2Core`. -/

section Limit

variable {n q : ℕ} {R : PWord (Generator n)}

/-- **The trivial quotient is admissible**, so the defining family is nonempty. -/
theorem isAdmissibleU_top :
    IsAdmissibleU n q R (topOpenNormalSubgroup (FreeProfiniteGroup (Generator n))) := by
  haveI : Subsingleton (FreeProfiniteGroup (Generator n) ⧸
      (topOpenNormalSubgroup (FreeProfiniteGroup (Generator n))).toSubgroup) :=
    QuotientGroup.subsingleton_quotient_top
  exact ⟨fun r _ => Subgroup.mem_top r, fun z => ⟨0, Subtype.ext (Subsingleton.elim _ _)⟩⟩

/-- **Admissibility is closed under `⊓`** — the subdirect step.  The relators die in `U ⊓ V`
because they die in each; the `2`-core clause passes by `ℚ₂`'s
`isPGroup_normalClosure_image_inf`, whose statement is already generic. -/
theorem isAdmissibleU_inf {U V : OpenNormalSubgroup (FreeProfiniteGroup (Generator n))}
    (hU : IsAdmissibleU n q R U) (hV : IsAdmissibleU n q R V) : IsAdmissibleU n q R (U ⊓ V) := by
  rw [isAdmissibleU_iff] at hU hV ⊢
  refine ⟨fun r hr => Subgroup.mem_inf.mpr ⟨hU.1 r hr, hV.1 r hr⟩, ?_⟩
  exact isPGroup_normalClosure_image_inf (wildFree n) U.toSubgroup V.toSubgroup hU.2 hV.2

/-- **Admissible domination**: every open normal subgroup above `N_R` contains an admissible one.
Compactness, exactly as in `GQ2.exists_isAdmissibleU_le`: the family `{U ∩ Wᶜ}` over admissible
`U` is directed by §4's `⊓`-closure and consists of nonempty closed subsets of the compact `F`,
so it has a common point — necessarily in `N_R ∩ Wᶜ = ∅`. -/
theorem exists_isAdmissibleU_le {W : OpenNormalSubgroup (FreeProfiniteGroup (Generator n))}
    (hle : NR n q R ≤ W.toSubgroup) :
    ∃ U : OpenNormalSubgroup (FreeProfiniteGroup (Generator n)),
      IsAdmissibleU n q R U ∧ U.toSubgroup ≤ W.toSubgroup := by
  by_contra hcon
  replace hcon : ∀ U : OpenNormalSubgroup (FreeProfiniteGroup (Generator n)),
      IsAdmissibleU n q R U → ¬ U.toSubgroup ≤ W.toSubgroup := fun U hU h => hcon ⟨U, hU, h⟩
  set ι := {U : OpenNormalSubgroup (FreeProfiniteGroup (Generator n)) // IsAdmissibleU n q R U}
    with hι
  haveI : Nonempty ι := ⟨⟨topOpenNormalSubgroup _, isAdmissibleU_top⟩⟩
  set t : ι → Set (FreeProfiniteGroup (Generator n)) :=
    fun U => (U.1 : Set (FreeProfiniteGroup (Generator n))) ∩ (W.toSubgroup : Set _)ᶜ with ht
  have htn : ∀ U, (t U).Nonempty := fun U => SetLike.not_le_iff_exists.mp (hcon U.1 U.2)
  have htcl : ∀ U, IsClosed (t U) :=
    fun U => (U.1.toOpenSubgroup.isClosed).inter W.toOpenSubgroup.isOpen.isClosed_compl
  have htc : ∀ U, IsCompact (t U) := fun U => (htcl U).isCompact
  have htd : Directed (· ⊇ ·) t := by
    intro U V
    exact ⟨⟨U.1 ⊓ V.1, isAdmissibleU_inf U.2 V.2⟩,
      Set.inter_subset_inter_left _ (SetLike.coe_subset_coe.mpr inf_le_left),
      Set.inter_subset_inter_left _ (SetLike.coe_subset_coe.mpr inf_le_right)⟩
  obtain ⟨x, hx⟩ :=
    IsCompact.nonempty_iInter_of_directed_nonempty_isCompact_isClosed t htd htn htc htcl
  rw [Set.mem_iInter] at hx
  have hxNR : x ∈ NR n q R := by
    rw [NR, Subgroup.mem_iInf]
    exact fun U => (hx U).1
  exact (hx (Classical.arbitrary ι)).2 (hle hxNR)

/-- **Every open normal subgroup above `N_R` is admissible.**  The relators pass up along the
inclusion; the `2`-core clause passes by §0's kernel transfer, `ker (mk' U) = U ≤ W = ker (mk' W)`
— which is why no isomorphism `F ⧸ U ≅ …` has to be built. -/
theorem isAdmissibleU_of_NR_le {W : OpenNormalSubgroup (FreeProfiniteGroup (Generator n))}
    (hle : NR n q R ≤ W.toSubgroup) : IsAdmissibleU n q R W := by
  obtain ⟨U, hU, hUW⟩ := exists_isAdmissibleU_le hle
  refine ⟨fun r hr => hUW (hU.1 r hr), ?_⟩
  refine isPGroup_map_of_ker_le (QuotientGroup.mk' U.toSubgroup)
    (QuotientGroup.mk' W.toSubgroup) ?_ hU.2
  rw [QuotientGroup.ker_mk', QuotientGroup.ker_mk']
  exact hUW

/-- **The admissible opens are exactly the opens above `N_R`** — the order-theoretic form of
"`Γ_R` is the largest quotient all of whose finite quotients are admissible". -/
theorem isAdmissibleU_iff_NR_le (U : OpenNormalSubgroup (FreeProfiniteGroup (Generator n))) :
    IsAdmissibleU n q R U ↔ NR n q R ≤ U.toSubgroup :=
  ⟨NR_le_of_isAdmissibleU, isAdmissibleU_of_NR_le⟩

/-- **The pro-`2` clause survives the limit, quotient by quotient.**  In *every* finite
continuous quotient of `Γ_R` the normal closure of the wild letters is a `2`-group.

This is the whole point of the redefinition, and it is exactly the right-hand side of CB-W's
criterion `Count.isProP_wildPartR_iff_pro2Core`.  The proof pulls the open normal `W ≤ Γ_R` back
to `Ŵ ≤ F`, which contains `N_R` and is therefore admissible; §0's kernel transfer then moves its
clause across `ker (mk' Ŵ) = Ŵ = ker (mk_W ∘ gammaMk)` with no quotient-of-quotient bookkeeping.
The `ℚ₂` ancestor is Steps B and E of `GQ2.isProP_wildCore`. -/
theorem isPGroup_two_wildNormalClosure (W : OpenNormalSubgroup ((GammaR n q R) : Type)) :
    IsPGroup 2 (Subgroup.normalClosure ((QuotientGroup.mk' W.toSubgroup) ''
      (Set.range fun i : Fin (n + 1) => gammaGen n q R (.wild i)))) := by
  set ρ : ((FreeProfiniteGroup (Generator n)) : Type) →* ((GammaR n q R) : Type) ⧸ W.toSubgroup :=
    (QuotientGroup.mk' W.toSubgroup).comp (gammaMk n q R).toMonoidHom with hρ
  have hsurj : Function.Surjective ρ :=
    (QuotientGroup.mk'_surjective _).comp (gammaMk_surjective n q R)
  have himg : (QuotientGroup.mk' W.toSubgroup) ''
      (Set.range fun i : Fin (n + 1) => gammaGen n q R (.wild i)) = ρ '' wildFree n := by
    rw [image_wildFree, ← Set.range_comp]
    rfl
  rw [himg, ← Subgroup.map_normalClosure _ _ hsurj]
  -- the pullback of `W`, an admissible open normal subgroup of `F`
  set Ŵ : OpenNormalSubgroup (FreeProfiniteGroup (Generator n)) :=
    { toSubgroup := Subgroup.comap (gammaMk n q R).toMonoidHom W.toSubgroup
      isOpen' := W.toOpenSubgroup.isOpen.preimage (gammaMk n q R).continuous_toFun
      isNormal' := W.isNormal'.comap _ } with hŴ
  have hNRle : NR n q R ≤ Ŵ.toSubgroup := by
    intro g hg
    show gammaMk n q R g ∈ W.toSubgroup
    rw [gammaMk_eq_one_iff.mpr hg]
    exact one_mem _
  refine isPGroup_map_of_ker_le (QuotientGroup.mk' Ŵ.toSubgroup) ρ ?_
    (isAdmissibleU_of_NR_le hNRle).2
  rw [QuotientGroup.ker_mk']
  intro x hx
  rw [hρ, MonoidHom.mem_ker, MonoidHom.comp_apply, QuotientGroup.mk'_apply,
    QuotientGroup.eq_one_iff]
  exact hx

end Limit

/-! ## §5 The universal property of `Γ_R`

A relator-killing continuous hom out of `F` descends to `Γ_R` **iff it is admissible** — i.e. iff
it also satisfies the wild-`2` clause.  This is the restricted universal property advertised in
the module docstring, and it is strictly weaker than `presentationLift`'s: CB-W's `ℤ/3` markings
kill both relators and are precisely the ones it refuses. -/

section UniversalProperty

variable {n q : ℕ} {R : PWord (Generator n)}

/-- **`N_R ≤ ker f`, primitive form.**  Any relator-killing, wild-`2` homomorphism with open
kernel is admissible, so its kernel contains `N_R`.  The `ℚ₂` ancestor is `GQ2.NA_le_ker`; no
surjectivity hypothesis is needed here because §0's transfer lemma compares kernels, not maps. -/
theorem NR_le_ker_of_isOpen {P : Type*} [Group P]
    (f : ((FreeProfiniteGroup (Generator n)) : Type) →* P)
    (hopen : IsOpen ((f.ker : Subgroup _) : Set (FreeProfiniteGroup (Generator n))))
    (hrel : ∀ r ∈ gammaRelators n q R, f r = 1)
    (hcore : IsPGroup 2 ((Subgroup.normalClosure (wildFree n)).map f)) :
    NR n q R ≤ f.ker := by
  let U : OpenNormalSubgroup (FreeProfiniteGroup (Generator n)) :=
    { toSubgroup := f.ker, isOpen' := hopen }
  have hadm : IsAdmissibleU n q R U := by
    refine ⟨fun r hr => MonoidHom.mem_ker.mpr (hrel r hr), ?_⟩
    refine isPGroup_map_of_ker_le f (QuotientGroup.mk' U.toSubgroup) ?_ hcore
    rw [QuotientGroup.ker_mk']
  exact NR_le_of_isAdmissibleU hadm

/-- **`N_R ≤ ker f`, profinite target.**  The clause is asked of every finite continuous quotient
of the target, which is what "the wild core stays pro-`2`" means there. -/
theorem NR_le_ker {Q : Type} [Group Q] [TopologicalSpace Q] [IsTopologicalGroup Q]
    [CompactSpace Q] [T2Space Q] [TotallyDisconnectedSpace Q]
    (f : ContinuousMonoidHom ((FreeProfiniteGroup (Generator n)) : Type) Q)
    (hrel : ∀ r ∈ gammaRelators n q R, f r = 1)
    (hcore : ∀ V : OpenNormalSubgroup Q, IsPGroup 2 ((Subgroup.normalClosure (wildFree n)).map
      ((QuotientGroup.mk' V.toSubgroup).comp f.toMonoidHom))) :
    NR n q R ≤ f.toMonoidHom.ker := by
  intro x hx
  rw [MonoidHom.mem_ker]
  refine eq_one_of_forall_mem_openNormalSubgroup fun V => ?_
  set g : ((FreeProfiniteGroup (Generator n)) : Type) →* Q ⧸ V.toSubgroup :=
    (QuotientGroup.mk' V.toSubgroup).comp f.toMonoidHom with hg
  have hset : ((g.ker : Subgroup _) : Set (FreeProfiniteGroup (Generator n)))
      = f ⁻¹' (V.toSubgroup : Set Q) := by
    ext y
    simp only [hg, SetLike.mem_coe, MonoidHom.mem_ker, MonoidHom.comp_apply,
      QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff, Set.mem_preimage]
    exact Iff.rfl
  have hopen : IsOpen ((g.ker : Subgroup _) : Set (FreeProfiniteGroup (Generator n))) := by
    rw [hset]
    exact V.toOpenSubgroup.isOpen.preimage f.continuous_toFun
  have hrel' : ∀ r ∈ gammaRelators n q R, g r = 1 := by
    intro r hr
    rw [hg, MonoidHom.comp_apply, show f.toMonoidHom r = 1 from hrel r hr, map_one]
  have hmem := NR_le_ker_of_isOpen g hopen hrel' (hcore V) hx
  rw [MonoidHom.mem_ker, hg, MonoidHom.comp_apply, QuotientGroup.mk'_apply,
    QuotientGroup.eq_one_iff] at hmem
  exact hmem

/-- **The clause, for free, at a wild-killing hom** — the shape the tame specialization has. -/
theorem wildMap_of_wild_eq_one {Q : Type} [Group Q] [TopologicalSpace Q] [IsTopologicalGroup Q]
    [CompactSpace Q] [T2Space Q] [TotallyDisconnectedSpace Q]
    (f : ContinuousMonoidHom ((FreeProfiniteGroup (Generator n)) : Type) Q)
    (hf : ∀ i : Fin (n + 1), f (FreeProfiniteGroup.of (Generator.wild i)) = 1)
    (V : OpenNormalSubgroup Q) :
    IsPGroup 2 ((Subgroup.normalClosure (wildFree n)).map
      ((QuotientGroup.mk' V.toSubgroup).comp f.toMonoidHom)) :=
  isPGroup_map_normalClosure_of_forall_eq_one _ <| by
    rintro _ ⟨i, rfl⟩
    rw [MonoidHom.comp_apply, show f.toMonoidHom (FreeProfiniteGroup.of (Generator.wild i)) = 1
      from hf i, map_one]

/-- **The clause, for free, at a pro-`2` target** — every subgroup of a finite `2`-group is a
`2`-group.  This is why packet Prop. 3.4(2) survives the correction verbatim. -/
theorem wildMap_of_isProP {Q : Type} [Group Q] [TopologicalSpace Q] (hQ : IsProP 2 Q)
    (f : ((FreeProfiniteGroup (Generator n)) : Type) →* Q) (V : OpenNormalSubgroup Q) :
    IsPGroup 2 ((Subgroup.normalClosure (wildFree n)).map
      ((QuotientGroup.mk' V.toSubgroup).comp f)) :=
  isPGroup_map_of_isPGroup (hQ V) _ _

/-- **Descend an admissible hom to `Γ_R`** — the replacement for `presentationLift` at the
corrected definition.  Note the third hypothesis: this is the *restricted* universal property. -/
noncomputable def gammaLift (n q : ℕ) (R : PWord (Generator n)) {Q : Type} [Group Q]
    [TopologicalSpace Q] [IsTopologicalGroup Q] [CompactSpace Q] [T2Space Q]
    [TotallyDisconnectedSpace Q] (f : ContinuousMonoidHom ((FreeProfiniteGroup (Generator n)) : Type) Q)
    (hrel : ∀ r ∈ gammaRelators n q R, f r = 1)
    (hcore : ∀ V : OpenNormalSubgroup Q, IsPGroup 2 ((Subgroup.normalClosure (wildFree n)).map
      ((QuotientGroup.mk' V.toSubgroup).comp f.toMonoidHom))) :
    ContinuousMonoidHom ((GammaR n q R) : Type) Q :=
  quotientLift (NR n q R) f (NR_le_ker f hrel hcore)

@[simp] theorem gammaLift_gammaMk (n q : ℕ) (R : PWord (Generator n)) {Q : Type} [Group Q]
    [TopologicalSpace Q] [IsTopologicalGroup Q] [CompactSpace Q] [T2Space Q]
    [TotallyDisconnectedSpace Q] (f : ContinuousMonoidHom ((FreeProfiniteGroup (Generator n)) : Type) Q)
    (hrel : ∀ r ∈ gammaRelators n q R, f r = 1)
    (hcore : ∀ V : OpenNormalSubgroup Q, IsPGroup 2 ((Subgroup.normalClosure (wildFree n)).map
      ((QuotientGroup.mk' V.toSubgroup).comp f.toMonoidHom)))
    (w : ((FreeProfiniteGroup (Generator n)) : Type)) :
    gammaLift n q R f hrel hcore (gammaMk n q R w) = f w := rfl

end UniversalProperty

/-! ## §6 `GammaBare` — the definition that was corrected

The bare two-relator profinite presentation, kept under its own name.  It is a *genuinely
different* group from `Γ_R`: `Count/Wild.lean` §4 proves that the closed normal closure of its
wild letters is never pro-`2` (send `σ, τ ↦ 1` and solve one `𝔽₃`-linear condition in `n + 1 ≥ 2`
unknowns), so it fails the admissibility clause that `Γ_R` is defined by.  CB-W's refutation and
CB-0's `R = 1` counterexample are both stated against this object, where they remain theorems. -/

section Bare

variable {n q : ℕ} {R : PWord (Generator n)}

/-- The **bare** two-relator profinite presentation `⟨σ, τ, x₀ … x_n ∣ τ^σ = τ^q, R = 1⟩_prof`,
*without* the pro-`2` clause.  This was `GammaR` before ticket GR1. -/
noncomputable def GammaBare (n q : ℕ) (R : PWord (Generator n)) : ProfiniteGrp :=
  profinitePresentation (gammaRelators n q R)

/-- The presentation projection `F ↠ Γ_R^bare`. -/
noncomputable def bareMk (n q : ℕ) (R : PWord (Generator n)) :
    ContinuousMonoidHom ((FreeProfiniteGroup (Generator n)) : Type) ((GammaBare n q R) : Type) :=
  quotientMk (relatorSubgroup (gammaRelators n q R))

theorem bareMk_surjective (n q : ℕ) (R : PWord (Generator n)) :
    Function.Surjective (bareMk n q R) := quotientMk_surjective _

/-- The image of a generator letter in the bare presentation. -/
noncomputable def bareGen (n q : ℕ) (R : PWord (Generator n)) (g : Generator n) : GammaBare n q R :=
  bareMk n q R (FreeProfiniteGroup.of g)

/-- The bare presentation marked by its own generators. -/
noncomputable def bareMarking (n q : ℕ) (R : PWord (Generator n)) :
    Marking n ((GammaBare n q R) : Type) := ⟨bareGen n q R⟩

@[simp] theorem bareMarking_apply (g : Generator n) :
    bareMarking n q R g = bareGen n q R g := rfl

theorem bareMarking_eq_map : bareMarking n q R = (freeMarking n).map ⇑(bareMk n q R) := rfl

/-- **`W_R^bare`**: the closed normal subgroup of the bare presentation generated by the wild
letters.  ⚠ It is **never** pro-`2` — `Count.not_isProP_two_wildPartBare`. -/
noncomputable def wildPartBare (n q : ℕ) (R : PWord (Generator n)) :
    Subgroup ((GammaBare n q R) : Type) :=
  (Subgroup.normalClosure
    (Set.range fun i : Fin (n + 1) => bareGen n q R (.wild i))).topologicalClosure

instance wildPartBare_normal : (wildPartBare n q R).Normal :=
  Subgroup.is_normal_topologicalClosure _

instance wildPartBare_isClosed :
    IsClosed ((wildPartBare n q R) : Set ((GammaBare n q R) : Type)) :=
  Subgroup.isClosed_topologicalClosure _

theorem bareGen_wild_mem_wildPartBare (i : Fin (n + 1)) :
    bareGen n q R (.wild i) ∈ wildPartBare n q R :=
  Subgroup.le_topologicalClosure _ (Subgroup.subset_normalClosure ⟨i, rfl⟩)

/-- The relator closure is contained in `N_R`: `N_R` is closed, normal and contains the
relators. -/
theorem relatorSubgroup_le_NR : relatorSubgroup (gammaRelators n q R) ≤ NR n q R :=
  Subgroup.topologicalClosure_minimal _
    (Subgroup.normalClosure_le_normal fun _ hr => mem_NR_of_mem_gammaRelators hr)
    (NR_isClosed n q R)

/-- **`Γ_R` is a quotient of the bare presentation** — the correction only *adds* relations. -/
noncomputable def bareToGammaR (n q : ℕ) (R : PWord (Generator n)) :
    ContinuousMonoidHom ((GammaBare n q R) : Type) ((GammaR n q R) : Type) :=
  presentationLift (gammaRelators n q R) (gammaMk n q R) fun _ hr => relator_gammaMk_eq_one hr

@[simp] theorem bareToGammaR_bareGen (g : Generator n) :
    bareToGammaR n q R (bareGen n q R g) = gammaGen n q R g := rfl

theorem bareToGammaR_surjective (n q : ℕ) (R : PWord (Generator n)) :
    Function.Surjective (bareToGammaR n q R) := by
  intro y
  obtain ⟨w, rfl⟩ := gammaMk_surjective n q R y
  exact ⟨bareMk n q R w, rfl⟩

end Bare

end GQ2.Dyadic
