/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-4.8 and Fable-5
-/
module

public import Mathlib.GroupTheory.SemidirectProduct
public import Mathlib.Order.CompletePartialOrder
public import GQ2.BoundaryFrame

@[expose] public section

/-!
# The tame quotient `T_q` at a general residue cardinality (dyadic campaign, ticket F3)

The packet's §3 opening display, at a general residue cardinality `q = q_K = 2^f`:

  `T_q = ⟨σ, τ ∣ τ^σ = τ^q⟩_prof`,   `ν₂(σ) = 1`, `ν₂(τ) = 0`.

This file is the **statement-layer leaf** of the general-`K` tame development.  Per the AX4
review (`docs/dyadic/ax4-proposal.md` §2.1, question Q4) the axiom
`orientedTameQuotientAt` mentions `Tq`, `nuTq` and `tame_relation_q` in its *type*, so those
must live in a file that `GQ2/Foundations/Axioms.lean` can import.  The leaf therefore keeps a
minimal import closure — `GQ2.BoundaryFrame` (already in `Axioms.lean`'s closure) plus two
Mathlib files — and everything that reaches higher (the `Γ_R` specializations of Prop. 3.4, the
relative-Goursat boundary theorem 3.5, the `q`-distinguishing regression) lives in
`GQ2/Dyadic/TameBoundary.lean`.

## What is here

* `tameWordQ`, `Tq`, `tqSigma`, `tqTau`, `tame_relation_q` — the presented group and its relation.
* `nuTq` — the `2`-primary unramified character, with its two generator values.
* `gen_tq_quotient` — topological generation by `σ, τ`, transported to discrete quotients (the
  `LG3` acceptance item; the `q = 2` precedent is `GQ2.SectionThree.gen_ttame_quotient`).
* `o2_Tq_eq_bot` — **packet Lemma 3.3** at general `q`: `O₂(T_q) = 1`, i.e. a normal subgroup all
  of whose finite continuous images are `2`-groups is trivial.  The proof runs through the
  general-`q` Fermat family `C_{q^{2^k}−1} ⋊ C_{2^k}` (§ below).
* `tq_two_equiv` — the `q = 2` bridge to the frozen `ℚ₂` object `Ttame`.  It is the **identity**:
  `tameWordQ 2` is syntactically `tameWord`, so `Tq 2` and `Ttame` are the same definition
  (AX4 memo risk R7 — no second copy of the `ℚ₂` tame group enters the library).

## Conventions

`x ^ g = g⁻¹ x g` (`conjP`) and `[x, y] = x⁻¹ y⁻¹ x y` (`commP`), the house conventions of
`GQ2/Words.lean`.  As at `q = 2`, the presented `σ` is **geometric** Frobenius: `tame_relation_q`
reads `σ⁻¹ τ σ = τ^q`, so `σ` is NSW (7.5.3)'s `σ⁻¹`.

## Deviation from `q = 2`: the Fermat levels are no longer centre-free

At `q = 2` the levels `C_{2^{2^k}−1} ⋊ C_{2^k}` have **trivial centre**
(`GQ2.SectionThree.fermat_central_eq_one`) and that is how normal `2`-subgroups are killed.  At
general `q` the centre is *not* trivial: an element `inl x` is central exactly when
`(q − 1) x = 0`, so the centre is cyclic of order `q − 1`.  What survives — and is all the proof
needs — is that `q − 1` is **odd** when `q` is even, so the centre has odd order and a central
`2`-element is still trivial (`fermatQ_central_pow_eq_one` below).  This is the only place where
the `q = 2` argument had to be restructured rather than transcribed.

## Duplication note

The three finite-image tame lemmas of §1 (`TameQ.odd_order`, `TameQ.zpowers_normal`,
`TameQ.normal_two_subgroup_central`) are the general-`q` forms of `GQ2.Tame`'s `q = 2` lemmas,
and the first two coincide with ticket PJ1's `GQ2.Dyadic.tame_odd_order_pow` /
`tame_zpowers_normal_pow` (`GQ2/Dyadic/Projectivity.lean`).  They are restated here in the
nested namespace `TameQ` because `Projectivity.lean` imports `GQ2.RegularSummand.Involution`,
which sits far above `GQ2/Foundations/Axioms.lean`; a leaf that must be importable *from*
`Axioms.lean` cannot reach it.  The statements are deliberately kept name-distinct so that both
files can be imported into the same environment.
-/

namespace GQ2.Dyadic

/-! ## 1. Finite-image tame lemmas at a general `q`

Packet Lemma 3.1 is a statement about *finite quotients*: in a finite group generated by a tame
pair `(s, t)` with `s⁻¹ t s = t^q`, the element `t` has order prime to `q`.  These are the
finite-image inputs used below and by the `Γ_R` side. -/

namespace TameQ

variable {G : Type*} [Group G]

/-- Iterated conjugation: `(sⁿ)⁻¹ t sⁿ = t^(qⁿ)`, from the tame relation `s⁻¹ t s = t^q`. -/
theorem conj_pow_iterate {s t : G} {q : ℕ} (h : s⁻¹ * t * s = t ^ q) :
    ∀ n : ℕ, (s ^ n)⁻¹ * t * s ^ n = t ^ (q ^ n) := by
  intro n
  induction n with
  | zero => simp
  | succ k ih =>
    have step : (s ^ (k + 1))⁻¹ * t * s ^ (k + 1)
        = (s ^ k)⁻¹ * (s⁻¹ * t * s) * s ^ k := by group
    rw [step, h]
    have conj_q : (s ^ k)⁻¹ * t ^ q * s ^ k = ((s ^ k)⁻¹ * t * s ^ k) ^ q := by
      have hc := conj_pow (a := (s ^ k)⁻¹) (b := t) (i := q)
      simpa using hc.symm
    rw [conj_q, ih, ← pow_mul, ← pow_succ]

/-- **Packet Lemma 3.1, first assertion, at general `q`.**  If `s` has finite order and
`s⁻¹ t s = t^q` with `q` even and nonzero, then `t` has odd order: conjugating by
`s^{orderOf s} = 1` gives `t^(q^k) = t`, so `orderOf t ∣ q^k − 1`, which is odd. -/
theorem odd_order {s t : G} {q : ℕ} (hs : orderOf s ≠ 0) (hq0 : q ≠ 0) (hq : Even q)
    (h : s⁻¹ * t * s = t ^ q) : Odd (orderOf t) := by
  set k := orderOf s with hk
  have hconj := conj_pow_iterate h k
  rw [pow_orderOf_eq_one] at hconj
  simp only [inv_one, one_mul, mul_one] at hconj
  have hpos : 1 ≤ q ^ k := Nat.one_le_iff_ne_zero.mpr (pow_ne_zero _ hq0)
  have hone : t ^ (q ^ k - 1) = 1 := by
    rw [← mul_left_inj t, one_mul, ← pow_succ, Nat.sub_add_cancel hpos, ← hconj]
  have hdvd : orderOf t ∣ q ^ k - 1 := orderOf_dvd_of_pow_eq_one hone
  rcases Nat.even_or_odd (orderOf t) with he | ho
  · exfalso
    have hd1 : (2 : ℕ) ∣ q ^ k - 1 := he.two_dvd.trans hdvd
    have h2q : (2 : ℕ) ∣ q ^ k := (Even.two_dvd hq).trans (dvd_pow_self q hs)
    omega
  · exact ho

/-- `⟨t^q⟩ = ⟨t⟩` when `q` is prime to `orderOf t`. -/
theorem zpowers_pow_eq_of_coprime {t : G} {q : ℕ} (hcop : Nat.Coprime q (orderOf t)) :
    Subgroup.zpowers (t ^ q) = Subgroup.zpowers t := by
  refine le_antisymm (Subgroup.zpowers_le.2 (Subgroup.pow_mem _ (Subgroup.mem_zpowers t) q))
    (Subgroup.zpowers_le.2 ?_)
  obtain ⟨m, hm⟩ := exists_pow_eq_self_of_coprime hcop
  exact Subgroup.mem_zpowers_iff.mpr ⟨(m : ℤ), by rw [zpow_natCast]; exact hm⟩

/-- **Packet Lemma 3.1, inertia normality, at general `q`.**  `⟨t⟩ ◁ ⟨s, t⟩` whenever
`s⁻¹ t s = t^q`.  No hypothesis on `q` is needed: conjugation is an automorphism, so `t ↦ t^q`
preserves the order of `t`, which already forces `gcd(q, orderOf t) = 1`. -/
theorem zpowers_normal {s t : G} [Finite G] {q : ℕ}
    (hgen : Subgroup.closure {s, t} = ⊤) (h : s⁻¹ * t * s = t ^ q) :
    (Subgroup.zpowers t).Normal := by
  have hcop : Nat.Coprime q (orderOf t) := by
    have hsc : SemiconjBy s⁻¹ t (t ^ q) := by
      show s⁻¹ * t = t ^ q * s⁻¹
      rw [← h]; group
    have hconj : orderOf t = orderOf (t ^ q) := hsc.orderOf_eq
    rw [orderOf_pow t] at hconj
    have hpos : 0 < orderOf t := orderOf_pos t
    have hgpos : 0 < Nat.gcd (orderOf t) q :=
      Nat.pos_of_ne_zero fun h0 => by rw [Nat.gcd_eq_zero_iff] at h0; omega
    have : Nat.gcd (orderOf t) q = 1 := by
      by_contra hne
      have h1 : 1 < Nat.gcd (orderOf t) q := by omega
      have hlt := Nat.div_lt_self hpos h1
      omega
    exact Nat.coprime_comm.mp this
  have hmaps : (Subgroup.zpowers t).map (MulAut.conj s⁻¹).toMonoidHom = Subgroup.zpowers t := by
    have hc : (MulAut.conj s⁻¹).toMonoidHom t = t ^ q := by
      show s⁻¹ * t * s⁻¹⁻¹ = t ^ q
      rw [inv_inv]; exact h
    rw [MonoidHom.map_zpowers, hc]; exact zpowers_pow_eq_of_coprime hcop
  have hs_norm : s ∈ Subgroup.normalizer (Subgroup.zpowers t) := by
    have hinv := Subgroup.mem_normalizer_iff_map_conj_eq.mpr hmaps
    simpa using Subgroup.inv_mem _ hinv
  have ht_norm : t ∈ Subgroup.normalizer (Subgroup.zpowers t) :=
    Subgroup.le_normalizer (Subgroup.mem_zpowers t)
  rw [← Subgroup.normalizer_eq_top_iff, eq_top_iff, ← hgen, Subgroup.closure_le]
  intro x hx
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
  rcases hx with rfl | rfl
  exacts [SetLike.mem_coe.2 hs_norm, SetLike.mem_coe.2 ht_norm]

/-- **Packet Lemma 3.1 (normal `2`-subgroups are central), at general even `q`.**  Every normal
`2`-subgroup `N` of a finite tame quotient `⟨s, t ∣ s⁻¹ t s = t^q⟩` is central.

Key idea (verbatim the `q = 2` argument of `GQ2.Tame.tame_normal_two_subgroup_central`):
`N ⊓ ⟨t⟩ = ⊥` by coprime orders, so for `n ∈ N` the commutator `⁅n, s⁆` lies in `N` (normality)
*and* in `⟨t⟩` (the quotient `G/⟨t⟩` is cyclic, hence abelian), whence `⁅n, s⁆ = 1`; with
`⁅n, t⁆ = 1` this puts `n` in the centralizer of the generators. -/
theorem normal_two_subgroup_central {s t : G} [Finite G] {q : ℕ} (hq0 : q ≠ 0) (hq : Even q)
    (hgen : Subgroup.closure {s, t} = ⊤) (h : s⁻¹ * t * s = t ^ q)
    (N : Subgroup G) [hNnorm : N.Normal] (hN : IsPGroup 2 N) :
    N ≤ Subgroup.center G := by
  haveI hCn : (Subgroup.zpowers t).Normal := zpowers_normal hgen h
  have hodd : Odd (Nat.card (Subgroup.zpowers t)) := by
    rw [Nat.card_zpowers]; exact odd_order (orderOf_pos s).ne' hq0 hq h
  have hinf : N ⊓ Subgroup.zpowers t = ⊥ := by
    obtain ⟨k, hk⟩ := hN.exists_card_eq
    have hnd : ¬ (2 : ℕ) ∣ Nat.card (Subgroup.zpowers t) := by
      have := Nat.odd_iff.mp hodd; omega
    have hcop : Nat.Coprime (Nat.card N) (Nat.card (Subgroup.zpowers t)) := by
      rw [hk]; exact ((Nat.prime_two.coprime_iff_not_dvd).mpr hnd).pow_left k
    have hd1 : Nat.card (N ⊓ Subgroup.zpowers t : Subgroup G) ∣ Nat.card N :=
      Subgroup.card_dvd_of_le inf_le_left
    have hd2 : Nat.card (N ⊓ Subgroup.zpowers t : Subgroup G) ∣ Nat.card (Subgroup.zpowers t) :=
      Subgroup.card_dvd_of_le inf_le_right
    have hcard : Nat.card (N ⊓ Subgroup.zpowers t : Subgroup G) = 1 :=
      Nat.eq_one_of_dvd_coprimes hcop hd1 hd2
    exact Subgroup.eq_bot_of_card_eq _ hcard
  have hsup : Subgroup.zpowers t ⊔ Subgroup.zpowers s = ⊤ := by
    rw [eq_top_iff, ← hgen, Subgroup.closure_le]
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with rfl | rfl
    · exact SetLike.mem_coe.2 (Subgroup.mem_sup_right (Subgroup.mem_zpowers _))
    · exact SetLike.mem_coe.2 (Subgroup.mem_sup_left (Subgroup.mem_zpowers _))
  set φ := QuotientGroup.mk' (Subgroup.zpowers t) with hφ
  have htmk : φ t = 1 := by
    rw [hφ, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]; exact Subgroup.mem_zpowers t
  have htop : Subgroup.zpowers (φ s) = ⊤ := by
    have hm := congrArg (Subgroup.map φ) hsup
    rwa [Subgroup.map_sup, MonoidHom.map_zpowers, MonoidHom.map_zpowers, htmk,
      Subgroup.zpowers_one_eq_bot, bot_sup_eq,
      Subgroup.map_top_of_surjective _ (QuotientGroup.mk'_surjective _)] at hm
  intro n hn
  have hct : Commute n t := by
    have hcN : n * t * n⁻¹ * t⁻¹ ∈ N := by
      have h1 : n * (t * n⁻¹ * t⁻¹) ∈ N := N.mul_mem hn (hNnorm.conj_mem _ (N.inv_mem hn) t)
      rwa [← mul_assoc, ← mul_assoc] at h1
    have hcT : n * t * n⁻¹ * t⁻¹ ∈ Subgroup.zpowers t :=
      Subgroup.mul_mem _ (hCn.conj_mem t (Subgroup.mem_zpowers t) n)
        (Subgroup.inv_mem _ (Subgroup.mem_zpowers t))
    exact commutatorElement_eq_one_iff_commute.mp
      (Subgroup.mem_bot.mp (hinf ▸ Subgroup.mem_inf.mpr ⟨hcN, hcT⟩))
  have hcs : Commute n s := by
    have hcN : n * s * n⁻¹ * s⁻¹ ∈ N := by
      have h1 : n * (s * n⁻¹ * s⁻¹) ∈ N := N.mul_mem hn (hNnorm.conj_mem _ (N.inv_mem hn) s)
      rwa [← mul_assoc, ← mul_assoc] at h1
    have hcomm_q : Commute (φ n) (φ s) := by
      have hmemq : φ n ∈ Subgroup.zpowers (φ s) := by rw [htop]; exact Subgroup.mem_top _
      obtain ⟨k, hk⟩ := hmemq
      rw [← hk]; exact (Commute.refl (φ s)).zpow_left k
    have hcT : n * s * n⁻¹ * s⁻¹ ∈ Subgroup.zpowers t := by
      rw [← QuotientGroup.eq_one_iff, ← QuotientGroup.mk'_apply, ← hφ,
        map_mul, map_mul, map_mul, map_inv, map_inv, hcomm_q.eq]
      group
    exact commutatorElement_eq_one_iff_commute.mp
      (Subgroup.mem_bot.mp (hinf ▸ Subgroup.mem_inf.mpr ⟨hcN, hcT⟩))
  rw [Subgroup.mem_center_iff]
  intro g
  have hg : g ∈ Subgroup.centralizer {n} := by
    have hle : Subgroup.closure ({s, t} : Set G) ≤ Subgroup.centralizer {n} := by
      rw [Subgroup.closure_le]
      intro x hx
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
      refine Subgroup.mem_centralizer_iff.mpr ?_
      rintro m hm
      rw [Set.mem_singleton_iff] at hm; subst hm
      rcases hx with rfl | rfl
      · exact hcs
      · exact hct
    exact (hgen ▸ hle) (Subgroup.mem_top g)
  exact ((Subgroup.mem_centralizer_iff.mp hg) n (Set.mem_singleton n)).symm

end TameQ

/-! ## 2. The presented group `T_q` -/

/-- The tame relator `τ^σ · (τ^q)⁻¹` in the free profinite group on `σ, τ = of 0, of 1`.
At `q = 2` this is *syntactically* `GQ2.tameWord` (`GQ2/BoundaryFrame.lean`). -/
noncomputable def tameWordQ (q : ℕ) : FreeProfiniteGroup (Fin 2) :=
  conjP (FreeProfiniteGroup.of 1) (FreeProfiniteGroup.of 0) * (FreeProfiniteGroup.of 1 ^ q)⁻¹

@[simp] theorem tameWordQ_two : tameWordQ 2 = tameWord := rfl

/-- **`T_q`** (packet §3 opening display): the profinite group `⟨σ, τ ∣ τ^σ = τ^q⟩_prof`. -/
noncomputable def Tq (q : ℕ) : ProfiniteGrp := profinitePresentation {tameWordQ q}

/-- At `q = 2` the general construction *is* the `ℚ₂` object `Ttame` — same definition, not
merely an isomorphic copy (AX4 memo risk R7). -/
@[simp] theorem Tq_two : Tq 2 = Ttame := rfl

/-- The image of `σ` in `T_q`. -/
noncomputable def tqSigma (q : ℕ) : Tq q :=
  quotientMk (relatorSubgroup {tameWordQ q}) (FreeProfiniteGroup.of 0)

/-- The image of `τ` in `T_q`. -/
noncomputable def tqTau (q : ℕ) : Tq q :=
  quotientMk (relatorSubgroup {tameWordQ q}) (FreeProfiniteGroup.of 1)

@[simp] theorem tqSigma_two : tqSigma 2 = tameSigma := rfl
@[simp] theorem tqTau_two : tqTau 2 = tameTau := rfl

/-- **The tame relation** in `T_q`: `τ^σ = τ^q` (packet §3 opening display; proved from the
presentation — no axiom).  The `q = 2` precedent is `GQ2.tame_relation`. -/
theorem tame_relation_q (q : ℕ) : conjP (tqTau q) (tqSigma q) = tqTau q ^ q := by
  have h := relator_quotientMk_eq_one {tameWordQ q} rfl
  simp only [tameWordQ, conjP] at h ⊢
  exact mul_inv_eq_one.mp h

/-- The tame relation pushed through any homomorphism out of `T_q`. -/
theorem tame_rel_map_q {q : ℕ} {H : Type*} [Group H] (f : Tq q →* H) :
    (f (tqSigma q))⁻¹ * f (tqTau q) * f (tqSigma q) = (f (tqTau q)) ^ q := by
  have h := congrArg (⇑f) (tame_relation_q q)
  simpa only [conjP, map_mul, map_inv, map_pow] using h

/-! ## 3. Topological generation

These are the general-`q` copies of `GQ2.SectionThree`'s generation toolkit
(`GQ2/Prop32.lean`), which is not available here: `Prop32.lean` imports
`GQ2/Foundations/Interfaces.lean`, above `Axioms.lean`. -/

namespace TopGen

/-- `Set.range` of a `Fin 2`-tuple is the unordered pair. -/
theorem range_fin_two {α : Type*} (v : Fin 2 → α) : Set.range v = {v 0, v 1} := by
  ext x
  simp [Fin.exists_fin_two, eq_comm]

/-- The free profinite group is topologically generated by its generators. -/
theorem freeProfiniteGroup (X : Type) :
    (Subgroup.closure (Set.range (FreeProfiniteGroup.of (X := X)))).topologicalClosure = ⊤ := by
  set g : FreeGroup X →* FreeProfiniteGroup X :=
    (ProfiniteGrp.ProfiniteCompletion.eta (GrpCat.of (FreeGroup X))).hom with hg
  have h1 : Set.range (FreeProfiniteGroup.of (X := X))
      = ⇑g '' Set.range (FreeGroup.of : X → FreeGroup X) := by
    rw [← Set.range_comp]; rfl
  have hrange : Subgroup.closure (Set.range (FreeProfiniteGroup.of (X := X))) = g.range := by
    rw [h1, ← MonoidHom.map_closure, FreeGroup.closure_range_of X, ← MonoidHom.range_eq_map]
  rw [hrange]
  have hdense : DenseRange g := ProfiniteGrp.ProfiniteCompletion.denseRange _
  rw [SetLike.ext'_iff]
  simpa only [Subgroup.topologicalClosure_coe, Subgroup.coe_top, MonoidHom.coe_range]
    using hdense.closure_range

/-- Topological generation transfers along a continuous surjective homomorphism. -/
theorem map {G H : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (f : G →* H) (hcont : Continuous f) (hsurj : Function.Surjective f) {S : Set G}
    (hS : (Subgroup.closure S).topologicalClosure = ⊤) :
    (Subgroup.closure (f '' S)).topologicalClosure = ⊤ := by
  rw [← MonoidHom.map_closure]
  exact hsurj.denseRange.topologicalClosure_map_subgroup hcont hS

/-- In a discrete (e.g. finite) group, topological generation is plain generation. -/
theorem gen_of_discrete {H : Type*} [Group H] [TopologicalSpace H]
    [IsTopologicalGroup H] [DiscreteTopology H] {S : Set H}
    (hS : (Subgroup.closure S).topologicalClosure = ⊤) :
    Subgroup.closure S = ⊤ := by
  have h1 : (Subgroup.closure S).topologicalClosure = Subgroup.closure S := by
    apply SetLike.ext'
    rw [Subgroup.topologicalClosure_coe]
    exact (isClosed_discrete _).closure_eq
  rwa [h1] at hS

/-- Two continuous homomorphisms agreeing on a topologically generating set agree everywhere. -/
theorem monoidHom_eq {G H : Type*} [Group G] [TopologicalSpace G]
    [IsTopologicalGroup G] [Group H] [TopologicalSpace H] [T2Space H] {f g : G →* H}
    (hf : Continuous f) (hg : Continuous g)
    {S : Set G} (hS : (Subgroup.closure S).topologicalClosure = ⊤)
    (h : ∀ x ∈ S, f x = g x) : ∀ x, f x = g x := by
  let E : Subgroup G :=
    { carrier := {x | f x = g x}
      one_mem' := by simp
      mul_mem' := fun ha hb => by
        simp only [Set.mem_setOf_eq] at *
        rw [map_mul, map_mul, ha, hb]
      inv_mem' := fun ha => by
        simp only [Set.mem_setOf_eq] at *
        rw [map_inv, map_inv, ha] }
  have hE : (Subgroup.closure S).topologicalClosure ≤ E :=
    Subgroup.topologicalClosure_minimal _
      ((Subgroup.closure_le E).mpr fun x hx => h x hx) (isClosed_eq hf hg)
  intro x
  exact hE (hS ▸ Subgroup.mem_top x)

/-- `closure {a, 1} = closure {a}`. -/
theorem closure_pair_one {G : Type*} [Group G] (a : G) :
    Subgroup.closure {a, (1 : G)} = Subgroup.closure {a} := by
  refine le_antisymm ((Subgroup.closure_le _).mpr ?_) (Subgroup.closure_mono ?_)
  · rintro z (rfl | rfl)
    · exact Subgroup.subset_closure (Set.mem_singleton _)
    · exact Subgroup.one_mem _
  · exact Set.singleton_subset_iff.mpr (Set.mem_insert _ _)

end TopGen

/-- `T_q` is topologically generated by `σ, τ`. -/
theorem topGen_tq (q : ℕ) :
    (Subgroup.closure {tqSigma q, tqTau q}).topologicalClosure = ⊤ := by
  have h := TopGen.map (f := (quotientMk (relatorSubgroup {tameWordQ q})).toMonoidHom)
    (quotientMk (relatorSubgroup {tameWordQ q})).continuous_toFun (quotientMk_surjective _)
    (TopGen.freeProfiniteGroup (Fin 2))
  have h1 : (⇑(quotientMk (relatorSubgroup {tameWordQ q})).toMonoidHom) ''
      Set.range (FreeProfiniteGroup.of (X := Fin 2)) = {tqSigma q, tqTau q} := by
    rw [← Set.range_comp, TopGen.range_fin_two]
    rfl
  rwa [h1] at h

/-- **Mandated export (LG3 acceptance item).**  In every discrete continuous quotient of `T_q`,
the images of `σ, τ` generate.  The `q = 2` precedent is
`GQ2.SectionThree.gen_ttame_quotient`. -/
theorem gen_tq_quotient {q : ℕ} {H : Type*} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [DiscreteTopology H] (c : Tq q →* H) (hcont : Continuous c)
    (hsurj : Function.Surjective c) :
    Subgroup.closure {c (tqSigma q), c (tqTau q)} = ⊤ := by
  have h := TopGen.map c hcont hsurj (topGen_tq q)
  rw [Set.image_insert_eq, Set.image_singleton] at h
  exact TopGen.gen_of_discrete h

/-- Two continuous homs out of `T_q` agreeing on `σ` and `τ` are equal. -/
theorem contMonoidHom_eq_of_gens {q : ℕ} {H : Type*} [Group H] [TopologicalSpace H]
    [IsTopologicalGroup H] [T2Space H] {f g : ContinuousMonoidHom (Tq q) H}
    (hσ : f (tqSigma q) = g (tqSigma q)) (hτ : f (tqTau q) = g (tqTau q)) : ∀ x, f x = g x :=
  TopGen.monoidHom_eq (f := f.toMonoidHom) (g := g.toMonoidHom) f.continuous_toFun
    g.continuous_toFun (topGen_tq q) (by rintro z (rfl | rfl) <;> assumption)

/-! ## 4. The `2`-primary unramified character `ν_t` -/

private theorem tameToZhat_of_zero' : tameToZhat (FreeProfiniteGroup.of 0) = Zhat.ofInt 1 :=
  FreeProfiniteGroup.homEquiv_symm_of _ _ _

private theorem tameToZhat_of_one' : tameToZhat (FreeProfiniteGroup.of 1) = 1 :=
  FreeProfiniteGroup.homEquiv_symm_of _ _ _

private theorem tameToZhat_tameWordQ (q : ℕ) : tameToZhat (tameWordQ q) = 1 := by
  simp only [tameWordQ, conjP, map_mul, map_inv, map_pow, tameToZhat_of_zero',
    tameToZhat_of_one']
  group

/-- **`ν_t : T_q → Z₂`** (packet §3: the `2`-primary component of the unramified character),
pinned by `ν_t(σ) = 1`, `ν_t(τ) = 0`.  At `q = 2` this is *definitionally* `GQ2.nuT`. -/
noncomputable def nuTq (q : ℕ) : ContinuousMonoidHom (Tq q) Ztwo :=
  presentationLift {tameWordQ q} ((maxProPMk 2 Zhat).comp tameToZhat) <| by
    rintro r rfl
    show maxProPMk 2 Zhat (tameToZhat (tameWordQ q)) = 1
    rw [tameToZhat_tameWordQ, map_one]

@[simp] theorem nuTq_two : nuTq 2 = nuT := rfl

@[simp] theorem nuTq_tqSigma (q : ℕ) : nuTq q (tqSigma q) = ztwoOne := by
  show maxProPMk 2 Zhat (tameToZhat (FreeProfiniteGroup.of 0)) = ztwoOne
  rw [tameToZhat_of_zero']
  rfl

@[simp] theorem nuTq_tqTau (q : ℕ) : nuTq q (tqTau q) = 1 := by
  show maxProPMk 2 Zhat (tameToZhat (FreeProfiniteGroup.of 1)) = 1
  rw [tameToZhat_of_one', map_one]

/-! ## 5. The `q = 2` bridge -/

/-- **Mandated export.**  The bridge to the frozen `ℚ₂` tame group: at `q = 2` there is nothing
to bridge — `Tq 2` and `Ttame` are the same definition, so the comparison is the identity.  This
is exactly what AX4 memo risk R7 asks for: no second copy of `T_2` enters the library, and no
`ℚ₂` capstone's axiom print can change by re-routing through `Tq 2`. -/
noncomputable def tq_two_equiv : ContinuousMulEquiv (Tq 2) Ttame := ContinuousMulEquiv.refl Ttame

@[simp] theorem tq_two_equiv_apply (x : Tq 2) : tq_two_equiv x = x := rfl

@[simp] theorem tq_two_equiv_tqSigma : tq_two_equiv (tqSigma 2) = tameSigma := rfl

@[simp] theorem tq_two_equiv_tqTau : tq_two_equiv (tqTau 2) = tameTau := rfl

@[simp] theorem nuT_tq_two_equiv (x : Tq 2) : nuT (tq_two_equiv x) = nuTq 2 x := rfl

/-! ## 6. The Fermat levels `G_{q,k} = C_{q^{2^k}−1} ⋊ C_{2^k}`

The packet's proof of Lemma 3.3 maps `T_q` onto the finite groups `C_{q^{2^k}−1} ⋊ C_{2^k}`,
where the generator of `C_{2^k}` acts by the `q`-power map.  This is well defined because *the
order of `q` modulo `q^{2^k} − 1` is exactly `2^k`*: if `0 < d < 2^k` then
`0 < q^d − 1 < q^{2^k} − 1`.

The hypothesis `2 ≤ q` is carried as a `Fact` so that the `ZMod` instances
(`NeZero (q^{2^k} − 1)`, hence `Fintype`) are found by instance search. -/

section FermatLevels

/-- `e_{q,k} = q^{2^k} − 1`, the inertia order of the `k`-th Fermat level.  At `q = 2` this is
`GQ2.SectionThree.emN`. -/
def eqN (q k : ℕ) : ℕ := q ^ 2 ^ k - 1

variable (q k : ℕ) [Fact (2 ≤ q)]

theorem two_le_q : 2 ≤ q := Fact.out

theorem two_le_q_pow : 2 ≤ q ^ 2 ^ k :=
  le_trans (two_le_q q) (Nat.le_self_pow (pow_ne_zero k two_ne_zero) q)

instance neZero_eqN : NeZero (eqN q k) := ⟨by have := two_le_q_pow q k; simp only [eqN]; omega⟩

theorem coprime_q_eqN : Nat.Coprime q (eqN q k) := by
  have h1 : Nat.gcd q (eqN q k) ∣ q ^ 2 ^ k :=
    (Nat.gcd_dvd_left _ _).trans (dvd_pow_self q (pow_ne_zero k two_ne_zero))
  have h2 : Nat.gcd q (eqN q k) ∣ q ^ 2 ^ k - 1 := Nat.gcd_dvd_right _ _
  have h3 := Nat.dvd_sub h1 h2
  have hpos := two_le_q_pow q k
  rw [show q ^ 2 ^ k - (q ^ 2 ^ k - 1) = 1 by omega] at h3
  exact Nat.dvd_one.mp h3

/-- The unit `q ∈ (ℤ/e_{q,k})ˣ` — the Frobenius action on inertia. -/
noncomputable def uq : (ZMod (eqN q k))ˣ := ZMod.unitOfCoprime q (coprime_q_eqN q k)

theorem uq_val : ((uq q k : (ZMod (eqN q k))ˣ) : ZMod (eqN q k)) = (q : ZMod (eqN q k)) := by
  rw [uq, ZMod.coe_unitOfCoprime]

theorem uq_val_pow (j : ℕ) : ((uq q k ^ j : (ZMod (eqN q k))ˣ) : ZMod (eqN q k))
    = ((q ^ j : ℕ) : ZMod (eqN q k)) := by
  rw [Units.val_pow_eq_pow_val, uq_val]
  push_cast
  rfl

theorem uq_pow_two_pow : uq q k ^ 2 ^ k = 1 := by
  have h := two_le_q_pow q k
  ext
  rw [uq_val_pow, Units.val_one,
    show (q ^ 2 ^ k : ℕ) = eqN q k + 1 from by simp only [eqN]; omega,
    Nat.cast_add, ZMod.natCast_self, Nat.cast_one, zero_add]

/-- **The order of `q` modulo `e_{q,k}` is exactly `2^k`**, in the only form needed: no smaller
power of the unit `q` is `1`.  (Packet Lemma 3.3: *"if `0 < d < 2^k`, then
`0 < q^d − 1 < q^{2^k} − 1`"*.) -/
theorem uq_pow_eq_one_iff {j : ℕ} (hj : j < 2 ^ k) (h : uq q k ^ j = 1) : j = 0 := by
  have hq := two_le_q q
  have h1 : ((q ^ j : ℕ) : ZMod (eqN q k)) = ((1 : ℕ) : ZMod (eqN q k)) := by
    have := congrArg (Units.val) h
    rw [uq_val_pow, Units.val_one] at this
    rw [this, Nat.cast_one]
  have h2 : (1 : ℕ) ≡ q ^ j [MOD eqN q k] := (ZMod.natCast_eq_natCast_iff _ _ _).mp h1.symm
  have h3 : eqN q k ∣ q ^ j - 1 :=
    (Nat.modEq_iff_dvd' (Nat.one_le_pow _ _ (by omega))).mp h2
  have h4 : q ^ j - 1 < eqN q k := by
    have hlt : q ^ j < q ^ 2 ^ k := Nat.pow_lt_pow_right (by omega) hj
    have h1j : 1 ≤ q ^ j := Nat.one_le_pow _ _ (by omega)
    simp only [eqN]
    omega
  have h5 : q ^ j - 1 = 0 := Nat.eq_zero_of_dvd_of_lt h3 h4
  have h6 : q ^ j = 1 := by
    have := Nat.one_le_pow j q (by omega)
    omega
  by_contra hj0
  exact absurd h6 (Nat.one_lt_pow hj0 (by omega)).ne'

private theorem toMultAut_apply {e : ℕ} (u : (ZMod e)ˣ) (x : Multiplicative (ZMod e)) :
    AddEquiv.toMultiplicative (DistribMulAction.toAddEquiv (ZMod e) u) x
      = Multiplicative.ofAdd (u • Multiplicative.toAdd x) := rfl

/-- Units of `ZMod e`, acting as automorphisms of the *multiplicative* cyclic group of order `e`
(the vehicle for the `q`-power action of Frobenius on inertia). -/
def unitsMulAutQ (e : ℕ) : (ZMod e)ˣ →* MulAut (Multiplicative (ZMod e)) where
  toFun u := AddEquiv.toMultiplicative (DistribMulAction.toAddEquiv (ZMod e) u)
  map_one' := by
    ext x
    rw [toMultAut_apply, one_smul, MulAut.one_apply, ofAdd_toAdd]
  map_mul' u v := by
    ext x
    rw [MulAut.mul_apply, toMultAut_apply, toMultAut_apply, toMultAut_apply]
    simp only [toAdd_ofAdd, mul_smul]

private theorem unitsMulAutQ_apply (e : ℕ) (u : (ZMod e)ˣ) (x : Multiplicative (ZMod e)) :
    unitsMulAutQ e u x = Multiplicative.ofAdd ((u : ZMod e) * x.toAdd) := rfl

/-- The character `C_{2^k} → (ℤ/e_{q,k})ˣ` sending the generator to `q⁻¹` (the *inverse*
`q`-power map, so that `s⁻¹ t s = t^q` holds with the house conjugation convention). -/
noncomputable def uCharQ : Multiplicative (ZMod (2 ^ k)) →* (ZMod (eqN q k))ˣ where
  toFun h := (uq q k)⁻¹ ^ (Multiplicative.toAdd h).val
  map_one' := by simp
  map_mul' a b := by
    have hper : ((uq q k)⁻¹) ^ 2 ^ k = 1 := by
      rw [inv_pow, uq_pow_two_pow, inv_one]
    show (uq q k)⁻¹ ^ (Multiplicative.toAdd a + Multiplicative.toAdd b).val
      = (uq q k)⁻¹ ^ (Multiplicative.toAdd a).val * (uq q k)⁻¹ ^ (Multiplicative.toAdd b).val
    rw [ZMod.val_add, ← pow_add]
    exact (pow_eq_pow_mod _ hper).symm

/-- The Frobenius action `φ_{q,k} : C_{2^k} → Aut(C_{e_{q,k}})`. -/
noncomputable def phiFermatQ :
    Multiplicative (ZMod (2 ^ k)) →* MulAut (Multiplicative (ZMod (eqN q k))) :=
  (unitsMulAutQ (eqN q k)).comp (uCharQ q k)

private theorem phiFermatQ_apply (h : Multiplicative (ZMod (2 ^ k)))
    (x : Multiplicative (ZMod (eqN q k))) :
    phiFermatQ q k h x
      = Multiplicative.ofAdd
          ((((uq q k)⁻¹ ^ (Multiplicative.toAdd h).val : (ZMod (eqN q k))ˣ) : ZMod (eqN q k))
            * Multiplicative.toAdd x) := rfl

/-- **The Fermat level** `G_{q,k} = C_{e_{q,k}} ⋊ C_{2^k}` with the (inverse-)`q`-power action.
An `abbrev`, so all `SemidirectProduct` instances apply without wrapper friction. -/
noncomputable abbrev GFermatQ :=
  SemidirectProduct (Multiplicative (ZMod (eqN q k))) (Multiplicative (ZMod (2 ^ k)))
    (phiFermatQ q k)

instance instTopGFermatQ : TopologicalSpace (GFermatQ q k) := ⊥
instance instDiscGFermatQ : DiscreteTopology (GFermatQ q k) := ⟨rfl⟩

instance instFiniteGFermatQ : Finite (GFermatQ q k) := by
  refine Finite.of_surjective
    (fun p : Multiplicative (ZMod (eqN q k)) × Multiplicative (ZMod (2 ^ k)) =>
      (⟨p.1, p.2⟩ : GFermatQ q k)) ?_
  rintro ⟨a, b⟩
  exact ⟨(a, b), rfl⟩

/-- `s ∈ G_{q,k}`: the Frobenius generator. -/
noncomputable def sFermatQ : GFermatQ q k := SemidirectProduct.inr (Multiplicative.ofAdd 1)

/-- `t ∈ G_{q,k}`: the inertia generator. -/
noncomputable def tFermatQ : GFermatQ q k := SemidirectProduct.inl (Multiplicative.ofAdd 1)

/-- `q^{v} = q` as units mod `e_{q,k}`, for `v = (1 : ℤ/2^k).val`.  Uniform in `k`: `v ≡ 1`
modulo `2^k` and the unit `q` has order dividing `2^k`.  (For `k ≥ 1` one has `v = 1` outright;
for the degenerate level `k = 0` one has `v = 0` and `e_{q,0} = q − 1`, so the identity is the
congruence `1 ≡ q (mod q − 1)`.  At `q = 2` that level was a subsingleton and needed no
argument.) -/
private theorem uq_pow_val_one : uq q k ^ ((1 : ZMod (2 ^ k))).val = uq q k := by
  have hper : uq q k ^ 2 ^ k = 1 := uq_pow_two_pow q k
  have hv : ((1 : ZMod (2 ^ k))).val ≡ 1 [MOD 2 ^ k] := by
    have hc : (((1 : ZMod (2 ^ k))).val : ZMod (2 ^ k)) = ((1 : ℕ) : ZMod (2 ^ k)) := by
      rw [ZMod.natCast_val, ZMod.cast_id, Nat.cast_one]
    exact (ZMod.natCast_eq_natCast_iff _ _ _).mp hc
  calc uq q k ^ ((1 : ZMod (2 ^ k))).val
      = uq q k ^ (((1 : ZMod (2 ^ k))).val % 2 ^ k) := pow_eq_pow_mod _ hper
    _ = uq q k ^ (1 % 2 ^ k) := by rw [hv]
    _ = uq q k ^ 1 := (pow_eq_pow_mod _ hper).symm
    _ = uq q k := pow_one _

/-- The tame relation holds in `G_{q,k}`: `s⁻¹ t s = t^q`. -/
theorem fermatQ_relation : (sFermatQ q k)⁻¹ * tFermatQ q k * sFermatQ q k = tFermatQ q k ^ q := by
  have h1 : (sFermatQ q k)⁻¹ * tFermatQ q k * sFermatQ q k
      = SemidirectProduct.inl ((phiFermatQ q k (Multiplicative.ofAdd 1))⁻¹
          (Multiplicative.ofAdd 1)) := by
    rw [SemidirectProduct.inl_aut_inv, sFermatQ, tFermatQ, map_inv]
  have h2 : (phiFermatQ q k (Multiplicative.ofAdd 1))⁻¹
      = unitsMulAutQ _ (uq q k ^ ((1 : ZMod (2 ^ k))).val) := by
    rw [phiFermatQ, MonoidHom.comp_apply]
    show (unitsMulAutQ _ ((uq q k)⁻¹ ^ ((Multiplicative.toAdd (Multiplicative.ofAdd
      (1 : ZMod (2 ^ k))))).val))⁻¹ = _
    rw [toAdd_ofAdd, ← map_inv, inv_pow, inv_inv]
  have h3 : tFermatQ q k ^ q = SemidirectProduct.inl
      (Multiplicative.ofAdd ((q : ℕ) : ZMod (eqN q k))) := by
    rw [tFermatQ, ← map_pow]
    congr 1
    rw [← ofAdd_nsmul, nsmul_eq_mul, mul_one]
  rw [h1, h2, h3, unitsMulAutQ_apply]
  congr 1
  rw [toAdd_ofAdd, mul_one, uq_pow_val_one, uq_val]

/-- `G_{q,k}` is generated by `s, t`. -/
theorem fermatQ_gen : Subgroup.closure {sFermatQ q k, tFermatQ q k} = ⊤ := by
  have hs : sFermatQ q k ∈ Subgroup.closure {sFermatQ q k, tFermatQ q k} :=
    Subgroup.subset_closure (Set.mem_insert _ _)
  have ht : tFermatQ q k ∈ Subgroup.closure {sFermatQ q k, tFermatQ q k} :=
    Subgroup.subset_closure (Set.mem_insert_of_mem _ (Set.mem_singleton _))
  rw [eq_top_iff]
  rintro ⟨a, b⟩ -
  have hzdec : (⟨a, b⟩ : GFermatQ q k)
      = SemidirectProduct.inl a * SemidirectProduct.inr b := by
    refine SemidirectProduct.ext ?_ ?_
    · show a = (SemidirectProduct.inl a * SemidirectProduct.inr b).left
      rw [SemidirectProduct.mul_left, SemidirectProduct.left_inl,
        SemidirectProduct.right_inl, map_one (phiFermatQ q k), MulAut.one_apply,
        SemidirectProduct.left_inr, mul_one]
    · show b = (SemidirectProduct.inl a * SemidirectProduct.inr b).right
      rw [SemidirectProduct.mul_right, SemidirectProduct.right_inl,
        SemidirectProduct.right_inr, one_mul]
  rw [hzdec]
  have ha2 : a = (Multiplicative.ofAdd (1 : ZMod (eqN q k))) ^ (Multiplicative.toAdd a).val := by
    have h1 : ((Multiplicative.toAdd a).val • (1 : ZMod (eqN q k))) = Multiplicative.toAdd a := by
      rw [nsmul_eq_mul, mul_one, ZMod.natCast_val, ZMod.cast_id]
    rw [← ofAdd_nsmul, h1, ofAdd_toAdd]
  have hb2 : b = (Multiplicative.ofAdd (1 : ZMod (2 ^ k))) ^ (Multiplicative.toAdd b).val := by
    have h1 : ((Multiplicative.toAdd b).val • (1 : ZMod (2 ^ k))) = Multiplicative.toAdd b := by
      rw [nsmul_eq_mul, mul_one, ZMod.natCast_val, ZMod.cast_id]
    rw [← ofAdd_nsmul, h1, ofAdd_toAdd]
  have hpowA : SemidirectProduct.inl (φ := phiFermatQ q k) a
      = tFermatQ q k ^ (Multiplicative.toAdd a).val :=
    (congrArg _ ha2).trans (map_pow _ _ _)
  have hpowB : SemidirectProduct.inr (φ := phiFermatQ q k) b
      = sFermatQ q k ^ (Multiplicative.toAdd b).val :=
    (congrArg _ hb2).trans (map_pow _ _ _)
  rw [hpowA, hpowB]
  exact mul_mem (pow_mem ht _) (pow_mem hs _)

/-- **The centre of `G_{q,k}` has exponent dividing `q − 1`.**

This is the one structural deviation from the `q = 2` development, where the centre is
*trivial* (`GQ2.SectionThree.fermat_central_eq_one`).  At general `q` an element `inl x` is
central exactly when `(q − 1)x = 0`, so the centre is cyclic of order `q − 1`; for even `q` that
order is odd, which is all the Lemma 3.3 argument needs. -/
theorem fermatQ_central_pow_eq_one {z : GFermatQ q k} (hz : z ∈ Subgroup.center (GFermatQ q k)) :
    z ^ (q - 1) = 1 := by
  have hq := two_le_q q
  rw [Subgroup.mem_center_iff] at hz
  -- (a) commuting with `t = inl (ofAdd 1)` forces the `C_{2^k}`-component to be trivial
  have hzr : z.right = 1 := by
    have hL := congrArg SemidirectProduct.left (hz (tFermatQ q k))
    simp only [SemidirectProduct.mul_left, tFermatQ, SemidirectProduct.left_inl,
      SemidirectProduct.right_inl, map_one, MulAut.one_apply] at hL
    have hfix : phiFermatQ q k z.right (Multiplicative.ofAdd 1) = Multiplicative.ofAdd 1 := by
      have h1 : z.left * phiFermatQ q k z.right (Multiplicative.ofAdd 1)
          = z.left * Multiplicative.ofAdd 1 := by
        rw [← hL, mul_comm]
      exact mul_left_cancel h1
    have hcx : (((uq q k)⁻¹ ^ (Multiplicative.toAdd z.right).val : (ZMod (eqN q k))ˣ)
          : ZMod (eqN q k)) * (1 : ZMod (eqN q k)) = (1 : ZMod (eqN q k)) := by
      have := congrArg Multiplicative.toAdd hfix
      rwa [phiFermatQ_apply, toAdd_ofAdd, toAdd_ofAdd] at this
    rw [mul_one] at hcx
    have hunit : ((uq q k)⁻¹ ^ (Multiplicative.toAdd z.right).val : (ZMod (eqN q k))ˣ) = 1 :=
      Units.ext (by rw [hcx]; rfl)
    have hpow : (uq q k) ^ (Multiplicative.toAdd z.right).val = 1 := by
      rw [inv_pow, inv_eq_one] at hunit
      exact hunit
    have hval0 : (Multiplicative.toAdd z.right).val = 0 :=
      uq_pow_eq_one_iff q k (ZMod.val_lt _) hpow
    have hz0 : Multiplicative.toAdd z.right = 0 := by
      have := congrArg (Nat.cast : ℕ → ZMod (2 ^ k)) hval0
      rwa [ZMod.natCast_val, ZMod.cast_id, Nat.cast_zero] at this
    rw [← ofAdd_toAdd z.right, hz0]
    rfl
  -- (b) commuting with `s = inr (ofAdd 1)` forces `q·x = x`, i.e. `(q − 1)·x = 0`
  have hql : (q : ZMod (eqN q k)) * Multiplicative.toAdd z.left = Multiplicative.toAdd z.left := by
    have hL := congrArg SemidirectProduct.left (hz (sFermatQ q k))
    simp only [SemidirectProduct.mul_left, sFermatQ, SemidirectProduct.left_inr,
      SemidirectProduct.right_inr, hzr, map_one, one_mul, mul_one] at hL
    have hcx : (((uq q k)⁻¹ ^ ((1 : ZMod (2 ^ k))).val : (ZMod (eqN q k))ˣ) : ZMod (eqN q k))
        * Multiplicative.toAdd z.left = Multiplicative.toAdd z.left := by
      have := congrArg Multiplicative.toAdd hL
      rwa [phiFermatQ_apply, toAdd_ofAdd, toAdd_ofAdd] at this
    calc (q : ZMod (eqN q k)) * Multiplicative.toAdd z.left
        = ((uq q k ^ ((1 : ZMod (2 ^ k))).val : (ZMod (eqN q k))ˣ) : ZMod (eqN q k))
            * Multiplicative.toAdd z.left := by rw [uq_pow_val_one, uq_val]
      _ = ((uq q k ^ ((1 : ZMod (2 ^ k))).val : (ZMod (eqN q k))ˣ) : ZMod (eqN q k))
            * ((((uq q k)⁻¹ ^ ((1 : ZMod (2 ^ k))).val : (ZMod (eqN q k))ˣ) : ZMod (eqN q k))
              * Multiplicative.toAdd z.left) := by rw [hcx]
      _ = (((uq q k ^ ((1 : ZMod (2 ^ k))).val
            * (uq q k)⁻¹ ^ ((1 : ZMod (2 ^ k))).val : (ZMod (eqN q k))ˣ)) : ZMod (eqN q k))
            * Multiplicative.toAdd z.left := by rw [Units.val_mul, mul_assoc]
      _ = Multiplicative.toAdd z.left := by
          rw [inv_pow, mul_inv_cancel]
          simp
  -- assemble: `z = inl z.left` and `z.left ^ (q − 1) = 1`
  have hzl : z = SemidirectProduct.inl z.left := by
    refine SemidirectProduct.ext ?_ ?_
    · rw [SemidirectProduct.left_inl]
    · rw [SemidirectProduct.right_inl, hzr]
  have hkill : (q - 1 : ℕ) • Multiplicative.toAdd z.left = 0 := by
    have hcast : ((q - 1 : ℕ) : ZMod (eqN q k)) = (q : ZMod (eqN q k)) - 1 := by
      rw [Nat.cast_sub (by omega), Nat.cast_one]
    rw [nsmul_eq_mul, hcast, sub_mul, one_mul, hql, sub_self]
  rw [hzl, ← map_pow, ← ofAdd_toAdd z.left, ← ofAdd_nsmul, hkill]
  show SemidirectProduct.inl (Multiplicative.ofAdd (0 : ZMod (eqN q k))) = 1
  rw [show (Multiplicative.ofAdd (0 : ZMod (eqN q k))) = 1 from rfl, map_one]

/-- The tame relator dies in `G_{q,k}` (product form, for the presentation lift). -/
theorem fermatQ_relator :
    conjP (tFermatQ q k) (sFermatQ q k) * ((tFermatQ q k) ^ q)⁻¹ = 1 := by
  have h : conjP (tFermatQ q k) (sFermatQ q k) = tFermatQ q k ^ q := fermatQ_relation q k
  rw [h, mul_inv_cancel]

/-- The classifying map `F₂ ⟶ G_{q,k}` (`σ ↦ s, τ ↦ t`). -/
noncomputable def fermatBaseQ : FreeProfiniteGroup (Fin 2) ⟶ ProfiniteGrp.of (GFermatQ q k) :=
  (FreeProfiniteGroup.homEquiv (Fin 2) (ProfiniteGrp.of (GFermatQ q k))).symm
    ![sFermatQ q k, tFermatQ q k]

@[simp] private theorem fermatBaseQ_of_zero :
    (fermatBaseQ q k).hom.toMonoidHom (FreeProfiniteGroup.of 0) = sFermatQ q k :=
  FreeProfiniteGroup.homEquiv_symm_of _ _ _

@[simp] private theorem fermatBaseQ_of_one :
    (fermatBaseQ q k).hom.toMonoidHom (FreeProfiniteGroup.of 1) = tFermatQ q k :=
  FreeProfiniteGroup.homEquiv_symm_of _ _ _

theorem fermatQ_kill : ∀ r ∈ ({tameWordQ q} : Set (FreeProfiniteGroup (Fin 2))),
    (fermatBaseQ q k).hom.toMonoidHom r = 1 := by
  intro r hr
  rcases Set.mem_singleton_iff.mp hr with rfl
  set F : FreeProfiniteGroup (Fin 2) →* GFermatQ q k := (fermatBaseQ q k).hom.toMonoidHom with hF
  have e0 : F (FreeProfiniteGroup.of 0) = sFermatQ q k := fermatBaseQ_of_zero q k
  have e1 : F (FreeProfiniteGroup.of 1) = tFermatQ q k := fermatBaseQ_of_one q k
  show F (tameWordQ q) = 1
  rw [tameWordQ]
  simp only [conjP, map_mul, map_inv, map_pow, e0, e1]
  simpa only [conjP] using fermatQ_relator q k

/-- The marked map `T_q → G_{q,k}` (`σ ↦ s, τ ↦ t`). -/
noncomputable def fermatHomQ : ContinuousMonoidHom (Tq q) (GFermatQ q k) :=
  presentationLift {tameWordQ q} (fermatBaseQ q k).hom (fermatQ_kill q k)

@[simp] private theorem fermatHomQ_tqSigma : fermatHomQ q k (tqSigma q) = sFermatQ q k :=
  (presentationLift_mk {tameWordQ q} (fermatBaseQ q k).hom (fermatQ_kill q k)
    (FreeProfiniteGroup.of 0)).trans (fermatBaseQ_of_zero q k)

@[simp] private theorem fermatHomQ_tqTau : fermatHomQ q k (tqTau q) = tFermatQ q k :=
  (presentationLift_mk {tameWordQ q} (fermatBaseQ q k).hom (fermatQ_kill q k)
    (FreeProfiniteGroup.of 1)).trans (fermatBaseQ_of_one q k)

private theorem fermatHomQ_surjective : Function.Surjective (fermatHomQ q k) := by
  have hle : Subgroup.closure {sFermatQ q k, tFermatQ q k} ≤ (fermatHomQ q k).toMonoidHom.range := by
    rw [Subgroup.closure_le]
    rintro z (rfl | rfl)
    · exact ⟨tqSigma q, fermatHomQ_tqSigma q k⟩
    · exact ⟨tqTau q, fermatHomQ_tqTau q k⟩
  intro y
  exact hle (fermatQ_gen q k ▸ Subgroup.mem_top y)

/-- An element of a `2`-group subgroup has `2`-power order. -/
private theorem exists_orderOf_eq_two_pow {H : Type*} [Group H] {K : Subgroup H}
    (hK : IsPGroup 2 K) {u : H} (hu : u ∈ K) : ∃ i : ℕ, orderOf u = 2 ^ i := by
  obtain ⟨j, hj⟩ := hK ⟨u, hu⟩
  have hj' : u ^ 2 ^ j = 1 := by
    have h1 := congrArg (fun w : K => (w : H)) hj
    simp only [SubmonoidClass.coe_pow, OneMemClass.coe_one] at h1
    exact h1
  obtain ⟨i, _, hi⟩ := (Nat.dvd_prime_pow Nat.prime_two).mp
    (orderOf_dvd_iff_pow_eq_one.mpr hj')
  exact ⟨i, hi⟩

/-- **Elements of a normal subgroup with `2`-group finite images die in every Fermat level.**
The image is a normal `2`-subgroup, hence central (`TameQ.normal_two_subgroup_central`); a
central element is killed by `q − 1`, which is odd because `q` is even, while a `2`-group
element has `2`-power order — so it is trivial. -/
theorem fermatHomQ_eq_one_of_mem (hqe : Even q) {M : Subgroup (Tq q)} [hMn : M.Normal]
    (h2 : ∀ (G : Type) [Group G] [TopologicalSpace G] [DiscreteTopology G] [Finite G]
      (f : Tq q →* G), Continuous f → IsPGroup 2 (M.map f))
    {x : Tq q} (hx : x ∈ M) : fermatHomQ q k x = 1 := by
  have hq := two_le_q q
  haveI hNmap : (M.map (fermatHomQ q k).toMonoidHom).Normal :=
    Subgroup.Normal.map hMn _ (fermatHomQ_surjective q k)
  have hp2 : IsPGroup 2 (M.map (fermatHomQ q k).toMonoidHom) :=
    h2 _ _ (fermatHomQ q k).continuous_toFun
  have hcent := TameQ.normal_two_subgroup_central (by omega) hqe (fermatQ_gen q k)
    (fermatQ_relation q k) (M.map (fermatHomQ q k).toMonoidHom) hp2
  set z := fermatHomQ q k x with hzdef
  have hzmem : z ∈ M.map (fermatHomQ q k).toMonoidHom := Subgroup.mem_map.mpr ⟨x, hx, rfl⟩
  -- odd order from centrality
  have hodd : orderOf z ∣ q - 1 :=
    orderOf_dvd_of_pow_eq_one (fermatQ_central_pow_eq_one q k (hcent hzmem))
  -- 2-power order from the 2-group hypothesis
  obtain ⟨i, hi⟩ := exists_orderOf_eq_two_pow hp2 hzmem
  have hq1odd : ¬ (2 : ℕ) ∣ (q - 1) := by
    obtain ⟨c, hc⟩ := hqe
    omega
  have : orderOf z = 1 := by
    rcases Nat.eq_zero_or_pos i with rfl | hipos
    · rwa [pow_zero] at hi
    · exact absurd (dvd_trans (by rw [hi]; exact dvd_pow_self 2 hipos.ne') hodd) hq1odd
  exact orderOf_eq_one_iff.mp this

/-- Every element of `Multiplicative (ℤ/n)` is a power of `ofAdd 1`. -/
private theorem multiplicative_zmod_pow (n : ℕ) [NeZero n] (x : Multiplicative (ZMod n)) :
    x = (Multiplicative.ofAdd (1 : ZMod n)) ^ (Multiplicative.toAdd x).val := by
  have h1 : ((Multiplicative.toAdd x).val • (1 : ZMod n)) = Multiplicative.toAdd x := by
    rw [nsmul_eq_mul, mul_one, ZMod.natCast_val, ZMod.cast_id]
  rw [← ofAdd_nsmul, h1, ofAdd_toAdd]

/-- The unramified coordinate at level `k`: `ν_k = rightHom ∘ (T_q → G_{q,k})`. -/
noncomputable def fermatNuQ : ContinuousMonoidHom (Tq q) (Multiplicative (ZMod (2 ^ k))) :=
  ⟨SemidirectProduct.rightHom.comp (fermatHomQ q k).toMonoidHom, by
    have h : Continuous ((SemidirectProduct.rightHom :
        GFermatQ q k →* Multiplicative (ZMod (2 ^ k))) ∘ (fermatHomQ q k)) :=
      Continuous.comp continuous_of_discreteTopology (fermatHomQ q k).continuous_toFun
    exact h⟩

@[simp] private theorem fermatNuQ_tqTau : fermatNuQ q k (tqTau q) = 1 := by
  show SemidirectProduct.rightHom (fermatHomQ q k (tqTau q)) = 1
  rw [fermatHomQ_tqTau, tFermatQ, SemidirectProduct.rightHom_inl]

@[simp] private theorem fermatNuQ_tqSigma :
    fermatNuQ q k (tqSigma q) = Multiplicative.ofAdd 1 := by
  show SemidirectProduct.rightHom (fermatHomQ q k (tqSigma q)) = _
  rw [fermatHomQ_tqSigma, sFermatQ, SemidirectProduct.rightHom_inr]

end FermatLevels

/-! ## 7. The inertia quotient `Q_q = T_q / ⟨⟨τ⟩⟩` -/

/-- The closed normal closure of `τ` in `T_q` — the (pro-odd) tame inertia. -/
noncomputable def inertiaPartQ (q : ℕ) : Subgroup (Tq q) :=
  (Subgroup.normalClosure {tqTau q}).topologicalClosure

instance inertiaPartQ_normal (q : ℕ) : (inertiaPartQ q).Normal :=
  Subgroup.is_normal_topologicalClosure _

instance inertiaPartQ_isClosed (q : ℕ) : IsClosed ((inertiaPartQ q) : Set (Tq q)) :=
  Subgroup.isClosed_topologicalClosure _

/-- `Q_q = T_q / ⟨⟨τ⟩⟩`, the procyclic unramified quotient. -/
noncomputable def QurQ (q : ℕ) : ProfiniteGrp := profiniteQuotient (inertiaPartQ q)

/-- The projection `T_q → Q_q`, typed at the bundled carrier. -/
noncomputable def qMkQ (q : ℕ) : ContinuousMonoidHom (Tq q) (QurQ q) := quotientMk (inertiaPartQ q)

/-- The image of `σ` in `Q_q`. -/
noncomputable def qSigmaQ (q : ℕ) : QurQ q := quotientMk (inertiaPartQ q) (tqSigma q)

private theorem qMkQ_tqTau (q : ℕ) : quotientMk (inertiaPartQ q) (tqTau q) = 1 := by
  rw [quotientMk_eq_one_iff]
  exact Subgroup.le_topologicalClosure _
    (Subgroup.subset_normalClosure (Set.mem_singleton _))

/-- `Q_q` is topologically generated by `σ`. -/
theorem topGen_qurQ (q : ℕ) : (Subgroup.closure {qSigmaQ q}).topologicalClosure = ⊤ := by
  have h := TopGen.map (f := (quotientMk (inertiaPartQ q)).toMonoidHom)
    (quotientMk (inertiaPartQ q)).continuous_toFun (quotientMk_surjective _) (topGen_tq q)
  rw [Set.image_insert_eq, Set.image_singleton] at h
  have h1 : (⇑(quotientMk (inertiaPartQ q)).toMonoidHom) (tqTau q) = 1 := qMkQ_tqTau q
  rw [h1] at h
  rwa [TopGen.closure_pair_one] at h

section Levels

variable (q k : ℕ) [Fact (2 ≤ q)]

theorem fermatNuQ_kills_inertia : inertiaPartQ q ≤ (fermatNuQ q k).toMonoidHom.ker := by
  have hker_closed : IsClosed ((fermatNuQ q k).toMonoidHom.ker : Set (Tq q)) := by
    rw [MonoidHom.coe_ker]
    exact IsClosed.preimage (fermatNuQ q k).continuous_toFun isClosed_singleton
  refine Subgroup.topologicalClosure_minimal _ ?_ hker_closed
  refine Subgroup.normalClosure_le_normal ?_
  intro z hz
  rcases Set.mem_singleton_iff.mp hz with rfl
  exact MonoidHom.mem_ker.mpr (fermatNuQ_tqTau q k)

/-- The level maps `ψ_k : Q_q → C_{2^k}` descend from `ν_k`. -/
noncomputable def psiFermatQQ : ContinuousMonoidHom (QurQ q) (Multiplicative (ZMod (2 ^ k))) :=
  quotientLift (inertiaPartQ q) (fermatNuQ q k) (fermatNuQ_kills_inertia q k)

@[simp] private theorem psiFermatQQ_qSigmaQ :
    psiFermatQQ q k (qSigmaQ q) = Multiplicative.ofAdd 1 := by
  rw [show psiFermatQQ q k (qSigmaQ q) = fermatNuQ q k (tqSigma q) from
    quotientLift_quotientMk _ _ _ _]
  exact fermatNuQ_tqSigma q k

private theorem psiFermatQQ_surjective : Function.Surjective (psiFermatQQ q k) := by
  intro y
  refine ⟨qSigmaQ q ^ (Multiplicative.toAdd y).val, ?_⟩
  rw [map_pow, psiFermatQQ_qSigmaQ, ← multiplicative_zmod_pow]

end Levels

/-! ## 8. Packet Lemma 3.3: `O₂(T_q) = 1` -/

/-- In a finite cyclic group, an element whose order divides `#K` lies in `K`. -/
private theorem mem_of_orderOf_dvd_card {C : Type*} [Group C] [IsCyclic C] [Finite C]
    {K : Subgroup C} {x : C} (hdvd : orderOf x ∣ Nat.card K) : x ∈ K := by
  classical
  haveI := Fintype.ofFinite C
  set n := Nat.card K with hn
  have hnpos : 0 < n := Nat.card_pos
  have hx : x ^ n = 1 := orderOf_dvd_iff_pow_eq_one.mp hdvd
  have hle : ({b : C | b ^ n = 1} : Finset C).card ≤ n := IsCyclic.card_pow_eq_one_le hnpos
  have hsub : (K : Set C).toFinset ⊆ ({b : C | b ^ n = 1} : Finset C) := by
    intro y hy
    rw [Set.mem_toFinset] at hy
    have hyn : y ^ n = 1 :=
      orderOf_dvd_iff_pow_eq_one.mp (Subgroup.orderOf_dvd_natCard K hy)
    simpa using hyn
  have hcard : n ≤ (K : Set C).toFinset.card := by
    rw [Set.toFinset_card, ← Nat.card_eq_fintype_card]
    exact le_of_eq hn
  have heq : (K : Set C).toFinset = ({b : C | b ^ n = 1} : Finset C) :=
    Finset.eq_of_subset_of_card_le hsub (le_trans hle hcard)
  have hxmem : x ∈ ({b : C | b ^ n = 1} : Finset C) := by simpa using hx
  rw [← heq, Set.mem_toFinset] at hxmem
  exact hxmem

/-- Arithmetic core of the cyclic level-comparison: if a natural `n` factors both as `2^a * cχ`
and as `cU * cπ` with `a` the `2`-adic valuation of `cU`, then `cχ` and `cπ` have the same
`2`-adic valuation. -/
private theorem factorization_two_ker_eq {n cχ cπ cU a : ℕ}
    (hχ : n = 2 ^ a * cχ) (hπ : n = cU * cπ)
    (hcχ : cχ ≠ 0) (hcπ : cπ ≠ 0) (hcU : cU ≠ 0)
    (ha : a = cU.factorization 2) :
    cχ.factorization 2 = cπ.factorization 2 := by
  have e1 : a + cχ.factorization 2 = n.factorization 2 := by
    rw [hχ, Nat.factorization_mul (pow_ne_zero a two_ne_zero) hcχ, Finsupp.add_apply,
      Nat.Prime.factorization_pow Nat.prime_two, Finsupp.single_eq_same]
  have e2 : a + cπ.factorization 2 = n.factorization 2 := by
    rw [hπ, Nat.factorization_mul hcU hcπ, Finsupp.add_apply, ← ha]
  omega

section Lemma33

variable {q : ℕ} [Fact (2 ≤ q)]

/-- **Packet Lemma 3.3, `Q`-coordinate step.**  For a normal subgroup `M` of `T_q` with
`2`-group finite images, the image `qMkQ x` of any `x ∈ M` lies in every open normal subgroup
`U ≤ Q_q`: comparing the Fermat character `χ` (onto `C_{2^a}`) with the projection `π` onto
`Q_q/U` through the finer level `W`, the `2`-power-order class of `x` in `Q_q/W` sits in `ker χ`,
and the matching `2`-adic valuations force it into `ker π`, i.e. into `U`. -/
private theorem qMkQ_mem_of_two_images (hqe : Even q) (M : Subgroup (Tq q)) [M.Normal]
    (h2 : ∀ (G : Type) [Group G] [TopologicalSpace G] [DiscreteTopology G] [Finite G]
      (f : Tq q →* G), Continuous f → IsPGroup 2 (M.map f))
    {x : Tq q} (hx : x ∈ M) (U : OpenNormalSubgroup (QurQ q)) : qMkQ q x ∈ U := by
  haveI : Finite (QurQ q ⧸ U.toSubgroup) := inferInstance
  set y : QurQ q := qMkQ q x with hy
  set a : ℕ := (Nat.card (QurQ q ⧸ U.toSubgroup)).factorization 2 with ha
  have hKopen : IsOpen (((psiFermatQQ q a).toMonoidHom.ker : Subgroup (QurQ q)) : Set (QurQ q)) := by
    rw [MonoidHom.coe_ker]
    exact (isOpen_discrete _).preimage (psiFermatQQ q a).continuous_toFun
  haveI hkerN : ((psiFermatQQ q a).toMonoidHom.ker).Normal := MonoidHom.normal_ker _
  haveI hWn : (U.toSubgroup ⊓ (psiFermatQQ q a).toMonoidHom.ker).Normal := by
    constructor
    intro n hn g
    exact ⟨U.isNormal'.conj_mem _ hn.1 g, hkerN.conj_mem _ hn.2 g⟩
  obtain ⟨W, hWdef⟩ : ∃ W : OpenNormalSubgroup (QurQ q),
      W.toSubgroup = U.toSubgroup ⊓ (psiFermatQQ q a).toMonoidHom.ker :=
    ⟨⟨⟨U.toSubgroup ⊓ (psiFermatQQ q a).toMonoidHom.ker,
      U.toOpenSubgroup.isOpen'.inter hKopen⟩, hWn⟩, rfl⟩
  haveI : Finite (QurQ q ⧸ W.toSubgroup) := inferInstance
  set π : (QurQ q ⧸ W.toSubgroup) →* (QurQ q ⧸ U.toSubgroup) :=
    QuotientGroup.map W.toSubgroup U.toSubgroup (MonoidHom.id _) (by
      rw [Subgroup.comap_id, hWdef]
      exact inf_le_left) with hπ
  set χ : (QurQ q ⧸ W.toSubgroup) →* Multiplicative (ZMod (2 ^ a)) :=
    QuotientGroup.lift W.toSubgroup (psiFermatQQ q a).toMonoidHom
      (fun w hw => MonoidHom.mem_ker.mp (hWdef ▸ hw).2) with hχ
  haveI hWnormal : W.toSubgroup.Normal := W.isNormal'
  haveI hWtg : IsTopologicalGroup (QurQ q ⧸ W.toSubgroup) :=
    QuotientGroup.instIsTopologicalGroup W.toSubgroup
  haveI : IsCyclic (QurQ q ⧸ W.toSubgroup) := by
    have hgenC : Subgroup.closure {(QuotientGroup.mk' W.toSubgroup) (qSigmaQ q)} = ⊤ := by
      have h := TopGen.map (f := QuotientGroup.mk' W.toSubgroup) QuotientGroup.continuous_mk
        (QuotientGroup.mk'_surjective _) (topGen_qurQ q)
      rw [Set.image_singleton] at h
      exact TopGen.gen_of_discrete h
    refine ⟨⟨(QuotientGroup.mk' W.toSubgroup) (qSigmaQ q), fun z => ?_⟩⟩
    have hz : z ∈ Subgroup.closure {(QuotientGroup.mk' W.toSubgroup) (qSigmaQ q)} :=
      hgenC ▸ Subgroup.mem_top z
    rwa [← Subgroup.zpowers_eq_closure] at hz
  have hπsurj : Function.Surjective π := by
    intro c
    obtain ⟨z, rfl⟩ := QuotientGroup.mk'_surjective U.toSubgroup c
    exact ⟨(QuotientGroup.mk' W.toSubgroup) z, QuotientGroup.map_mk' _ _ _ _ _⟩
  have hχsurj : Function.Surjective χ := by
    intro c
    obtain ⟨q0, hq0⟩ := psiFermatQQ_surjective q a c
    exact ⟨(QuotientGroup.mk' W.toSubgroup) q0, (QuotientGroup.lift_mk' _ _ q0).trans hq0⟩
  have hposχ : Nat.card ((χ.ker : Subgroup (QurQ q ⧸ W.toSubgroup))) ≠ 0 := Nat.card_pos.ne'
  have hposπ : Nat.card ((π.ker : Subgroup (QurQ q ⧸ W.toSubgroup))) ≠ 0 := Nat.card_pos.ne'
  have hposU : Nat.card (QurQ q ⧸ U.toSubgroup) ≠ 0 := Nat.card_pos.ne'
  have hCχ : Nat.card (QurQ q ⧸ W.toSubgroup) = 2 ^ a * Nat.card χ.ker := by
    have h1 := Subgroup.card_eq_card_quotient_mul_card_subgroup (χ.ker)
    have hq2 : Nat.card ((QurQ q ⧸ W.toSubgroup) ⧸ χ.ker)
        = Nat.card (Multiplicative (ZMod (2 ^ a))) :=
      Nat.card_congr (QuotientGroup.quotientKerEquivOfSurjective χ hχsurj).toEquiv
    have h3 : Nat.card (Multiplicative (ZMod (2 ^ a))) = 2 ^ a := by
      rw [Nat.card_congr (Multiplicative.toAdd (α := ZMod (2 ^ a))), Nat.card_zmod]
    rw [h1, hq2, h3]
  have hCπ : Nat.card (QurQ q ⧸ W.toSubgroup)
      = Nat.card (QurQ q ⧸ U.toSubgroup) * Nat.card π.ker := by
    have h1 := Subgroup.card_eq_card_quotient_mul_card_subgroup (π.ker)
    have hq2 : Nat.card ((QurQ q ⧸ W.toSubgroup) ⧸ π.ker) = Nat.card (QurQ q ⧸ U.toSubgroup) :=
      Nat.card_congr (QuotientGroup.quotientKerEquivOfSurjective π hπsurj).toEquiv
    rw [h1, hq2]
  have hv2 : (Nat.card χ.ker).factorization 2 = (Nat.card π.ker).factorization 2 :=
    factorization_two_ker_eq hCχ hCπ hposχ hposπ hposU ha
  set u : QurQ q ⧸ W.toSubgroup := (QuotientGroup.mk' W.toSubgroup) y with hu
  have huK : u ∈ χ.ker := by
    rw [MonoidHom.mem_ker, hu]
    rw [show χ ((QuotientGroup.mk' W.toSubgroup) y) = psiFermatQQ q a y from
      QuotientGroup.lift_mk' _ _ y]
    rw [hy, show psiFermatQQ q a (qMkQ q x) = fermatNuQ q a x from
      quotientLift_quotientMk _ _ _ _]
    show SemidirectProduct.rightHom (fermatHomQ q a x) = 1
    rw [fermatHomQ_eq_one_of_mem q a hqe h2 hx, map_one]
  have hu2 : ∃ i : ℕ, orderOf u = 2 ^ i := by
    have hcont : Continuous ((QuotientGroup.mk' W.toSubgroup).comp (qMkQ q).toMonoidHom) := by
      rw [MonoidHom.coe_comp]
      exact Continuous.comp QuotientGroup.continuous_mk (qMkQ q).continuous_toFun
    have hmem : u ∈ M.map ((QuotientGroup.mk' W.toSubgroup).comp (qMkQ q).toMonoidHom) :=
      Subgroup.mem_map.mpr ⟨x, hx, rfl⟩
    exact exists_orderOf_eq_two_pow
      (h2 _ ((QuotientGroup.mk' W.toSubgroup).comp (qMkQ q).toMonoidHom) hcont) hmem
  obtain ⟨i, hi⟩ := hu2
  have hidvd : orderOf u ∣ Nat.card χ.ker := Subgroup.orderOf_dvd_natCard _ huK
  have hile : i ≤ (Nat.card χ.ker).factorization 2 := by
    rw [hi] at hidvd
    exact (Nat.Prime.pow_dvd_iff_le_factorization Nat.prime_two hposχ).mp hidvd
  have hidvd2 : orderOf u ∣ Nat.card π.ker := by
    rw [hi]
    exact (Nat.Prime.pow_dvd_iff_le_factorization Nat.prime_two hposπ).mpr (hv2 ▸ hile)
  have huπ : u ∈ π.ker := mem_of_orderOf_dvd_card hidvd2
  rw [MonoidHom.mem_ker, hu, show π ((QuotientGroup.mk' W.toSubgroup) y)
    = (QuotientGroup.mk' U.toSubgroup) y from QuotientGroup.map_mk' _ _ _ _ y] at huπ
  exact (QuotientGroup.eq_one_iff y).mp huπ

/-- **Packet Lemma 3.3, inertia step.**  An `x ∈ M` (`2`-group finite images) that already lies
in `inertiaPartQ` is trivial: through every finite level `V` its image lies in the tame `τ`-line
`⟨τ̄⟩`, whose order is odd (Lemma 3.1), while `x`'s image has `2`-power order. -/
private theorem eq_one_of_mem_inertiaPartQ (hqe : Even q) (M : Subgroup (Tq q))
    (h2 : ∀ (G : Type) [Group G] [TopologicalSpace G] [DiscreteTopology G] [Finite G]
      (f : Tq q →* G), Continuous f → IsPGroup 2 (M.map f))
    {x : Tq q} (hx : x ∈ M) (hxI : x ∈ inertiaPartQ q) : x = 1 := by
  have hq2 : 2 ≤ q := Fact.out
  refine eq_one_of_forall_mem_openNormalSubgroup fun V => ?_
  haveI : Finite (Tq q ⧸ V.toSubgroup) := inferInstance
  set mkV : Tq q →* Tq q ⧸ V.toSubgroup := QuotientGroup.mk' V.toSubgroup with hmkV
  have hp2 := h2 _ mkV QuotientGroup.continuous_mk
  have hmem : mkV x ∈ M.map mkV := Subgroup.mem_map.mpr ⟨x, hx, rfl⟩
  obtain ⟨j, hj⟩ := hp2 ⟨mkV x, hmem⟩
  have hj' : (mkV x) ^ 2 ^ j = 1 := by
    rw [Subtype.ext_iff] at hj
    simpa using hj
  have hgen := gen_tq_quotient mkV QuotientGroup.continuous_mk (QuotientGroup.mk'_surjective _)
  have hrel : (mkV (tqSigma q))⁻¹ * mkV (tqTau q) * mkV (tqSigma q) = (mkV (tqTau q)) ^ q :=
    tame_rel_map_q mkV
  haveI hzpn : (Subgroup.zpowers (mkV (tqTau q))).Normal := TameQ.zpowers_normal hgen hrel
  have hxzp : mkV x ∈ Subgroup.zpowers (mkV (tqTau q)) := by
    have h1 : mkV x ∈ closure ((⇑mkV) '' (Subgroup.normalClosure {tqTau q} : Set (Tq q))) :=
      map_mem_closure QuotientGroup.continuous_mk hxI (Set.mapsTo_image _ _)
    rw [(isClosed_discrete _).closure_eq] at h1
    obtain ⟨w, hwNC, hwx⟩ := h1
    have hle : Subgroup.normalClosure {tqTau q}
        ≤ (Subgroup.normalClosure {mkV (tqTau q)}).comap mkV := by
      haveI : ((Subgroup.normalClosure {mkV (tqTau q)}).comap mkV).Normal :=
        Subgroup.Normal.comap Subgroup.normalClosure_normal mkV
      refine Subgroup.normalClosure_le_normal ?_
      intro z hz
      rcases Set.mem_singleton_iff.mp hz with rfl
      exact Subgroup.mem_comap.mpr (Subgroup.subset_normalClosure (Set.mem_singleton _))
    have h3 : mkV w ∈ Subgroup.normalClosure {mkV (tqTau q)} :=
      Subgroup.mem_comap.mp (hle hwNC)
    have h4 : Subgroup.normalClosure {mkV (tqTau q)} ≤ Subgroup.zpowers (mkV (tqTau q)) := by
      refine Subgroup.normalClosure_le_normal ?_
      intro z hz
      rcases Set.mem_singleton_iff.mp hz with rfl
      exact Subgroup.mem_zpowers _
    exact hwx ▸ h4 h3
  have hodd : Odd (orderOf (mkV (tqTau q))) :=
    TameQ.odd_order (orderOf_pos (mkV (tqSigma q))).ne' (by omega) hqe hrel
  have hdvd_odd : orderOf (mkV x) ∣ orderOf (mkV (tqTau q)) := by
    have h := Subgroup.orderOf_dvd_natCard _ hxzp
    rwa [Nat.card_zpowers] at h
  have hdvd_two : orderOf (mkV x) ∣ 2 ^ j := orderOf_dvd_iff_pow_eq_one.mpr hj'
  have hcop : Nat.Coprime (2 ^ j) (orderOf (mkV (tqTau q))) := by
    refine Nat.Coprime.pow_left j ?_
    rw [Nat.Prime.coprime_iff_not_dvd Nat.prime_two]
    intro hdvd
    have := Nat.odd_iff.mp hodd
    omega
  have hone : orderOf (mkV x) = 1 := Nat.eq_one_of_dvd_coprimes hcop hdvd_two hdvd_odd
  exact (QuotientGroup.eq_one_iff x).mp (orderOf_eq_one_iff.mp hone)

/-- **Mandated export — packet Lemma 3.3 (`O₂(T_q) = 1`).**  A normal subgroup of `T_q` all of
whose finite continuous images are `2`-groups is trivial.

Packet argument: through each Fermat level `C_{q^{2^k}−1} ⋊ C_{2^k}` the image is a central
`2`-subgroup, hence trivial (the centre has odd order `q − 1`), so the `Q`-coordinate dies in
every `C_{2^k}`; the cyclic level-comparison then kills the `Q`-image entirely, and the remaining
inertia part has both odd and `2`-power order levelwise.  The `q = 2` precedent is
`GQ2.SectionThree.eq_bot_of_normal_two_images`; this is what feeds the derived `W_K = O₂(G_K)`
maximality statement of the AX4 layer (`GQ2/Prop32.lean`'s `tameData_maximal` at `q = 2`). -/
theorem o2_Tq_eq_bot (hqe : Even q) (M : Subgroup (Tq q)) [hMn : M.Normal]
    (h2 : ∀ (G : Type) [Group G] [TopologicalSpace G] [DiscreteTopology G] [Finite G]
      (f : Tq q →* G), Continuous f → IsPGroup 2 (M.map f)) :
    M = ⊥ := by
  rw [eq_bot_iff]
  intro x hx
  rw [Subgroup.mem_bot]
  have hxI : x ∈ inertiaPartQ q := by
    have hy1 : qMkQ q x = 1 :=
      eq_one_of_forall_mem_openNormalSubgroup (qMkQ_mem_of_two_images hqe M h2 hx)
    exact (quotientMk_eq_one_iff (N := inertiaPartQ q)).mp hy1
  exact eq_one_of_mem_inertiaPartQ hqe M h2 hx hxI

end Lemma33

/-- `o2_Tq_eq_bot` in the form the general-`K` layer instantiates it: `q = q_K = 2^f`
with `f ≥ 1`. -/
theorem o2_Tq_two_pow_eq_bot {f : ℕ} (hf : 1 ≤ f) (M : Subgroup (Tq (2 ^ f))) [M.Normal]
    (h2 : ∀ (G : Type) [Group G] [TopologicalSpace G] [DiscreteTopology G] [Finite G]
      (F : Tq (2 ^ f) →* G), Continuous F → IsPGroup 2 (M.map F)) :
    M = ⊥ := by
  haveI : Fact (2 ≤ 2 ^ f) := ⟨Nat.one_lt_two_pow_iff.mpr (by omega)⟩
  refine o2_Tq_eq_bot ?_ M h2
  obtain ⟨f', rfl⟩ : ∃ f', f = f' + 1 := ⟨f - 1, by omega⟩
  exact ⟨2 ^ f', by rw [pow_succ]; ring⟩

end GQ2.Dyadic
