/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using OpenAI Codex
-/
import GQ2.Dyadic.Count.H3AugmentationSeparation

/-!
# Augmentation nilpotence for finite 2-groups

This file proves the finite group-algebra theorem isolated in
`H3AugmentationSeparation`: the augmentation ideal in `F₂[Q]` is nilpotent whenever
`Q` is a finite `2`-group.
-/

namespace GQ2.ContCoh

noncomputable section

universe u

open GQ2.Dyadic.Count GQ2.Dyadic.SqCore
open scoped Pointwise

/-! ## A central relation generates a two-sided ideal -/

/-- The left ideal generated by an element which commutes with the whole ring is two-sided. -/
theorem idealSpanSingleton_isTwoSided_of_commute
    {R : Type u} [Ring R] (c : R) (hc : ∀ r : R, Commute c r) :
  (Ideal.span ({c} : Set R)).IsTwoSided := by
  constructor
  intro r x hx
  induction hx using Submodule.span_induction with
  | mem y hy =>
    rw [Set.mem_singleton_iff.mp hy]
    rw [(hc x).eq]
    exact Ideal.mul_mem_left _ x (Ideal.mem_span_singleton_self c)
  | zero => simp
  | add x y _ _ hx hy =>
    simpa [add_mul] using Ideal.add_mem _ hx hy
  | smul a x _ hx =>
    rw [smul_eq_mul, mul_assoc]
    exact Ideal.mul_mem_left _ a hx

/-! ## The group-algebra quotient by a central involution -/

/-- The group-algebra relation attached to a group element. -/
def modTwoGroupRelation {Q : Type u} [Group Q] (z : Q) : MonoidAlgebra (ZMod 2) Q :=
  MonoidAlgebra.single z 1 - 1

/-- A central group element gives a central group-algebra relation. -/
theorem modTwoGroupRelation_commute {Q : Type u} [Group Q] (z : Q)
    (hz : ∀ q : Q, Commute z q) (x : MonoidAlgebra (ZMod 2) Q) :
    Commute (modTwoGroupRelation z) x := by
  apply Commute.sub_left
  · exact MonoidAlgebra.of_commute hz x
  · exact Commute.one_left x

/-- The ideal generated by a central group-algebra relation is two-sided. -/
theorem modTwoGroupRelationIdeal_isTwoSided {Q : Type u} [Group Q] (z : Q)
    (hz : ∀ q : Q, Commute z q) :
    (Ideal.span ({modTwoGroupRelation z} : Set (MonoidAlgebra (ZMod 2) Q))).IsTwoSided :=
  idealSpanSingleton_isTwoSided_of_commute _ (modTwoGroupRelation_commute z hz)

/-- The relation of an involution squares to zero in characteristic two. -/
theorem modTwoGroupRelation_sq_eq_zero {Q : Type u} [Group Q] (z : Q)
    (hzsq : z ^ 2 = 1) : modTwoGroupRelation z ^ 2 = 0 := by
  have hmul : z * z = 1 := by simpa [pow_two] using hzsq
  simp only [modTwoGroupRelation, pow_two, mul_sub, sub_mul,
    MonoidAlgebra.single_mul_single, one_mul, mul_one, hmul]
  have htwo (x : MonoidAlgebra (ZMod 2) Q) : x + x = 0 := by
    rw [← two_smul (R := ZMod 2)]
    have h2 : (2 : ZMod 2) = 0 := by decide
    rw [h2, zero_smul]
  let a : MonoidAlgebra (ZMod 2) Q := MonoidAlgebra.single z 1
  change (1 : MonoidAlgebra (ZMod 2) Q) - a - (a - 1) = 0
  calc
    (1 : MonoidAlgebra (ZMod 2) Q) - a - (a - 1) = (1 + 1) - (a + a) := by abel
    _ = 0 := by simp only [htwo, sub_zero]

/-- The ideal generated by a central involution relation is square-zero. -/
theorem modTwoGroupRelationIdeal_sq_eq_bot {Q : Type u} [Group Q] (z : Q)
    (hz : ∀ q : Q, Commute z q) (hzsq : z ^ 2 = 1) :
    (Ideal.span ({modTwoGroupRelation z} : Set (MonoidAlgebra (ZMod 2) Q))) ^ 2 = ⊥ := by
  letI := modTwoGroupRelationIdeal_isTwoSided z hz
  rw [Ideal.span_singleton_pow, modTwoGroupRelation_sq_eq_zero z hzsq]
  simp

/-- The map on mod-two group algebras induced by a quotient map. -/
def modTwoQuotientGroupAlgebraMap {Q : Type u} [Group Q] (N : Subgroup Q) [N.Normal] :
    MonoidAlgebra (ZMod 2) Q →ₐ[ZMod 2] MonoidAlgebra (ZMod 2) (Q ⧸ N) :=
  MonoidAlgebra.mapDomainAlgHom (ZMod 2) (ZMod 2) (QuotientGroup.mk' N)

/-- A subgroup relation is killed by the corresponding quotient group-algebra map. -/
theorem modTwoGroupRelation_mem_quotientGroupAlgebraMap_ker
    {Q : Type u} [Group Q] (N : Subgroup Q) [N.Normal] (z : Q) (hzN : z ∈ N) :
    modTwoGroupRelation z ∈ RingHom.ker (modTwoQuotientGroupAlgebraMap N).toRingHom := by
  rw [RingHom.mem_ker]
  change modTwoQuotientGroupAlgebraMap N (MonoidAlgebra.single z 1 - 1) = 0
  rw [map_sub, map_one]
  rw [modTwoQuotientGroupAlgebraMap, MonoidAlgebra.mapDomainAlgHom_apply,
    MonoidAlgebra.mapDomain_single]
  have hzq : QuotientGroup.mk' N z = 1 := (QuotientGroup.eq_one_iff z).mpr hzN
  rw [hzq]
  exact sub_self (1 : MonoidAlgebra (ZMod 2) (Q ⧸ N))

/-- The central relation ideal maps to zero in the quotient group algebra. -/
theorem modTwoGroupRelationIdeal_le_quotientGroupAlgebraMap_ker
    {Q : Type u} [Group Q] (N : Subgroup Q) [N.Normal] (z : Q) (hzN : z ∈ N) :
    Ideal.span ({modTwoGroupRelation z} : Set (MonoidAlgebra (ZMod 2) Q)) ≤
      RingHom.ker (modTwoQuotientGroupAlgebraMap N).toRingHom := by
  rw [Ideal.span_le]
  intro x hx
  rw [Set.mem_singleton_iff.mp hx]
  exact modTwoGroupRelation_mem_quotientGroupAlgebraMap_ker N z hzN

/-- A cyclic subgroup generated by a central element is normal. -/
theorem zpowers_normal_of_commute {Q : Type u} [Group Q] (z : Q)
    (hz : ∀ q : Q, Commute z q) : (Subgroup.zpowers z).Normal := by
  constructor
  intro n hn g
  obtain ⟨k, rfl⟩ := Subgroup.mem_zpowers_iff.mp hn
  rw [← ((hz g).zpow_left k).eq, mul_assoc, mul_inv_cancel, mul_one]
  exact Subgroup.zpow_mem (Subgroup.zpowers z) (Subgroup.mem_zpowers z) k

/-- For a central element, quotienting the group algebra by `[z]-1` is the group algebra of
the quotient by `⟨z⟩`.  This is the kernel calculation used in the finite-group induction. -/
theorem quotientGroupAlgebraMap_zpowers_ker_eq_relationIdeal
    {Q : Type u} [Group Q] (N : Subgroup Q) [N.Normal]
    (z : Q) (hz : ∀ q : Q, Commute z q) (hN : N = Subgroup.zpowers z) :
    RingHom.ker (modTwoQuotientGroupAlgebraMap N).toRingHom =
      Ideal.span ({modTwoGroupRelation z} : Set (MonoidAlgebra (ZMod 2) Q)) := by
  let J : Ideal (MonoidAlgebra (ZMod 2) Q) :=
    Ideal.span ({modTwoGroupRelation z} : Set (MonoidAlgebra (ZMod 2) Q))
  letI : J.IsTwoSided := modTwoGroupRelationIdeal_isTwoSided z hz
  let qmk : MonoidAlgebra (ZMod 2) Q →ₐ[ZMod 2]
      (MonoidAlgebra (ZMod 2) Q ⧸ J) := Ideal.Quotient.mkₐ (ZMod 2) J
  let groupToQuotientUnits : Q →* (MonoidAlgebra (ZMod 2) Q ⧸ J)ˣ :=
    (Units.map qmk.toMonoidHom).comp
      (MonoidAlgebra.of (ZMod 2) Q).toHomUnits
  have hz_unit : groupToQuotientUnits z = 1 := by
    apply Units.ext
    change Ideal.Quotient.mk J (MonoidAlgebra.single z 1) = 1
    exact (Ideal.Quotient.mk_eq_one_iff_sub_mem (I := J) _).mpr
      (Ideal.mem_span_singleton_self (modTwoGroupRelation z))
  have hzpowers : N ≤ groupToQuotientUnits.ker := by
    intro x hx
    rw [hN] at hx
    obtain ⟨k, rfl⟩ := Subgroup.mem_zpowers_iff.mp hx
    rw [MonoidHom.mem_ker, map_zpow, hz_unit, one_zpow]
  let quotientGroupToUnits : (Q ⧸ N) →*
      (MonoidAlgebra (ZMod 2) Q ⧸ J)ˣ :=
    QuotientGroup.lift N groupToQuotientUnits hzpowers
  let quotientGroupToQuotient : (Q ⧸ N) →*
      (MonoidAlgebra (ZMod 2) Q ⧸ J) :=
    (Units.coeHom _).comp quotientGroupToUnits
  let inverse : MonoidAlgebra (ZMod 2) (Q ⧸ N) →ₐ[ZMod 2]
      (MonoidAlgebra (ZMod 2) Q ⧸ J) :=
    MonoidAlgebra.lift (ZMod 2) _ _ quotientGroupToQuotient
  have hsingle (q : Q) (a : ZMod 2) :
      inverse (modTwoQuotientGroupAlgebraMap N (MonoidAlgebra.single q a)) =
        qmk (MonoidAlgebra.single q a) := by
    rw [modTwoQuotientGroupAlgebraMap, MonoidAlgebra.mapDomainAlgHom_apply,
      MonoidAlgebra.mapDomain_single, MonoidAlgebra.lift_single]
    have hq : quotientGroupToQuotient (QuotientGroup.mk' N q) =
        qmk (MonoidAlgebra.single q 1) := by
      simp [quotientGroupToQuotient, quotientGroupToUnits, groupToQuotientUnits, qmk]
    rw [hq, ← map_smul]
    congr 1
    simp
  have hinverse (x : MonoidAlgebra (ZMod 2) Q) :
      inverse (modTwoQuotientGroupAlgebraMap N x) = qmk x := by
    induction x using MonoidAlgebra.induction_on with
    | hM q => simpa using hsingle q 1
    | hadd x y hx hy => rw [map_add, map_add, map_add, hx, hy]
    | hsmul a x hx => rw [map_smul, map_smul, map_smul, hx]
  apply le_antisymm
  · intro x hx
    rw [RingHom.mem_ker] at hx
    change modTwoQuotientGroupAlgebraMap N x = 0 at hx
    have hzero := congr_arg inverse hx
    rw [map_zero, hinverse] at hzero
    exact (Ideal.Quotient.eq_zero_iff_mem.mp hzero : x ∈ J)
  · exact modTwoGroupRelationIdeal_le_quotientGroupAlgebraMap_ker
      N z (hN.symm ▸ Subgroup.mem_zpowers z)

/-! ## Central involutions in finite 2-groups -/

/-- Every nontrivial finite `2`-group contains a central element of order two. -/
theorem exists_central_involution_of_isPGroup
    (Q : Type u) [Group Q] [Finite Q] [Nontrivial Q] (hQ : IsPGroup 2 Q) :
    ∃ z : Q, z ≠ 1 ∧ z ^ 2 = 1 ∧ ∀ q : Q, Commute z q := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  haveI : Nontrivial (Subgroup.center Q) := hQ.center_nontrivial
  have hcenterP : IsPGroup 2 (Subgroup.center Q) := hQ.to_subgroup (Subgroup.center Q)
  have hdvd : 2 ∣ Nat.card (Subgroup.center Q) :=
    hcenterP.card_eq_or_dvd.resolve_left (ne_of_gt Finite.one_lt_card)
  obtain ⟨z, hzorder⟩ := exists_prime_orderOf_dvd_card' 2 hdvd
  have hzpow : (z : Q) ^ 2 = 1 := by
    rw [← Subgroup.coe_pow, orderOf_eq_prime_iff.mp hzorder |>.1]
    rfl
  have hzne : (z : Q) ≠ 1 := by
    intro hz
    have : z = 1 := Subtype.ext hz
    rw [this, orderOf_one] at hzorder
    omega
  exact ⟨z, hzne, hzpow, fun q ↦ (Subgroup.mem_center_iff.mp z.2 q).symm⟩

/-! ## Nilpotence ascends across the central square-zero kernel -/

/-- Augmentation commutes with every quotient group-algebra map. -/
theorem modTwoFiniteAugmentation_quotientGroupAlgebraMap
    {Q : Type u} [Group Q] (N : Subgroup Q) [N.Normal]
    (x : MonoidAlgebra (ZMod 2) Q) :
    modTwoFiniteAugmentation (Q ⧸ N) (modTwoQuotientGroupAlgebraMap N x) =
      modTwoFiniteAugmentation Q x := by
  induction x using MonoidAlgebra.induction_on with
  | hM q =>
      have hof : MonoidAlgebra.of (ZMod 2) Q q =
          MonoidAlgebra.single q 1 := rfl
      rw [hof, modTwoQuotientGroupAlgebraMap, MonoidAlgebra.mapDomainAlgHom_apply,
        MonoidAlgebra.mapDomain_single, modTwoFiniteAugmentation_single,
        modTwoFiniteAugmentation_single]
  | hadd x y hx hy => simp only [map_add, hx, hy]
  | hsmul a x hx => simp only [map_smul, hx]

/-- If the quotient by a central involution has nilpotent augmentation ideal, then so does the
original group.  The exponent is doubled because the quotient-map kernel is square-zero. -/
theorem modTwoFiniteAugmentationIdeal_isNilpotent_of_central_involution_quotient
    {Q : Type u} [Group Q] (N : Subgroup Q) [N.Normal]
    (z : Q) (hz : ∀ q : Q, Commute z q) (hzsq : z ^ 2 = 1)
    (hN : N = Subgroup.zpowers z)
    (hquot : IsNilpotent (modTwoFiniteAugmentationIdeal (Q ⧸ N))) :
    IsNilpotent (modTwoFiniteAugmentationIdeal Q) := by
  let I := modTwoFiniteAugmentationIdeal Q
  let Iq := modTwoFiniteAugmentationIdeal (Q ⧸ N)
  letI : I.IsTwoSided := by
    change (RingHom.ker (modTwoFiniteAugmentation Q).toRingHom).IsTwoSided
    infer_instance
  let J : Ideal (MonoidAlgebra (ZMod 2) Q) :=
    Ideal.span ({modTwoGroupRelation z} : Set (MonoidAlgebra (ZMod 2) Q))
  letI : J.IsTwoSided := modTwoGroupRelationIdeal_isTwoSided z hz
  have hmaps : Set.MapsTo (modTwoQuotientGroupAlgebraMap N) I Iq := by
    intro x hx
    change x ∈ modTwoFiniteAugmentationIdeal Q at hx
    change modTwoQuotientGroupAlgebraMap N x ∈
      modTwoFiniteAugmentationIdeal (Q ⧸ N)
    rw [modTwoFiniteAugmentationIdeal, RingHom.mem_ker] at hx ⊢
    change modTwoFiniteAugmentation (Q ⧸ N)
      (modTwoQuotientGroupAlgebraMap N x) = 0
    rw [modTwoFiniteAugmentation_quotientGroupAlgebraMap]
    exact hx
  obtain ⟨n, hn⟩ := hquot
  have hpowker : I ^ n ≤ RingHom.ker (modTwoQuotientGroupAlgebraMap N).toRingHom := by
    intro x hx
    rw [RingHom.mem_ker]
    have himage := idealPow_mapsTo_of_mapsTo
      (modTwoQuotientGroupAlgebraMap N).toRingHom I Iq hmaps n hx
    rw [hn] at himage
    exact Ideal.mem_bot.mp himage
  have hpowJ : I ^ n ≤ J := by
    change I ^ n ≤ Ideal.span ({modTwoGroupRelation z} :
      Set (MonoidAlgebra (ZMod 2) Q))
    rw [← quotientGroupAlgebraMap_zpowers_ker_eq_relationIdeal N z hz hN]
    exact hpowker
  refine ⟨n + n, le_antisymm ?_ bot_le⟩
  change I ^ (n + n) ≤ ⊥
  rw [Ideal.IsTwoSided.pow_add]
  calc
    I ^ n * I ^ n ≤ J * J := Ideal.mul_mono hpowJ hpowJ
    _ = Ideal.span ({modTwoGroupRelation z * modTwoGroupRelation z} :
          Set (MonoidAlgebra (ZMod 2) Q)) :=
      Ideal.span_singleton_mul_span_singleton _ _
    _ = ⊥ := by
      rw [← pow_two, modTwoGroupRelation_sq_eq_zero z hzsq]
      simp

/-! ## The finite 2-group theorem -/

/-- For a subsingleton group, the augmentation is inverse to the scalar inclusion. -/
theorem algebraMap_modTwoFiniteAugmentation_eq_of_subsingleton
    (Q : Type u) [Group Q] [Subsingleton Q] (x : MonoidAlgebra (ZMod 2) Q) :
    algebraMap (ZMod 2) (MonoidAlgebra (ZMod 2) Q) (modTwoFiniteAugmentation Q x) = x := by
  induction x using MonoidAlgebra.induction_on with
  | hM q =>
      have hq : q = 1 := Subsingleton.elim _ _
      subst q
      simp [MonoidAlgebra.of_apply, modTwoFiniteAugmentation]
  | hadd x y hx hy => simp only [map_add, hx, hy]
  | hsmul a x hx =>
      rw [map_smul (modTwoFiniteAugmentation Q)]
      change algebraMap (ZMod 2) (MonoidAlgebra (ZMod 2) Q)
        (a * modTwoFiniteAugmentation Q x) = a • x
      rw [map_mul, hx]
      rw [Algebra.smul_def]

/-- The mod-two augmentation ideal of a subsingleton group is zero. -/
theorem modTwoFiniteAugmentationIdeal_eq_bot_of_subsingleton
    (Q : Type u) [Group Q] [Subsingleton Q] :
    modTwoFiniteAugmentationIdeal Q = ⊥ := by
  apply le_antisymm _ bot_le
  intro x hx
  rw [modTwoFiniteAugmentationIdeal, RingHom.mem_ker] at hx
  change modTwoFiniteAugmentation Q x = 0 at hx
  rw [← algebraMap_modTwoFiniteAugmentation_eq_of_subsingleton Q x, hx, map_zero]
  exact Ideal.zero_mem ⊥

/-- **Finite `2`-group augmentation nilpotence.**  The augmentation ideal in `F₂[Q]` is
nilpotent for every finite `2`-group `Q`.

The proof is the classical induction on `|Q|`: choose a central involution `z`, pass to
`Q/⟨z⟩`, and use that the group-algebra quotient kernel is the square-zero ideal generated
by `[z]-1`. -/
theorem finiteTwoGroupModTwoAugmentationNilpotence :
    FiniteTwoGroupModTwoAugmentationNilpotence.{u} := by
  intro Q _ _ hQ
  induction hcard : Nat.card Q using Nat.strong_induction_on generalizing Q with
  | h n ih =>
      by_cases hnontrivial : Nontrivial Q
      · letI : Nontrivial Q := hnontrivial
        obtain ⟨z, hzne, hzsq, hzcentral⟩ :=
          exists_central_involution_of_isPGroup Q hQ
        let N : Subgroup Q := Subgroup.zpowers z
        letI : N.Normal := by
          dsimp [N]
          exact zpowers_normal_of_commute z hzcentral
        have hNne : N ≠ ⊥ := by
          intro hbot
          have hzmem : z ∈ N := by
            dsimp [N]
            exact Subgroup.mem_zpowers z
          rw [hbot, Subgroup.mem_bot] at hzmem
          exact hzne hzmem
        have hlt : Nat.card (Q ⧸ N) < Nat.card Q := by
          calc
            Nat.card (Q ⧸ N) < Nat.card (Q ⧸ N) * Nat.card N :=
              lt_mul_of_one_lt_right Nat.card_pos (N.one_lt_card_iff_ne_bot.mpr hNne)
            _ = Nat.card Q := (N.card_eq_card_quotient_mul_card_subgroup).symm
        have hquot : IsNilpotent (modTwoFiniteAugmentationIdeal (Q ⧸ N)) :=
          ih (Nat.card (Q ⧸ N)) (hcard ▸ hlt) (Q ⧸ N)
            (hQ.to_quotient N) rfl
        exact modTwoFiniteAugmentationIdeal_isNilpotent_of_central_involution_quotient
          N z hzcentral hzsq (by rfl) hquot
      · haveI : Subsingleton Q := not_nontrivial_iff_subsingleton.mp hnontrivial
        rw [modTwoFiniteAugmentationIdeal_eq_bot_of_subsingleton Q]
        change IsNilpotent (0 : Ideal (MonoidAlgebra (ZMod 2) Q))
        exact ⟨1, Submodule.pow_one _⟩

/-! ## Unconditional separation and the square-core capstone -/

/-- The completed mod-two augmentation filtration of every pro-`2` group is separated. -/
theorem modTwoCompletedAugmentationSeparated_of_isProTwo
    (G : Type u) [Group G] [TopologicalSpace G] [IsTopologicalGroup G] [CompactSpace G]
    (hpro : IsProP 2 G) :
    ModTwoCompletedAugmentationSeparated (G := G) :=
  modTwoCompletedAugmentationSeparated_of_finiteTwoGroupNilpotence
    G hpro finiteTwoGroupModTwoAugmentationNilpotence

/-- In particular, the completed augmentation filtration of the improved square core is
separated. -/
theorem modTwoCompletedAugmentationSeparated_DSq (h : ℕ) :
    ModTwoCompletedAugmentationSeparated (G := DSq h) :=
  modTwoCompletedAugmentationSeparated_of_isProTwo
    (DSq h : Type) (isProP_DSq h)

/-- Finite `2`-group augmentation nilpotence removes the separation hypothesis from the
completed-Fox capstone.  The remaining inputs are initial-form regularity and bar--Fox
assembly. -/
theorem finiteElementaryH2RightExactSupply_DSq_of_barFox
    (h : ℕ)
    (hregular : CompletedRowAugmentationInitialRegular (DSq h : Type)
      (sqCompletedModTwoFoxDerivativeRow h))
    (assembly : SqFiniteToCompletedBarFoxAssembly h) :
    FiniteElementaryH2RightExactSupply (DSq h : Type) :=
  finiteElementaryH2RightExactSupply_DSq_of_augmentation_barFox h
    (modTwoCompletedAugmentationSeparated_DSq h) hregular assembly

end

end GQ2.ContCoh
