/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using OpenAI Codex
-/
import GQ2.Dyadic.Count.H3CompletedMagnusGradedBridge
import GQ2.Dyadic.Count.H3FiniteBarFoxReverse

/-!
# Finite generator differences and the completed augmentation kernel

At every finite quotient, elementary telescoping proves that the augmentation ideal is generated
by the differences of any group-generating marking.  The only genuinely completed step is to
choose the coefficients compatibly over all finite quotients.  This file formalizes the finite
theorem, isolates that inverse-limit lifting statement as
`FiniteGeneratorCompletedAugmentationLiftingTheorem`, and proves that it simultaneously supplies
both reverse kernels in `SqCompletedMagnusDegreeZeroOneExact`.

Thus the degree-zero and degree-one obstruction is not two unrelated Magnus assertions: a
single completed finite-generator decomposition

`x = sum_i c_i ([g_i]-1)`

does both jobs.  If `x` has zero first moments, the completed Leibniz rule shows that every
coefficient `c_i` has augmentation zero; applying the same decomposition theorem once more
puts every `c_i` in `J`, hence `x` in `J^2`.
-/

namespace GQ2.ContCoh

noncomputable section

open GQ2 GQ2.FoxH GQ2.Dyadic GQ2.Dyadic.Count
open GQ2.Dyadic.SqCore

/-! ## Finite telescoping -/

variable {Q I : Type} [Group Q]

/-- The left ideal of `F₂[Q]` generated by the differences of a marking. -/
def modTwoMarkedAugmentationIdeal (m : I → Q) :
    Ideal (MonoidAlgebra (ZMod 2) Q) :=
  Ideal.span (Set.range fun i => MonoidAlgebra.single (m i) 1 - 1)

/-- If the marking generates the group, every group-like difference belongs to the marked
augmentation ideal. -/
theorem modTwoGroupDifference_mem_markedAugmentationIdeal
    (m : I → Q) (hgen : Subgroup.closure (Set.range m) = ⊤) (q : Q) :
    MonoidAlgebra.single q 1 - 1 ∈ modTwoMarkedAugmentationIdeal m := by
  let H : Subgroup Q := {
    carrier := {q | MonoidAlgebra.single q 1 - 1 ∈
      modTwoMarkedAugmentationIdeal m}
    one_mem' := by
      change MonoidAlgebra.single 1 1 - 1 ∈ modTwoMarkedAugmentationIdeal m
      rw [← MonoidAlgebra.one_def, sub_self]
      exact (modTwoMarkedAugmentationIdeal m).zero_mem
    mul_mem' := by
      intro a b ha hb
      change MonoidAlgebra.single a 1 - 1 ∈ modTwoMarkedAugmentationIdeal m at ha
      change MonoidAlgebra.single b 1 - 1 ∈ modTwoMarkedAugmentationIdeal m at hb
      change MonoidAlgebra.single (a * b) 1 - 1 ∈ modTwoMarkedAugmentationIdeal m
      have hmul : MonoidAlgebra.single (a * b) (1 : ZMod 2) - 1 =
          MonoidAlgebra.single a 1 * (MonoidAlgebra.single b 1 - 1) +
            (MonoidAlgebra.single a 1 - 1) := by
        rw [mul_sub, mul_one, MonoidAlgebra.single_mul_single]
        simp only [one_mul]
        abel
      rw [hmul]
      exact (modTwoMarkedAugmentationIdeal m).add_mem
        ((modTwoMarkedAugmentationIdeal m).mul_mem_left _ hb) ha
    inv_mem' := by
      intro a ha
      change MonoidAlgebra.single a 1 - 1 ∈ modTwoMarkedAugmentationIdeal m at ha
      change MonoidAlgebra.single a⁻¹ 1 - 1 ∈ modTwoMarkedAugmentationIdeal m
      have hinv : MonoidAlgebra.single a⁻¹ (1 : ZMod 2) - 1 =
          -MonoidAlgebra.single a⁻¹ 1 * (MonoidAlgebra.single a 1 - 1) := by
        rw [neg_mul, mul_sub, mul_one, MonoidAlgebra.single_mul_single]
        simp only [inv_mul_cancel, one_mul]
        rw [← MonoidAlgebra.one_def]
        abel
      rw [hinv]
      exact (modTwoMarkedAugmentationIdeal m).mul_mem_left _ ha }
  have hle : Subgroup.closure (Set.range m) ≤ H := by
    rw [Subgroup.closure_le]
    rintro _ ⟨i, rfl⟩
    change MonoidAlgebra.single (m i) 1 - 1 ∈
      modTwoMarkedAugmentationIdeal m
    rw [modTwoMarkedAugmentationIdeal]
    exact Submodule.subset_span ⟨i, rfl⟩
  rw [hgen] at hle
  exact hle (Subgroup.mem_top q)

/-- Telescoping extends linearly: an arbitrary group-algebra element minus its augmentation
scalar belongs to the marked augmentation ideal. -/
theorem modTwoGroupAlgebra_sub_augmentation_mem_marked
    (m : I → Q) (hgen : Subgroup.closure (Set.range m) = ⊤)
    (x : MonoidAlgebra (ZMod 2) Q) :
    x - algebraMap (ZMod 2) (MonoidAlgebra (ZMod 2) Q)
        (modTwoFiniteAugmentation Q x) ∈
      modTwoMarkedAugmentationIdeal m := by
  induction x using MonoidAlgebra.induction_on with
  | hM q =>
      have haug : modTwoFiniteAugmentation Q
          (MonoidAlgebra.of (ZMod 2) Q q) = 1 := by
        simp [modTwoFiniteAugmentation]
      rw [haug, map_one]
      exact modTwoGroupDifference_mem_markedAugmentationIdeal m hgen q
  | hadd x y hx hy =>
      simp only [map_add]
      convert (modTwoMarkedAugmentationIdeal m).add_mem hx hy using 1
      abel
  | hsmul a x hx =>
      simp only [map_smul]
      have hm := (modTwoMarkedAugmentationIdeal m).mul_mem_left
        (algebraMap (ZMod 2) (MonoidAlgebra (ZMod 2) Q) a) hx
      simpa [Algebra.smul_def, mul_sub] using hm

/-- **Finite Cayley-boundary theorem.**  A group-generating marking generates the entire
mod-two augmentation ideal. -/
theorem modTwoMarkedAugmentationIdeal_eq_finiteAugmentationIdeal
    (m : I → Q) (hgen : Subgroup.closure (Set.range m) = ⊤) :
    modTwoMarkedAugmentationIdeal m = modTwoFiniteAugmentationIdeal Q := by
  apply le_antisymm
  · rw [modTwoMarkedAugmentationIdeal, Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    exact modTwoFiniteAugmentationIdeal_single_sub_one Q (m i)
  · intro x hx
    rw [modTwoFiniteAugmentationIdeal, RingHom.mem_ker] at hx
    change modTwoFiniteAugmentation Q x = 0 at hx
    have hmem := modTwoGroupAlgebra_sub_augmentation_mem_marked m hgen x
    rw [hx, map_zero, sub_zero] at hmem
    exact hmem

/-- The images of the improved square generators generate the finite augmentation ideal at
every actual open-normal quotient. -/
theorem sqOpenQuotientMarkedAugmentationIdeal_eq
    (h : ℕ) (V : OpenNormalSubgroup (DSq h : Type)) :
    modTwoMarkedAugmentationIdeal (sqOpenQuotientMarking h V) =
      modTwoFiniteLevelAugmentationIdeal (DSq h : Type) V :=
  modTwoMarkedAugmentationIdeal_eq_finiteAugmentationIdeal
    (sqOpenQuotientMarking h V) (sqOpenQuotientMarking_closure_eq_top h V)

/-! ## The exact completed inverse-limit theorem -/

/-- A finite marking admits completed augmentation-generator coordinates if every
augmentation-zero compatible family is a finite sum of the marked differences with completed
coefficients.  Quantifying over the coordinate used to measure augmentation avoids building a
separate coordinate-independence API. -/
def CompletedAugmentationGeneratorLifting
    (G : Type) [Group G] [TopologicalSpace G] [IsTopologicalGroup G] [CompactSpace G]
    {I : Type} [Fintype I] (m : I → G) : Prop :=
  ∀ (U : OpenNormalSubgroup G) (x : ModTwoCompletedGroupAlgebra G),
    modTwoCompletedAugmentationCoordinate G U x = 0 →
      ∃ c : I → ModTwoCompletedGroupAlgebra G,
        x = ∑ i, c i * (ModTwoCompletedGroupAlgebra.of G (m i) - 1)

/-- The reusable compactness/Nakayama theorem still needed: finite topological generation of a
profinite group implies compatible completed generator coordinates.  The finite theorem above
proves nonemptiness at every quotient; proving this statement amounts exactly to passing from
those finite affine solution sets to a compatible inverse-limit point. -/
def FiniteGeneratorCompletedAugmentationLiftingTheorem : Prop :=
  ∀ (G : Type) [Group G] [TopologicalSpace G] [IsTopologicalGroup G] [CompactSpace G]
    (I : Type) [Fintype I] (m : I → G),
    (Subgroup.closure (Set.range m)).topologicalClosure = ⊤ →
      CompletedAugmentationGeneratorLifting G m

/-- The square marking satisfies the exact finite topological-generation hypothesis of the
completed lifting theorem. -/
theorem completedAugmentationGeneratorLifting_sq_of_finiteGeneratorTheorem
    (H : FiniteGeneratorCompletedAugmentationLiftingTheorem) (h : ℕ) :
    CompletedAugmentationGeneratorLifting (DSq h : Type) (sqGen h) :=
  H (DSq h : Type) (Fin (sqRank h)) (sqGen h) (dsq_topGen h)

/-! ## One lifting theorem gives both reverse kernels -/

/-- Completed first moments satisfy the augmentation Leibniz rule. -/
theorem sqCompletedFirstMomentMap_mul
    (h : ℕ) (x y : ModTwoCompletedGroupAlgebra (DSq h : Type)) :
    sqCompletedFirstMomentMap h (x * y) =
      modTwoCompletedAugmentationCoordinate (DSq h : Type)
          (sqMagnusOneKernel h) y • sqCompletedFirstMomentMap h x +
        modTwoCompletedAugmentationCoordinate (DSq h : Type)
            (sqMagnusOneKernel h) x • sqCompletedFirstMomentMap h y := by
  funext a
  change modTwoGroupAlgebraLinearMoment _
      (ModTwoCompletedGroupAlgebra.coordinate (DSq h : Type)
        (sqMagnusOneKernel h) (x * y)) = _
  rw [map_mul, modTwoGroupAlgebraLinearMoment_mul]
  simp [sqCompletedFirstMomentMap, modTwoCompletedAugmentationCoordinate,
    smul_eq_mul, mul_comm]

/-- A marked generator difference has the corresponding standard first-moment vector. -/
theorem sqCompletedFirstMomentMap_generatorDifference
    (h : ℕ) (i : Fin (sqRank h)) :
    sqCompletedFirstMomentMap h
        (ModTwoCompletedGroupAlgebra.of (DSq h : Type) (sqGen h i) - 1) =
      Pi.single i 1 := by
  funext a
  change modTwoGroupAlgebraLinearMoment _
      (ModTwoCompletedGroupAlgebra.coordinate (DSq h : Type)
        (sqMagnusOneKernel h)
        (ModTwoCompletedGroupAlgebra.of (DSq h : Type) (sqGen h i) - 1)) = _
  rw [map_sub, ModTwoCompletedGroupAlgebra.coordinate_of, map_one, map_sub]
  rw [modTwoGroupAlgebraLinearMoment_single, one_mul]
  have hone :
      modTwoGroupAlgebraLinearMoment
        ((multiplicativeModTwoCharacter (sqMagnusOneCoordinate h a)).comp
          (sqMagnusOneQuotientHom h))
        (1 : MonoidAlgebra (ZMod 2)
          ((DSq h : Type) ⧸ (sqMagnusOneKernel h).toSubgroup)) = 0 := by
    rw [MonoidAlgebra.one_def, modTwoGroupAlgebraLinearMoment_single]
    simp
  rw [hone, sub_zero]
  change Multiplicative.toAdd
      (((multiplicativeModTwoCharacter (sqMagnusOneCoordinate h a)).comp
        (sqMagnusOneQuotientHom h))
        (QuotientGroup.mk' (sqMagnusOneKernel h).toSubgroup (sqGen h i))) = _
  rw [MonoidHom.comp_apply, sqMagnusOneQuotientHom_marking]
  change sqMagnusOneCoordinate h a (Multiplicative.toAdd (sqMagnusOneMark h i)) =
    (Pi.single i (1 : ZMod 2) : Fin (sqRank h) → ZMod 2) a
  rw [sqMagnusOneCoordinate_mark]
  classical
  by_cases hai : i = a <;> simp [hai]

/-- A completed generator decomposition proves the reverse degree-zero kernel. -/
theorem sqCompletedDegreeZero_reverse_of_generatorLifting
    (h : ℕ)
    (H : CompletedAugmentationGeneratorLifting (DSq h : Type) (sqGen h))
    (x : ModTwoCompletedGroupAlgebra (DSq h : Type))
    (hx : modTwoCompletedAugmentationCoordinate (DSq h : Type)
      (sqMagnusOneKernel h) x = 0) :
    x ∈ modTwoCompletedAugmentationIdeal (DSq h : Type) := by
  obtain ⟨c, rfl⟩ := H (sqMagnusOneKernel h) x hx
  apply Ideal.sum_mem
  intro i hi
  exact (modTwoCompletedAugmentationIdeal (DSq h : Type)).mul_mem_left _
    (by rw [modTwoCompletedAugmentationIdeal]
        exact Submodule.subset_span ⟨sqGen h i, rfl⟩)

/-- In a completed generator decomposition, first moments are exactly the augmentations of the
coefficients. -/
theorem sqCompletedFirstMomentMap_generatorExpansion
    (h : ℕ) (c : Fin (sqRank h) →
      ModTwoCompletedGroupAlgebra (DSq h : Type)) :
    sqCompletedFirstMomentMap h
        (∑ i, c i *
          (ModTwoCompletedGroupAlgebra.of (DSq h : Type) (sqGen h i) - 1)) =
      fun i => modTwoCompletedAugmentationCoordinate (DSq h : Type)
        (sqMagnusOneKernel h) (c i) := by
  rw [map_sum]
  have hgenAug (i : Fin (sqRank h)) :
      modTwoCompletedAugmentationCoordinate (DSq h : Type)
          (sqMagnusOneKernel h)
          (ModTwoCompletedGroupAlgebra.of (DSq h : Type) (sqGen h i) - 1) = 0 :=
    modTwoCompletedAugmentationCoordinate_eq_zero_of_mem
      (DSq h : Type) (sqMagnusOneKernel h) (by
        rw [modTwoCompletedAugmentationIdeal]
        exact Submodule.subset_span ⟨sqGen h i, rfl⟩)
  simp_rw [sqCompletedFirstMomentMap_mul, hgenAug, zero_smul, zero_add,
    sqCompletedFirstMomentMap_generatorDifference]
  funext a
  classical
  simp [Pi.single_apply]

/-- The same completed generator lifting also proves the reverse degree-one kernel. -/
theorem sqCompletedDegreeOne_reverse_of_generatorLifting
    (h : ℕ)
    (H : CompletedAugmentationGeneratorLifting (DSq h : Type) (sqGen h))
    (x : ModTwoCompletedGroupAlgebra (DSq h : Type))
    (hxJ : x ∈ modTwoCompletedAugmentationIdeal (DSq h : Type))
    (hx : sqCompletedFirstMomentMap h x = 0) :
    x ∈ modTwoCompletedAugmentationIdeal (DSq h : Type) ^ 2 := by
  have haug := modTwoCompletedAugmentationCoordinate_eq_zero_of_mem
    (DSq h : Type) (sqMagnusOneKernel h) hxJ
  obtain ⟨c, hc⟩ := H (sqMagnusOneKernel h) x haug
  have hcaug : ∀ i, modTwoCompletedAugmentationCoordinate (DSq h : Type)
      (sqMagnusOneKernel h) (c i) = 0 := by
    intro i
    have hm := congrFun (congrArg (sqCompletedFirstMomentMap h) hc) i
    rw [sqCompletedFirstMomentMap_generatorExpansion] at hm
    simpa [hx] using hm.symm
  have hcJ : ∀ i, c i ∈ modTwoCompletedAugmentationIdeal (DSq h : Type) := by
    intro i
    exact sqCompletedDegreeZero_reverse_of_generatorLifting h H (c i) (hcaug i)
  rw [hc]
  rw [Submodule.pow_succ]
  simp only [Submodule.pow_one]
  apply Ideal.sum_mem
  intro i hi
  exact Ideal.mul_mem_mul (hcJ i) (by
    rw [modTwoCompletedAugmentationIdeal]
    exact Submodule.subset_span ⟨sqGen h i, rfl⟩)

/-- **Degree-zero/one closure from one completed Nakayama theorem.** -/
theorem sqCompletedMagnusDegreeZeroOneExact_of_generatorLifting
    (h : ℕ)
    (H : CompletedAugmentationGeneratorLifting (DSq h : Type) (sqGen h)) :
    SqCompletedMagnusDegreeZeroOneExact h :=
  sqCompletedMagnusDegreeZeroOneExact_of_reverseKernels h
    (sqCompletedDegreeZero_reverse_of_generatorLifting h H)
    (sqCompletedDegreeOne_reverse_of_generatorLifting h H)

/-- Universal finite-generator completed lifting therefore closes both square reverse kernels. -/
theorem sqCompletedMagnusDegreeZeroOneExact_of_finiteGeneratorTheorem
    (H : FiniteGeneratorCompletedAugmentationLiftingTheorem) (h : ℕ) :
    SqCompletedMagnusDegreeZeroOneExact h :=
  sqCompletedMagnusDegreeZeroOneExact_of_generatorLifting h
    (completedAugmentationGeneratorLifting_sq_of_finiteGeneratorTheorem H h)

end

end GQ2.ContCoh
