/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using OpenAI Codex
-/
import GQ2.Dyadic.Count.H3FiniteBarFoxComparison

/-!
# The section-dependent reverse finite bar--Fox comparison

At a finite quotient generated by a marking `m : I → Q`, choose the normalized word section
`relationSection` of `FreeGroup.lift m`.  Fox differentiation of the chosen word for `q` sends
the bar edge `[q]` back to a path in the marked Cayley graph.  The failure of the section to be
multiplicative is the Schreier factor `relationDefect q r`, so the reverse image of the boundary
of `[q|r]` is exactly the universal Fox row of that factor.

This gives the honest reverse chain map through the **full** relation kernel.  It also gives a
chain homotopy between the reverse--forward composite on presentation one-cells and the identity.
Both identities are valid for arbitrary section choices and require no cohomological exactness.

For an actual finite quotient of `DSq h`, the marked generators generate algebraically, so this
construction applies without an extra hypothesis.  The remaining obstruction is now explicit:
to reach `SqFiniteToCompletedBarFoxAssembly`, the full relation-kernel cells must be coordinatized
by the single improved relator, compatibly under quotient refinement.  Such a coordinatization is
not supplied here (and cannot be obtained from pointwise finite strong freeness, which already
fails at the trivial quotient).
-/

namespace GQ2.Dyadic.Count

noncomputable section

open GQ2.ContCoh GQ2.FoxH
open GQ2.Dyadic.SqCore

variable {Q I : Type} [Group Q]

/-! ## Fox paths attached to a normalized word section -/

/-- The marked one-boundary commutes with regular translation. -/
theorem finiteMarkedBoundaryOne_translate (m : I → Q) (g : Q)
    (c : RegularModTwoRelationModule Q I) :
    finiteMarkedBoundaryOne m (regularModTwoTranslate Q I g c) =
      regularModTwoTranslate Q Unit g (finiteMarkedBoundaryOne m c) := by
  classical
  induction c using Finsupp.induction with
  | zero => simp
  | single_add p a c hp ha ih =>
      rcases p with ⟨q, i⟩
      simp only [map_add, regularModTwoTranslate_single, ih,
        finiteMarkedBoundaryOne_single]
      rw [mul_assoc]

/-- Successive regular translations multiply their translating elements. -/
theorem regularModTwoTranslate_comp (g q : Q)
    (c : RegularModTwoRelationModule Q I) :
    regularModTwoTranslate Q I g (regularModTwoTranslate Q I q c) =
      regularModTwoTranslate Q I (g * q) c := by
  classical
  ext p
  rcases p with ⟨r, i⟩
  simp only [regularModTwoTranslate_apply, mul_inv_rev, mul_assoc]

/-- Fox differentiation of the normalized section word gives a marked path from `1` to `q`. -/
def finiteSectionPath (m : I → Q)
    (heval : Function.Surjective (FreeGroup.lift m)) (q : Q) :
    RegularModTwoRelationModule Q I :=
  modTwoFoxDerivative m (relationSection heval q)

/-- The boundary of the section path is `[q] + [1]`. -/
theorem finiteMarkedBoundaryOne_sectionPath
    (m : I → Q) (heval : Function.Surjective (FreeGroup.lift m)) (q : Q) :
    finiteMarkedBoundaryOne m (finiteSectionPath m heval q) =
      Finsupp.single (q, ()) 1 + Finsupp.single (1, ()) 1 := by
  rw [finiteSectionPath, finiteMarkedBoundaryOne_modTwoFoxDerivative,
    relationSection_spec]

/-- Reverse a bar one-chain by replacing every edge `g[q]` with the translate by `g` of the
chosen section path for `q`. -/
def finiteBarToMarkedOne (m : I → Q)
    (heval : Function.Surjective (FreeGroup.lift m)) :
    FiniteModTwoBarChainOne Q →ₗ[ZMod 2] RegularModTwoRelationModule Q I :=
  (Finsupp.lsum (ZMod 2)) fun p : Q × Q =>
    LinearMap.toSpanSingleton (ZMod 2) _
      (regularModTwoTranslate Q I p.1 (finiteSectionPath m heval p.2))

@[simp] theorem finiteBarToMarkedOne_single
    (m : I → Q) (heval : Function.Surjective (FreeGroup.lift m))
    (g q : Q) (a : ZMod 2) :
    finiteBarToMarkedOne m heval (Finsupp.single (g, q) a) =
      a • regularModTwoTranslate Q I g (finiteSectionPath m heval q) := by
  classical
  rw [finiteBarToMarkedOne, Finsupp.lsum_single]
  simp

/-- The section-dependent reverse map is a chain map in degree one. -/
theorem finiteBarToMarkedOne_boundary
    (m : I → Q) (heval : Function.Surjective (FreeGroup.lift m))
    (c : FiniteModTwoBarChainOne Q) :
    finiteMarkedBoundaryOne m (finiteBarToMarkedOne m heval c) =
      finiteModTwoBarBoundaryOne c := by
  classical
  induction c using Finsupp.induction with
  | zero => simp
  | single_add p a c hp ha ih =>
      rcases p with ⟨g, q⟩
      simp only [map_add, ih, finiteBarToMarkedOne_single,
        finiteModTwoBarBoundaryOne_single, map_smul,
        finiteMarkedBoundaryOne_translate,
        finiteMarkedBoundaryOne_sectionPath,
        regularModTwoTranslate_single, mul_one]
      simp [smul_add, Finsupp.smul_single, smul_eq_mul]

/-! ## The universal relation-kernel two-cells -/

/-- The finite Fox boundary whose relator alphabet is the entire relation kernel. -/
def finiteUniversalRelationFoxBoundary
    (m : I → Q) :
    ModTwoFoxBoundary Q
      (RegularModTwoRelationModule Q (FreeRelationKernel m))
      (RegularModTwoRelationModule Q I) :=
  finiteLevelModTwoFoxBoundary m fun r : FreeRelationKernel m => r.1

/-- Fox differentiation of the Schreier factor is the three-edge section defect. -/
theorem modTwoFoxDerivative_relationDefect
    (m : I → Q) (heval : Function.Surjective (FreeGroup.lift m)) (q r : Q) :
    modTwoFoxDerivative m (relationDefect heval q r).1 =
      finiteSectionPath m heval q +
        regularModTwoTranslate Q I q (finiteSectionPath m heval r) +
          finiteSectionPath m heval (q * r) := by
  simp only [modTwoFoxDerivative, relationDefect, Subgroup.coe_mk,
    map_mul, map_inv, WordLift.mul_u, WordLift.mul_g, WordLift.inv_u,
    lift_foxLift_g, relationSection_spec, finiteSectionPath]
  rw [smul_neg, ← mul_smul]
  simp only [mul_inv_cancel, one_smul, ZModModule.neg_eq_self]
  rfl

/-- Replace a bar two-cell `g[q|r]` by the translated Schreier relation factor
`g · (s(q)s(r)s(qr)⁻¹)`. -/
def finiteBarToUniversalRelationTwo (m : I → Q)
    (heval : Function.Surjective (FreeGroup.lift m)) :
    FiniteModTwoBarChainTwo Q →ₗ[ZMod 2]
      RegularModTwoRelationModule Q (FreeRelationKernel m) :=
  (Finsupp.lsum (ZMod 2)) fun p : Q × (Q × Q) =>
    LinearMap.toSpanSingleton (ZMod 2) _
      (Finsupp.single (p.1, relationDefect heval p.2.1 p.2.2) 1)

@[simp] theorem finiteBarToUniversalRelationTwo_single
    (m : I → Q) (heval : Function.Surjective (FreeGroup.lift m))
    (g q r : Q) (a : ZMod 2) :
    finiteBarToUniversalRelationTwo m heval (Finsupp.single (g, (q, r)) a) =
      Finsupp.single (g, relationDefect heval q r) a := by
  classical
  rw [finiteBarToUniversalRelationTwo, Finsupp.lsum_single]
  simp [LinearMap.toSpanSingleton_apply, smul_eq_mul]

/-- **Reverse degree-two chain identity.** The reverse image of the bar boundary of every
two-chain is exactly the universal Fox boundary of its Schreier relation factor. -/
theorem finiteBarToMarkedOne_boundaryTwo
    (m : I → Q) (heval : Function.Surjective (FreeGroup.lift m))
    (c : FiniteModTwoBarChainTwo Q) :
    finiteBarToMarkedOne m heval (finiteModTwoBarBoundaryTwo c) =
      (finiteUniversalRelationFoxBoundary m).map
        (finiteBarToUniversalRelationTwo m heval c) := by
  classical
  induction c using Finsupp.induction with
  | zero => simp
  | single_add p a c hp ha ih =>
      rcases p with ⟨g, q, r⟩
      simp only [map_add, ih, finiteModTwoBarBoundaryTwo_single,
        finiteBarToMarkedOne_single,
        finiteBarToUniversalRelationTwo_single,
        finiteUniversalRelationFoxBoundary,
        finiteLevelModTwoFoxBoundary_single]
      rw [modTwoFoxDerivative_relationDefect]
      simp only [map_add, regularModTwoTranslate_comp]
      simp only [smul_add]
      abel

/-! ## A reverse--forward homotopy on presentation one-cells -/

/-- The kernel word comparing the chosen section word for `m i` with the generator letter
itself. -/
def finiteGeneratorSectionDefect (m : I → Q)
    (heval : Function.Surjective (FreeGroup.lift m)) (i : I) :
    FreeRelationKernel m :=
  ⟨relationSection heval (m i) * (FreeGroup.of i)⁻¹, by
    rw [MonoidHom.mem_ker, map_mul, map_inv, relationSection_spec]
    simp⟩

/-- A presentation one-cell is sent to the translated relation cell comparing the chosen
section path of its marked value with that generator edge. -/
def finiteMarkedOneToUniversalRelationTwo (m : I → Q)
    (heval : Function.Surjective (FreeGroup.lift m)) :
    RegularModTwoRelationModule Q I →ₗ[ZMod 2]
      RegularModTwoRelationModule Q (FreeRelationKernel m) :=
  (Finsupp.lsum (ZMod 2)) fun p : Q × I =>
    LinearMap.toSpanSingleton (ZMod 2) _
      (Finsupp.single (p.1, finiteGeneratorSectionDefect m heval p.2) 1)

@[simp] theorem finiteMarkedOneToUniversalRelationTwo_single
    (m : I → Q) (heval : Function.Surjective (FreeGroup.lift m))
    (g : Q) (i : I) (a : ZMod 2) :
    finiteMarkedOneToUniversalRelationTwo m heval (Finsupp.single (g, i) a) =
      Finsupp.single (g, finiteGeneratorSectionDefect m heval i) a := by
  classical
  rw [finiteMarkedOneToUniversalRelationTwo, Finsupp.lsum_single]
  simp [LinearMap.toSpanSingleton_apply, smul_eq_mul]

/-- Fox differentiation of the generator-section defect is the sum of the chosen section path
and the generator basis edge. -/
theorem modTwoFoxDerivative_finiteGeneratorSectionDefect
    (m : I → Q) (heval : Function.Surjective (FreeGroup.lift m)) (i : I) :
    modTwoFoxDerivative m (finiteGeneratorSectionDefect m heval i).1 =
      finiteSectionPath m heval (m i) + modTwoFoxGenerator (L := Q) i := by
  simp only [modTwoFoxDerivative, finiteGeneratorSectionDefect, Subgroup.coe_mk,
    map_mul, map_inv, WordLift.mul_u, WordLift.inv_u,
    lift_foxLift_g, relationSection_spec, finiteSectionPath]
  rw [FreeGroup.lift_apply_of]
  rw [smul_neg, ← mul_smul]
  simp [foxLift, ZModModule.neg_eq_self]

/-- **Reverse--forward homotopy identity.** On every presentation one-chain, the composite
`presentation → bar → presentation` differs from the identity by the universal Fox boundary
of the generator-section relation cells. -/
theorem finiteBarToMarkedOne_comp_markedToBarOne
    (m : I → Q) (heval : Function.Surjective (FreeGroup.lift m))
    (c : RegularModTwoRelationModule Q I) :
    finiteBarToMarkedOne m heval (finiteMarkedToBarOne m c) + c =
      (finiteUniversalRelationFoxBoundary m).map
        (finiteMarkedOneToUniversalRelationTwo m heval c) := by
  classical
  induction c using Finsupp.induction with
  | zero => simp
  | single_add p a c hp ha ih =>
      rcases p with ⟨g, i⟩
      simp only [map_add, finiteMarkedToBarOne_single,
        finiteBarToMarkedOne_single,
        finiteMarkedOneToUniversalRelationTwo_single,
        finiteUniversalRelationFoxBoundary,
        finiteLevelModTwoFoxBoundary_single]
      rw [modTwoFoxDerivative_finiteGeneratorSectionDefect]
      simp only [map_add]
      have hgen : regularModTwoTranslate Q I g (modTwoFoxGenerator (L := Q) i) =
          Finsupp.single (g, i) 1 := by
        simp [modTwoFoxGenerator]
      rw [hgen]
      simp only [smul_add, Finsupp.smul_single, smul_eq_mul, mul_one]
      change finiteBarToMarkedOne m heval (finiteMarkedToBarOne m c) + c =
        (finiteLevelModTwoFoxBoundary m (fun r : FreeRelationKernel m => r.1)).map
          (finiteMarkedOneToUniversalRelationTwo m heval c) at ih
      rw [← ih]
      abel

/-! ## Refinement: conditional naturality and the strict-section obstruction -/

variable {Q' : Type} [Group Q']

/-- A section path commutes with pushforward provided the chosen normalized word sections agree
strictly.  The following no-go theorem explains why this premise cannot hold across a proper
quotient and therefore has to be weakened by relation-cell corrections in an inverse system. -/
theorem finiteSectionPath_natural_of_section
    (phi : Q →* Q') (m : I → Q)
    (heval : Function.Surjective (FreeGroup.lift m))
    (heval' : Function.Surjective (FreeGroup.lift (fun i ↦ phi (m i))))
    (hsection : ∀ q, relationSection heval' (phi q) = relationSection heval q)
    (q : Q) :
    regularModTwoPushforward phi I (finiteSectionPath m heval q) =
      finiteSectionPath (fun i ↦ phi (m i)) heval' (phi q) := by
  rw [finiteSectionPath, finiteSectionPath,
    regularModTwoPushforward_modTwoFoxDerivative, hsection]

/-- Under strict compatibility of the word sections, the reverse degree-one comparison is
natural for a group homomorphism. -/
theorem finiteBarToMarkedOne_natural_of_section
    (phi : Q →* Q') (m : I → Q)
    (heval : Function.Surjective (FreeGroup.lift m))
    (heval' : Function.Surjective (FreeGroup.lift (fun i ↦ phi (m i))))
    (hsection : ∀ q, relationSection heval' (phi q) = relationSection heval q)
    (c : FiniteModTwoBarChainOne Q) :
    regularModTwoPushforward phi I (finiteBarToMarkedOne m heval c) =
      finiteBarToMarkedOne (fun i ↦ phi (m i)) heval'
        (finiteModTwoBarMapOne phi c) := by
  classical
  induction c using Finsupp.induction with
  | zero => simp
  | single_add p a c hp ha ih =>
      rcases p with ⟨g, q⟩
      simp only [map_add, ih, finiteBarToMarkedOne_single,
        finiteModTwoBarMapOne, regularModTwoMap_single, map_smul,
        regularModTwoPushforward_translate]
      rw [finiteSectionPath_natural_of_section phi m heval heval' hsection]

/-! ### Arbitrary sections are natural up to an explicit relation cell -/

/-- The target-kernel word measuring the failure of the two normalized sections to commute
with `phi`.  Both factors evaluate to `phi q` at the pushed marking. -/
def relationSectionRefinementDefect
    (phi : Q →* Q') (m : I → Q)
    (heval : Function.Surjective (FreeGroup.lift m))
    (heval' : Function.Surjective (FreeGroup.lift (fun i ↦ phi (m i))))
    (q : Q) : FreeRelationKernel (fun i ↦ phi (m i)) :=
  ⟨relationSection heval' (phi q) * (relationSection heval q)⁻¹, by
    rw [MonoidHom.mem_ker, map_mul, map_inv, relationSection_spec,
      ← map_freeGroup_lift phi m, relationSection_spec]
    simp⟩

/-- The Fox row of the refinement defect is exactly the sum of the target section path and the
pushforward of the source section path.  In characteristic two this is their difference. -/
theorem modTwoFoxDerivative_relationSectionRefinementDefect
    (phi : Q →* Q') (m : I → Q)
    (heval : Function.Surjective (FreeGroup.lift m))
    (heval' : Function.Surjective (FreeGroup.lift (fun i ↦ phi (m i))))
    (q : Q) :
    modTwoFoxDerivative (fun i ↦ phi (m i))
        (relationSectionRefinementDefect phi m heval heval' q).1 =
      finiteSectionPath (fun i ↦ phi (m i)) heval' (phi q) +
        regularModTwoPushforward phi I (finiteSectionPath m heval q) := by
  simp only [modTwoFoxDerivative, relationSectionRefinementDefect,
    Subgroup.coe_mk, map_mul, map_inv, WordLift.mul_u, WordLift.inv_u,
    lift_foxLift_g, relationSection_spec, finiteSectionPath]
  rw [← map_freeGroup_lift phi m, relationSection_spec]
  rw [smul_neg, ← mul_smul]
  simp only [mul_inv_cancel, one_smul, ZModModule.neg_eq_self]
  change _ + modTwoFoxDerivative (fun i ↦ phi (m i)) (relationSection heval q) =
    _ + regularModTwoPushforward phi I
      (modTwoFoxDerivative m (relationSection heval q))
  rw [regularModTwoPushforward_modTwoFoxDerivative]

/-- Minimal relator-coordinate data which turns the arbitrary section defect into a specified
presentation two-chain.  No coordinate is requested on unrelated elements of the full relation
kernel. -/
structure FiniteSectionRefinementRelatorCoordinates
    (phi : Q →* Q') (m : I → Q)
    (heval : Function.Surjective (FreeGroup.lift m))
    (heval' : Function.Surjective (FreeGroup.lift (fun i ↦ phi (m i))))
    (rel : Type) (w : rel → FreeGroup I) where
  /-- A presentation relation-chain correcting the section at `q`. -/
  coordinate : Q → RegularModTwoRelationModule Q' rel
  /-- Its presentation Fox boundary is the universal section-refinement defect row. -/
  fox : ∀ q,
    (finiteLevelModTwoFoxBoundary (fun i ↦ phi (m i)) w).map (coordinate q) =
      modTwoFoxDerivative (fun i ↦ phi (m i))
        (relationSectionRefinementDefect phi m heval heval' q).1

/-- Extend the pointwise refinement coordinates equivariantly to bar one-chains. -/
def finiteBarSectionRefinementRelatorCorrection
    {rel : Type} {w : rel → FreeGroup I}
    {phi : Q →* Q'} {m : I → Q}
    {heval : Function.Surjective (FreeGroup.lift m)}
    {heval' : Function.Surjective (FreeGroup.lift (fun i ↦ phi (m i)))}
    (C : FiniteSectionRefinementRelatorCoordinates
      phi m heval heval' rel w) :
    FiniteModTwoBarChainOne Q →ₗ[ZMod 2]
      RegularModTwoRelationModule Q' rel :=
  (Finsupp.lsum (ZMod 2)) fun p : Q × Q =>
    LinearMap.toSpanSingleton (ZMod 2) _
      (regularModTwoTranslate Q' rel (phi p.1) (C.coordinate p.2))

@[simp] theorem finiteBarSectionRefinementRelatorCorrection_single
    {rel : Type} {w : rel → FreeGroup I}
    {phi : Q →* Q'} {m : I → Q}
    {heval : Function.Surjective (FreeGroup.lift m)}
    {heval' : Function.Surjective (FreeGroup.lift (fun i ↦ phi (m i)))}
    (C : FiniteSectionRefinementRelatorCoordinates
      phi m heval heval' rel w)
    (g q : Q) (a : ZMod 2) :
    finiteBarSectionRefinementRelatorCorrection C (Finsupp.single (g, q) a) =
      a • regularModTwoTranslate Q' rel (phi g) (C.coordinate q) := by
  classical
  rw [finiteBarSectionRefinementRelatorCorrection, Finsupp.lsum_single]
  simp

/-- The boundary of a basis correction chain is the translated universal refinement-defect
row. -/
theorem finiteBarSectionRefinementRelatorCorrection_boundary_single
    {rel : Type} {w : rel → FreeGroup I}
    {phi : Q →* Q'} {m : I → Q}
    {heval : Function.Surjective (FreeGroup.lift m)}
    {heval' : Function.Surjective (FreeGroup.lift (fun i ↦ phi (m i)))}
    (C : FiniteSectionRefinementRelatorCoordinates
      phi m heval heval' rel w)
    (g q : Q) (a : ZMod 2) :
    (finiteLevelModTwoFoxBoundary (fun i ↦ phi (m i)) w).map
        (finiteBarSectionRefinementRelatorCorrection C
          (Finsupp.single (g, q) a)) =
      a • regularModTwoTranslate Q' I (phi g)
        (modTwoFoxDerivative (fun i ↦ phi (m i))
          (relationSectionRefinementDefect phi m heval heval' q).1) := by
  rw [finiteBarSectionRefinementRelatorCorrection_single, map_smul]
  congr 1
  calc
    (finiteLevelModTwoFoxBoundary (fun i ↦ phi (m i)) w).map
        (regularModTwoTranslate Q' rel (phi g) (C.coordinate q)) =
      regularModTwoTranslate Q' I (phi g)
        ((finiteLevelModTwoFoxBoundary (fun i ↦ phi (m i)) w).map
          (C.coordinate q)) :=
      (finiteLevelModTwoFoxBoundary (fun i ↦ phi (m i)) w).equivariant
        (phi g) (C.coordinate q)
    _ = _ := congrArg (regularModTwoTranslate Q' I (phi g)) (C.fox q)

/-- **Exact corrected naturality.** Arbitrary normalized finite sections give a reverse
degree-one comparison natural up to the displayed presentation Fox boundary precisely when the
minimal section-refinement defects admit the specified relator coordinates. -/
theorem finiteBarToMarkedOne_refinement_up_to_fox
    {rel : Type} {w : rel → FreeGroup I}
    (phi : Q →* Q') (m : I → Q)
    (heval : Function.Surjective (FreeGroup.lift m))
    (heval' : Function.Surjective (FreeGroup.lift (fun i ↦ phi (m i))))
    (C : FiniteSectionRefinementRelatorCoordinates
      phi m heval heval' rel w)
    (c : FiniteModTwoBarChainOne Q) :
    regularModTwoPushforward phi I (finiteBarToMarkedOne m heval c) +
        finiteBarToMarkedOne (fun i ↦ phi (m i)) heval'
          (finiteModTwoBarMapOne phi c) =
      (finiteLevelModTwoFoxBoundary (fun i ↦ phi (m i)) w).map
        (finiteBarSectionRefinementRelatorCorrection C c) := by
  classical
  induction c using Finsupp.induction with
  | zero => simp
  | single_add p a c hp ha ih =>
      rcases p with ⟨g, q⟩
      simp only [map_add, finiteBarToMarkedOne_single,
        finiteModTwoBarMapOne, regularModTwoMap_single,
        finiteBarSectionRefinementRelatorCorrection_boundary_single,
        map_smul, regularModTwoPushforward_translate,
        modTwoFoxDerivative_relationSectionRefinementDefect]
      simp only [smul_add]
      rw [← ih]
      abel

/-- **Strict-section no-go.** If normalized section words were literally compatible along a
homomorphism, that homomorphism would have to be injective.  Thus a proper refinement quotient
cannot be handled by choosing word lifts that commute on the nose; relation-cell corrections
are mathematically unavoidable. -/
theorem injective_of_strictlyNatural_relationSection
    (phi : Q →* Q') (m : I → Q)
    (heval : Function.Surjective (FreeGroup.lift m))
    (heval' : Function.Surjective (FreeGroup.lift (fun i ↦ phi (m i))))
    (hsection : ∀ q, relationSection heval' (phi q) = relationSection heval q) :
    Function.Injective phi := by
  intro q r hqr
  have hs : relationSection heval q = relationSection heval r := by
    rw [← hsection q, ← hsection r, hqr]
  calc
    q = FreeGroup.lift m (relationSection heval q) :=
      (relationSection_spec heval q).symm
    _ = FreeGroup.lift m (relationSection heval r) := congrArg _ hs
    _ = r := relationSection_spec heval r

/-- Contrapositive form of the strict-section no-go, convenient at a proper quotient map. -/
theorem not_strictlyNatural_relationSection_of_not_injective
    (phi : Q →* Q') (m : I → Q)
    (heval : Function.Surjective (FreeGroup.lift m))
    (heval' : Function.Surjective (FreeGroup.lift (fun i ↦ phi (m i))))
    (hninj : ¬ Function.Injective phi) :
    ¬ (∀ q, relationSection heval' (phi q) = relationSection heval q) := by
  intro hsection
  exact hninj
    (injective_of_strictlyNatural_relationSection phi m heval heval' hsection)

/-! ## Actual finite quotients of the improved square core -/

/-- The images of the improved-presentation generators generate every open-normal quotient
algebraically. -/
theorem sqOpenQuotientMarking_closure_eq_top (h : ℕ)
    (V : OpenNormalSubgroup (DSq h : Type)) :
    Subgroup.closure (Set.range (sqOpenQuotientMarking h V)) = ⊤ := by
  letI : DiscreteTopology ((DSq h : Type) ⧸ V.toSubgroup) :=
    Subgroup.instDiscreteTopologyQuotientOfSeparatelyContinuousMul V.toOpenSubgroup
  set H := Subgroup.closure (Set.range (sqOpenQuotientMarking h V)) with hH
  have hle : Subgroup.closure (Set.range (sqGen h)) ≤
      H.comap (QuotientGroup.mk' V.toSubgroup) := by
    rw [Subgroup.closure_le]
    rintro _ ⟨i, rfl⟩
    exact Subgroup.subset_closure ⟨i, rfl⟩
  have hclosed : IsClosed
      ((H.comap (QuotientGroup.mk' V.toSubgroup) :
        Subgroup (DSq h : Type)) : Set (DSq h : Type)) := by
    show IsClosed ((QuotientGroup.mk' V.toSubgroup) ⁻¹'
      (H : Set ((DSq h : Type) ⧸ V.toSubgroup)))
    exact IsClosed.preimage continuous_quotient_mk' (isClosed_discrete _)
  have hall := Subgroup.topologicalClosure_minimal _ hle hclosed
  rw [dsq_topGen h] at hall
  change H = ⊤
  apply eq_top_iff.mpr
  intro q hq
  obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective V.toSubgroup q
  exact hall (Subgroup.mem_top g)

/-- The free-group evaluation at the actual quotient marking is surjective. -/
theorem sqOpenQuotientFreeEvaluation_surjective (h : ℕ)
    (V : OpenNormalSubgroup (DSq h : Type)) :
    Function.Surjective (FreeGroup.lift (sqOpenQuotientMarking h V)) :=
  freeGroup_lift_surjective_of_closure (sqOpenQuotientMarking_closure_eq_top h V)

/-- Surjectivity at the coarser quotient, written with the pushed finer marking. -/
theorem sqOpenQuotientProjectedFreeEvaluation_surjective
    (h : ℕ) {V W : OpenNormalSubgroup (DSq h : Type)}
    (hWV : W.toSubgroup ≤ V.toSubgroup) :
    Function.Surjective (FreeGroup.lift (fun i ↦
      openNormalQuotientProj hWV (sqOpenQuotientMarking h W i))) := by
  simpa only [openNormalQuotientProj_sqOpenQuotientMarking] using
    sqOpenQuotientFreeEvaluation_surjective h V

/-- The exact remaining single-relator coordinate datum along one actual refinement.  It asks
only for coordinates of the normalized section defects, and its Fox row is the literal improved
square row at the coarser quotient. -/
abbrev SqOpenQuotientSectionRefinementRelatorCoordinates
    (h : ℕ) {V W : OpenNormalSubgroup (DSq h : Type)}
    (hWV : W.toSubgroup ≤ V.toSubgroup) :=
  FiniteSectionRefinementRelatorCoordinates
    (openNormalQuotientProj hWV) (sqOpenQuotientMarking h W)
    (sqOpenQuotientFreeEvaluation_surjective h W)
    (sqOpenQuotientProjectedFreeEvaluation_surjective h hWV)
    Unit (fun _ : Unit ↦ sqDiscreteRelator h)

/-- Coherent single-relator coordinates for the section failures throughout the open-normal
inverse system.  The `composition` field is the cocycle law for chain homotopies along a tower
`W ≤ V ≤ U`: the direct correction is the coarser correction plus pushforward of the finer
one.  This is precisely the extra compatibility needed to turn the quotient-wise corrected
naturality theorem below into a coherent inverse-system reverse comparison in degree one.

It deliberately does not claim the degree-three cochain reconstruction fields of
`SqFiniteToCompletedBarFoxAssembly`; those still require the higher bar/relation comparison. -/
structure SqOpenQuotientReverseSectionCoordinateSystem (h : ℕ) where
  /-- Minimal actual improved-relator coordinates at every refinement. -/
  level : ∀ {V W : OpenNormalSubgroup (DSq h : Type)}
    (hWV : W.toSubgroup ≤ V.toSubgroup),
    SqOpenQuotientSectionRefinementRelatorCoordinates h hWV
  /-- The identity refinement has zero correction. -/
  identity : ∀ (V : OpenNormalSubgroup (DSq h : Type))
    (q : (DSq h : Type) ⧸ V.toSubgroup),
    (level (le_refl V.toSubgroup)).coordinate q = 0
  /-- Corrections compose additively and by extension of scalars along a refinement tower. -/
  composition : ∀ {U V W : OpenNormalSubgroup (DSq h : Type)}
    (hWV : W.toSubgroup ≤ V.toSubgroup)
    (hVU : V.toSubgroup ≤ U.toSubgroup)
    (q : (DSq h : Type) ⧸ W.toSubgroup),
    (level (hWV.trans hVU)).coordinate q =
      (level hVU).coordinate (openNormalQuotientProj hWV q) +
        regularModTwoPushforward (openNormalQuotientProj hVU) Unit
          ((level hWV).coordinate q)

/-- The section-dependent reverse map on bar one-chains for an actual improved-square quotient. -/
def sqOpenQuotientBarToMarkedOne (h : ℕ)
    (V : OpenNormalSubgroup (DSq h : Type)) :
    FiniteModTwoBarChainOne ((DSq h : Type) ⧸ V.toSubgroup) →ₗ[ZMod 2]
      RegularModTwoRelationModule ((DSq h : Type) ⧸ V.toSubgroup) (Fin (sqRank h)) :=
  finiteBarToMarkedOne (sqOpenQuotientMarking h V)
    (sqOpenQuotientFreeEvaluation_surjective h V)

/-- The actual quotient reverse map is a chain map in degree one. -/
theorem sqOpenQuotientBarToMarkedOne_boundary (h : ℕ)
    (V : OpenNormalSubgroup (DSq h : Type))
    (c : FiniteModTwoBarChainOne ((DSq h : Type) ⧸ V.toSubgroup)) :
    finiteMarkedBoundaryOne (sqOpenQuotientMarking h V)
        (sqOpenQuotientBarToMarkedOne h V c) =
      finiteModTwoBarBoundaryOne c :=
  finiteBarToMarkedOne_boundary _ _ c

/-- The single-relator correction chain attached to one actual refinement. -/
def sqOpenQuotientSectionRefinementCorrection
    (h : ℕ) {V W : OpenNormalSubgroup (DSq h : Type)}
    {hWV : W.toSubgroup ≤ V.toSubgroup}
    (C : SqOpenQuotientSectionRefinementRelatorCoordinates h hWV) :
    FiniteModTwoBarChainOne ((DSq h : Type) ⧸ W.toSubgroup) →ₗ[ZMod 2]
      RegularModTwoRelationModule ((DSq h : Type) ⧸ V.toSubgroup) Unit :=
  finiteBarSectionRefinementRelatorCorrection C

@[simp] theorem sqOpenQuotientSectionRefinementCorrection_single
    (h : ℕ) {V W : OpenNormalSubgroup (DSq h : Type)}
    {hWV : W.toSubgroup ≤ V.toSubgroup}
    (C : SqOpenQuotientSectionRefinementRelatorCoordinates h hWV)
    (g q : (DSq h : Type) ⧸ W.toSubgroup) (a : ZMod 2) :
    sqOpenQuotientSectionRefinementCorrection h C (Finsupp.single (g, q) a) =
      a • regularModTwoTranslate ((DSq h : Type) ⧸ V.toSubgroup) Unit
        (openNormalQuotientProj hWV g) (C.coordinate q) :=
  finiteBarSectionRefinementRelatorCorrection_single C g q a

/-- Quotient projections compose along a tower of open-normal subgroups. -/
theorem sqOpenNormalQuotientProj_comp
    (h : ℕ) {U V W : OpenNormalSubgroup (DSq h : Type)}
    (hWV : W.toSubgroup ≤ V.toSubgroup)
    (hVU : V.toSubgroup ≤ U.toSubgroup)
    (q : (DSq h : Type) ⧸ W.toSubgroup) :
    openNormalQuotientProj hVU (openNormalQuotientProj hWV q) =
      openNormalQuotientProj (hWV.trans hVU) q := by
  obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective W.toSubgroup q
  simp only [openNormalQuotientProj_mk]

/-- **Actual corrected refinement identity.** Once the section defects have coordinates in the
literal improved relator row, the two section-dependent reverse maps commute up to that actual
presentation Fox boundary.  This is the honest replacement for impossible strict section
compatibility. -/
theorem sqOpenQuotientBarToMarkedOne_refinement_up_to_fox
    (h : ℕ) {V W : OpenNormalSubgroup (DSq h : Type)}
    (hWV : W.toSubgroup ≤ V.toSubgroup)
    (C : SqOpenQuotientSectionRefinementRelatorCoordinates h hWV)
    (c : FiniteModTwoBarChainOne ((DSq h : Type) ⧸ W.toSubgroup)) :
    regularModTwoPushforward (openNormalQuotientProj hWV) (Fin (sqRank h))
          (sqOpenQuotientBarToMarkedOne h W c) +
        sqOpenQuotientBarToMarkedOne h V
          (finiteModTwoBarMapOne (openNormalQuotientProj hWV) c) =
      (sqFiniteLevelModTwoFoxBoundary h (sqOpenQuotientMarking h V)).map
        (sqOpenQuotientSectionRefinementCorrection h C c) := by
  simpa only [sqOpenQuotientBarToMarkedOne,
    sqOpenQuotientSectionRefinementCorrection,
    sqFiniteLevelModTwoFoxBoundary,
    openNormalQuotientProj_sqOpenQuotientMarking] using
    finiteBarToMarkedOne_refinement_up_to_fox
      (openNormalQuotientProj hWV) (sqOpenQuotientMarking h W)
      (sqOpenQuotientFreeEvaluation_surjective h W)
      (sqOpenQuotientProjectedFreeEvaluation_surjective h hWV) C c

/-- A coherent coordinate system supplies the actual corrected reverse square at every
open-normal refinement. -/
theorem SqOpenQuotientReverseSectionCoordinateSystem.corrected_naturality
    {h : ℕ} (S : SqOpenQuotientReverseSectionCoordinateSystem h)
    {V W : OpenNormalSubgroup (DSq h : Type)}
    (hWV : W.toSubgroup ≤ V.toSubgroup)
    (c : FiniteModTwoBarChainOne ((DSq h : Type) ⧸ W.toSubgroup)) :
    regularModTwoPushforward (openNormalQuotientProj hWV) (Fin (sqRank h))
          (sqOpenQuotientBarToMarkedOne h W c) +
        sqOpenQuotientBarToMarkedOne h V
          (finiteModTwoBarMapOne (openNormalQuotientProj hWV) c) =
      (sqFiniteLevelModTwoFoxBoundary h (sqOpenQuotientMarking h V)).map
      (sqOpenQuotientSectionRefinementCorrection h (S.level hWV) c) :=
  sqOpenQuotientBarToMarkedOne_refinement_up_to_fox h hWV (S.level hWV) c

/-- The correction homotopies themselves satisfy the tower cocycle law.  This is the concrete
chain-level content of `SqOpenQuotientReverseSectionCoordinateSystem.composition`. -/
theorem SqOpenQuotientReverseSectionCoordinateSystem.correction_composition
    {h : ℕ} (S : SqOpenQuotientReverseSectionCoordinateSystem h)
    {U V W : OpenNormalSubgroup (DSq h : Type)}
    (hWV : W.toSubgroup ≤ V.toSubgroup)
    (hVU : V.toSubgroup ≤ U.toSubgroup)
    (c : FiniteModTwoBarChainOne ((DSq h : Type) ⧸ W.toSubgroup)) :
    sqOpenQuotientSectionRefinementCorrection h
        (S.level (hWV.trans hVU)) c =
      sqOpenQuotientSectionRefinementCorrection h (S.level hVU)
          (finiteModTwoBarMapOne (openNormalQuotientProj hWV) c) +
        regularModTwoPushforward (openNormalQuotientProj hVU) Unit
          (sqOpenQuotientSectionRefinementCorrection h (S.level hWV) c) := by
  classical
  induction c using Finsupp.induction with
  | zero => simp
  | single_add p a c hp ha ih =>
      rcases p with ⟨g, q⟩
      simp only [map_add, ih,
        sqOpenQuotientSectionRefinementCorrection_single,
        finiteModTwoBarMapOne, regularModTwoMap_single,
        regularModTwoPushforward_translate, map_smul]
      rw [S.composition hWV hVU q]
      simp only [map_add, smul_add, sqOpenNormalQuotientProj_comp]
      abel

/-- The universal relation-kernel reverse two-cell map for an actual improved-square quotient. -/
def sqOpenQuotientBarToUniversalRelationTwo (h : ℕ)
    (V : OpenNormalSubgroup (DSq h : Type)) :
    FiniteModTwoBarChainTwo ((DSq h : Type) ⧸ V.toSubgroup) →ₗ[ZMod 2]
      RegularModTwoRelationModule ((DSq h : Type) ⧸ V.toSubgroup)
        (FreeRelationKernel (sqOpenQuotientMarking h V)) :=
  finiteBarToUniversalRelationTwo (sqOpenQuotientMarking h V)
    (sqOpenQuotientFreeEvaluation_surjective h V)

/-- The actual reverse degree-two identity, landing in the full relation kernel. -/
theorem sqOpenQuotientBarToMarkedOne_boundaryTwo (h : ℕ)
    (V : OpenNormalSubgroup (DSq h : Type))
    (c : FiniteModTwoBarChainTwo ((DSq h : Type) ⧸ V.toSubgroup)) :
    sqOpenQuotientBarToMarkedOne h V (finiteModTwoBarBoundaryTwo c) =
      (finiteUniversalRelationFoxBoundary (sqOpenQuotientMarking h V)).map
        (sqOpenQuotientBarToUniversalRelationTwo h V c) :=
  finiteBarToMarkedOne_boundaryTwo _ _ c

/-- Strict normalized word-section compatibility along an actual refinement projection is
impossible whenever that projection has nontrivial kernel. -/
theorem not_sqOpenQuotientRelationSection_strict_natural
    (h : ℕ) {V W : OpenNormalSubgroup (DSq h : Type)}
    (hWV : W.toSubgroup ≤ V.toSubgroup)
    (hninj : ¬ Function.Injective (openNormalQuotientProj hWV)) :
    ¬ (∀ q,
      relationSection (sqOpenQuotientFreeEvaluation_surjective h V)
          (openNormalQuotientProj hWV q) =
        relationSection (sqOpenQuotientFreeEvaluation_surjective h W) q) := by
  apply not_strictlyNatural_relationSection_of_not_injective
    (openNormalQuotientProj hWV) (sqOpenQuotientMarking h W)
    (sqOpenQuotientFreeEvaluation_surjective h W)
    (sqOpenQuotientFreeEvaluation_surjective h V)
    hninj

end

end GQ2.Dyadic.Count
