/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using OpenAI Codex
-/
import GQ2.Dyadic.Count.H3FiniteBarFoxComparison

/-!
# The section-dependent reverse finite bar--Fox comparison

At a finite quotient generated by a marking `m : I → Q`, choose the normalized word section
`relationSection` of `FreeGroup.lift m`.  Fox differentiation of the chosen word for `q` sends
the bar edge `[q]` back to a path in the marked Cayley graph.  The failure of the section to be
multiplicative is the Schreier factor `relationDefect q r`, so the reverse image of the boundary
of `[q|r]` is exactly the universal Fox row of that factor.

This gives the honest reverse chain map through the **full** relation kernel.  It also gives a
chain homotopy between the reverse--forward composite on presentation one-cells and the identity.
Both identities are valid for arbitrary section choices and require no cohomological exactness.

For an actual finite quotient of `DSq h`, the marked generators generate algebraically, so this
construction applies without an extra hypothesis.  The remaining obstruction is now explicit:
to reach `SqFiniteToCompletedBarFoxAssembly`, the full relation-kernel cells must be coordinatized
by the single improved relator, compatibly under quotient refinement.  Such a coordinatization is
not supplied here (and cannot be obtained from pointwise finite strong freeness, which already
fails at the trivial quotient).
-/

namespace GQ2.Dyadic.Count

noncomputable section

open GQ2.ContCoh GQ2.FoxH
open GQ2.Dyadic.SqCore

variable {Q I : Type} [Group Q]

/-! ## Fox paths attached to a normalized word section -/

/-- The marked one-boundary commutes with regular translation. -/
theorem finiteMarkedBoundaryOne_translate (m : I → Q) (g : Q)
    (c : RegularModTwoRelationModule Q I) :
    finiteMarkedBoundaryOne m (regularModTwoTranslate Q I g c) =
      regularModTwoTranslate Q Unit g (finiteMarkedBoundaryOne m c) := by
  classical
  induction c using Finsupp.induction with
  | zero => simp
  | single_add p a c hp ha ih =>
      rcases p with ⟨q, i⟩
      simp only [map_add, regularModTwoTranslate_single, ih,
        finiteMarkedBoundaryOne_single]
      rw [mul_assoc]

/-- Successive regular translations multiply their translating elements. -/
theorem regularModTwoTranslate_comp (g q : Q)
    (c : RegularModTwoRelationModule Q I) :
    regularModTwoTranslate Q I g (regularModTwoTranslate Q I q c) =
      regularModTwoTranslate Q I (g * q) c := by
  classical
  ext p
  rcases p with ⟨r, i⟩
  simp only [regularModTwoTranslate_apply, mul_inv_rev, mul_assoc]

/-- Fox differentiation of the normalized section word gives a marked path from `1` to `q`. -/
def finiteSectionPath (m : I → Q)
    (heval : Function.Surjective (FreeGroup.lift m)) (q : Q) :
    RegularModTwoRelationModule Q I :=
  modTwoFoxDerivative m (relationSection heval q)

/-- The boundary of the section path is `[q] + [1]`. -/
theorem finiteMarkedBoundaryOne_sectionPath
    (m : I → Q) (heval : Function.Surjective (FreeGroup.lift m)) (q : Q) :
    finiteMarkedBoundaryOne m (finiteSectionPath m heval q) =
      Finsupp.single (q, ()) 1 + Finsupp.single (1, ()) 1 := by
  rw [finiteSectionPath, finiteMarkedBoundaryOne_modTwoFoxDerivative,
    relationSection_spec]

/-- Reverse a bar one-chain by replacing every edge `g[q]` with the translate by `g` of the
chosen section path for `q`. -/
def finiteBarToMarkedOne (m : I → Q)
    (heval : Function.Surjective (FreeGroup.lift m)) :
    FiniteModTwoBarChainOne Q →ₗ[ZMod 2] RegularModTwoRelationModule Q I :=
  (Finsupp.lsum (ZMod 2)) fun p : Q × Q =>
    LinearMap.toSpanSingleton (ZMod 2) _
      (regularModTwoTranslate Q I p.1 (finiteSectionPath m heval p.2))

@[simp] theorem finiteBarToMarkedOne_single
    (m : I → Q) (heval : Function.Surjective (FreeGroup.lift m))
    (g q : Q) (a : ZMod 2) :
    finiteBarToMarkedOne m heval (Finsupp.single (g, q) a) =
      a • regularModTwoTranslate Q I g (finiteSectionPath m heval q) := by
  classical
  rw [finiteBarToMarkedOne, Finsupp.lsum_single]
  simp

/-- The section-dependent reverse map is a chain map in degree one. -/
theorem finiteBarToMarkedOne_boundary
    (m : I → Q) (heval : Function.Surjective (FreeGroup.lift m))
    (c : FiniteModTwoBarChainOne Q) :
    finiteMarkedBoundaryOne m (finiteBarToMarkedOne m heval c) =
      finiteModTwoBarBoundaryOne c := by
  classical
  induction c using Finsupp.induction with
  | zero => simp
  | single_add p a c hp ha ih =>
      rcases p with ⟨g, q⟩
      simp only [map_add, ih, finiteBarToMarkedOne_single,
        finiteModTwoBarBoundaryOne_single, map_smul,
        finiteMarkedBoundaryOne_translate,
        finiteMarkedBoundaryOne_sectionPath,
        regularModTwoTranslate_single, mul_one]
      simp [smul_add, Finsupp.smul_single, smul_eq_mul]

/-! ## The universal relation-kernel two-cells -/

/-- The finite Fox boundary whose relator alphabet is the entire relation kernel. -/
def finiteUniversalRelationFoxBoundary
    (m : I → Q) :
    ModTwoFoxBoundary Q
      (RegularModTwoRelationModule Q (FreeRelationKernel m))
      (RegularModTwoRelationModule Q I) :=
  finiteLevelModTwoFoxBoundary m fun r : FreeRelationKernel m => r.1

/-- Fox differentiation of the Schreier factor is the three-edge section defect. -/
theorem modTwoFoxDerivative_relationDefect
    (m : I → Q) (heval : Function.Surjective (FreeGroup.lift m)) (q r : Q) :
    modTwoFoxDerivative m (relationDefect heval q r).1 =
      finiteSectionPath m heval q +
        regularModTwoTranslate Q I q (finiteSectionPath m heval r) +
          finiteSectionPath m heval (q * r) := by
  simp only [modTwoFoxDerivative, relationDefect, Subgroup.coe_mk,
    map_mul, map_inv, WordLift.mul_u, WordLift.mul_g, WordLift.inv_u,
    lift_foxLift_g, relationSection_spec, finiteSectionPath]
  rw [smul_neg, ← mul_smul]
  simp only [mul_inv_cancel, one_smul, ZModModule.neg_eq_self]
  rfl

/-- Replace a bar two-cell `g[q|r]` by the translated Schreier relation factor
`g · (s(q)s(r)s(qr)⁻¹)`. -/
def finiteBarToUniversalRelationTwo (m : I → Q)
    (heval : Function.Surjective (FreeGroup.lift m)) :
    FiniteModTwoBarChainTwo Q →ₗ[ZMod 2]
      RegularModTwoRelationModule Q (FreeRelationKernel m) :=
  (Finsupp.lsum (ZMod 2)) fun p : Q × (Q × Q) =>
    LinearMap.toSpanSingleton (ZMod 2) _
      (Finsupp.single (p.1, relationDefect heval p.2.1 p.2.2) 1)

@[simp] theorem finiteBarToUniversalRelationTwo_single
    (m : I → Q) (heval : Function.Surjective (FreeGroup.lift m))
    (g q r : Q) (a : ZMod 2) :
    finiteBarToUniversalRelationTwo m heval (Finsupp.single (g, (q, r)) a) =
      Finsupp.single (g, relationDefect heval q r) a := by
  classical
  rw [finiteBarToUniversalRelationTwo, Finsupp.lsum_single]
  simp [LinearMap.toSpanSingleton_apply, smul_eq_mul]

/-- **Reverse degree-two chain identity.** The reverse image of the bar boundary of every
two-chain is exactly the universal Fox boundary of its Schreier relation factor. -/
theorem finiteBarToMarkedOne_boundaryTwo
    (m : I → Q) (heval : Function.Surjective (FreeGroup.lift m))
    (c : FiniteModTwoBarChainTwo Q) :
    finiteBarToMarkedOne m heval (finiteModTwoBarBoundaryTwo c) =
      (finiteUniversalRelationFoxBoundary m).map
        (finiteBarToUniversalRelationTwo m heval c) := by
  classical
  induction c using Finsupp.induction with
  | zero => simp
  | single_add p a c hp ha ih =>
      rcases p with ⟨g, q, r⟩
      simp only [map_add, ih, finiteModTwoBarBoundaryTwo_single,
        finiteBarToMarkedOne_single,
        finiteBarToUniversalRelationTwo_single,
        finiteUniversalRelationFoxBoundary,
        finiteLevelModTwoFoxBoundary_single]
      rw [modTwoFoxDerivative_relationDefect]
      simp only [map_add, regularModTwoTranslate_comp]
      simp only [smul_add]
      abel

/-! ## A reverse--forward homotopy on presentation one-cells -/

/-- The kernel word comparing the chosen section word for `m i` with the generator letter
itself. -/
def finiteGeneratorSectionDefect (m : I → Q)
    (heval : Function.Surjective (FreeGroup.lift m)) (i : I) :
    FreeRelationKernel m :=
  ⟨relationSection heval (m i) * (FreeGroup.of i)⁻¹, by
    rw [MonoidHom.mem_ker, map_mul, map_inv, relationSection_spec]
    simp⟩

/-- A presentation one-cell is sent to the translated relation cell comparing the chosen
section path of its marked value with that generator edge. -/
def finiteMarkedOneToUniversalRelationTwo (m : I → Q)
    (heval : Function.Surjective (FreeGroup.lift m)) :
    RegularModTwoRelationModule Q I →ₗ[ZMod 2]
      RegularModTwoRelationModule Q (FreeRelationKernel m) :=
  (Finsupp.lsum (ZMod 2)) fun p : Q × I =>
    LinearMap.toSpanSingleton (ZMod 2) _
      (Finsupp.single (p.1, finiteGeneratorSectionDefect m heval p.2) 1)

@[simp] theorem finiteMarkedOneToUniversalRelationTwo_single
    (m : I → Q) (heval : Function.Surjective (FreeGroup.lift m))
    (g : Q) (i : I) (a : ZMod 2) :
    finiteMarkedOneToUniversalRelationTwo m heval (Finsupp.single (g, i) a) =
      Finsupp.single (g, finiteGeneratorSectionDefect m heval i) a := by
  classical
  rw [finiteMarkedOneToUniversalRelationTwo, Finsupp.lsum_single]
  simp [LinearMap.toSpanSingleton_apply, smul_eq_mul]

/-- Fox differentiation of the generator-section defect is the sum of the chosen section path
and the generator basis edge. -/
theorem modTwoFoxDerivative_finiteGeneratorSectionDefect
    (m : I → Q) (heval : Function.Surjective (FreeGroup.lift m)) (i : I) :
    modTwoFoxDerivative m (finiteGeneratorSectionDefect m heval i).1 =
      finiteSectionPath m heval (m i) + modTwoFoxGenerator (L := Q) i := by
  simp only [modTwoFoxDerivative, finiteGeneratorSectionDefect, Subgroup.coe_mk,
    map_mul, map_inv, WordLift.mul_u, WordLift.inv_u,
    lift_foxLift_g, relationSection_spec, finiteSectionPath]
  rw [FreeGroup.lift_apply_of]
  rw [smul_neg, ← mul_smul]
  simp [foxLift, ZModModule.neg_eq_self]

/-- **Reverse--forward homotopy identity.** On every presentation one-chain, the composite
`presentation → bar → presentation` differs from the identity by the universal Fox boundary
of the generator-section relation cells. -/
theorem finiteBarToMarkedOne_comp_markedToBarOne
    (m : I → Q) (heval : Function.Surjective (FreeGroup.lift m))
    (c : RegularModTwoRelationModule Q I) :
    finiteBarToMarkedOne m heval (finiteMarkedToBarOne m c) + c =
      (finiteUniversalRelationFoxBoundary m).map
        (finiteMarkedOneToUniversalRelationTwo m heval c) := by
  classical
  induction c using Finsupp.induction with
  | zero => simp
  | single_add p a c hp ha ih =>
      rcases p with ⟨g, i⟩
      simp only [map_add, finiteMarkedToBarOne_single,
        finiteBarToMarkedOne_single,
        finiteMarkedOneToUniversalRelationTwo_single,
        finiteUniversalRelationFoxBoundary,
        finiteLevelModTwoFoxBoundary_single]
      rw [modTwoFoxDerivative_finiteGeneratorSectionDefect]
      simp only [map_add]
      have hgen : regularModTwoTranslate Q I g (modTwoFoxGenerator (L := Q) i) =
          Finsupp.single (g, i) 1 := by
        simp [modTwoFoxGenerator]
      rw [hgen]
      simp only [smul_add, Finsupp.smul_single, smul_eq_mul, mul_one]
      change finiteBarToMarkedOne m heval (finiteMarkedToBarOne m c) + c =
        (finiteLevelModTwoFoxBoundary m (fun r : FreeRelationKernel m => r.1)).map
          (finiteMarkedOneToUniversalRelationTwo m heval c) at ih
      rw [← ih]
      abel

/-! ## Actual finite quotients of the improved square core -/

/-- The images of the improved-presentation generators generate every open-normal quotient
algebraically. -/
theorem sqOpenQuotientMarking_closure_eq_top (h : ℕ)
    (V : OpenNormalSubgroup (DSq h : Type)) :
    Subgroup.closure (Set.range (sqOpenQuotientMarking h V)) = ⊤ := by
  letI : DiscreteTopology ((DSq h : Type) ⧸ V.toSubgroup) :=
    Subgroup.instDiscreteTopologyQuotientOfSeparatelyContinuousMul V.toOpenSubgroup
  set H := Subgroup.closure (Set.range (sqOpenQuotientMarking h V)) with hH
  have hle : Subgroup.closure (Set.range (sqGen h)) ≤
      H.comap (QuotientGroup.mk' V.toSubgroup) := by
    rw [Subgroup.closure_le]
    rintro _ ⟨i, rfl⟩
    exact Subgroup.subset_closure ⟨i, rfl⟩
  have hclosed : IsClosed
      ((H.comap (QuotientGroup.mk' V.toSubgroup) :
        Subgroup (DSq h : Type)) : Set (DSq h : Type)) := by
    show IsClosed ((QuotientGroup.mk' V.toSubgroup) ⁻¹'
      (H : Set ((DSq h : Type) ⧸ V.toSubgroup)))
    exact IsClosed.preimage continuous_quotient_mk' (isClosed_discrete _)
  have hall := Subgroup.topologicalClosure_minimal _ hle hclosed
  rw [dsq_topGen h] at hall
  change H = ⊤
  apply eq_top_iff.mpr
  intro q hq
  obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective V.toSubgroup q
  exact hall (Subgroup.mem_top g)

/-- The free-group evaluation at the actual quotient marking is surjective. -/
theorem sqOpenQuotientFreeEvaluation_surjective (h : ℕ)
    (V : OpenNormalSubgroup (DSq h : Type)) :
    Function.Surjective (FreeGroup.lift (sqOpenQuotientMarking h V)) :=
  freeGroup_lift_surjective_of_closure (sqOpenQuotientMarking_closure_eq_top h V)

/-- The section-dependent reverse map on bar one-chains for an actual improved-square quotient. -/
def sqOpenQuotientBarToMarkedOne (h : ℕ)
    (V : OpenNormalSubgroup (DSq h : Type)) :
    FiniteModTwoBarChainOne ((DSq h : Type) ⧸ V.toSubgroup) →ₗ[ZMod 2]
      RegularModTwoRelationModule ((DSq h : Type) ⧸ V.toSubgroup) (Fin (sqRank h)) :=
  finiteBarToMarkedOne (sqOpenQuotientMarking h V)
    (sqOpenQuotientFreeEvaluation_surjective h V)

/-- The actual quotient reverse map is a chain map in degree one. -/
theorem sqOpenQuotientBarToMarkedOne_boundary (h : ℕ)
    (V : OpenNormalSubgroup (DSq h : Type))
    (c : FiniteModTwoBarChainOne ((DSq h : Type) ⧸ V.toSubgroup)) :
    finiteMarkedBoundaryOne (sqOpenQuotientMarking h V)
        (sqOpenQuotientBarToMarkedOne h V c) =
      finiteModTwoBarBoundaryOne c :=
  finiteBarToMarkedOne_boundary _ _ c

end

end GQ2.Dyadic.Count
