/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Codex
-/
import GQ2.Dyadic.Count.HTwoRelationBasis

/-!
# A strongly-free summand criterion for the mod-two relation module

Let `R = ker(F(X) → L)`.  The elementary mod-two relation module is the quotient

`R / (R² [R,R])`.

At a finite quotient this module generally has more generators than the displayed defining
relators: the finite quotient contributes additional relations.  Thus the useful classical
strong-freeness conclusion is not that the whole module is two regular copies, but that the
regular module generated by the displayed relator orbits is a *split summand*.

`StronglyFreeModTwoRelatorSummand` states this conclusion using the explicit quotient.  It
contains an orbit map from the free regular module, a retraction back to that module, and the
equivariance of the retraction.  The main theorem proves that this genuinely stronger,
literature-shaped premise constructs `ModTwoRelationBasisCoordinates`.
-/

namespace GQ2.Dyadic.Count

noncomputable section

open GQ2.FoxH

section ModTwoQuotient

variable {X L : Type} [Group L] (m : X → L)

/-- Squares and commutators generating `R² [R,R]` inside the free relation kernel. -/
def freeRelationModTwoGenerators : Set (FreeRelationKernel m) :=
  {x | (∃ r : FreeRelationKernel m, x = r ^ 2) ∨
    ∃ r s : FreeRelationKernel m, x = r * s * r⁻¹ * s⁻¹}

/-- The characteristic subgroup `R² [R,R]` of the free relation kernel. -/
def freeRelationModTwoSubgroup : Subgroup (FreeRelationKernel m) :=
  Subgroup.normalClosure (freeRelationModTwoGenerators m)

instance freeRelationModTwoSubgroup_normal :
    (freeRelationModTwoSubgroup m).Normal :=
  Subgroup.normalClosure_normal

/-- The elementary mod-two relation quotient `R / (R² [R,R])`. -/
abbrev FreeRelationModTwoQuotient :=
  FreeRelationKernel m ⧸ freeRelationModTwoSubgroup m

theorem freeRelation_sq_mem_modTwoSubgroup (r : FreeRelationKernel m) :
    r ^ 2 ∈ freeRelationModTwoSubgroup m :=
  Subgroup.subset_normalClosure (Or.inl ⟨r, rfl⟩)

theorem freeRelation_commutator_mem_modTwoSubgroup
    (r s : FreeRelationKernel m) :
    r * s * r⁻¹ * s⁻¹ ∈ freeRelationModTwoSubgroup m :=
  Subgroup.subset_normalClosure (Or.inr ⟨r, s, rfl⟩)

@[simp] theorem freeRelationModTwoQuotient_sq
    (r : FreeRelationKernel m) :
    QuotientGroup.mk' (freeRelationModTwoSubgroup m) (r ^ 2) = 1 := by
  rw [QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]
  exact freeRelation_sq_mem_modTwoSubgroup m r

@[simp] theorem freeRelationModTwoQuotient_commutator
    (r s : FreeRelationKernel m) :
    QuotientGroup.mk' (freeRelationModTwoSubgroup m)
      (r * s * r⁻¹ * s⁻¹) = 1 := by
  rw [QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]
  exact freeRelation_commutator_mem_modTwoSubgroup m r s

end ModTwoQuotient

section StrongFreeness

variable {X rel L : Type} [Group L] {m : X → L}

/-- A classical strongly-free conclusion at a finite target: the regular module generated by
the displayed relator orbits is a split summand of `R / (R²[R,R])`.

The `orbit` equation identifies every reachable regular basis vector with the corresponding
conjugate of the displayed relator.  `retract` makes these classes linearly independent, not
merely generators of a quotient.  The last field says the retraction is `L`-equivariant. -/
structure StronglyFreeModTwoRelatorSummand (w : rel → FreeGroup X)
    (hrel : ∀ k, FreeGroup.lift m (w k) = 1) where
  orbit : Multiplicative (RegularModTwoRelationModule L rel) →*
    FreeRelationModTwoQuotient m
  coordinates : FreeRelationModTwoQuotient m →*
    Multiplicative (RegularModTwoRelationModule L rel)
  retract : coordinates.comp orbit = MonoidHom.id _
  orbit_basis : ∀ (f : FreeGroup X) (k : rel),
    orbit (Multiplicative.ofAdd
      (Finsupp.single (FreeGroup.lift m f, k) (1 : ZMod 2))) =
      QuotientGroup.mk' (freeRelationModTwoSubgroup m)
        (relationKernelConj m f
          ⟨w k, MonoidHom.mem_ker.mpr (hrel k)⟩)
  conjugation : ∀ (f : FreeGroup X) (s : FreeRelationKernel m),
    coordinates (QuotientGroup.mk' (freeRelationModTwoSubgroup m)
      (relationKernelConj m f s)) = Multiplicative.ofAdd
        (regularModTwoTranslate L rel (FreeGroup.lift m f)
          (Multiplicative.toAdd
            (coordinates (QuotientGroup.mk' (freeRelationModTwoSubgroup m) s))))

/-- The orbit map in a strongly-free summand is genuinely injective.  This is the extra
independence content absent from `ModTwoRelationBasisCoordinates`. -/
theorem StronglyFreeModTwoRelatorSummand.orbit_injective
    {w : rel → FreeGroup X} {hrel : ∀ k, FreeGroup.lift m (w k) = 1}
    (B : StronglyFreeModTwoRelatorSummand w hrel) : Function.Injective B.orbit := by
  apply Function.LeftInverse.injective (g := B.coordinates)
  intro c
  change (B.coordinates.comp B.orbit) c = c
  rw [B.retract]
  rfl

/-- A strongly-free split relation summand supplies the coordinate projection used by the
transgression argument. -/
def StronglyFreeModTwoRelatorSummand.toModTwoRelationBasisCoordinates
    {w : rel → FreeGroup X} {hrel : ∀ k, FreeGroup.lift m (w k) = 1}
    (B : StronglyFreeModTwoRelatorSummand w hrel) :
    ModTwoRelationBasisCoordinates w hrel where
  coordinates := B.coordinates.comp
    (QuotientGroup.mk' (freeRelationModTwoSubgroup m))
  conjugation f s := B.conjugation f s
  relator k := by
    let e : Multiplicative (RegularModTwoRelationModule L rel) :=
      Multiplicative.ofAdd (Finsupp.single ((1 : L), k) (1 : ZMod 2))
    have hret : B.coordinates (B.orbit e) = e := by
      change (B.coordinates.comp B.orbit) e = e
      rw [B.retract]
      rfl
    have horbit := B.orbit_basis (1 : FreeGroup X) k
    have horbit' : B.orbit e =
        QuotientGroup.mk' (freeRelationModTwoSubgroup m)
          ⟨w k, MonoidHom.mem_ker.mpr (hrel k)⟩ := by
      simpa [e, relationKernelConj] using horbit
    change B.coordinates
      (QuotientGroup.mk' (freeRelationModTwoSubgroup m)
        ⟨w k, MonoidHom.mem_ker.mpr (hrel k)⟩) = e
    rw [← horbit']
    exact hret

/-- In particular, a strongly-free summand gives arbitrary relation characters in every
exponent-two coefficient module. -/
theorem relationModuleRelatorSurjective_of_stronglyFreeModTwoRelatorSummand
    {A : Type} [AddCommGroup A] [DistribMulAction L A]
    {w : rel → FreeGroup X} {hrel : ∀ k, FreeGroup.lift m (w k) = 1}
    (B : StronglyFreeModTwoRelatorSummand w hrel)
    (hA₂ : ∀ a : A, a + a = 0) :
    RelationModuleRelatorSurjective (A := A) w hrel :=
  relationModuleRelatorSurjective_of_modTwoRelationBasis
    B.toModTwoRelationBasisCoordinates hA₂

end StrongFreeness

end

end GQ2.Dyadic.Count
