/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Codex
-/
import GQ2.Dyadic.Count.HTwoRelationBasis

/-!
# A strongly-free summand criterion for the mod-two relation module

Let `R = ker(F(X) → L)`.  The elementary mod-two relation module is the quotient

`R / (R² [R,R])`.

At a finite quotient this module generally has more generators than the displayed defining
relators: the finite quotient contributes additional relations.  Thus the useful classical
strong-freeness conclusion is not that the whole module is two regular copies, but that the
regular module generated by the displayed relator orbits is a *split summand*.

`StronglyFreeModTwoRelatorSummand` states this conclusion using the explicit quotient.  It
contains an orbit map from the free regular module, a retraction back to that module, and the
equivariance of the retraction.  It is the literature-shaped version of
`ModTwoRelationBasisCoordinates`; for a generating marking the two existence statements are
proved equivalent in `HTwoFoxStronglyFree`.
-/

namespace GQ2.Dyadic.Count

noncomputable section

open GQ2.FoxH

section ModTwoQuotient

variable {X L : Type} [Group L] (m : X → L)

/-- Squares and commutators generating `R² [R,R]` inside the free relation kernel. -/
def freeRelationModTwoGenerators : Set (FreeRelationKernel m) :=
  {x | (∃ r : FreeRelationKernel m, x = r ^ 2) ∨
    ∃ r s : FreeRelationKernel m, x = r * s * r⁻¹ * s⁻¹}

/-- The characteristic subgroup `R² [R,R]` of the free relation kernel. -/
def freeRelationModTwoSubgroup : Subgroup (FreeRelationKernel m) :=
  Subgroup.normalClosure (freeRelationModTwoGenerators m)

instance freeRelationModTwoSubgroup_normal :
    (freeRelationModTwoSubgroup m).Normal :=
  Subgroup.normalClosure_normal

/-- The elementary mod-two relation quotient `R / (R² [R,R])`. -/
abbrev FreeRelationModTwoQuotient :=
  FreeRelationKernel m ⧸ freeRelationModTwoSubgroup m

/-- The canonical map `R → R/(R²[R,R])`. -/
def freeRelationModTwoMk : FreeRelationKernel m →* FreeRelationModTwoQuotient m :=
  QuotientGroup.mk' (freeRelationModTwoSubgroup m)

theorem freeRelationModTwoMk_surjective :
    Function.Surjective (freeRelationModTwoMk m) :=
  QuotientGroup.mk'_surjective _

theorem freeRelation_sq_mem_modTwoSubgroup (r : FreeRelationKernel m) :
    r ^ 2 ∈ freeRelationModTwoSubgroup m :=
  Subgroup.subset_normalClosure (Or.inl ⟨r, rfl⟩)

theorem freeRelation_commutator_mem_modTwoSubgroup
    (r s : FreeRelationKernel m) :
    r * s * r⁻¹ * s⁻¹ ∈ freeRelationModTwoSubgroup m :=
  Subgroup.subset_normalClosure (Or.inr ⟨r, s, rfl⟩)

@[simp] theorem freeRelationModTwoQuotient_sq
    (r : FreeRelationKernel m) :
    QuotientGroup.mk' (freeRelationModTwoSubgroup m) (r ^ 2) = 1 := by
  rw [QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]
  exact freeRelation_sq_mem_modTwoSubgroup m r

@[simp] theorem freeRelationModTwoQuotient_commutator
    (r s : FreeRelationKernel m) :
    QuotientGroup.mk' (freeRelationModTwoSubgroup m)
      (r * s * r⁻¹ * s⁻¹) = 1 := by
  rw [QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]
  exact freeRelation_commutator_mem_modTwoSubgroup m r s

/-- Universal descent from `R/(R²[R,R])`: every homomorphism from the relation kernel to a
commutative exponent-two group factors through the explicit quotient. -/
def freeRelationModTwoLift {B : Type} [CommGroup B]
    (f : FreeRelationKernel m →* B) (hB₂ : ∀ b : B, b ^ 2 = 1) :
    FreeRelationModTwoQuotient m →* B := by
  refine QuotientGroup.lift (freeRelationModTwoSubgroup m) f ?_
  apply Subgroup.normalClosure_le_normal
  intro x hx
  rcases hx with ⟨r, rfl⟩ | ⟨r, s, rfl⟩
  · change f (r ^ 2) = 1
    rw [map_pow]
    exact hB₂ _
  · change f (r * s * r⁻¹ * s⁻¹) = 1
    simp

/-- The descended homomorphism agrees with the original map on the relation kernel. -/
@[simp] theorem freeRelationModTwoLift_mk {B : Type} [CommGroup B]
    (f : FreeRelationKernel m →* B) (hB₂ : ∀ b : B, b ^ 2 = 1)
    (r : FreeRelationKernel m) :
    freeRelationModTwoLift m f hB₂ (freeRelationModTwoMk m r) = f r := by
  rfl

/-- Homomorphism-level factorization through the explicit mod-two relation quotient. -/
theorem freeRelationModTwoLift_comp_mk {B : Type} [CommGroup B]
    (f : FreeRelationKernel m →* B) (hB₂ : ∀ b : B, b ^ 2 = 1) :
    (freeRelationModTwoLift m f hB₂).comp (freeRelationModTwoMk m) = f := by
  ext r
  exact freeRelationModTwoLift_mk m f hB₂ r

/-- Uniqueness in the universal property: a map out of the quotient is determined by its
restriction to the relation kernel. -/
theorem freeRelationModTwoLift_unique {B : Type} [CommGroup B]
    (f : FreeRelationKernel m →* B) (hB₂ : ∀ b : B, b ^ 2 = 1)
    (g : FreeRelationModTwoQuotient m →* B)
    (hg : g.comp (freeRelationModTwoMk m) = f) :
    g = freeRelationModTwoLift m f hB₂ := by
  apply MonoidHom.ext
  intro x
  obtain ⟨r, hr⟩ := freeRelationModTwoMk_surjective m x
  rw [← hr]
  change (g.comp (freeRelationModTwoMk m)) r = _
  rw [hg]
  exact (freeRelationModTwoLift_mk m f hB₂ r).symm

end ModTwoQuotient

section QuotientFactorizations

variable {X rel L A : Type} [Group L] [AddCommGroup A] [DistribMulAction L A]
  {m : X → L} {w : rel → FreeGroup X}
  {hrel : ∀ k, FreeGroup.lift m (w k) = 1}

/-- Every coordinate map in the older relation-basis interface canonically descends to the
genuine mod-two relation quotient. -/
def ModTwoRelationBasisCoordinates.quotientCoordinates
    (B : ModTwoRelationBasisCoordinates w hrel) :
    FreeRelationModTwoQuotient m →*
      Multiplicative (RegularModTwoRelationModule L rel) :=
  freeRelationModTwoLift m B.coordinates (fun c => by
    apply Multiplicative.toAdd.injective
    simp only [toAdd_pow, toAdd_one, two_nsmul]
    ext p
    exact (by decide : ∀ a : ZMod 2, a + a = 0) _)

/-- The descended map recovers the original relation-basis coordinates. -/
@[simp] theorem ModTwoRelationBasisCoordinates.quotientCoordinates_mk
    (B : ModTwoRelationBasisCoordinates w hrel) (s : FreeRelationKernel m) :
    B.quotientCoordinates (freeRelationModTwoMk m s) = B.coordinates s :=
  freeRelationModTwoLift_mk m _ _ _

/-- Homomorphism-level factorization of any mod-two basis coordinate map. -/
theorem ModTwoRelationBasisCoordinates.quotientCoordinates_comp_mk
    (B : ModTwoRelationBasisCoordinates w hrel) :
    B.quotientCoordinates.comp (freeRelationModTwoMk m) = B.coordinates :=
  freeRelationModTwoLift_comp_mk m _ _

/-- An exponent-two relation character factors canonically through `R/(R²[R,R])`. -/
def FreeRelationCharacter.modTwoFactor
    (chi : FreeRelationCharacter m A) (hA₂ : ∀ a : A, a + a = 0) :
    FreeRelationModTwoQuotient m →* Multiplicative A :=
  freeRelationModTwoLift m chi.toMonoidHom (fun b => by
    apply Multiplicative.toAdd.injective
    simpa only [toAdd_pow, toAdd_one, two_nsmul] using
      hA₂ (Multiplicative.toAdd b))

/-- The quotient factor recovers the original relation character on `R`. -/
@[simp] theorem FreeRelationCharacter.modTwoFactor_mk
    (chi : FreeRelationCharacter m A) (hA₂ : ∀ a : A, a + a = 0)
    (s : FreeRelationKernel m) :
    chi.modTwoFactor hA₂ (freeRelationModTwoMk m s) = chi.toMonoidHom s :=
  freeRelationModTwoLift_mk m _ _ _

/-- Homomorphism-level factorization of an elementary relation character. -/
theorem FreeRelationCharacter.modTwoFactor_comp_mk
    (chi : FreeRelationCharacter m A) (hA₂ : ∀ a : A, a + a = 0) :
    (chi.modTwoFactor hA₂).comp (freeRelationModTwoMk m) = chi.toMonoidHom :=
  freeRelationModTwoLift_comp_mk m _ _

end QuotientFactorizations

section StrongFreeness

variable {X rel L : Type} [Group L] {m : X → L}

/-- A classical strongly-free conclusion at a finite target: the regular module generated by
the displayed relator orbits is a split summand of `R / (R²[R,R])`.

The `orbit` equation identifies every reachable regular basis vector with the corresponding
conjugate of the displayed relator.  `retract` makes these classes linearly independent, not
merely generators of a quotient.  The last field says the retraction is `L`-equivariant. -/
structure StronglyFreeModTwoRelatorSummand (w : rel → FreeGroup X)
    (hrel : ∀ k, FreeGroup.lift m (w k) = 1) where
  orbit : Multiplicative (RegularModTwoRelationModule L rel) →*
    FreeRelationModTwoQuotient m
  coordinates : FreeRelationModTwoQuotient m →*
    Multiplicative (RegularModTwoRelationModule L rel)
  retract : coordinates.comp orbit = MonoidHom.id _
  orbit_basis : ∀ (f : FreeGroup X) (k : rel),
    orbit (Multiplicative.ofAdd
      (Finsupp.single (FreeGroup.lift m f, k) (1 : ZMod 2))) =
      QuotientGroup.mk' (freeRelationModTwoSubgroup m)
        (relationKernelConj m f
          ⟨w k, MonoidHom.mem_ker.mpr (hrel k)⟩)
  conjugation : ∀ (f : FreeGroup X) (s : FreeRelationKernel m),
    coordinates (QuotientGroup.mk' (freeRelationModTwoSubgroup m)
      (relationKernelConj m f s)) = Multiplicative.ofAdd
        (regularModTwoTranslate L rel (FreeGroup.lift m f)
          (Multiplicative.toAdd
            (coordinates (QuotientGroup.mk' (freeRelationModTwoSubgroup m) s))))

/-- The orbit map in a strongly-free summand is genuinely injective.  This is the extra
independence content absent from `ModTwoRelationBasisCoordinates`. -/
theorem StronglyFreeModTwoRelatorSummand.orbit_injective
    {w : rel → FreeGroup X} {hrel : ∀ k, FreeGroup.lift m (w k) = 1}
    (B : StronglyFreeModTwoRelatorSummand w hrel) : Function.Injective B.orbit := by
  apply Function.LeftInverse.injective (g := B.coordinates)
  intro c
  change (B.coordinates.comp B.orbit) c = c
  rw [B.retract]
  rfl

/-- A strongly-free split relation summand supplies the coordinate projection used by the
transgression argument. -/
def StronglyFreeModTwoRelatorSummand.toModTwoRelationBasisCoordinates
    {w : rel → FreeGroup X} {hrel : ∀ k, FreeGroup.lift m (w k) = 1}
    (B : StronglyFreeModTwoRelatorSummand w hrel) :
    ModTwoRelationBasisCoordinates w hrel where
  coordinates := B.coordinates.comp
    (QuotientGroup.mk' (freeRelationModTwoSubgroup m))
  conjugation f s := B.conjugation f s
  relator k := by
    let e : Multiplicative (RegularModTwoRelationModule L rel) :=
      Multiplicative.ofAdd (Finsupp.single ((1 : L), k) (1 : ZMod 2))
    have hret : B.coordinates (B.orbit e) = e := by
      change (B.coordinates.comp B.orbit) e = e
      rw [B.retract]
      rfl
    have horbit := B.orbit_basis (1 : FreeGroup X) k
    have horbit' : B.orbit e =
        QuotientGroup.mk' (freeRelationModTwoSubgroup m)
          ⟨w k, MonoidHom.mem_ker.mpr (hrel k)⟩ := by
      simpa [e, relationKernelConj] using horbit
    change B.coordinates
      (QuotientGroup.mk' (freeRelationModTwoSubgroup m)
        ⟨w k, MonoidHom.mem_ker.mpr (hrel k)⟩) = e
    rw [← horbit']
    exact hret

/-- In particular, a strongly-free summand gives arbitrary relation characters in every
exponent-two coefficient module. -/
theorem relationModuleRelatorSurjective_of_stronglyFreeModTwoRelatorSummand
    {A : Type} [AddCommGroup A] [DistribMulAction L A]
    {w : rel → FreeGroup X} {hrel : ∀ k, FreeGroup.lift m (w k) = 1}
    (B : StronglyFreeModTwoRelatorSummand w hrel)
    (hA₂ : ∀ a : A, a + a = 0) :
    RelationModuleRelatorSurjective (A := A) w hrel :=
  relationModuleRelatorSurjective_of_modTwoRelationBasis
    B.toModTwoRelationBasisCoordinates hA₂

end StrongFreeness

end

end GQ2.Dyadic.Count
