/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Codex
-/
import GQ2.Dyadic.Count.HTwoRelationModule

/-!
# A mod-two relation-basis criterion

For a surjective marking `F(X) → L`, the classical mod-two relation module is generated by
the conjugates of the defining relators.  Strong freeness says more: these conjugates form a
free `𝔽₂[L]`-basis.  This file isolates the part of that conclusion needed by the finite
relator-realization argument.

`ModTwoRelationBasisCoordinates` is an explicit equivariant coordinate map

`R = ker(F(X) → L) → ⨁ (L × rel), 𝔽₂`

which sends each displayed relator to the basis vector at `(1,k)`.  This is strictly stronger
than relator-evaluation surjectivity and contains no coefficient module, cocycle, cohomology
group, or word cokernel.  It is the direct formal target for a future strongly-free/Labute
theorem.  The main result constructs, for every exponent-two coefficient module and every
requested relator vector, the corresponding equivariant relation character.
-/

namespace GQ2.Dyadic.Count

noncomputable section

open GQ2.FoxH

section RegularModule

variable (L rel : Type) [Group L]

/-- The underlying additive group of the free mod-two `L`-module on `rel`. -/
abbrev RegularModTwoRelationModule := (L × rel) →₀ ZMod 2

/-- Left translation on the regular basis: the coefficient at `(h,k)` after translation by
`g` is the old coefficient at `(g⁻¹h,k)`. -/
def regularModTwoTranslate (g : L) :
    RegularModTwoRelationModule L rel ≃+
      RegularModTwoRelationModule L rel :=
  Finsupp.domCongr ((Equiv.mulLeft g).prodCongr (Equiv.refl rel))

@[simp] theorem regularModTwoTranslate_apply (g h : L) (k : rel)
    (c : RegularModTwoRelationModule L rel) :
    regularModTwoTranslate L rel g c (h, k) = c (g⁻¹ * h, k) := by
  rfl

@[simp] theorem regularModTwoTranslate_single (g h : L) (k : rel) (a : ZMod 2) :
    regularModTwoTranslate L rel g (Finsupp.single (h, k) a) =
      Finsupp.single (g * h, k) a := by
  classical
  ext p
  rcases p with ⟨p, j⟩
  rw [regularModTwoTranslate_apply]
  by_cases hp : (g⁻¹ * p, j) = (h, k)
  · have hp' : (p, j) = (g * h, k) := by
      have hp2 : j = k := congrArg (fun x : L × rel => x.2) hp
      apply Prod.ext
      · simpa using congrArg (fun x => g * x)
          (congrArg (fun x : L × rel => x.1) hp)
      · exact hp2
    simp [hp, hp']
  · have hp' : (p, j) ≠ (g * h, k) := by
      intro hp'
      have hp2 : j = k := congrArg (fun x : L × rel => x.2) hp'
      apply hp
      apply Prod.ext
      · simpa using congrArg (fun x => g⁻¹ * x)
          (congrArg (fun x : L × rel => x.1) hp')
      · exact hp2
    simp [hp, hp']

end RegularModule

section BasisCoordinates

variable {X rel L : Type} [Group L] {m : X → L}

/-- Explicit free-regular coordinates on the mod-two relation module.  A genuine theorem that
the displayed relator orbits form a split regular summand supplies this structure by retracting
`R/(R²[R,R])` onto that summand; only the resulting coordinate projection is needed below. -/
structure ModTwoRelationBasisCoordinates (w : rel → FreeGroup X)
    (hrel : ∀ k, FreeGroup.lift m (w k) = 1) where
  coordinates : FreeRelationKernel m →*
    Multiplicative (RegularModTwoRelationModule L rel)
  conjugation : ∀ (f : FreeGroup X) (s : FreeRelationKernel m),
    coordinates (relationKernelConj m f s) = Multiplicative.ofAdd
      (regularModTwoTranslate L rel (FreeGroup.lift m f)
        (Multiplicative.toAdd (coordinates s)))
  relator : ∀ k, coordinates ⟨w k, MonoidHom.mem_ker.mpr (hrel k)⟩ =
    Multiplicative.ofAdd (Finsupp.single (1, k) 1)

end BasisCoordinates

section Evaluation

variable {L rel A : Type} [Group L] [AddCommGroup A] [DistribMulAction L A]

/-- Evaluate a regular relation-module vector at requested relator values. -/
def regularModTwoRelationEval (hA₂ : ∀ a : A, a + a = 0) (r : rel → A) :
    RegularModTwoRelationModule L rel →+ A := by
  letI : Module (ZMod 2) A :=
    AddCommGroup.zmodModule (fun a => by simpa [two_nsmul] using hA₂ a)
  exact ((Finsupp.lsum (ZMod 2)) fun p : L × rel =>
    LinearMap.toSpanSingleton (ZMod 2) A (p.1 • r p.2)).toAddMonoidHom

@[simp] theorem regularModTwoRelationEval_single
    (hA₂ : ∀ a : A, a + a = 0) (r : rel → A)
    (g : L) (k : rel) (a : ZMod 2) :
    regularModTwoRelationEval hA₂ r (Finsupp.single (g, k) a) =
      a.val • (g • r k) := by
  letI : Module (ZMod 2) A :=
    AddCommGroup.zmodModule (fun a => by simpa [two_nsmul] using hA₂ a)
  change ((Finsupp.lsum (ZMod 2)) fun p : L × rel =>
    LinearMap.toSpanSingleton (ZMod 2) A (p.1 • r p.2))
      (Finsupp.single (g, k) a) = _
  rw [Finsupp.lsum_single]
  change a • (g • r k) = a.val • (g • r k)
  rfl

@[simp] theorem regularModTwoRelationEval_basis
    (hA₂ : ∀ a : A, a + a = 0) (r : rel → A) (k : rel) :
    regularModTwoRelationEval hA₂ r
      (Finsupp.single ((1 : L), k) (1 : ZMod 2)) = r k := by
  rw [regularModTwoRelationEval_single]
  change (1 : ℕ) • ((1 : L) • r k) = r k
  simp

/-- Evaluation intertwines regular left translation with the given `L`-action. -/
theorem regularModTwoRelationEval_translate
    (hA₂ : ∀ a : A, a + a = 0) (r : rel → A) (g : L)
    (c : RegularModTwoRelationModule L rel) :
    regularModTwoRelationEval hA₂ r (regularModTwoTranslate L rel g c) =
      g • regularModTwoRelationEval hA₂ r c := by
  classical
  induction c using Finsupp.induction with
  | zero => simp
  | single_add p a c hp ha ih =>
      rcases p with ⟨h, k⟩
      rw [map_add, map_add, regularModTwoTranslate_single, map_add,
        regularModTwoRelationEval_single, regularModTwoRelationEval_single, ih]
      have hscalar : a.val • ((g * h) • r k) =
          g • (a.val • (h • r k)) := by
        rw [mul_smul]
        exact (map_nsmul (DistribMulAction.toAddEquiv A g) a.val (h • r k)).symm
      rw [hscalar, smul_add]

end Evaluation

section Character

variable {X rel L A : Type} [Group L] [AddCommGroup A] [DistribMulAction L A]
  {m : X → L} {w : rel → FreeGroup X}
  {hrel : ∀ k, FreeGroup.lift m (w k) = 1}

/-- The relation character obtained by evaluating strongly-free coordinates. -/
def FreeRelationCharacter.ofModTwoRelationBasis
    (B : ModTwoRelationBasisCoordinates w hrel)
    (hA₂ : ∀ a : A, a + a = 0) (r : rel → A) :
    FreeRelationCharacter m A where
  toMonoidHom :=
    (AddMonoidHom.toMultiplicative (regularModTwoRelationEval hA₂ r)).comp B.coordinates
  conjugation f s := by
    change Multiplicative.ofAdd (regularModTwoRelationEval hA₂ r
      (Multiplicative.toAdd (B.coordinates (relationKernelConj m f s)))) = _
    apply Multiplicative.toAdd.injective
    change regularModTwoRelationEval hA₂ r
        (Multiplicative.toAdd (B.coordinates (relationKernelConj m f s))) =
      FreeGroup.lift m f • regularModTwoRelationEval hA₂ r
        (Multiplicative.toAdd (B.coordinates s))
    rw [B.conjugation]
    change regularModTwoRelationEval hA₂ r
        (regularModTwoTranslate L rel (FreeGroup.lift m f)
          (Multiplicative.toAdd (B.coordinates s))) = _
    exact regularModTwoRelationEval_translate hA₂ r _ _

@[simp] theorem FreeRelationCharacter.ofModTwoRelationBasis_val_relator
    (B : ModTwoRelationBasisCoordinates w hrel)
    (hA₂ : ∀ a : A, a + a = 0) (r : rel → A) (k : rel) :
    (FreeRelationCharacter.ofModTwoRelationBasis B hA₂ r).val
      ⟨w k, MonoidHom.mem_ker.mpr (hrel k)⟩ = r k := by
  change regularModTwoRelationEval hA₂ r
    (Multiplicative.toAdd (B.coordinates ⟨w k, MonoidHom.mem_ker.mpr (hrel k)⟩)) = r k
  rw [B.relator]
  exact regularModTwoRelationEval_basis hA₂ r k

/-- A strongly-free coordinate system implies the relation-module evaluation condition used
by the transgression bridge. -/
theorem relationModuleRelatorSurjective_of_modTwoRelationBasis
    (B : ModTwoRelationBasisCoordinates w hrel)
    (hA₂ : ∀ a : A, a + a = 0) :
    RelationModuleRelatorSurjective (A := A) w hrel := by
  intro r
  refine ⟨FreeRelationCharacter.ofModTwoRelationBasis B hA₂ r, ?_⟩
  intro k
  exact FreeRelationCharacter.ofModTwoRelationBasis_val_relator B hA₂ r k

end Character

section BasisRealization

variable {X rel L A : Type} [Group L] [TopologicalSpace L]
  [DiscreteTopology L] [Finite L]
  [AddCommGroup A] [DistribMulAction L A] [Finite A]
  {m : X → L}

/-- End-to-end generic bridge from a strongly-free mod-two coordinate system to finite cocycle
relator realization.  The only additional assumptions are the two target-local resolver facts
which compare the intrinsic profinite words with their chosen integer representatives. -/
theorem relatorRealization_of_modTwoRelationBasis
    (W : rel → PWord X) (w : rel → FreeGroup X)
    (hA₂ : ∀ a : A, a + a = 0)
    (hres : ResolvesAt W w (WordLift A L))
    (hgen : Subgroup.closure (Set.range m) = ⊤)
    (hrel : ∀ k, FreeGroup.lift m (w k) = 1)
    (B : ModTwoRelationBasisCoordinates w hrel)
    (hresExt : ∀ chi : FreeRelationCharacter m A,
      ResolvesAt W w (ModuleExt (relationCharacterCocycle
        (freeGroup_lift_surjective_of_closure hgen) chi))) :
    ∀ r : rel → A, ∃ z : ModuleTwoCocycle L A,
      (fun k => moduleRel (W k) m z) - r ∈
        (heisD1 (A := A) m w).range :=
  relatorRealization_of_relationModule W w hres hgen hrel
    (relationModuleRelatorSurjective_of_modTwoRelationBasis B hA₂) hresExt

end BasisRealization

end


end GQ2.Dyadic.Count
