/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-5
-/
import GQ2.Dyadic.Count.Wild

/-!
# `WordCertificate.hwild`, discharged (dyadic campaign, ticket GR1)

Field 17 of AS1's `WordCertificate`,

  `hwild : IsProP 2 (TameSpec.tameOfSpec n q R hspec).toMonoidHom.ker`,

is a **theorem**, generic in `n`, `q` and `R`.  No branch owes it, and it is not an axiom here.

## The two halves, and where each was proved

The whole file is a composition of work done elsewhere, in two lines each:

* **CB-W's criterion** (`Count/Wild.lean` §7): `hwild` holds **iff** every finite continuous
  quotient of `Γ_R` has `2`-group wild normal closure (`hwild_iff_pro2Core`, resting on
  `isProP_wildPartR_iff_pro2Core` and F3b's `ker_tameOfSpec`).  That is the compactness half of
  the `ℚ₂` argument `GQ2.isProP_wildCore`, transferred; CB-W proved it unconditionally and
  identified it as "the clause that would have to be added to the definition of `GammaR`".
* **GR1's definition** (`GQ2/Dyadic/AdmissibleR.lean` §4): every finite continuous quotient of
  `Γ_R` does have `2`-group wild normal closure (`isPGroup_two_wildNormalClosure`), because
  `Γ_R = F ⧸ N_R` is the admissible limit and every open normal subgroup above `N_R` is
  admissible.  That is the *input* half — the one CB-W correctly reported cannot come from
  relators, and which the campaign's own definition of `Γ_R` supplies.

## Why this was ever in doubt

Until GR1 the Lean `GammaR` was `profinitePresentation (gammaRelators n q R)` — the bare
two-relator presentation — and over *that* group `hwild` is **false** for every branch
(`Count.not_hwild_bare`, CB-W §4; CB-0's `R = 1` special case in `Count/Routine.lean` §6).  The
campaign's `Γ_R` was never that group: plan §1 states it with the clause
`⟪x₀,…,x_n⟫-closure pro-2`, and the simplification campaign's §3 says in terms that *"a bare
two-relator profinite quotient is not interchangeable with this definition"*.  The refutations
are retained, retargeted to `GammaBare`, as the record that the clause is genuinely independent
of the relators.

## Axiom posture

`sorry`-free, **no new axiom**; every headline `#print axioms` is the standard three.  ⚠ `hwild`
is an axiom on the *arithmetic* side — `G_ℚ₂`'s `TameQuotientData.isProP` through B10, and AX4's
structure field for `G_K` — and it must **not** become one on the candidate side.  It has not:
`isProP_wildPartR` below is a theorem, and its trust base is Mathlib plus the standard three.
-/

namespace GQ2.Dyadic

namespace Count

open GQ2 GQ2.Dyadic.Words

/-! ## §1 The pro-`2` wild part

The headline about the group.  `hwild` is the same statement read through the tame
specialization, which is F3b's `ker_tameOfSpec`. -/

section Discharge

variable {n q : ℕ} {R : PWord (Generator n)}

/-- **`W_R` is pro-`2`** — packet Prop. 3.4(1)'s standing hypothesis, now a theorem about the
candidate group.  The closed normal subgroup of `Γ_R` generated by the wild letters is pro-`2`,
for every `n`, every `q` and every relator word `R`.

This is the dyadic analogue of `GQ2.isProP_wildCore` (`GQ2/AdmissibleLimit.lean:375`), assembled
from its two separable halves exactly as CB-W's §7 predicted: the compactness reduction
(`isProP_wildPartR_iff_pro2Core`) fed the admissibility input
(`isPGroup_two_wildNormalClosure`). -/
theorem isProP_wildPartR (n q : ℕ) (R : PWord (Generator n)) : IsProP 2 (wildPartR n q R) :=
  isProP_wildPartR_iff_pro2Core.mpr fun W => isPGroup_two_wildNormalClosure W

/-- **`WordCertificate.hwild`, generically.**  Field 17 of AS1's record, for every `n`, `q`, `R`
and every tame-specialization witness. -/
theorem hwild_of_tameSpecializes (hspec : TameSpec.TameSpecializes n q R) :
    IsProP 2 (TameSpec.tameOfSpec n q R hspec).toMonoidHom.ker :=
  (hwild_iff_pro2Core hspec).mpr fun W => isPGroup_two_wildNormalClosure W

/-- `W_R` is exactly `ker(tame_R)`, so the two readings of `hwild` agree — F3b's
`ker_tameOfSpec`, recorded here for the field's spelling. -/
theorem hwild_eq_isProP_wildPartR (hspec : TameSpec.TameSpecializes n q R) :
    (TameSpec.tameOfSpec n q R hspec).toMonoidHom.ker = wildPartR n q R :=
  TameSpec.ker_tameOfSpec hspec

end Discharge

/-! ## §2 The five frozen branches

Nothing branch-specific is left: `hwild_of_tameSpecializes` is uniform in the word, so each
branch discharge is the generic theorem applied to that branch's Gate-B witness.  They are named
so that AS2–AS5 have handles with the field's spelling, and so that the board can record the
lanes as closed rather than owed. -/

section Branches

/-- **Compact `N`** (the `√−2` branch). -/
theorem hwild_nCompact {q α h : ℕ}
    (hspec : TameSpec.TameSpecializes (2 + 2 * h) q (nCompactW α h)) :
    IsProP 2 (TameSpec.tameOfSpec (2 + 2 * h) q (nCompactW α h) hspec).toMonoidHom.ker :=
  hwild_of_tameSpecializes hspec

/-- **`L`** (the square branch). -/
theorem hwild_lSq {q h : ℕ} (hspec : TameSpec.TameSpecializes (2 * h + 1) q (LSq.lSqW h)) :
    IsProP 2 (TameSpec.tameOfSpec (2 * h + 1) q (LSq.lSqW h) hspec).toMonoidHom.ker :=
  hwild_of_tameSpecializes hspec

/-- **Non-compact `N`**. -/
theorem hwild_npcW {q α r h : ℕ} {e : EtaData}
    (hspec : TameSpec.TameSpecializes (2 + 2 * h) q (Npc.npcW α r h e)) :
    IsProP 2 (TameSpec.tameOfSpec (2 + 2 * h) q (Npc.npcW α r h e) hspec).toMonoidHom.ker :=
  hwild_of_tameSpecializes hspec

/-- **Compact `M`**. -/
theorem hwild_mCompact {q α h : ℕ}
    (hspec : TameSpec.TameSpecializes (2 + 2 * h) q (MCompact.mCompactW α h)) :
    IsProP 2
      (TameSpec.tameOfSpec (2 + 2 * h) q (MCompact.mCompactW α h) hspec).toMonoidHom.ker :=
  hwild_of_tameSpecializes hspec

/-- **Non-compact `M`**. -/
theorem hwild_mpcW {q α r p h : ℕ} {η : Mpc.EtaDisplay}
    (hspec : TameSpec.TameSpecializes (2 + 2 * h) q (Mpc.mpcW α r p η h)) :
    IsProP 2
      (TameSpec.tameOfSpec (2 + 2 * h) q (Mpc.mpcW α r p η h) hspec).toMonoidHom.ker :=
  hwild_of_tameSpecializes hspec

end Branches

/-! ## §3 The `√−2` pilot, end to end

`K = ℚ₂(√−2)`, `α = 2`, `h = 0`, `q_K = 2` — the frozen row of `Words/N0.lean`, with the Gate-B
witness CB-W rebuilt in `Count/Wild.lean` §6.  The pilot is the exact statement CB-W's
`pilot_not_hwild_bare` refutes over `GammaBare`, so the pair is the sharpest form of the
correction: same word, same `q`, same tame specialization — **different group**. -/

section Pilot

/-- **`hwild` holds at the pilot.**  Contrast `Count.pilot_not_hwild_bare`, the same statement
over the bare two-relator presentation, where it fails. -/
theorem pilot_hwild :
    IsProP 2
      (TameSpec.tameOfSpec (2 + 2 * 0) 2 pilotW pilot_tameSpecialization).toMonoidHom.ker :=
  hwild_nCompact pilot_tameSpecialization

end Pilot

end Count

end GQ2.Dyadic
