import GQ2.GammaA
import GQ2.MaxProP

/-!
# The universal marking is admissible in the limit  (ticket P-04)

`Γ_A = F₄ ⧸ N_A` (paper §2.1, eq. (7); `GQ2/GammaA.lean`) is the largest quotient of the free
profinite group `F₄` all of whose finite quotients are admissible.  This file proves that the
presentation data survives the limit — the three facts Prop 2.3 (P-05) needs about `Γ_A` itself:

* **relators die in the limit**: `tameRelator_mem_NA` / `wildRelator_mem_NA` — the profinite
  relator words of the universal marking (relations (5)/(6)) lie in `N_A`, i.e. their images in
  `Γ_A` are `1` (`quotientMk_tameRelator_eq_one` / `quotientMk_wildRelator_eq_one`);
* **the admissible opens are exactly the opens above `N_A`** (`isAdmissibleU_iff_NA_le`) — the
  order-theoretic form of "`Γ_A`'s finite quotients are the admissible quotients";
* **the wild pair's closed normal closure is pro-2 in the limit** (`isProP_wildCore`): the closed
  normal subgroup `⟨⟨x₀, x₁⟩⟩ ≤ Γ_A` generated by the images of `x₀, x₁` is a pro-2 group — the
  pro-2 condition of eq. (7) holds for `Γ_A` itself, not just for its finite quotients.

## Design note: the limit argument

The engine is the **directedness of the admissible family** (the subdirect-closure content of
paper Lemma 2.1, `GQ2/Subdirect.lean`), run through the same compactness pattern as
`GQ2/MaxProP.lean`:

1. `isAdmissibleU_top`: the trivial quotient is admissible (all four conditions are trivial in a
   subsingleton), so the admissible family is nonempty — no appeal to the Appendix-B `S₃`
   quotient is needed.
2. `isAdmissibleU_inf`: admissibility is closed under `U ⊓ V`.  Generation holds in *every*
   finite quotient of `F₄` (`generates_univMarking_map` — density of the abstract free group in
   its profinite completion); the relators die in `U ⊓ V` because they die in `U` and in `V`
   (this is where `tameRelator_mem_of_isAdmissibleU` recurs); and the 2-core condition passes to
   `U ⊓ V` **subdirectly**: an element of the normal closure in `F₄ ⧸ U ⊓ V` has a lift whose
   images in `F₄ ⧸ U` and `F₄ ⧸ V` are 2-elements, so it is a 2-element
   (`isPGroup_normalClosure_image_inf`, the elementwise form of "`Q_A` is closed under subdirect
   products", Lemma 2.1).
3. `exists_isAdmissibleU_le`: **admissible domination** — every open normal `W ≥ N_A` contains an
   admissible `U`.  Compactness: the family `{U ∩ Wᶜ}` over admissible `U` is a directed (by 2)
   family of closed sets in the compact `F₄`; were all nonempty, their intersection would meet
   `N_A ∩ Wᶜ = ∅`.  (Same pattern as `isPGroup_quotient_of_proPKernel_le`.)
4. `isAdmissibleU_of_NA_le`: push admissibility from the dominating `U` up to `W` along
   `F₄ ⧸ U ↠ F₄ ⧸ W` via Lemma 2.2 (`Marking.map_admissible`).  With the trivial converse
   (`N_A` is an intersection) this gives the characterization `isAdmissibleU_iff_NA_le`.
5. `isProP_wildCore`: for an open normal `V ≤ ⟨⟨x₀,x₁⟩⟩` (subspace topology), pick an open
   normal `W ≤ Γ_A` with `W ∩ ⟨⟨x₀,x₁⟩⟩ ≤ V` (Krull-style: `V` is a neighbourhood of `1`);
   pull `W` back to an open normal `Ŵ ≥ N_A` of `F₄`, which is **admissible** by 4, so the
   normal closure of `x₀, x₁` in `F₄ ⧸ Ŵ` is a 2-group; a dense-image argument (the image of
   `⟨⟨x₀,x₁⟩⟩ = closure M` in the *finite discrete* `Γ_A ⧸ W` equals the image of the abstract
   normal closure `M`) then bounds every element of `⟨⟨x₀,x₁⟩⟩ ⧸ V` by a 2-power.

Everything is deduced from the *definition* of `N_A` — no appeal to `Γ_A ≅ lim` machinery, and
no new axioms (`#print axioms` = the standard three throughout).
-/

open CategoryTheory ProfiniteGrp

namespace GQ2

/-! ## Generation in every finite quotient

The four generators topologically generate `F₄` (density of the abstract free group in its
profinite completion), so their images generate every finite (discrete) quotient.  This is the
`Generates` clause of admissibility, for free, for *every* open normal subgroup. -/

section Generation

/-- The set underlying the universal marking is the range of the generator inclusion. -/
private lemma range_of_eq_univMarking_set :
    Set.range (FreeProfiniteGroup.of : Fin 4 → FreeProfiniteGroup (Fin 4))
      = {univMarking.σ, univMarking.τ, univMarking.x₀, univMarking.x₁} := by
  ext y
  simp only [Set.mem_range, univMarking, Set.mem_insert_iff, Set.mem_singleton_iff]
  constructor
  · rintro ⟨i, rfl⟩
    fin_cases i <;> tauto
  · rintro (rfl | rfl | rfl | rfl)
    exacts [⟨0, rfl⟩, ⟨1, rfl⟩, ⟨2, rfl⟩, ⟨3, rfl⟩]

/-- The subgroup generated by the universal marking is the (dense) image of the abstract free
group `FreeGroup (Fin 4)` in its profinite completion. -/
lemma closure_univMarking_eq_range_eta :
    Subgroup.closure ({univMarking.σ, univMarking.τ, univMarking.x₀, univMarking.x₁} :
        Set (FreeProfiniteGroup (Fin 4)))
      = ((ProfiniteCompletion.eta (GrpCat.of (FreeGroup (Fin 4)))).hom).range := by
  rw [← range_of_eq_univMarking_set, MonoidHom.range_eq_map,
    ← FreeGroup.closure_range_of (Fin 4), MonoidHom.map_closure, ← Set.range_comp]
  rfl

/-- **Generation is automatic**: the pushed universal marking generates every finite quotient
`F₄ ⧸ W` (`W` open normal).  Density of the free group in its completion + discreteness of the
quotient. -/
theorem generates_univMarking_map (W : OpenNormalSubgroup (FreeProfiniteGroup (Fin 4))) :
    (univMarking.map (QuotientGroup.mk' W.toSubgroup)).Generates := by
  rw [Marking.Generates]
  have himg : ({(univMarking.map (QuotientGroup.mk' W.toSubgroup)).σ,
      (univMarking.map (QuotientGroup.mk' W.toSubgroup)).τ,
      (univMarking.map (QuotientGroup.mk' W.toSubgroup)).x₀,
      (univMarking.map (QuotientGroup.mk' W.toSubgroup)).x₁} :
        Set (FreeProfiniteGroup (Fin 4) ⧸ W.toSubgroup))
      = (QuotientGroup.mk' W.toSubgroup) ''
          {univMarking.σ, univMarking.τ, univMarking.x₀, univMarking.x₁} := by
    simp [Marking.map, Set.image_insert_eq, Set.image_singleton]
  rw [himg, ← MonoidHom.map_closure, closure_univMarking_eq_range_eta, Subgroup.eq_top_iff']
  intro x
  obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective W.toSubgroup x
  -- `g` lies in the closure of the dense image of the free group …
  have hg : g
      ∈ closure (Set.range (ProfiniteCompletion.etaFn (GrpCat.of (FreeGroup (Fin 4))))) := by
    rw [(ProfiniteCompletion.denseRange _).closure_eq]
    trivial
  -- … so its class lies in the image of that image (the quotient is discrete).
  have himgcl : (QuotientGroup.mk' W.toSubgroup) g
      ∈ closure ((QuotientGroup.mk' W.toSubgroup) ''
          Set.range (ProfiniteCompletion.etaFn (GrpCat.of (FreeGroup (Fin 4))))) :=
    image_closure_subset_closure_image QuotientGroup.continuous_mk ⟨g, hg, rfl⟩
  rw [closure_discrete] at himgcl
  obtain ⟨y, ⟨z, rfl⟩, hyx⟩ := himgcl
  exact Subgroup.mem_map.mpr ⟨_, ⟨z, rfl⟩, hyx⟩

end Generation

/-! ## The relator words lie in `N_A`  (deliverable (i))

Each admissible open normal `U` kills both relator words (the finite-level relations of
`IsAdmissibleU` read back through the profinite⟺finite bridges of `GQ2/GammaA.lean`), so the
words lie in the intersection `N_A` — i.e. relations (5) and (6) *hold in `Γ_A`*. -/

section Relators

/-- An admissible open normal subgroup contains the tame relator word (relation (5)). -/
theorem tameRelator_mem_of_isAdmissibleU {U : OpenNormalSubgroup (FreeProfiniteGroup (Fin 4))}
    (hU : IsAdmissibleU U) : univMarking.tameRelator ∈ U.toSubgroup :=
  (QuotientGroup.eq_one_iff _).mp
    ((Marking.map_tameRelator_eq_one_iff (quotientMk U.toSubgroup) univMarking).mpr hU.2.1)

/-- An admissible open normal subgroup contains the wild relator word (relation (6)). -/
theorem wildRelator_mem_of_isAdmissibleU {U : OpenNormalSubgroup (FreeProfiniteGroup (Fin 4))}
    (hU : IsAdmissibleU U) : univMarking.wildRelator ∈ U.toSubgroup :=
  (QuotientGroup.eq_one_iff _).mp
    ((Marking.map_wildRelator_eq_one_iff (quotientMk U.toSubgroup) univMarking).mpr hU.2.2.1)

/-- **The tame relator word lies in `N_A`** — relation (5) holds in `Γ_A` (paper eq. (7)). -/
theorem tameRelator_mem_NA : univMarking.tameRelator ∈ NA := by
  rw [NA, Subgroup.mem_iInf]
  exact fun U => tameRelator_mem_of_isAdmissibleU U.2

/-- **The wild relator word lies in `N_A`** — relation (6) holds in `Γ_A` (paper eq. (7)). -/
theorem wildRelator_mem_NA : univMarking.wildRelator ∈ NA := by
  rw [NA, Subgroup.mem_iInf]
  exact fun U => wildRelator_mem_of_isAdmissibleU U.2

/-- Relation (5) in `Γ_A`: the image of the tame relator word is trivial. -/
@[simp] theorem quotientMk_tameRelator_eq_one :
    quotientMk NA univMarking.tameRelator = 1 :=
  (quotientMk_eq_one_iff NA).mpr tameRelator_mem_NA

/-- Relation (6) in `Γ_A`: the image of the wild relator word is trivial. -/
@[simp] theorem quotientMk_wildRelator_eq_one :
    quotientMk NA univMarking.wildRelator = 1 :=
  (quotientMk_eq_one_iff NA).mpr wildRelator_mem_NA

end Relators

/-! ## Directedness of the admissible family  (Lemma 2.1 in the limit)

The admissible open normal subgroups form a *directed* family: the trivial quotient is
admissible, and admissibility is closed under `⊓` (the subdirect-closure content of paper
Lemma 2.1: `F₄ ⧸ U ⊓ V` is a subdirect product of `F₄ ⧸ U` and `F₄ ⧸ V`).  Compactness then
gives **admissible domination**: every open normal subgroup above `N_A` contains an admissible
one, hence is itself admissible (Lemma 2.2 pushforward) — the admissible opens are *exactly*
the opens above `N_A`. -/

section Directed

/-- **Subdirect 2-core (Lemma 2.1, elementwise).**  If the normal closures of the image of `S`
in `G ⧸ A` and in `G ⧸ B` are `p`-groups, so is the normal closure of the image of `S` in
`G ⧸ (A ⊓ B)`: any element lifts to `n` in the abstract normal closure of `S`, and
`n ^ p^i ∈ A`, `n ^ p^j ∈ B` give `n ^ p^(i+j) ∈ A ⊓ B`. -/
theorem isPGroup_normalClosure_image_inf {G : Type*} [Group G] {p : ℕ} (S : Set G)
    (A B : Subgroup G) [A.Normal] [B.Normal]
    (hA : IsPGroup p (Subgroup.normalClosure ((QuotientGroup.mk' A) '' S)))
    (hB : IsPGroup p (Subgroup.normalClosure ((QuotientGroup.mk' B) '' S))) :
    IsPGroup p (Subgroup.normalClosure ((QuotientGroup.mk' (A ⊓ B)) '' S)) := by
  intro x
  -- lift `x` into the abstract normal closure of `S`
  have hx : (x : G ⧸ (A ⊓ B))
      ∈ Subgroup.map (QuotientGroup.mk' (A ⊓ B)) (Subgroup.normalClosure S) := by
    rw [Subgroup.map_normalClosure _ _ (QuotientGroup.mk'_surjective _)]
    exact x.2
  obtain ⟨n, hn, hnx⟩ := hx
  -- its images in the two factors are `p`-elements
  have hnA : (QuotientGroup.mk' A) n ∈ Subgroup.normalClosure ((QuotientGroup.mk' A) '' S) := by
    rw [← Subgroup.map_normalClosure _ _ (QuotientGroup.mk'_surjective _)]
    exact ⟨n, hn, rfl⟩
  have hnB : (QuotientGroup.mk' B) n ∈ Subgroup.normalClosure ((QuotientGroup.mk' B) '' S) := by
    rw [← Subgroup.map_normalClosure _ _ (QuotientGroup.mk'_surjective _)]
    exact ⟨n, hn, rfl⟩
  obtain ⟨i, hi⟩ := hA ⟨_, hnA⟩
  obtain ⟨j, hj⟩ := hB ⟨_, hnB⟩
  have hiA : n ^ p ^ i ∈ A := by
    have h := congrArg Subtype.val hi
    rw [SubgroupClass.coe_pow, OneMemClass.coe_one, ← map_pow] at h
    exact (QuotientGroup.eq_one_iff _).mp h
  have hjB : n ^ p ^ j ∈ B := by
    have h := congrArg Subtype.val hj
    rw [SubgroupClass.coe_pow, OneMemClass.coe_one, ← map_pow] at h
    exact (QuotientGroup.eq_one_iff _).mp h
  refine ⟨i + j, ?_⟩
  ext
  rw [SubgroupClass.coe_pow, OneMemClass.coe_one, ← hnx, ← map_pow]
  refine (QuotientGroup.eq_one_iff _).mpr (Subgroup.mem_inf.mpr ⟨?_, ?_⟩)
  · rw [pow_add, pow_mul]
    exact Subgroup.pow_mem A hiA _
  · rw [pow_add, mul_comm, pow_mul]
    exact Subgroup.pow_mem B hjB _

/-- **The trivial quotient is admissible**: all four clauses are trivial in a subsingleton.
(Nonvacuity of the admissible family, with no appeal to the Appendix-B `S₃` quotient.) -/
theorem isAdmissibleU_top :
    IsAdmissibleU (topOpenNormalSubgroup (FreeProfiniteGroup (Fin 4))) := by
  haveI hsub : Subsingleton (FreeProfiniteGroup (Fin 4) ⧸
      (topOpenNormalSubgroup (FreeProfiniteGroup (Fin 4))).toSubgroup) :=
    QuotientGroup.subsingleton_quotient_top
  refine ⟨?_, Subsingleton.elim _ _, Subsingleton.elim _ _, fun g => ⟨0, Subtype.ext ?_⟩⟩
  · rw [Marking.Generates, Subgroup.eq_top_iff']
    exact fun x => (Subsingleton.elim 1 x) ▸ one_mem _
  · exact Subsingleton.elim _ _

/-- Pushing a marking along a composite is composing the pushes. -/
@[simp] lemma Marking.map_map {G H K : Type*} [Group G] [Group H] [Group K]
    (f : G →* H) (g : H →* K) (t : Marking G) : (t.map f).map g = t.map (g.comp f) := rfl

/-- The wild pair of a pushed marking is the image of the wild pair. -/
private lemma image_wild_pair {H : Type*} [Group H] (f : FreeProfiniteGroup (Fin 4) →* H) :
    ({(univMarking.map f).x₀, (univMarking.map f).x₁} : Set H)
      = f '' {univMarking.x₀, univMarking.x₁} := by
  rw [Set.image_pair]
  rfl

/-- **Admissibility is closed under intersections** (Lemma 2.1, subdirect closure): the
canonical quotient by `U ⊓ V` is a subdirect product of the quotients by `U` and by `V`, and
each admissibility clause passes through. -/
theorem isAdmissibleU_inf {U V : OpenNormalSubgroup (FreeProfiniteGroup (Fin 4))}
    (hU : IsAdmissibleU U) (hV : IsAdmissibleU V) : IsAdmissibleU (U ⊓ V) := by
  refine ⟨generates_univMarking_map _, ?_, ?_, ?_⟩
  · -- tame relation: the tame relator word lies in `U ⊓ V`
    exact (Marking.map_tameRelator_eq_one_iff (quotientMk (U ⊓ V).toSubgroup) univMarking).mp
      ((QuotientGroup.eq_one_iff _).mpr (Subgroup.mem_inf.mpr
        ⟨tameRelator_mem_of_isAdmissibleU hU, tameRelator_mem_of_isAdmissibleU hV⟩))
  · -- wild relation: the wild relator word lies in `U ⊓ V`
    exact (Marking.map_wildRelator_eq_one_iff (quotientMk (U ⊓ V).toSubgroup) univMarking).mp
      ((QuotientGroup.eq_one_iff _).mpr (Subgroup.mem_inf.mpr
        ⟨wildRelator_mem_of_isAdmissibleU hU, wildRelator_mem_of_isAdmissibleU hV⟩))
  · -- 2-core, subdirectly
    have hA := hU.2.2.2
    have hB := hV.2.2.2
    rw [Marking.Pro2Core, image_wild_pair] at hA hB
    rw [Marking.Pro2Core, image_wild_pair]
    exact isPGroup_normalClosure_image_inf {univMarking.x₀, univMarking.x₁}
      U.toSubgroup V.toSubgroup hA hB

/-- **Admissible domination.**  Every open normal subgroup of `F₄` containing `N_A` contains an
*admissible* open normal subgroup.  (Compactness: were every admissible `U ⊄ W`, the directed
family `{U ∩ Wᶜ}` of nonempty closed sets would have a common point, necessarily in
`N_A ∩ Wᶜ = ∅`.) -/
theorem exists_isAdmissibleU_le {W : OpenNormalSubgroup (FreeProfiniteGroup (Fin 4))}
    (hle : NA ≤ W.toSubgroup) :
    ∃ U : OpenNormalSubgroup (FreeProfiniteGroup (Fin 4)),
      IsAdmissibleU U ∧ U.toSubgroup ≤ W.toSubgroup := by
  by_contra hcon
  replace hcon : ∀ U : OpenNormalSubgroup (FreeProfiniteGroup (Fin 4)), IsAdmissibleU U →
      ¬ U.toSubgroup ≤ W.toSubgroup := fun U hU h => hcon ⟨U, hU, h⟩
  set ι := {U : OpenNormalSubgroup (FreeProfiniteGroup (Fin 4)) // IsAdmissibleU U} with hι
  haveI : Nonempty ι := ⟨⟨topOpenNormalSubgroup _, isAdmissibleU_top⟩⟩
  set t : ι → Set (FreeProfiniteGroup (Fin 4)) :=
    fun U => (U.1 : Set (FreeProfiniteGroup (Fin 4))) ∩ (W.toSubgroup : Set _)ᶜ with ht
  have htn : ∀ U, (t U).Nonempty :=
    fun U => SetLike.not_le_iff_exists.mp (hcon U.1 U.2)
  have htcl : ∀ U, IsClosed (t U) :=
    fun U => (U.1.toOpenSubgroup.isClosed).inter W.toOpenSubgroup.isOpen.isClosed_compl
  have htc : ∀ U, IsCompact (t U) := fun U => (htcl U).isCompact
  have htd : Directed (· ⊇ ·) t := by
    intro U V
    exact ⟨⟨U.1 ⊓ V.1, isAdmissibleU_inf U.2 V.2⟩,
      Set.inter_subset_inter_left _ (SetLike.coe_subset_coe.mpr inf_le_left),
      Set.inter_subset_inter_left _ (SetLike.coe_subset_coe.mpr inf_le_right)⟩
  obtain ⟨x, hx⟩ :=
    IsCompact.nonempty_iInter_of_directed_nonempty_isCompact_isClosed t htd htn htc htcl
  rw [Set.mem_iInter] at hx
  have hxNA : x ∈ NA := by
    rw [NA, Subgroup.mem_iInf]
    exact fun U => (hx U).1
  exact (hx (Classical.arbitrary ι)).2 (hle hxNA)

/-- Every open normal subgroup above `N_A` is itself admissible: push the marking forward from
a dominating admissible `U` along `F₄ ⧸ U ↠ F₄ ⧸ W` (Lemma 2.2, `Marking.map_admissible`). -/
theorem isAdmissibleU_of_NA_le {W : OpenNormalSubgroup (FreeProfiniteGroup (Fin 4))}
    (hle : NA ≤ W.toSubgroup) : IsAdmissibleU W := by
  obtain ⟨U, hU, hUW⟩ := exists_isAdmissibleU_le hle
  have hcomap : U.toSubgroup ≤ Subgroup.comap (MonoidHom.id _) W.toSubgroup := by
    simpa using hUW
  set π : (FreeProfiniteGroup (Fin 4) ⧸ U.toSubgroup) →*
      (FreeProfiniteGroup (Fin 4) ⧸ W.toSubgroup) :=
    QuotientGroup.map U.toSubgroup W.toSubgroup (MonoidHom.id _) hcomap with hπ
  have hπs : Function.Surjective π := by
    intro y
    obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective W.toSubgroup y
    refine ⟨QuotientGroup.mk' U.toSubgroup g, ?_⟩
    rw [hπ, QuotientGroup.map_mk']
    rfl
  have hcomp : π.comp (QuotientGroup.mk' U.toSubgroup) = QuotientGroup.mk' W.toSubgroup := by
    ext x
    rw [MonoidHom.comp_apply, hπ, QuotientGroup.map_mk']
    rfl
  have hpush : univMarking.map (QuotientGroup.mk' W.toSubgroup)
      = (univMarking.map (QuotientGroup.mk' U.toSubgroup)).map π := by
    rw [Marking.map_map, hcomp]
  rw [IsAdmissibleU, hpush]
  exact Marking.map_admissible π hπs _ hU

/-- **The admissible opens are exactly the opens above `N_A`** — the order-theoretic form of
"`Γ_A = F₄ ⧸ N_A` is the largest quotient all of whose finite quotients are admissible"
(paper §2.1, eq. (7)).  This is the interface Prop 2.3 (P-05) consumes. -/
theorem isAdmissibleU_iff_NA_le (U : OpenNormalSubgroup (FreeProfiniteGroup (Fin 4))) :
    IsAdmissibleU U ↔ NA ≤ U.toSubgroup :=
  ⟨fun h => iInf_le (fun V : {V : OpenNormalSubgroup (FreeProfiniteGroup (Fin 4)) //
      IsAdmissibleU V} => V.1.toSubgroup) ⟨U, h⟩, isAdmissibleU_of_NA_le⟩

end Directed

/-! ## The wild pair's closed normal closure is pro-2  (deliverable (ii))

The pro-2 clause of eq. (7) holds *in the limit*: the closed normal subgroup of `Γ_A` generated
by the images of `x₀, x₁` is a pro-2 group.  Every open normal subgroup of it is trapped, via an
open normal subgroup of `Γ_A`, by an admissible finite quotient of `F₄`, where the 2-core clause
of admissibility bounds every element by a 2-power. -/

section WildCore

/-- **The wild core of `Γ_A`**: the closed normal closure `⟨⟨x₀, x₁⟩⟩ ≤ Γ_A` of the images of
the wild generators — the subgroup that paper eq. (7) requires to be pro-2.  (Stated on the
underlying quotient `F₄ ⧸ N_A`, to which `GammaA` is definitionally equal.  The §3 layer's
`GQ2.SectionThree.wildPart` is *definitionally this subgroup* — deduplicated 2026-07-03 —
so `isProP_wildCore` etc. transfer verbatim; see `GQ2/SectionThree.lean`.) -/
noncomputable def wildCore : Subgroup (FreeProfiniteGroup (Fin 4) ⧸ NA) :=
  (Subgroup.normalClosure
    {quotientMk NA univMarking.x₀, quotientMk NA univMarking.x₁}).topologicalClosure

instance wildCore_normal : wildCore.Normal :=
  Subgroup.is_normal_topologicalClosure _

lemma wildCore_isClosed : IsClosed (wildCore : Set (FreeProfiniteGroup (Fin 4) ⧸ NA)) :=
  Subgroup.isClosed_topologicalClosure _

/-- **The wild core is pro-2** (paper §2.1, the pro-2 clause of eq. (7), in the limit): every
finite continuous quotient of `⟨⟨x₀, x₁⟩⟩ ≤ Γ_A` is a 2-group.

The limit argument (see the module docstring): an open normal `V ≤ wildCore` contains
`W ∩ wildCore` for some open normal `W ≤ Γ_A`; the pullback `Ŵ ≤ F₄` of `W` contains `N_A`, so
it is **admissible** (`isAdmissibleU_of_NA_le`), and its 2-core clause bounds the relevant
elements: any `m ∈ wildCore` agrees modulo `W` with an element of the *abstract* normal closure
(discreteness of `Γ_A ⧸ W`), whose lift to `F₄` becomes a 2-element in `F₄ ⧸ Ŵ`. -/
theorem isProP_wildCore : IsProP 2 wildCore := by
  haveI : IsClosed (NA : Set (FreeProfiniteGroup (Fin 4))) := NA_isClosed
  intro V x
  obtain ⟨m, rfl⟩ := QuotientGroup.mk_surjective x
  -- Step A: an open normal `W ≤ Γ_A` with `W ∩ wildCore ≤ V` (via an open `O ⊆ Γ_A` inducing `V`)
  obtain ⟨O, hOopen, hOV⟩ := isOpen_induced_iff.mp V.toOpenSubgroup.isOpen
  have h1O : (1 : FreeProfiniteGroup (Fin 4) ⧸ NA) ∈ O := by
    have h1V : (1 : wildCore) ∈ Subtype.val ⁻¹' O := by
      rw [hOV]
      exact one_mem V.toOpenSubgroup
    exact h1V
  obtain ⟨W, hWO⟩ := ProfiniteGrp.exist_openNormalSubgroup_sub_open_nhds_of_one hOopen h1O
  -- Step B: pull `W` back to an admissible open normal subgroup `Ŵ ≥ N_A` of `F₄`
  set Ŵ : OpenNormalSubgroup (FreeProfiniteGroup (Fin 4)) :=
    { toSubgroup := Subgroup.comap (QuotientGroup.mk' NA) W.toSubgroup
      isOpen' := W.toOpenSubgroup.isOpen.preimage continuous_quotient_mk'
      isNormal' := W.isNormal'.comap _ } with hŴ
  have hNAle : NA ≤ Ŵ.toSubgroup := by
    intro g hg
    show QuotientGroup.mk' NA g ∈ W.toSubgroup
    have h1 : QuotientGroup.mk' NA g = 1 := (QuotientGroup.eq_one_iff g).mpr hg
    rw [h1]
    exact one_mem _
  have hcore := (isAdmissibleU_of_NA_le hNAle).2.2.2
  rw [Marking.Pro2Core, image_wild_pair] at hcore
  -- Step C: `m` agrees modulo `W` with an element of the abstract normal closure
  have hmcl : (m : FreeProfiniteGroup (Fin 4) ⧸ NA) ∈ closure
      ((Subgroup.normalClosure
        {quotientMk NA univMarking.x₀, quotientMk NA univMarking.x₁} :
          Subgroup (FreeProfiniteGroup (Fin 4) ⧸ NA)) : Set (FreeProfiniteGroup (Fin 4) ⧸ NA)) := by
    rw [← Subgroup.topologicalClosure_coe]
    exact m.2
  have himg : (QuotientGroup.mk' W.toSubgroup) (m : FreeProfiniteGroup (Fin 4) ⧸ NA)
      ∈ closure ((QuotientGroup.mk' W.toSubgroup) ''
          ((Subgroup.normalClosure
            {quotientMk NA univMarking.x₀, quotientMk NA univMarking.x₁} :
              Subgroup (FreeProfiniteGroup (Fin 4) ⧸ NA)) :
                Set (FreeProfiniteGroup (Fin 4) ⧸ NA))) :=
    image_closure_subset_closure_image continuous_quotient_mk' ⟨_, hmcl, rfl⟩
  rw [closure_discrete] at himg
  obtain ⟨nΓ, hnM, hnm⟩ := himg
  -- Step D: lift to the abstract normal closure in `F₄`
  have hMmap : (Subgroup.normalClosure
      {quotientMk NA univMarking.x₀, quotientMk NA univMarking.x₁} :
        Subgroup (FreeProfiniteGroup (Fin 4) ⧸ NA))
      = Subgroup.map (QuotientGroup.mk' NA)
          (Subgroup.normalClosure {univMarking.x₀, univMarking.x₁}) := by
    rw [Subgroup.map_normalClosure _ _ (QuotientGroup.mk'_surjective _), Set.image_pair]
    rfl
  rw [SetLike.mem_coe, hMmap] at hnM
  obtain ⟨n', hn', rfl⟩ := hnM
  -- Step E: the 2-core clause of the admissible `Ŵ` bounds `n'`
  have hmem : (QuotientGroup.mk' Ŵ.toSubgroup) n'
      ∈ Subgroup.normalClosure
          ((QuotientGroup.mk' Ŵ.toSubgroup) '' {univMarking.x₀, univMarking.x₁}) := by
    rw [← Subgroup.map_normalClosure _ _ (QuotientGroup.mk'_surjective _)]
    exact ⟨n', hn', rfl⟩
  obtain ⟨k, hk⟩ := hcore ⟨_, hmem⟩
  refine ⟨k, ?_⟩
  -- Step F: transfer the 2-power bound back through `W` and `V`
  have hn'W : (QuotientGroup.mk' NA n') ^ 2 ^ k ∈ W.toSubgroup := by
    have h := congrArg Subtype.val hk
    rw [SubgroupClass.coe_pow, OneMemClass.coe_one, ← map_pow] at h
    have hŴmem : n' ^ 2 ^ k ∈ Ŵ.toSubgroup := (QuotientGroup.eq_one_iff _).mp h
    rw [← map_pow]
    exact hŴmem
  have hmW : (m : FreeProfiniteGroup (Fin 4) ⧸ NA) ^ 2 ^ k ∈ W.toSubgroup := by
    have h : (QuotientGroup.mk' W.toSubgroup)
        ((m : FreeProfiniteGroup (Fin 4) ⧸ NA) ^ 2 ^ k) = 1 := by
      rw [map_pow, ← hnm, ← map_pow]
      exact (QuotientGroup.eq_one_iff _).mpr hn'W
    exact (QuotientGroup.eq_one_iff _).mp h
  have hmV : m ^ 2 ^ k ∈ V.toSubgroup := by
    have hpre : (m ^ 2 ^ k : wildCore) ∈ Subtype.val ⁻¹' O :=
      hWO (by rw [SubgroupClass.coe_pow]; exact hmW)
    rwa [hOV] at hpre
  have h1 : (QuotientGroup.mk' V.toSubgroup) (m ^ 2 ^ k) = 1 :=
    (QuotientGroup.eq_one_iff _).mpr hmV
  rw [map_pow] at h1
  exact h1

end WildCore

end GQ2

/-! ### Paper-tag ledger (auto-generated by paperforge; do not edit)

  * eq. (7) = ⟦eq-candidateinverse⟧
  * Lemma 2.1 = ⟦lem-subdirect⟧
  * Lemma 2.2 = ⟦lem-cofinal⟧
  * Prop 2.3 = ⟦prop-epi-semantics⟧
-/
