import GQ2.DyadicPresentation
import GQ2.BoundaryConstruction

/-!
# The Nielsen isomorphism `D₀ ≅ Π`  (ticket P-25, toward `prop_3_10_local_marked`)

`D₀ = ⟨A,S,Y ∣ A²S⁴[S,Y]⟩` (the dyadic Demushkin presentation, `GQ2/DyadicPresentation.lean`) and
`Π = ⟨σ,x₀,x₁ ∣ x₀^{σ²}·x₀·[x₁,σ]⟩` (the boundary-frame presentation, `GQ2/BoundaryFrame.lean`) are
isomorphic pro-`2` groups via an **explicit Nielsen change of generators** (paper Cor 3.12):

* `Π → D₀`:  `σ ↦ S`, `x₀ ↦ S⁻²A⁻¹`, `x₁ ↦ Y`  — kills `piRelator` (since
  `(S⁻²A⁻¹)^{S²}·(S⁻²A⁻¹) = S⁻⁴A⁻² = [S,Y]` by `d0_relation`).
* `D₀ → Π`:  `A ↦ x₀⁻¹σ⁻²`, `S ↦ σ`, `Y ↦ x₁`  — kills `d0Relator` (using `piRelator = 1`).

These are mutually inverse, giving `d0PiEquiv : D₀ ≅ Π` matching the marked generators.  Composed
with `prop_1_1` (`G_{ℚ₂}(2) ≅ D₀`) this yields the local half of Prop 3.10.  Structure mirrors
`GQ2/BoundaryConstruction.lean`'s `prop_3_10_gammaA` (presentation maps + density mutual inverse),
but with **no word collapse** — the relators match by pure `group` algebra + `d0_relation`.
-/

namespace GQ2

namespace SectionThree

open scoped Classical

/-- `D₀` is a pro-`2` group. -/
theorem d0_isProP : IsProP 2 D0 :=
  isProP_quotient_proPKernel

/-! ## Topological generation of `D₀` -/

/-- The evaluation `F₃ → D₀`, `A ↦ A, S ↦ S, Y ↦ Y`. -/
noncomputable def evalD0 : ContinuousMonoidHom (FreeProfiniteGroup (Fin 3)) D0 :=
  (maxProPMk 2 D0Full).comp (quotientMk (relatorSubgroup {d0Relator}))

@[simp] lemma evalD0_of0 : evalD0 (FreeProfiniteGroup.of 0) = d0A := rfl
@[simp] lemma evalD0_of1 : evalD0 (FreeProfiniteGroup.of 1) = d0S := rfl
@[simp] lemma evalD0_of2 : evalD0 (FreeProfiniteGroup.of 2) = d0Y := rfl

theorem evalD0_surjective : Function.Surjective evalD0 :=
  (quotientMk_surjective _).comp (quotientMk_surjective _)

/-- `D₀` is topologically generated by `A, S, Y`. -/
theorem topGen_d0 :
    (Subgroup.closure {d0A, d0S, d0Y}).topologicalClosure = ⊤ := by
  have h := topGen_map (f := evalD0.toMonoidHom) evalD0.continuous_toFun evalD0_surjective
    (topGen_freeProfiniteGroup (Fin 3))
  have h1 : (⇑evalD0.toMonoidHom) '' Set.range (FreeProfiniteGroup.of (X := Fin 3))
      = {d0A, d0S, d0Y} := by
    rw [← Set.range_comp]
    ext z; constructor
    · rintro ⟨i, rfl⟩; fin_cases i
      · exact Set.mem_insert _ _
      · exact Set.mem_insert_of_mem _ (Set.mem_insert _ _)
      · exact Set.mem_insert_of_mem _ (Set.mem_insert_of_mem _ rfl)
    · intro hz; rcases hz with rfl | rfl | rfl
      · exact ⟨0, rfl⟩
      · exact ⟨1, rfl⟩
      · exact ⟨2, rfl⟩
  rwa [h1] at h

/-- In every discrete continuous quotient of `D₀`, the images of `A, S, Y` generate. -/
theorem gen_d0_quotient {H : Type*} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [DiscreteTopology H] (f : D0 →* H) (hcont : Continuous f) (hsurj : Function.Surjective f) :
    Subgroup.closure {f d0A, f d0S, f d0Y} = ⊤ := by
  have h := topGen_map f hcont hsurj topGen_d0
  rw [Set.image_insert_eq, Set.image_insert_eq, Set.image_singleton] at h
  exact gen_of_topGen_discrete h

/-! ## `[Y,S] = A²S⁴` in `D₀` (rearranged `d0_relation`) -/

/-- `commP d0Y d0S = d0A² d0S⁴` (rearrange `A²S⁴[S,Y] = 1`). -/
theorem commP_d0Y_d0S : commP d0Y d0S = d0A ^ 2 * d0S ^ 4 := by
  have hY : commP d0S d0Y = (d0A ^ 2 * d0S ^ 4)⁻¹ := eq_inv_of_mul_eq_one_right d0_relation
  have hinv : commP d0Y d0S = (commP d0S d0Y)⁻¹ := by simp only [commP]; group
  rw [hinv, hY, inv_inv]

/-! ## The forward map `Π → D₀` -/

/-- `σ ↦ S, x₀ ↦ S⁻²A⁻¹, x₁ ↦ Y`. -/
noncomputable def piToD0Base : FreeProfiniteGroup (Fin 3) ⟶ D0 :=
  (FreeProfiniteGroup.homEquiv (Fin 3) D0).symm ![d0S, (d0S ^ 2)⁻¹ * d0A⁻¹, d0Y]

@[simp] lemma piToD0Base_of0 : piToD0Base.hom.toMonoidHom (FreeProfiniteGroup.of 0) = d0S :=
  FreeProfiniteGroup.homEquiv_symm_of _ _ _
@[simp] lemma piToD0Base_of1 :
    piToD0Base.hom.toMonoidHom (FreeProfiniteGroup.of 1) = (d0S ^ 2)⁻¹ * d0A⁻¹ :=
  FreeProfiniteGroup.homEquiv_symm_of _ _ _
@[simp] lemma piToD0Base_of2 : piToD0Base.hom.toMonoidHom (FreeProfiniteGroup.of 2) = d0Y :=
  FreeProfiniteGroup.homEquiv_symm_of _ _ _

theorem piToD0Base_piRelator : piToD0Base.hom.toMonoidHom piRelator = 1 := by
  rw [piRelator]
  simp only [map_mul, map_pow, Marking.map_conjP, Marking.map_commP, piToD0Base_of0,
    piToD0Base_of1, piToD0Base_of2]
  rw [commP_d0Y_d0S]
  simp only [conjP]
  group

/-! ## The backward map `D₀ → Π` -/

/-- `A ↦ x₀⁻¹σ⁻², S ↦ σ, Y ↦ x₁`. -/
noncomputable def d0ToPiBase : FreeProfiniteGroup (Fin 3) ⟶ PiBd :=
  (FreeProfiniteGroup.homEquiv (Fin 3) PiBd).symm ![piX0⁻¹ * (piSigma ^ 2)⁻¹, piSigma, piX1]

@[simp] lemma d0ToPiBase_of0 :
    d0ToPiBase.hom.toMonoidHom (FreeProfiniteGroup.of 0) = piX0⁻¹ * (piSigma ^ 2)⁻¹ :=
  FreeProfiniteGroup.homEquiv_symm_of _ _ _
@[simp] lemma d0ToPiBase_of1 : d0ToPiBase.hom.toMonoidHom (FreeProfiniteGroup.of 1) = piSigma :=
  FreeProfiniteGroup.homEquiv_symm_of _ _ _
@[simp] lemma d0ToPiBase_of2 : d0ToPiBase.hom.toMonoidHom (FreeProfiniteGroup.of 2) = piX1 :=
  FreeProfiniteGroup.homEquiv_symm_of _ _ _

theorem d0ToPiBase_d0Relator : d0ToPiBase.hom.toMonoidHom d0Relator = 1 := by
  -- from `piRelator = 1`: `σ⁻²x₀⁻¹σ² = x₀·[x₁,σ]` (`conjP piX0⁻¹ (piSigma²)`).
  have hconj : conjP piX0⁻¹ (piSigma ^ 2) = piX0 * commP piX1 piSigma := by
    have h : conjP piX0 (piSigma ^ 2) = (piX0 * commP piX1 piSigma)⁻¹ := by
      have hpi := piRelatorWord_eq_one
      rw [mul_assoc] at hpi
      exact eq_inv_of_mul_eq_one_left hpi
    have hi : conjP piX0⁻¹ (piSigma ^ 2) = (conjP piX0 (piSigma ^ 2))⁻¹ := by
      simp only [conjP]; group
    rw [hi, h, inv_inv]
  rw [d0Relator]
  simp only [map_mul, map_pow, Marking.map_commP, d0ToPiBase_of0, d0ToPiBase_of1, d0ToPiBase_of2]
  have hstep : (piX0⁻¹ * (piSigma ^ 2)⁻¹) ^ 2 * piSigma ^ 4 * commP piSigma piX1
      = piX0⁻¹ * conjP piX0⁻¹ (piSigma ^ 2) * commP piSigma piX1 := by
    simp only [conjP, commP, pow_two]; group
  rw [hstep, hconj]
  simp only [commP]; group

end SectionThree

end GQ2
