import GQ2.GammaA

/-!
# Topological finite generation, and `Γ_A` (ticket P-03, Track A)

`main_presentation` (`GQ2/Statement.lean`) consumes topological finite generation of its candidate
group `Γ_A` in the shape `∃ s : Finset _, (Subgroup.closure ↑s).topologicalClosure = ⊤`.  This file
discharges it for `GQ2.GammaA`, via two reusable facts:

* `GQ2.isTopologicallyFinGen_freeProfiniteGroup` — the free profinite group on a **finite** set is
  topologically finitely generated (its free generators' images topologically generate: the free
  group is dense in its profinite completion, `ProfiniteGrp.ProfiniteCompletion.denseRange`);
* `GQ2.IsTopologicallyFinGen.of_surjective` — topological finite generation passes along a
  continuous **surjection** (the image of a topological generating set topologically generates —
  `DenseRange.topologicalClosure_map_subgroup`), in particular to any `profiniteQuotient`.

Instantiating the second at the quotient projection `F₄ ↠ F₄ ⧸ N_A = Γ_A` gives
`GQ2.gammaA_topologicallyFinitelyGenerated`, in exactly the form `main_presentation` (hence the
step-2 assembly `main_presentation_literal`, ticket P-19) needs.

No axioms: every result here is at the standard three (`#print axioms`).
-/

open CategoryTheory

namespace GQ2

universe u

/-- A topological group is **topologically finitely generated** when some *finite* subset
topologically generates it — i.e. the (algebraic) subgroup it generates is dense.  This is the
predicate `main_presentation` needs of `Γ_A`. -/
def IsTopologicallyFinGen (G : Type*) [Group G] [TopologicalSpace G]
    [IsTopologicalGroup G] : Prop :=
  ∃ s : Finset G, (Subgroup.closure (s : Set G)).topologicalClosure = ⊤

/-- **Topological finite generation passes along a continuous surjection.**  If `f : G →* Q` is
continuous and surjective and `G` is topologically finitely generated, then so is `Q` (the images
of a topological generating set topologically generate `Q`).  In particular it passes to every
`profiniteQuotient`. -/
theorem IsTopologicallyFinGen.of_surjective {G Q : Type*}
    [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [Group Q] [TopologicalSpace Q] [IsTopologicalGroup Q]
    (f : G →* Q) (hf : Continuous f) (hfs : Function.Surjective f)
    (hG : IsTopologicallyFinGen G) : IsTopologicallyFinGen Q := by
  obtain ⟨s, hs⟩ := hG
  refine ⟨(s.finite_toSet.image f).toFinset, ?_⟩
  rw [Set.Finite.coe_toFinset, ← MonoidHom.map_closure]
  exact hfs.denseRange.topologicalClosure_map_subgroup hf hs

/-- **The free profinite group on a finite set is topologically finitely generated.**  The finite
generating set is the image of the free generators under `FreeProfiniteGroup.of`; they topologically
generate because the free group is dense in its profinite completion
(`ProfiniteGrp.ProfiniteCompletion.denseRange`). -/
theorem isTopologicallyFinGen_freeProfiniteGroup {X : Type u} [Finite X] :
    IsTopologicallyFinGen (FreeProfiniteGroup X) := by
  refine ⟨(Set.finite_range (FreeProfiniteGroup.of (X := X))).toFinset, ?_⟩
  rw [Set.Finite.coe_toFinset]
  -- The completion hom `g : FreeGroup X →* FreeProfiniteGroup X`, whose range is dense.
  set g : FreeGroup X →* FreeProfiniteGroup X :=
    (ProfiniteGrp.ProfiniteCompletion.eta (GrpCat.of (FreeGroup X))).hom
  -- The subgroup generated by the generator-images is exactly the range of `g`.
  have hrange : Subgroup.closure (Set.range (FreeProfiniteGroup.of (X := X))) = g.range := by
    have h1 : Set.range (FreeProfiniteGroup.of (X := X))
        = ⇑g '' Set.range (FreeGroup.of : X → FreeGroup X) := by
      rw [← Set.range_comp]; rfl
    rw [h1, ← MonoidHom.map_closure, FreeGroup.closure_range_of X, ← MonoidHom.range_eq_map]
  rw [hrange, SetLike.ext'_iff]
  -- `range g` is dense, so its topological closure is everything.
  have hdense : DenseRange g := ProfiniteGrp.ProfiniteCompletion.denseRange _
  simpa only [Subgroup.topologicalClosure_coe, Subgroup.coe_top, MonoidHom.coe_range]
    using hdense.closure_range

/-- **`Γ_A` is topologically finitely generated** (the predicate form). -/
theorem gammaA_isTopologicallyFinGen : IsTopologicallyFinGen (GammaA : Type) := by
  haveI : IsClosed (NA : Set (FreeProfiniteGroup (Fin 4))) := NA_isClosed
  exact isTopologicallyFinGen_freeProfiniteGroup.of_surjective (quotientMk NA).toMonoidHom
    (quotientMk NA).continuous_toFun (quotientMk_surjective NA)

/-- **`Γ_A` is topologically finitely generated**, in exactly the `∃ s : Finset _, …` shape that
`GQ2.main_presentation` consumes (used by the step-2 assembly `main_presentation_literal`, P-19). -/
theorem gammaA_topologicallyFinitelyGenerated :
    ∃ s : Finset (GammaA : Type),
      (Subgroup.closure (s : Set (GammaA : Type))).topologicalClosure = ⊤ :=
  gammaA_isTopologicallyFinGen

end GQ2
