import Mathlib

/-!
# B7′: the dyadic Hilbert symbol  (ticket T-07)

The paper's Lemma 3.5 evaluates the cup product
`H¹(ℚ₂, μ₂) × H¹(ℚ₂, μ₂) → H²(ℚ₂, μ₂) ≅ 𝔽₂` on the square-class basis via the *Hilbert symbol*
`(·,·)₂`.  This file provides that symbol elementarily and records the explicit dyadic formula as
the axiom **B7′**.

* `GQ2.HilbertSymbol.IsHilbertSolvable a b` — the ternary form `a X² + b Y² - Z²` has a nontrivial
  `ℚ₂`-zero.  `hilbertSymbol a b : ℤˣ` (`= {±1}`) is `1` on this locus, `-1` off it.  Defined with no
  cohomology, so the elementary identities below are *theorems*.
* `GQ2.HilbertSymbol.ε`, `GQ2.HilbertSymbol.ω : ℤ₂ˣ → 𝔽₂` — Serre's residue characters
  `ε(u) ≡ (u-1)/2`, `ω(u) ≡ (u²-1)/8 (mod 2)` (*A Course in Arithmetic*, Ch. II §3.3), computed
  through the reduction `ℤ₂ → ℤ/8`.  Both are homomorphisms on units (`ε_mul`, `ω_mul`).
* **Axiom `hilbertSymbol_dyadic`** = Serre CiA III §1.2 Theorem 1, `p = 2` case:
  `(2^α u, 2^β v)₂ = (-1)^{ε(u)ε(v) + α ω(v) + β ω(u)}`.

Stress tests (theorems): symmetry `(a,b)=(b,a)`; `(a,-a)=1`; square-class invariance in one slot;
the ε/ω residue tables and their values on the unit `-1`; and (as a consequence of the axiom) the
square-class-basis value `(-1,-1)₂ = -1`, the nontrivial diagonal entry of the paper's initial cup
form `α² + βγ + γβ`.

Conventions: `ℚ_[2] = Padic 2`, `ℤ_[2] = PadicInt 2`, `𝔽₂ = ZMod 2`; the symbol is `ℤˣ = {±1}`-valued
via `signOf : 𝔽₂ → ℤˣ`, `0 ↦ 1`, `1 ↦ -1`.

The axiom is `[Classical.]` (a theorem of Mathlib-in-principle; axiomatized here at step 1). Per the
ticket rule it will be migrated to `GQ2/Foundations/Axioms.lean` by T-19.
-/

namespace GQ2.HilbertSymbol

open scoped Classical

/-! ## The Hilbert symbol via solvability of `z² = a x² + b y²` -/

/-- `IsHilbertSolvable a b`: the ternary quadratic form `a X² + b Y² - Z²` has a nontrivial zero
over `ℚ₂`, i.e. the Hilbert symbol `(a, b)₂` is `+1`.  (Serre, *A Course in Arithmetic*, III §1.1.) -/
def IsHilbertSolvable (a b : ℚ_[2]) : Prop :=
  ∃ x y z : ℚ_[2], (x ≠ 0 ∨ y ≠ 0 ∨ z ≠ 0) ∧ a * x ^ 2 + b * y ^ 2 = z ^ 2

/-- `signOf x = (-1)^x ∈ ℤˣ = {±1}`. -/
def signOf (x : ZMod 2) : ℤˣ := if x = 0 then 1 else -1

/-- The (quadratic) **Hilbert symbol** `(a, b)₂ ∈ ℤˣ = {±1}` for `a, b ∈ ℚ₂ˣ`: `+1` iff
`a X² + b Y² = Z²` has a nontrivial solution, else `-1`. -/
noncomputable def hilbertSymbol (a b : ℚ_[2]ˣ) : ℤˣ :=
  if IsHilbertSolvable (a : ℚ_[2]) (b : ℚ_[2]) then 1 else -1

/-! ## Elementary identities (theorems, from the definition) -/


/-! ## Serre's residue characters `ε` and `ω`  (CiA Ch. II §3.3)

`ε` and `ω` depend only on `u (mod 8)`, so they factor through the reduction `ℤ₂ → ℤ/8`.  We define
them by the literal formulas `(u-1)/2` and `(u²-1)/8` on the residue's canonical representative
`ZMod.val ∈ {0,…,7}` (both numerators are divisible by `2`, resp. `8`, on the odd residues). -/

/-- `ε` on residues: `(r - 1)/2 mod 2`, using the representative `r.val ∈ {0,…,7}`. -/
def epsResidue (r : ZMod 8) : ZMod 2 := ((r.val - 1) / 2 : ℕ)

/-- `ω` on residues: `(r² - 1)/8 mod 2`, using the representative `r.val ∈ {0,…,7}`. -/
def omegaResidue (r : ZMod 8) : ZMod 2 := ((r.val ^ 2 - 1) / 8 : ℕ)

/-- `ε(u) ≡ (u - 1)/2 (mod 2)` — Serre, *A Course in Arithmetic*, Ch. II §3.3. -/
noncomputable def ε (u : ℤ_[2]ˣ) : ZMod 2 := epsResidue (PadicInt.toZModPow 3 (u : ℤ_[2]))

/-- `ω(u) ≡ (u² - 1)/8 (mod 2)` — Serre, *A Course in Arithmetic*, Ch. II §3.3. -/
noncomputable def ω (u : ℤ_[2]ˣ) : ZMod 2 := omegaResidue (PadicInt.toZModPow 3 (u : ℤ_[2]))


/-- The reduction of the unit `-1 ∈ ℤ₂ˣ` is `-1 ∈ ℤ/8`. -/
theorem toZModPow_neg_one : PadicInt.toZModPow 3 ((-1 : ℤ_[2]ˣ) : ℤ_[2]) = -1 := by
  rw [Units.val_neg, Units.val_one, map_neg, map_one]

/-- `ε(-1) = 1` (as `-1 ≡ 3 (mod 4)`); checks the `ℤ₂ˣ → 𝔽₂` reduction, not just the residue. -/
theorem ε_neg_one : ε (-1) = 1 := by
  rw [ε, toZModPow_neg_one]; decide

/-- `ω(-1) = 0` (as `-1 ≡ -1 (mod 8)`); checks the `ℤ₂ˣ → 𝔽₂` reduction, not just the residue. -/
theorem ω_neg_one : ω (-1) = 0 := by
  rw [ω, toZModPow_neg_one]; decide


/-! ## Inputs of the dyadic Hilbert-symbol formula (former axiom B7′)

The statement itself — `(2^α u, 2^β v)₂ = (-1)^{ε(u)ε(v) + αω(v) + βω(u)}`, Serre CiA III §1.2
Thm 1 — lives in `GQ2/Foundations/Axioms.lean` (`GQ2.HilbertSymbol.hilbertSymbol_dyadic`,
consolidated there by T-19; since 2026-07-09 a same-name *theorem*, proved in-repo via
`GQ2/HilbertSymbolDyadicClose.lean`), together with its faithfulness check `(-1,-1)₂ = -1`.  Here we
provide the two decomposition inputs of its statement. -/

/-- The unit `2 ∈ ℚ₂ˣ`. -/
noncomputable def unit2 : ℚ_[2]ˣ := Units.mk0 2 (by norm_num)

/-- The inclusion of units `ℤ₂ˣ → ℚ₂ˣ` induced by `ℤ₂ ↪ ℚ₂`. -/
noncomputable def unitCoe (u : ℤ_[2]ˣ) : ℚ_[2]ˣ :=
  Units.map (PadicInt.Coe.ringHom (p := 2)).toMonoidHom u

end GQ2.HilbertSymbol

/-! ### Paper-tag ledger (auto-generated by paperforge; do not edit)

  * Lemma 3.5 = ⟦lem-markedinitialform⟧
-/
