/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-4.8 and Fable-5
-/
module

public import Mathlib.GroupTheory.SemidirectProduct
public import GQ2.AppendixB
public import GQ2.SectionThree
public import GQ2.Tame
public import GQ2.Foundations.Axioms

@[expose] public section

set_option backward.privateInPublic true
set_option backward.privateInPublic.warn false

/-!
# Proposition 3.2 — proofs

Proves the §3 statements for the paper's **Prop. 3.2** (common tame quotient) and the two
`ν`-surjectivities of Prop. 3.14.  The theorems are declared here, in the same
`GQ2.SectionThree` namespace, because their proofs import the definition layer in
`GQ2/SectionThree.lean`.

* **`Γ_A` side** (`prop_3_2_gammaA`, axiom-free): the classifier `F₄ → T_tame`
  (`σ↦σ, τ↦τ, x₀,x₁↦1`) kills `N_A` — through every finite level the pushed marking
  `(σ̄, τ̄, 1, 1)` is *admissible*, because `τ̄` has odd order (Lemma 3.1, `GQ2/Tame.lean`),
  so `ω₂` kills it and the whole eq. (1)–(3) word ledger collapses (`u_i = d₀ = c₀ = d_g =
  h_c = h₀ = 1`), making relation (6) trivially true — exactly the paper's proof.  Descending
  and inverting via the presentation universal property gives the marked isomorphism
  `Γ_A/W_A ≅ T_tame`; the two composites are the identity by density of the marked
  generators.
* **`ν`-surjectivities** (`nuT_surjective`, `nuTwo_surjective`, axiom-free): the ranges are
  closed subgroups (continuous images of compact groups) containing `ν(σ) = 1`, and `1`
  topologically generates `Z₂` (via `ℤ` dense in `ℤ̂`, the profinite-exponentiation API).
* **Local side** (`prop_3_2_local`, `Ax = B10`): the axiom `GQ2.tameQuotient` supplies the
  closed normal pro-2 `W` with `G_{ℚ₂}/W ≅ T_tame`; Lemma 3.3's **maximality** is proved —
  `T_tame` has no nontrivial "normal subgroup with 2-group finite images", by the paper's
  argument: through each Fermat-level quotient `C_{2^{2^m}−1} ⋊ C_{2^m}` (faithful squaring
  action, trivial center) the image is central hence trivial, so the `Ẑ`-coordinate of such
  a subgroup is infinitely 2-divisible; the inertia part then dies levelwise (odd ∧ 2-power).

Infrastructure (all axiom-free): topological generation of free profinite groups by their
generators (also proved by the finite-generation proof's `GQ2/FinitelyGenerated.lean` in `IsTopologicallyFinGen`
packaging; the overlap is one lemma deep and flagged for dedup), its transfer along
continuous surjections and into finite quotients, and equality-on-topological-generators for
continuous homomorphisms.
-/

open CategoryTheory

namespace GQ2

namespace SectionThree

/-! ## Topological generation: free profinite groups and their quotients -/

/-- `Set.range` of a `Fin 2`-tuple is the unordered pair. -/
lemma range_fin_two {α : Type*} (v : Fin 2 → α) : Set.range v = {v 0, v 1} := by
  ext x
  simp [Fin.exists_fin_two, eq_comm]

/-- The free profinite group is topologically generated by its generators (the discrete free
group is dense in its profinite completion).  Cf. the finite-generation proof's `GQ2/FinitelyGenerated.lean` for the
same fact in `IsTopologicallyFinGen` packaging. -/
theorem topGen_freeProfiniteGroup (X : Type) :
    (Subgroup.closure (Set.range (FreeProfiniteGroup.of (X := X)))).topologicalClosure = ⊤ := by
  set g : FreeGroup X →* FreeProfiniteGroup X :=
    (ProfiniteGrp.ProfiniteCompletion.eta (GrpCat.of (FreeGroup X))).hom with hg
  have h1 : Set.range (FreeProfiniteGroup.of (X := X))
      = ⇑g '' Set.range (FreeGroup.of : X → FreeGroup X) := by
    rw [← Set.range_comp]; rfl
  have hrange : Subgroup.closure (Set.range (FreeProfiniteGroup.of (X := X))) = g.range := by
    rw [h1, ← MonoidHom.map_closure, FreeGroup.closure_range_of X, ← MonoidHom.range_eq_map]
  rw [hrange]
  have hdense : DenseRange g := ProfiniteGrp.ProfiniteCompletion.denseRange _
  rw [SetLike.ext'_iff]
  simpa only [Subgroup.topologicalClosure_coe, Subgroup.coe_top, MonoidHom.coe_range]
    using hdense.closure_range

/-- Topological generation transfers along a continuous surjective homomorphism. -/
theorem topGen_map {G H : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (f : G →* H) (hcont : Continuous f) (hsurj : Function.Surjective f) {S : Set G}
    (hS : (Subgroup.closure S).topologicalClosure = ⊤) :
    (Subgroup.closure (f '' S)).topologicalClosure = ⊤ := by
  rw [← MonoidHom.map_closure]
  exact hsurj.denseRange.topologicalClosure_map_subgroup hcont hS

/-- In a discrete (e.g. finite) group, topological generation is plain generation. -/
theorem gen_of_topGen_discrete {H : Type*} [Group H] [TopologicalSpace H]
    [IsTopologicalGroup H] [DiscreteTopology H] {S : Set H}
    (hS : (Subgroup.closure S).topologicalClosure = ⊤) :
    Subgroup.closure S = ⊤ := by
  have h1 : (Subgroup.closure S).topologicalClosure = Subgroup.closure S := by
    apply SetLike.ext'
    rw [Subgroup.topologicalClosure_coe]
    exact (isClosed_discrete _).closure_eq
  rwa [h1] at hS

/-- Two continuous homomorphisms agreeing on a topologically generating set agree
everywhere. -/
theorem monoidHom_eq_of_topGen {G H : Type*} [Group G] [TopologicalSpace G]
    [IsTopologicalGroup G] [Group H] [TopologicalSpace H] [T2Space H] {f g : G →* H}
    (hf : Continuous f) (hg : Continuous g)
    {S : Set G} (hS : (Subgroup.closure S).topologicalClosure = ⊤)
    (h : ∀ x ∈ S, f x = g x) : ∀ x, f x = g x := by
  -- the equalizer is a closed subgroup containing `S`
  let E : Subgroup G :=
    { carrier := {x | f x = g x}
      one_mem' := by simp
      mul_mem' := fun ha hb => by
        simp only [Set.mem_setOf_eq] at *
        rw [map_mul, map_mul, ha, hb]
      inv_mem' := fun ha => by
        simp only [Set.mem_setOf_eq] at *
        rw [map_inv, map_inv, ha] }
  have hE : (Subgroup.closure S).topologicalClosure ≤ E :=
    Subgroup.topologicalClosure_minimal _
      ((Subgroup.closure_le E).mpr fun x hx => h x hx) (isClosed_eq hf hg)
  intro x
  exact hE (hS ▸ Subgroup.mem_top x)

/-! ## Marked topological generation of `T_tame` and its finite levels -/

/-- `T_tame` is topologically generated by `σ, τ`. -/
theorem topGen_ttame :
    (Subgroup.closure {tameSigma, tameTau}).topologicalClosure = ⊤ := by
  have h := topGen_map (f := (quotientMk (relatorSubgroup {tameWord})).toMonoidHom)
    (quotientMk (relatorSubgroup {tameWord})).continuous_toFun (quotientMk_surjective _)
    (topGen_freeProfiniteGroup (Fin 2))
  have h1 : (⇑(quotientMk (relatorSubgroup {tameWord})).toMonoidHom) ''
      Set.range (FreeProfiniteGroup.of (X := Fin 2)) = {tameSigma, tameTau} := by
    rw [← Set.range_comp, range_fin_two]
    rfl
  rwa [h1] at h

/-- In every discrete continuous quotient of `T_tame`, the images of `σ, τ` generate. -/
theorem gen_ttame_quotient {H : Type*} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [DiscreteTopology H] (f : Ttame →* H) (hcont : Continuous f)
    (hsurj : Function.Surjective f) :
    Subgroup.closure {f tameSigma, f tameTau} = ⊤ := by
  have h := topGen_map f hcont hsurj topGen_ttame
  rw [Set.image_insert_eq, Set.image_singleton] at h
  exact gen_of_topGen_discrete h

/-! ## The word-ledger collapse

Paper, proofs of Prop. 3.2 / Prop. 3.10: at a marking with trivial wild letters and
odd-order `τ`, the `ω₂`-exponent kills `τ`-words and the auxiliary words (1)–(3) all
collapse to `1`, so relation (6) holds trivially. -/

/-- `x^{ω₂} = 1` for an element of odd order (the `2`-primary part of an odd-order element). -/
lemma powOmega2_eq_one_of_odd {G : Type*} [Group G] {x : G} (hx : Odd (orderOf x)) :
    powOmega2 x = 1 := by
  have h2 : (orderOf x).factorization 2 = 0 := by
    refine Nat.factorization_eq_zero_of_not_dvd ?_
    have := Nat.odd_iff.mp hx
    omega
  rw [powOmega2, omega2Exp, h2]
  simp

/-! ## The `Γ_A` side: the classifier and its levels -/

/-- The classifier `F₄ ⟶ T_tame`: `σ ↦ σ, τ ↦ τ, x₀ ↦ 1, x₁ ↦ 1`. -/
noncomputable def tameClassifier : FreeProfiniteGroup (Fin 4) ⟶ Ttame :=
  (FreeProfiniteGroup.homEquiv (Fin 4) Ttame).symm ![tameSigma, tameTau, 1, 1]

@[simp] private lemma tameClassifier_sigma :
    tameClassifier.hom.toMonoidHom univMarking.σ = tameSigma :=
  FreeProfiniteGroup.homEquiv_symm_of _ _ _

@[simp] private lemma tameClassifier_tau :
    tameClassifier.hom.toMonoidHom univMarking.τ = tameTau :=
  FreeProfiniteGroup.homEquiv_symm_of _ _ _

@[simp] private lemma tameClassifier_x0 :
    tameClassifier.hom.toMonoidHom univMarking.x₀ = 1 :=
  FreeProfiniteGroup.homEquiv_symm_of _ _ _

@[simp] private lemma tameClassifier_x1 :
    tameClassifier.hom.toMonoidHom univMarking.x₁ = 1 :=
  FreeProfiniteGroup.homEquiv_symm_of _ _ _

/-- Through every open normal level of `T_tame`, the marking pushed from the classifier is
admissible: `τ̄` has odd order (Lemma 3.1), so the ledger collapses. -/
theorem isAdmissible_tameClassifier_level (V : OpenNormalSubgroup Ttame) :
    (univMarking.map ((QuotientGroup.mk' V.toSubgroup).comp
      tameClassifier.hom.toMonoidHom)).Admissible := by
  haveI : Finite (Ttame ⧸ V.toSubgroup) := inferInstance
  set q : Ttame →* Ttame ⧸ V.toSubgroup := QuotientGroup.mk' V.toSubgroup with hq
  set f : FreeProfiniteGroup (Fin 4) →* Ttame ⧸ V.toSubgroup :=
    q.comp tameClassifier.hom.toMonoidHom with hf
  -- the pushed marking is `(σ̄, τ̄, 1, 1)`
  have hσ : (univMarking.map f).σ = q tameSigma := by
    show f univMarking.σ = q tameSigma
    rw [hf, MonoidHom.comp_apply, tameClassifier_sigma]
  have hτ : (univMarking.map f).τ = q tameTau := by
    show f univMarking.τ = q tameTau
    rw [hf, MonoidHom.comp_apply, tameClassifier_tau]
  have hx₀ : (univMarking.map f).x₀ = 1 := by
    show f univMarking.x₀ = 1
    rw [hf, MonoidHom.comp_apply, tameClassifier_x0, map_one]
  have hx₁ : (univMarking.map f).x₁ = 1 := by
    show f univMarking.x₁ = 1
    rw [hf, MonoidHom.comp_apply, tameClassifier_x1, map_one]
  -- the tame relation at the level
  have hrel : (q tameSigma)⁻¹ * q tameTau * q tameSigma = (q tameTau) ^ 2 := by
    have h := congrArg (⇑q) tame_relation
    rw [map_pow, Marking.map_conjP] at h
    simpa [conjP] using h
  -- odd order of `τ̄` (Lemma 3.1)
  have hodd : Odd (orderOf (q tameTau)) :=
    Tame.tame_odd_order (orderOf_pos (q tameSigma)).ne' hrel
  refine ⟨?_, ?_, ?_, ?_⟩
  · -- generates
    rw [Marking.Generates, hσ, hτ, hx₀, hx₁]
    have hgen2 : Subgroup.closure {q tameSigma, q tameTau} = ⊤ :=
      gen_ttame_quotient q continuous_quot_mk (QuotientGroup.mk'_surjective _)
    rw [eq_top_iff, ← hgen2]
    refine Subgroup.closure_mono ?_
    intro z hz
    rcases hz with rfl | rfl
    · exact Set.mem_insert _ _
    · exact Set.mem_insert_of_mem _ (Set.mem_insert _ _)
  · -- tame relation
    rw [Marking.TameRel, hσ, hτ]
    simpa [conjP] using hrel
  · -- wild relation, via the ledger collapse
    have h := Marking.wildRel_of_trivial_wild (Marking.mk (q tameSigma) (q tameTau) 1 1) rfl rfl
      (powOmega2_eq_one_of_odd hodd)
    have ht : univMarking.map f = Marking.mk (q tameSigma) (q tameTau) 1 1 := by
      rw [show univMarking.map f = Marking.mk (univMarking.map f).σ (univMarking.map f).τ
        (univMarking.map f).x₀ (univMarking.map f).x₁ from rfl, hσ, hτ, hx₀, hx₁]
    rwa [ht]
  · -- pro-2 core: the wild letters are trivial
    rw [Marking.Pro2Core, hx₀, hx₁]
    have hset : ({(1 : Ttame ⧸ V.toSubgroup), 1} : Set _) = {1} := by simp
    have hbot : Subgroup.normalClosure ({(1 : Ttame ⧸ V.toSubgroup), 1} : Set _) = ⊥ := by
      rw [hset, eq_bot_iff]
      refine Subgroup.normalClosure_le_normal ?_
      simp
    rw [hbot]
    intro x
    exact ⟨0, by
      rw [pow_zero, pow_one]
      exact Subtype.ext (Subgroup.mem_bot.mp x.2)⟩

/-! ## The descent `Γ_A → T_tame` and its inverse -/

/-- The tame relator of the universal marking lies in `N_A` (it dies in every admissible
quotient — relation (5) is part of admissibility).  Also proved by the admissible-limit proof's
`GQ2/AdmissibleLimit.lean`; kept inline for import hygiene, flagged for dedup. -/
theorem tameRelator_mem_NA' : univMarking.tameRelator ∈ NA := by
  refine Subgroup.mem_iInf.mpr fun U => ?_
  have htame : (univMarking.map (QuotientGroup.mk' U.1.toSubgroup)).TameRel := U.2.2.1
  rw [Marking.TameRel] at htame
  have h1 : QuotientGroup.mk' U.1.toSubgroup univMarking.tameRelator = 1 := by
    rw [Marking.tameRelator, map_mul, map_inv, map_pow, Marking.map_conjP]
    rw [show (QuotientGroup.mk' U.1.toSubgroup) univMarking.τ
        = (univMarking.map (QuotientGroup.mk' U.1.toSubgroup)).τ from rfl,
      show (QuotientGroup.mk' U.1.toSubgroup) univMarking.σ
        = (univMarking.map (QuotientGroup.mk' U.1.toSubgroup)).σ from rfl, htame]
    simp
  exact (QuotientGroup.eq_one_iff _).mp h1

/-- `N_A` is contained in the kernel of the classifier `F₄ → T_tame` (each of its finite
levels is an admissible quotient, by `isAdmissible_tameClassifier_level`). -/
theorem NA_le_ker_tameClassifier :
    NA ≤ tameClassifier.hom.toMonoidHom.ker := by
  intro x hx
  rw [MonoidHom.mem_ker]
  refine eq_one_of_forall_mem_openNormalSubgroup fun V => ?_
  haveI : Finite (Ttame ⧸ V.toSubgroup) := inferInstance
  set f : ContinuousMonoidHom (FreeProfiniteGroup (Fin 4)) (Ttame ⧸ V.toSubgroup) :=
    (quotientMk V.toSubgroup).comp tameClassifier.hom with hf
  have hadm : (univMarking.map f.toMonoidHom).Admissible :=
    isAdmissible_tameClassifier_level V
  have hker := NA_le_ker f hadm hx
  rw [MonoidHom.mem_ker] at hker
  have h1 : QuotientGroup.mk' V.toSubgroup (tameClassifier.hom.toMonoidHom x) = 1 := hker
  exact (QuotientGroup.eq_one_iff _).mp h1

/-- The `↥Γ_A`-spelled copy of `wildPart` (definitionally equal; the admissible-limit layer spells
`wildPart` at the raw quotient `F₄ ⧸ N_A`, but this file's constructions all run at the
bundled-carrier spelling `↥Γ_A`, where the `ProfiniteGrp` instance path applies uniformly). -/
noncomputable def wildPartB : Subgroup (GammaA : Type) := wildPart

instance wildPartB_normal : wildPartB.Normal := wildPart_normal

private lemma wildPartB_isClosed : IsClosed (wildPartB : Set (GammaA : Type)) := wildPart_isClosed

lemma wildPartB_eq_closure :
    wildPartB = (Subgroup.normalClosure {gammaX0, gammaX1}).topologicalClosure :=
  wildPart_eq_closure

/-- The descent `φ_A : Γ_A → T_tame` of the classifier (`σ↦σ, τ↦τ, x₀,x₁↦1`). -/
noncomputable def phiA : ContinuousMonoidHom GammaA Ttame :=
  haveI : IsClosed (NA : Set (FreeProfiniteGroup (Fin 4))) := NA_isClosed
  quotientLift NA tameClassifier.hom NA_le_ker_tameClassifier

@[simp] lemma phiA_gammaSigma : phiA gammaSigma = tameSigma := by
  haveI : IsClosed (NA : Set (FreeProfiniteGroup (Fin 4))) := NA_isClosed
  show phiA (quotientMk NA univMarking.σ) = tameSigma
  exact (quotientLift_quotientMk _ _ _ _).trans tameClassifier_sigma

@[simp] lemma phiA_gammaTau : phiA gammaTau = tameTau := by
  haveI : IsClosed (NA : Set (FreeProfiniteGroup (Fin 4))) := NA_isClosed
  show phiA (quotientMk NA univMarking.τ) = tameTau
  exact (quotientLift_quotientMk _ _ _ _).trans tameClassifier_tau

@[simp] lemma phiA_gammaX0 : phiA gammaX0 = 1 := by
  haveI : IsClosed (NA : Set (FreeProfiniteGroup (Fin 4))) := NA_isClosed
  show phiA (quotientMk NA univMarking.x₀) = 1
  exact (quotientLift_quotientMk _ _ _ _).trans tameClassifier_x0

@[simp] lemma phiA_gammaX1 : phiA gammaX1 = 1 := by
  haveI : IsClosed (NA : Set (FreeProfiniteGroup (Fin 4))) := NA_isClosed
  show phiA (quotientMk NA univMarking.x₁) = 1
  exact (quotientLift_quotientMk _ _ _ _).trans tameClassifier_x1

/-- `W_A ≤ ker φ_A` (the wild generators map to `1`, and the kernel is closed normal). -/
theorem wildPartB_le_ker_phiA : wildPartB ≤ phiA.toMonoidHom.ker := by
  have hker_closed : IsClosed (phiA.toMonoidHom.ker : Set GammaA) := by
    rw [MonoidHom.coe_ker]
    exact IsClosed.preimage phiA.continuous_toFun isClosed_singleton
  rw [wildPartB_eq_closure]
  refine Subgroup.topologicalClosure_minimal _ ?_ hker_closed
  refine Subgroup.normalClosure_le_normal ?_
  rintro z (rfl | rfl)
  · exact MonoidHom.mem_ker.mpr phiA_gammaX0
  · exact MonoidHom.mem_ker.mpr phiA_gammaX1

/-- `ψ : Γ_A/W_A → T_tame`, the descent of `φ_A`. -/
noncomputable def psiW : ContinuousMonoidHom (GammaA ⧸ wildPartB) Ttame :=
  quotientLift wildPartB phiA wildPartB_le_ker_phiA

/-- `Γ_A/W_A` as a profinite group (for the universal property of `T_tame`'s presentation). -/
noncomputable def TameA : ProfiniteGrp :=
  haveI : IsClosed (wildPartB : Set (GammaA : Type)) := wildPartB_isClosed
  profiniteQuotient wildPartB

/-- The base map `F₂ ⟶ Γ_A/W_A`: `σ ↦ σ̄, τ ↦ τ̄`. -/
noncomputable def chiBase : FreeProfiniteGroup (Fin 2) ⟶ TameA :=
  (FreeProfiniteGroup.homEquiv (Fin 2) TameA).symm
    ![quotientMk wildPartB gammaSigma, quotientMk wildPartB gammaTau]

@[simp] private lemma chiBase_of_zero :
    chiBase.hom.toMonoidHom (FreeProfiniteGroup.of 0) = quotientMk wildPartB gammaSigma :=
  FreeProfiniteGroup.homEquiv_symm_of _ _ _

@[simp] private lemma chiBase_of_one :
    chiBase.hom.toMonoidHom (FreeProfiniteGroup.of 1) = quotientMk wildPartB gammaTau :=
  FreeProfiniteGroup.homEquiv_symm_of _ _ _

/-- The base map kills the tame relator: its image is the `W_A`-class of the `Γ_A`-image of
`univMarking.tameRelator ∈ N_A`. -/
theorem chiBase_tameWord : chiBase.hom.toMonoidHom tameWord = 1 := by
  haveI : IsClosed (NA : Set (FreeProfiniteGroup (Fin 4))) := NA_isClosed
  have h1 : chiBase.hom.toMonoidHom tameWord
      = quotientMk wildPartB (quotientMk NA univMarking.tameRelator) := by
    rw [tameWord, Marking.tameRelator]
    simp only [map_mul, map_inv, map_pow, Marking.map_conjP, chiBase_of_zero, chiBase_of_one]
    rfl
  rw [h1, show quotientMk NA univMarking.tameRelator = 1 from
    (quotientMk_eq_one_iff _).mpr tameRelator_mem_NA']
  exact map_one _

/-- `χ : T_tame → Γ_A/W_A`, by the universal property of the presentation. -/
noncomputable def chiW : ContinuousMonoidHom Ttame TameA :=
  presentationLift {tameWord} chiBase.hom fun r hr => by
    rcases hr with rfl
    exact chiBase_tameWord

@[simp] private lemma chiW_tameSigma : chiW tameSigma = quotientMk wildPartB gammaSigma := by
  show chiW (quotientMk (relatorSubgroup {tameWord}) (FreeProfiniteGroup.of 0)) = _
  exact (presentationLift_mk _ _ _ _).trans chiBase_of_zero

@[simp] private lemma chiW_tameTau : chiW tameTau = quotientMk wildPartB gammaTau := by
  show chiW (quotientMk (relatorSubgroup {tameWord}) (FreeProfiniteGroup.of 1)) = _
  exact (presentationLift_mk _ _ _ _).trans chiBase_of_one

@[simp] private lemma psiW_mk_gammaSigma : psiW (quotientMk wildPartB gammaSigma) = tameSigma := by
  exact (quotientLift_quotientMk _ _ _ _).trans phiA_gammaSigma

@[simp] private lemma psiW_mk_gammaTau : psiW (quotientMk wildPartB gammaTau) = tameTau := by
  exact (quotientLift_quotientMk _ _ _ _).trans phiA_gammaTau

/-- `Γ_A/W_A` is topologically generated by the classes of the four marked generators. -/
theorem topGen_tameA :
    (Subgroup.closure (Set.range fun i : Fin 4 =>
      quotientMk wildPartB (quotientMk NA (FreeProfiniteGroup.of i)))).topologicalClosure
      = ⊤ := by
  haveI : IsClosed (NA : Set (FreeProfiniteGroup (Fin 4))) := NA_isClosed
  have h := topGen_map
    (f := ((quotientMk wildPartB).comp (quotientMk NA)).toMonoidHom)
    ((quotientMk wildPartB).comp (quotientMk NA)).continuous_toFun
    ((quotientMk_surjective wildPartB).comp (quotientMk_surjective NA))
    (topGen_freeProfiniteGroup (Fin 4))
  rwa [← Set.range_comp] at h

/-- `ψ ∘ χ = id` on `T_tame` (both send `σ ↦ σ, τ ↦ τ`; density). -/
theorem psiW_chiW (x : Ttame) : psiW (chiW x) = x := by
  have h := monoidHom_eq_of_topGen
    (f := psiW.toMonoidHom.comp chiW.toMonoidHom) (g := MonoidHom.id Ttame)
    (by rw [MonoidHom.coe_comp]
        exact Continuous.comp psiW.continuous_toFun chiW.continuous_toFun) continuous_id
    topGen_ttame ?_
  · exact h x
  · rintro z (rfl | rfl)
    · show psiW (chiW tameSigma) = tameSigma
      rw [chiW_tameSigma, psiW_mk_gammaSigma]
    · show psiW (chiW tameTau) = tameTau
      rw [chiW_tameTau, psiW_mk_gammaTau]

/-- `χ ∘ ψ = id` on `Γ_A/W_A` (checked on the four marked generator classes; density). -/
theorem chiW_psiW (x : GammaA ⧸ wildPartB) : chiW (psiW x) = x := by
  haveI : IsClosed (NA : Set (FreeProfiniteGroup (Fin 4))) := NA_isClosed
  have h := monoidHom_eq_of_topGen
    (f := chiW.toMonoidHom.comp psiW.toMonoidHom) (g := MonoidHom.id _)
    (by rw [MonoidHom.coe_comp]
        exact Continuous.comp chiW.continuous_toFun psiW.continuous_toFun) continuous_id
    topGen_tameA ?_
  · exact h x
  · rintro z ⟨i, rfl⟩
    fin_cases i
    · show chiW (psiW (quotientMk wildPartB gammaSigma)) = quotientMk wildPartB gammaSigma
      rw [psiW_mk_gammaSigma, chiW_tameSigma]
    · show chiW (psiW (quotientMk wildPartB gammaTau)) = quotientMk wildPartB gammaTau
      rw [psiW_mk_gammaTau, chiW_tameTau]
    · -- `x₀`-class is `1`
      have hx : quotientMk wildPartB gammaX0 = 1 := by
        rw [quotientMk_eq_one_iff, wildPartB_eq_closure]
        exact Subgroup.le_topologicalClosure _
          (Subgroup.subset_normalClosure (Set.mem_insert _ _))
      show chiW (psiW (quotientMk wildPartB gammaX0)) = quotientMk wildPartB gammaX0
      rw [hx, map_one, map_one]
      rfl
    · -- `x₁`-class is `1`
      have hx : quotientMk wildPartB gammaX1 = 1 := by
        rw [quotientMk_eq_one_iff, wildPartB_eq_closure]
        exact Subgroup.le_topologicalClosure _
          (Subgroup.subset_normalClosure (Set.mem_insert_of_mem _ rfl))
      show chiW (psiW (quotientMk wildPartB gammaX1)) = quotientMk wildPartB gammaX1
      rw [hx, map_one, map_one]
      rfl

/-- The marked isomorphism `Γ_A/W_A ≅ T_tame` (Prop. 3.2, `Γ_A` side). -/
noncomputable def tameAEquiv : ContinuousMulEquiv (GammaA ⧸ wildPartB) Ttame where
  toFun := psiW
  invFun := chiW
  left_inv := chiW_psiW
  right_inv := psiW_chiW
  map_mul' := map_mul psiW
  continuous_toFun := psiW.continuous_toFun
  continuous_invFun := chiW.continuous_toFun

/-- **Prop. 3.2, `Γ_A` side**: the quotient of `Γ_A` by `W_A` is `T_tame`,
matching the marked generators. -/
theorem prop_3_2_gammaA :
    ∃ e : ContinuousMulEquiv (GammaA ⧸ wildPart) Ttame,
      e (QuotientGroup.mk gammaSigma) = tameSigma ∧
      e (QuotientGroup.mk gammaTau) = tameTau :=
  ⟨tameAEquiv, psiW_mk_gammaSigma, psiW_mk_gammaTau⟩

/-! ## The `ν`-surjectivities of Prop. 3.14 -/

/-- `ℤ̂` is topologically generated by `1`. -/
theorem topGen_zhat :
    (Subgroup.closure {Zhat.ofInt 1}).topologicalClosure = ⊤ := by
  have hneg : Zhat.ofInt (-1) = (Zhat.ofInt 1)⁻¹ := by
    refine eq_inv_of_mul_eq_one_left ?_
    rw [← Zhat.ofInt_add, show (-1 + 1 : ℤ) = 0 from by norm_num, Zhat.ofInt_zero]
  have hzpow : ∀ n : ℤ, Zhat.ofInt n = Zhat.ofInt 1 ^ n := by
    intro n
    induction n using Int.induction_on with
    | zero => rw [Zhat.ofInt_zero, zpow_zero]
    | succ k ih => rw [Zhat.ofInt_add, ih, zpow_add_one]
    | pred k ih =>
      rw [sub_eq_add_neg, Zhat.ofInt_add, ih, hneg, zpow_add, zpow_neg_one]
  have hsub : Set.range Zhat.ofInt ⊆ (Subgroup.closure {Zhat.ofInt 1} : Set _) := by
    rintro _ ⟨n, rfl⟩
    rw [hzpow n]
    exact zpow_mem (Subgroup.subset_closure (Set.mem_singleton _)) n
  apply SetLike.ext'
  rw [Subgroup.topologicalClosure_coe, Subgroup.coe_top]
  refine Set.eq_univ_of_univ_subset ?_
  calc (Set.univ : Set Zhat) = closure (Set.range Zhat.ofInt) :=
        Zhat.denseRange_ofInt.closure_range.symm
    _ ⊆ closure (Subgroup.closure {Zhat.ofInt 1} : Set _) := closure_mono hsub

/-- `Z₂` is topologically generated by `ztwoOne`. -/
theorem topGen_ztwo :
    (Subgroup.closure {ztwoOne}).topologicalClosure = ⊤ := by
  have h := topGen_map (f := (maxProPMk 2 Zhat).toMonoidHom)
    (maxProPMk 2 Zhat).continuous_toFun
    (quotientMk_surjective (proPKernel 2 Zhat)) topGen_zhat
  rwa [Set.image_singleton] at h

/-- A continuous homomorphism from a compact group hitting a topological generator of a `T2`
target is surjective. -/
theorem surjective_of_mem_range_topGen {G H : Type*} [Group G] [TopologicalSpace G]
    [CompactSpace G] [Group H] [TopologicalSpace H] [IsTopologicalGroup H] [T2Space H]
    (f : ContinuousMonoidHom G H) {x : H}
    (hgen : (Subgroup.closure {x}).topologicalClosure = ⊤)
    (hx : x ∈ Set.range f) : Function.Surjective f := by
  have hclosed : IsClosed (f.toMonoidHom.range : Set H) := by
    rw [MonoidHom.coe_range]
    exact (isCompact_range f.continuous_toFun).isClosed
  have h1 : Subgroup.closure {x} ≤ f.toMonoidHom.range := by
    rw [Subgroup.closure_le, Set.singleton_subset_iff]
    exact hx
  have h2 : (Subgroup.closure {x}).topologicalClosure ≤ f.toMonoidHom.range :=
    Subgroup.topologicalClosure_minimal _ h1 hclosed
  rw [hgen] at h2
  intro y
  exact h2 (Subgroup.mem_top y)

/-- **`ν_t : T_tame ↠ Z₂` is surjective** (Prop. 3.14's arrow).
`nuT` is qualified `GQ2.nuT` (the `BoundaryFrame` `Ttame → Z₂` map) to disambiguate from the
later `SectionThree.nuT` (the `ν_ur` descent through `(G_ℚ₂(2))^ab`, a different map) which
otherwise shadows it in this namespace. -/
theorem nuT_surjective : Function.Surjective GQ2.nuT :=
  surjective_of_mem_range_topGen GQ2.nuT topGen_ztwo ⟨tameSigma, nuT_tameSigma⟩

/-- **`ν₂ : Π ↠ Z₂` is surjective** (eq. (21)'s arrow). -/
theorem nuTwo_surjective : Function.Surjective nuTwo :=
  surjective_of_mem_range_topGen nuTwo topGen_ztwo ⟨piSigma, nuTwo_piSigma⟩

/-! ## Pro-2 subgroups have 2-group finite images -/

/-- A closed-subgroup-free transfer: if `N ≤ P` is pro-2 (as a topological group) then its
image under any continuous homomorphism to a finite discrete group is a 2-group. -/
theorem isPGroup_map_of_isProP {P : Type*} [Group P] [TopologicalSpace P] {N : Subgroup P}
    (hN : IsProP 2 N) {G : Type*} [Group G] [TopologicalSpace G] [DiscreteTopology G]
    (f : P →* G) (hf : Continuous f) : IsPGroup 2 (N.map f) := by
  set f' : N →* G := f.comp N.subtype with hf'
  have hf'cont : Continuous f' := hf.comp continuous_subtype_val
  have hker_open : IsOpen ((f'.ker : Subgroup N) : Set N) := by
    rw [MonoidHom.coe_ker]
    exact (isOpen_discrete _).preimage hf'cont
  set U : OpenNormalSubgroup N := ⟨⟨f'.ker, hker_open⟩, inferInstance⟩ with hU
  have hp : IsPGroup 2 (N ⧸ U.toSubgroup) := hN U
  have hrange : IsPGroup 2 f'.range :=
    hp.of_surjective (QuotientGroup.rangeKerLift f')
      (QuotientGroup.rangeKerLift_surjective f')
  have heq : f'.range = N.map f := by
    rw [hf', MonoidHom.range_comp, Subgroup.subtype_range]
  rwa [heq] at hrange

/-! ## The inertia quotient `Q = T_tame / ⟨⟨τ⟩⟩` -/

/-- The closed normal closure of `τ` in `T_tame` — the (pro-odd) tame inertia. -/
noncomputable def inertiaPart : Subgroup Ttame :=
  (Subgroup.normalClosure {tameTau}).topologicalClosure

instance inertiaPart_normal : inertiaPart.Normal :=
  Subgroup.is_normal_topologicalClosure _

/-- `Q = T_tame / ⟨⟨τ⟩⟩`, the procyclic unramified quotient. -/
noncomputable def Qur : ProfiniteGrp :=
  haveI : IsClosed (inertiaPart : Set Ttame) := Subgroup.isClosed_topologicalClosure _
  profiniteQuotient inertiaPart

/-- The projection `T_tame → Q`, typed at the bundled carrier. -/
noncomputable def qMk : ContinuousMonoidHom Ttame Qur := quotientMk inertiaPart

/-- The image of `σ` in `Q`. -/
noncomputable def qSigma : Qur := quotientMk inertiaPart tameSigma

private lemma qMk_tameTau : quotientMk inertiaPart tameTau = 1 := by
  rw [quotientMk_eq_one_iff]
  exact Subgroup.le_topologicalClosure _
    (Subgroup.subset_normalClosure (Set.mem_singleton _))

/-- `closure {a, 1} = closure {a}`. -/
lemma closure_pair_one {G : Type*} [Group G] (a : G) :
    Subgroup.closure {a, (1 : G)} = Subgroup.closure {a} := by
  refine le_antisymm ((Subgroup.closure_le _).mpr ?_) (Subgroup.closure_mono ?_)
  · rintro z (rfl | rfl)
    · exact Subgroup.subset_closure (Set.mem_singleton _)
    · exact Subgroup.one_mem _
  · exact Set.singleton_subset_iff.mpr (Set.mem_insert _ _)

/-- `Q` is topologically generated by `σ`. -/
theorem topGen_qur :
    (Subgroup.closure {qSigma}).topologicalClosure = ⊤ := by
  have h := topGen_map (f := (quotientMk inertiaPart).toMonoidHom)
    (quotientMk inertiaPart).continuous_toFun (quotientMk_surjective _) topGen_ttame
  rw [Set.image_insert_eq, Set.image_singleton] at h
  have h1 : (⇑(quotientMk inertiaPart).toMonoidHom) tameTau = 1 := qMk_tameTau
  rw [h1] at h
  rwa [closure_pair_one] at h

/-! ## The Fermat levels `G_m = C_{2^{2^m}−1} ⋊ C_{2^m}`

The paper's proof of Lemma 3.3: the finite quotients of `T_tame` in which geometric
Frobenius has order exactly `2^m` on inertia of order `e_m = 2^{2^m} − 1` (the squaring
action is *faithful*, since the order of `2 mod e_m` is exactly `2^m`).  Their centers are
trivial, so normal 2-subgroups die; this pins the `Ẑ`-coordinate of a pro-2 normal subgroup
to be divisible by every `2^m`. -/

section FermatLevels

variable (m : ℕ)

/-- `e_m = 2^{2^m} − 1`. -/
def emN : ℕ := 2 ^ (2 ^ m) - 1

instance : NeZero (emN m) :=
  ⟨Nat.sub_ne_zero_of_lt (Nat.one_lt_two_pow_iff.mpr (pow_ne_zero m two_ne_zero))⟩


lemma coprime_two_emN : Nat.Coprime 2 (emN m) := by
  rw [Nat.Prime.coprime_iff_not_dvd Nat.prime_two]
  intro hdvd
  have h1 : (2 : ℕ) ∣ 2 ^ (2 ^ m) := dvd_pow_self 2 (pow_ne_zero m two_ne_zero)
  have h2 : 2 ^ (2 ^ m) ≥ 2 := Nat.le_self_pow (pow_ne_zero m two_ne_zero) 2
  rw [emN] at hdvd
  omega

/-- The unit `2 ∈ (ℤ/e_m)ˣ`. -/
noncomputable def u2 : (ZMod (emN m))ˣ := ZMod.unitOfCoprime 2 (coprime_two_emN m)

private lemma u2_val_pow (j : ℕ) : ((u2 m ^ j : (ZMod (emN m))ˣ) : ZMod (emN m))
    = ((2 ^ j : ℕ) : ZMod (emN m)) := by
  rw [Units.val_pow_eq_pow_val, u2, ZMod.coe_unitOfCoprime]
  push_cast
  rfl

private lemma u2_pow_two_pow : u2 m ^ (2 ^ m) = 1 := by
  ext
  rw [u2_val_pow, Units.val_one,
    show (2 ^ 2 ^ m : ℕ) = emN m + 1 from (Nat.sub_add_cancel Nat.one_le_two_pow).symm,
    Nat.cast_add, ZMod.natCast_self, Nat.cast_one, zero_add]

/-- The order of `2 mod e_m` is exactly `2^m`, in the only form needed: no smaller power of
the unit `2` is `1`. -/
lemma u2_pow_eq_one_iff {j : ℕ} (hj : j < 2 ^ m) (h : u2 m ^ j = 1) : j = 0 := by
  have h1 : ((2 ^ j : ℕ) : ZMod (emN m)) = ((1 : ℕ) : ZMod (emN m)) := by
    have := congrArg (Units.val) h
    rw [u2_val_pow, Units.val_one] at this
    rw [this, Nat.cast_one]
  have h2 : (1 : ℕ) ≡ 2 ^ j [MOD emN m] := (ZMod.natCast_eq_natCast_iff _ _ _).mp h1.symm
  have h3 : emN m ∣ 2 ^ j - 1 :=
    (Nat.modEq_iff_dvd' Nat.one_le_two_pow).mp h2
  have h4 : 2 ^ j - 1 < emN m := by
    have hlt : (2 : ℕ) ^ j < 2 ^ 2 ^ m := Nat.pow_lt_pow_right one_lt_two hj
    have h1j : 1 ≤ 2 ^ j := Nat.one_le_two_pow
    rw [emN]
    omega
  have h5 : 2 ^ j - 1 = 0 := Nat.eq_zero_of_dvd_of_lt h3 h4
  have h6 : (2 : ℕ) ^ j = 1 := by
    have := Nat.one_le_two_pow (n := j)
    omega
  by_contra hj0
  exact absurd h6 (Nat.one_lt_two_pow_iff.mpr hj0).ne'

private lemma toMultAut_apply {e : ℕ} (u : (ZMod e)ˣ) (x : Multiplicative (ZMod e)) :
    AddEquiv.toMultiplicative (DistribMulAction.toAddEquiv (ZMod e) u) x
      = Multiplicative.ofAdd (u • Multiplicative.toAdd x) := rfl

/-- Units of `ZMod e`, acting as automorphisms of the *multiplicative* cyclic group of order
`e` (the vehicle for the squaring action of Frobenius on inertia). -/
def unitsMulAut (e : ℕ) : (ZMod e)ˣ →* MulAut (Multiplicative (ZMod e)) where
  toFun u := AddEquiv.toMultiplicative (DistribMulAction.toAddEquiv (ZMod e) u)
  map_one' := by
    ext x
    rw [toMultAut_apply, one_smul, MulAut.one_apply, ofAdd_toAdd]
  map_mul' u v := by
    ext x
    rw [MulAut.mul_apply, toMultAut_apply, toMultAut_apply, toMultAut_apply]
    simp only [toAdd_ofAdd, mul_smul]

private lemma unitsMulAut_apply (e : ℕ) (u : (ZMod e)ˣ) (x : Multiplicative (ZMod e)) :
    unitsMulAut e u x = Multiplicative.ofAdd ((u : ZMod e) * x.toAdd) := rfl

/-- The character `C_{2^m} → (ℤ/e_m)ˣ` sending the generator to `2⁻¹` (the *inverse*
squaring, so that `s⁻¹ t s = t²` holds with the paper's conjugation convention). -/
noncomputable def uChar : Multiplicative (ZMod (2 ^ m)) →* (ZMod (emN m))ˣ where
  toFun h := (u2 m)⁻¹ ^ (Multiplicative.toAdd h).val
  map_one' := by simp
  map_mul' a b := by
    have hper : ((u2 m)⁻¹) ^ (2 ^ m) = 1 := by
      rw [inv_pow, u2_pow_two_pow, inv_one]
    show (u2 m)⁻¹ ^ (Multiplicative.toAdd a + Multiplicative.toAdd b).val
      = (u2 m)⁻¹ ^ (Multiplicative.toAdd a).val * (u2 m)⁻¹ ^ (Multiplicative.toAdd b).val
    rw [ZMod.val_add, ← pow_add]
    exact (pow_eq_pow_mod _ hper).symm

/-- The Frobenius action `φ_m : C_{2^m} → Aut(C_{e_m})`. -/
noncomputable def phiFermat :
    Multiplicative (ZMod (2 ^ m)) →* MulAut (Multiplicative (ZMod (emN m))) :=
  (unitsMulAut (emN m)).comp (uChar m)

private lemma phiFermat_apply (h : Multiplicative (ZMod (2 ^ m))) (x : Multiplicative (ZMod (emN m))) :
    phiFermat m h x
      = Multiplicative.ofAdd
          ((((u2 m)⁻¹ ^ (Multiplicative.toAdd h).val : (ZMod (emN m))ˣ) : ZMod (emN m))
            * Multiplicative.toAdd x) := rfl

/-- **The Fermat level** `G_m = C_{e_m} ⋊ C_{2^m}` with (inverse-)squaring action.
(An `abbrev`, so all `SemidirectProduct` instances apply without wrapper friction.) -/
noncomputable abbrev GFermat :=
  SemidirectProduct (Multiplicative (ZMod (emN m))) (Multiplicative (ZMod (2 ^ m))) (phiFermat m)

instance instTopGFermat : TopologicalSpace (GFermat m) := ⊥
instance instDiscGFermat : DiscreteTopology (GFermat m) := ⟨rfl⟩

instance instFiniteGFermat : Finite (GFermat m) := by
  refine Finite.of_surjective
    (fun p : Multiplicative (ZMod (emN m)) × Multiplicative (ZMod (2 ^ m)) =>
      (⟨p.1, p.2⟩ : GFermat m)) ?_
  rintro ⟨k, h⟩
  exact ⟨(k, h), rfl⟩

/-- `s ∈ G_m`: the Frobenius generator. -/
noncomputable def sFermat : GFermat m := SemidirectProduct.inr (Multiplicative.ofAdd 1)

/-- `t ∈ G_m`: the inertia generator. -/
noncomputable def tFermat : GFermat m := SemidirectProduct.inl (Multiplicative.ofAdd 1)

private instance instSubsingletonGFermatZero : Subsingleton (GFermat 0) := by
  haveI h1 : Subsingleton (Multiplicative (ZMod (emN 0))) := by
    rw [show emN 0 = 1 from rfl]
    infer_instance
  haveI h2 : Subsingleton (Multiplicative (ZMod (2 ^ 0))) := by
    rw [show (2 : ℕ) ^ 0 = 1 from rfl]
    infer_instance
  exact ⟨fun a b => SemidirectProduct.ext (Subsingleton.elim _ _) (Subsingleton.elim _ _)⟩

/-- The tame relation holds in `G_m`: `s⁻¹ t s = t²`. -/
lemma fermat_relation : (sFermat m)⁻¹ * tFermat m * sFermat m = tFermat m ^ 2 := by
  rcases Nat.eq_zero_or_pos m with rfl | hm
  · exact Subsingleton.elim _ _
  have hval : ((1 : ZMod (2 ^ m))).val = 1 :=
    ZMod.val_one_eq_one_mod (2 ^ m) ▸ Nat.mod_eq_of_lt (Nat.one_lt_two_pow_iff.mpr hm.ne')
  have hchar : uChar m (Multiplicative.ofAdd 1) = (u2 m)⁻¹ := by
    show (u2 m)⁻¹ ^ ((1 : ZMod (2 ^ m))).val = _
    rw [hval, pow_one]
  have h1 : (sFermat m)⁻¹ * tFermat m * sFermat m
      = SemidirectProduct.inl ((phiFermat m (Multiplicative.ofAdd 1))⁻¹
          (Multiplicative.ofAdd 1)) := by
    rw [SemidirectProduct.inl_aut_inv, sFermat, tFermat, map_inv]
  rw [h1]
  have h2 : (phiFermat m (Multiplicative.ofAdd 1))⁻¹ = unitsMulAut _ (u2 m) := by
    rw [phiFermat, MonoidHom.comp_apply, hchar, ← map_inv, inv_inv]
  rw [h2, unitsMulAut_apply]
  have h3 : tFermat m ^ 2 = SemidirectProduct.inl (Multiplicative.ofAdd (1 + 1)) := by
    rw [tFermat, ← map_pow]
    congr 1
    rw [pow_two, ← ofAdd_add]
  rw [h3]
  congr 1
  simp only [toAdd_ofAdd]
  rw [show ((u2 m : (ZMod (emN m))ˣ) : ZMod (emN m)) = 2 from by
    rw [u2, ZMod.coe_unitOfCoprime]; push_cast; ring]
  ring_nf

/-- `G_m` is generated by `s, t`. -/
lemma fermat_gen : Subgroup.closure {sFermat m, tFermat m} = ⊤ := by
  have hs : sFermat m ∈ Subgroup.closure {sFermat m, tFermat m} :=
    Subgroup.subset_closure (Set.mem_insert _ _)
  have ht : tFermat m ∈ Subgroup.closure {sFermat m, tFermat m} :=
    Subgroup.subset_closure (Set.mem_insert_of_mem _ (Set.mem_singleton _))
  rw [eq_top_iff]
  rintro ⟨k, h⟩ -
  have hzdec : (⟨k, h⟩ : GFermat m)
      = SemidirectProduct.inl k * SemidirectProduct.inr h := by
    refine SemidirectProduct.ext ?_ ?_
    · show k = (SemidirectProduct.inl k * SemidirectProduct.inr h).left
      rw [SemidirectProduct.mul_left, SemidirectProduct.left_inl,
        SemidirectProduct.right_inl, map_one (phiFermat m), MulAut.one_apply,
        SemidirectProduct.left_inr, mul_one]
    · show h = (SemidirectProduct.inl k * SemidirectProduct.inr h).right
      rw [SemidirectProduct.mul_right, SemidirectProduct.right_inl,
        SemidirectProduct.right_inr, one_mul]
  rw [hzdec]
  have hk2 : k = (Multiplicative.ofAdd (1 : ZMod (emN m))) ^ (Multiplicative.toAdd k).val := by
    have h1 : ((Multiplicative.toAdd k).val • (1 : ZMod (emN m))) = Multiplicative.toAdd k := by
      rw [nsmul_eq_mul, mul_one, ZMod.natCast_val, ZMod.cast_id]
    rw [← ofAdd_nsmul, h1, ofAdd_toAdd]
  have hh2 : h = (Multiplicative.ofAdd (1 : ZMod (2 ^ m))) ^ (Multiplicative.toAdd h).val := by
    have h1 : ((Multiplicative.toAdd h).val • (1 : ZMod (2 ^ m))) = Multiplicative.toAdd h := by
      rw [nsmul_eq_mul, mul_one, ZMod.natCast_val, ZMod.cast_id]
    rw [← ofAdd_nsmul, h1, ofAdd_toAdd]
  have hpowK : SemidirectProduct.inl (φ := phiFermat m) k
      = tFermat m ^ (Multiplicative.toAdd k).val :=
    (congrArg _ hk2).trans (map_pow _ _ _)
  have hpowH : SemidirectProduct.inr (φ := phiFermat m) h
      = sFermat m ^ (Multiplicative.toAdd h).val :=
    (congrArg _ hh2).trans (map_pow _ _ _)
  rw [hpowK, hpowH]
  exact mul_mem (pow_mem ht _) (pow_mem hs _)

/-- The center of `G_m` is trivial (the action is faithful and fixed-point-free on the
generator). -/
lemma fermat_central_eq_one {z : GFermat m} (hz : z ∈ Subgroup.center (GFermat m)) :
    z = 1 := by
  rcases Nat.eq_zero_or_pos m with rfl | hm
  · exact Subsingleton.elim _ _
  rw [Subgroup.mem_center_iff] at hz
  -- (a) commuting with `t = inl (ofAdd 1)` forces the `H`-component to be trivial
  have hzr : z.right = 1 := by
    have hL := congrArg SemidirectProduct.left (hz (tFermat m))
    simp only [SemidirectProduct.mul_left, tFermat, SemidirectProduct.left_inl,
      SemidirectProduct.right_inl, map_one, MulAut.one_apply] at hL
    -- hL : ofAdd 1 * z.left = z.left * φ(z.right)(ofAdd 1)
    have hfix : phiFermat m z.right (Multiplicative.ofAdd 1) = Multiplicative.ofAdd 1 := by
      have h1 : z.left * phiFermat m z.right (Multiplicative.ofAdd 1)
          = z.left * Multiplicative.ofAdd 1 := by
        rw [← hL, mul_comm]
      exact mul_left_cancel h1
    have hcx : (((u2 m)⁻¹ ^ (Multiplicative.toAdd z.right).val : (ZMod (emN m))ˣ)
          : ZMod (emN m)) * (1 : ZMod (emN m)) = (1 : ZMod (emN m)) := by
      have := congrArg Multiplicative.toAdd hfix
      rwa [phiFermat_apply, toAdd_ofAdd, toAdd_ofAdd] at this
    rw [mul_one] at hcx
    have hunit : ((u2 m)⁻¹ ^ (Multiplicative.toAdd z.right).val : (ZMod (emN m))ˣ) = 1 :=
      Units.ext (by rw [hcx]; rfl)
    have hpow : (u2 m) ^ (Multiplicative.toAdd z.right).val = 1 := by
      rw [inv_pow, inv_eq_one] at hunit
      exact hunit
    have hval0 : (Multiplicative.toAdd z.right).val = 0 :=
      u2_pow_eq_one_iff m (ZMod.val_lt _) hpow
    have hz0 : Multiplicative.toAdd z.right = 0 := by
      have := congrArg (Nat.cast : ℕ → ZMod (2 ^ m)) hval0
      rwa [ZMod.natCast_val, ZMod.cast_id, Nat.cast_zero] at this
    rw [← ofAdd_toAdd z.right, hz0]
    rfl
  -- (b) commuting with `s = inr (ofAdd 1)` forces the `K`-component to be trivial
  have hzl : z.left = 1 := by
    have hL := congrArg SemidirectProduct.left (hz (sFermat m))
    simp only [SemidirectProduct.mul_left, sFermat, SemidirectProduct.left_inr,
      SemidirectProduct.right_inr, hzr, map_one, one_mul,
      mul_one] at hL
    -- hL : φ(ofAdd 1) z.left = z.left
    have hcx : (((u2 m)⁻¹ ^ ((1 : ZMod (2 ^ m))).val : (ZMod (emN m))ˣ) : ZMod (emN m))
        * Multiplicative.toAdd z.left = Multiplicative.toAdd z.left := by
      have := congrArg Multiplicative.toAdd hL
      rwa [phiFermat_apply, toAdd_ofAdd, toAdd_ofAdd] at this
    have hvalone : ((1 : ZMod (2 ^ m))).val = 1 :=
      ZMod.val_one_eq_one_mod (2 ^ m) ▸ Nat.mod_eq_of_lt (Nat.one_lt_two_pow_iff.mpr hm.ne')
    rw [hvalone, pow_one] at hcx
    -- multiply by `u2`: `x = 2x`, so `x = 0`
    have h2x : ((u2 m : (ZMod (emN m))ˣ) : ZMod (emN m)) * Multiplicative.toAdd z.left
        = Multiplicative.toAdd z.left := by
      calc ((u2 m : (ZMod (emN m))ˣ) : ZMod (emN m)) * Multiplicative.toAdd z.left
          = ((u2 m : (ZMod (emN m))ˣ) : ZMod (emN m))
            * ((((u2 m)⁻¹ : (ZMod (emN m))ˣ) : ZMod (emN m)) * Multiplicative.toAdd z.left) := by
            rw [hcx]
        _ = (((u2 m * (u2 m)⁻¹ : (ZMod (emN m))ˣ)) : ZMod (emN m))
            * Multiplicative.toAdd z.left := by
            rw [Units.val_mul, mul_assoc]
        _ = Multiplicative.toAdd z.left := by
            rw [mul_inv_cancel]
            simp
    have h2 : ((u2 m : (ZMod (emN m))ˣ) : ZMod (emN m)) = 2 := by
      rw [u2, ZMod.coe_unitOfCoprime]; push_cast; ring
    rw [h2, two_mul] at h2x
    have hx0 : Multiplicative.toAdd z.left = 0 := by
      have h3 : Multiplicative.toAdd z.left + Multiplicative.toAdd z.left
          = Multiplicative.toAdd z.left := h2x
      linear_combination h3
    rw [← ofAdd_toAdd z.left, hx0]
    rfl
  refine SemidirectProduct.ext ?_ ?_
  · rw [hzl]; rfl
  · rw [hzr]; rfl


/-- The tame relator dies in `G_m` (product form, for the presentation lift). -/
lemma fermat_relator : conjP (tFermat m) (sFermat m) * ((tFermat m) ^ 2)⁻¹ = 1 := by
  have h : conjP (tFermat m) (sFermat m) = tFermat m ^ 2 := fermat_relation m
  rw [h, mul_inv_cancel]

/-- The classifying map `F₂ ⟶ G_m` (`σ ↦ s, τ ↦ t`). -/
noncomputable def fermatBase : FreeProfiniteGroup (Fin 2) ⟶ ProfiniteGrp.of (GFermat m) :=
  (FreeProfiniteGroup.homEquiv (Fin 2) (ProfiniteGrp.of (GFermat m))).symm
    ![sFermat m, tFermat m]

@[simp] private lemma fermatBase_of_zero :
    (fermatBase m).hom.toMonoidHom (FreeProfiniteGroup.of 0) = sFermat m :=
  FreeProfiniteGroup.homEquiv_symm_of _ _ _

@[simp] private lemma fermatBase_of_one :
    (fermatBase m).hom.toMonoidHom (FreeProfiniteGroup.of 1) = tFermat m :=
  FreeProfiniteGroup.homEquiv_symm_of _ _ _

private lemma fermat_kill : ∀ r ∈ ({tameWord} : Set (FreeProfiniteGroup (Fin 2))),
    (fermatBase m).hom.toMonoidHom r = 1 := by
  intro r hr
  rcases Set.mem_singleton_iff.mp hr with rfl
  set f : FreeProfiniteGroup (Fin 2) →* GFermat m := (fermatBase m).hom.toMonoidHom with hf
  have e0 : f (FreeProfiniteGroup.of 0) = sFermat m := fermatBase_of_zero m
  have e1 : f (FreeProfiniteGroup.of 1) = tFermat m := fermatBase_of_one m
  show f tameWord = 1
  rw [tameWord]
  simp only [map_mul, map_inv, map_pow, Marking.map_conjP, e0, e1]
  exact fermat_relator m

/-- The marked map `T_tame → G_m` (`σ ↦ s, τ ↦ t`). -/
noncomputable def fermatHom : ContinuousMonoidHom Ttame (GFermat m) :=
  presentationLift {tameWord} (fermatBase m).hom (fermat_kill m)

@[simp] private lemma fermatHom_tameSigma : fermatHom m tameSigma = sFermat m :=
  (presentationLift_mk {tameWord} (fermatBase m).hom (fermat_kill m)
    (FreeProfiniteGroup.of 0)).trans (fermatBase_of_zero m)

@[simp] private lemma fermatHom_tameTau : fermatHom m tameTau = tFermat m :=
  (presentationLift_mk {tameWord} (fermatBase m).hom (fermat_kill m)
    (FreeProfiniteGroup.of 1)).trans (fermatBase_of_one m)

private lemma fermatHom_surjective : Function.Surjective (fermatHom m) := by
  have hle : Subgroup.closure {sFermat m, tFermat m} ≤ (fermatHom m).toMonoidHom.range := by
    rw [Subgroup.closure_le]
    rintro z (rfl | rfl)
    · exact ⟨tameSigma, fermatHom_tameSigma m⟩
    · exact ⟨tameTau, fermatHom_tameTau m⟩
  intro y
  exact hle (fermat_gen m ▸ Subgroup.mem_top y)

/-- Elements of a normal subgroup with 2-group finite images die in every Fermat level (the
image is a central 2-subgroup of a center-free group). -/
lemma fermatHom_eq_one_of_mem {M : Subgroup Ttame} [hMn : M.Normal]
    (h2 : ∀ (G : Type) [Group G] [TopologicalSpace G] [DiscreteTopology G] [Finite G]
      (f : Ttame →* G), Continuous f → IsPGroup 2 (M.map f))
    {x : Ttame} (hx : x ∈ M) : fermatHom m x = 1 := by
  haveI hNmap : (M.map (fermatHom m).toMonoidHom).Normal :=
    Subgroup.Normal.map hMn _ (fermatHom_surjective m)
  have hp2 : IsPGroup 2 (M.map (fermatHom m).toMonoidHom) :=
    h2 _ _ (fermatHom m).continuous_toFun
  have hcent := Tame.tame_normal_two_subgroup_central (fermat_gen m) (fermat_relation m)
    (M.map (fermatHom m).toMonoidHom) hp2
  exact fermat_central_eq_one m (hcent (Subgroup.mem_map.mpr ⟨x, hx, rfl⟩))

/-- Every element of `Multiplicative (ℤ/n)` is a power of `ofAdd 1`. -/
lemma multiplicative_zmod_pow (n : ℕ) [NeZero n] (x : Multiplicative (ZMod n)) :
    x = (Multiplicative.ofAdd (1 : ZMod n)) ^ (Multiplicative.toAdd x).val := by
  have h1 : ((Multiplicative.toAdd x).val • (1 : ZMod n)) = Multiplicative.toAdd x := by
    rw [nsmul_eq_mul, mul_one, ZMod.natCast_val, ZMod.cast_id]
  rw [← ofAdd_nsmul, h1, ofAdd_toAdd]

/-- The unramified coordinate at level `m`: `ν_m = rightHom ∘ (T_tame → G_m)`. -/
noncomputable def fermatNu : ContinuousMonoidHom Ttame (Multiplicative (ZMod (2 ^ m))) :=
  ⟨SemidirectProduct.rightHom.comp (fermatHom m).toMonoidHom, by
    have h : Continuous ((SemidirectProduct.rightHom :
        GFermat m →* Multiplicative (ZMod (2 ^ m))) ∘ (fermatHom m)) :=
      Continuous.comp continuous_of_discreteTopology (fermatHom m).continuous_toFun
    exact h⟩

private lemma fermatNu_kills_inertia : inertiaPart ≤ (fermatNu m).toMonoidHom.ker := by
  have hker_closed : IsClosed ((fermatNu m).toMonoidHom.ker : Set Ttame) := by
    rw [MonoidHom.coe_ker]
    exact IsClosed.preimage (fermatNu m).continuous_toFun isClosed_singleton
  refine Subgroup.topologicalClosure_minimal _ ?_ hker_closed
  refine Subgroup.normalClosure_le_normal ?_
  intro z hz
  rcases Set.mem_singleton_iff.mp hz with rfl
  refine MonoidHom.mem_ker.mpr ?_
  show SemidirectProduct.rightHom (fermatHom m tameTau) = 1
  rw [fermatHom_tameTau, tFermat, SemidirectProduct.rightHom_inl]

/-- The level maps `ψ_m : Q → C_{2^m}` descend from `ν_m`. -/
noncomputable def psiFermatQ : ContinuousMonoidHom Qur (Multiplicative (ZMod (2 ^ m))) :=
  quotientLift inertiaPart (fermatNu m) (fermatNu_kills_inertia m)

@[simp] private lemma psiFermatQ_qSigma : psiFermatQ m qSigma = Multiplicative.ofAdd 1 := by
  rw [show psiFermatQ m qSigma = fermatNu m tameSigma from quotientLift_quotientMk _ _ _ _]
  show SemidirectProduct.rightHom (fermatHom m tameSigma) = _
  rw [fermatHom_tameSigma, sFermat, SemidirectProduct.rightHom_inr]

private lemma psiFermatQ_surjective : Function.Surjective (psiFermatQ m) := by
  intro y
  refine ⟨qSigma ^ (Multiplicative.toAdd y).val, ?_⟩
  rw [map_pow, psiFermatQ_qSigma, ← multiplicative_zmod_pow]

end FermatLevels

/-! ## Cyclic-group torsion helper -/

/-- In a finite cyclic group, an element whose order divides `#K` lies in `K` (the subgroup
of order `#K` is exactly the `#K`-torsion, by the cyclic root-count bound). -/
lemma mem_of_orderOf_dvd_card {C : Type*} [Group C] [IsCyclic C] [Finite C]
    {K : Subgroup C} {x : C} (hdvd : orderOf x ∣ Nat.card K) : x ∈ K := by
  classical
  haveI := Fintype.ofFinite C
  set n := Nat.card K with hn
  have hnpos : 0 < n := Nat.card_pos
  have hx : x ^ n = 1 := orderOf_dvd_iff_pow_eq_one.mp hdvd
  have hle : ({b : C | b ^ n = 1} : Finset C).card ≤ n :=
    IsCyclic.card_pow_eq_one_le hnpos
  have hsub : (K : Set C).toFinset ⊆ ({b : C | b ^ n = 1} : Finset C) := by
    intro y hy
    rw [Set.mem_toFinset] at hy
    have hyn : y ^ n = 1 :=
      orderOf_dvd_iff_pow_eq_one.mp (Subgroup.orderOf_dvd_natCard K hy)
    simpa using hyn
  have hcard : n ≤ (K : Set C).toFinset.card := by
    rw [Set.toFinset_card, ← Nat.card_eq_fintype_card]
    exact le_of_eq hn
  have heq : (K : Set C).toFinset = ({b : C | b ^ n = 1} : Finset C) :=
    Finset.eq_of_subset_of_card_le hsub (le_trans hle hcard)
  have hxmem : x ∈ ({b : C | b ^ n = 1} : Finset C) := by simpa using hx
  rw [← heq, Set.mem_toFinset] at hxmem
  exact hxmem

/-- The tame relation through any homomorphism out of `T_tame`. -/
lemma tame_rel_map {H : Type*} [Group H] (f : Ttame →* H) :
    (f tameSigma)⁻¹ * f tameTau * f tameSigma = (f tameTau) ^ 2 := by
  have h := congrArg (⇑f) tame_relation
  rw [map_pow, Marking.map_conjP] at h
  simpa [conjP] using h

/-! ## Lemma 3.3, core form -/

/-- An element of a `2`-group subgroup has `2`-power order. -/
private lemma IsPGroup.exists_orderOf_eq_two_pow {H : Type*} [Group H] {K : Subgroup H}
    (hK : IsPGroup 2 K) {u : H} (hu : u ∈ K) : ∃ i : ℕ, orderOf u = 2 ^ i := by
  obtain ⟨k, hk⟩ := hK ⟨u, hu⟩
  have hk' : u ^ 2 ^ k = 1 := by
    have h1 := congrArg (fun w : K => (w : H)) hk
    simp only [SubmonoidClass.coe_pow, OneMemClass.coe_one] at h1
    exact h1
  obtain ⟨i, _, hi⟩ := (Nat.dvd_prime_pow Nat.prime_two).mp
    (orderOf_dvd_iff_pow_eq_one.mpr hk')
  exact ⟨i, hi⟩

/-- Arithmetic core of the cyclic level-comparison: if a natural `n` factors both as
`2 ^ a * cχ` and as `cU * cπ` with `a` the `2`-adic valuation of `cU`, then `cχ` and `cπ`
have the same `2`-adic valuation. -/
private lemma factorization_two_ker_eq {n cχ cπ cU a : ℕ}
    (hχ : n = 2 ^ a * cχ) (hπ : n = cU * cπ)
    (hcχ : cχ ≠ 0) (hcπ : cπ ≠ 0) (hcU : cU ≠ 0)
    (ha : a = cU.factorization 2) :
    cχ.factorization 2 = cπ.factorization 2 := by
  have e1 : a + cχ.factorization 2 = n.factorization 2 := by
    rw [hχ, Nat.factorization_mul (pow_ne_zero a two_ne_zero) hcχ, Finsupp.add_apply,
      Nat.Prime.factorization_pow Nat.prime_two, Finsupp.single_eq_same]
  have e2 : a + cπ.factorization 2 = n.factorization 2 := by
    rw [hπ, Nat.factorization_mul hcU hcπ, Finsupp.add_apply, ← ha]
  omega

/-- **Lemma 3.3, `Q`-coordinate step.** For a normal subgroup `M` of `T_tame` with 2-group
finite images, the image `qMk x` of any `x ∈ M` lies in every open normal subgroup `U ≤ Qur`:
comparing the Fermat character `χ` (onto `C_{2^a}`) with the projection `π` onto `Qur/U`
through the finer level `W`, the 2-power-order class of `x` in `Qur/W` sits in `ker χ`, and the
matching 2-adic valuations (`factorization_two_ker_eq`) force it into `ker π`, i.e. into `U`. -/
private lemma qMk_mem_of_two_images (M : Subgroup Ttame) [M.Normal]
    (h2 : ∀ (G : Type) [Group G] [TopologicalSpace G] [DiscreteTopology G] [Finite G]
      (f : Ttame →* G), Continuous f → IsPGroup 2 (M.map f))
    {x : Ttame} (hx : x ∈ M) (U : OpenNormalSubgroup Qur) : qMk x ∈ U := by
  haveI : Finite (Qur ⧸ U.toSubgroup) := inferInstance
  set y : Qur := qMk x with hy
  set a : ℕ := (Nat.card (Qur ⧸ U.toSubgroup)).factorization 2 with ha
  have hKopen : IsOpen (((psiFermatQ a).toMonoidHom.ker : Subgroup Qur) : Set Qur) := by
    rw [MonoidHom.coe_ker]
    exact (isOpen_discrete _).preimage (psiFermatQ a).continuous_toFun
  haveI hkerN : ((psiFermatQ a).toMonoidHom.ker).Normal := MonoidHom.normal_ker _
  haveI hWn : (U.toSubgroup ⊓ (psiFermatQ a).toMonoidHom.ker).Normal := by
    constructor
    intro n hn g
    exact ⟨U.isNormal'.conj_mem _ hn.1 g, hkerN.conj_mem _ hn.2 g⟩
  obtain ⟨W, hWdef⟩ : ∃ W : OpenNormalSubgroup Qur,
      W.toSubgroup = U.toSubgroup ⊓ (psiFermatQ a).toMonoidHom.ker :=
    ⟨⟨⟨U.toSubgroup ⊓ (psiFermatQ a).toMonoidHom.ker,
      U.toOpenSubgroup.isOpen'.inter hKopen⟩, hWn⟩, rfl⟩
  haveI : Finite (Qur ⧸ W.toSubgroup) := inferInstance
  set π : (Qur ⧸ W.toSubgroup) →* (Qur ⧸ U.toSubgroup) :=
    QuotientGroup.map W.toSubgroup U.toSubgroup (MonoidHom.id _) (by
      rw [Subgroup.comap_id, hWdef]
      exact inf_le_left) with hπ
  set χ : (Qur ⧸ W.toSubgroup) →* Multiplicative (ZMod (2 ^ a)) :=
    QuotientGroup.lift W.toSubgroup (psiFermatQ a).toMonoidHom
      (fun w hw => MonoidHom.mem_ker.mp (hWdef ▸ hw).2) with hχ
  haveI hWnormal : W.toSubgroup.Normal := W.isNormal'
  haveI hWtg : IsTopologicalGroup (Qur ⧸ W.toSubgroup) :=
    QuotientGroup.instIsTopologicalGroup W.toSubgroup
  haveI : IsCyclic (Qur ⧸ W.toSubgroup) := by
    have hgenC : Subgroup.closure {(QuotientGroup.mk' W.toSubgroup) qSigma} = ⊤ := by
      have h := topGen_map (f := QuotientGroup.mk' W.toSubgroup) QuotientGroup.continuous_mk
        (QuotientGroup.mk'_surjective _) topGen_qur
      rw [Set.image_singleton] at h
      exact gen_of_topGen_discrete h
    refine ⟨⟨(QuotientGroup.mk' W.toSubgroup) qSigma, fun z => ?_⟩⟩
    have hz : z ∈ Subgroup.closure {(QuotientGroup.mk' W.toSubgroup) qSigma} :=
      hgenC ▸ Subgroup.mem_top z
    rwa [← Subgroup.zpowers_eq_closure] at hz
  have hπsurj : Function.Surjective π := by
    intro c
    obtain ⟨z, rfl⟩ := QuotientGroup.mk'_surjective U.toSubgroup c
    exact ⟨(QuotientGroup.mk' W.toSubgroup) z, QuotientGroup.map_mk' _ _ _ _ _⟩
  have hχsurj : Function.Surjective χ := by
    intro c
    obtain ⟨q0, hq0⟩ := psiFermatQ_surjective a c
    exact ⟨(QuotientGroup.mk' W.toSubgroup) q0,
      (QuotientGroup.lift_mk' _ _ q0).trans hq0⟩
  have hposχ : Nat.card ((χ.ker : Subgroup (Qur ⧸ W.toSubgroup))) ≠ 0 := Nat.card_pos.ne'
  have hposπ : Nat.card ((π.ker : Subgroup (Qur ⧸ W.toSubgroup))) ≠ 0 := Nat.card_pos.ne'
  have hposU : Nat.card (Qur ⧸ U.toSubgroup) ≠ 0 := Nat.card_pos.ne'
  have hCχ : Nat.card (Qur ⧸ W.toSubgroup) = 2 ^ a * Nat.card χ.ker := by
    have h1 := Subgroup.card_eq_card_quotient_mul_card_subgroup (χ.ker)
    have hq2 : Nat.card ((Qur ⧸ W.toSubgroup) ⧸ χ.ker)
        = Nat.card (Multiplicative (ZMod (2 ^ a))) :=
      Nat.card_congr (QuotientGroup.quotientKerEquivOfSurjective χ hχsurj).toEquiv
    have h3 : Nat.card (Multiplicative (ZMod (2 ^ a))) = 2 ^ a := by
      rw [Nat.card_congr (Multiplicative.toAdd (α := ZMod (2 ^ a))), Nat.card_zmod]
    rw [h1, hq2, h3]
  have hCπ : Nat.card (Qur ⧸ W.toSubgroup)
      = Nat.card (Qur ⧸ U.toSubgroup) * Nat.card π.ker := by
    have h1 := Subgroup.card_eq_card_quotient_mul_card_subgroup (π.ker)
    have hq2 : Nat.card ((Qur ⧸ W.toSubgroup) ⧸ π.ker) = Nat.card (Qur ⧸ U.toSubgroup) :=
      Nat.card_congr (QuotientGroup.quotientKerEquivOfSurjective π hπsurj).toEquiv
    rw [h1, hq2]
  have hv2 : (Nat.card χ.ker).factorization 2 = (Nat.card π.ker).factorization 2 :=
    factorization_two_ker_eq hCχ hCπ hposχ hposπ hposU ha
  set u : Qur ⧸ W.toSubgroup := (QuotientGroup.mk' W.toSubgroup) y with hu
  have huK : u ∈ χ.ker := by
    rw [MonoidHom.mem_ker, hu]
    rw [show χ ((QuotientGroup.mk' W.toSubgroup) y) = psiFermatQ a y from
      QuotientGroup.lift_mk' _ _ y]
    rw [hy, show psiFermatQ a (qMk x) = fermatNu a x from
      quotientLift_quotientMk _ _ _ _]
    show SemidirectProduct.rightHom (fermatHom a x) = 1
    rw [fermatHom_eq_one_of_mem a h2 hx, map_one]
  have hu2 : ∃ i : ℕ, orderOf u = 2 ^ i := by
    have hcont : Continuous ((QuotientGroup.mk' W.toSubgroup).comp
        qMk.toMonoidHom) := by
      rw [MonoidHom.coe_comp]
      exact Continuous.comp QuotientGroup.continuous_mk qMk.continuous_toFun
    have hmem : u ∈ M.map ((QuotientGroup.mk' W.toSubgroup).comp
        qMk.toMonoidHom) :=
      Subgroup.mem_map.mpr ⟨x, hx, rfl⟩
    exact IsPGroup.exists_orderOf_eq_two_pow
      (h2 _ ((QuotientGroup.mk' W.toSubgroup).comp qMk.toMonoidHom) hcont) hmem
  obtain ⟨i, hi⟩ := hu2
  have hidvd : orderOf u ∣ Nat.card χ.ker := Subgroup.orderOf_dvd_natCard _ huK
  have hile : i ≤ (Nat.card χ.ker).factorization 2 := by
    rw [hi] at hidvd
    exact (Nat.Prime.pow_dvd_iff_le_factorization Nat.prime_two hposχ).mp hidvd
  have hidvd2 : orderOf u ∣ Nat.card π.ker := by
    rw [hi]
    exact (Nat.Prime.pow_dvd_iff_le_factorization Nat.prime_two hposπ).mpr (hv2 ▸ hile)
  have huπ : u ∈ π.ker := mem_of_orderOf_dvd_card hidvd2
  rw [MonoidHom.mem_ker, hu, show π ((QuotientGroup.mk' W.toSubgroup) y)
    = (QuotientGroup.mk' U.toSubgroup) y from QuotientGroup.map_mk' _ _ _ _ y] at huπ
  exact (QuotientGroup.eq_one_iff y).mp huπ

/-- **Lemma 3.3, inertia step.** An `x ∈ M` (2-group finite images) that already lies in
`inertiaPart` is trivial: through every finite level `V`, its image lies in the tame
`τ`-line `⟨τ̄⟩`, whose order is odd (Lemma 3.1), while `x`'s image has 2-power order — so it
is trivial in every `V`, hence `x = 1`. -/
private lemma eq_one_of_mem_inertiaPart (M : Subgroup Ttame)
    (h2 : ∀ (G : Type) [Group G] [TopologicalSpace G] [DiscreteTopology G] [Finite G]
      (f : Ttame →* G), Continuous f → IsPGroup 2 (M.map f))
    {x : Ttame} (hx : x ∈ M) (hxI : x ∈ inertiaPart) : x = 1 := by
  refine eq_one_of_forall_mem_openNormalSubgroup fun V => ?_
  haveI : Finite (Ttame ⧸ V.toSubgroup) := inferInstance
  set mkV : Ttame →* Ttame ⧸ V.toSubgroup := QuotientGroup.mk' V.toSubgroup with hmkV
  have hp2 := h2 _ mkV QuotientGroup.continuous_mk
  have hmem : mkV x ∈ M.map mkV := Subgroup.mem_map.mpr ⟨x, hx, rfl⟩
  obtain ⟨k, hk⟩ := hp2 ⟨mkV x, hmem⟩
  have hk' : (mkV x) ^ 2 ^ k = 1 := by
    rw [Subtype.ext_iff] at hk
    simpa using hk
  have hgen := gen_ttame_quotient mkV QuotientGroup.continuous_mk (QuotientGroup.mk'_surjective _)
  have hrel : (mkV tameSigma)⁻¹ * mkV tameTau * mkV tameSigma = (mkV tameTau) ^ 2 :=
    tame_rel_map mkV
  haveI hzpn : (Subgroup.zpowers (mkV tameTau)).Normal :=
    Tame.zpowers_normal_of_tame hgen hrel
  have hxzp : mkV x ∈ Subgroup.zpowers (mkV tameTau) := by
    have h1 : mkV x ∈ closure ((⇑mkV) '' (Subgroup.normalClosure {tameTau} : Set Ttame)) :=
      map_mem_closure QuotientGroup.continuous_mk hxI (Set.mapsTo_image _ _)
    rw [(isClosed_discrete _).closure_eq] at h1
    obtain ⟨w, hwNC, hwx⟩ := h1
    have hle : Subgroup.normalClosure {tameTau}
        ≤ (Subgroup.normalClosure {mkV tameTau}).comap mkV := by
      haveI : ((Subgroup.normalClosure {mkV tameTau}).comap mkV).Normal :=
        Subgroup.Normal.comap Subgroup.normalClosure_normal mkV
      refine Subgroup.normalClosure_le_normal ?_
      intro z hz
      rcases Set.mem_singleton_iff.mp hz with rfl
      exact Subgroup.mem_comap.mpr (Subgroup.subset_normalClosure (Set.mem_singleton _))
    have h3 : mkV w ∈ Subgroup.normalClosure {mkV tameTau} :=
      Subgroup.mem_comap.mp (hle hwNC)
    have h4 : Subgroup.normalClosure {mkV tameTau} ≤ Subgroup.zpowers (mkV tameTau) := by
      refine Subgroup.normalClosure_le_normal ?_
      intro z hz
      rcases Set.mem_singleton_iff.mp hz with rfl
      exact Subgroup.mem_zpowers _
    exact hwx ▸ h4 h3
  have hodd : Odd (orderOf (mkV tameTau)) :=
    Tame.tame_odd_order (orderOf_pos (mkV tameSigma)).ne' hrel
  have hdvd_odd : orderOf (mkV x) ∣ orderOf (mkV tameTau) := by
    have h := Subgroup.orderOf_dvd_natCard _ hxzp
    rwa [Nat.card_zpowers] at h
  have hdvd_two : orderOf (mkV x) ∣ 2 ^ k := orderOf_dvd_iff_pow_eq_one.mpr hk'
  have hcop : Nat.Coprime (2 ^ k) (orderOf (mkV tameTau)) := by
    refine Nat.Coprime.pow_left k ?_
    rw [Nat.Prime.coprime_iff_not_dvd Nat.prime_two]
    intro hdvd
    have := Nat.odd_iff.mp hodd
    omega
  have hone : orderOf (mkV x) = 1 := Nat.eq_one_of_dvd_coprimes hcop hdvd_two hdvd_odd
  have hxone : mkV x = 1 := orderOf_eq_one_iff.mp hone
  exact (QuotientGroup.eq_one_iff x).mp hxone

/-- **Lemma 3.3 (core)**: a normal subgroup of `T_tame` all of whose finite continuous images
are 2-groups is trivial.  Paper argument: through each Fermat level `G_m` the image is a
central 2-subgroup of a center-free group, hence trivial, so the `Q`-coordinate dies in every
`C_{2^m}`; the cyclic level-comparison then kills the `Q`-image entirely, and the remaining
inertia part has both odd and 2-power order levelwise. -/
theorem eq_bot_of_normal_two_images (M : Subgroup Ttame) [hMn : M.Normal]
    (h2 : ∀ (G : Type) [Group G] [TopologicalSpace G] [DiscreteTopology G] [Finite G]
      (f : Ttame →* G), Continuous f → IsPGroup 2 (M.map f)) :
    M = ⊥ := by
  rw [eq_bot_iff]
  intro x hx
  rw [Subgroup.mem_bot]
  -- Step 1: the `Q`-image of `x` is trivial, i.e. `x ∈ inertiaPart`
  have hxI : x ∈ inertiaPart := by
    have hy1 : qMk x = 1 :=
      eq_one_of_forall_mem_openNormalSubgroup (qMk_mem_of_two_images M h2 hx)
    haveI hIc : IsClosed (inertiaPart : Set Ttame) := Subgroup.isClosed_topologicalClosure _
    exact (quotientMk_eq_one_iff (N := inertiaPart)).mp hy1
  -- Step 2: `x ∈ inertiaPart` with 2-power finite orders is trivial (odd ∧ 2-power)
  exact eq_one_of_mem_inertiaPart M h2 hx hxI

/-! ## Proposition 3.2, local side -/

/-- **Lemma 3.3's maximality, for any B10 datum** (extracted from `prop_3_2_local`'s proof
so the marked pro-2 isomorphisms oriented witness can reuse it): every closed normal pro-2 subgroup lies in `T.W`
(`eq_bot_of_normal_two_images` applied to the image of the competitor `N` in `T_tame`). -/
theorem tameData_maximal [CompactSpace AbsGalQ2] [TotallyDisconnectedSpace AbsGalQ2]
    (T' : TameQuotientData) :
    ∀ N : Subgroup AbsGalQ2, N.Normal → IsClosed (N : Set AbsGalQ2) →
      IsProP 2 N → N ≤ T'.W := by
  intro N hNn hNc hNp
  set T := T' with hT
  haveI := T.normal
  set q : AbsGalQ2 →* AbsGalQ2 ⧸ T.W := QuotientGroup.mk' T.W with hq
  set e : (AbsGalQ2 ⧸ T.W) →* Ttame := T.equiv.toMonoidHom with he
  set M : Subgroup Ttame := N.map (e.comp q) with hM
  have hesurj : Function.Surjective (e.comp q) := by
    rw [MonoidHom.coe_comp]
    exact T.equiv.surjective.comp (QuotientGroup.mk'_surjective _)
  haveI hMn : M.Normal := Subgroup.Normal.map hNn _ hesurj
  have hMbot : M = ⊥ := by
    refine eq_bot_of_normal_two_images M ?_
    intro G _ _ _ _ f hf
    rw [hM, Subgroup.map_map]
    refine isPGroup_map_of_isProP hNp _ ?_
    rw [MonoidHom.coe_comp, MonoidHom.coe_comp]
    exact (hf.comp T.equiv.continuous_toFun).comp continuous_quot_mk
  intro x hxN
  have h1 : e (q x) ∈ M := Subgroup.mem_map.mpr ⟨x, hxN, rfl⟩
  rw [hMbot, Subgroup.mem_bot] at h1
  have h2q : q x = 1 :=
    T.equiv.injective (by rw [map_one]; exact h1)
  exact (QuotientGroup.eq_one_iff x).mp h2q

/-- **Prop. 3.2, local side** (`Ax = B10`): the tame quotient of
`G_{ℚ₂}` is `T_tame`, by the *maximal* closed normal pro-2 subgroup.  Existence is axiom B10
(oriented form B10′ since the marked pro-2 isomorphisms; only the underlying `TameQuotientData` is used here);
maximality is Lemma 3.3 (`tameData_maximal`). -/
theorem prop_3_2_local [CompactSpace AbsGalQ2] [TotallyDisconnectedSpace AbsGalQ2] :
    Nonempty LocalTameQuotient :=
  ⟨{ toTameQuotientData := GQ2.tameQuotient.toTameQuotientData,
     maximal := tameData_maximal GQ2.tameQuotient.toTameQuotientData }⟩

end SectionThree

end GQ2

/-! ### Paper-tag ledger (auto-generated by paperforge; do not edit)

  * eq. (1) = ⟦eq-defwords⟧
  * eq. (21) = ⟦eq-nu2⟧
  * eq. (3) = ⟦eq-defwords3⟧
  * Lemma 3.1 = ⟦lem-tamefinite⟧
  * Lemma 3.3 = ⟦lem-o2tame⟧
  * Prop 3.10 = ⟦prop-pro2⟧
  * Prop 3.14 = ⟦prop-compatiblemarking⟧
  * Prop 3.2 = ⟦prop-tamequotient⟧
-/
