import GQ2.QuadraticFp2

/-!
# §8 radical-edge def-layer  (P-16a relocation; extracted from `GQ2/SectionEight.lean`)

The Lemma 8.6 **definition layer** — `CentralCover`, `polarMul`, `RadicalCoverData`,
`NoDescent`, `MLifts`, `MLifts.Central` — and the generic half-count engine
`two_mul_card_fiber`, lifted out of `GQ2/SectionEight.lean` into this lower shared file.

**Why.**  The P-16 own-files (`GQ2/CentralObstruction.lean`, …) need these defs to state and
prove their lemmas, but must not import `SectionEight` — otherwise splicing a proved lemma
back into `SectionEight` (`lemma_8_6_local := CentralObstruction…`) is a **circular import**
(the P-13g `prop_5_16` trap).  Same pattern as `GQ2/OrbitData.lean` for §6
(`docs/orbit-data-refactor.md`); see `docs/p16-ticket-split.md` (P-16a).

Moved verbatim from `SectionEight` (namespace preserved: `GQ2.SectionEight`).  No axioms;
`Ax = ∅`.
-/

namespace GQ2

namespace SectionEight

/-! ## Central double covers  (§8) -/

/-- **A central double cover** of the finite group `Y` (§8): a surjection whose kernel is
generated by a central element `z ≠ 1` of square one. -/
structure CentralCover (Y : Type) [Group Y] [Finite Y] where
  /-- The covering group. -/
  cover : Type
  [group : Group cover]
  [finite : Finite cover]
  [topo : TopologicalSpace cover]
  [disc : DiscreteTopology cover]
  /-- The covering surjection. -/
  p : cover →* Y
  surj : Function.Surjective p
  /-- The central kernel generator. -/
  z : cover
  z_ne : z ≠ 1
  z_sq : z * z = 1
  central : ∀ x : cover, z * x = x * z
  ker_eq : p.ker = Subgroup.zpowers z

attribute [instance] CentralCover.group CentralCover.finite CentralCover.topo
  CentralCover.disc

namespace CentralCover

variable {Y : Type} [Group Y] [Finite Y] (C : CentralCover Y)

/-- Squares die in the kernel subgroup `⟨z⟩` (its elements have order ≤ 2). -/
lemma sq_eq_one_of_mem_ker {x : C.cover} (hx : x ∈ C.p.ker) : x * x = 1 := by
  rw [C.ker_eq] at hx
  obtain ⟨n, rfl⟩ := hx
  rw [← Commute.mul_zpow (Commute.refl C.z), C.z_sq, one_zpow]

end CentralCover

/-! ## The Lemma 8.6 datum  (radical cover) -/

/-- The multiplicative polar form of a `𝔽₂`-valued square function on (a subgroup of) a
group: `B_q(m, m') = q(mm') + q(m) + q(m')`. -/
def polarMul {M : Type*} (q : M → ZMod 2) (mul : M → M → M) (m m' : M) : ZMod 2 :=
  q (mul m m') + q m + q m'

/-- **The Lemma 8.6 datum**: a central double cover of `Bg` restricting to a quadratic form
on the elementary abelian normal subgroup `M`, with polar radical containing `T ≤ M` and
vanishing on `T` (paper §8, setting of Lemma 8.6; `M = K/R`, `T = T₀` after §7). -/
structure RadicalCoverData (Bg : Type) [Group Bg] [Finite Bg] where
  /-- The central double cover `p : B̃ ↠ B`. -/
  C : CentralCover Bg
  /-- The elementary abelian layer `M` (paper: `M = K/R`). -/
  M : Subgroup Bg
  hM : M.Normal
  /-- The polar radical `T` (paper: `T = T₀`). -/
  T : Subgroup Bg
  hT : T.Normal
  hTM : T ≤ M
  helem : ∀ m ∈ M, m * m = 1
  hcomm : ∀ m ∈ M, ∀ m' ∈ M, m * m' = m' * m
  /-- The square form of the cover on `M`: `x̃² = z^{q(x)}` for any lift `x̃` of `x ∈ M`. -/
  q : ↥M → ZMod 2
  hq : ∀ (x : C.cover) (hx : C.p x ∈ M), x * x = C.z ^ (q ⟨C.p x, hx⟩).val
  /-- `T` lies in the polar radical of `q`. -/
  hrad : ∀ (t : Bg) (ht : t ∈ T) (m : Bg) (hm : m ∈ M),
    polarMul q (fun a b => ⟨a.1 * b.1, mul_mem a.2 b.2⟩) ⟨t, hTM ht⟩ ⟨m, hm⟩ = 0
  /-- `q` vanishes on `T`. -/
  hTzero : ∀ (t : Bg) (ht : t ∈ T), q ⟨t, hTM ht⟩ = 0

/-- The `M`-layer of a `RadicalCoverData` is normal (instance form, so that the quotient
`Bg ⧸ D.M` carries its group structure in statement positions — the `TameQuotientData`
Lean-detail pattern). -/
instance RadicalCoverData.instNormalM {Bg : Type} [Group Bg] [Finite Bg]
    (D : RadicalCoverData Bg) : D.M.Normal := D.hM

/-- **"The radical edge is nonzero", operationally** (Lemma 8.6, descent clause): the cover
admits **no** descent to `B/T`, i.e. no normal complement to `p⁻¹(T)` missing `z`. -/
def RadicalCoverData.NoDescent {Bg : Type} [Group Bg] [Finite Bg]
    (D : RadicalCoverData Bg) : Prop :=
  ¬∃ N : Subgroup D.C.cover, N.Normal ∧ N.map D.C.p = D.T ∧ D.C.z ∉ N

/-- **Half-count engine** (the combinatorial heart of Lemma 8.6's (127) count): a nonzero
`𝔽₂`-linear functional `ℓ` on a finite `𝔽₂`-vector space `V` has each fibre of exactly half
the size — `2·#{v ∣ ℓ v = c} = #V`.  (`ℓ` is surjective, so `V` partitions into two equal
fibres over `ZMod 2`.)  Consumed by both `lemma_8_6_*` and `prop_8_9`'s `(139)` half-value. -/
theorem two_mul_card_fiber {V : Type*} [AddCommGroup V] [Module (ZMod 2) V] [Finite V]
    (ℓ : V →ₗ[ZMod 2] ZMod 2) (hℓ : ℓ ≠ 0) (c : ZMod 2) :
    2 * Nat.card {v : V // ℓ v = c} = Nat.card V := by
  classical
  haveI : Fintype V := Fintype.ofFinite V
  have h01 : ∀ x : ZMod 2, x ≠ 1 → x = 0 := by decide
  have hsurj : Function.Surjective ℓ := by
    obtain ⟨v, hv⟩ : ∃ v, ℓ v = 1 := by
      by_contra h
      exact hℓ (by ext v; exact h01 _ (fun hv1 => h ⟨v, hv1⟩))
    intro c; exact ⟨c • v, by rw [map_smul, hv, smul_eq_mul, mul_one]⟩
  have hfibeq : ∀ c' : ZMod 2, Nat.card {v : V // ℓ v = c'} = Nat.card {v : V // ℓ v = c} := by
    intro c'
    obtain ⟨v0, hv0⟩ := hsurj (c' - c)
    refine Nat.card_congr ⟨fun w => ⟨w.1 - v0, by rw [map_sub, w.2, hv0]; ring⟩,
      fun w => ⟨v0 + w.1, by rw [map_add, hv0, w.2]; ring⟩,
      fun w => Subtype.ext (by simp), fun w => Subtype.ext (by simp)⟩
  have hsig : Nat.card V = ∑ c' : ZMod 2, Nat.card {v : V // ℓ v = c'} :=
    (Nat.card_congr (Equiv.sigmaFiberEquiv ℓ).symm).trans Nat.card_sigma
  rw [hsig, Finset.sum_congr rfl (fun c' _ => hfibeq c'), Finset.sum_const, Finset.card_univ,
    Nat.card_eq_fintype_card, ZMod.card, smul_eq_mul]

/-! ## Unrestricted `M`-lifts and the central relation  (Lemma 8.6 count objects) -/

section HalfTorsor

variable {Bg : Type} [Group Bg] [TopologicalSpace Bg] [DiscreteTopology Bg] [Finite Bg]

/-- The unrestricted `M`-lifts of a lower map `ρ : Γ → B/M`: continuous homomorphisms
`f : Γ → B` over `ρ`. -/
def MLifts (D : RadicalCoverData Bg) {Γ' : Type} [Group Γ'] [TopologicalSpace Γ']
    (ρ : ContinuousMonoidHom Γ' (Bg ⧸ D.M)) : Type :=
  {f : ContinuousMonoidHom Γ' Bg // ∀ γ : Γ', QuotientGroup.mk (f γ) = ρ γ}

/-- An `M`-lift **satisfies the central relation** when it lifts through the cover. -/
def MLifts.Central (D : RadicalCoverData Bg) {Γ' : Type} [Group Γ'] [TopologicalSpace Γ']
    {ρ : ContinuousMonoidHom Γ' (Bg ⧸ D.M)}
    (f : MLifts D ρ) : Prop :=
  ∃ g : ContinuousMonoidHom Γ' D.C.cover, ∀ γ : Γ', D.C.p (g γ) = f.1 γ

end HalfTorsor

end SectionEight

end GQ2
