import GQ2.RadicalEdge.Bridge
import GQ2.FiniteGroupLemmas
import GQ2.Block.FrameImpl
import GQ2.SectionThreeMarked
import GQ2.KappaNormalForm
import GQ2.MStageCount
import GQ2.MStageCountGammaA

/-!
# §9: the strong induction proving Theorem 4.2  (ticket P-17; F-skeleton = P-17a)

Theorem 4.2 — equality of the boundary-framed exact-image counts of the two sources for
**every** marked target — by strong induction on the marked 2-kernel size `|L_Y|`
(paper pp. 44–47).  This file froze the interfaces of the induction's ingredients
(the P-11/P-12/P-14 statement-layer pattern); the sub-tickets P-17b–P-17i proved them
all.  Design note and work order: `docs/section9-extraction.md`.

The two regimes:

* **Terminal** (`IsScalarStack T.LY`, i.e. every chief factor of `L_Y` is a trivial
  `H`-module): Lemma 9.2's Schur–Zassenhaus splitting `Y ≅ H ×_{H₂} Q`
  (`GQ2.FiniteGroup.oddOrder_twoQuotient_split` + `coprime_fiber_product`, proved) reduces
  both exact-image problems to the **common marked maximal pro-2 quotient** `Π` via (144) —
  the P-25 marked isomorphisms (`prop_3_10_gammaA`, `prop_3_10_local_marked`).
  → `terminal_count_eq` (P-17b).
* **Inductive** (a nonscalar chief factor exists): choose the §7 block
  (`SectionSeven.exists_minimalBlock`), build the concrete recursion frame and enrichment
  on it (`blockFrame`/`blockEnrichment`, P-17c/d — decorations descend by the proved
  `lemma_7_3`, whence the standing `hE2` hypothesis), obtain the closed system from
  `prop_8_9`, and solve it against the induction hypothesis
  (`count_eq_of_closedRecursion`, P-17h) with Lemma 9.4's strict-decrease bounds (P-17g).
  The `R = ⊥` degenerate lane instead uses the elementary `M`-stage partition
  (`mStage_partition`, P-17f) directly.

**Reviewed statement amendment (P-17a, documented)**: `thm_4_2` (relocated here from
`GQ2/BoundaryFrame.lean` — import direction; pointer left) gains the hypothesis
`(hE2 : ∀ e : E, e ^ 2 = 1)`.  The §9 induction is **false-in-method** without it: the
θ-decoration descends through the block only because `E` is elementary abelian 2
(`lemma_7_3`, whose paper statement carries exactly this hypothesis), and the terminal
case kills the odd complement through `θ` for the same reason.  §10 consumes Theorem 4.2
at `E = 0` only (paper p. 48), so the amendment is harmless downstream.  Ledger:
`docs/section9-extraction.md` §Deviations.
-/

namespace GQ2

open SectionEight QuadraticFp2

variable {H E : Type} [Group H] [TopologicalSpace H] [DiscreteTopology H] [Finite H]
  [CommGroup E] [TopologicalSpace E] [DiscreteTopology E] [Finite E]

namespace SectionNine

/-! ## Terminal-case group-theory foundation  (P-17b infra; proved)

The coprime-centralization mechanism behind Lemma 9.2's odd normal lift `Ñ ◁ Y`: an
odd-order subgroup acting on the scalar stack `L_Y` (a `Y`-central 2-group) centralizes it.
This is `GQ2.comm_bot_of_scalarChain` (P-15g) unpacked at the `IsScalarStack` datum. -/


/-- **Coprime centralization** (Lemma 9.2 mechanism, §9.1): an odd-order subgroup `N` acting
on a scalar stack `L` (a `Y`-central 2-group, `SectionSeven.IsScalarStack`) centralizes it —
`⁅N, L⁆ = ⊥`.  This is how the odd normal lift `Ñ` of Lemma 9.2 centralizes `L_Y` (its
uniqueness/normality then follow).  Proved from `comm_bot_of_scalarChain`; reusable by the
Lemma 9.2 structural sub-ticket P-17b1. -/
theorem scalarStack_centralized_of_coprime {Y : Type} [Group Y] [Finite Y]
    {L : Subgroup Y} (hstack : SectionSeven.IsScalarStack L) {N : Subgroup Y}
    (hcop : Nat.Coprime (Nat.card N) (Nat.card L)) : ⁅N, L⁆ = ⊥ := by
  obtain ⟨n, c, hc0, hcn, hmono, _, hcomm⟩ := hstack
  have h := comm_bot_of_scalarChain n N c hc0 hmono hcomm (by rw [hcn]; exact hcop)
  rwa [hcn] at h

/-! ## Tame 2-nilpotency  (P-17b2; Lemma 3.1 structural content)

The gating foundation for Lemma 9.2: a finite quotient `H` of the tame group `Ttame`
(generated by `s, t` with `s⁻¹ t s = t²`) is 2-nilpotent — `O²(H)` has odd order.  `⟨t⟩` is
odd (`Tame.tame_odd_order`) and normal (`Tame.zpowers_normal_of_tame`), the quotient `H ⧸ ⟨t⟩`
is cyclic, and a finite group with an odd normal subgroup and cyclic quotient is 2-nilpotent
(the odd complement is the preimage of the odd part of the cyclic quotient).  This lets P-17b1
build the odd normal lift `Ñ ◁ Y` via Schur–Zassenhaus (`oddOrder_twoQuotient_split`). -/

/-- A finite **cyclic** group `Q` has a normal subgroup `Q₀` of odd order (`= ⟨g^{2ᵃ}⟩`, the odd
part) such that the `2ᵃ`-power of every element lands in `Q₀` (i.e. `Q ⧸ Q₀` is a 2-group,
expressed membership-wise to avoid forming the quotient here). -/
theorem exists_normal_odd_pow_mem_of_cyclic {Q : Type*} [Group Q] [Finite Q]
    (hcyc : IsCyclic Q) :
    ∃ Q0 : Subgroup Q, Q0.Normal ∧ Odd (Nat.card Q0) ∧ ∀ x : Q, ∃ k : ℕ, x ^ 2 ^ k ∈ Q0 := by
  obtain ⟨g, hg⟩ := hcyc.exists_generator
  have hcomm : ∀ x y : Q, x * y = y * x := by
    intro x y
    obtain ⟨i, rfl⟩ := Subgroup.mem_zpowers_iff.mp (hg x)
    obtain ⟨j, rfl⟩ := Subgroup.mem_zpowers_iff.mp (hg y)
    exact (Commute.zpow_zpow (Commute.refl g) i j).eq
  have hgtop : Subgroup.zpowers g = ⊤ := by rw [eq_top_iff]; intro x _; exact hg x
  set n := Nat.card Q with hn
  have hnpos : 0 < n := Nat.card_pos
  have hord : orderOf g = n := by
    rw [← Nat.card_zpowers g, hgtop]; exact Nat.card_congr (Subgroup.topEquiv.toEquiv)
  set P2 := 2 ^ (n.factorization 2) with hP2
  have hP2pos : 0 < P2 := pow_pos (by norm_num) _
  have hsplit : P2 * (n / P2) = n := Nat.ordProj_mul_ordCompl_eq_self n 2
  have hdvd : P2 ∣ n := ⟨n / P2, hsplit.symm⟩
  have hbodd : ¬ 2 ∣ (n / P2) := Nat.not_dvd_ordCompl Nat.prime_two hnpos.ne'
  refine ⟨Subgroup.zpowers (g ^ P2), ?_, ?_, ?_⟩
  · refine ⟨fun w hw q => ?_⟩
    have hqw : q * w * q⁻¹ = w := by rw [hcomm q w]; group
    rw [hqw]; exact hw
  · rw [Nat.card_zpowers, orderOf_pow' g hP2pos.ne', hord, Nat.gcd_comm, Nat.gcd_eq_left hdvd]
    exact Nat.odd_iff.mpr (Nat.two_dvd_ne_zero.mp hbodd)
  · intro x
    refine ⟨n.factorization 2, ?_⟩
    obtain ⟨i, rfl⟩ := Subgroup.mem_zpowers_iff.mp (hg x)
    refine Subgroup.mem_zpowers_iff.mpr ⟨i, ?_⟩
    rw [← hP2, ← zpow_natCast (g ^ i) P2, ← zpow_natCast g P2, ← zpow_mul, ← zpow_mul, mul_comm]

/-- **2-nilpotency from a cyclic quotient.** A finite group `H` with a normal subgroup `C` of
odd order and *cyclic* quotient `H ⧸ C` has a normal subgroup `N` of odd order with 2-group
quotient (necessarily `N = O²(H)`): the preimage of the odd part of the cyclic `H ⧸ C`. -/
theorem exists_normal_odd_twoQuotient_of_cyclic_quotient {H : Type*} [Group H] [Finite H]
    (C : Subgroup H) [C.Normal] (hC : Odd (Nat.card C)) (hcyc : IsCyclic (H ⧸ C)) :
    ∃ N : Subgroup H, ∃ _ : N.Normal, Odd (Nat.card N) ∧ IsPGroup 2 (H ⧸ N) := by
  obtain ⟨Q0, hQ0norm, hQ0odd, hQ0pow⟩ := exists_normal_odd_pow_mem_of_cyclic hcyc
  set f : H →* H ⧸ C := QuotientGroup.mk' C with hf
  have hfsurj : Function.Surjective f := QuotientGroup.mk'_surjective C
  refine ⟨Q0.comap f, hQ0norm.comap f, ?_, ?_⟩
  · -- `Nat.card (comap f Q0) = card C * card Q0`, both odd, via index bookkeeping.
    have hidx : (Q0.comap f).index = Q0.index := Subgroup.index_comap_of_surjective Q0 hfsurj
    have hcardC : Nat.card C * C.index = Nat.card H := Subgroup.card_mul_index C
    have hCQ : C.index = Nat.card (H ⧸ C) := rfl
    have hcardN : Nat.card (Q0.comap f) * (Q0.comap f).index = Nat.card H :=
      Subgroup.card_mul_index _
    have hcardQ0 : Nat.card Q0 * Q0.index = Nat.card (H ⧸ C) := Subgroup.card_mul_index Q0
    have hNidx_pos : 0 < (Q0.comap f).index := Nat.pos_of_ne_zero Subgroup.index_ne_zero_of_finite
    have key : Nat.card (Q0.comap f) = Nat.card C * Nat.card Q0 := by
      apply Nat.eq_of_mul_eq_mul_right hNidx_pos
      rw [hcardN, hidx, mul_assoc, hcardQ0, ← hCQ, hcardC]
    rw [key]; exact hC.mul hQ0odd
  · -- `H ⧸ N` is a 2-group: every element's `2ᵏ`-power lifts into `Q0`.
    intro x
    obtain ⟨y, rfl⟩ := QuotientGroup.mk'_surjective (Q0.comap f) x
    obtain ⟨k, hk⟩ := hQ0pow (f y)
    refine ⟨k, ?_⟩
    rw [← map_pow, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff, Subgroup.mem_comap, map_pow]
    exact hk

/-- **Tame 2-nilpotency (Lemma 3.1 structural content).** A finite group generated by `s, t`
with the tame relation `s⁻¹ t s = t²` is 2-nilpotent: it has a normal subgroup `N` of odd order
with 2-group quotient (`N = O²(H)`).  `C = ⟨t⟩` is odd (`Tame.tame_odd_order`) and normal
(`Tame.zpowers_normal_of_tame`), and `H ⧸ C` is cyclic (generated by the image of `s`, since
`t ↦ 1`); apply `exists_normal_odd_twoQuotient_of_cyclic_quotient`.  This is the foundation
Lemma 9.2 rests on — the odd normal lift `Ñ` of P-17b1 lives over `O²(H)`. -/
theorem tame_two_nilpotent {H : Type*} [Group H] [Finite H] {s t : H}
    (hgen : Subgroup.closure {s, t} = ⊤) (h : s⁻¹ * t * s = t ^ 2) :
    ∃ N : Subgroup H, ∃ _ : N.Normal, Odd (Nat.card N) ∧ IsPGroup 2 (H ⧸ N) := by
  haveI hCnorm : (Subgroup.zpowers t).Normal := GQ2.Tame.zpowers_normal_of_tame hgen h
  have hCodd : Odd (Nat.card (Subgroup.zpowers t)) := by
    rw [Nat.card_zpowers]; exact GQ2.Tame.tame_odd_order (orderOf_pos s).ne' h
  have hcyc : IsCyclic (H ⧸ Subgroup.zpowers t) := by
    set φ := QuotientGroup.mk' (Subgroup.zpowers t) with hφ
    have hsup : Subgroup.zpowers t ⊔ Subgroup.zpowers s = ⊤ := by
      rw [eq_top_iff, ← hgen, Subgroup.closure_le]
      intro x hx
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
      rcases hx with rfl | rfl
      · exact SetLike.mem_coe.2 (Subgroup.mem_sup_right (Subgroup.mem_zpowers _))
      · exact SetLike.mem_coe.2 (Subgroup.mem_sup_left (Subgroup.mem_zpowers _))
    have htmk : φ t = 1 := by
      rw [hφ, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]; exact Subgroup.mem_zpowers t
    have htop : Subgroup.zpowers (φ s) = ⊤ := by
      have hm := congrArg (Subgroup.map φ) hsup
      rwa [Subgroup.map_sup, MonoidHom.map_zpowers, MonoidHom.map_zpowers, htmk,
        Subgroup.zpowers_one_eq_bot, bot_sup_eq,
        Subgroup.map_top_of_surjective _ (QuotientGroup.mk'_surjective _)] at hm
    exact ⟨⟨φ s, fun x => htop.ge (Subgroup.mem_top x)⟩⟩
  exact exists_normal_odd_twoQuotient_of_cyclic_quotient (Subgroup.zpowers t) hCodd hcyc

/-! ## Lemma 9.2 — the odd normal complement `Ñ ◁ Y`  (P-17b1)

For a terminal target `1 → L_Y → Y → H → 1` (`L_Y` a scalar-stack 2-group, `H` tame hence
2-nilpotent by `tame_two_nilpotent`), Schur–Zassenhaus inside `P = π_Y⁻¹(O²H)` produces an odd
complement `Ñ` to `L_Y`, which the scalar-stack centralization
(`scalarStack_centralized_of_coprime`)
forces to be *normal in `Y`* (`Ñ` = the odd-order elements of `P`).  The output bundle — `Ñ ◁ Y`
odd, `Y/Ñ` a 2-group, `Ñ ∩ L_Y = ⊥`, `π_Y(Ñ) = O²H`, `Ñ·L_Y = π_Y⁻¹(O²H)` — is exactly the data
P-17b3 feeds to `coprime_fiber_product` (Lemma 9.1) for `Y ≅ H ×_{H₂} (Y/Ñ)`. -/

/-- Odd divides odd. -/
private theorem odd_of_dvd {a b : ℕ} (hab : a ∣ b) (hb : Odd b) : Odd a := by
  rcases hab with ⟨c, rfl⟩; rw [Nat.odd_mul] at hb; exact hb.1

/-- Schur–Zassenhaus: the odd complement `Ñ` to `L` inside `P = π⁻¹(M)`, where `L = ker π` is a
2-group and `M ◁ H` is odd. -/
theorem sz_odd_complement {H Y : Type} [Group H] [Group Y] [Finite Y]
    (piY : Y →* H) (hpi : Function.Surjective piY)
    (L : Subgroup Y) (hkerL : piY.ker = L)
    (M : Subgroup H) [M.Normal]
    (hMcop : Nat.Coprime (Nat.card L) (Nat.card M)) :
    ∃ Ntil : Subgroup Y, Ntil ≤ M.comap piY ∧ Ntil ⊓ L = ⊥ ∧ Ntil ⊔ L = M.comap piY ∧
      Nat.card Ntil = Nat.card M := by
  haveI : Finite H := Finite.of_surjective piY hpi
  haveI hLn : L.Normal := hkerL ▸ piY.normal_ker
  set P := M.comap piY with hPdef
  have hLP : L ≤ P := by
    intro x hx
    rw [hPdef, Subgroup.mem_comap, ← hkerL, MonoidHom.mem_ker] at *
    rw [hx]; exact M.one_mem
  -- card P = card L * card M
  have hLindex : L.index = Nat.card H := by
    rw [Subgroup.index_eq_card, ← hkerL]
    exact Nat.card_congr (QuotientGroup.quotientKerEquivOfSurjective piY hpi).toEquiv
  have hPindex : P.index = M.index := Subgroup.index_comap_of_surjective M hpi
  have hcardY_L : Nat.card L * Nat.card H = Nat.card Y := by
    rw [← hLindex]; exact Subgroup.card_mul_index L
  have hcardH_M : Nat.card M * M.index = Nat.card H := Subgroup.card_mul_index M
  have hcardP : Nat.card P * M.index = Nat.card Y := by
    rw [← hPindex]; exact Subgroup.card_mul_index P
  have hMindex_pos : 0 < M.index := Nat.pos_of_ne_zero Subgroup.index_ne_zero_of_finite
  have hcardP_eq : Nat.card P = Nat.card L * Nat.card M := by
    apply Nat.eq_of_mul_eq_mul_right hMindex_pos
    rw [hcardP, mul_assoc, hcardH_M, hcardY_L]
  -- Work inside ↥P.
  haveI hNn : (L.subgroupOf P).Normal := hLn.subgroupOf P
  have hcardN : Nat.card (L.subgroupOf P) = Nat.card L :=
    Nat.card_congr (Subgroup.subgroupOfEquivOfLe hLP).toEquiv
  have hNidx : (L.subgroupOf P).index = Nat.card M := by
    have hmul := Subgroup.card_mul_index (L.subgroupOf P)
    rw [hcardN, hcardP_eq] at hmul
    exact Nat.eq_of_mul_eq_mul_left Nat.card_pos hmul
  have hcop : Nat.Coprime (Nat.card (L.subgroupOf P)) (L.subgroupOf P).index := by
    rw [hcardN, hNidx]; exact hMcop
  obtain ⟨K, hK⟩ := Subgroup.exists_right_complement'_of_coprime hcop
  set Ntil := K.map P.subtype with hNtil
  have hNleP : Ntil ≤ P := Subgroup.map_subtype_le K
  have hLeq : (L.subgroupOf P).map P.subtype = L := Subgroup.map_subgroupOf_eq_of_le hLP
  have hmaptop : Subgroup.map P.subtype ⊤ = P := by
    rw [← MonoidHom.range_eq_map]; exact P.range_subtype
  have hcardK : Nat.card K = Nat.card M := by
    have hcm := hK.card_mul
    rw [hcardN, hcardP_eq] at hcm
    exact Nat.eq_of_mul_eq_mul_left Nat.card_pos hcm
  refine ⟨Ntil, hNleP, ?_, ?_, ?_⟩
  · -- Ntil ⊓ L = ⊥
    rw [hNtil, ← hLeq, ← Subgroup.map_inf K (L.subgroupOf P) P.subtype P.subtype_injective,
      inf_comm, disjoint_iff.mp hK.disjoint, Subgroup.map_bot]
  · -- Ntil ⊔ L = P
    have hthis := congrArg (Subgroup.map P.subtype) hK.sup_eq_top
    rw [Subgroup.map_sup, hLeq, hmaptop] at hthis
    rw [hNtil, sup_comm]; exact hthis
  · -- card Ntil = card M
    rw [hNtil, ← Nat.card_congr
      (Subgroup.equivMapOfInjective K P.subtype P.subtype_injective).toEquiv, hcardK]

open scoped Pointwise commutatorElement in
/-- **Lemma 9.2 (structure).** For a marked target `1 → L → Y → H → 1` with `L = ker π` a
2-group *scalar stack* and `H` 2-nilpotent (`M = O²H` odd, `H/M` a 2-group), there is a unique
odd normal complement `Ñ ◁ Y` to `L` over `M`: `Ñ` is odd, `Y/Ñ` is a 2-group, `Ñ ∩ L = ⊥`,
`Ñ` centralizes `L`, `π(Ñ) = M`, and `Ñ · L = π⁻¹(M)`.  These are the fibre-product pieces
feeding `coprime_fiber_product` in P-17b3. -/
theorem lemma_9_2_core {H Y : Type} [Group H] [Group Y] [Finite Y]
    (piY : Y →* H) (hpi : Function.Surjective piY)
    (L : Subgroup Y) (hkerL : piY.ker = L) (hL2 : IsPGroup 2 L)
    (hstack : SectionSeven.IsScalarStack L)
    (M : Subgroup H) [M.Normal] (hModd : Odd (Nat.card M)) (hMtwo : IsPGroup 2 (H ⧸ M)) :
    ∃ Ntil : Subgroup Y, ∃ _ : Ntil.Normal, Odd (Nat.card Ntil) ∧ IsPGroup 2 (Y ⧸ Ntil) ∧
      Ntil ⊓ L = ⊥ ∧ ⁅Ntil, L⁆ = ⊥ ∧ Ntil.map piY = M ∧ Ntil ⊔ L = M.comap piY := by
  haveI : Finite H := Finite.of_surjective piY hpi
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  haveI hLn : L.Normal := hkerL ▸ piY.normal_ker
  haveI hMcn : (M.comap piY).Normal := ‹M.Normal›.comap piY
  -- card L (a 2-power) is coprime to card M (odd)
  have hcop : Nat.Coprime (Nat.card L) (Nat.card M) := by
    obtain ⟨k, hk⟩ := hL2.exists_card_eq
    rw [hk]
    have hnd : ¬ (2 : ℕ) ∣ Nat.card M := by have := Nat.odd_iff.mp hModd; omega
    exact (Nat.prime_two.coprime_iff_not_dvd.mpr hnd).pow_left k
  obtain ⟨Ntil, hNleP, hNL_bot, hNL_sup, hcardNtil⟩ := sz_odd_complement piY hpi L hkerL M hcop
  -- `Ñ` centralizes `L` (odd group on a scalar stack)
  have hcentral : ⁅Ntil, L⁆ = ⊥ :=
    scalarStack_centralized_of_coprime hstack (by rw [hcardNtil]; exact hcop.symm)
  -- every element of `P = Ñ·L` factors as `ñ·ℓ`
  have hdecomp : ∀ p ∈ Ntil ⊔ L, ∃ ñ ∈ Ntil, ∃ ℓ ∈ L, ñ * ℓ = p := by
    intro p hp
    have hp' : p ∈ (Ntil : Set Y) * (L : Set Y) := by
      rw [← Subgroup.mul_normal Ntil L]; exact hp
    rw [Set.mem_mul] at hp'
    obtain ⟨ñ, hñ, ℓ, hℓ, hprod⟩ := hp'
    exact ⟨ñ, hñ, ℓ, hℓ, hprod⟩
  -- order in a subgroup equals order in `Y`
  have hoc : ∀ (S : Subgroup Y) (x : Y) (hx : x ∈ S), orderOf (⟨x, hx⟩ : S) = orderOf x :=
    fun S x hx => (orderOf_injective S.subtype Subtype.coe_injective ⟨x, hx⟩).symm
  -- the characterisation: `Ñ` = the odd-order elements of `P`
  have hkey : ∀ p : Y, p ∈ Ntil ⊔ L → Odd (orderOf p) → p ∈ Ntil := by
    intro p hpsup hpodd
    obtain ⟨ñ, hñ, ℓ, hℓ, hprod⟩ := hdecomp p hpsup
    have hcomm : Commute ñ ℓ := by
      have h1 : ⁅ñ, ℓ⁆ ∈ ⁅Ntil, L⁆ := Subgroup.commutator_mem_commutator hñ hℓ
      rw [hcentral, Subgroup.mem_bot] at h1
      exact commutatorElement_eq_one_iff_commute.mp h1
    have hñdvd : orderOf ñ ∣ Nat.card M := by
      rw [← hcardNtil, ← hoc Ntil ñ hñ]; exact orderOf_dvd_natCard _
    have hℓdvd : orderOf ℓ ∣ Nat.card L := by
      rw [← hoc L ℓ hℓ]; exact orderOf_dvd_natCard _
    have hcopñℓ : Nat.Coprime (orderOf ñ) (orderOf ℓ) :=
      (hcop.symm.coprime_dvd_left hñdvd).coprime_dvd_right hℓdvd
    have hordp : orderOf p = orderOf ñ * orderOf ℓ := by
      rw [← hprod]; exact hcomm.orderOf_mul_eq_mul_orderOf_of_coprime hcopñℓ
    rw [hordp] at hpodd
    have hℓodd : Odd (orderOf ℓ) := (Nat.odd_mul.mp hpodd).2
    obtain ⟨j, hj⟩ := IsPGroup.iff_orderOf.mp hL2 ⟨ℓ, hℓ⟩
    rw [hoc L ℓ hℓ] at hj
    rw [hj] at hℓodd
    have hj0 : j = 0 := by
      by_contra hjne
      have h2d : 2 ∣ 2 ^ j := dvd_pow_self 2 hjne
      have := Nat.odd_iff.mp hℓodd
      omega
    have hℓ1 : ℓ = 1 := orderOf_eq_one_iff.mp (by rw [hj, hj0, pow_zero])
    rw [← hprod, hℓ1, mul_one]; exact hñ
  -- normality of `Ñ` in `Y`
  have hNn : Ntil.Normal := by
    refine ⟨fun n hn y => ?_⟩
    apply hkey
    · rw [hNL_sup]; exact hMcn.conj_mem n (hNL_sup ▸ Subgroup.mem_sup_left hn) y
    · have hconj : orderOf (y * n * y⁻¹) = orderOf n := by
        have h := orderOf_injective (MulAut.conj y).toMonoidHom (MulAut.conj y).injective n
        simpa [MulAut.conj_apply] using h
      rw [hconj]
      exact odd_of_dvd (by rw [← hcardNtil, ← hoc Ntil n hn]; exact orderOf_dvd_natCard _) hModd
  -- `π(Ñ) = M`
  have hmapM : Ntil.map piY = M := by
    apply le_antisymm (Subgroup.map_le_iff_le_comap.mpr hNleP)
    intro m hm
    obtain ⟨y, rfl⟩ := hpi m
    have hyP : y ∈ Ntil ⊔ L := by rw [hNL_sup]; exact Subgroup.mem_comap.mpr hm
    obtain ⟨ñ, hñ, ℓ, hℓ, hprod⟩ := hdecomp y hyP
    have hpiy : piY y = piY ñ := by
      rw [← hprod, map_mul, show piY ℓ = 1 from (MonoidHom.mem_ker.mp (hkerL ▸ hℓ)), mul_one]
    rw [hpiy]; exact Subgroup.mem_map.mpr ⟨ñ, hñ, rfl⟩
  -- `Y/Ñ` is a 2-group
  haveI := hNn
  obtain ⟨kL, hkL⟩ := hL2.exists_card_eq
  obtain ⟨kH, hkH⟩ := hMtwo.exists_card_eq
  have hLindex2 : L.index = Nat.card H := by
    rw [Subgroup.index_eq_card, ← hkerL]
    exact Nat.card_congr (QuotientGroup.quotientKerEquivOfSurjective piY hpi).toEquiv
  have hcardYLH : Nat.card L * Nat.card H = Nat.card Y := by
    rw [← hLindex2]; exact Subgroup.card_mul_index L
  have hcardHM : Nat.card M * Nat.card (H ⧸ M) = Nat.card H := by
    rw [← Subgroup.index_eq_card]; exact Subgroup.card_mul_index M
  have hNtilindex : Ntil.index = 2 ^ kL * 2 ^ kH := by
    have hci : Nat.card Ntil * Ntil.index = Nat.card Y := Subgroup.card_mul_index Ntil
    rw [hcardNtil, ← hcardYLH, ← hcardHM, hkL, hkH] at hci
    have hre : 2 ^ kL * (Nat.card M * 2 ^ kH) = Nat.card M * (2 ^ kL * 2 ^ kH) := by ring
    rw [hre] at hci
    exact Nat.eq_of_mul_eq_mul_left Nat.card_pos hci
  have hYNtil2 : IsPGroup 2 (Y ⧸ Ntil) :=
    IsPGroup.of_card (n := kL + kH) (by rw [← Subgroup.index_eq_card, hNtilindex, pow_add])
  exact ⟨Ntil, hNn, by rw [hcardNtil]; exact hModd, hYNtil2, hNL_bot, hcentral, hmapM, hNL_sup⟩

/-- **The head of a boundary-framed target is 2-nilpotent.**  `H` is a finite tame quotient
`α : Ttame ↠ H` (the frame `α`), so its generators `α σ, α τ` satisfy the tame relation and
generate `H`; `tame_two_nilpotent` applies.  This discharges the `M` hypothesis of
`lemma_9_2_core` from the frame. -/
theorem head_two_nilpotent {H E : Type} [Group H] [TopologicalSpace H] [DiscreteTopology H]
    [Finite H] [CommGroup E] [TopologicalSpace E] [DiscreteTopology E] [Finite E]
    (F : BoundaryFrame H E) :
    ∃ M : Subgroup H, ∃ _ : M.Normal, Odd (Nat.card M) ∧ IsPGroup 2 (H ⧸ M) := by
  have hgen : Subgroup.closure {F.alpha tameSigma, F.alpha tameTau} = ⊤ :=
    GQ2.SectionThree.gen_ttame_quotient F.alpha.toMonoidHom F.alpha.continuous_toFun
      F.alpha_surjective
  have hrel : (F.alpha tameSigma)⁻¹ * F.alpha tameTau * F.alpha tameSigma
      = (F.alpha tameTau) ^ 2 := by
    have h := congrArg (⇑F.alpha) tame_relation
    rw [conjP, map_mul, map_mul, map_inv, map_pow] at h
    exact h
  exact tame_two_nilpotent hgen hrel

/-! ## Lemma 9.2 fibre-product infrastructure  (P-17b3)

The concrete tools the (144) correspondence runs on, all proved std-3:

* `odd_subgroup_le_ker_of_expTwo` — `θ_Y` (decoration to the exponent-2 group `E`) kills the odd
  complement `Ñ`, so it descends to `Q = Y/Ñ` (`L92.thetaBarQ`).  This is where `hE2` enters.
* `odd_mem_of_pTwo_quotient` — an odd-order element dies in a 2-group quotient (⟹ `H₂ = H/O²H`
  is cyclic, the engine of source-independence).
* `L92` — a bundle of the `lemma_9_2_core` outputs; `L92.fibreMulEquiv` is the fibre-product
  isomorphism `Y ≃* {(h,q) | κ h = λ q}` (eq. (143)), built from `coprime_fiber_product`.

Remaining for `terminal_count_eq` (P-17b3): the boundary-lift ↔ Q-count bijection (two more
`coprime_fiber_product` applications for surjectivity) and source-independence of the Q-count
(the H₂-values factor through `ν_t`, so `compatA`/`compatF` make the two sources agree). -/

/-- **θ kills the odd complement.**  A homomorphism from a finite group to an exponent-2 group
vanishes on every odd-order normal subgroup.  (This is where `hE2` enters the terminal case:
`θ_Y` descends to `Q = Y/Ñ`.) -/
theorem odd_subgroup_le_ker_of_expTwo {Y E : Type} [Group Y] [Finite Y] [Group E]
    {N : Subgroup Y} (hodd : Odd (Nat.card N)) (hE2 : ∀ e : E, e ^ 2 = 1) (θ : Y →* E) :
    N ≤ θ.ker := by
  intro n hn
  rw [MonoidHom.mem_ker]
  have hno : Odd (orderOf n) := by
    have h1 : orderOf (⟨n, hn⟩ : N) ∣ Nat.card N := orderOf_dvd_natCard _
    have h2 : orderOf (⟨n, hn⟩ : N) = orderOf n :=
      (orderOf_injective N.subtype Subtype.coe_injective ⟨n, hn⟩).symm
    rw [h2] at h1
    exact odd_of_dvd h1 hodd
  have hd2 : orderOf (θ n) ∣ 2 := orderOf_dvd_of_pow_eq_one (hE2 (θ n))
  have hdn : orderOf (θ n) ∣ orderOf n := orderOf_map_dvd θ n
  have hodd' : Odd (orderOf (θ n)) := odd_of_dvd hdn hno
  rcases (Nat.dvd_prime Nat.prime_two).mp hd2 with h | h
  · exact orderOf_eq_one_iff.mp h
  · exact absurd (h ▸ hodd') (by decide)


/-- Bundle of the `lemma_9_2_core` outputs, to avoid threading a dozen hypotheses through the
fibre-product construction. -/
structure L92 (H Y : Type) [Group H] [Group Y] [Finite Y] where
  piY : Y →* H
  hpi : Function.Surjective piY
  L : Subgroup Y
  hkerL : piY.ker = L
  M : Subgroup H
  hMn : M.Normal
  hModd : Odd (Nat.card M)
  Ntil : Subgroup Y
  hNn : Ntil.Normal
  hNodd : Odd (Nat.card Ntil)
  hNL : Ntil ⊓ L = ⊥
  hmapM : Ntil.map piY = M
  hNLsup : Ntil ⊔ L = M.comap piY
  hQ2 : IsPGroup 2 (Y ⧸ Ntil)

namespace L92

variable {H Y : Type} [Group H] [Group Y] [Finite Y] (D : L92 H Y)

/-- `Q = Y / Ñ`. -/
abbrev Q := Y ⧸ D.Ntil

instance : (D.Ntil).Normal := D.hNn
instance : (D.M).Normal := D.hMn

/-- `Ntil ≤ ker (κ ∘ π_Y) = π_Y⁻¹(M)`. -/
theorem ntil_le_ker : D.Ntil ≤ ((QuotientGroup.mk' D.M).comp D.piY).ker := by
  intro n hn
  rw [MonoidHom.mem_ker, MonoidHom.comp_apply, QuotientGroup.mk'_apply,
    QuotientGroup.eq_one_iff]
  have : n ∈ D.M.comap D.piY := D.hNLsup ▸ Subgroup.mem_sup_left hn
  exact Subgroup.mem_comap.mp this

/-- The lower map `λ : Q ↠ H/M`, descending `κ ∘ π_Y`. -/
noncomputable def lamQ : D.Q →* H ⧸ D.M :=
  QuotientGroup.lift D.Ntil ((QuotientGroup.mk' D.M).comp D.piY) D.ntil_le_ker

@[simp] theorem lamQ_mk (y : Y) :
    D.lamQ (QuotientGroup.mk y) = QuotientGroup.mk' D.M (D.piY y) := rfl

/-- The fibre product `{(h,q) | κ h = λ q} ≤ H × Q`. -/
noncomputable def fibreSub : Subgroup (H × D.Q) :=
  MonoidHom.eqLocus ((QuotientGroup.mk' D.M).comp (MonoidHom.fst H D.Q))
    (D.lamQ.comp (MonoidHom.snd H D.Q))

/-- `(π_Y y, mk' Ntil y)` lands in the fibre product. -/
theorem toFibre_mem (y : Y) : (D.piY y, (QuotientGroup.mk y : D.Q)) ∈ D.fibreSub := by
  show (QuotientGroup.mk' D.M) (D.piY y) = D.lamQ (QuotientGroup.mk y)
  rw [lamQ_mk]

/-- The map `Y → fibre product`, `y ↦ (π_Y y, mk' Ntil y)`. -/
noncomputable def toFibre : Y →* D.fibreSub :=
  (D.piY.prod (QuotientGroup.mk' D.Ntil)).codRestrict _ D.toFibre_mem

theorem toFibre_injective : Function.Injective D.toFibre := by
  rw [injective_iff_map_eq_one]
  intro y hy
  have h1 : (D.piY y, (QuotientGroup.mk y : D.Q)) = 1 := by
    have := congrArg (Subtype.val) hy
    simpa [toFibre, MonoidHom.codRestrict] using this
  rw [Prod.ext_iff] at h1
  obtain ⟨hyH, hyQ⟩ := h1
  have hyL : y ∈ D.L := D.hkerL ▸ MonoidHom.mem_ker.mpr hyH
  have hyN : y ∈ D.Ntil := by rwa [← QuotientGroup.eq_one_iff]
  have : y ∈ D.Ntil ⊓ D.L := ⟨hyN, hyL⟩
  rw [D.hNL, Subgroup.mem_bot] at this
  exact this

theorem lamQ_surjective : Function.Surjective D.lamQ := by
  intro z
  obtain ⟨y, hy⟩ := (QuotientGroup.mk'_surjective D.M).comp D.hpi z
  exact ⟨QuotientGroup.mk y, by rw [lamQ_mk]; exact hy⟩

theorem toFibre_surjective : Function.Surjective D.toFibre := by
  haveI : Finite H := Finite.of_surjective D.piY D.hpi
  have hcop : Nat.Coprime (Nat.card (QuotientGroup.mk' D.M).ker) (Nat.card D.lamQ.ker) := by
    rw [QuotientGroup.ker_mk']
    have hpg : IsPGroup 2 (D.lamQ.ker) := fun x => by
      obtain ⟨k, hk⟩ := D.hQ2 (x : D.Q)
      exact ⟨k, by ext1; push_cast; exact hk⟩
    obtain ⟨k, hk⟩ := hpg.exists_card_eq
    rw [hk]
    have hnd : ¬ (2 : ℕ) ∣ Nat.card D.M := by have := Nat.odd_iff.mp D.hModd; omega
    exact ((Nat.prime_two.coprime_iff_not_dvd.mpr hnd).symm).pow_right k
  set J := (D.piY.prod (QuotientGroup.mk' D.Ntil)).range with hJdef
  have hJsub : ∀ p ∈ J, (QuotientGroup.mk' D.M) p.1 = D.lamQ p.2 := by
    rintro p ⟨y, rfl⟩
    show (QuotientGroup.mk' D.M) (D.piY y) = D.lamQ (QuotientGroup.mk y)
    rw [lamQ_mk]
  have hJA : Function.Surjective fun p : J => (p : H × D.Q).1 := by
    intro h; obtain ⟨y, hy⟩ := D.hpi h
    exact ⟨⟨(D.piY y, QuotientGroup.mk y), y, rfl⟩, hy⟩
  have hJB : Function.Surjective fun p : J => (p : H × D.Q).2 := by
    intro q; obtain ⟨y, hy⟩ := QuotientGroup.mk'_surjective D.Ntil q
    exact ⟨⟨(D.piY y, QuotientGroup.mk y), y, rfl⟩, hy⟩
  intro p
  have hp : (QuotientGroup.mk' D.M) (p : H × D.Q).1 = D.lamQ (p : H × D.Q).2 := p.2
  have hmem : (p : H × D.Q) ∈ J :=
    GQ2.FiniteGroup.coprime_fiber_product (QuotientGroup.mk' D.M) D.lamQ
      (QuotientGroup.mk'_surjective _) D.lamQ_surjective hcop J hJsub hJA hJB _ hp
  obtain ⟨y, hy⟩ := hmem
  exact ⟨y, Subtype.ext hy⟩

/-- **The fibre-product isomorphism** `Y ≃* {(h,q) | κ h = λ q}` (Lemma 9.2, eq. (143)). -/
noncomputable def fibreMulEquiv : Y ≃* D.fibreSub :=
  MulEquiv.ofBijective D.toFibre ⟨D.toFibre_injective, D.toFibre_surjective⟩

@[simp] theorem fibreMulEquiv_apply (y : Y) :
    (D.fibreMulEquiv y : H × D.Q) = (D.piY y, QuotientGroup.mk y) := rfl

/-- A decoration `θ : Y →* E` to an exponent-2 group descends to `Q = Y/Ñ` (θ kills odd `Ñ`). -/
noncomputable def thetaBarQ {E : Type} [Group E] (θ : Y →* E) (hE2 : ∀ e : E, e ^ 2 = 1) :
    D.Q →* E :=
  QuotientGroup.lift D.Ntil θ (odd_subgroup_le_ker_of_expTwo D.hNodd hE2 θ)

@[simp] theorem thetaBarQ_mk {E : Type} [Group E] (θ : Y →* E) (hE2 : ∀ e : E, e ^ 2 = 1)
    (y : Y) : D.thetaBarQ θ hE2 (QuotientGroup.mk y) = θ y := rfl

end L92

/-! ## The (144) correspondence  (P-17b3)

Lemma 9.2's fibre product identifies the boundary-framed lifts `Γ ↠ Y` with a Q-count set
(`boundaryLifts_equiv_qlifts`, source-generic); the maximal-pro-2 universal property then makes
that count source-independent (`qlifts_equiv_commonLifts`), routed through `ν`-compatibility and
`b`-surjectivity — no marked isomorphism is needed (only `prop_3_10_gammaA` and `ker_pro2F`). -/

section Correspondence

open SectionThree
open scoped Pointwise

variable {Y : Type} [Group Y] [TopologicalSpace Y] [DiscreteTopology Y] [Finite Y]

namespace L92

variable (D : L92 H Y)

omit [TopologicalSpace H] [DiscreteTopology H] [Finite H] in
/-- `Q = Y/Ñ` is discrete (quotient of a discrete group by an open subgroup). -/
theorem discreteTopology_Q : DiscreteTopology D.Q :=
  QuotientGroup.discreteTopology (isOpen_discrete _)

omit [TopologicalSpace H] [DiscreteTopology H] [Finite H] [TopologicalSpace Y]
  [DiscreteTopology Y] in
theorem piY_symm (z : D.fibreSub) : D.piY (D.fibreMulEquiv.symm z) = (z : H × D.Q).1 := by
  have h := D.fibreMulEquiv_apply (D.fibreMulEquiv.symm z)
  rw [MulEquiv.apply_symm_apply] at h
  exact ((Prod.ext_iff.mp h).1).symm

omit [TopologicalSpace H] [DiscreteTopology H] [Finite H] [TopologicalSpace Y]
  [DiscreteTopology Y] in
theorem mk_symm (z : D.fibreSub) :
    (QuotientGroup.mk (D.fibreMulEquiv.symm z) : D.Q) = (z : H × D.Q).2 := by
  have h := D.fibreMulEquiv_apply (D.fibreMulEquiv.symm z)
  rw [MulEquiv.apply_symm_apply] at h
  exact ((Prod.ext_iff.mp h).2).symm

/-- The quotient map `Y ↠ Q` as a continuous hom. -/
def mkCH : ContinuousMonoidHom Y D.Q := ⟨QuotientGroup.mk' D.Ntil, continuous_quotient_mk'⟩

omit [TopologicalSpace H] [DiscreteTopology H] [Finite H] [DiscreteTopology Y] in
@[simp] theorem mkCH_apply (y : Y) : D.mkCH y = (QuotientGroup.mk y : D.Q) := rfl

end L92

variable {Γ : Type} [Group Γ] [TopologicalSpace Γ]

/-- **The Q-count set**: continuous surjections `Γ ↠ Q` satisfying the descended boundary
conditions (H-part through `λ`, θ-part through `θ̄`). -/
def QLifts (F : BoundaryFrame H E) (T : MarkedTarget H E Y) (hE2 : ∀ e : E, e ^ 2 = 1)
    (D : L92 H Y) (b : ContinuousMonoidHom Γ ↥boundarySubgroup) : Type :=
  { g : ContSurj Γ D.Q //
    (∀ γ, D.lamQ (g.1 γ) = QuotientGroup.mk' D.M (F.alpha (b γ).val.1)) ∧
    (∀ γ, D.thetaBarQ T.thetaY hE2 (g.1 γ) = F.psiBar (b γ).val.2) }

/-- The reconstruction of a boundary lift `f : Γ ↠ Y` from a Q-lift `g`, via the fibre product
`Y ≅ H ×_{H₂} Q`: `f γ := fibreMulEquiv.symm (F.alpha (b γ).1, g γ)`. -/
noncomputable def qliftHom (F : BoundaryFrame H E) (D : L92 H Y)
    (b : ContinuousMonoidHom Γ ↥boundarySubgroup) (g : ContSurj Γ D.Q)
    (h1 : ∀ γ, D.lamQ (g.1 γ) = QuotientGroup.mk' D.M (F.alpha (b γ).val.1)) :
    ContinuousMonoidHom Γ Y where
  toMonoidHom := D.fibreMulEquiv.symm.toMonoidHom.comp
    (((F.alpha.toMonoidHom.comp ((MonoidHom.fst Ttame PiBd).comp
      (boundarySubgroup.subtype.comp b.toMonoidHom))).prod g.1.toMonoidHom).codRestrict
      D.fibreSub (fun γ => (h1 γ).symm))
  continuous_toFun := by
    haveI hdQ : DiscreteTopology D.Q := D.discreteTopology_Q
    haveI : DiscreteTopology (H × D.Q) := inferInstance
    haveI : DiscreteTopology D.fibreSub := inferInstance
    have hφ : Continuous fun γ : Γ =>
        (⟨(F.alpha (b γ).val.1, g.1 γ), (h1 γ).symm⟩ : D.fibreSub) :=
      Continuous.subtype_mk ((F.alpha.continuous_toFun.comp (continuous_fst.comp
        (continuous_subtype_val.comp b.continuous_toFun))).prodMk g.1.continuous_toFun) _
    exact (continuous_of_discreteTopology (f := D.fibreMulEquiv.symm)).comp hφ

@[simp] theorem qliftHom_piY (F : BoundaryFrame H E) (D : L92 H Y)
    (b : ContinuousMonoidHom Γ ↥boundarySubgroup) (g : ContSurj Γ D.Q)
    (h1 : ∀ γ, D.lamQ (g.1 γ) = QuotientGroup.mk' D.M (F.alpha (b γ).val.1)) (γ : Γ) :
    D.piY (qliftHom F D b g h1 γ) = F.alpha (b γ).val.1 := by
  rw [qliftHom]
  exact D.piY_symm _

@[simp] theorem qliftHom_mk (F : BoundaryFrame H E) (D : L92 H Y)
    (b : ContinuousMonoidHom Γ ↥boundarySubgroup) (g : ContSurj Γ D.Q)
    (h1 : ∀ γ, D.lamQ (g.1 γ) = QuotientGroup.mk' D.M (F.alpha (b γ).val.1)) (γ : Γ) :
    (QuotientGroup.mk (qliftHom F D b g h1 γ) : D.Q) = g.1 γ := by
  rw [qliftHom]
  exact D.mk_symm _

/-- The reconstructed `f = qliftHom … g` is **surjective** (the "second `coprime_fiber_product`":
the range of `(γ ↦ (F.alpha (b γ).1, g γ))` is all of the fibre, since it projects onto both `H`
and `Q` which have coprime kernels).  Uses `hb` (surjectivity of `b`). -/
theorem qliftHom_surjective (F : BoundaryFrame H E) (D : L92 H Y)
    (b : ContinuousMonoidHom Γ ↥boundarySubgroup) (hb : Function.Surjective b)
    (g : ContSurj Γ D.Q)
    (h1 : ∀ γ, D.lamQ (g.1 γ) = QuotientGroup.mk' D.M (F.alpha (b γ).val.1)) :
    Function.Surjective (qliftHom F D b g h1) := by
  haveI : Finite H := Finite.of_surjective D.piY D.hpi
  have hHsurj : Function.Surjective fun γ : Γ => F.alpha (b γ).val.1 := by
    intro h
    obtain ⟨t, ht⟩ := F.alpha_surjective h
    obtain ⟨p, hp⟩ := nuTwo_surjective (nuT t)
    obtain ⟨γ, hγ⟩ := hb ⟨(t, p), hp.symm⟩
    refine ⟨γ, ?_⟩
    show F.alpha (b γ).val.1 = h
    rw [hγ]; exact ht
  have hcop : Nat.Coprime (Nat.card (QuotientGroup.mk' D.M).ker) (Nat.card D.lamQ.ker) := by
    rw [QuotientGroup.ker_mk']
    have hpg : IsPGroup 2 (D.lamQ.ker) := fun x => by
      obtain ⟨k, hk⟩ := D.hQ2 (x : D.Q)
      exact ⟨k, by ext1; push_cast; exact hk⟩
    obtain ⟨k, hk⟩ := hpg.exists_card_eq
    rw [hk]
    have hnd : ¬ (2 : ℕ) ∣ Nat.card D.M := by have := Nat.odd_iff.mp D.hModd; omega
    exact ((Nat.prime_two.coprime_iff_not_dvd.mpr hnd).symm).pow_right k
  set hHomM : Γ →* H := F.alpha.toMonoidHom.comp ((MonoidHom.fst Ttame PiBd).comp
    (boundarySubgroup.subtype.comp b.toMonoidHom)) with hHomMdef
  set J := (hHomM.prod g.1.toMonoidHom).range with hJdef
  have hJsub : ∀ p ∈ J, (QuotientGroup.mk' D.M) p.1 = D.lamQ p.2 := by
    rintro p ⟨γ, rfl⟩
    exact (h1 γ).symm
  have hJA : Function.Surjective fun p : J => (p : H × D.Q).1 := by
    intro h
    obtain ⟨γ, hγ⟩ := hHsurj h
    exact ⟨⟨(hHomM γ, g.1 γ), γ, rfl⟩, hγ⟩
  have hJB : Function.Surjective fun p : J => (p : H × D.Q).2 := by
    intro q
    obtain ⟨γ, hγ⟩ := g.2 q
    exact ⟨⟨(hHomM γ, g.1 γ), γ, rfl⟩, hγ⟩
  intro y
  have hz : (QuotientGroup.mk' D.M) (D.fibreMulEquiv y : H × D.Q).1
      = D.lamQ (D.fibreMulEquiv y : H × D.Q).2 := (D.fibreMulEquiv y).2
  obtain ⟨γ, hγ⟩ := GQ2.FiniteGroup.coprime_fiber_product (QuotientGroup.mk' D.M) D.lamQ
    (QuotientGroup.mk'_surjective _) D.lamQ_surjective hcop J hJsub hJA hJB _ hz
  refine ⟨γ, D.fibreMulEquiv.injective (Subtype.ext ?_)⟩
  rw [D.fibreMulEquiv_apply, qliftHom_piY, qliftHom_mk]
  exact hγ

/-- **Forward map** of the (144) correspondence: a boundary lift `f : Γ ↠ Y` descends to the
Q-lift `mk ∘ f`. -/
def blToQ (F : BoundaryFrame H E) (T : MarkedTarget H E Y) (hE2 : ∀ e : E, e ^ 2 = 1)
    (D : L92 H Y) (hDpi : D.piY = T.piY) (b : ContinuousMonoidHom Γ ↥boundarySubgroup)
    (x : BoundaryLifts b F T) : QLifts F T hE2 D b := by
  refine ⟨⟨D.mkCH.comp x.1.1, (QuotientGroup.mk'_surjective _).comp x.1.2⟩, ?_, ?_⟩
  · intro γ
    have hbl : T.piY (x.1.1 γ) = F.alpha (b γ).val.1 := congrArg Prod.fst (x.2 γ)
    show D.lamQ (D.mkCH (x.1.1 γ)) = QuotientGroup.mk' D.M (F.alpha (b γ).val.1)
    rw [D.mkCH_apply, D.lamQ_mk, hDpi, hbl]
  · intro γ
    have hbl : T.thetaY (x.1.1 γ) = F.psiBar (b γ).val.2 := congrArg Prod.snd (x.2 γ)
    show D.thetaBarQ T.thetaY hE2 (D.mkCH (x.1.1 γ)) = F.psiBar (b γ).val.2
    rw [D.mkCH_apply, D.thetaBarQ_mk, hbl]

/-- **Backward map** of the (144) correspondence: a Q-lift `g` reconstructs the boundary lift
`qliftHom … g` via the fibre product. -/
noncomputable def qToBl (F : BoundaryFrame H E) (T : MarkedTarget H E Y)
    (hE2 : ∀ e : E, e ^ 2 = 1) (D : L92 H Y) (hDpi : D.piY = T.piY)
    (b : ContinuousMonoidHom Γ ↥boundarySubgroup)
    (hb : Function.Surjective b) (g : QLifts F T hE2 D b) : BoundaryLifts b F T := by
  refine ⟨⟨qliftHom F D b g.1 g.2.1, qliftHom_surjective F D b hb g.1 g.2.1⟩, fun γ => ?_⟩
  refine Prod.ext ?_ ?_
  · show T.piY (qliftHom F D b g.1 g.2.1 γ) = F.alpha (b γ).val.1
    rw [← hDpi, qliftHom_piY]
  · show T.thetaY (qliftHom F D b g.1 g.2.1 γ) = F.psiBar (b γ).val.2
    rw [← D.thetaBarQ_mk T.thetaY hE2, qliftHom_mk]
    exact g.2.2 γ

/-- **(A) The (144) correspondence** (source-generic): the boundary-framed lifts `Γ ↠ Y` and the
Q-count set are in bijection, hence equinumerous.  Uses only surjectivity of `b`. -/
theorem boundaryLifts_equiv_qlifts (F : BoundaryFrame H E) (T : MarkedTarget H E Y)
    (hE2 : ∀ e : E, e ^ 2 = 1) (D : L92 H Y) (hDpi : D.piY = T.piY)
    (b : ContinuousMonoidHom Γ ↥boundarySubgroup) (hb : Function.Surjective b) :
    Nat.card (BoundaryLifts b F T) = Nat.card (QLifts F T hE2 D b) := by
  apply Nat.card_congr
  refine ⟨blToQ F T hE2 D hDpi b, qToBl F T hE2 D hDpi b hb, fun x => ?_, fun g => ?_⟩
  · -- left_inv
    apply Subtype.ext; apply Subtype.ext
    show qliftHom F D b (blToQ F T hE2 D hDpi b x).1 (blToQ F T hE2 D hDpi b x).2.1 = x.1.1
    ext γ
    have hpi : F.alpha (b γ).val.1 = D.piY (x.1.1 γ) := by
      rw [hDpi]; exact (congrArg Prod.fst (x.2 γ)).symm
    apply D.fibreMulEquiv.injective; apply Subtype.ext
    simp only [D.fibreMulEquiv_apply, qliftHom_piY, qliftHom_mk]
    exact Prod.ext hpi rfl
  · -- right_inv
    apply Subtype.ext; apply Subtype.ext; ext γ
    exact qliftHom_mk F D b g.1 g.2.1 γ

end Correspondence

section SourceIndependence

open SectionThree

/-- Precomposition with a topological iso is an equivalence of hom-sets. -/
def precompEquiv {A B Q : Type*} [Group A] [TopologicalSpace A] [Group B] [TopologicalSpace B]
    [Group Q] [TopologicalSpace Q] (ρ : ContinuousMulEquiv A B) :
    ContinuousMonoidHom B Q ≃ ContinuousMonoidHom A Q where
  toFun ψ := ψ.comp ⟨ρ.toMonoidHom, ρ.continuous_toFun⟩
  invFun φ := φ.comp ⟨ρ.symm.toMonoidHom, ρ.symm.continuous_toFun⟩
  left_inv ψ := by
    ext b
    exact congrArg ψ (ρ.apply_symm_apply b)
  right_inv φ := by
    ext a
    exact congrArg φ (ρ.symm_apply_apply a)

variable {Γ : Type} [Group Γ] [TopologicalSpace Γ] [IsTopologicalGroup Γ]
  [CompactSpace Γ] [T2Space Γ] [TotallyDisconnectedSpace Γ]

/-- The factoring of `pro2 : Γ ↠ Π` through the maximal pro-2 quotient of `Γ`
(`Π` is pro-2, `isProP_maxProPQuotient`). -/
noncomputable def pro2FactorHom (pro2 : ContinuousMonoidHom Γ PiBd) :
    ContinuousMonoidHom (maxProPQuotient 2 Γ) PiBd :=
  (maxProPHomEquiv (isProP_maxProPQuotient (G := profinitePresentation {piRelator}))).symm pro2

omit [T2Space Γ] in
theorem pro2FactorHom_maxProPMk (pro2 : ContinuousMonoidHom Γ PiBd) (γ : Γ) :
    pro2FactorHom pro2 (maxProPMk 2 Γ γ) = pro2 γ :=
  DFunLike.congr_fun ((maxProPHomEquiv
    (isProP_maxProPQuotient (G := profinitePresentation {piRelator}))).apply_symm_apply pro2) γ

/-- The maximal pro-2 quotient of `Γ` is `Π` (`PiBd`), via a pro-2 quotient map `pro2` whose
kernel is exactly `proPKernel 2 Γ`. -/
noncomputable def pro2Iso (pro2 : ContinuousMonoidHom Γ PiBd) (hsurj : Function.Surjective pro2)
    (hker : pro2.toMonoidHom.ker = proPKernel 2 Γ) :
    ContinuousMulEquiv (maxProPQuotient 2 Γ) PiBd :=
  continuousMulEquivOfBijective (pro2FactorHom pro2)
    ⟨by
        rw [injective_iff_map_eq_one]
        intro x hx
        obtain ⟨γ, rfl⟩ := quotientMk_surjective (proPKernel 2 Γ) x
        have hx' : pro2 γ = 1 := by rw [← pro2FactorHom_maxProPMk pro2 γ]; exact hx
        exact (quotientMk_eq_one_iff _).mpr (hker ▸ MonoidHom.mem_ker.mpr hx'),
      fun p => by
        obtain ⟨γ, rfl⟩ := hsurj p
        exact ⟨maxProPMk 2 Γ γ, pro2FactorHom_maxProPMk pro2 γ⟩⟩

omit [T2Space Γ] in
theorem pro2Iso_maxProPMk (pro2 : ContinuousMonoidHom Γ PiBd) (hsurj : Function.Surjective pro2)
    (hker : pro2.toMonoidHom.ker = proPKernel 2 Γ) (γ : Γ) :
    pro2Iso pro2 hsurj hker (maxProPMk 2 Γ γ) = pro2 γ :=
  pro2FactorHom_maxProPMk pro2 γ

/-- **Precomposition with the pro-2 quotient map** is a bijection of hom-sets into a pro-2 group
`Q`: every `g : Γ ↠ Q` factors uniquely through `Π`.  (The universal property of the maximal
pro-2 quotient, transported to `Π`.) -/
noncomputable def compPro2Equiv (pro2 : ContinuousMonoidHom Γ PiBd)
    (hsurj : Function.Surjective pro2) (hker : pro2.toMonoidHom.ker = proPKernel 2 Γ)
    {Q : Type} [Group Q] [TopologicalSpace Q] [IsTopologicalGroup Q] [CompactSpace Q] [T2Space Q]
    [TotallyDisconnectedSpace Q] (hQ : IsProP 2 Q) :
    ContinuousMonoidHom PiBd Q ≃ ContinuousMonoidHom Γ Q :=
  (precompEquiv (pro2Iso pro2 hsurj hker)).trans (maxProPHomEquiv hQ)

omit [T2Space Γ] in
theorem compPro2Equiv_apply_apply (pro2 : ContinuousMonoidHom Γ PiBd)
    (hsurj : Function.Surjective pro2) (hker : pro2.toMonoidHom.ker = proPKernel 2 Γ)
    {Q : Type} [Group Q] [TopologicalSpace Q] [IsTopologicalGroup Q] [CompactSpace Q] [T2Space Q]
    [TotallyDisconnectedSpace Q] (hQ : IsProP 2 Q) (ψ : ContinuousMonoidHom PiBd Q) (γ : Γ) :
    compPro2Equiv pro2 hsurj hker hQ ψ γ = ψ (pro2 γ) := by
  show ψ (pro2Iso pro2 hsurj hker (maxProPMk 2 Γ γ)) = ψ (pro2 γ)
  rw [pro2Iso_maxProPMk]

variable {Y : Type} [Group Y] [TopologicalSpace Y] [DiscreteTopology Y] [Finite Y]

/-- **The common Q-count set on `Π`** (source-free): the H-condition is indexed by `∂bd`
(so it never mentions a source), the θ-condition ranges over all of `Π`. -/
def CommonLifts (F : BoundaryFrame H E) (T : MarkedTarget H E Y) (hE2 : ∀ e : E, e ^ 2 = 1)
    (D : L92 H Y) : Type :=
  { g : ContSurj PiBd D.Q //
    (∀ x : ↥boundarySubgroup, D.lamQ (g.1 x.val.2) = QuotientGroup.mk' D.M (F.alpha x.val.1)) ∧
    (∀ π : PiBd, D.thetaBarQ T.thetaY hE2 (g.1 π) = F.psiBar π) }

/-- **(B) Source-independence** (per source): the Q-count for a source `Γ` (with pro-2 quotient
map `pro2` presenting `Π`, `hker`) equals the source-free count on `Π`.  The H-condition
transports through surjectivity of `b` (`hbpro2`: the pro-2 component of `b` is `pro2`); the
θ-condition is already on `Π`. -/
theorem qlifts_equiv_commonLifts (F : BoundaryFrame H E) (T : MarkedTarget H E Y)
    (hE2 : ∀ e : E, e ^ 2 = 1) (D : L92 H Y)
    {Γ : Type} [Group Γ] [TopologicalSpace Γ] [IsTopologicalGroup Γ] [CompactSpace Γ] [T2Space Γ]
    [TotallyDisconnectedSpace Γ] (b : ContinuousMonoidHom Γ ↥boundarySubgroup)
    (hb : Function.Surjective b) (pro2 : ContinuousMonoidHom Γ PiBd)
    (hpro2 : Function.Surjective pro2) (hbpro2 : ∀ γ, (b γ).val.2 = pro2 γ)
    (hker : pro2.toMonoidHom.ker = proPKernel 2 Γ) :
    Nat.card (QLifts F T hE2 D b) = Nat.card (CommonLifts F T hE2 D) := by
  haveI hdQ : DiscreteTopology D.Q := D.discreteTopology_Q
  haveI : Finite D.Q := inferInstance
  have hQ : IsProP 2 D.Q := isProP_of_isPGroup D.hQ2
  set E' := compPro2Equiv pro2 hpro2 hker hQ with hE'def
  have happly : ∀ (ψ : ContinuousMonoidHom PiBd D.Q) (γ : Γ), E' ψ γ = ψ (pro2 γ) := by
    intro ψ γ; rw [hE'def]; exact compPro2Equiv_apply_apply pro2 hpro2 hker hQ ψ γ
  apply Nat.card_congr
  refine ⟨fun g => ⟨⟨E'.symm g.1.1, ?_⟩, ?_, ?_⟩, fun g => ⟨⟨E' g.1.1, ?_⟩, ?_, ?_⟩, ?_, ?_⟩
  · -- toFun surjective
    intro q
    obtain ⟨γ, hγ⟩ := g.1.2 q
    exact ⟨pro2 γ, by rw [← happly (E'.symm g.1.1) γ, E'.apply_symm_apply]; exact hγ⟩
  · -- toFun H-condition (indexed by ∂bd)
    intro x
    obtain ⟨γ, hγ⟩ := hb x
    have hx1 : (E'.symm g.1.1) x.val.2 = g.1.1 γ := by
      rw [show x.val.2 = pro2 γ by rw [← hγ]; exact hbpro2 γ,
        ← happly (E'.symm g.1.1) γ, E'.apply_symm_apply]
    rw [hx1, g.2.1 γ, hγ]
  · -- toFun θ-condition (indexed by Π)
    intro π
    obtain ⟨γ, hγ⟩ := hpro2 π
    have hπ : (E'.symm g.1.1) π = g.1.1 γ := by
      rw [← hγ, ← happly (E'.symm g.1.1) γ, E'.apply_symm_apply]
    rw [hπ, g.2.2 γ, hbpro2 γ, hγ]
  · -- invFun surjective
    intro q
    obtain ⟨π, hπ⟩ := g.1.2 q
    obtain ⟨γ, hγ⟩ := hpro2 π
    exact ⟨γ, by rw [happly g.1.1 γ, hγ]; exact hπ⟩
  · -- invFun H-condition (per γ)
    intro γ
    rw [happly g.1.1 γ]
    have h := g.2.1 (b γ)
    rw [hbpro2 γ] at h
    exact h
  · -- invFun θ-condition (per γ)
    intro γ
    rw [happly g.1.1 γ, g.2.2 (pro2 γ), hbpro2 γ]
  · -- left_inv
    intro g; apply Subtype.ext; apply Subtype.ext; exact E'.apply_symm_apply g.1.1
  · -- right_inv
    intro g; apply Subtype.ext; apply Subtype.ext; exact E'.symm_apply_apply g.1.1

end SourceIndependence

open SectionThree in
/-- `ker pro2A = proPKernel 2 Γ_A` for any `BoundaryMaps` `B`: `pro2A` agrees with the
`prop_3_10_gammaA` isomorphism `e ∘ maxProPMk` on the four marked topological generators, hence
equals it, and `e` is injective. -/
theorem ker_pro2A (B : BoundaryMaps) :
    B.pro2A.toMonoidHom.ker = proPKernel 2 GammaA := by
  obtain ⟨e, heσ, heτ, hex0, hex1⟩ := prop_3_10_gammaA
  set eHom : ContinuousMonoidHom GammaA PiBd :=
    (⟨e.toMonoidHom, e.continuous_toFun⟩ :
      ContinuousMonoidHom (maxProPQuotient 2 GammaA) PiBd).comp (maxProPMk 2 GammaA) with heHom
  have heq : ∀ g, B.pro2A g = eHom g := by
    apply monoidHom_eq_of_topGen B.pro2A.continuous_toFun eHom.continuous_toFun topGen_gammaA
    rintro z (rfl | rfl | rfl | rfl)
    · exact B.pro2A_sigma.trans heσ.symm
    · exact B.pro2A_tau.trans heτ.symm
    · exact B.pro2A_x0.trans hex0.symm
    · exact B.pro2A_x1.trans hex1.symm
  ext g
  constructor
  · intro hg
    have hg1 : eHom g = 1 := by rw [← heq g]; exact MonoidHom.mem_ker.mp hg
    have h2 : maxProPMk 2 GammaA g = 1 :=
      e.injective (by show e (maxProPMk 2 GammaA g) = e 1; rw [map_one]; exact hg1)
    exact (quotientMk_eq_one_iff (proPKernel 2 GammaA)).mp h2
  · intro hg
    have h2 : maxProPMk 2 GammaA g = 1 := (quotientMk_eq_one_iff (proPKernel 2 GammaA)).mpr hg
    have h3 : eHom g = 1 := by show e (maxProPMk 2 GammaA g) = 1; rw [h2, map_one]
    exact MonoidHom.mem_ker.mpr (by show B.pro2A g = 1; rw [heq g]; exact h3)

/-! ## The terminal regime  (P-17b) -/

/-- **The terminal case** (§9.1): if every chief factor of `L_Y` is scalar (a trivial
`H`-module — `IsScalarStack`), the two exact-image problems are *identical*: Lemma 9.2
splits `Y ≅ H ×_{H₂} Q` off the odd part of `H` (Schur–Zassenhaus,
`GQ2.FiniteGroup.oddOrder_twoQuotient_split`), the boundary data descend to the finite
2-group `Q` (`θ` kills the odd complement since `E` has exponent 2), and the (144)
correspondence + `coprime_fiber_product` identify boundary-framed maps from either source
with marked maps `Π → Q` — the same set for both sources by the P-25 marked pro-2
isomorphisms.  [P-17a statement; proof P-17b.] -/
theorem terminal_count_eq (B : BoundaryMaps) (F : BoundaryFrame H E)
    [CompactSpace AbsGalQ2] [TotallyDisconnectedSpace AbsGalQ2]
    {Y : Type} [Group Y] [TopologicalSpace Y] [DiscreteTopology Y] [Finite Y]
    (T : MarkedTarget H E Y) (hE2 : ∀ e : E, e ^ 2 = 1)
    (hstack : SectionSeven.IsScalarStack T.LY) :
    exactImageCount B.bA F T = exactImageCount B.bF F T := by
  obtain ⟨M, hMn, hModd, hMtwo⟩ := head_two_nilpotent F
  obtain ⟨Ntil, hNn, hNodd, hNQ2, hNL, _hNcomm, hmapM, hNLsup⟩ :=
    lemma_9_2_core T.piY T.piY_surjective T.LY T.ker_piY T.isPGroup_two hstack M hModd hMtwo
  set D : L92 H Y := ⟨T.piY, T.piY_surjective, T.LY, T.ker_piY, M, hMn, hModd, Ntil, hNn,
    hNodd, hNL, hmapM, hNLsup, hNQ2⟩ with hD
  have hDpi : D.piY = T.piY := by rw [hD]
  have hbA : Function.Surjective B.bA := fun x => by
    obtain ⟨g, hg⟩ := B.surjA x
    exact ⟨g, Subtype.ext (by rw [B.bA_apply_coe]; exact congrArg Subtype.val hg)⟩
  have hbF : Function.Surjective B.bF := fun x => by
    obtain ⟨g, hg⟩ := B.surjF x
    exact ⟨g, Subtype.ext (by rw [B.bF_apply_coe]; exact congrArg Subtype.val hg)⟩
  have hbpro2A : ∀ g, (B.bA g).val.2 = B.pro2A g := fun g => by rw [B.bA_apply_coe]
  have hbpro2F : ∀ g, (B.bF g).val.2 = B.pro2F g := fun g => by rw [B.bF_apply_coe]
  have hpro2A_surj : Function.Surjective B.pro2A := fun p => by
    obtain ⟨t, ht⟩ := SectionThree.nuT_surjective (nuTwo p)
    obtain ⟨g, hg⟩ := B.surjA ⟨(t, p), ht⟩
    exact ⟨g, congrArg (fun x : ↥boundarySubgroup => x.val.2) hg⟩
  show Nat.card (BoundaryLifts B.bA F T) = Nat.card (BoundaryLifts B.bF F T)
  calc Nat.card (BoundaryLifts B.bA F T)
      = Nat.card (QLifts F T hE2 D B.bA) := boundaryLifts_equiv_qlifts F T hE2 D hDpi B.bA hbA
    _ = Nat.card (CommonLifts F T hE2 D) :=
        qlifts_equiv_commonLifts F T hE2 D B.bA hbA B.pro2A hpro2A_surj hbpro2A (ker_pro2A B)
    _ = Nat.card (QLifts F T hE2 D B.bF) :=
        (qlifts_equiv_commonLifts F T hE2 D B.bF hbF B.pro2F B.pro2F_surjective hbpro2F
          B.ker_pro2F).symm
    _ = Nat.card (BoundaryLifts B.bF F T) :=
        (boundaryLifts_equiv_qlifts F T hE2 D hDpi B.bF hbF).symm

/-! ## The κ⁰ base class  (P-17e; Lemma 6.1)

### Reusable structural core (the Lemma 6.3 skeleton)

The paper's *existence* proof for the base class `κ⁰_q` is **Lemma 6.3**, not Lemma 6.1
(Lemma 6.1 only records the equivalence "(59)+(60) ⟺ `E_f` carries a lifted `C`-action" and
*assumes* a lift is chosen).  Lemma 6.3 builds the datum for a **simple self-dual tame** module
`V` by three structural moves, each of which is a self-contained, source-generic fact proved
here; see `docs/p17e-kappa0-scoping.md` for why the *general* `kappa0_exists` below is **not**
a paper theorem (the lift obstruction in `H²(C, V^∨)` need not vanish for an arbitrary module)
and for the honest restatement these lemmas assemble into.

* `isEquivariantFactorSet_of_invariant` — an **invariant** normalized factor set needs no
  corrections (`m = 0`): the paper's orbit factor sets (75)/(76).
* `IsEquivariantFactorSet.add` — the datum of a **sum** `q + q'` is the sum of the data: the
  "sum of the cocycles corresponding to the orbit polynomials occurring in `q_W`" step.
* `IsEquivariantFactorSet.comap` — **pullback** along an equivariant additive map (eq. (77)),
  packaged as `kappa0_exists_of_split` (the Lemma 6.3 reduction to a split embedding). -/


/-- **Pullback** of an equivariant factor-set datum along an equivariant additive map
`i : V →+ W` (eq. (77), datum level): if `i` is `C`-equivariant, then `dat.comap i` is an
equivariant factor-set datum for the pulled-back form `q ∘ i`. -/
theorem IsEquivariantFactorSet.comap {C V W : Type*} [Group C] [AddCommGroup V] [AddCommGroup W]
    [DistribMulAction C V] [DistribMulAction C W] {q : W → ZMod 2} {dat : FactorSet C W}
    (hdat : IsEquivariantFactorSet q dat) (i : V →+ W)
    (hi : ∀ (c : C) (v : V), i (c • v) = c • i v) :
    IsEquivariantFactorSet (fun v => q (i v)) (dat.comap i) where
  f_cocycle v w x := by
    show dat.f (i (v + w)) (i x) + dat.f (i v) (i w) = dat.f (i v) (i (w + x)) + dat.f (i w) (i x)
    rw [map_add, map_add]; exact hdat.f_cocycle (i v) (i w) (i x)
  f_diag v := hdat.f_diag (i v)
  f_polar v w := by
    show dat.f (i v) (i w) + dat.f (i w) (i v) = polar (fun v => q (i v)) v w
    rw [hdat.f_polar (i v) (i w)]; simp only [polar, map_add]
  f_zero_left v := by
    show dat.f (i 0) (i v) = 0
    rw [map_zero]; exact hdat.f_zero_left (i v)
  f_zero_right v := by
    show dat.f (i v) (i 0) = 0
    rw [map_zero]; exact hdat.f_zero_right (i v)
  m_quad c v w := by
    show dat.m c (i (v + w)) + dat.m c (i v) + dat.m c (i w)
       = dat.f (i (c • v)) (i (c • w)) + dat.f (i v) (i w)
    rw [map_add, hi c v, hi c w]; exact hdat.m_quad c (i v) (i w)
  m_mul c d v := by
    show dat.m (c * d) (i v) = dat.m c (i (d • v)) + dat.m d (i v)
    rw [hi d v]; exact hdat.m_mul c d (i v)
  m_one v := hdat.m_one (i v)

/-- **Pullback of an equivariant factor-set datum along a group homomorphism** `π : C →* D`
compatible with the actions (`c • v = π c • v`): `f` is unchanged, `m_c := m_{π c}`.  This is
the reduction of the κ⁰ existence problem to any group the action factors through — e.g. the
faithful tame image of `ActsThroughTame` below (existence over the image gives existence over
`C`), which is how Lemma 6.3's "let `H = H_V` be the faithful tame image" step enters. -/
theorem IsEquivariantFactorSet.comapHom {C D V : Type*} [Group C] [Group D] [AddCommGroup V]
    [DistribMulAction C V] [DistribMulAction D V] {q : V → ZMod 2} {dat : FactorSet D V}
    (hdat : IsEquivariantFactorSet q dat) (π : C →* D)
    (hπ : ∀ (c : C) (v : V), c • v = π c • v) :
    IsEquivariantFactorSet q (⟨dat.f, fun c v => dat.m (π c) v⟩ : FactorSet C V) where
  f_cocycle := hdat.f_cocycle
  f_diag := hdat.f_diag
  f_polar := hdat.f_polar
  f_zero_left := hdat.f_zero_left
  f_zero_right := hdat.f_zero_right
  m_quad c v w := by
    show dat.m (π c) (v + w) + dat.m (π c) v + dat.m (π c) w
       = dat.f (c • v) (c • w) + dat.f v w
    rw [hπ c v, hπ c w]; exact hdat.m_quad (π c) v w
  m_mul c d v := by
    show dat.m (π (c * d)) v = dat.m (π c) (d • v) + dat.m (π d) v
    rw [map_mul, hπ d v]; exact hdat.m_mul (π c) (π d) v
  m_one v := by
    show dat.m (π 1) v = 0
    rw [map_one]; exact hdat.m_one v


/-- The `C`-action on `V` **factors through a finite tame group**: a finite `H` acting on `V`,
generated by a pair `s, t` with the tame relation `s⁻¹ t s = t²` (the finite avatar of a
`Ttame`-quotient, the same interface as `tame_two_nilpotent`), and a *surjective* `π : C →* H`
with `c • v = π c • v`.  Surjectivity makes `H`-data (invariance of `q`, submodule lattice)
agree with `C`-data, so an equivariant factor-set datum over `H` pulls back along
`IsEquivariantFactorSet.comapHom`.  At the P-17d call site this is discharged with `H :=` the
frame head: `K` acts trivially on `V = P/S` by `[K,P] ≤ [P,P] ≤ S`, and the rest of `L_Y`
acts trivially by `FoxH.lemma_5_12` (normal 2-subgroup on a chief factor), so the `C = Y/K`
action descends to `Y/L_Y ≅ H`, whose marked generators satisfy the tame relation. -/
def ActsThroughTame (C : Type*) [Group C] (V : Type*) [AddCommGroup V]
    [DistribMulAction C V] : Prop :=
  ∃ (H : Type) (_ : Group H) (_ : Finite H) (_ : DistribMulAction H V)
    (π : C →* H) (s t : H),
    Function.Surjective π ∧ (∀ (c : C) (v : V), c • v = π c • v) ∧
    Subgroup.closure {s, t} = ⊤ ∧ s⁻¹ * t * s = t ^ 2

/-- Every element of `𝔽₂` is `0` or `1` (kernel-`decide`d at top level, where the context is
free of the `V`/`q` variables that would otherwise trip `decide`'s free-variable guard). -/
private theorem zmod_two_cases : ∀ b : ZMod 2, b = 0 ∨ b = 1 := by decide


/-! ### The orbit factor sets are equivariant (P-17e2; Lemma 6.3's (75)/(76))

The concrete `m = 0` orbit data from `GQ2/OrbitData.lean` are `IsEquivariantFactorSet` for their
square maps: biadditive in the coordinates, and `G/N`-invariant because the left-regular action
merely permutes coordinates (`finsum_comp_equiv` along `Equiv.mulLeft`).  Entry point:
`isEquivariantFactorSet_of_biadditive_invariant` (now polar-free). -/


/-- **Existence of the equivariant factor-set datum** (the base determinant class `κ⁰_q`) —
**the paper's Lemma 6.3**, p. 26: a `C`-invariant nonsingular quadratic form on a **simple tame**
`𝔽₂[C]`-module admits a normalized equivariant factor-set datum.  (Self-duality is implied:
`hns` + `hinv` make `v ↦ polar q v ·` a `C`-isomorphism `V ≅ V^∨`.)

**Reviewed statement amendment (P-17e escalation, resolved 2026-07-06 — deviation ledger
`docs/p17e-kappa0-scoping.md`)**: the P-17a form omitted `hsimple`/`htame`, making the statement
*stronger than the paper's* and in fact **false** — Lemma 6.1 only proves the equivalence
"(59)+(60) ⟺ `E_f` carries a lifted `C`-action" and *assumes* the lift exists; a datum is
exactly a splitting of `1 → V^∨ → Aut_Z(E_f) → O(q) → 1` pulled back along `ρ : C → O(q)`, and
for `C = O(q)` itself that extension is **non-split** for large extraspecial `E_f` (Griess,
Pacific J. Math. 48 (1973)).  The added hypotheses are Lemma 6.3's own, are dischargeable at the
sole call site (P-17d, see `ActsThroughTame`'s docstring), and restore truth via the paper's
construction: reduce to the faithful tame image (`comapHom`), split-embed `V` into a permutation
module (Lemma 6.11 / Maschke — projectivity is where simplicity+tameness are consumed), decompose
the extended form into orbit polynomials, and sum their explicit data ((75)/(76)/Lemma 6.2) —
the proved lemmas above are exactly these assembly steps.
[P-17a statement, amended P-17e.  **PROVED (P-17e5)**: unpack `htame`, transport
invariance/simplicity along the surjection, apply `GQ2.kappa0_exists_tame`
(`GQ2/KappaNormalForm.lean` — faithful-image reduction, the odd/unramified averaging branch,
and the ramified branch through `lemma_6_11_of_tame_pair` + the permutation-module normal
form), and pull back with `comapHom`.] -/
theorem kappa0_exists {C : Type} [Group C] [Finite C]
    {V : Type} [AddCommGroup V] [Finite V] [DistribMulAction C V]
    (q : V → ZMod 2) (hq : IsQuadraticFp2 q) (hns : Nonsingular q)
    (hinv : IsInvariant C q) (hsimple : FoxH.IsSimpleModTwo C V)
    (htame : ActsThroughTame C V) :
    ∃ dat : FactorSet C V, IsEquivariantFactorSet q dat := by
  obtain ⟨H, hG, hF, hA, π, s, t, hπsurj, hπcompat, hgen, hrel⟩ := htame
  letI := hG
  letI := hF
  letI := hA
  -- transport invariance and simplicity along the surjection `π`
  have hinvH : IsInvariant H q := by
    intro h v
    obtain ⟨c, rfl⟩ := hπsurj h
    rw [← hπcompat, hinv]
  have hsimpleH : ∀ W : AddSubgroup V,
      (∀ (g : H) (w : V), w ∈ W → g • w ∈ W) → W = ⊥ ∨ W = ⊤ := by
    intro W hW
    refine hsimple.2 W fun g w hw => ?_
    rw [hπcompat]
    exact hW (π g) w hw
  obtain ⟨dat, hdat⟩ :=
    kappa0_exists_tame hgen hrel q hq hns hinvH hsimple.1 hsimpleH
  exact ⟨_, IsEquivariantFactorSet.comapHom hdat π hπcompat⟩

/-! ## The concrete block frame and enrichment  (P-17c, P-17d)

The §7 block `Blk` on a target `T` determines the recursion frame of §8 concretely:
`B = Y/R`, `C = Y/K` with the boundary data descended through `lemma_7_3` (this is where
`hE2` enters), `D_R` = the kernel-encoded scalar characters (`card_DR`'s subtype itself),
and the scalar covers `p_λ = Y/R' ↠ Y/R`.  The enrichment fields are the §7.4 outputs:
`q_λ` via `prop_7_4` + `mForm_of_qbar` (P-16d1), quadraticity/nonsingularity of `q̄_λ`
derived from the block (design routes in `docs/section9-extraction.md`), the descended
module from `GQ2/BlockModule.lean`'s `blockAction`, and the κ⁰ datum from `kappa0_exists`.
Spec and size lemmas about these constructions (the (145)/(148)/(153) bounds, Lemma 9.4)
are P-17g, stated per the design note. -/

/-- **The concrete recursion frame of the block** (P-17c).  `R = ⊥` is allowed (the frame
is then degenerate; the induction's `R = ⊥` lane uses `mStage_partition` instead of
`prop_8_9`). -/
noncomputable def blockFrame {Y : Type} [Group Y] [TopologicalSpace Y] [DiscreteTopology Y]
    [Finite Y] (T : MarkedTarget H E Y) (Blk : SectionSeven.MinimalBlock T.LY)
    (hE2 : ∀ e : E, e ^ 2 = 1) : RecursionFrame T Blk :=
  blockFrameImpl T Blk hE2

/- **The concrete enrichment of the block frame** (P-17d): the per-`λ` §7.4 square-form data
and the descended κ⁰ datum, discharging `prop_8_9`'s `En` hypothesis.  **Defined in
`GQ2/BlockEnrichment.lean`** (`SectionNine.blockEnrichment`, P-17d3) — it must sit downstream of
this file because it consumes `kappa0_exists`/`ActsThroughTame`; its signature gains
`F : BoundaryFrame H E` (supplying `cH := F.alpha` for `prop_7_4` and the tame generators for
`htame`).  Axiom-clean modulo `kappa0_exists` (P-17e). -/

/-! ## The elementary `M`-stage partition  (P-17f; §9.2, the `R = ⊥` lane) -/

/-- Stages (A)+(B) of `mStage_partition`: the boundary-lift set `Mset` (unrestricted `B`-lifts
whose `C`-projection is a boundary-framed surjection) fibres over its `C`-image, and the
`LiftsOver`-fibration collapses through the uniform multiplicity `hmult` to `mult · e_Γ(C)`. -/
private theorem mStage_Mset_card_eq_mult {Y : Type} [Group Y] [TopologicalSpace Y]
    [DiscreteTopology Y] [Finite Y] {T : MarkedTarget H E Y}
    {Blk : SectionSeven.MinimalBlock T.LY} (RF : RecursionFrame T Blk) {Γ : Type} [Group Γ]
    [TopologicalSpace Γ] [IsTopologicalGroup Γ] [CompactSpace Γ] [TotallyDisconnectedSpace Γ]
    (hfg : ∃ s : Finset Γ, (Subgroup.closure (s : Set Γ)).topologicalClosure = ⊤)
    (b : ContinuousMonoidHom Γ ↥boundarySubgroup) (F : BoundaryFrame H E) (mult : ℕ)
    (hmult : ∀ ρ : BoundaryLifts b F RF.TC, Nat.card (RF.LiftsOver b F ρ) = mult) :
    Nat.card {m : ContinuousMonoidHom Γ RF.YB //
        IsBoundaryLift b F RF.TB m ∧ Function.Surjective (⇑RF.piBC ∘ ⇑m)}
      = mult * exactImageCount b F RF.TC := by
  classical
  haveI : Finite (ContinuousMonoidHom Γ RF.YB) := finite_continuousMonoidHom hfg RF.YB
  haveI : Finite (BoundaryLifts b F RF.TC) := finite_boundaryLifts b F RF.TC hfg
  haveI : Fintype (BoundaryLifts b F RF.TC) := Fintype.ofFinite _
  have hheadBC : RF.TC.piY.comp RF.piBC = RF.TB.piY := RF.headBC
  have hthetaBC : RF.TC.thetaY.comp RF.piBC = RF.TB.thetaY := RF.thetaBC
  set Mset := {m : ContinuousMonoidHom Γ RF.YB //
    IsBoundaryLift b F RF.TB m ∧ Function.Surjective (⇑RF.piBC ∘ ⇑m)} with hMsetdef
  haveI : Finite Mset := Subtype.finite
  -- (A) the `LiftsOver`-fibration collapses by `hmult` (the `half139_of` pattern)
  have hmultsum : ∑ ρ : BoundaryLifts b F RF.TC, Nat.card (RF.LiftsOver b F ρ)
      = mult * exactImageCount b F RF.TC := by
    rw [Finset.sum_congr rfl (fun ρ _ => hmult ρ), Finset.sum_const, Finset.card_univ,
      smul_eq_mul, exactImageCount, Nat.card_eq_fintype_card]
    exact mul_comm _ _
  -- (B) `Mset` fibres over the `C`-image `ρ`, the fibre being `LiftsOver ρ`
  have eUnion : Nat.card Mset = ∑ ρ : BoundaryLifts b F RF.TC, Nat.card (RF.LiftsOver b F ρ) := by
    set Φ : Mset → BoundaryLifts b F RF.TC := fun m =>
      ⟨⟨⟨RF.piBC.comp m.1.toMonoidHom,
          (continuous_of_discreteTopology (f := ⇑RF.piBC)).comp m.1.continuous_toFun⟩, m.2.2⟩,
        fun γ => by
          show (RF.TC.piY (RF.piBC (m.1 γ)), RF.TC.thetaY (RF.piBC (m.1 γ))) = F.frameMap (b γ)
          have h1 : RF.TC.piY (RF.piBC (m.1 γ)) = RF.TB.piY (m.1 γ) := by
            rw [show RF.TC.piY (RF.piBC (m.1 γ)) = (RF.TC.piY.comp RF.piBC) (m.1 γ) from rfl,
              hheadBC]
          have h2 : RF.TC.thetaY (RF.piBC (m.1 γ)) = RF.TB.thetaY (m.1 γ) := by
            rw [show RF.TC.thetaY (RF.piBC (m.1 γ)) = (RF.TC.thetaY.comp RF.piBC) (m.1 γ) from rfl,
              hthetaBC]
          rw [h1, h2]
          exact m.2.1 γ⟩ with hΦdef
    rw [Nat.card_congr (Equiv.sigmaFiberEquiv Φ).symm, Nat.card_sigma]
    refine Finset.sum_congr rfl (fun ρ _ => Nat.card_congr ?_)
    exact
      { toFun := fun mm =>
          ⟨mm.1.1, fun γ => congrArg (fun x : BoundaryLifts b F RF.TC => x.1.1 γ) mm.2⟩
        invFun := fun n =>
          ⟨⟨n.1, RF.isBoundaryLift_of_over b F n.1 ρ n.2,
              by rw [show (⇑RF.piBC ∘ ⇑n.1) = ⇑ρ.1.1 from funext n.2]; exact ρ.1.2⟩,
            Subtype.ext (Subtype.ext (ContinuousMonoidHom.ext fun γ => n.2 γ))⟩
        left_inv := fun mm => Subtype.ext (Subtype.ext rfl)
        right_inv := fun n => Subtype.ext rfl }
  rw [eUnion]; exact hmultsum

/-- Stage (C), `C`-onto head-surjective stratum: the exact-image fibre of `Mset` over a subgroup
`J ↠ C` that is head-surjective counts the boundary-framed exact-image lifts of the stratum
`T_B|_J` (the `partition137_of`/`lemma_8_3` image-stratification). -/
private theorem mStage_stratum_fiber_card {Y : Type} [Group Y] [TopologicalSpace Y]
    [DiscreteTopology Y] [Finite Y] {T : MarkedTarget H E Y}
    {Blk : SectionSeven.MinimalBlock T.LY} (RF : RecursionFrame T Blk) {Γ : Type} [Group Γ]
    [TopologicalSpace Γ] [IsTopologicalGroup Γ] [CompactSpace Γ] [TotallyDisconnectedSpace Γ]
    (b : ContinuousMonoidHom Γ ↥boundarySubgroup) (F : BoundaryFrame H E) (J : Subgroup RF.YB)
    (hJc : J.map RF.piBC = ⊤) (hJh : Function.Surjective (RF.TB.piY.comp J.subtype)) :
    Nat.card {m : {n : ContinuousMonoidHom Γ RF.YB //
          IsBoundaryLift b F RF.TB n ∧ Function.Surjective (⇑RF.piBC ∘ ⇑n)} //
        m.1.toMonoidHom.range = J}
      = exactImageCount b F (RF.TB.stratum J hJh) := by
  classical
  rw [exactImageCount]
  have hmem : ∀ (m : {n : ContinuousMonoidHom Γ RF.YB //
      IsBoundaryLift b F RF.TB n ∧ Function.Surjective (⇑RF.piBC ∘ ⇑n)}),
      m.1.toMonoidHom.range = J → ∀ γ, m.1 γ ∈ J := by
    intro m hm γ
    have : m.1 γ ∈ m.1.toMonoidHom.range := ⟨γ, rfl⟩
    rwa [hm] at this
  refine Nat.card_congr ⟨fun m =>
    ⟨⟨cmhCodRestrict m.1.1 J (hmem m.1 m.2), fun j => ?_⟩, fun γ => ?_⟩,
    fun f => ⟨⟨cmhInclude J f.1.1, fun γ => f.2 γ, ?_⟩, ?_⟩,
    fun m => Subtype.ext (Subtype.ext rfl),
    fun f => Subtype.ext (Subtype.ext (ContinuousMonoidHom.ext fun γ => Subtype.ext rfl))⟩
  · -- corestriction surjective onto `↥J`
    have hj : (j : RF.YB) ∈ m.1.1.toMonoidHom.range := by rw [m.2]; exact j.2
    obtain ⟨γ, hγ⟩ := hj
    exact ⟨γ, Subtype.ext hγ⟩
  · -- stratum boundary equation (definitional transport)
    exact m.1.2.1 γ
  · -- `C`-surjectivity of the included map, from `J ↠ C`
    intro c
    have hc : c ∈ J.map RF.piBC := by rw [hJc]; trivial
    obtain ⟨y, hyJ, hyc⟩ := Subgroup.mem_map.mp hc
    obtain ⟨γ, hγ⟩ := f.1.2 ⟨y, hyJ⟩
    exact ⟨γ, by show RF.piBC ((f.1.1 γ : RF.YB)) = c; rw [hγ, hyc]⟩
  · -- the included map has range exactly `J`
    have h1 : (cmhInclude J f.1.1).toMonoidHom.range
        = f.1.1.toMonoidHom.range.map J.subtype := MonoidHom.range_comp _ _
    rw [h1, MonoidHom.range_eq_top.mpr f.1.2, ← MonoidHom.range_eq_map,
      Subgroup.range_subtype]

/-- Stage (C), `C`-missing stratum: a subgroup `J` that does not surject onto `C` has empty
exact-image fibre in `Mset` (each `Mset`-member is `C`-onto, so its range is too). -/
private theorem mStage_fiber_empty_of_not_onto {Y : Type} [Group Y] [TopologicalSpace Y]
    [DiscreteTopology Y] [Finite Y] {T : MarkedTarget H E Y}
    {Blk : SectionSeven.MinimalBlock T.LY} (RF : RecursionFrame T Blk) {Γ : Type} [Group Γ]
    [TopologicalSpace Γ] [IsTopologicalGroup Γ] [CompactSpace Γ] [TotallyDisconnectedSpace Γ]
    (b : ContinuousMonoidHom Γ ↥boundarySubgroup) (F : BoundaryFrame H E) (J : Subgroup RF.YB)
    (hJc : J.map RF.piBC ≠ ⊤) :
    Nat.card {m : {n : ContinuousMonoidHom Γ RF.YB //
          IsBoundaryLift b F RF.TB n ∧ Function.Surjective (⇑RF.piBC ∘ ⇑n)} //
        m.1.toMonoidHom.range = J} = 0 := by
  classical
  have hE : IsEmpty {m : {n : ContinuousMonoidHom Γ RF.YB //
      IsBoundaryLift b F RF.TB n ∧ Function.Surjective (⇑RF.piBC ∘ ⇑n)} //
      m.1.toMonoidHom.range = J} := by
    constructor
    rintro ⟨m, hm⟩
    apply hJc
    rw [← hm, ← MonoidHom.range_comp, MonoidHom.range_eq_top]
    intro c
    obtain ⟨γ, hγ⟩ := m.2.2 c
    exact ⟨γ, hγ⟩
  exact Nat.card_of_isEmpty

/-- Stage (C), head-missing stratum: under the head-surjectivity hypothesis `hhead`, a subgroup
`J` whose head projection misses `C` has empty exact-image fibre in `Mset`. -/
private theorem mStage_fiber_empty_of_not_head {Y : Type} [Group Y] [TopologicalSpace Y]
    [DiscreteTopology Y] [Finite Y] {T : MarkedTarget H E Y}
    {Blk : SectionSeven.MinimalBlock T.LY} (RF : RecursionFrame T Blk) {Γ : Type} [Group Γ]
    [TopologicalSpace Γ] [IsTopologicalGroup Γ] [CompactSpace Γ] [TotallyDisconnectedSpace Γ]
    (b : ContinuousMonoidHom Γ ↥boundarySubgroup) (F : BoundaryFrame H E)
    (hhead : Function.Surjective (fun γ : Γ => (F.frameMap (b γ)).1)) (J : Subgroup RF.YB)
    (hJh : ¬ Function.Surjective (RF.TB.piY.comp J.subtype)) :
    Nat.card {m : {n : ContinuousMonoidHom Γ RF.YB //
          IsBoundaryLift b F RF.TB n ∧ Function.Surjective (⇑RF.piBC ∘ ⇑n)} //
        m.1.toMonoidHom.range = J} = 0 := by
  classical
  have hE : IsEmpty {m : {n : ContinuousMonoidHom Γ RF.YB //
      IsBoundaryLift b F RF.TB n ∧ Function.Surjective (⇑RF.piBC ∘ ⇑n)} //
      m.1.toMonoidHom.range = J} := by
    constructor
    rintro ⟨m, hm⟩
    apply hJh
    intro hh
    obtain ⟨γ, hγ⟩ := hhead hh
    have hmemJ : m.1 γ ∈ J := by
      have : m.1 γ ∈ m.1.toMonoidHom.range := ⟨γ, rfl⟩
      rwa [hm] at this
    refine ⟨⟨m.1 γ, hmemJ⟩, ?_⟩
    show RF.TB.piY (m.1 γ) = hh
    have hbd := m.2.1 γ
    have := congrArg Prod.fst hbd
    simpa [hγ] using this
  exact Nat.card_of_isEmpty

/-- Stage (C) of `mStage_partition`: `Mset` stratifies by exact image into the `C`-onto strata
of `T_B`, assembling the three fibre classifications (`mStage_stratum_fiber_card`,
`mStage_fiber_empty_of_not_onto`, `mStage_fiber_empty_of_not_head`). -/
private theorem mStage_Mset_card_eq_finsum {Y : Type} [Group Y] [TopologicalSpace Y]
    [DiscreteTopology Y] [Finite Y] {T : MarkedTarget H E Y}
    {Blk : SectionSeven.MinimalBlock T.LY} (RF : RecursionFrame T Blk) {Γ : Type} [Group Γ]
    [TopologicalSpace Γ] [IsTopologicalGroup Γ] [CompactSpace Γ] [TotallyDisconnectedSpace Γ]
    (hfg : ∃ s : Finset Γ, (Subgroup.closure (s : Set Γ)).topologicalClosure = ⊤)
    (b : ContinuousMonoidHom Γ ↥boundarySubgroup) (F : BoundaryFrame H E)
    (hhead : Function.Surjective (fun γ : Γ => (F.frameMap (b γ)).1)) :
    Nat.card {m : ContinuousMonoidHom Γ RF.YB //
        IsBoundaryLift b F RF.TB m ∧ Function.Surjective (⇑RF.piBC ∘ ⇑m)}
      = ∑ᶠ J ∈ {J : Subgroup RF.YB | J.map RF.piBC = ⊤}, exactImageCountOn b F RF.TB J := by
  classical
  haveI : Finite (ContinuousMonoidHom Γ RF.YB) := finite_continuousMonoidHom hfg RF.YB
  haveI : Finite (Subgroup RF.YB) :=
    Finite.of_injective (fun J : Subgroup RF.YB => (J : Set RF.YB)) SetLike.coe_injective
  haveI : Fintype (Subgroup RF.YB) := Fintype.ofFinite _
  set Mset := {m : ContinuousMonoidHom Γ RF.YB //
    IsBoundaryLift b F RF.TB m ∧ Function.Surjective (⇑RF.piBC ∘ ⇑m)} with hMsetdef
  -- stratify `Mset` by the exact image `range m`
  have e2 : Nat.card Mset
      = ∑ J : Subgroup RF.YB, Nat.card {m : Mset // m.1.toMonoidHom.range = J} := by
    rw [Nat.card_congr (Equiv.sigmaFiberEquiv
      (fun m : Mset => m.1.toMonoidHom.range)).symm, Nat.card_sigma]
  set fib : Subgroup RF.YB → ℕ :=
    fun J => Nat.card {m : Mset // m.1.toMonoidHom.range = J} with hfibdef
  set S : Finset (Subgroup RF.YB) :=
    Finset.univ.filter (fun J => J.map RF.piBC = ⊤) with hSdef
  -- assemble: restrict to `S`, match `fib` to `exactImageCountOn`, convert to `finsum`
  have hStep : (∑ J : Subgroup RF.YB, fib J) = ∑ J ∈ S, fib J := by
    rw [hSdef, ← Finset.sum_filter_add_sum_filter_not Finset.univ
      (fun J => J.map RF.piBC = ⊤) fib]
    have hz : ∑ J ∈ Finset.univ.filter (fun J => ¬ J.map RF.piBC = ⊤), fib J = 0 :=
      Finset.sum_eq_zero (fun J hJ =>
        mStage_fiber_empty_of_not_onto RF b F J (Finset.mem_filter.mp hJ).2)
    rw [hz, add_zero]
  have hmatch : ∀ J ∈ S, fib J = exactImageCountOn b F RF.TB J := by
    intro J hJ
    rw [hSdef, Finset.mem_filter] at hJ
    obtain ⟨_, hJc⟩ := hJ
    by_cases hJh : Function.Surjective (RF.TB.piY.comp J.subtype)
    · simp only [exactImageCountOn, dif_pos hJh]
      exact mStage_stratum_fiber_card RF b F J hJc hJh
    · simp only [exactImageCountOn, dif_neg hJh]
      exact mStage_fiber_empty_of_not_head RF b F hhead J hJh
  have hsetconv : {J : Subgroup RF.YB | J.map RF.piBC = ⊤} = ↑S := by
    rw [hSdef]; ext J; simp
  have hfinsum : ∑ᶠ J ∈ {J : Subgroup RF.YB | J.map RF.piBC = ⊤},
        exactImageCountOn b F RF.TB J
      = ∑ J ∈ S, exactImageCountOn b F RF.TB J := by
    rw [hsetconv, finsum_mem_coe_finset]
  rw [e2, hStep, Finset.sum_congr rfl hmatch]
  exact hfinsum.symm

/-- **The `M`-stage partition** (§9.2): the unrestricted `B`-lifts of the lower exact-image
maps, all with the same multiplicity `mult` over each lower map (`hmult` — the
`|Z¹_{Γ,ρ}(M)| = 2^{2·dim M}` numerics of props 5.15/5.16, source-discharged at P-17i),
partition by exact image into the `C`-onto strata of `T_B`:
`mult · e_Γ(C) = Σ_{J ↠ C} e_Γ(stratum J)`.  Machinery: the `LiftsOver`-fibration of
P-16d3 + the image-stratification of `partition137_of`/`lemma_8_3`.
[P-17a statement; proof P-17f.] -/
theorem mStage_partition {Y : Type} [Group Y] [TopologicalSpace Y] [DiscreteTopology Y]
    [Finite Y] {T : MarkedTarget H E Y} {Blk : SectionSeven.MinimalBlock T.LY}
    (RF : RecursionFrame T Blk) {Γ : Type} [Group Γ] [TopologicalSpace Γ]
    [IsTopologicalGroup Γ] [CompactSpace Γ] [TotallyDisconnectedSpace Γ]
    (hfg : ∃ s : Finset Γ, (Subgroup.closure (s : Set Γ)).topologicalClosure = ⊤)
    (b : ContinuousMonoidHom Γ ↥boundarySubgroup) (F : BoundaryFrame H E)
    (hhead : Function.Surjective (fun γ : Γ => (F.frameMap (b γ)).1))
    (mult : ℕ)
    (hmult : ∀ ρ : BoundaryLifts b F RF.TC, Nat.card (RF.LiftsOver b F ρ) = mult) :
    mult * exactImageCount b F RF.TC
      = ∑ᶠ J ∈ {J : Subgroup RF.YB | J.map RF.piBC = ⊤},
          exactImageCountOn b F RF.TB J := by
  classical
  rw [← mStage_Mset_card_eq_mult RF hfg b F mult hmult]
  exact mStage_Mset_card_eq_finsum RF hfg b F hhead

/-! ## The recursion solver  (P-17h) -/

/-- **Solving the closed recursion** (the §9.3 bookkeeping): two sources satisfying the
boxed system (136)–(140) for the *same* frame and the *same* shared data `(μ, G⁰, D_T,
phase)` have equal exact-image counts at the top, provided the strictly-smaller ingredient
counts agree — the atoms the induction hypothesis supplies:

* `hTB`/`hTC` — the quotient-stage counts (`|L_B|, |L_C| < |L_Y|`);
* `hpull` — the (138) pullback-stratum counts at every scalar cover, restricted to the
  strata over **proper `C`-onto** images (the only ones (137) consumes; exactly the (148)
  regime, kernels `≤ 2|J ∩ L_B| ≤ |L_B| < |L_Y|` — for an improper image the pulled kernel
  can equal `|L_Y|` at `|R| = 2`, so an unrestricted atom would be un-suppliable by the
  induction) [restriction added P-17i, documented];
* `hphase` — the phase-cover liftable counts (derived at P-17i from `lemma_8_3` at the
  phase covers + the (153) bound `2|L_C| < |L_Y|`; here taken as an atom).

Derivation: (138) + `hpull` give the `m_J` agreement (cancel 8); (139)/(140) + `hTC` +
`hphase` give the `Z_{B/C}` agreement (cancel `2`, resp. `2·#D_T ≠ 0`); (137) then gives
the `m_B` agreement; (136) + `#D_R ≠ 0` gives the top count.  Pure `ℤ`-arithmetic.
[P-17a statement; proof P-17h.] -/
theorem count_eq_of_closedRecursion {Y : Type} [Group Y] [TopologicalSpace Y]
    [DiscreteTopology Y] [Finite Y] {T : MarkedTarget H E Y}
    {Blk : SectionSeven.MinimalBlock T.LY} (RF : RecursionFrame T Blk)
    {Γ₁ : Type} [Group Γ₁] [TopologicalSpace Γ₁]
    {Γ₂ : Type} [Group Γ₂] [TopologicalSpace Γ₂]
    (b₁ : ContinuousMonoidHom Γ₁ ↥boundarySubgroup)
    (b₂ : ContinuousMonoidHom Γ₂ ↥boundarySubgroup)
    (F : BoundaryFrame H E) (μ : ℕ) (G0 : ℤ) (DT : Type) [Fintype DT]
    (phase : (l : RF.DR) → l ≠ RF.zeroDR → DT → CentralCover RF.YC)
    (h₁ : ClosedRecursion RF b₁ F μ G0 DT phase)
    (h₂ : ClosedRecursion RF b₂ F μ G0 DT phase)
    (hDT : Nat.card DT ≠ 0)
    (hTB : exactImageCount b₁ F RF.TB = exactImageCount b₂ F RF.TB)
    (hTC : exactImageCount b₁ F RF.TC = exactImageCount b₂ F RF.TC)
    (hpull : ∀ (l : RF.DR) (h : l ≠ RF.zeroDR) (J' : Subgroup (RF.scalarCover l h).cover),
      J'.map (RF.scalarCover l h).p ≠ ⊤ → (J'.map (RF.scalarCover l h).p).map RF.piBC = ⊤ →
      exactImageCountOn b₁ F ((RF.scalarCover l h).pullTarget RF.TB) J'
        = exactImageCountOn b₂ F ((RF.scalarCover l h).pullTarget RF.TB) J')
    (hphase : ∀ (l : RF.DR) (h : l ≠ RF.zeroDR) (ζ : DT),
      RF.nPhase b₁ F (phase l h ζ) = RF.nPhase b₂ F (phase l h ζ)) :
    exactImageCount b₁ F T = exactImageCount b₂ F T := by
  classical
  -- (138) + `hpull`: the proper `C`-onto stratum counts `m_J` agree (cancel the `8`), hence
  -- so do `mJOn` (only these instances are consumed by (137) below)
  have hmJOn : ∀ (l : RF.DR) (hl : l ≠ RF.zeroDR) (J : Subgroup RF.YB),
      J ≠ ⊤ → J.map RF.piBC = ⊤ →
      RF.mJOn b₁ F l hl J = RF.mJOn b₂ F l hl J := by
    intro l hl J hJne hJC
    simp only [RecursionFrame.mJOn]
    by_cases hJ : Function.Surjective (RF.TB.piY.comp J.subtype)
    · rw [dif_pos hJ, dif_pos hJ]
      have h8 : 8 * RF.mJ b₁ F l hl J hJ = 8 * RF.mJ b₂ F l hl J hJ := by
        rw [h₁.eq138 l hl J hJ, h₂.eq138 l hl J hJ]
        refine finsum_mem_congr rfl (fun J' hJ' => ?_)
        have hJ'' : J'.map (RF.scalarCover l hl).p = J := hJ'
        exact hpull l hl J' (by rw [hJ'']; exact hJne) (by rw [hJ'']; exact hJC)
      omega
    · rw [dif_neg hJ, dif_neg hJ]
  -- (139)/(140): the compatible-lift counts `zBC` agree (case split on the descent-∃)
  have hzBC : ∀ (l : RF.DR) (hl : l ≠ RF.zeroDR),
      RF.zBC b₁ F l hl = RF.zBC b₂ F l hl := by
    intro l hl
    by_cases hdesc : ∃ N : Subgroup (RF.scalarCover l hl).cover, N.Normal ∧
        N.map (RF.scalarCover l hl).p = RF.TBsub ∧ (RF.scalarCover l hl).z ∉ N
    · -- descent: (140), cancel `2·#DT ≠ 0`
      have hns : (∑ᶠ ζ : DT,
            (2 * (RF.nPhase b₁ F (phase l hl ζ) : ℤ) - (exactImageCount b₁ F RF.TC : ℤ)))
          = ∑ᶠ ζ : DT,
            (2 * (RF.nPhase b₂ F (phase l hl ζ) : ℤ) - (exactImageCount b₂ F RF.TC : ℤ)) :=
        finsum_congr (fun ζ => by rw [hphase l hl ζ, hTC])
      have hcancel : 2 * (Nat.card DT : ℤ) * (RF.zBC b₁ F l hl : ℤ)
          = 2 * (Nat.card DT : ℤ) * (RF.zBC b₂ F l hl : ℤ) := by
        rw [h₁.eq140 l hl hdesc, h₂.eq140 l hl hdesc, hns, hTC]
      have hne : (2 : ℤ) * (Nat.card DT : ℤ) ≠ 0 :=
        mul_ne_zero two_ne_zero (Nat.cast_ne_zero.mpr hDT)
      exact_mod_cast mul_left_cancel₀ hne hcancel
    · -- no descent: (139), cancel `2`
      have hcancel : 2 * RF.zBC b₁ F l hl = 2 * RF.zBC b₂ F l hl := by
        rw [h₁.eq139 l hl hdesc, h₂.eq139 l hl hdesc, hTC]
      omega
  -- (137) + `mB(0) = e(T_B)`: the top-stratum counts `m_B` agree
  have hmB : ∀ l : RF.DR, RF.mB b₁ F l = RF.mB b₂ F l := by
    intro l
    by_cases hl : l = RF.zeroDR
    · subst hl
      simp only [RecursionFrame.mB]
      exact hTB
    · have hsum : (∑ᶠ J ∈ {J : Subgroup RF.YB | J ≠ ⊤ ∧ J.map RF.piBC = ⊤},
            (RF.mJOn b₁ F l hl J : ℤ))
          = ∑ᶠ J ∈ {J : Subgroup RF.YB | J ≠ ⊤ ∧ J.map RF.piBC = ⊤},
            (RF.mJOn b₂ F l hl J : ℤ) :=
        finsum_mem_congr rfl (fun J hJmem => by
          obtain ⟨hJne, hJC⟩ := hJmem
          rw [hmJOn l hl J hJne hJC])
      have hz : (RF.zBC b₁ F l hl : ℤ) = (RF.zBC b₂ F l hl : ℤ) := by rw [hzBC l hl]
      have hcast : (RF.mB b₁ F l : ℤ) = (RF.mB b₂ F l : ℤ) := by
        have h137 : (RF.mB b₁ F l : ℤ)
            + ∑ᶠ J ∈ {J : Subgroup RF.YB | J ≠ ⊤ ∧ J.map RF.piBC = ⊤},
                (RF.mJOn b₁ F l hl J : ℤ)
            = (RF.mB b₂ F l : ℤ)
            + ∑ᶠ J ∈ {J : Subgroup RF.YB | J ≠ ⊤ ∧ J.map RF.piBC = ⊤},
                (RF.mJOn b₂ F l hl J : ℤ) := by
          rw [← h₁.eq137 l hl, ← h₂.eq137 l hl, hz]
        rw [hsum] at h137
        exact add_right_cancel h137
      exact_mod_cast hcast
  -- (136): the top counts `e(T)` agree (cancel `#D_R ≠ 0`)
  have hDRne : (Nat.card RF.DR : ℤ) ≠ 0 := by
    have h : Nat.card RF.DR ≠ 0 := Nat.card_ne_zero.mpr ⟨⟨RF.zeroDR⟩, inferInstance⟩
    exact_mod_cast h
  have hrhs : (RF.zR : ℤ) * ∑ᶠ l : RF.DR,
        (2 * (RF.mB b₁ F l : ℤ) - exactImageCount b₁ F RF.TB)
      = (RF.zR : ℤ) * ∑ᶠ l : RF.DR,
        (2 * (RF.mB b₂ F l : ℤ) - exactImageCount b₂ F RF.TB) := by
    congr 1
    exact finsum_congr (fun l => by rw [hmB l, hTB])
  have hcast : (exactImageCount b₁ F T : ℤ) = (exactImageCount b₂ F T : ℤ) := by
    refine mul_left_cancel₀ hDRne ?_
    rw [h₁.eq136, h₂.eq136, hrhs]
  exact_mod_cast hcast

end SectionNine

/-! ## Theorem 4.2 — moved to `GQ2/ThmFourTwo.lean`  (P-17i relocation, second hop)

The statements `GQ2.thm_4_2` and `GQ2.thm_4_2_stratum` (with the P-17i proof: induction
scaffold + terminal + `M`-stage lanes) **moved to `GQ2/ThmFourTwo.lean`**: the `R`-stage lane
consumes `prop_8_9` (`Prop89Close`) and `SectionNine.blockEnrichment` (`BlockEnrichment`,
*downstream* of this file — it consumes `kappa0_exists`), so the proof cannot live here.
Fully qualified names are unchanged (`GQ2.thm_4_2`); consumers import `GQ2.ThmFourTwo`.
[First hop was `BoundaryFrame → SectionNine`, P-17a.]  This file is sorry-free as of the
move. -/

end GQ2

/-! ### Paper-tag ledger (auto-generated by paperforge; do not edit)

  * eq. (143) = ⟦eq-pointwiseconstrained⟧
  * eq. (77) = ⟦eq-basepullback⟧
  * Lemma 3.1 = ⟦lem-tamefinite⟧
  * Lemma 6.1 = ⟦lem-extraspecialconnecting⟧
  * Lemma 6.11 = ⟦lem-faithfulprojective⟧
  * Lemma 6.2 = ⟦lem-halforbitcocycle⟧
  * Lemma 6.3 = ⟦lem-basedetclass⟧
  * Lemma 9.1 = ⟦lem-coprimesubdirect⟧
  * Lemma 9.2 = ⟦lem-scalarterminal⟧
  * Lemma 9.4 = ⟦lem-strictdecrease⟧ (= lemma 8.16 in current tex)
  * Theorem 4.2 = ⟦thm-fixedframe⟧
-/
