import GQ2.BoundaryFrame
import GQ2.QuadraticFp2
import GQ2.EvensKahn

/-!
# §7: a minimal nontrivial module layer in the wild kernel — statements  (ticket P-14)

Statement-first extraction of the paper's §7 (pages 37–38; the step-1 docs never recorded its
content — discovered at extraction, per the P-14 acceptance note): the group-theoretic block
structure that §8 fixes ("For the simple-head block fixed in section 7, write `T = T₀`").
Every `theorem … := by sorry` carries its paper reference; proofs are ticket P-15.

## The paper's setup and its encoding

For a framed target `G` (here `Y`, cf. `GQ2.MarkedTarget`) with marked normal 2-subgroup `L`
and tame quotient `H`, **suppose not every chief factor of `L` is a trivial (scalar) module**;
choose

* `S ◁ P ◁ G`, `P ≤ L`, with all chief factors below `S` trivial and `V = P/S` the first
  nontrivial simple factor;
* `K ◁ G`, `K ≤ P`, minimal subject to `KS = P`; and put
  `R = Φ(K) = K²[K,K]`, `M = K/R`, `T₀ = (K ∩ S)/R`, `C = G/K`.

Encodings (`docs/section67-extraction.md` §7):

* Everything is phrased at the level of **subgroups of `Y`** (normality in `Y` = the module
  condition), avoiding quotient-module instances; the quotients `M`, `V` appear only where the
  paper's claims are irreducibly about them (`lemma_7_1_head`, `prop_7_4`), via subgroup
  quotients `↥K ⧸ …`.
* "All chief factors trivial" is `IsScalarStack`: a normal chain from `⊥` with `G`-commutators
  dropping one level (`⁅y, x⁆ ∈ cᵢ` for `x ∈ cᵢ₊₁`) — for a finite 2-group this is exactly
  "every chief factor is the trivial `𝔽₂`-module".
* `R = Φ(K)` is the subgroup generated by squares and commutators of `K` (`frattiniLike`).
* Tameness of the head (used by 7.2/7.4) is carried as a marked surjection from `GQ2.Ttame`
  (`GQ2/BoundaryFrame.lean`), matching the frame's `α`.
* The dual-invariants clause `(M^∨)^C = 0` of Lemma 7.1 is stated as: `K` has **no `Y`-normal
  subgroup of index 2** above `R` (nonzero invariant functionals ↔ such subgroups).

Axioms: none (statement layer; census stays 10).
-/

namespace GQ2

namespace SectionSeven

open QuadraticFp2

open scoped Pointwise

variable {Y : Type} [Group Y] [Finite Y]

/-! ## Scalar stacks and the block structure -/

/-- **Scalar stack** (§7 opening): a normal chain `⊥ = c₀ ≤ c₁ ≤ ⋯ ≤ c_n = L` (each `cᵢ ◁ Y`)
whose successive layers are acted on trivially by `Y` (`⁅y, x⁆ ∈ cᵢ` for `x ∈ cᵢ₊₁`) — i.e.
every chief factor of `L` is the trivial (scalar) module.  The §7 block exists exactly when the
marked kernel is *not* a scalar stack; the scalar regime is §9.1/9.2's case. -/
def IsScalarStack (L : Subgroup Y) : Prop :=
  ∃ (n : ℕ) (c : ℕ → Subgroup Y),
    c 0 = ⊥ ∧ c n = L ∧ (∀ i, c i ≤ c (i + 1)) ∧ (∀ i, (c i).Normal) ∧
      ∀ i, ∀ y : Y, ∀ x ∈ c (i + 1), y * x * y⁻¹ * x⁻¹ ∈ c i

/-- `Φ`-like subgroup: the subgroup of `Y` generated by the squares and commutators of the
elements of `K`.  For `K ◁ Y` a finite 2-group this is the Frattini subgroup `Φ(K) = K²[K,K]`
of `K`, as a subgroup of `Y` (normal in `Y`, being characteristic in `K`). -/
def frattiniLike (K : Subgroup Y) : Subgroup Y :=
  Subgroup.closure ({x | ∃ k ∈ K, x = k * k} ∪ {x | ∃ k ∈ K, ∃ l ∈ K, x = k * l * k⁻¹ * l⁻¹})

omit [Finite Y] in
/-- `Φ(K) ≤ K` (the generators are squares and commutators of elements of `K`). -/
theorem frattiniLike_le (K : Subgroup Y) : frattiniLike K ≤ K := by
  refine (Subgroup.closure_le _).mpr ?_
  rintro x (⟨k, hk, rfl⟩ | ⟨k, hk, l, hl, rfl⟩)
  · exact mul_mem hk hk
  · exact mul_mem (mul_mem (mul_mem hk hl) (inv_mem hk)) (inv_mem hl)

omit [Finite Y] in
/-- `Φ(P)` is the image of the subtype-level Frattini-like subgroup of `↥P` — the bridge that
lets quotient arguments run inside `↥P` without closure inductions. -/
theorem frattiniLike_eq_map (P : Subgroup Y) :
    frattiniLike P
      = (Subgroup.closure ({x : P | ∃ k : P, x = k * k}
          ∪ {x : P | ∃ k l : P, x = k * l * k⁻¹ * l⁻¹})).map P.subtype := by
  rw [MonoidHom.map_closure, frattiniLike]
  congr 1
  ext x
  constructor
  · rintro (⟨k, hk, rfl⟩ | ⟨k, hk, l, hl, rfl⟩)
    · exact ⟨⟨k, hk⟩ * ⟨k, hk⟩, Or.inl ⟨⟨k, hk⟩, rfl⟩, rfl⟩
    · exact ⟨⟨k, hk⟩ * ⟨l, hl⟩ * ⟨k, hk⟩⁻¹ * ⟨l, hl⟩⁻¹,
        Or.inr ⟨⟨k, hk⟩, ⟨l, hl⟩, rfl⟩, rfl⟩
  · rintro ⟨x', hx', rfl⟩
    rcases hx' with ⟨k, rfl⟩ | ⟨k, l, rfl⟩
    · exact Or.inl ⟨k.1, k.2, rfl⟩
    · exact Or.inr ⟨k.1, k.2, l.1, l.2, rfl⟩

omit [Finite Y] in
/-- For `K ◁ Y`, `Φ(K)` is normal in `Y` (conjugation permutes the generating set). -/
theorem frattiniLike_normal (K : Subgroup Y) (hK : K.Normal) : (frattiniLike K).Normal := by
  constructor
  intro n hn g
  have himg : (frattiniLike K).map (MulAut.conj g).toMonoidHom ≤ frattiniLike K := by
    rw [frattiniLike, MonoidHom.map_closure]
    refine (Subgroup.closure_le _).mpr ?_
    rintro _ ⟨x, hx, rfl⟩
    rcases hx with ⟨k, hk, rfl⟩ | ⟨k, hk, l, hl, rfl⟩
    · refine Subgroup.subset_closure (Or.inl ⟨g * k * g⁻¹, hK.conj_mem k hk g, ?_⟩)
      show g * (k * k) * g⁻¹ = g * k * g⁻¹ * (g * k * g⁻¹)
      group
    · refine Subgroup.subset_closure
        (Or.inr ⟨g * k * g⁻¹, hK.conj_mem k hk g, g * l * g⁻¹, hK.conj_mem l hl g, ?_⟩)
      show g * (k * l * k⁻¹ * l⁻¹) * g⁻¹
        = g * k * g⁻¹ * (g * l * g⁻¹) * (g * k * g⁻¹)⁻¹ * (g * l * g⁻¹)⁻¹
      group
  exact himg ⟨n, hn, rfl⟩

/-- **The §7 minimal block** (§7 opening): `S ◁ P ◁ Y` with `P ≤ L`, everything below `S`
scalar, `V = P/S` a nontrivial simple `Y`-chief factor, and `K ◁ Y` minimal with `KS = P`. -/
structure MinimalBlock (L : Subgroup Y) where
  /-- The marked kernel is normal (a `GQ2.MarkedTarget` guarantee, carried so the block is
  self-contained).  [Field added in the P-15 pass, with `h2L`.] -/
  hL : L.Normal
  /-- The marked kernel is a 2-group — the paper's standing "marked normal **2**-subgroup"
  hypothesis.  [Field added in the P-15 pass: caught by attempting `lemma_7_1_head`, which is
  **false** without it (counterexample `Y = S₃`, `L = P = K = A₃`, `S = ⊥`: all other fields
  hold but `Φ(A₃) = A₃ ≰ K ⊓ S`).  Deviation ledger updated.] -/
  h2L : IsPGroup 2 L
  /-- The scalar socle `S`. -/
  S : Subgroup Y
  /-- The layer top `P`. -/
  P : Subgroup Y
  /-- The minimal generator `K`. -/
  K : Subgroup Y
  hS : S.Normal
  hP : P.Normal
  hK : K.Normal
  hPL : P ≤ L
  hSP : S < P
  /-- All chief factors below `S` are trivial. -/
  scalar_below : IsScalarStack S
  /-- `P/S` is a chief factor: no `Y`-normal subgroup strictly between. -/
  chief : ∀ X : Subgroup Y, X.Normal → S ≤ X → X ≤ P → X = S ∨ X = P
  /-- `V = P/S` is a **nontrivial** module: some `Y`-conjugation moves `P` nontrivially mod
  `S`. -/
  nontrivial_action : ∃ (y : Y) (p : Y), p ∈ P ∧ y * p * y⁻¹ * p⁻¹ ∉ S
  hKP : K ≤ P
  /-- `KS = P`. -/
  gen : K ⊔ S = P
  /-- Minimality of `K` among `Y`-normal subgroups with `K'S = P`. -/
  minimal : ∀ K' : Subgroup Y, K'.Normal → K' ≤ K → K' ⊔ S = P → K' = K

variable {L : Subgroup Y}

/-- `R = Φ(K)`. -/
def MinimalBlock.R (B : MinimalBlock L) : Subgroup Y := frattiniLike B.K

/-- **Existence of the block** (§7 opening, "Choose …"): if the marked kernel `L` (a normal
finite 2-group, `GQ2.MarkedTarget`'s `L_Y`) is not a scalar stack, a minimal block exists.
[P-14 statement; proof P-15.] -/
theorem exists_minimalBlock (hL : L.Normal) (h2 : IsPGroup 2 L)
    (h : ¬ IsScalarStack L) : Nonempty (MinimalBlock L) := by
  classical
  haveI : Finite (Subgroup Y) :=
    Finite.of_injective (fun H : Subgroup Y => (H : Set Y)) SetLike.coe_injective
  -- `S`: an inclusion-maximal `Y`-normal scalar stack inside `L` (`⊥` is one)
  have hbot : (⊥ : Subgroup Y) ∈ {T : Subgroup Y | T.Normal ∧ T ≤ L ∧ IsScalarStack T} := by
    refine ⟨Subgroup.normal_bot, bot_le, 0, fun _ => ⊥, rfl, rfl, fun _ => le_rfl,
      fun _ => Subgroup.normal_bot, ?_⟩
    intro i y x hx
    have hx1 : x = 1 := by simpa using hx
    subst hx1
    simp
  obtain ⟨S, hSmax⟩ := Set.Finite.exists_maximal (Set.toFinite _) ⟨⊥, hbot⟩
  obtain ⟨hSn, hSL, hSstack⟩ := hSmax.prop
  have hSltL : S < L := hSL.lt_of_ne fun hEq => h (hEq ▸ hSstack)
  -- `P`: an inclusion-minimal `Y`-normal subgroup strictly between `S` and `L`
  obtain ⟨P, hPmin⟩ := Set.Finite.exists_minimal
    (Set.toFinite {T : Subgroup Y | T.Normal ∧ S < T ∧ T ≤ L}) ⟨L, hL, hSltL, le_rfl⟩
  obtain ⟨hPn, hSltP, hPL⟩ := hPmin.prop
  -- minimality of `P` is the chief condition
  have hchief : ∀ X : Subgroup Y, X.Normal → S ≤ X → X ≤ P → X = S ∨ X = P := by
    intro X hXn hSX hXP
    rcases hSX.lt_or_eq with hlt | heq
    · exact Or.inr (hPmin.eq_of_le ⟨hXn, hlt, hXP.trans hPL⟩ hXP)
    · exact Or.inl heq.symm
  -- maximality of `S` is the nontriviality of the action on `P/S`
  have hnta : ∃ (y : Y) (p : Y), p ∈ P ∧ y * p * y⁻¹ * p⁻¹ ∉ S := by
    by_contra hall
    push Not at hall
    obtain ⟨n, c, hc0, hcn, hmono, hnorm, hcomm⟩ := hSstack
    -- otherwise `S`'s chain extends one level to `P`
    have hPstack : IsScalarStack P := by
      refine ⟨n + 1, fun i => if i ≤ n then c i else P, ?_, ?_, ?_, ?_, ?_⟩
      · dsimp only
        rw [if_pos (Nat.zero_le n)]
        exact hc0
      · dsimp only
        rw [if_neg (by omega : ¬ n + 1 ≤ n)]
      · intro i
        dsimp only
        by_cases hi : i + 1 ≤ n
        · rw [if_pos (by omega : i ≤ n), if_pos hi]
          exact hmono i
        · by_cases hi' : i ≤ n
          · rw [if_pos hi', if_neg hi]
            have hin : i = n := by omega
            subst hin
            rw [hcn]
            exact hSltP.le
          · rw [if_neg hi', if_neg hi]
      · intro i
        dsimp only
        by_cases hi : i ≤ n
        · rw [if_pos hi]
          exact hnorm i
        · rw [if_neg hi]
          exact hPn
      · intro i y x hx
        dsimp only at hx ⊢
        by_cases hi : i + 1 ≤ n
        · rw [if_pos hi] at hx
          rw [if_pos (by omega : i ≤ n)]
          exact hcomm i y x hx
        · rw [if_neg hi] at hx
          by_cases hi' : i ≤ n
          · have hin : i = n := by omega
            subst hin
            rw [if_pos le_rfl, hcn]
            exact hall y x hx
          · rw [if_neg hi']
            exact hSltP.le (hall y x hx)
    exact hSltP.ne (hSmax.eq_of_le ⟨hPn, hPL, hPstack⟩ hSltP.le)
  -- `K`: an inclusion-minimal `Y`-normal subgroup of `P` with `K ⊔ S = P`
  obtain ⟨K, hKmin⟩ := Set.Finite.exists_minimal
    (Set.toFinite {T : Subgroup Y | T.Normal ∧ T ≤ P ∧ T ⊔ S = P})
    ⟨P, hPn, le_rfl, sup_eq_left.mpr hSltP.le⟩
  obtain ⟨hKn, hKP, hKgen⟩ := hKmin.prop
  exact ⟨⟨hL, h2, S, P, K, hSn, hPn, hKn, hPL, hSltP, hSstack, hchief, hnta, hKP, hKgen,
    fun K' hK'n hK'K hK'gen => hKmin.eq_of_le ⟨hK'n, hK'K.trans hKP, hK'gen⟩ hK'K⟩⟩

/-! ## Lemma 7.1 (simple head) -/

/-- **Lemma 7.1, head clause** — recorded in its load-bearing form `R ≤ K ∩ S` (the paper's
"Since `K/(K∩S) ≅ V` is elementary abelian, `R ≤ K∩S`; the displayed sequence follows"): given
`gen : K ⊔ S = P`, the exact sequence `0 → T₀ → M → V → 0` and the head identification
`M/T₀ ≅ V` are then the second isomorphism theorem
(`QuotientGroup.quotientInfEquivProdNormalQuotient`), which Mathlib supplies — so the inclusion
is the §7-specific content.  [P-14 statement; proof P-15.] -/
theorem lemma_7_1_head (B : MinimalBlock L) : B.R ≤ B.K ⊓ B.S := by
  refine le_inf (frattiniLike_le B.K) ?_
  -- the `Y`-normal candidate `(Φ(P) ⊔ S) ⊓ P` between `S` and `P`
  haveI := frattiniLike_normal B.P B.hP
  haveI := B.hS
  have hXn : ((frattiniLike B.P ⊔ B.S) ⊓ B.P).Normal := by
    have hsup : (frattiniLike B.P ⊔ B.S).Normal := Subgroup.sup_normal _ _
    exact ⟨fun n hn y => Subgroup.mem_inf.mpr
      ⟨hsup.conj_mem _ (Subgroup.mem_inf.mp hn).1 y,
        B.hP.conj_mem _ (Subgroup.mem_inf.mp hn).2 y⟩⟩
  rcases B.chief _ hXn (le_inf le_sup_right B.hSP.le) inf_le_right with hX | hX
  · -- `X = S`: every square/commutator of `K ≤ P` lands in `S`
    refine (Subgroup.closure_le _).mpr ?_
    rintro x (⟨k, hk, rfl⟩ | ⟨k, hk, l, hl, rfl⟩)
    · have hmem : k * k ∈ (frattiniLike B.P ⊔ B.S) ⊓ B.P := Subgroup.mem_inf.mpr
        ⟨Subgroup.mem_sup_left (Subgroup.subset_closure (Or.inl ⟨k, B.hKP hk, rfl⟩)),
          B.P.mul_mem (B.hKP hk) (B.hKP hk)⟩
      rw [hX] at hmem
      exact hmem
    · have hmem : k * l * k⁻¹ * l⁻¹ ∈ (frattiniLike B.P ⊔ B.S) ⊓ B.P := Subgroup.mem_inf.mpr
        ⟨Subgroup.mem_sup_left
            (Subgroup.subset_closure (Or.inr ⟨k, B.hKP hk, l, B.hKP hl, rfl⟩)),
          B.P.mul_mem (B.P.mul_mem (B.P.mul_mem (B.hKP hk) (B.hKP hl))
            (B.P.inv_mem (B.hKP hk))) (B.P.inv_mem (B.hKP hl))⟩
      rw [hX] at hmem
      exact hmem
  · -- `X = P`: the finite-2-group Frattini contradiction
    exfalso
    have hPsub : ∀ p ∈ B.P, p ∈ frattiniLike B.P ⊔ B.S := by
      intro p hp
      have hmem : p ∈ (frattiniLike B.P ⊔ B.S) ⊓ B.P := by rw [hX]; exact hp
      exact (Subgroup.mem_inf.mp hmem).1
    -- the quotient `Q = ↥P ⧸ S` is a nontrivial finite 2-group…
    haveI hSPn : (B.S.subgroupOf B.P).Normal := B.hS.subgroupOf B.P
    have hP2 : IsPGroup 2 B.P := by
      intro g
      obtain ⟨n, hn⟩ := B.h2L ⟨g.1, B.hPL g.2⟩
      refine ⟨n, ?_⟩
      ext
      simpa using congrArg Subtype.val hn
    haveI : Fact (Nat.Prime 2) := Nat.fact_prime_two
    have hQ2 : IsPGroup 2 (↥B.P ⧸ B.S.subgroupOf B.P) := hP2.to_quotient _
    obtain ⟨p₀, hp₀P, hp₀S⟩ := SetLike.exists_of_lt B.hSP
    haveI hQnt : Nontrivial (↥B.P ⧸ B.S.subgroupOf B.P) := by
      refine ⟨⟨QuotientGroup.mk ⟨p₀, hp₀P⟩, 1, ?_⟩⟩
      rw [ne_eq, QuotientGroup.eq_one_iff]
      exact fun hmem => hp₀S (Subgroup.mem_subgroupOf.mp hmem)
    -- …generated by squares and commutators (through `P ≤ Φ(P)·S`)
    have htop : ∀ x : ↥B.P ⧸ B.S.subgroupOf B.P,
        x ∈ Subgroup.closure
          ({y | ∃ a, y = a * a} ∪ {y | ∃ a b, y = a * b * a⁻¹ * b⁻¹}) := by
      intro x
      obtain ⟨y, rfl⟩ := QuotientGroup.mk'_surjective (B.S.subgroupOf B.P) x
      have hy' : (y : Y) ∈ (frattiniLike B.P : Set Y) * (B.S : Set Y) := by
        rw [← Subgroup.mul_normal (frattiniLike B.P) B.S]
        exact hPsub y.1 y.2
      obtain ⟨f, hf, s, hs, hfs⟩ := hy'
      rw [frattiniLike_eq_map] at hf
      obtain ⟨f', hf', hf'val⟩ := hf
      have hmk : QuotientGroup.mk' (B.S.subgroupOf B.P) y
          = QuotientGroup.mk' (B.S.subgroupOf B.P) f' := by
        symm
        rw [QuotientGroup.mk'_eq_mk']
        refine ⟨⟨s, B.hSP.le hs⟩, Subgroup.mem_subgroupOf.mpr hs, ?_⟩
        ext
        show (f' : Y) * s = (y : Y)
        have hf'' : (f' : Y) = f := hf'val
        rw [hf'']
        exact hfs
      rw [hmk]
      have hmem := Subgroup.mem_map_of_mem (QuotientGroup.mk' (B.S.subgroupOf B.P)) hf'
      rw [MonoidHom.map_closure] at hmem
      refine (Subgroup.closure_le _).mpr ?_ hmem
      rintro _ ⟨z, hz, rfl⟩
      rcases hz with ⟨a, rfl⟩ | ⟨a, b, rfl⟩
      · exact Subgroup.subset_closure (Or.inl ⟨_, by rw [map_mul]⟩)
      · exact Subgroup.subset_closure
          (Or.inr ⟨_, _, by rw [map_mul, map_mul, map_mul, map_inv, map_inv]⟩)
    -- pass to the abelianization: every element is a square
    have habel : ∀ w : Abelianization (↥B.P ⧸ B.S.subgroupOf B.P),
        w ∈ Subgroup.closure {x | ∃ a, x = a * a} := by
      intro w
      obtain ⟨q, rfl⟩ := QuotientGroup.mk'_surjective _ w
      have hmem := Subgroup.mem_map_of_mem
        (Abelianization.of (G := ↥B.P ⧸ B.S.subgroupOf B.P)) (htop q)
      rw [MonoidHom.map_closure] at hmem
      have hcommW : ∀ u v : Abelianization (↥B.P ⧸ B.S.subgroupOf B.P),
          u * v * u⁻¹ * v⁻¹ = 1 := by
        intro u v
        rw [mul_comm u v, mul_assoc v u, mul_inv_cancel, mul_one, mul_inv_cancel]
      refine (Subgroup.closure_le _).mpr ?_ hmem
      rintro _ ⟨z, hz, rfl⟩
      rcases hz with ⟨a, rfl⟩ | ⟨a, b, rfl⟩
      · exact Subgroup.subset_closure ⟨_, by rw [map_mul]⟩
      · have h1 : Abelianization.of (a * b * a⁻¹ * b⁻¹) = 1 := by
          rw [map_mul, map_mul, map_mul, map_inv, map_inv, hcommW]
        rw [h1]
        exact one_mem _
    -- squaring is a surjective, hence injective, endomorphism of the finite abelianization
    have hsurj : Function.Surjective
        (powMonoidHom 2 : Abelianization (↥B.P ⧸ B.S.subgroupOf B.P) →* _) := by
      rw [← MonoidHom.range_eq_top, eq_top_iff]
      intro w _
      refine (Subgroup.closure_le _).mpr ?_ (habel w)
      rintro _ ⟨a, rfl⟩
      exact ⟨a, by rw [powMonoidHom_apply, pow_two]⟩
    have hinj : Function.Injective
        (powMonoidHom 2 : Abelianization (↥B.P ⧸ B.S.subgroupOf B.P) →* _) :=
      Finite.injective_iff_surjective.mpr hsurj
    by_cases hWt : Subsingleton (Abelianization (↥B.P ⧸ B.S.subgroupOf B.P))
    · -- trivial abelianization: `Q` is perfect, contradicting nilpotency of finite 2-groups
      have hcommQ : commutator (↥B.P ⧸ B.S.subgroupOf B.P) = ⊤ := by
        rw [eq_top_iff]
        intro q _
        have h1 : Abelianization.of q = 1 := Subsingleton.elim _ _
        exact (QuotientGroup.eq_one_iff q).mp h1
      have hnil := hQ2.isNilpotent
      obtain ⟨n, hn⟩ := Subgroup.nilpotent_iff_lowerCentralSeries.mp hnil
      have hall : ∀ m,
          Subgroup.lowerCentralSeries (⊤ : Subgroup (↥B.P ⧸ B.S.subgroupOf B.P)) m = ⊤ := by
        intro m
        induction m with
        | zero => rfl
        | succ m ih =>
          rw [Subgroup.lowerCentralSeries_succ, ih, ← _root_.commutator_def]
          exact hcommQ
      rw [hall n] at hn
      obtain ⟨q, hq⟩ := exists_ne (1 : ↥B.P ⧸ B.S.subgroupOf B.P)
      exact hq (Subgroup.mem_bot.mp (hn ▸ Subgroup.mem_top q))
    · -- nontrivial abelianization: an order-2 element dies under injective squaring
      classical
      rw [not_subsingleton_iff_nontrivial] at hWt
      obtain ⟨w, hw⟩ := exists_ne (1 : Abelianization (↥B.P ⧸ B.S.subgroupOf B.P))
      obtain ⟨n, hn⟩ := (hQ2.to_quotient (commutator _)) w
      have hex : ∃ j, w ^ (2 : ℕ) ^ j = 1 := ⟨n, hn⟩
      have hspec : w ^ (2 : ℕ) ^ Nat.find hex = 1 := Nat.find_spec hex
      have hm0 : Nat.find hex ≠ 0 := by
        intro h0
        rw [h0, pow_zero, pow_one] at hspec
        exact hw hspec
      have hw'1 : w ^ (2 : ℕ) ^ (Nat.find hex - 1) ≠ 1 :=
        Nat.find_min hex (Nat.sub_lt (Nat.pos_of_ne_zero hm0) one_pos)
      have hw'sq : (powMonoidHom 2 : Abelianization _ →* _) (w ^ (2 : ℕ) ^ (Nat.find hex - 1))
          = (powMonoidHom 2 : Abelianization _ →* _) 1 := by
        rw [map_one, powMonoidHom_apply, ← pow_mul]
        have harith : (2 : ℕ) ^ (Nat.find hex - 1) * 2 = 2 ^ Nat.find hex := by
          rw [← pow_succ]
          congr 1
          omega
        rw [harith, hspec]
      exact hw'1 (hinj hw'sq)

/-- **Lemma 7.1, radical clause**: `T₀ = (K ∩ S)·R` is the unique maximal `Y`-normal subgroup
of `K` above `R` — i.e. `T₀ = rad_{𝔽₂[C]} M` and `M/T₀` is the unique simple head.
[P-14 statement; proof P-15: the head clause collapses the right-hand side to `K ⊓ S`; the
chief dichotomy on `X ⊔ S` then leaves two branches — `= P` dies by `K`'s minimality, `= S`
pins `X = K ⊓ S` by `X`'s maximality (a strict inclusion would force `K ≤ S`, hence `P = S`).
Stated after the head clause, which it consumes.] -/
theorem lemma_7_1_radical (B : MinimalBlock L)
    (X : Subgroup Y) (hX : X.Normal) (_hRX : B.R ≤ X) (hXK : X < B.K)
    (hmax : ∀ X' : Subgroup Y, X'.Normal → X < X' → X' ≤ B.K → X' = B.K) :
    X = (B.K ⊓ B.S) ⊔ B.R := by
  -- by the head clause `R ≤ K ⊓ S`, the right-hand side is `K ⊓ S`
  rw [sup_eq_left.mpr (lemma_7_1_head B)]
  -- `K ≰ S` (else `P = K ⊔ S = S`, contradicting `S < P`)
  have hKnS : ¬ B.K ≤ B.S := by
    intro hKS
    have hPS : B.P = B.S := by
      rw [← B.gen]
      exact le_antisymm (sup_le hKS le_rfl) le_sup_right
    exact B.hSP.ne hPS.symm
  -- chief dichotomy on the `Y`-normal subgroup `X ⊔ S` between `S` and `P`
  haveI := hX
  haveI := B.hS
  have hXSn : (X ⊔ B.S).Normal := Subgroup.sup_normal X B.S
  have hle : X ⊔ B.S ≤ B.P := sup_le (hXK.le.trans B.hKP) B.hSP.le
  rcases B.chief _ hXSn le_sup_right hle with hXS | hXS
  · -- `X ⊔ S = S`: then `X ≤ K ⊓ S`, and maximality of `X` pins the equality
    have hXKS : X ≤ B.K ⊓ B.S := le_inf hXK.le (le_sup_left.trans hXS.le)
    rcases hXKS.lt_or_eq with hlt | heq
    · -- a strict inclusion would force `K ⊓ S = K`, i.e. `K ≤ S`
      exfalso
      have hKSn : (B.K ⊓ B.S).Normal := ⟨fun n hn y => Subgroup.mem_inf.mpr
        ⟨B.hK.conj_mem _ (Subgroup.mem_inf.mp hn).1 y,
          B.hS.conj_mem _ (Subgroup.mem_inf.mp hn).2 y⟩⟩
      have hKK : B.K ⊓ B.S = B.K := hmax _ hKSn hlt inf_le_left
      have : B.K ≤ B.S := by rw [← hKK]; exact inf_le_right
      exact hKnS this
    · exact heq
  · -- `X ⊔ S = P`: minimality of `K` forces `X = K`, contradicting `X < K`
    exact absurd (B.minimal X hX hXK.le hXS) hXK.ne

omit [Finite Y] in
/-- **Lemma 7.1, dual-invariants clause**: `(M^∨)^C = 0` — `K` has no `Y`-normal subgroup of
index 2 above `R` (a nonzero invariant functional on `M` would be its kernel).
[P-14 statement; proof P-15 — chief-dichotomy on `X ⊔ S` + minimality; the `X ⊔ S = S` branch
pins `|P/S| = 2`, whence the `Y`-action mod `S` is trivial, contradicting `nontrivial_action`.
Finiteness-free.] -/
theorem lemma_7_1_dual (B : MinimalBlock L) :
    ¬ ∃ X : Subgroup Y, X.Normal ∧ B.R ≤ X ∧ X ≤ B.K ∧ (X.subgroupOf B.K).index = 2 := by
  rintro ⟨X, hXn, hRX, hXK, hidx⟩
  -- `X ≠ K` (index 2 ≠ 1)
  have hXne : X ≠ B.K := by
    rintro rfl
    rw [Subgroup.subgroupOf_self, Subgroup.index_top] at hidx
    exact absurd hidx (by omega)
  -- dichotomy on the `Y`-normal subgroup `X ⊔ S` between `S` and `P`
  haveI := hXn
  haveI := B.hS
  have hXSn : (X ⊔ B.S).Normal := Subgroup.sup_normal X B.S
  have hle : X ⊔ B.S ≤ B.P := sup_le (hXK.trans B.hKP) B.hSP.le
  rcases B.chief _ hXSn le_sup_right hle with hXS | hXS
  · -- `X ⊔ S = S`: then `X ≤ K ⊓ S`, and index 2 factors through `K ⊓ S`
    have hXS' : X ≤ B.S := le_sup_left.trans hXS.le
    have hXKS : X ≤ B.K ⊓ B.S := le_inf hXK hXS'
    have hrel : X.relIndex (B.K ⊓ B.S) * (B.K ⊓ B.S).relIndex B.K = 2 :=
      (Subgroup.relIndex_mul_relIndex X (B.K ⊓ B.S) B.K hXKS inf_le_left).trans hidx
    have hdvd : (B.K ⊓ B.S).relIndex B.K ∣ 2 := ⟨X.relIndex (B.K ⊓ B.S), by
      rw [← hrel]; ring⟩
    rcases (Nat.prime_two.eq_one_or_self_of_dvd _ hdvd) with h1 | h2
    · -- relindex 1: `K ≤ S`, so `P = K ⊔ S = S`, contradicting `S < P`
      have hKS : B.K ≤ B.K ⊓ B.S := Subgroup.relIndex_eq_one.mp h1
      have hPS : B.P = B.S := by
        rw [← B.gen]
        exact le_antisymm (sup_le (hKS.trans inf_le_right) le_rfl) le_sup_right
      exact absurd hPS.symm B.hSP.ne
    · -- relindex 2: `V = P/S` has order 2, so `Y` acts trivially mod `S` — contradiction
      -- with `nontrivial_action`.  Core: conjugation fixes `K` mod `S`…
      have hcomm : ∀ (y k : Y), k ∈ B.K → y * k * y⁻¹ * k⁻¹ ∈ B.S := by
        intro y k hk
        have hc : y * k * y⁻¹ ∈ B.K := B.hK.conj_mem k hk y
        by_cases hkS : k ∈ B.S
        · exact mul_mem (B.hS.conj_mem k hkS y) (inv_mem hkS)
        · have hcS : y * k * y⁻¹ ∉ B.S := by
            intro hc'
            apply hkS
            have h := B.hS.conj_mem _ hc' y⁻¹
            have heq : y⁻¹ * (y * k * y⁻¹) * y⁻¹⁻¹ = k := by group
            rwa [heq] at h
          have hu1 : (⟨y * k * y⁻¹, hc⟩ : B.K) ∉ (B.K ⊓ B.S).subgroupOf B.K := by
            intro hmem
            exact hcS (Subgroup.mem_subgroupOf.mp hmem).2
          have hu2 : (⟨k, hk⟩ : B.K)⁻¹ ∉ (B.K ⊓ B.S).subgroupOf B.K := by
            intro hmem
            rw [inv_mem_iff] at hmem
            exact hkS (Subgroup.mem_subgroupOf.mp hmem).2
          have h3 := notMem_mul_mem (U := (B.K ⊓ B.S).subgroupOf B.K) h2 hu1 hu2
          exact (Subgroup.mem_subgroupOf.mp h3).2
      -- …and extends to `P = K·S`
      have hcommP : ∀ (y p : Y), p ∈ B.P → y * p * y⁻¹ * p⁻¹ ∈ B.S := by
        intro y p hp
        rw [← B.gen] at hp
        have hp' : p ∈ (B.K : Set Y) * (B.S : Set Y) := by
          rw [← Subgroup.mul_normal B.K B.S]
          exact hp
        obtain ⟨k, hk, s, hs, rfl⟩ := hp'
        have heq : y * (k * s) * y⁻¹ * (k * s)⁻¹
            = (y * k * y⁻¹ * k⁻¹) * (k * ((y * s * y⁻¹) * s⁻¹) * k⁻¹) := by group
        rw [heq]
        exact mul_mem (hcomm y k hk)
          (B.hS.conj_mem _ (mul_mem (B.hS.conj_mem s hs y) (inv_mem hs)) k)
      obtain ⟨y, p, hpP, hnot⟩ := B.nontrivial_action
      exact hnot (hcommP y p hpP)
  · -- `X ⊔ S = P`: minimality forces `X = K`, contradicting index 2
    exact hXne (B.minimal X hXn hXK hXS)

/-! ## Coprime action on a scalar stack (shared §7 infrastructure) -/

/-- **Coprime odd action on a `Y`-central series is trivial.**  If `c : ℕ → Subgroup G` is a
`Y`-central series (`c 0 = ⊥`, monotone, `⁅g, x⁆ ∈ c i` for `x ∈ c (i+1)`, i.e. every chief
factor is a trivial module) reaching `c n`, and `Nt ≤ G` has order coprime to `|c n|`, then
`⁅Nt, c n⁆ = ⊥` — `Nt` centralizes `c n`.

Mathlib lacks the coprime-action commutator theory (`[G,A]=[G,A,A]`, the `G = [G,A]·C_G(A)`
decomposition); this is the special case the §7 block needs, proved by an elementary induction
on the series length.  The bottom layer `c 1 ≤ Z(G)` (central, since `⁅G, c 1⁆ ≤ c 0 = ⊥`);
after quotienting by it the induction hypothesis gives `⁅Nt, c (n+1)⁆ ≤ c 1`, and then for each
fixed `x` the displacement `a ↦ ⁅a, x⁆` is a homomorphism `Nt →* G` landing in the central
2-layer `c 1`, whose image is simultaneously a quotient of `Nt` (order coprime to `|c 1|`) and a
subgroup of `c 1` — hence trivial.  [P-15 helper for Lemma 7.2.] -/
private theorem comm_bot_of_scalarChain :
    ∀ (n : ℕ) {G : Type} [Group G] [Finite G] (Nt : Subgroup G) (c : ℕ → Subgroup G),
      c 0 = ⊥ → (∀ i, c i ≤ c (i + 1)) →
      (∀ i, ∀ g : G, ∀ x ∈ c (i + 1), g * x * g⁻¹ * x⁻¹ ∈ c i) →
      Nat.Coprime (Nat.card Nt) (Nat.card (c n)) →
      ⁅Nt, c n⁆ = ⊥ := by
  intro n
  induction n with
  | zero =>
    intro G _ _ Nt c hc0 _ _ _
    rw [hc0]
    exact Subgroup.commutator_bot_right Nt
  | succ n ih =>
    intro G _ _ Nt c hc0 hmono hcomm hcop
    -- the bottom layer is central: `⁅g, x⁆ = 1` for `x ∈ c 1`
    have hc1triv : ∀ x ∈ c 1, ∀ g : G, g * x * g⁻¹ * x⁻¹ = 1 := by
      intro x hx g
      have h := hcomm 0 g x hx
      rwa [hc0, Subgroup.mem_bot] at h
    have hZcomm : ∀ x ∈ c 1, ∀ g : G, g * x = x * g := by
      intro x hx g
      have h2 : g * x * g⁻¹ = x := mul_inv_eq_one.mp (hc1triv x hx g)
      calc g * x = g * x * g⁻¹ * g := by group
        _ = x * g := by rw [h2]
    haveI hc1n : (c 1).Normal :=
      ⟨fun x hx g => by
        have he : g * x * g⁻¹ = x := mul_inv_eq_one.mp (hc1triv x hx g)
        rw [he]; exact hx⟩
    set φ : G →* G ⧸ c 1 := QuotientGroup.mk' (c 1) with hφ
    have hφsurj : Function.Surjective φ := QuotientGroup.mk'_surjective (c 1)
    -- push the chain to `G ⧸ c 1`
    have hd0 : (c 1).map φ = ⊥ := by
      rw [Subgroup.map_eq_bot_iff, hφ, QuotientGroup.ker_mk']
    have hdcomm : ∀ i, ∀ gq : G ⧸ c 1, ∀ xq ∈ (c (i + 1 + 1)).map φ,
        gq * xq * gq⁻¹ * xq⁻¹ ∈ (c (i + 1)).map φ := by
      intro i gq xq hxq
      obtain ⟨x, hx, rfl⟩ := Subgroup.mem_map.mp hxq
      obtain ⟨g, rfl⟩ := hφsurj gq
      have hrw : φ g * φ x * (φ g)⁻¹ * (φ x)⁻¹ = φ (g * x * g⁻¹ * x⁻¹) := by
        simp only [map_mul, map_inv]
      rw [hrw]
      exact Subgroup.mem_map_of_mem φ (hcomm (i + 1) g x hx)
    have hd1 : Nat.card ((c (n + 1)).map φ) ∣ Nat.card (c (n + 1)) :=
      Subgroup.card_map_dvd (H := c (n + 1)) φ
    have hd2 : Nat.card (Nt.map φ) ∣ Nat.card Nt := Subgroup.card_map_dvd (H := Nt) φ
    have hcop' : Nat.Coprime (Nat.card (Nt.map φ)) (Nat.card ((c (n + 1)).map φ)) :=
      (hcop.coprime_dvd_left hd2).coprime_dvd_right hd1
    have key : ⁅Nt.map φ, (c (n + 1)).map φ⁆ = ⊥ :=
      ih (Nt.map φ) (fun i => (c (i + 1)).map φ) hd0
        (fun i => Subgroup.map_mono (hmono (i + 1))) (fun i => hdcomm i) hcop'
    -- so `⁅Nt, c (n+1)⁆ ≤ c 1`
    have hsub : ⁅Nt, c (n + 1)⁆ ≤ c 1 := by
      have hmapbot : (⁅Nt, c (n + 1)⁆).map φ = ⊥ := by
        rw [Subgroup.map_commutator]; exact key
      rwa [Subgroup.map_eq_bot_iff, hφ, QuotientGroup.ker_mk'] at hmapbot
    -- `|c 1|` divides `|c (n+1)|`, so it is coprime to `|Nt|`
    have hc1le : c 1 ≤ c (n + 1) := monotone_nat_of_le_succ hmono (by omega)
    have hcop1 : Nat.Coprime (Nat.card Nt) (Nat.card (c 1)) :=
      hcop.coprime_dvd_right (Subgroup.card_dvd_of_le hc1le)
    -- the displacement homomorphism kills each `x ∈ c (n+1)`
    rw [eq_bot_iff, Subgroup.commutator_le]
    intro g hg x hx
    rw [Subgroup.mem_bot, commutatorElement_def]
    -- the displacement map `a ↦ a x a⁻¹ x⁻¹` lands in the central layer `c 1`
    have hmemc1 : ∀ a : G, a ∈ Nt → a * x * a⁻¹ * x⁻¹ ∈ c 1 := by
      intro a ha
      have h := hsub (Subgroup.commutator_mem_commutator ha hx)
      rwa [commutatorElement_def] at h
    have hmuleq : ∀ a b : G, a ∈ Nt → b ∈ Nt →
        (a * b) * x * (a * b)⁻¹ * x⁻¹ = (a * x * a⁻¹ * x⁻¹) * (b * x * b⁻¹ * x⁻¹) := by
      intro a b _ hb
      have hbx : b * x * b⁻¹ * x⁻¹ ∈ c 1 := hmemc1 b hb
      have e1 : (a * b) * x * (a * b)⁻¹ * x⁻¹
          = a * (b * x * b⁻¹ * x⁻¹) * a⁻¹ * (a * x * a⁻¹ * x⁻¹) := by group
      rw [e1]
      have e2 : a * (b * x * b⁻¹ * x⁻¹) * a⁻¹ = b * x * b⁻¹ * x⁻¹ := by
        rw [hZcomm _ hbx a]; group
      rw [e2, hZcomm _ hbx (a * x * a⁻¹ * x⁻¹)]
    let ψ : Nt →* G := MonoidHom.mk' (fun a => (a : G) * x * (a : G)⁻¹ * x⁻¹) (by
      intro a b
      rw [Subgroup.coe_mul]
      exact hmuleq _ _ a.2 b.2)
    have hψrange : ψ.range ≤ c 1 := by
      rintro _ ⟨a, rfl⟩
      exact hmemc1 (a : G) a.2
    have hone : Nat.card ψ.range = 1 :=
      Nat.eq_one_of_dvd_coprimes hcop1 (Subgroup.card_range_dvd ψ)
        (Subgroup.card_dvd_of_le hψrange)
    have hbot : ψ.range = ⊥ := Subgroup.card_eq_one.mp hone
    have hgx : ψ ⟨g, hg⟩ = 1 := by
      have hmem : ψ ⟨g, hg⟩ ∈ ψ.range := ⟨⟨g, hg⟩, rfl⟩
      rwa [hbot, Subgroup.mem_bot] at hmem
    exact hgx

/-! ## Lemma 7.2 (Frattini–centralizer collapse) and Lemma 7.3 (decorations vanish) -/

/-- **Lemma 7.2**: for a tame head (the target's head map factors through `GQ2.Ttame`),
`R = Φ(K)` is central elementary abelian in `K`, and `K⁴ = 1`.  [P-14 statement; proof P-15
(odd Hall lift + three-subgroup lemma + the `G`-equivariant fourth-power map).] -/
theorem lemma_7_2 {H : Type} [Group H] [TopologicalSpace H] [DiscreteTopology H] [Finite H]
    (π : Y →* H) (hπ : Function.Surjective π) (hkerπ : π.ker = L)
    (cH : ContinuousMonoidHom Ttame H) (hcH : Function.Surjective cH)
    (B : MinimalBlock L) :
    (∀ r ∈ B.R, ∀ k ∈ B.K, r * k = k * r) ∧ (∀ r ∈ B.R, r * r = 1) ∧
      ∀ k ∈ B.K, k ^ 4 = 1 := by
  sorry

omit [Finite Y] in
/-- **Lemma 7.3 (decorations vanish on the block)**: every homomorphism from `Y` to an
elementary abelian 2-group kills `K` (via Lemma 7.1's dual clause).  The frame decorations
`θ_Y` of `GQ2.MarkedTarget` are such homomorphisms.  [P-14 statement; proof P-15: a nonzero
value `f k₀ ≠ 1` yields — through the `𝔽₂`-module structure on `Additive E` and a separating
dual functional — a `C₂`-character of `Y` nontrivial on `K` and killing `R`, whose kernel meets
`K` in a `Y`-normal index-2 subgroup above `R`, contradicting `lemma_7_1_dual`.
Finiteness-free.] -/
theorem lemma_7_3 (B : MinimalBlock L)
    {E : Type} [CommGroup E] (hE : ∀ e : E, e ^ 2 = 1) (f : Y →* E) :
    B.K ≤ f.ker := by
  by_contra hnot
  rw [SetLike.le_def] at hnot
  simp only [not_forall] at hnot
  obtain ⟨k₀, hk₀K, hk₀⟩ := hnot
  rw [MonoidHom.mem_ker] at hk₀
  -- `Additive E` is an `𝔽₂`-vector space
  letI : Module (ZMod 2) (Additive E) := AddCommGroup.zmodModule (by
    intro x
    apply Additive.toMul.injective
    rw [toMul_nsmul, toMul_zero]
    exact hE x.toMul)
  -- a functional separating `f k₀` from `0`
  have hw : Additive.ofMul (f k₀) ≠ (0 : Additive E) := by simpa using hk₀
  obtain ⟨φ, hφ⟩ : ∃ φ : Module.Dual (ZMod 2) (Additive E),
      φ (Additive.ofMul (f k₀)) ≠ 0 := by
    by_contra hall
    simp only [not_exists, not_not] at hall
    exact hw ((Module.forall_dual_apply_eq_zero_iff (ZMod 2) _).mp hall)
  -- the induced `C₂`-character of `Y`
  set g : Y →* Multiplicative (ZMod 2) :=
    (AddMonoidHom.toMultiplicativeRight φ.toAddMonoidHom).comp f with hg
  have hgk₀ : g k₀ ≠ 1 := by
    rw [hg]
    simp only [MonoidHom.comp_apply, AddMonoidHom.toMultiplicativeRight_apply_apply]
    intro h
    apply hφ
    simpa using congrArg Multiplicative.toAdd h
  -- `R` dies under `g` (squares and commutators die in `C₂`)
  have hRker : frattiniLike B.K ≤ g.ker := by
    refine (Subgroup.closure_le _).mpr ?_
    have hsq : ∀ x : Multiplicative (ZMod 2), x * x = 1 := by decide
    have hab : ∀ a b : Multiplicative (ZMod 2), a * b * a⁻¹ * b⁻¹ = 1 := by decide
    rintro x (⟨k, hk, rfl⟩ | ⟨k, hk, l, hl, rfl⟩)
    · rw [SetLike.mem_coe, MonoidHom.mem_ker, map_mul]
      exact hsq _
    · rw [SetLike.mem_coe, MonoidHom.mem_ker, map_mul, map_mul, map_mul, map_inv, map_inv]
      exact hab _ _
  -- the kernel meets `K` in a `Y`-normal index-2 subgroup above `R`
  have hXn : (g.ker ⊓ B.K).Normal := ⟨fun n hn y => Subgroup.mem_inf.mpr
    ⟨g.normal_ker.conj_mem _ (Subgroup.mem_inf.mp hn).1 y,
      B.hK.conj_mem _ (Subgroup.mem_inf.mp hn).2 y⟩⟩
  set g' : B.K →* Multiplicative (ZMod 2) := g.comp B.K.subtype with hg'
  have hker' : (g.ker ⊓ B.K).subgroupOf B.K = g'.ker := by
    ext ⟨y, hy⟩
    simp [Subgroup.mem_subgroupOf, MonoidHom.mem_ker, hg']
  have hidx : ((g.ker ⊓ B.K).subgroupOf B.K).index = 2 := by
    rw [hker', Subgroup.index_ker]
    have h2 : Nat.card (Multiplicative (ZMod 2)) = 2 := by
      rw [Nat.card_congr Multiplicative.toAdd, Nat.card_zmod]
    have hdvd : Nat.card g'.range ∣ 2 := by
      have h := Subgroup.card_subgroup_dvd_card g'.range
      rwa [h2] at h
    rcases (Nat.prime_two.eq_one_or_self_of_dvd _ hdvd) with h1 | h1
    · exfalso
      have hbot : g'.range = ⊥ := Subgroup.card_eq_one.mp h1
      have hmem : g' ⟨k₀, hk₀K⟩ ∈ g'.range := ⟨_, rfl⟩
      rw [hbot, Subgroup.mem_bot] at hmem
      exact hgk₀ hmem
    · exact h1
  exact lemma_7_1_dual B ⟨g.ker ⊓ B.K, hXn,
    le_inf hRker (frattiniLike_le B.K), inf_le_right, hidx⟩

/-! ## Proposition 7.4 (simple-head determinant)

The proof layer splits the paper's argument into an abstract-block tier (everything except
step 2) and the genuinely tame step 2 (`q_λ|_{T₀} = 0`), which needs `H¹(H_V, V^∨) = 0` for
the head's action image and is therefore stated with the framed-target head data
(P-15 amendment: the P-14 statement had dropped §7's standing framed-target hypothesis,
under which the paper proves 7.4 — restored here; see `docs/section67-extraction.md`). -/

omit [Finite Y] in
/-- Squares of `K` generate into `R = Φ(K)`. -/
private theorem sq_mem_R (B : MinimalBlock L) {k : Y} (hk : k ∈ B.K) : k * k ∈ B.R :=
  Subgroup.subset_closure (Or.inl ⟨k, hk, rfl⟩)

omit [Finite Y] in
/-- Commutators of `K` generate into `R = Φ(K)`. -/
private theorem comm_mem_R (B : MinimalBlock L) {k l : Y} (hk : k ∈ B.K) (hl : l ∈ B.K) :
    k * l * k⁻¹ * l⁻¹ ∈ B.R :=
  Subgroup.subset_closure (Or.inr ⟨k, hk, l, hl, rfl⟩)

omit [Finite Y] in
/-- **Prop 7.4, step 1** (`b_λ(T₀, M) = 0`): a `Y`-invariant additive `λ : R → 𝔽₂` kills every
commutator `[k, t]`, `k ∈ K`, `t ∈ K ∩ S`.  Abstract-block proof (no tame input) — the paper's
socle argument run at subgroup level: the right kernel `T` of the pairing
`(k, t) ↦ λ([k, t])` is a `Y`-normal subgroup; were some `t₀ ∈ K ∩ S` outside it, the
scalar-stack chain of `S` intersected with `K ∩ S` would have a first layer `⊄ T`, and any
`t*` there has all its `Y`-commutators inside `T` — making `k ↦ λ([k, t*])` a nonzero
`Y`-invariant functional on `K` killing `R`, whose kernel is a `Y`-normal index-2 subgroup of
`K` above `R`, contradicting `lemma_7_1_dual`. -/
private theorem lam_comm_vanish (B : MinimalBlock L) (hRN : B.R.Normal)
    (lam : ↥B.R → ZMod 2)
    (hlam_hom : ∀ r r' : ↥B.R, lam (r * r') = lam r + lam r')
    (hlam_conj : ∀ (y r : Y) (hr : r ∈ B.R),
      lam ⟨y * r * y⁻¹, hRN.conj_mem r hr y⟩ = lam ⟨r, hr⟩) :
    ∀ k, k ∈ B.K → ∀ t, t ∈ B.K ⊓ B.S → ∀ (h : k * t * k⁻¹ * t⁻¹ ∈ B.R),
      lam ⟨k * t * k⁻¹ * t⁻¹, h⟩ = 0 := by
  classical
  -- λ-kit: value at 1, inverses, subtype products
  have hz2 : ∀ x y : ZMod 2, x + y = 0 → y = x := by decide
  have hxx : ∀ x : ZMod 2, x + x = 0 := by decide
  have lam_one : lam 1 = 0 := by
    have h := hlam_hom 1 1
    rw [one_mul] at h
    have h2 : (0 : ZMod 2) + lam 1 = lam 1 + lam 1 := by rw [zero_add]; exact h
    exact (add_right_cancel h2).symm
  have lam_inv : ∀ (a : Y) (ha : a ∈ B.R), lam ⟨a⁻¹, inv_mem ha⟩ = lam ⟨a, ha⟩ := by
    intro a ha
    have h := hlam_hom ⟨a, ha⟩ ⟨a⁻¹, inv_mem ha⟩
    have e : (⟨a, ha⟩ * ⟨a⁻¹, inv_mem ha⟩ : ↥B.R) = 1 := Subtype.ext (by
      show a * a⁻¹ = 1
      group)
    rw [e, lam_one] at h
    exact hz2 _ _ h.symm
  -- β-additivity in the `K`-slot: `[kk', t] = (k[k', t]k⁻¹)·[k, t]`
  have beta_add_k : ∀ (k k' t : Y) (hk : k ∈ B.K) (hk' : k' ∈ B.K) (ht : t ∈ B.K),
      lam ⟨k * k' * t * (k * k')⁻¹ * t⁻¹, comm_mem_R B (B.K.mul_mem hk hk') ht⟩
        = lam ⟨k' * t * k'⁻¹ * t⁻¹, comm_mem_R B hk' ht⟩
          + lam ⟨k * t * k⁻¹ * t⁻¹, comm_mem_R B hk ht⟩ := by
    intro k k' t hk hk' ht
    have e : (⟨k * k' * t * (k * k')⁻¹ * t⁻¹, comm_mem_R B (B.K.mul_mem hk hk') ht⟩ : ↥B.R)
        = ⟨k * (k' * t * k'⁻¹ * t⁻¹) * k⁻¹, hRN.conj_mem _ (comm_mem_R B hk' ht) k⟩
          * ⟨k * t * k⁻¹ * t⁻¹, comm_mem_R B hk ht⟩ := Subtype.ext (by
      show k * k' * t * (k * k')⁻¹ * t⁻¹
        = k * (k' * t * k'⁻¹ * t⁻¹) * k⁻¹ * (k * t * k⁻¹ * t⁻¹)
      group)
    rw [e, hlam_hom]
    congr 1
    exact hlam_conj k _ (comm_mem_R B hk' ht)
  -- β-additivity in the `t`-slot: `[k, tt'] = [k, t]·(t[k, t']t⁻¹)`
  have beta_add_t : ∀ (k t t' : Y) (hk : k ∈ B.K) (ht : t ∈ B.K) (ht' : t' ∈ B.K),
      lam ⟨k * (t * t') * k⁻¹ * (t * t')⁻¹, comm_mem_R B hk (B.K.mul_mem ht ht')⟩
        = lam ⟨k * t * k⁻¹ * t⁻¹, comm_mem_R B hk ht⟩
          + lam ⟨k * t' * k⁻¹ * t'⁻¹, comm_mem_R B hk ht'⟩ := by
    intro k t t' hk ht ht'
    have e : (⟨k * (t * t') * k⁻¹ * (t * t')⁻¹, comm_mem_R B hk (B.K.mul_mem ht ht')⟩ : ↥B.R)
        = ⟨k * t * k⁻¹ * t⁻¹, comm_mem_R B hk ht⟩
          * ⟨t * (k * t' * k⁻¹ * t'⁻¹) * t⁻¹, hRN.conj_mem _ (comm_mem_R B hk ht') t⟩ :=
      Subtype.ext (by
        show k * (t * t') * k⁻¹ * (t * t')⁻¹
          = (k * t * k⁻¹ * t⁻¹) * (t * (k * t' * k⁻¹ * t'⁻¹) * t⁻¹)
        group)
    rw [e, hlam_hom]
    congr 1
    exact hlam_conj t _ (comm_mem_R B hk ht')
  -- β kills `R` in the `K`-slot: `[r, t] = r·(t r⁻¹ t⁻¹)`
  have beta_R_k : ∀ (r t : Y) (hr : r ∈ B.R) (h : r * t * r⁻¹ * t⁻¹ ∈ B.R),
      lam ⟨r * t * r⁻¹ * t⁻¹, h⟩ = 0 := by
    intro r t hr h
    have e : (⟨r * t * r⁻¹ * t⁻¹, h⟩ : ↥B.R)
        = ⟨r, hr⟩ * ⟨t * r⁻¹ * t⁻¹, hRN.conj_mem _ (inv_mem hr) t⟩ := Subtype.ext (by
      show r * t * r⁻¹ * t⁻¹ = r * (t * r⁻¹ * t⁻¹)
      group)
    rw [e, hlam_hom, hlam_conj t _ (inv_mem hr), lam_inv r hr]
    exact hxx _
  -- the right kernel `T` of the pairing, a subgroup of `Y` inside `K ⊓ S`
  let T : Subgroup Y :=
    { carrier := {t | t ∈ B.K ⊓ B.S ∧ ∀ k, k ∈ B.K → ∀ h : k * t * k⁻¹ * t⁻¹ ∈ B.R,
        lam ⟨k * t * k⁻¹ * t⁻¹, h⟩ = 0}
      one_mem' := by
        refine ⟨one_mem _, fun k hk h => ?_⟩
        have e : (⟨k * 1 * k⁻¹ * 1⁻¹, h⟩ : ↥B.R) = 1 := Subtype.ext (by
          show k * 1 * k⁻¹ * 1⁻¹ = 1
          group)
        rw [e, lam_one]
      mul_mem' := by
        rintro t t' ⟨htKS, ht⟩ ⟨ht'KS, ht'⟩
        refine ⟨mul_mem htKS ht'KS, fun k hk h => ?_⟩
        have e : (⟨k * (t * t') * k⁻¹ * (t * t')⁻¹, h⟩ : ↥B.R)
            = ⟨k * (t * t') * k⁻¹ * (t * t')⁻¹,
                comm_mem_R B hk (B.K.mul_mem htKS.1 ht'KS.1)⟩ := rfl
        rw [e, beta_add_t k t t' hk htKS.1 ht'KS.1,
          ht k hk (comm_mem_R B hk htKS.1), ht' k hk (comm_mem_R B hk ht'KS.1), add_zero]
      inv_mem' := by
        rintro t ⟨htKS, ht⟩
        refine ⟨inv_mem htKS, fun k hk h => ?_⟩
        have h1 := beta_add_t k t t⁻¹ hk htKS.1 (B.K.inv_mem htKS.1)
        have e1 : (⟨k * (t * t⁻¹) * k⁻¹ * (t * t⁻¹)⁻¹,
            comm_mem_R B hk (B.K.mul_mem htKS.1 (B.K.inv_mem htKS.1))⟩ : ↥B.R) = 1 :=
          Subtype.ext (by
            show k * (t * t⁻¹) * k⁻¹ * (t * t⁻¹)⁻¹ = 1
            group)
        rw [e1, lam_one, ht k hk (comm_mem_R B hk htKS.1), zero_add] at h1
        have e2 : (⟨k * t⁻¹ * k⁻¹ * t⁻¹⁻¹, h⟩ : ↥B.R)
            = ⟨k * t⁻¹ * k⁻¹ * t⁻¹⁻¹, comm_mem_R B hk (B.K.inv_mem htKS.1)⟩ := rfl
        rw [e2, ← h1] }
  -- suppose some `[k₀, t₀]` survives
  intro k₀ hk₀ t₀ ht₀ h₀
  by_contra hne
  have ht₀T : t₀ ∉ T := fun hT => hne (hT.2 k₀ hk₀ h₀)
  -- the scalar-stack chain of `S`, intersected with `K ⊓ S`, first escapes `T` at level `j`
  obtain ⟨n, c, hc0, hcn, hmono, hnorm, hcomm⟩ := B.scalar_below
  have hex : ∃ i, ¬ (c i ⊓ (B.K ⊓ B.S) ≤ T) := by
    refine ⟨n, fun hle => ht₀T (hle (Subgroup.mem_inf.mpr ⟨?_, ht₀⟩))⟩
    rw [hcn]
    exact ht₀.2
  set j := Nat.find hex with hjdef
  have hjspec : ¬ (c j ⊓ (B.K ⊓ B.S) ≤ T) := Nat.find_spec hex
  have hj0 : j ≠ 0 := by
    intro h0
    apply hjspec
    rw [h0, hc0, bot_inf_eq]
    exact bot_le
  have hprev : c (j - 1) ⊓ (B.K ⊓ B.S) ≤ T :=
    not_not.mp (Nat.find_min hex (Nat.sub_lt (Nat.pos_of_ne_zero hj0) one_pos))
  obtain ⟨ts, htsmem, htsT⟩ := SetLike.not_le_iff_exists.mp hjspec
  have htsmem' := Subgroup.mem_inf.mp htsmem
  have htsK : ts ∈ B.K := htsmem'.2.1
  -- all `Y`-commutators of `ts` land in `T`
  have hcommT : ∀ y : Y, y * ts * y⁻¹ * ts⁻¹ ∈ T := by
    intro y
    have h1 : ts ∈ c ((j - 1) + 1) := by
      have hj1 : (j - 1) + 1 = j := by omega
      rw [hj1]
      exact htsmem'.1
    have h2 : y * ts * y⁻¹ * ts⁻¹ ∈ c (j - 1) := hcomm (j - 1) y ts h1
    have h3 : y * ts * y⁻¹ * ts⁻¹ ∈ B.K ⊓ B.S := Subgroup.mem_inf.mpr
      ⟨B.K.mul_mem (B.hK.conj_mem ts htsmem'.2.1 y) (B.K.inv_mem htsmem'.2.1),
        B.S.mul_mem (B.hS.conj_mem ts htsmem'.2.2 y) (B.S.inv_mem htsmem'.2.2)⟩
    exact hprev (Subgroup.mem_inf.mpr ⟨h2, h3⟩)
  -- the functional `β := λ([·, ts])` is `Y`-invariant
  have hbeta_conj : ∀ (y k : Y), k ∈ B.K →
      ∀ (h1 : y * k * y⁻¹ * ts * (y * k * y⁻¹)⁻¹ * ts⁻¹ ∈ B.R)
        (h2 : k * ts * k⁻¹ * ts⁻¹ ∈ B.R),
      lam ⟨y * k * y⁻¹ * ts * (y * k * y⁻¹)⁻¹ * ts⁻¹, h1⟩
        = lam ⟨k * ts * k⁻¹ * ts⁻¹, h2⟩ := by
    intro y k hk h1 h2
    -- `[yky⁻¹, ts] = y·[k, y⁻¹ts y]·y⁻¹`
    have hin : y⁻¹ * ts * y ∈ B.K := by
      have := B.hK.conj_mem ts htsK y⁻¹
      simpa using this
    have hmemc : k * (y⁻¹ * ts * y) * k⁻¹ * (y⁻¹ * ts * y)⁻¹ ∈ B.R := comm_mem_R B hk hin
    have e1 : (⟨y * k * y⁻¹ * ts * (y * k * y⁻¹)⁻¹ * ts⁻¹, h1⟩ : ↥B.R)
        = ⟨y * (k * (y⁻¹ * ts * y) * k⁻¹ * (y⁻¹ * ts * y)⁻¹) * y⁻¹,
            hRN.conj_mem _ hmemc y⟩ := Subtype.ext (by
      show y * k * y⁻¹ * ts * (y * k * y⁻¹)⁻¹ * ts⁻¹
        = y * (k * (y⁻¹ * ts * y) * k⁻¹ * (y⁻¹ * ts * y)⁻¹) * y⁻¹
      group)
    rw [e1, hlam_conj y _ hmemc]
    -- `y⁻¹ ts y = w·ts` with `w := [y⁻¹, ts] ∈ T`
    set w := y⁻¹ * ts * y * ts⁻¹ with hw
    have hwT : w ∈ T := by
      rw [hw]
      simpa using hcommT y⁻¹
    have hwK : w ∈ B.K := (Subgroup.mem_inf.mp hwT.1).1
    have e2 : (⟨k * (y⁻¹ * ts * y) * k⁻¹ * (y⁻¹ * ts * y)⁻¹, hmemc⟩ : ↥B.R)
        = ⟨k * (w * ts) * k⁻¹ * (w * ts)⁻¹, comm_mem_R B hk (B.K.mul_mem hwK htsK)⟩ := by
      refine Subtype.ext ?_
      show k * (y⁻¹ * ts * y) * k⁻¹ * (y⁻¹ * ts * y)⁻¹ = k * (w * ts) * k⁻¹ * (w * ts)⁻¹
      rw [hw]
      group
    rw [e2, beta_add_t k w ts hk hwK htsK, hwT.2 k hk (comm_mem_R B hk hwK), zero_add]
  -- the kernel `Z` of `β` inside `K`: a `Y`-normal index-2 subgroup above `R`
  let Z : Subgroup Y :=
    { carrier := {k | k ∈ B.K ∧ ∀ h : k * ts * k⁻¹ * ts⁻¹ ∈ B.R,
        lam ⟨k * ts * k⁻¹ * ts⁻¹, h⟩ = 0}
      one_mem' := by
        refine ⟨one_mem _, fun h => ?_⟩
        have e : (⟨1 * ts * 1⁻¹ * ts⁻¹, h⟩ : ↥B.R) = 1 := Subtype.ext (by
          show 1 * ts * 1⁻¹ * ts⁻¹ = 1
          group)
        rw [e, lam_one]
      mul_mem' := by
        rintro k k' ⟨hkK, hk⟩ ⟨hk'K, hk'⟩
        refine ⟨mul_mem hkK hk'K, fun h => ?_⟩
        have e : (⟨k * k' * ts * (k * k')⁻¹ * ts⁻¹, h⟩ : ↥B.R)
            = ⟨k * k' * ts * (k * k')⁻¹ * ts⁻¹,
                comm_mem_R B (B.K.mul_mem hkK hk'K) htsK⟩ := rfl
        rw [e, beta_add_k k k' ts hkK hk'K htsK, hk (comm_mem_R B hkK htsK),
          hk' (comm_mem_R B hk'K htsK), add_zero]
      inv_mem' := by
        rintro k ⟨hkK, hk⟩
        refine ⟨inv_mem hkK, fun h => ?_⟩
        have h1 := beta_add_k k k⁻¹ ts hkK (B.K.inv_mem hkK) htsK
        have e1 : (⟨k * k⁻¹ * ts * (k * k⁻¹)⁻¹ * ts⁻¹,
            comm_mem_R B (B.K.mul_mem hkK (B.K.inv_mem hkK)) htsK⟩ : ↥B.R) = 1 :=
          Subtype.ext (by
            show k * k⁻¹ * ts * (k * k⁻¹)⁻¹ * ts⁻¹ = 1
            group)
        rw [e1, lam_one, hk (comm_mem_R B hkK htsK), add_zero] at h1
        have e2 : (⟨k⁻¹ * ts * k⁻¹⁻¹ * ts⁻¹, h⟩ : ↥B.R)
            = ⟨k⁻¹ * ts * k⁻¹⁻¹ * ts⁻¹, comm_mem_R B (B.K.inv_mem hkK) htsK⟩ := rfl
        rw [e2, ← h1] }
  have hZn : Z.Normal := by
    constructor
    intro m hm y
    refine ⟨B.hK.conj_mem m hm.1 y, fun h => ?_⟩
    rw [hbeta_conj y m hm.1 h (comm_mem_R B hm.1 htsK)]
    exact hm.2 (comm_mem_R B hm.1 htsK)
  have hRZ : B.R ≤ Z := by
    intro r hr
    exact ⟨frattiniLike_le B.K hr, fun h => beta_R_k r ts hr h⟩
  have hZK : Z ≤ B.K := fun z hz => hz.1
  -- `β` is onto `𝔽₂` (it is nonzero at some `k*`), so `Z` has index 2 in `K`
  have hone : ∀ x : ZMod 2, x ≠ 0 → x = 1 := by decide
  have hsurj : ∃ k, ∃ hk : k ∈ B.K,
      lam ⟨k * ts * k⁻¹ * ts⁻¹, comm_mem_R B hk htsK⟩ = 1 := by
    by_contra hall
    push Not at hall
    refine htsT ⟨htsmem'.2, fun k hk h => ?_⟩
    have e : (⟨k * ts * k⁻¹ * ts⁻¹, h⟩ : ↥B.R)
        = ⟨k * ts * k⁻¹ * ts⁻¹, comm_mem_R B hk htsK⟩ := rfl
    rw [e]
    by_contra hne0
    exact (hall k hk) (hone _ hne0)
  set g' : ↥B.K →* Multiplicative (ZMod 2) :=
    { toFun := fun k =>
        Multiplicative.ofAdd (lam ⟨k.1 * ts * k.1⁻¹ * ts⁻¹, comm_mem_R B k.2 htsK⟩)
      map_one' := by
        have e : (⟨(1 : ↥B.K).1 * ts * (1 : ↥B.K).1⁻¹ * ts⁻¹,
            comm_mem_R B (1 : ↥B.K).2 htsK⟩ : ↥B.R) = 1 := Subtype.ext (by
          show (1 : Y) * ts * (1 : Y)⁻¹ * ts⁻¹ = 1
          group)
        show Multiplicative.ofAdd _ = 1
        rw [e, lam_one]
        rfl
      map_mul' := by
        intro a b
        have e : (⟨(a * b).1 * ts * (a * b).1⁻¹ * ts⁻¹, comm_mem_R B (a * b).2 htsK⟩ : ↥B.R)
            = ⟨a.1 * b.1 * ts * (a.1 * b.1)⁻¹ * ts⁻¹,
                comm_mem_R B (B.K.mul_mem a.2 b.2) htsK⟩ := rfl
        show Multiplicative.ofAdd _ = _
        rw [e, beta_add_k a.1 b.1 ts a.2 b.2 htsK]
        rw [ofAdd_add]
        exact mul_comm _ _ } with hg'
  have hg'app : ∀ x : ↥B.K,
      g' x = Multiplicative.ofAdd (lam ⟨x.1 * ts * x.1⁻¹ * ts⁻¹, comm_mem_R B x.2 htsK⟩) :=
    fun _ => rfl
  have hker : Z.subgroupOf B.K = g'.ker := by
    ext ⟨k, hk⟩
    simp only [Subgroup.mem_subgroupOf, MonoidHom.mem_ker]
    constructor
    · intro hz
      rw [hg'app, hz.2 (comm_mem_R B hk htsK)]
      rfl
    · intro h1
      refine ⟨hk, fun h => ?_⟩
      rw [hg'app] at h1
      have h2 : lam ⟨k * ts * k⁻¹ * ts⁻¹, comm_mem_R B hk htsK⟩ = 0 := by
        have := congrArg Multiplicative.toAdd h1
        simpa using this
      exact h2
  have hidx : (Z.subgroupOf B.K).index = 2 := by
    rw [hker, Subgroup.index_ker]
    have h2 : Nat.card (Multiplicative (ZMod 2)) = 2 := by
      rw [Nat.card_congr Multiplicative.toAdd, Nat.card_zmod]
    have hdvd : Nat.card g'.range ∣ 2 := by
      have h := Subgroup.card_subgroup_dvd_card g'.range
      rwa [h2] at h
    rcases (Nat.prime_two.eq_one_or_self_of_dvd _ hdvd) with h1 | h1
    · exfalso
      obtain ⟨ks, hks, hks1⟩ := hsurj
      have hbot : g'.range = ⊥ := Subgroup.card_eq_one.mp h1
      have hmem : g' ⟨ks, hks⟩ ∈ g'.range := ⟨_, rfl⟩
      rw [hbot, Subgroup.mem_bot] at hmem
      rw [hg'app] at hmem
      have h0 : lam ⟨ks * ts * ks⁻¹ * ts⁻¹, comm_mem_R B hks htsK⟩ = 0 := by
        have := congrArg Multiplicative.toAdd hmem
        simpa using this
      rw [hks1] at h0
      exact one_ne_zero h0
    · exact h1
  exact lemma_7_1_dual B ⟨Z, hZn, hRZ, hZK, hidx⟩

/-- **Prop 7.4, step 2** (`q_λ|_{T₀} = 0`): under the framed-target head — the same tame data
as `lemma_7_2` — a `Y`-invariant additive `λ : R → 𝔽₂` kills the squares of `K ∩ S`.  This is
the genuinely tame step of Prop 7.4 (the paper's shear/extension-splitting argument needing
`H¹(H_V, V^∨) = 0`, by odd tame inertia in the ramified case and odd cyclic action image in
the unramified case).  Mapped route: σ := `λ((·)²)` is (after `lam_comm_vanish`) a
`Y`-invariant hom on `K ∩ S` killing `R`; if nonzero, a base functional `g₀` with
`g₀(t̄₀) = 1` has principal cocycle `c(y) := y·g₀ − g₀` valued in `V^∨` and factoring through
`H* := Y/Y_V` (shear vanishing = quadratic invariance); char-2 odd-averaging over `⟨τ*⟩`
(ramified; `tame_odd_order` + `zpowers_normal_of_tame` + `(V^∨)^{⟨τ*⟩} = 0` by the chief
condition) or over the odd cyclic `H*` (unramified) kills `[c]`, yielding a `Y`-invariant
functional contradicting `lemma_7_1_dual`.  [P-15 helper; sorried pending the averaging
tier.] -/
private theorem lam_sq_vanish {H : Type} [Group H] [TopologicalSpace H] [DiscreteTopology H]
    [Finite H]
    (π : Y →* H) (hπ : Function.Surjective π) (hkerπ : π.ker = L)
    (cH : ContinuousMonoidHom Ttame H) (hcH : Function.Surjective cH)
    (B : MinimalBlock L) (hRN : B.R.Normal)
    (lam : ↥B.R → ZMod 2)
    (hlam_hom : ∀ r r' : ↥B.R, lam (r * r') = lam r + lam r')
    (hlam_conj : ∀ (y r : Y) (hr : r ∈ B.R),
      lam ⟨y * r * y⁻¹, hRN.conj_mem r hr y⟩ = lam ⟨r, hr⟩) :
    ∀ t, t ∈ B.K ⊓ B.S → ∀ (h : t * t ∈ B.R), lam ⟨t * t, h⟩ = 0 := by
  sorry

/-- **Proposition 7.4**: for every nonzero `Y`-invariant functional `λ ∈ D_R = (R^∨)^C`, the
pushout square map of the central extension `1 → 𝔽₂ → K_λ → M → 1` kills `T₀` and its polar
form kills `(T₀, M)`; hence it descends to a **nonzero, nonsingular, `Y`-invariant** quadratic
form `q̄_λ : V → 𝔽₂` on the simple head `V = P/S` — the form §8's Gauss sums live on.
Stated with the square-map spec `λ(k²) = q̄(k mod S)` (`hsq` supplies `k² ∈ R`, Lemma 7.2's
clause, so 7.4 is consumable independently).  [P-14 statement; **P-15 amendment**: the
framed-target head data (as in `lemma_7_2`) restored — §7's standing hypothesis, under which
the paper proves 7.4; its step 2 (`q_λ|_{T₀} = 0`) consumes `H¹(H_V, V^∨) = 0`, which needs
the tame structure and fails for general finite heads.  See `docs/section67-extraction.md`.] -/
theorem prop_7_4 {H : Type} [Group H] [TopologicalSpace H] [DiscreteTopology H] [Finite H]
    (π : Y →* H) (hπ : Function.Surjective π) (hkerπ : π.ker = L)
    (cH : ContinuousMonoidHom Ttame H) (hcH : Function.Surjective cH)
    (B : MinimalBlock L)
    (hRN : B.R.Normal)
    (hsq : ∀ k ∈ B.K, k * k ∈ B.R)
    (lam : ↥B.R → ZMod 2)
    (hlam_hom : ∀ r r' : ↥B.R, lam (r * r') = lam r + lam r')
    (hlam_conj : ∀ (y : Y) (r : Y) (hr : r ∈ B.R),
      lam ⟨y * r * y⁻¹, hRN.conj_mem r hr y⟩ = lam ⟨r, hr⟩)
    (hlam_ne : lam ≠ 0) :
    ∃ qbar : (↥B.P ⧸ (B.S.subgroupOf B.P)) → ZMod 2,
      (∀ (k : Y) (hk : k ∈ B.K), lam ⟨k * k, hsq k hk⟩
        = qbar (QuotientGroup.mk ⟨k, B.hKP hk⟩)) ∧
      qbar ≠ 0 ∧
      (∀ (y : Y) (p : Y) (hp : p ∈ B.P),
        qbar (QuotientGroup.mk ⟨y * p * y⁻¹, B.hP.conj_mem p hp y⟩)
          = qbar (QuotientGroup.mk ⟨p, hp⟩)) := by
  classical
  haveI := B.hS
  have hB := lam_comm_vanish B hRN lam hlam_hom hlam_conj
  have hA := lam_sq_vanish π hπ hkerπ cH hcH B hRN lam hlam_hom hlam_conj
  -- master well-definedness: representatives in the same `S`-coset have equal square-values
  have hwd : ∀ (k k' : Y) (hk : k ∈ B.K) (hk' : k' ∈ B.K),
      (QuotientGroup.mk (⟨k, B.hKP hk⟩ : ↥B.P) :
        ↥B.P ⧸ B.S.subgroupOf B.P) = QuotientGroup.mk ⟨k', B.hKP hk'⟩ →
      lam ⟨k * k, hsq k hk⟩ = lam ⟨k' * k', hsq k' hk'⟩ := by
    intro k k' hk hk' hmk
    rw [QuotientGroup.eq] at hmk
    have htS : k⁻¹ * k' ∈ B.S := Subgroup.mem_subgroupOf.mp hmk
    have htK : k⁻¹ * k' ∈ B.K := B.K.mul_mem (B.K.inv_mem hk) hk'
    have hcm : k⁻¹ * (k⁻¹ * k') * k⁻¹⁻¹ * (k⁻¹ * k')⁻¹ ∈ B.R :=
      comm_mem_R B (B.K.inv_mem hk) htK
    have e : (⟨k' * k', hsq k' hk'⟩ : ↥B.R)
        = (⟨k * k, hsq k hk⟩ * ⟨k⁻¹ * (k⁻¹ * k') * k⁻¹⁻¹ * (k⁻¹ * k')⁻¹, hcm⟩)
            * ⟨(k⁻¹ * k') * (k⁻¹ * k'), hsq _ htK⟩ := Subtype.ext (by
      show k' * k'
        = k * k * (k⁻¹ * (k⁻¹ * k') * k⁻¹⁻¹ * (k⁻¹ * k')⁻¹) * ((k⁻¹ * k') * (k⁻¹ * k'))
      group)
    rw [e, hlam_hom, hlam_hom,
      hB k⁻¹ (B.K.inv_mem hk) (k⁻¹ * k') (Subgroup.mem_inf.mpr ⟨htK, htS⟩) hcm,
      hA (k⁻¹ * k') (Subgroup.mem_inf.mpr ⟨htK, htS⟩) (hsq _ htK), add_zero, add_zero]
  -- every class has a `K`-representative
  have hdec : ∀ v : ↥B.P ⧸ B.S.subgroupOf B.P,
      ∃ k, ∃ hk : k ∈ B.K, (QuotientGroup.mk (⟨k, B.hKP hk⟩ : ↥B.P) :
        ↥B.P ⧸ B.S.subgroupOf B.P) = v := by
    intro v
    obtain ⟨p, rfl⟩ := QuotientGroup.mk_surjective v
    have hp' : (p : Y) ∈ (B.K : Set Y) * (B.S : Set Y) := by
      rw [← Subgroup.mul_normal B.K B.S, B.gen]
      exact p.2
    obtain ⟨k, hk, s, hs, hks⟩ := hp'
    refine ⟨k, hk, ?_⟩
    rw [QuotientGroup.eq]
    refine Subgroup.mem_subgroupOf.mpr ?_
    show k⁻¹ * (p : Y) ∈ B.S
    have hkp : k⁻¹ * (p : Y) = s := by rw [← hks]; group
    rw [hkp]
    exact hs
  choose w hwK hwmk using hdec
  refine ⟨fun v => lam ⟨w v * w v, hsq (w v) (hwK v)⟩, ?_, ?_, ?_⟩
  · -- the square-map spec
    intro k hk
    exact (hwd (w _) k (hwK _) hk (hwmk _)).symm
  · -- nonzero
    intro h0
    have h0v : ∀ v, lam ⟨w v * w v, hsq (w v) (hwK v)⟩ = 0 := fun v => congrFun h0 v
    have lam_one : lam 1 = 0 := by
      have h := hlam_hom 1 1
      rw [one_mul] at h
      have h2 : (0 : ZMod 2) + lam 1 = lam 1 + lam 1 := by rw [zero_add]; exact h
      exact (add_right_cancel h2).symm
    -- squares vanish under λ
    have hsqv : ∀ (k : Y) (hk : k ∈ B.K), lam ⟨k * k, hsq k hk⟩ = 0 := by
      intro k hk
      rw [hwd k (w _) hk (hwK _) (hwmk _).symm]
      exact h0v _
    -- commutators vanish under λ
    have hcomm0 : ∀ (a b : Y), a ∈ B.K → b ∈ B.K →
        ∀ h : a * b * a⁻¹ * b⁻¹ ∈ B.R, lam ⟨a * b * a⁻¹ * b⁻¹, h⟩ = 0 := by
      intro a b ha hb h
      have hx : a⁻¹ ∈ B.K := B.K.inv_mem ha
      have hxy : a⁻¹ * b ∈ B.K := B.K.mul_mem hx hb
      have e : (⟨(a⁻¹ * b) * (a⁻¹ * b), hsq _ hxy⟩ : ↥B.R)
          = (⟨a⁻¹ * a⁻¹, hsq _ hx⟩ * ⟨a * b * a⁻¹ * b⁻¹, h⟩) * ⟨b * b, hsq b hb⟩ :=
        Subtype.ext (by
          show (a⁻¹ * b) * (a⁻¹ * b) = a⁻¹ * a⁻¹ * (a * b * a⁻¹ * b⁻¹) * (b * b)
          group)
      have h1 := hsqv (a⁻¹ * b) hxy
      rw [e, hlam_hom, hlam_hom, hsqv a⁻¹ hx, hsqv b hb, zero_add, add_zero] at h1
      exact h1
    -- so λ kills all of `R = Φ(K)`, contradicting `hlam_ne`
    let Z' : Subgroup Y :=
      { carrier := {x | ∃ hx : x ∈ B.R, lam ⟨x, hx⟩ = 0}
        one_mem' := ⟨one_mem _, lam_one⟩
        mul_mem' := by
          rintro a b ⟨ha, la⟩ ⟨hb, lb⟩
          refine ⟨mul_mem ha hb, ?_⟩
          have h := hlam_hom ⟨a, ha⟩ ⟨b, hb⟩
          rw [la, lb, add_zero] at h
          exact h
        inv_mem' := by
          rintro a ⟨ha, la⟩
          refine ⟨inv_mem ha, ?_⟩
          have h := hlam_hom ⟨a, ha⟩ ⟨a⁻¹, inv_mem ha⟩
          have e : (⟨a, ha⟩ * ⟨a⁻¹, inv_mem ha⟩ : ↥B.R) = 1 := Subtype.ext (by
            show a * a⁻¹ = 1
            group)
          rw [e, lam_one, la, zero_add] at h
          exact h.symm }
    have hRZ : B.R ≤ Z' := by
      refine (Subgroup.closure_le _).mpr ?_
      rintro x (⟨k, hk, rfl⟩ | ⟨k, hk, l, hl, rfl⟩)
      · exact ⟨sq_mem_R B hk, hsqv k hk⟩
      · exact ⟨comm_mem_R B hk hl, hcomm0 k l hk hl _⟩
    apply hlam_ne
    funext r
    obtain ⟨hr', h0'⟩ := hRZ r.2
    have hre : lam r = lam ⟨r.1, hr'⟩ := rfl
    rw [hre, h0']
    rfl
  · -- `Y`-invariance
    intro y p hp
    have hkK : w (QuotientGroup.mk ⟨p, hp⟩) ∈ B.K := hwK _
    set k := w (QuotientGroup.mk ⟨p, hp⟩) with hkdef
    have hkpS : k⁻¹ * p ∈ B.S := by
      have hkp := hwmk (QuotientGroup.mk (⟨p, hp⟩ : ↥B.P))
      rw [QuotientGroup.eq] at hkp
      exact Subgroup.mem_subgroupOf.mp hkp
    have hmk1 : (QuotientGroup.mk (⟨y * k * y⁻¹, B.hKP (B.hK.conj_mem k hkK y)⟩ : ↥B.P) :
        ↥B.P ⧸ B.S.subgroupOf B.P)
          = QuotientGroup.mk ⟨y * p * y⁻¹, B.hP.conj_mem p hp y⟩ := by
      rw [QuotientGroup.eq]
      refine Subgroup.mem_subgroupOf.mpr ?_
      show (y * k * y⁻¹)⁻¹ * (y * p * y⁻¹) ∈ B.S
      have e : (y * k * y⁻¹)⁻¹ * (y * p * y⁻¹) = y * (k⁻¹ * p) * y⁻¹ := by group
      rw [e]
      exact B.hS.conj_mem _ hkpS y
    have step1 : lam ⟨w (QuotientGroup.mk ⟨y * p * y⁻¹, B.hP.conj_mem p hp y⟩)
          * w (QuotientGroup.mk ⟨y * p * y⁻¹, B.hP.conj_mem p hp y⟩), hsq _ (hwK _)⟩
        = lam ⟨(y * k * y⁻¹) * (y * k * y⁻¹), hsq _ (B.hK.conj_mem k hkK y)⟩ :=
      hwd (w _) (y * k * y⁻¹) (hwK _) (B.hK.conj_mem k hkK y) ((hwmk _).trans hmk1.symm)
    have step2 : lam ⟨(y * k * y⁻¹) * (y * k * y⁻¹), hsq _ (B.hK.conj_mem k hkK y)⟩
        = lam ⟨k * k, hsq k hkK⟩ := by
      have e : (⟨(y * k * y⁻¹) * (y * k * y⁻¹), hsq _ (B.hK.conj_mem k hkK y)⟩ : ↥B.R)
          = ⟨y * (k * k) * y⁻¹, hRN.conj_mem _ (hsq k hkK) y⟩ := Subtype.ext (by
        show (y * k * y⁻¹) * (y * k * y⁻¹) = y * (k * k) * y⁻¹
        group)
      rw [e]
      exact hlam_conj y (k * k) (hsq k hkK)
    exact step1.trans step2

end SectionSeven

end GQ2
