/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import GQ2.Reciprocity
import GQ2.UnramifiedNorm
import GQ2.HilbertLedger

/-!
# P-15f2c2c2 (N2): the CFT unit-index equals the ramification index

For a finite **abelian** Galois layer `F/ℚ₂` inside `ℚ̄₂ = AlgebraicClosure ℚ_[2]`, local class
field theory (B5, `LocalReciprocity.norm_reciprocity`) identifies `Gal(F/ℚ₂) ≅ ℚ₂ˣ / N_{F/ℚ₂}(Fˣ)`,
and the **inertia subgroup** — the image of the units `ℤ₂ˣ ↪ ℚ₂ˣ` under reciprocity — has order the
ramification index `e = FF.e`.  This file proves that count:

```
Nat.card ↥(((restrictAb F hab).comp R.recip).comp unitEmbed).range = FF.e.
```

**Design (`docs/p15f2c2c-handoff.md` §3 N2, scoping §half-(B) step 3).**  With `n := finrank ℚ₂ F`,
`N := normSubgroup F`, `U := unitEmbed.range` (`= ker v₂`):

* `norm_val` (analytic core): `‖(Algebra.norm ℚ₂ x : ℚ₂)‖ = ‖(x : ℚ̄₂)‖ ^ n`, via
  `Algebra.norm_eq_prod_automorphisms` + lifting each `F ≃ₐ F` to `ℚ̄₂`
  (`restrictNormalHom_surjective` + `restrictNormal_commutes`) + `norm_galois`, then
  `card_aut_eq_finrank`;
* the integer identity `e · v₂(Norm x) = n · v_F(x)` (`norm_eq_zpow` + `FF.he`, raising `‖·‖` to the
  `e` to avoid fractions);
* `v₂(N(Fˣ)) = f₀·ℤ` for `f₀ := v₂(Norm π_F)` (so `e·f₀ = n`, `normValPi_dvd_v2_of_mem`); hence
  `Gal ⧸ (unit-image)` is cyclic, generated by the class of `rec(2)` of order `f₀`
  (`q^k = 1 ↔ f₀ ∣ k` — plain `orderOf` arithmetic, no `relindex` calculus), and
  `#(unit-image)·f₀ = #Gal = n = e·f₀` forces `#(unit-image) = e` (`Subgroup.card_mul_index`).

Kept **parametric** over `(R : LocalReciprocity)` and `(FF : DyadicUnitFiltration F)` (the
Reciprocity.lean stress-test / half-A idiom), so the statement is **std-3**; the axioms B5/B13 enter
only when the c2c4 assembly instantiates `R := localReciprocity`, `FF := dyadicUnitFiltration F`.
-/

namespace GQ2

namespace UnitNormIndex

open scoped Classical
open IntermediateField

local notation "ℚ̄₂" => AlgebraicClosure ℚ_[2]

/-- **Analytic core.**  The `ℚ₂`-norm of `x ∈ F` has spectral absolute value `‖x‖^{[F:ℚ₂]}`: the
norm is the product over `Gal(F/ℚ₂)` of the conjugates (`Algebra.norm_eq_prod_automorphisms`), each
conjugate has the same spectral norm as `x` (lift the `F`-automorphism to `ℚ̄₂` and apply
`norm_galois`), and there are `finrank ℚ₂ F` of them (`card_aut_eq_finrank`). -/
theorem norm_val (F : IntermediateField ℚ_[2] ℚ̄₂) [FiniteDimensional ℚ_[2] F] [IsGalois ℚ_[2] F]
    (x : F) :
    ‖(Algebra.norm ℚ_[2] x : ℚ_[2])‖ = ‖(x : ℚ̄₂)‖ ^ (Module.finrank ℚ_[2] F) := by
  -- each `F`-automorphism preserves the spectral norm (lift to `ℚ̄₂`)
  have hconj : ∀ σ : F ≃ₐ[ℚ_[2]] F, ‖algebraMap F ℚ̄₂ (σ x)‖ = ‖algebraMap F ℚ̄₂ x‖ := by
    intro σ
    obtain ⟨g, hg⟩ := AlgEquiv.restrictNormalHom_surjective (F := ℚ_[2]) (K₁ := F) (E := ℚ̄₂) σ
    have hcomm : (algebraMap F ℚ̄₂ (σ x)) = g (algebraMap F ℚ̄₂ x) := by
      rw [← hg]; exact (AlgEquiv.restrictNormal_commutes g F x)
    have hg2 := norm_galois g (algebraMap F ℚ̄₂ x)
    rw [AlgEquiv.smul_def] at hg2
    rw [hcomm, hg2]
  -- the norm as a product over automorphisms, coerced to `ℚ̄₂`
  have hprod : algebraMap ℚ_[2] F (Algebra.norm ℚ_[2] x) = ∏ σ : F ≃ₐ[ℚ_[2]] F, σ x :=
    Algebra.norm_eq_prod_automorphisms ℚ_[2] x
  have hcoe : (algebraMap ℚ_[2] ℚ̄₂ (Algebra.norm ℚ_[2] x))
      = ∏ σ : F ≃ₐ[ℚ_[2]] F, algebraMap F ℚ̄₂ (σ x) := by
    rw [IsScalarTower.algebraMap_apply ℚ_[2] F ℚ̄₂, hprod, map_prod]
  have hxcoe : (x : ℚ̄₂) = algebraMap F ℚ̄₂ x := rfl
  rw [hxcoe, ← norm_algebraMap' (𝕜' := ℚ̄₂) (Algebra.norm ℚ_[2] x), hcoe, norm_prod,
    Finset.prod_congr rfl (fun σ _ => hconj σ), Finset.prod_const, Finset.card_univ,
    ← IsGalois.card_aut_eq_finrank ℚ_[2] F, Nat.card_eq_fintype_card]

/-- `‖(2 : ℚ₂)‖ = 2 ^ (-1)`: `v₂(2) = 1`. -/
theorem norm_two : ‖(2 : ℚ_[2])‖ = (2 : ℝ) ^ (-1 : ℤ) := by
  rw [Padic.norm_eq_zpow_neg_valuation (by norm_num : (2 : ℚ_[2]) ≠ 0)]
  congr 1
  rw [show (2 : ℚ_[2]) = ((2 : ℕ) : ℚ_[2]) by norm_num, Padic.valuation_p]

/-- **The ramification identity.**  For `y ∈ Fˣ` with `‖(y:ℚ̄₂)‖ = ‖π_F‖^m` (the value-group
exponent, `norm_eq_zpow`), `e · v₂(N_{F/ℚ₂} y) = [F:ℚ₂] · m`.  (Raise `‖N y‖ = ‖π_F‖^{n·m}` to the
`e` and match `2`-power exponents: `‖π_F‖^e = ‖2‖ = 2^{-1}`.) -/
theorem e_mul_val_norm (F : IntermediateField ℚ_[2] ℚ̄₂) [FiniteDimensional ℚ_[2] F]
    [IsGalois ℚ_[2] F] (FF : DyadicUnitFiltration F) (y : F) (hy : y ≠ 0) (m : ℤ)
    (hm : ‖(y : ℚ̄₂)‖ = ‖FF.π‖ ^ m) :
    (FF.e : ℤ) * (Algebra.norm ℚ_[2] y).valuation = (Module.finrank ℚ_[2] F : ℤ) * m := by
  have hny : (Algebra.norm ℚ_[2] y : ℚ_[2]) ≠ 0 := Algebra.norm_ne_zero_iff.mpr hy
  have hN2 : ‖(Algebra.norm ℚ_[2] y : ℚ_[2])‖ = (2 : ℝ) ^ (-(Algebra.norm ℚ_[2] y).valuation) := by
    rw [Padic.norm_eq_zpow_neg_valuation hny]; norm_num
  have hBe : ‖FF.π‖ ^ (FF.e : ℤ) = (2 : ℝ) ^ (-1 : ℤ) := by
    rw [zpow_natCast, ← FF.he, show (2 : ℚ̄₂) = algebraMap ℚ_[2] ℚ̄₂ 2 from (map_ofNat _ 2).symm,
      norm_algebraMap' (𝕜' := ℚ̄₂), norm_two]
  have hNB : ‖(Algebra.norm ℚ_[2] y : ℚ_[2])‖
      = ‖FF.π‖ ^ ((Module.finrank ℚ_[2] F : ℤ) * m) := by
    rw [norm_val F y, hm, ← zpow_natCast (‖FF.π‖ ^ m) (Module.finrank ℚ_[2] F), ← zpow_mul]
    congr 1; ring
  have hcombine : (2 : ℝ) ^ (-(Algebra.norm ℚ_[2] y).valuation * (FF.e : ℤ))
      = (2 : ℝ) ^ (-((Module.finrank ℚ_[2] F : ℤ) * m)) := by
    calc (2 : ℝ) ^ (-(Algebra.norm ℚ_[2] y).valuation * (FF.e : ℤ))
        = ((2 : ℝ) ^ (-(Algebra.norm ℚ_[2] y).valuation)) ^ (FF.e : ℤ) := by rw [← zpow_mul]
      _ = ‖(Algebra.norm ℚ_[2] y : ℚ_[2])‖ ^ (FF.e : ℤ) := by rw [← hN2]
      _ = (‖FF.π‖ ^ ((Module.finrank ℚ_[2] F : ℤ) * m)) ^ (FF.e : ℤ) := by rw [hNB]
      _ = (‖FF.π‖ ^ (FF.e : ℤ)) ^ ((Module.finrank ℚ_[2] F : ℤ) * m) := by
            rw [← zpow_mul, ← zpow_mul, mul_comm]
      _ = ((2 : ℝ) ^ (-1 : ℤ)) ^ ((Module.finrank ℚ_[2] F : ℤ) * m) := by rw [hBe]
      _ = (2 : ℝ) ^ (-((Module.finrank ℚ_[2] F : ℤ) * m)) := by rw [← zpow_mul]; ring_nf
  have hinj := zpow_right_injective₀ (by norm_num : (0 : ℝ) < 2) (by norm_num : (2 : ℝ) ≠ 1) hcombine
  linarith [hinj]

/-! ## The `v₂`-calculus on `ℚ₂ˣ` and the uniformizer-unit decomposition -/

section V2Calc

/-- `v₂` is additive: units of `ℚ₂` are nonzero, so `Padic.valuation_mul` applies. -/
theorem v2_mul (x y : ℚ_[2]ˣ) : v2 (x * y) = v2 x + v2 y := by
  simp only [v2, Units.val_mul]
  exact Padic.valuation_mul x.ne_zero y.ne_zero

/-- `v₂(x^k) = k·v₂(x)` for `k : ℤ`. -/
theorem v2_zpow (x : ℚ_[2]ˣ) (k : ℤ) : v2 (x ^ k) = k * v2 x := by
  simp [v2, Units.val_zpow_eq_zpow_val, Padic.valuation_zpow]

/-- `v₂(x⁻¹) = -v₂(x)`. -/
theorem v2_inv (x : ℚ_[2]ˣ) : v2 x⁻¹ = -v2 x := by
  simp [v2, Units.val_inv_eq_inv_val, Padic.valuation_inv]

/-- `v₂(2) = 1`. -/
theorem v2_uniformizer : v2 uniformizer = 1 := by
  show ((uniformizer : ℚ_[2]ˣ) : ℚ_[2]).valuation = 1
  rw [uniformizer_val, show (2 : ℚ_[2]) = ((2 : ℕ) : ℚ_[2]) by norm_num, Padic.valuation_p]

/-- `v₂` kills the `ℤ₂`-units (`u` and `u⁻¹` are both `2`-adic integers, so both valuations are
`≥ 0` and they sum to `0`). -/
theorem v2_unitEmbed (u : ℤ_[2]ˣ) : v2 (unitEmbed u) = 0 := by
  have hnn : ∀ w : ℤ_[2]ˣ, 0 ≤ v2 (unitEmbed w) := by
    intro w
    show 0 ≤ ((unitEmbed w : ℚ_[2]ˣ) : ℚ_[2]).valuation
    rw [unitEmbed_val, PadicInt.algebraMap_apply]
    exact PadicInt.valuation_coe_nonneg
  have hadd : v2 (unitEmbed u) + v2 (unitEmbed u⁻¹) = 0 := by
    rw [← v2_mul, ← map_mul, mul_inv_cancel, map_one]
    show ((1 : ℚ_[2]ˣ) : ℚ_[2]).valuation = 0
    rw [Units.val_one, Padic.valuation_one]
  have h1 := hnn u
  have h2 := hnn u⁻¹
  omega

/-- **`ker v₂ = unitEmbed.range`**, the substantive inclusion: a `ℚ₂ˣ`-element of valuation `0`
is the embedding of a `ℤ₂`-unit — `ℤ₂` is literally `{x : ℚ₂ // ‖x‖ ≤ 1}`, and
`PadicInt.isUnit_iff` detects units by norm `1`. -/
theorem mem_unitEmbed_range_of_v2_eq_zero {x : ℚ_[2]ˣ} (hx : v2 x = 0) :
    x ∈ unitEmbed.range := by
  have hx0 : ((x : ℚ_[2]ˣ) : ℚ_[2]) ≠ 0 := Units.ne_zero x
  have hnorm : ‖((x : ℚ_[2]ˣ) : ℚ_[2])‖ = 1 := by
    rw [Padic.norm_eq_zpow_neg_valuation hx0,
      show ((x : ℚ_[2]ˣ) : ℚ_[2]).valuation = 0 from hx, neg_zero, zpow_zero]
  let z : ℤ_[2] := ⟨(x : ℚ_[2]), hnorm.le⟩
  have hz1 : ‖z‖ = 1 := hnorm
  obtain ⟨w, hw⟩ := PadicInt.isUnit_iff.mpr hz1
  refine ⟨w, Units.ext ?_⟩
  show ((unitEmbed w : ℚ_[2]ˣ) : ℚ_[2]) = (x : ℚ_[2])
  rw [unitEmbed_val, PadicInt.algebraMap_apply, hw]

/-- **The uniformizer-unit decomposition** of `ℚ₂ˣ`: every `x` is `2^{v₂(x)}·u` with `u ∈ ℤ₂ˣ`. -/
theorem eq_zpow_uniformizer_mul_unit (x : ℚ_[2]ˣ) :
    ∃ u : ℤ_[2]ˣ, x = uniformizer ^ v2 x * unitEmbed u := by
  have h0 : v2 (uniformizer ^ (-v2 x) * x) = 0 := by
    rw [v2_mul, v2_zpow, v2_uniformizer]; ring
  obtain ⟨u, hu⟩ := mem_unitEmbed_range_of_v2_eq_zero h0
  refine ⟨u, ?_⟩
  rw [hu, ← mul_assoc, ← zpow_add, add_neg_cancel, zpow_zero, one_mul]

end V2Calc

/-! ## The norm-valuation `f₀ := v₂(N_{F/ℚ₂}(π_F))` and the valuation image of the norm
subgroup -/

section NormVal

variable (F : IntermediateField ℚ_[2] ℚ̄₂) [FiniteDimensional ℚ_[2] F] [IsGalois ℚ_[2] F]

/-- The uniformizer `π_F` as a unit of the field `↥F`. -/
noncomputable def piUnit (FF : DyadicUnitFiltration F) : (↥F)ˣ :=
  Units.mk0 ⟨FF.π, FF.hπ_mem⟩ fun h => FF.hπ_ne (by simpa using congrArg Subtype.val h)

/-- `f₀ := v₂(N_{F/ℚ₂}(π_F))`, the valuation of the norm of the uniformizer.  (This is the
residue degree `f = n/e`; we never need that identification, only `e·f₀ = n` and the divisibility
`f₀ ∣ v₂(N(Fˣ))`.) -/
noncomputable def normValPi (FF : DyadicUnitFiltration F) : ℤ :=
  v2 (Units.map (Algebra.norm ℚ_[2] (S := F)) (piUnit F FF))

/-- `e · f₀ = n` — the `m = 1` case of `e_mul_val_norm` at `y = π_F`. -/
theorem e_mul_normValPi (FF : DyadicUnitFiltration F) :
    (FF.e : ℤ) * normValPi F FF = (Module.finrank ℚ_[2] F : ℤ) := by
  have h := e_mul_val_norm F FF ((piUnit F FF : ↥F)) (Units.ne_zero _) 1
    (by rw [zpow_one]; rfl)
  rw [mul_one] at h
  simpa [normValPi, v2, piUnit] using h

/-- `f₀ ≥ 1`. -/
theorem normValPi_pos (FF : DyadicUnitFiltration F) : 1 ≤ normValPi F FF := by
  have h := e_mul_normValPi F FF
  have hn : 0 < (Module.finrank ℚ_[2] F : ℤ) := by exact_mod_cast Module.finrank_pos
  have he : 0 < (FF.e : ℤ) := by exact_mod_cast FF.he_pos
  nlinarith

/-- **`v₂` maps the norm subgroup into `f₀·ℤ`**: every norm from `Fˣ` has valuation a multiple
of `f₀` (the value-group exponent of `y` scales through `e_mul_val_norm`, and `e` cancels). -/
theorem normValPi_dvd_v2_of_mem (FF : DyadicUnitFiltration F) {x : ℚ_[2]ˣ}
    (hx : x ∈ normSubgroup F) : normValPi F FF ∣ v2 x := by
  obtain ⟨y, rfl⟩ := hx
  have hy0F : (y : ↥F) ≠ 0 := Units.ne_zero y
  have hy0 : ((y : ↥F) : ℚ̄₂) ≠ 0 := by exact_mod_cast hy0F
  obtain ⟨m, hm⟩ := UnramifiedNorm.norm_eq_zpow FF (SetLike.coe_mem (y : ↥F)) hy0
  have h := e_mul_val_norm F FF (y : ↥F) hy0F m hm
  have he := e_mul_normValPi F FF
  have hene : (FF.e : ℤ) ≠ 0 := Int.natCast_ne_zero.mpr (Nat.one_le_iff_ne_zero.mp FF.he_pos)
  refine ⟨m, mul_left_cancel₀ hene ?_⟩
  have hval : v2 (Units.map (Algebra.norm ℚ_[2] (S := F)) y)
      = (Algebra.norm ℚ_[2] ((y : ↥F))).valuation := by
    simp [v2]
  rw [hval, h, ← he]
  ring

omit [IsGalois ℚ_[2] ↥F] in
/-- Realizing the multiples: for every `m`, some norm has valuation `f₀·m` — namely
`N(π_F^m)`. -/
theorem exists_mem_normSubgroup_v2_eq (FF : DyadicUnitFiltration F) (m : ℤ) :
    ∃ w ∈ normSubgroup F, v2 w = normValPi F FF * m := by
  refine ⟨Units.map (Algebra.norm ℚ_[2] (S := F)) (piUnit F FF ^ m),
    ⟨piUnit F FF ^ m, rfl⟩, ?_⟩
  rw [map_zpow, v2_zpow]
  simp only [normValPi]
  ring

end NormVal

/-! ## The main count: the unit-image in `Gal(F/ℚ₂)` has exactly `e` elements -/

/-- **P-15f2c2c2, the deliverable.**  For a finite abelian Galois layer `F/ℚ₂` with B13
filtration data `FF`, the image in `Gal(F/ℚ₂)` of the `ℤ₂`-units under the (bundled) reciprocity
map has exactly `FF.e` elements — "inertia has order `e`", in the only vocabulary the repo
carries (no inertia subgroup, no residue fields).

Proof shape (see the module docstring): the quotient of `Gal(F/ℚ₂)` by the unit-image `Gu` is
generated by the class `q` of `φ(2)` (uniformizer-unit decomposition + B5(a) surjectivity), and
`q^k = 1 ↔ f₀ ∣ k` (B5(a) kernel = norm subgroup + the `v₂`-bookkeeping of `normValPi`), so
`[Gal : Gu] = orderOf q = f₀` and `#Gu · f₀ = n = e · f₀`.

Parametric in `R : LocalReciprocity` and `FF` (the half-A idiom): this statement is **std-3**;
the axioms B5/B13 enter only when the c2c4 assembly instantiates `R := localReciprocity`,
`FF := dyadicUnitFiltration F`.  Consumed by c2c4 at `F := F₀ = L^{⟨t⟩}` to convert
"unit-image is odd" into "`e_{F₀}` is odd". -/
theorem card_unitImage_eq_e (R : LocalReciprocity) (F : IntermediateField ℚ_[2] ℚ̄₂)
    [FiniteDimensional ℚ_[2] F] [IsGalois ℚ_[2] F]
    (hab : ∀ σ τ : (F ≃ₐ[ℚ_[2]] F), σ * τ = τ * σ) (FF : DyadicUnitFiltration F) :
    Nat.card (((restrictAb F hab).comp R.recip).comp unitEmbed).range = FF.e := by
  obtain ⟨hsurj, hker⟩ := R.norm_reciprocity F hab
  set φ : ℚ_[2]ˣ →* (F ≃ₐ[ℚ_[2]] F) := (restrictAb F hab).comp R.recip with hφ
  set Gu : Subgroup (F ≃ₐ[ℚ_[2]] F) := (φ.comp unitEmbed).range with hGu
  haveI hGuN : Gu.Normal := by
    refine ⟨fun n hn g => ?_⟩
    have hcomm : g * n * g⁻¹ = n := by rw [hab g n, mul_inv_cancel_right]
    rwa [hcomm]
  have hf0pos : 1 ≤ normValPi F FF := normValPi_pos F FF
  have hcast : ((normValPi F FF).toNat : ℤ) = normValPi F FF := Int.toNat_of_nonneg (by omega)
  set q : (F ≃ₐ[ℚ_[2]] F) ⧸ Gu := (QuotientGroup.mk (φ uniformizer)) with hqdef
  -- unit-embeds die in the quotient
  have hUdie : ∀ u : ℤ_[2]ˣ,
      (QuotientGroup.mk (φ (unitEmbed u)) : (F ≃ₐ[ℚ_[2]] F) ⧸ Gu) = 1 :=
    fun u => (QuotientGroup.eq_one_iff _).mpr ⟨u, rfl⟩
  -- (1) `q` generates the quotient
  have hgen : ∀ z : (F ≃ₐ[ℚ_[2]] F) ⧸ Gu, z ∈ Subgroup.zpowers q := by
    intro z
    obtain ⟨g, rfl⟩ := QuotientGroup.mk_surjective z
    obtain ⟨x, rfl⟩ := hsurj g
    obtain ⟨u, hu⟩ := eq_zpow_uniformizer_mul_unit x
    rw [Subgroup.mem_zpowers_iff]
    refine ⟨v2 x, ?_⟩
    rw [hqdef, ← QuotientGroup.mk_zpow, ← map_zpow]
    conv_rhs => rw [hu]
    rw [map_mul, QuotientGroup.mk_mul, hUdie u, mul_one]
  -- (2) `q^k = 1 ↔ f₀ ∣ k`
  have hpow : ∀ k : ℤ, q ^ k = 1 ↔ normValPi F FF ∣ k := by
    intro k
    rw [hqdef, ← QuotientGroup.mk_zpow, ← map_zpow, QuotientGroup.eq_one_iff]
    constructor
    · rintro ⟨u, hu⟩
      rw [MonoidHom.comp_apply] at hu
      have hN : uniformizer ^ k * (unitEmbed u)⁻¹ ∈ normSubgroup F := by
        rw [← hker, MonoidHom.mem_ker, map_mul, map_inv, ← hu, mul_inv_cancel]
      have hdvd := normValPi_dvd_v2_of_mem F FF hN
      rwa [v2_mul, v2_zpow, v2_uniformizer, mul_one, v2_inv, v2_unitEmbed, neg_zero,
        add_zero] at hdvd
    · rintro ⟨m, rfl⟩
      obtain ⟨w, hwN, hwv⟩ := exists_mem_normSubgroup_v2_eq F FF m
      have hv0 : v2 (uniformizer ^ (normValPi F FF * m) * w⁻¹) = 0 := by
        rw [v2_mul, v2_zpow, v2_uniformizer, mul_one, v2_inv, hwv]; ring
      obtain ⟨u, hu⟩ := mem_unitEmbed_range_of_v2_eq_zero hv0
      have hw1 : φ w = 1 := by rw [← MonoidHom.mem_ker, hker]; exact hwN
      refine ⟨u, ?_⟩
      rw [MonoidHom.comp_apply, hu, map_mul, map_inv, hw1, inv_one, mul_one]
  -- (3) `orderOf q = f₀`
  have horder : orderOf q = (normValPi F FF).toNat := by
    have h1 : orderOf q ∣ (normValPi F FF).toNat := orderOf_dvd_of_pow_eq_one (by
      have h := (hpow (normValPi F FF)).mpr dvd_rfl
      rwa [← hcast, zpow_natCast] at h)
    have h2 : (normValPi F FF).toNat ∣ orderOf q := by
      have hq1 : q ^ ((orderOf q : ℕ) : ℤ) = 1 := by
        rw [zpow_natCast, pow_orderOf_eq_one]
      have h := (hpow ((orderOf q : ℕ) : ℤ)).mp hq1
      rwa [← hcast, Int.natCast_dvd_natCast] at h
    exact Nat.dvd_antisymm h1 h2
  -- (4) the quotient has `f₀` elements
  have hcardQ : Nat.card ((F ≃ₐ[ℚ_[2]] F) ⧸ Gu) = (normValPi F FF).toNat := by
    have htop : Subgroup.zpowers q = ⊤ := (Subgroup.eq_top_iff' _).mpr hgen
    rw [← horder, ← Nat.card_zpowers, htop, Subgroup.card_top]
  -- (5) assemble: `#Gu · f₀ = #Gal = n = e · f₀`
  have hcards := Subgroup.card_mul_index Gu
  rw [Subgroup.index_eq_card, hcardQ] at hcards
  have hcardG : Nat.card (F ≃ₐ[ℚ_[2]] F) = Module.finrank ℚ_[2] F :=
    IsGalois.card_aut_eq_finrank ℚ_[2] F
  rw [hcardG] at hcards
  have hef : FF.e * (normValPi F FF).toNat = Module.finrank ℚ_[2] F := by
    have h := e_mul_normValPi F FF
    rw [← hcast] at h
    exact_mod_cast h
  have hfin : Nat.card Gu * (normValPi F FF).toNat = FF.e * (normValPi F FF).toNat := by
    rw [hcards, hef]
  exact Nat.eq_of_mul_eq_mul_right (by omega) hfin

end UnitNormIndex

end GQ2
