import GQ2.DeepPart

/-!
# P-15f3: `prop_6_18_unramified` via the Hermitian-line model

The unramified case of Proposition 6.18 (eq. (115)): for a simple faithful `𝔽₂[C]`-module `V`
of cardinality `2^{2m}` at an **unramified** marking (`c tameTau` acts trivially), the base
determinant form `Q⁰_loc` has the negative Gauss sign:
`#(Q⁰_loc)⁻¹(0) = 2^{2m−1} − 2^{m−1}`.

Unlike the ramified case (which routes through Lemma 6.17's self-perpendicularity + vanishing,
`GQ2.DeepPart.card_Q0loc_zero_eq_of_dim_of_vanish`, hardwired to the `+` sign), the unramified
minus-type count comes from the **Hermitian-line model**: `V` is identified with a finite field
`F = 𝔽_{2^{2m}}` (Schur, `C` cyclic hence `𝔽₂[C]`-image a field), `H¹(G_{ℚ₂}, V) ≅ F` as an
`F`-line, and `Q⁰_loc` transports to a nonsingular **norm-one-invariant** quadratic form on `F`,
whose zero-count is `2^{2m−1} − 2^{m−1}` by the model-free algebraic core
`GQ2.DeepPart.card_normOne_invariant_form_zero`.

This file lives downstream of `DeepPart` (which supplies `Q0loc`, the Euler collapse, the
Hermitian count, and `nonsingular_Q0loc`), so — following the P-15d / 6.18-ramified pattern — the
statement is **moved out** of `SectionSix.lean` (a pointer comment is left there); the fully
qualified name stays `GQ2.SectionSix.prop_6_18_unramified` is preserved by re-export.
-/

namespace GQ2

open ContCoh QuadraticFp2 Corestriction SectionSix DeepPart

open scoped Classical

namespace UnramifiedModel

/-! ## Coefficient functoriality of `mapCoeff1` (general — belongs in the cohomology library)

`mapCoeff1` is functorial in the coefficient map: it sends `id` to `id` and `f ∘ g` to
`mapCoeff1 f ∘ mapCoeff1 g`.  These descend the corresponding cochain-level facts about `Z1comap`
through the `H¹` quotient (`QuotientAddGroup.map_mk'`).  Needed to promote the coefficient action
of an abelian `C` on `V` to a `C`-action on `H¹`. -/

section Functoriality

variable {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
variable {M : Type*} [AddCommGroup M] [TopologicalSpace M] [IsTopologicalAddGroup M]
  [DistribMulAction G M] [ContinuousSMul G M]
variable {N : Type*} [AddCommGroup N] [TopologicalSpace N] [IsTopologicalAddGroup N]
  [DistribMulAction G N] [ContinuousSMul G N]
variable {P : Type*} [AddCommGroup P] [TopologicalSpace P] [IsTopologicalAddGroup P]
  [DistribMulAction G P] [ContinuousSMul G P]

/-- `mapCoeff1` on an explicit cocycle class post-composes the cocycle with `f`. -/
theorem mapCoeff1_H1mk (f : N →+ M) (hf : Continuous f)
    (hcompat : ∀ (g : G) (n : N), f (g • n) = g • f n) (z : Z1 G N) :
    mapCoeff1 f hf hcompat (H1mk G N z)
      = H1mk G M (Z1comap (ContinuousMonoidHom.id G) f hf (fun g n => hcompat g n) z) :=
  rfl

/-- `mapCoeff1 (id) = id`. -/
theorem mapCoeff1_id
    (hcompat : ∀ (g : G) (m : M), (AddMonoidHom.id M) (g • m) = g • (AddMonoidHom.id M) m) :
    mapCoeff1 (AddMonoidHom.id M) continuous_id hcompat = AddMonoidHom.id (H1 G M) := by
  ext x
  induction x using QuotientAddGroup.induction_on with
  | _ z => rfl

/-- `mapCoeff1 (f ∘ g) = mapCoeff1 f ∘ mapCoeff1 g`. -/
theorem mapCoeff1_comp (f : N →+ M) (hf : Continuous f)
    (hfc : ∀ (g : G) (n : N), f (g • n) = g • f n)
    (e : P →+ N) (he : Continuous e) (hec : ∀ (g : G) (p : P), e (g • p) = g • e p) :
    mapCoeff1 (f.comp e) (hf.comp he) (fun g p => by rw [AddMonoidHom.comp_apply, hec, hfc]; rfl)
      = (mapCoeff1 f hf hfc).comp (mapCoeff1 e he hec) := by
  ext x
  induction x using QuotientAddGroup.induction_on with
  | _ z => rfl

end Functoriality

variable {C : Type} [Group C] [TopologicalSpace C] [DiscreteTopology C] [Finite C]
variable {V : Type} [AddCommGroup V] [TopologicalSpace V] [DiscreteTopology V] [Finite V]
  [DistribMulAction AbsGalQ2 V] [ContinuousSMul AbsGalQ2 V] [DistribMulAction C V]

/-- **Step 1 of the unramified model**: the acting group `C` is cyclic, generated by
`c tameSigma`.  Faithfulness (`hfaith`) upgrades the trivial *action* `hunram` to the trivial
*element* `c tameTau = 1`, then tame topological generation (`SectionThree.gen_ttame_quotient`)
collapses the two generators to one.  (Verbatim the `hgen` step of `prop_6_9_unramified`.) -/
theorem c_cyclic (c : ContinuousMonoidHom Ttame C) (hc : Function.Surjective ⇑c)
    (hfaith : ∀ h : C, (∀ v : V, h • v = v) → h = 1)
    (hunram : ∀ v : V, c tameTau • v = v) :
    ∀ x : C, x ∈ Subgroup.zpowers (c tameSigma) := by
  have htautriv : c tameTau = 1 := hfaith (c tameTau) hunram
  have hcl : Subgroup.closure {c tameSigma, c tameTau} = ⊤ :=
    SectionThree.gen_ttame_quotient c.toMonoidHom c.continuous_toFun hc
  rw [htautriv] at hcl
  have hz : Subgroup.closure ({c tameSigma, 1} : Set C) = Subgroup.zpowers (c tameSigma) := by
    rw [Subgroup.zpowers_eq_closure]
    apply le_antisymm
    · rw [Subgroup.closure_le]
      intro y hy
      rcases hy with rfl | rfl
      · exact Subgroup.subset_closure (Set.mem_singleton _)
      · exact one_mem _
    · exact Subgroup.closure_mono (Set.singleton_subset_iff.mpr (Set.mem_insert _ _))
  rw [hz] at hcl
  intro x; rw [hcl]; trivial

/-- **Proposition 6.18, eq. (115), unramified case**: negative Gauss sign,
`#(Q⁰_loc)⁻¹(0) = 2^{2m−1} − 2^{m−1}`.

Proved via the Hermitian-line model (see the file docstring): identify `V` with `𝔽_{2^{2m}}`,
transport `Q⁰_loc` to a norm-one-invariant nonsingular form, and count zeros with
`card_normOne_invariant_form_zero`.  [P-14 statement; proof P-15f3, Ax: B6, B7.]

**Statement amended (P-15f, flag for P-20)**: added `hc : Function.Surjective ⇑c` (as in
`prop_6_18_ramified`). -/
theorem prop_6_18_unramified (D : TateDuality 2) (B : BoundaryMaps)
    (c : ContinuousMonoidHom Ttame C)
    (hc : Function.Surjective ⇑c)
    (ρ : ContinuousMonoidHom AbsGalQ2 C) (hfac : ∀ g, ρ g = c (B.tameF g))
    (hρ : ∀ (g : AbsGalQ2) (v : V), g • v = ρ g • v)
    (hfaith : ∀ h : C, (∀ v : V, h • v = v) → h = 1)
    (hsimple : ∀ W : AddSubgroup V, (∀ (h : C), ∀ w ∈ W, h • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (hV : ∃ v : V, v ≠ 0)
    (hunram : ∀ v : V, c tameTau • v = v)
    (q : V → ZMod 2) (hq : IsQuadraticFp2 q) (hns : Nonsingular q) (hinv : IsInvariant C q)
    (dat : FactorSet C V) (hdat : IsEquivariantFactorSet q dat)
    (m : ℕ) (hm : 1 ≤ m) (hcard : Nat.card V = 2 ^ (2 * m)) :
    Nat.card {x : H1 AbsGalQ2 V // Q0loc D dat ρ x = 0}
      = 2 ^ (2 * m - 1) - 2 ^ (m - 1) := by
  classical
  haveI : Finite (H1 AbsGalQ2 V) := Foundations.finite_H1 V
  haveI : Fintype (H1 AbsGalQ2 V) := Fintype.ofFinite _
  have hV2 : ∀ v : V, v + v = 0 := exp_two_of_simple_of_card hsimple m hm hcard
  have hqG : ∀ (g : AbsGalQ2) (v : V), q (g • v) = q v := fun g v => by rw [hρ]; exact hinv _ v
  have hquad : IsQuadraticFp2 (Q0loc D dat ρ (V := V)) :=
    isQuadraticFp2_Q0loc D q hq dat hdat ρ hρ hqG
  have hnons : Nonsingular (Q0loc D dat ρ (V := V)) :=
    nonsingular_Q0loc D q hq hns hV2 dat hdat ρ hρ hqG
  -- the `C`-action moves some vector (else `V` is `𝔽₂`, contradicting `#V = 2^{2m}`, `m ≥ 1`)
  have hmove : ∃ (h₀ : C) (v : V), h₀ • v ≠ v := by
    by_contra hcon
    push_neg at hcon
    obtain ⟨v, hv⟩ := hV
    haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
    have hord : addOrderOf v = 2 := addOrderOf_eq_prime (by rw [two_nsmul]; exact hV2 v) hv
    have htop : AddSubgroup.zmultiples v = ⊤ := by
      refine (hsimple _ (fun h w hw => by rw [hcon]; exact hw)).resolve_left (fun h0 => hv ?_)
      have hmem : v ∈ AddSubgroup.zmultiples v := AddSubgroup.mem_zmultiples v
      rw [h0, AddSubgroup.mem_bot] at hmem; exact hmem
    have hcard2 : Nat.card V = 2 := by
      have h1 : Nat.card ↥(AddSubgroup.zmultiples v) = 2 := by rw [Nat.card_zmultiples, hord]
      rwa [htop, Nat.card_congr AddSubgroup.topEquiv.toEquiv] at h1
    rw [hcard] at hcard2
    have h4 : (4 : ℕ) ≤ 2 ^ (2 * m) :=
      calc (4 : ℕ) = 2 ^ 2 := by norm_num
        _ ≤ 2 ^ (2 * m) := Nat.pow_le_pow_right (by norm_num) (by omega)
    omega
  obtain ⟨h₀, hmoves⟩ := hmove
  have hρsurj : Function.Surjective ⇑ρ := by
    intro y
    obtain ⟨t, ht⟩ := hc y
    obtain ⟨g, hg⟩ := B.tameF_surjective t
    exact ⟨g, by rw [hfac, hg, ht]⟩
  have hcardH1 : Fintype.card (H1 AbsGalQ2 V) = 2 ^ (2 * m) := by
    rw [← Nat.card_eq_fintype_card,
      card_H1_eq_card_of_simple V D ρ.toMonoidHom hρsurj hρ hsimple h₀ hmoves q hq hns hinv hV2,
      hcard]
  -- **The Arf invariant is `1` (minus type)** — the crux.
  -- The clean route is `GaussSigns.arf_eq_s_ramified` (the SAME engine `prop_6_9_unramified` uses,
  -- but now applied to `Q0loc` on `H¹` rather than `q` on `V`): a cyclic group `G` acting
  -- faithfully on `H¹`, an equivariant `H¹ ≃+ (Fin s → W)` decomposition into copies of a simple
  -- `G`-module `W` (`#W = 2^{2m'}`), and `Q0loc` `G`-invariant, give `arf (Q0loc) = (s : ZMod 2)`;
  -- the minus sign is `s` odd.
  -- CONSTRUCTION PLAN (the remaining P-15f3 work), with the correct mechanism:
  --   (1) [DONE-able now] `C` is cyclic, `C = ⟨c tameSigma⟩`: faithfulness upgrades the trivial
  --       ACTION `hunram` to the trivial ELEMENT `htautriv : c tameTau = 1 := hfaith _ hunram`, then
  --       `SectionThree.gen_ttame_quotient` + `hunram`-collapse gives `∀ x : C, x ∈ zpowers (c tameSigma)`
  --       (verbatim as in `prop_6_9_unramified`, SectionSix.lean:347).
  --   (2) The `C`-action on `H¹`: `C` is abelian (cyclic), so each `c • ·` is a `G`-equivariant
  --       (`hρ` factors through the abelian `C`) additive auto of `V`, inducing `mapCoeff1 (c • ·)`
  --       on `H¹` — a `C`-module structure, faithful and with `#H¹ = #V = 2^{2m}`.
  --   (3) The decomposition `H¹ ≃+ (Fin s → W)` over `C` with `s` ODD in the unramified case: this
  --       is the base-cohomology analogue of `prop_6_9`'s source decomposition.  Equivalently, via
  --       Schur (`Module.End.instDivisionRing` + `littleWedderburn`) `H¹` is a line over the
  --       endomorphism field `D = 𝔽_{2^{2m}}`, so `s = 1` (odd) with `W = H¹`.
  --   (4) `Q0loc` `C`-invariance — the one genuinely cohomological brick: for `c ∈ C` an
  --       equivariant `q`-isometry (`hinv`), `lemma_6_14` (naturality) + `Q0loc` datum-independence
  --       for the fixed `q` give `Q0loc (mapCoeff1 (c • ·) x) = Q0loc x`.  Datum-independence
  --       (`Q0loc D dat ρ = Q0loc D dat' ρ` for equivariant `dat, dat'` of the same `q`, Lemma 6.4)
  --       is a P-15 obligation not yet banked — the real remaining content.
  have harf : arf (Q0loc D dat ρ (V := V)) = 1 := by
    sorry
  simpa only [zeroCount] using
    zeroCount_of_arf_one (Q0loc D dat ρ (V := V)) hquad hnons hm hcardH1 harf

end UnramifiedModel

end GQ2
