/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-4.8 and Fable-5
-/
import GQ2.DeepPart
import Mathlib.RingTheory.LittleWedderburn

/-!
# `prop_6_18_unramified` via the Hermitian-line model

The unramified case of Proposition 6.18 (eq. (115)): for a simple faithful `𝔽₂[C]`-module `V`
of cardinality `2^{2m}` at an **unramified** marking (`c tameTau` acts trivially), the base
determinant form `Q⁰_loc` has the negative Gauss sign:
`#(Q⁰_loc)⁻¹(0) = 2^{2m−1} − 2^{m−1}`.

Unlike the ramified case (which routes through Lemma 6.17's self-perpendicularity + vanishing,
`GQ2.DeepPart.card_Q0loc_zero_eq_of_dim_of_vanish`, hardwired to the `+` sign), the unramified
minus-type count comes from the **Hermitian-line model**: `V` is identified with a finite field
`F = 𝔽_{2^{2m}}` (Schur, `C` cyclic hence `𝔽₂[C]`-image a field), `H¹(G_{ℚ₂}, V) ≅ F` as an
`F`-line, and `Q⁰_loc` transports to a nonsingular **norm-one-invariant** quadratic form on `F`,
whose zero-count is `2^{2m−1} − 2^{m−1}` by the model-free algebraic core
`GQ2.DeepPart.card_normOne_invariant_form_zero`.

This file lives downstream of `DeepPart` (which supplies `Q0loc`, the Euler collapse, the
Hermitian count, and `nonsingular_Q0loc`), so — following the Lemma 6.14 proof / 6.18-ramified pattern — the
statement is **moved out** of `SectionSix.lean` (a pointer comment is left there); the fully
qualified name stays `GQ2.SectionSix.prop_6_18_unramified` is preserved by re-export.
-/

namespace GQ2

open ContCoh QuadraticFp2 Corestriction SectionSix DeepPart

open scoped Classical

namespace UnramifiedModel

/-! ## Coefficient functoriality of `mapCoeff1` (general — belongs in the cohomology library)

`mapCoeff1` is functorial in the coefficient map: it sends `id` to `id` and `f ∘ g` to
`mapCoeff1 f ∘ mapCoeff1 g`.  These descend the corresponding cochain-level facts about `Z1comap`
through the `H¹` quotient (`QuotientAddGroup.map_mk'`).  Needed to promote the coefficient action
of an abelian `C` on `V` to a `C`-action on `H¹`. -/

section Functoriality

variable {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
variable {M : Type*} [AddCommGroup M] [TopologicalSpace M] [IsTopologicalAddGroup M]
  [DistribMulAction G M] [ContinuousSMul G M]
variable {N : Type*} [AddCommGroup N] [TopologicalSpace N] [IsTopologicalAddGroup N]
  [DistribMulAction G N] [ContinuousSMul G N]
variable {P : Type*} [AddCommGroup P] [TopologicalSpace P] [IsTopologicalAddGroup P]
  [DistribMulAction G P] [ContinuousSMul G P]


end Functoriality

variable {C : Type} [Group C] [TopologicalSpace C] [DiscreteTopology C] [Finite C]
variable {V : Type} [AddCommGroup V] [TopologicalSpace V] [DiscreteTopology V] [Finite V]
  [DistribMulAction AbsGalQ2 V] [ContinuousSMul AbsGalQ2 V] [DistribMulAction C V]

omit [Finite C] [TopologicalSpace V] [DiscreteTopology V] [Finite V]
  [DistribMulAction AbsGalQ2 V] [ContinuousSMul AbsGalQ2 V] in
/-- **Step 1 of the unramified model**: the acting group `C` is cyclic, generated by
`c tameSigma`.  Faithfulness (`hfaith`) upgrades the trivial *action* `hunram` to the trivial
*element* `c tameTau = 1`, then tame topological generation (`SectionThree.gen_ttame_quotient`)
collapses the two generators to one.  (Verbatim the `hgen` step of `prop_6_9_unramified`.) -/
theorem c_cyclic (c : ContinuousMonoidHom Ttame C) (hc : Function.Surjective ⇑c)
    (hfaith : ∀ h : C, (∀ v : V, h • v = v) → h = 1)
    (hunram : ∀ v : V, c tameTau • v = v) :
    ∀ x : C, x ∈ Subgroup.zpowers (c tameSigma) := by
  have hcl : Subgroup.closure {c tameSigma, c tameTau} = ⊤ :=
    SectionThree.gen_ttame_quotient c.toMonoidHom c.continuous_toFun hc
  rw [hfaith (c tameTau) hunram, Set.pair_comm, Subgroup.closure_insert_one,
    ← Subgroup.zpowers_eq_closure] at hcl
  intro x; rw [hcl]; trivial

omit [TopologicalSpace C] [DiscreteTopology C] [Finite C] in
/-- Commutativity of a cyclic `C` (generated by `t`): every element is a power of `t`. -/
theorem comm_of_cyclic (t : C) (hcyc : ∀ x : C, x ∈ Subgroup.zpowers t) (a b : C) :
    a * b = b * a := by
  obtain ⟨i, hi⟩ := Subgroup.mem_zpowers_iff.mp (hcyc a)
  obtain ⟨j, hj⟩ := Subgroup.mem_zpowers_iff.mp (hcyc b)
  rw [← hi, ← hj, ← zpow_add, ← zpow_add, add_comm]

/-- **The coefficient endomorphism of `H¹(G_ℚ₂, V)` attached to `c : C`** (for a `ρ`-factored
action with `C` commutative): `c • ·` is a `G_ℚ₂`-equivariant additive endo of `V` —
equivariance is commutativity of `C` with the `ρ`-factored action — so it acts on `H¹` via
`mapCoeff1`. -/
noncomputable def cCoeff (ρ : ContinuousMonoidHom AbsGalQ2 C)
    (hρ : ∀ (g : AbsGalQ2) (v : V), g • v = ρ g • v)
    (hCcomm : ∀ a b : C, a * b = b * a) (c : C) :
    H1 AbsGalQ2 V →+ H1 AbsGalQ2 V :=
  mapCoeff1 (DistribSMul.toAddMonoidHom V c) continuous_of_discreteTopology
    (fun g v => by
      show c • (g • v) = g • (c • v)
      rw [hρ g v, hρ g (c • v), ← mul_smul, ← mul_smul, hCcomm])

/-- **The coefficient action of a commutative `C` on `H¹(G_ℚ₂, V)`** (brick toward
`arf(Q0loc)=1`): the `DistribMulAction` axioms for `cCoeff` descend from `mapCoeff1`
functoriality (`mapCoeff1_id`/`mapCoeff1_comp`). -/
@[reducible] noncomputable def cActionH1 (ρ : ContinuousMonoidHom AbsGalQ2 C)
    (hρ : ∀ (g : AbsGalQ2) (v : V), g • v = ρ g • v)
    (hCcomm : ∀ a b : C, a * b = b * a) : DistribMulAction C (H1 AbsGalQ2 V) where
  smul c := cCoeff ρ hρ hCcomm c
  one_smul x := by
    induction x using QuotientAddGroup.induction_on with
    | _ z =>
      show mapCoeff1 (DistribSMul.toAddMonoidHom V (1 : C)) _ _ (H1mk AbsGalQ2 V z)
        = H1mk AbsGalQ2 V z
      rw [mapCoeff1_H1mk]
      congr 1
      exact Subtype.ext (funext fun g => one_smul _ _)
  mul_smul a b x := by
    induction x using QuotientAddGroup.induction_on with
    | _ z =>
      show mapCoeff1 (DistribSMul.toAddMonoidHom V (a * b)) _ _ (H1mk AbsGalQ2 V z)
        = mapCoeff1 (DistribSMul.toAddMonoidHom V a) _ _
            (mapCoeff1 (DistribSMul.toAddMonoidHom V b) _ _ (H1mk AbsGalQ2 V z))
      rw [mapCoeff1_H1mk, mapCoeff1_H1mk, mapCoeff1_H1mk]
      congr 1
      exact Subtype.ext (funext fun g => mul_smul a b _)
  smul_zero c := map_zero _
  smul_add c x y := map_add _ _ _

omit [TopologicalSpace C] [DiscreteTopology C] [TopologicalSpace V] [DiscreteTopology V]
  [Finite V] [DistribMulAction AbsGalQ2 V] [ContinuousSMul AbsGalQ2 V] in
/-- **V-side of the Schur transfer, membership + `C`-equivariance**: for a cyclic `C = ⟨T⟩`, every
`c : C` acts on `V` through the subring `F := 𝔽₂⟨σ⟩ ⊆ End V` generated by `σ = ` the `T`-action, and
every element of `F` is `C`-equivariant (it commutes with `σ`, hence with every power of `σ`). -/
private theorem cCoeff_mem_and_equiv (T : C) (hcyc : ∀ x : C, x ∈ Subgroup.zpowers T) :
    (∀ c : C, DistribMulAction.toAddMonoidEnd C V c
        ∈ Subring.closure {DistribMulAction.toAddMonoidEnd C V T}) ∧
    (∀ f ∈ Subring.closure {DistribMulAction.toAddMonoidEnd C V T},
        ∀ (c : C) (v : V), f (c • v) = c • f v) := by
  set σ : AddMonoid.End V := DistribMulAction.toAddMonoidEnd C V T with hσdef
  set F : Subring (AddMonoid.End V) := Subring.closure {σ} with hFdef
  have hfin : IsOfFinOrder T :=
    isOfFinOrder_iff_pow_eq_one.mpr ⟨orderOf T, orderOf_pos T, pow_orderOf_eq_one T⟩
  have hnatpow : ∀ g : C, ∃ k : ℕ, T ^ k = g := fun g =>
    (Submonoid.mem_powers_iff g T).mp (hfin.mem_powers_iff_mem_zpowers.mpr (hcyc g))
  have hactpow : ∀ c : C, ∃ k : ℕ, DistribMulAction.toAddMonoidEnd C V c = σ ^ k := by
    intro c
    obtain ⟨k, hk⟩ := hnatpow c
    exact ⟨k, by rw [← hk, map_pow]⟩
  have hmemAct : ∀ c : C, DistribMulAction.toAddMonoidEnd C V c ∈ F := by
    intro c
    obtain ⟨k, hk⟩ := hactpow c
    rw [hk]
    exact pow_mem (Subring.subset_closure (Set.mem_singleton σ)) k
  have hcommσ : ∀ f ∈ F, f * σ = σ * f := by
    intro f hf
    induction hf using Subring.closure_induction with
    | mem x hx => rw [Set.mem_singleton_iff.mp hx]
    | zero => rw [zero_mul, mul_zero]
    | one => rw [one_mul, mul_one]
    | add x y hx hy ihx ihy => rw [add_mul, mul_add, ihx, ihy]
    | neg x hx ih => rw [neg_mul, mul_neg, ih]
    | mul x y hx hy ihx ihy => rw [mul_assoc, ihy, ← mul_assoc, ihx, mul_assoc]
  have hCequivF : ∀ f ∈ F, ∀ (c : C) (v : V), f (c • v) = c • f v := by
    intro f hf c v
    obtain ⟨k, hk⟩ := hactpow c
    have hcomm : f * σ ^ k = σ ^ k * f := (Commute.pow_right (hcommσ f hf) k)
    have h1 : ∀ w : V, c • w = (σ ^ k) w := fun w => by rw [← hk]; rfl
    calc f (c • v) = f ((σ ^ k) v) := by rw [h1]
      _ = (f * σ ^ k) v := rfl
      _ = (σ ^ k * f) v := by rw [hcomm]
      _ = (σ ^ k) (f v) := rfl
      _ = c • f v := (h1 (f v)).symm
  exact ⟨hmemAct, hCequivF⟩

omit [TopologicalSpace C] [DiscreteTopology C] [Finite C] [TopologicalSpace V]
  [DiscreteTopology V] [DistribMulAction AbsGalQ2 V] [ContinuousSMul AbsGalQ2 V] in
/-- **V-side Schur bijectivity**: a nonzero element of `F = 𝔽₂⟨σ⟩ ⊆ End V` is bijective on `V`.  Its
kernel is a `C`-stable subgroup (using `C`-equivariance of `F`), hence `⊥` or `⊤` by simplicity;
`⊤` is excluded by `f ≠ 0`, so injectivity — and bijectivity, `V` being finite — follows. -/
private theorem cCoeff_bijective_of_ne_zero (T : C)
    (hsimple : ∀ W : AddSubgroup V, (∀ (h : C), ∀ w ∈ W, h • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (hCequivF : ∀ f ∈ Subring.closure {DistribMulAction.toAddMonoidEnd C V T},
        ∀ (c : C) (v : V), f (c • v) = c • f v) :
    ∀ f ∈ Subring.closure {DistribMulAction.toAddMonoidEnd C V T}, f ≠ 0 →
      Function.Bijective f := by
  intro f hf hne
  let K : AddSubgroup V :=
    { carrier := {v | f v = 0}
      zero_mem' := map_zero f
      add_mem' := fun {a b} ha hb => by
        show f (a + b) = 0
        rw [map_add, show f a = 0 from ha, show f b = 0 from hb, add_zero]
      neg_mem' := fun {a} ha => by
        show f (-a) = 0
        rw [map_neg, show f a = 0 from ha, neg_zero] }
  have hKstab : ∀ (c : C), ∀ v ∈ K, c • v ∈ K := by
    intro c v hv
    show f (c • v) = 0
    rw [hCequivF f hf c v, show f v = 0 from hv, smul_zero]
  rcases hsimple K hKstab with hb | ht
  · refine Finite.injective_iff_bijective.mp (fun a b hab => ?_)
    have hmem : a - b ∈ K := by
      show f (a - b) = 0
      rw [map_sub, hab, sub_self]
    rw [hb, AddSubgroup.mem_bot] at hmem
    exact sub_eq_zero.mp hmem
  · refine absurd (AddMonoidHom.ext fun v => ?_) hne
    have hmem : v ∈ K := ht ▸ AddSubgroup.mem_top v
    exact hmem

omit [TopologicalSpace C] [DiscreteTopology C] [Finite C] [TopologicalSpace V]
  [DiscreteTopology V] [DistribMulAction AbsGalQ2 V] [ContinuousSMul AbsGalQ2 V] in
/-- **V-side, `F` is a field**: `F = 𝔽₂⟨σ⟩` is a finite domain (nonzero elements are bijective, so
non-zero-divisors), hence a field by little Wedderburn (`Finite.isDomain_to_isField`). -/
private theorem cCoeff_isField (T : C) (hVnt : Nontrivial V)
    (hbij : ∀ f ∈ Subring.closure {DistribMulAction.toAddMonoidEnd C V T}, f ≠ 0 →
      Function.Bijective f) :
    IsField (Subring.closure {DistribMulAction.toAddMonoidEnd C V T}) := by
  haveI := hVnt
  haveI : Finite (AddMonoid.End V) :=
    Finite.of_injective (fun f => (f : V → V)) DFunLike.coe_injective
  set F : Subring (AddMonoid.End V) := Subring.closure {DistribMulAction.toAddMonoidEnd C V T}
    with hFdef
  haveI : Nontrivial F := by
    refine ⟨0, 1, fun h => ?_⟩
    obtain ⟨v, hv⟩ := exists_ne (0 : V)
    apply hv
    have h2 : ((0 : F) : AddMonoid.End V) v = ((1 : F) : AddMonoid.End V) v := by rw [h]
    simpa using h2.symm
  haveI : NoZeroDivisors F := by
    refine ⟨fun {a b} hab => ?_⟩
    by_contra! hcon
    obtain ⟨ha, hb⟩ := hcon
    have hbbij : Function.Bijective (b : AddMonoid.End V) :=
      hbij b.1 b.2 (fun h0 => hb (Subtype.ext h0))
    have habij : Function.Bijective (a : AddMonoid.End V) :=
      hbij a.1 a.2 (fun h0 => ha (Subtype.ext h0))
    obtain ⟨v, hv⟩ := exists_ne (0 : V)
    have h0 : (a : AddMonoid.End V) ((b : AddMonoid.End V) v) = 0 := by
      have := congrArg (fun g : F => (g : AddMonoid.End V) v) hab
      simpa using this
    have hbv : (b : AddMonoid.End V) v = 0 :=
      habij.1 (by rw [h0, map_zero])
    exact hv (hbbij.1 (by rw [hbv, map_zero]))
  haveI : IsDomain F := NoZeroDivisors.to_isDomain F
  exact Finite.isDomain_to_isField F

omit [TopologicalSpace C] [DiscreteTopology C] [Finite C] [TopologicalSpace V]
  [DiscreteTopology V] [Finite V] [DistribMulAction AbsGalQ2 V] [ContinuousSMul AbsGalQ2 V] in
/-- **V-side cardinality**: the orbit map `F → V`, `f ↦ f v₀` at any `v₀ ≠ 0` is injective (nonzero
elements of `F` are bijective) with `C`-stable range, hence bijective by simplicity, so
`#F = #V`. -/
private theorem cCoeff_card_eq (T : C) (hVnt : Nontrivial V)
    (hsimple : ∀ W : AddSubgroup V, (∀ (h : C), ∀ w ∈ W, h • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (hmemAct : ∀ c : C, DistribMulAction.toAddMonoidEnd C V c
        ∈ Subring.closure {DistribMulAction.toAddMonoidEnd C V T})
    (hbij : ∀ f ∈ Subring.closure {DistribMulAction.toAddMonoidEnd C V T}, f ≠ 0 →
      Function.Bijective f) :
    Nat.card (Subring.closure {DistribMulAction.toAddMonoidEnd C V T}) = Nat.card V := by
  haveI := hVnt
  set F : Subring (AddMonoid.End V) := Subring.closure {DistribMulAction.toAddMonoidEnd C V T}
    with hFdef
  have hactapp : ∀ (c : C) (v : V), DistribMulAction.toAddMonoidEnd C V c v = c • v :=
    fun c v => rfl
  obtain ⟨v₀, hv₀⟩ := exists_ne (0 : V)
  have hθinj : Function.Injective (fun f : F => (f : AddMonoid.End V) v₀) := by
    intro f g hfg
    have hfg' : (f : AddMonoid.End V) v₀ = (g : AddMonoid.End V) v₀ := hfg
    by_contra hne
    have hd0 : ((f - g : F) : AddMonoid.End V) ≠ 0 :=
      fun h0 => hne (sub_eq_zero.mp (Subtype.ext h0))
    have hdbij := hbij _ (f - g).2 hd0
    apply hv₀
    apply hdbij.1
    rw [map_zero]
    show (f : AddMonoid.End V) v₀ - (g : AddMonoid.End V) v₀ = 0
    rw [hfg', sub_self]
  have hθsurj : Function.Surjective (fun f : F => (f : AddMonoid.End V) v₀) := by
    let R0 : AddSubgroup V :=
      { carrier := Set.range (fun f : F => (f : AddMonoid.End V) v₀)
        zero_mem' := ⟨0, rfl⟩
        add_mem' := by
          rintro x y ⟨fx, hfx⟩ ⟨fy, hfy⟩
          have hfx' : (fx : AddMonoid.End V) v₀ = x := hfx
          have hfy' : (fy : AddMonoid.End V) v₀ = y := hfy
          refine ⟨fx + fy, ?_⟩
          show (fx : AddMonoid.End V) v₀ + (fy : AddMonoid.End V) v₀ = x + y
          rw [hfx', hfy']
        neg_mem' := by
          rintro x ⟨fx, hfx⟩
          have hfx' : (fx : AddMonoid.End V) v₀ = x := hfx
          refine ⟨-fx, ?_⟩
          show -((fx : AddMonoid.End V) v₀) = -x
          rw [hfx'] }
    have hRstab : ∀ (c : C), ∀ v ∈ R0, c • v ∈ R0 := by
      rintro c v ⟨f, hf⟩
      have hf' : (f : AddMonoid.End V) v₀ = v := hf
      refine ⟨⟨DistribMulAction.toAddMonoidEnd C V c, hmemAct c⟩ * f, ?_⟩
      show DistribMulAction.toAddMonoidEnd C V c ((f : AddMonoid.End V) v₀) = c • v
      rw [hf', hactapp]
    rcases hsimple R0 hRstab with hb | ht
    · exfalso
      have h1 : v₀ ∈ R0 := ⟨1, rfl⟩
      rw [hb, AddSubgroup.mem_bot] at h1
      exact hv₀ h1
    · intro v
      exact (ht ▸ AddSubgroup.mem_top v : v ∈ R0)
  exact Nat.card_eq_of_bijective _ ⟨hθinj, hθsurj⟩

omit [DiscreteTopology C] in
/-- **The Schur transfer (brick (c))**: for a cyclic `C = ⟨T⟩` acting faithfully and simply on a
finite nontrivial `V`, the coefficient action `cCoeff` on `H¹(G_ℚ₂, V)` is again *faithful* and
*simple*, provided `#H¹ = #V`.

Route: `F := 𝔽₂⟨σ⟩ ⊆ End(V)` (`σ` = the `T`-action) is a finite domain — kernels of its nonzero
elements are `C`-stable, so trivial by simplicity, and injective ⟹ bijective on finite `V` —
hence a *field* by little Wedderburn (`Finite.isDomain_to_isField`; no commutativity needed as
input).  The orbit map `F → V`, `f ↦ f v₀` at any `v₀ ≠ 0` is injective with `C`-stable range,
so bijective by simplicity: `#F = #V`.  `mapCoeff1` transfers `F` multiplicatively/additively to
`End(H¹)`, where units of `F` stay pointwise-invertible; the orbit map `F → H¹` at any
`0 ≠ x₀ ∈ S` for a `C`-stable `S` is injective with range inside `S`, so
`#S ≥ #F = #V = #H¹` forces `S = ⊤`. -/
theorem cCoeff_faithful_and_simple (ρ : ContinuousMonoidHom AbsGalQ2 C)
    (hρ : ∀ (g : AbsGalQ2) (v : V), g • v = ρ g • v)
    (hCcomm : ∀ a b : C, a * b = b * a)
    (T : C) (hcyc : ∀ x : C, x ∈ Subgroup.zpowers T)
    (hfaith : ∀ h : C, (∀ v : V, h • v = v) → h = 1)
    (hsimple : ∀ W : AddSubgroup V, (∀ (h : C), ∀ w ∈ W, h • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (hVnt : Nontrivial V)
    (hcardeq : Nat.card (H1 AbsGalQ2 V) = Nat.card V) :
    (∀ c : C, (∀ x : H1 AbsGalQ2 V, cCoeff ρ hρ hCcomm c x = x) → c = 1) ∧
    Nontrivial (H1 AbsGalQ2 V) ∧
    ∀ S : AddSubgroup (H1 AbsGalQ2 V),
      (∀ (c : C), ∀ x ∈ S, cCoeff ρ hρ hCcomm c x ∈ S) → S = ⊥ ∨ S = ⊤ := by
  classical
  haveI : Finite (AddMonoid.End V) :=
    Finite.of_injective (fun f => (f : V → V)) DFunLike.coe_injective
  haveI : Finite (H1 AbsGalQ2 V) := Foundations.finite_H1 V
  haveI hH1nt : Nontrivial (H1 AbsGalQ2 V) := by
    rwa [← Finite.one_lt_card_iff_nontrivial, hcardeq, Finite.one_lt_card_iff_nontrivial]
  set σ : AddMonoid.End V := DistribMulAction.toAddMonoidEnd C V T with hσdef
  set F : Subring (AddMonoid.End V) := Subring.closure {σ} with hFdef
  -- V-side algebra: `F = 𝔽₂⟨σ⟩` is a field of the same cardinality as `V` (Schur + Wedderburn)
  obtain ⟨hmemAct, hCequivF⟩ := cCoeff_mem_and_equiv (V := V) T hcyc
  have hbij := cCoeff_bijective_of_ne_zero (V := V) T hsimple hCequivF
  have hfield := cCoeff_isField (V := V) T hVnt hbij
  have hFcard := cCoeff_card_eq (V := V) T hVnt hsimple hmemAct hbij
  -- === the transfer `Φ : F → End(H¹)` via `mapCoeff1` ===
  have hGequivF : ∀ f (hf : f ∈ F), ∀ (γ : AbsGalQ2) (v : V), f (γ • v) = γ • f v := by
    intro f hf γ v
    rw [hρ γ v, hρ γ (f v)]
    exact hCequivF f hf (ρ γ) v
  set Φ : F → (H1 AbsGalQ2 V →+ H1 AbsGalQ2 V) := fun f =>
    mapCoeff1 (f : AddMonoid.End V) continuous_of_discreteTopology (hGequivF f.1 f.2)
    with hΦdef
  have hΦmul : ∀ (f g : F) (x : H1 AbsGalQ2 V), Φ (f * g) x = Φ f (Φ g x) := by
    intro f g x
    induction x using QuotientAddGroup.induction_on with
    | _ z => rfl
  have hΦadd : ∀ (f g : F) (x : H1 AbsGalQ2 V), Φ (f + g) x = Φ f x + Φ g x := by
    intro f g x
    induction x using QuotientAddGroup.induction_on with
    | _ z => rfl
  have hΦone : ∀ x : H1 AbsGalQ2 V, Φ 1 x = x := by
    intro x
    induction x using QuotientAddGroup.induction_on with
    | _ z => rfl
  have hΦzero : ∀ x : H1 AbsGalQ2 V, Φ 0 x = 0 := by
    intro x
    induction x using QuotientAddGroup.induction_on with
    | _ z => rfl
  have hΦsub : ∀ (f g : F) (x : H1 AbsGalQ2 V), Φ (f - g) x = Φ f x - Φ g x := by
    intro f g x
    have h1 := hΦadd (f - g) g x
    rw [sub_add_cancel] at h1
    rw [eq_sub_iff_add_eq, ← h1]
  -- `cCoeff` is `Φ` at the action element
  have hcCoeffΦ : ∀ (c : C) (x : H1 AbsGalQ2 V),
      cCoeff ρ hρ hCcomm c x = Φ ⟨DistribMulAction.toAddMonoidEnd C V c, hmemAct c⟩ x := by
    intro c x
    induction x using QuotientAddGroup.induction_on with
    | _ z => rfl
  -- === (c1) faithfulness on `H¹` ===
  have hfaithH1 : ∀ c : C, (∀ x : H1 AbsGalQ2 V, cCoeff ρ hρ hCcomm c x = x) → c = 1 := by
    intro c hcx
    set u : F := ⟨DistribMulAction.toAddMonoidEnd C V c, hmemAct c⟩ - 1 with hudef
    by_cases hu : u = 0
    · -- `c` acts trivially on `V`
      apply hfaith c
      intro v
      have h1 : (u : AddMonoid.End V) v = ((0 : F) : AddMonoid.End V) v := by rw [hu]
      have h2 : c • v - v = 0 := by
        have h3 : (u : AddMonoid.End V) v = c • v - v := rfl
        rw [← h3, h1]
        rfl
      exact sub_eq_zero.mp h2
    · exfalso
      obtain ⟨w, hw⟩ := hfield.mul_inv_cancel hu
      have hΦu : ∀ x : H1 AbsGalQ2 V, Φ u x = 0 := by
        intro x
        rw [hudef, hΦsub, ← hcCoeffΦ, hcx x, hΦone, sub_self]
      obtain ⟨x, hx⟩ := exists_ne (0 : H1 AbsGalQ2 V)
      apply hx
      have hcm : u * w = w * u := (hfield.mul_comm u w)
      calc x = Φ 1 x := (hΦone x).symm
        _ = Φ (w * u) x := by rw [← hw, hcm]
        _ = Φ w (Φ u x) := hΦmul w u x
        _ = Φ w 0 := by rw [hΦu]
        _ = 0 := map_zero _
  refine ⟨hfaithH1, hH1nt, ?_⟩
  -- === (c2) simplicity of `H¹` ===
  intro S hS
  by_cases hSbot : S = ⊥
  · exact Or.inl hSbot
  refine Or.inr ?_
  have hx₀ : ∃ x ∈ S, x ≠ 0 := by
    by_contra! hcon
    exact hSbot ((AddSubgroup.eq_bot_iff_forall S).mpr hcon)
  obtain ⟨x₀, hx₀S, hx₀ne⟩ := hx₀
  -- `S` is stable under all of `Φ(F)`
  have hFS : ∀ (f : AddMonoid.End V) (hf : f ∈ F), ∀ x ∈ S, Φ ⟨f, hf⟩ x ∈ S := by
    intro f hf
    induction hf using Subring.closure_induction with
    | mem y hy =>
      intro x hx
      have hyσ := Set.mem_singleton_iff.mp hy
      subst hyσ
      have h1 : Φ ⟨σ, Subring.subset_closure (Set.mem_singleton σ)⟩ x
          = cCoeff ρ hρ hCcomm T x := (hcCoeffΦ T x).symm
      rw [h1]
      exact hS T x hx
    | zero =>
      intro x hx
      show Φ (0 : F) x ∈ S
      rw [hΦzero]
      exact S.zero_mem
    | one =>
      intro x hx
      show Φ (1 : F) x ∈ S
      rw [hΦone]
      exact hx
    | add y z hy hz ihy ihz =>
      intro x hx
      have h1 : Φ (⟨y, hy⟩ + ⟨z, hz⟩ : F) x = Φ ⟨y, hy⟩ x + Φ ⟨z, hz⟩ x := hΦadd _ _ x
      exact h1 ▸ S.add_mem (ihy x hx) (ihz x hx)
    | neg y hy ih =>
      intro x hx
      have h1 : Φ (-⟨y, hy⟩ : F) x = -Φ ⟨y, hy⟩ x := by
        have h2 := hΦsub 0 ⟨y, hy⟩ x
        rw [zero_sub, hΦzero, zero_sub] at h2
        exact h2
      exact h1 ▸ S.neg_mem (ih x hx)
    | mul y z hy hz ihy ihz =>
      intro x hx
      have h1 : Φ (⟨y, hy⟩ * ⟨z, hz⟩ : F) x = Φ ⟨y, hy⟩ (Φ ⟨z, hz⟩ x) := hΦmul _ _ x
      exact h1 ▸ ihy _ (ihz x hx)
  -- the injection `F ↪ S` at `x₀`
  have hΨinj : Function.Injective (fun f : F => Φ f x₀) := by
    intro f g hfg
    have hfg' : Φ f x₀ = Φ g x₀ := hfg
    by_contra hne
    have hd : f - g ≠ 0 := sub_ne_zero.mpr hne
    obtain ⟨w, hw⟩ := hfield.mul_inv_cancel hd
    apply hx₀ne
    have hcm : (f - g) * w = w * (f - g) := hfield.mul_comm _ _
    calc x₀ = Φ 1 x₀ := (hΦone x₀).symm
      _ = Φ (w * (f - g)) x₀ := by rw [← hw, hcm]
      _ = Φ w (Φ (f - g) x₀) := hΦmul _ _ x₀
      _ = Φ w 0 := by rw [hΦsub, hfg', sub_self]
      _ = 0 := map_zero _
  have hle : Nat.card F ≤ Nat.card S := by
    refine Nat.card_le_card_of_injective
      (fun f : F => (⟨Φ f x₀, hFS f.1 f.2 x₀ hx₀S⟩ : S)) (fun a b hab => ?_)
    exact hΨinj (congrArg Subtype.val hab)
  have hcards : Nat.card S = Nat.card (H1 AbsGalQ2 V) := by
    refine le_antisymm (AddSubgroup.card_le_card_addGroup S) ?_
    calc Nat.card (H1 AbsGalQ2 V) = Nat.card V := hcardeq
      _ = Nat.card F := hFcard.symm
      _ ≤ Nat.card S := hle
  exact (AddSubgroup.card_eq_iff_eq_top S).mp hcards


omit [DiscreteTopology C] [Finite C] [Finite V] [ContinuousSMul AbsGalQ2 V] in
/-- **Brick (d2), the explicit datum coboundary**: for `g₀ : C` (abelian `C`), the graph pullback
along the `g₀`-comapped datum differs from the original by the 2-coboundary of the continuous
1-cochain `γ ↦ m_{g₀}(b γ)`.  Pointwise this is `m_quad` (turning `f(g₀v, g₀w) − f(v,w)` into the
`∂(m_{g₀})`-term) plus the two `m_mul` expansions of `m_{g₀·ργ} = m_{ργ·g₀}` and the 1-cocycle
identity for `b`.  This is the specific instance of Lemma 6.4 datum-independence that the
unramified Prop 6.18 needs. -/
theorem graphPullback_comap_smul_sub_mem_B2 {q : V → ZMod 2} (dat : FactorSet C V)
    (hdat : IsEquivariantFactorSet q dat) (hCcomm : ∀ a b : C, a * b = b * a)
    (ρ : ContinuousMonoidHom AbsGalQ2 C) (hρ : ∀ (γ : AbsGalQ2) (v : V), γ • v = ρ γ • v)
    (g₀ : C) (b : Z1 AbsGalQ2 V) :
    graphPullback (dat.comap (DistribSMul.toAddMonoidHom V g₀)) ρ b.1
      - graphPullback dat ρ b.1 ∈ B2 AbsGalQ2 (ZMod 2) := by
  obtain ⟨hbc, hb⟩ := mem_Z1_iff.mp b.2
  refine (AddSubgroup.mem_map).mpr ⟨fun γ => dat.m g₀ (b.1 γ), ?_, ?_⟩
  · exact mem_C1_iff.mpr ((continuous_of_discreteTopology (f := fun v : V => dat.m g₀ v)).comp hbc)
  · funext p
    obtain ⟨γ, γ'⟩ := p
    have hbg : b.1 (γ * γ') = b.1 γ + ρ γ • b.1 γ' := by rw [hb γ γ', hρ]
    have hgp1 : graphPullback (dat.comap (DistribSMul.toAddMonoidHom V g₀)) ρ b.1 (γ, γ')
        = dat.f (g₀ • b.1 γ) (g₀ • (ρ γ • b.1 γ')) + dat.m (ρ γ) (g₀ • b.1 γ') := rfl
    have hgp2 : graphPullback dat ρ b.1 (γ, γ')
        = dat.f (b.1 γ) (ρ γ • b.1 γ') + dat.m (ρ γ) (b.1 γ') := rfl
    have hA := hdat.m_quad g₀ (b.1 γ) (ρ γ • b.1 γ')
    have hB := hdat.m_mul (ρ γ) g₀ (b.1 γ')
    have hB' := hdat.m_mul g₀ (ρ γ) (b.1 γ')
    rw [hCcomm (ρ γ) g₀] at hB
    simp only [dOne, AddMonoidHom.coe_mk, ZeroHom.coe_mk, absGal_smul_zmodTwo, Pi.sub_apply,
      hgp1, hgp2, hbg]
    linear_combination (norm := (ring_nf; simp [CharTwo.two_eq_zero])) hA + hB + hB'

omit [TopologicalSpace C] [DiscreteTopology C] [Finite C] [TopologicalSpace V]
  [DiscreteTopology V] [Finite V] [DistribMulAction AbsGalQ2 V] [ContinuousSMul AbsGalQ2 V] in
/-- **Some `C`-orbit is nontrivial**: for a simple `V` of cardinality `2^{2m}` with `m ≥ 1`, the
`C`-action moves some vector.  Otherwise the action is trivial, so `⟨v⟩ = ⊤` for any `v ≠ 0` by
simplicity forces `#V = 2`, contradicting `#V = 2^{2m} ≥ 4`. -/
private theorem exists_smul_ne
    (hsimple : ∀ W : AddSubgroup V, (∀ (h : C), ∀ w ∈ W, h • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (hV : ∃ v : V, v ≠ 0) (hV2 : ∀ v : V, v + v = 0)
    (m : ℕ) (hm : 1 ≤ m) (hcard : Nat.card V = 2 ^ (2 * m)) :
    ∃ (h₀ : C) (v : V), h₀ • v ≠ v := by
  by_contra! hcon
  obtain ⟨v, hv⟩ := hV
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  have hord : addOrderOf v = 2 := addOrderOf_eq_prime (by rw [two_nsmul]; exact hV2 v) hv
  have htop : AddSubgroup.zmultiples v = ⊤ := by
    refine (hsimple _ (fun h w hw => by rw [hcon]; exact hw)).resolve_left (fun h0 => hv ?_)
    have hmem : v ∈ AddSubgroup.zmultiples v := AddSubgroup.mem_zmultiples v
    rw [h0, AddSubgroup.mem_bot] at hmem; exact hmem
  have hcard2 : Nat.card V = 2 := by
    have h1 : Nat.card ↥(AddSubgroup.zmultiples v) = 2 := by rw [Nat.card_zmultiples, hord]
    rwa [htop, Nat.card_congr AddSubgroup.topEquiv.toEquiv] at h1
  rw [hcard] at hcard2
  have h4 : (4 : ℕ) ≤ 2 ^ (2 * m) :=
    calc (4 : ℕ) = 2 ^ 2 := by norm_num
      _ ≤ 2 ^ (2 * m) := Nat.pow_le_pow_right (by norm_num) (by omega)
  omega

omit [Finite C] [Finite V] in
/-- **Brick (d): `Q⁰_loc` is invariant under the coefficient action of `C` on `H¹`.**  For `g : C`,
naturality of `Q⁰_loc` along the coefficient map `i := (g • ·)` (`lemma_6_14`, using that `g`
commutes with both the `ρ`-factored `G_ℚ₂`-action and the `C`-action) rewrites `Q⁰_loc(g • x)` as
the pulled-back datum's `Q⁰_loc`, which agrees with the original by the explicit datum coboundary
`graphPullback_comap_smul_sub_mem_B2`. -/
private theorem Q0loc_smul_eq (D : TateDuality 2) (ρ : ContinuousMonoidHom AbsGalQ2 C)
    (hρ : ∀ (g : AbsGalQ2) (v : V), g • v = ρ g • v) (hCcomm : ∀ a b : C, a * b = b * a)
    (q : V → ZMod 2) (dat : FactorSet C V) (hdat : IsEquivariantFactorSet q dat) :
    letI := cActionH1 ρ hρ hCcomm
    ∀ (g : C) (x : H1 AbsGalQ2 V), Q0loc D dat ρ (g • x) = Q0loc D dat ρ x := by
  letI := cActionH1 ρ hρ hCcomm
  intro g x
  have hicompat : ∀ (γ : AbsGalQ2) (v : V),
      (DistribSMul.toAddMonoidHom V g) (γ • v)
        = γ • (DistribSMul.toAddMonoidHom V g) v := by
    intro γ v
    show g • (γ • v) = γ • (g • v)
    rw [hρ γ v, hρ γ (g • v), ← mul_smul, ← mul_smul, hCcomm]
  have hiC : ∀ (c : C) (v : V),
      (DistribSMul.toAddMonoidHom V g) (c • v)
        = c • (DistribSMul.toAddMonoidHom V g) v := by
    intro c v
    show g • (c • v) = c • (g • v)
    rw [← mul_smul, ← mul_smul, hCcomm]
  have h614 := RepIndependence.lemma_6_14 D dat ρ
    (DistribSMul.toAddMonoidHom V g) continuous_of_discreteTopology hicompat
    hdat hiC hρ x
  have hB2 := graphPullback_comap_smul_sub_mem_B2 dat hdat hCcomm ρ hρ g (Quotient.out x)
  have hQeq : Q0loc D (dat.comap (DistribSMul.toAddMonoidHom V g)) ρ x
      = Q0loc D dat ρ x :=
    congrArg (iotaF D) (RepIndependence.h2ofFun_eq_of_sub_mem_B2 hB2)
  have hsm : (g • x : H1 AbsGalQ2 V)
      = mapCoeff1 (DistribSMul.toAddMonoidHom V g) continuous_of_discreteTopology
          hicompat x := rfl
  rw [hsm, ← h614, hQeq]

/-- **Proposition 6.18, eq. (115), unramified case**: negative Gauss sign,
`#(Q⁰_loc)⁻¹(0) = 2^{2m−1} − 2^{m−1}`.

Proved via the Hermitian-line model (see the file docstring): identify `V` with `𝔽_{2^{2m}}`,
transport `Q⁰_loc` to a norm-one-invariant nonsingular form, and count zeros with
`card_normOne_invariant_form_zero`.  [the §§6–7 statement; proof the deep-part proof, Ax: B6, B7.]

**Signature note:** the hypothesis `hc : Function.Surjective ⇑c` (as in
`prop_6_18_ramified`). -/
theorem prop_6_18_unramified (D : TateDuality 2) (B : BoundaryMaps)
    (c : ContinuousMonoidHom Ttame C)
    (hc : Function.Surjective ⇑c)
    (ρ : ContinuousMonoidHom AbsGalQ2 C) (hfac : ∀ g, ρ g = c (B.tameF g))
    (hρ : ∀ (g : AbsGalQ2) (v : V), g • v = ρ g • v)
    (hfaith : ∀ h : C, (∀ v : V, h • v = v) → h = 1)
    (hsimple : ∀ W : AddSubgroup V, (∀ (h : C), ∀ w ∈ W, h • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (hV : ∃ v : V, v ≠ 0)
    (hunram : ∀ v : V, c tameTau • v = v)
    (q : V → ZMod 2) (hq : IsQuadraticFp2 q) (hns : Nonsingular q) (hinv : IsInvariant C q)
    (dat : FactorSet C V) (hdat : IsEquivariantFactorSet q dat)
    (m : ℕ) (hm : 1 ≤ m) (hcard : Nat.card V = 2 ^ (2 * m)) :
    Nat.card {x : H1 AbsGalQ2 V // Q0loc D dat ρ x = 0}
      = 2 ^ (2 * m - 1) - 2 ^ (m - 1) := by
  classical
  haveI : Finite (H1 AbsGalQ2 V) := Foundations.finite_H1 V
  haveI : Fintype (H1 AbsGalQ2 V) := Fintype.ofFinite _
  have hV2 : ∀ v : V, v + v = 0 := exp_two_of_simple_of_card hsimple m hm hcard
  have hqG : ∀ (g : AbsGalQ2) (v : V), q (g • v) = q v := fun g v => by rw [hρ]; exact hinv _ v
  have hquad : IsQuadraticFp2 (Q0loc D dat ρ (V := V)) :=
    isQuadraticFp2_Q0loc D q hq dat hdat ρ hρ hqG
  have hnons : Nonsingular (Q0loc D dat ρ (V := V)) :=
    nonsingular_Q0loc D q hq hns hV2 dat hdat ρ hρ hqG
  -- the `C`-action moves some vector (else `V` is `𝔽₂`, contradicting `#V = 2^{2m}`, `m ≥ 1`)
  obtain ⟨h₀, hmoves⟩ := exists_smul_ne (V := V) hsimple hV hV2 m hm hcard
  have hρsurj : Function.Surjective ⇑ρ := by
    intro y
    obtain ⟨t, ht⟩ := hc y
    obtain ⟨g, hg⟩ := B.tameF_surjective t
    exact ⟨g, by rw [hfac, hg, ht]⟩
  have hcardH1 : Fintype.card (H1 AbsGalQ2 V) = 2 ^ (2 * m) := by
    rw [← Nat.card_eq_fintype_card,
      card_H1_eq_card_of_simple V D ρ.toMonoidHom hρsurj hρ hsimple h₀ hmoves q hq hns hinv hV2,
      hcard]
  -- **The Arf invariant is `1` (minus type)** — via `GaussSigns.arf_eq_s_ramified` on `H¹`:
  -- `C = ⟨c tameSigma⟩` is cyclic (`c_cyclic`), its coefficient action on `H¹` is faithful and
  -- simple (`cCoeff_faithful_and_simple`, the Schur transfer), `H¹ ≃+ (Fin 1 → H¹)` trivially,
  -- `s = 1` is odd, and `Q0loc` is `C`-invariant (`lemma_6_14` naturality + the explicit datum
  -- coboundary `graphPullback_comap_smul_sub_mem_B2`).
  have harf : arf (Q0loc D dat ρ (V := V)) = 1 := by
    have hcyc := c_cyclic c hc hfaith hunram
    have hCcomm := comm_of_cyclic (c tameSigma) hcyc
    haveI hVnt : Nontrivial V := by
      obtain ⟨v, hv⟩ := hV
      exact ⟨v, 0, hv⟩
    have hcardeq : Nat.card (H1 AbsGalQ2 V) = Nat.card V := by
      rw [Nat.card_eq_fintype_card, hcardH1, hcard]
    obtain ⟨hfaithH1, hntH1, hsimpleH1⟩ :=
      cCoeff_faithful_and_simple ρ hρ hCcomm (c tameSigma) hcyc hfaith hsimple hVnt hcardeq
    letI actH1 : DistribMulAction C (H1 AbsGalQ2 V) := cActionH1 ρ hρ hCcomm
    -- exponent 2 on `H¹` (descends pointwise from `V`)
    have hH12 : ∀ x : H1 AbsGalQ2 V, x + x = 0 := by
      intro x
      induction x using QuotientAddGroup.induction_on with
      | _ z =>
        have hz : z + z = 0 := Subtype.ext (funext fun γ => hV2 (z.1 γ))
        show (QuotientAddGroup.mk (z + z) : H1 AbsGalQ2 V) = 0
        rw [hz]
        rfl
    -- the trivial one-block decomposition
    let e : H1 AbsGalQ2 V ≃+ (Fin 1 → H1 AbsGalQ2 V) :=
      { toFun := fun x _ => x
        invFun := fun f => f 0
        left_inv := fun x => rfl
        right_inv := fun f => funext fun j => by rw [Subsingleton.elim (0 : Fin 1) j]
        map_add' := fun x y => rfl }
    -- **brick (d): `Q0loc` is invariant under the coefficient action** — `lemma_6_14`
    -- naturality along `i := (g • ·)` plus the explicit datum coboundary
    -- (`graphPullback_comap_smul_sub_mem_B2`)
    have hqinv := Q0loc_smul_eq (V := V) D ρ hρ hCcomm q dat hdat
    have h := GaussSigns.arf_eq_s_ramified (G := C) (V := H1 AbsGalQ2 V) (W := H1 AbsGalQ2 V)
      (c tameSigma) hcyc hfaithH1 ⟨hntH1, fun S hS => hsimpleH1 S (fun g x hx => hS g x hx)⟩
      hH12 hH12 (Q0loc D dat ρ) hquad hnons hqinv m 1 hm le_rfl
      (by rw [Nat.card_eq_fintype_card, hcardH1]) e (fun g v j => rfl)
    simpa using h
  simpa only [zeroCount] using
    zeroCount_of_arf_one (Q0loc D dat ρ (V := V)) hquad hnons hm hcardH1 harf

end UnramifiedModel

end GQ2

/-! ### Paper-tag ledger (auto-generated by paperforge; do not edit)

  * eq. (115) = ⟦eq-localzeros⟧
  * Lemma 6.17 = ⟦lem-shapirodet⟧
  * Lemma 6.4 = ⟦lem-detnormalizationindependence⟧
  * Proposition 6.18 = ⟦prop-localzero⟧
-/
