import GQ2.Block.Module
import GQ2.BoundaryFrame
import GQ2.EvensKahn
import GQ2.Prop32
import GQ2.QuadraticFp2

/-!
# §7 block structure and Lemma 7.1 (simple head)

Split off from `GQ2.SectionSeven`.  This file provides the definition layer of the paper's §7:

* **Scalar stacks** (`IsScalarStack`) and the Frattini-like subgroup `Φ(K)` (`frattiniLike`) with
  its containment/normality API;
* the **§7 minimal block** `MinimalBlock` (`S ◁ P ◁ Y`, `P ≤ L`) with its radical field
  `MinimalBlock.frattiniK` (`R = Φ(K)`) and the existence theorem `exists_minimalBlock`;
* **Lemma 7.1** (simple head): the head, radical and dual-invariants clauses
  (`lemma_7_1_head`, `lemma_7_1_radical`, `lemma_7_1_dual`).

See `GQ2.SectionSeven` for the umbrella module docstring.
-/

namespace GQ2

namespace SectionSeven

open QuadraticFp2

open scoped Pointwise

variable {Y : Type} [Group Y] [Finite Y]

/-! ## Scalar stacks and the block structure -/

/-- **Scalar stack** (§7 opening): a normal chain `⊥ = c₀ ≤ c₁ ≤ ⋯ ≤ c_n = L` (each `cᵢ ◁ Y`)
whose successive layers are acted on trivially by `Y` (`⁅y, x⁆ ∈ cᵢ` for `x ∈ cᵢ₊₁`) — i.e.
every chief factor of `L` is the trivial (scalar) module.  The §7 block exists exactly when the
marked kernel is *not* a scalar stack; the scalar regime is §9.1/9.2's case. -/
def IsScalarStack (L : Subgroup Y) : Prop :=
  ∃ (n : ℕ) (c : ℕ → Subgroup Y),
    c 0 = ⊥ ∧ c n = L ∧ (∀ i, c i ≤ c (i + 1)) ∧ (∀ i, (c i).Normal) ∧
      ∀ i, ∀ y : Y, ∀ x ∈ c (i + 1), y * x * y⁻¹ * x⁻¹ ∈ c i

/-- `Φ`-like subgroup: the subgroup of `Y` generated by the squares and commutators of the
elements of `K`.  For `K ◁ Y` a finite 2-group this is the Frattini subgroup `Φ(K) = K²[K,K]`
of `K`, as a subgroup of `Y` (normal in `Y`, being characteristic in `K`). -/
def frattiniLike (K : Subgroup Y) : Subgroup Y :=
  Subgroup.closure
    ({x | ∃ k ∈ K, x = k * k} ∪ {x | ∃ k ∈ K, ∃ l ∈ K, x = k * l * k⁻¹ * l⁻¹})

omit [Finite Y] in
/-- `Φ(K) ≤ K` (the generators are squares and commutators of elements of `K`). -/
theorem frattiniLike_le (K : Subgroup Y) : frattiniLike K ≤ K := by
  refine (Subgroup.closure_le _).mpr ?_
  rintro x (⟨k, hk, rfl⟩ | ⟨k, hk, l, hl, rfl⟩)
  · exact mul_mem hk hk
  · exact mul_mem (mul_mem (mul_mem hk hl) (inv_mem hk)) (inv_mem hl)

omit [Finite Y] in
/-- `Φ(P)` is the image of the subtype-level Frattini-like subgroup of `↥P` — the bridge that
lets quotient arguments run inside `↥P` without closure inductions. -/
theorem frattiniLike_eq_map (P : Subgroup Y) :
    frattiniLike P
      = (Subgroup.closure ({x : P | ∃ k : P, x = k * k}
          ∪ {x : P | ∃ k l : P, x = k * l * k⁻¹ * l⁻¹})).map P.subtype := by
  rw [MonoidHom.map_closure, frattiniLike]
  congr 1
  ext x
  constructor
  · rintro (⟨k, hk, rfl⟩ | ⟨k, hk, l, hl, rfl⟩)
    · exact ⟨⟨k, hk⟩ * ⟨k, hk⟩, Or.inl ⟨⟨k, hk⟩, rfl⟩, rfl⟩
    · exact ⟨⟨k, hk⟩ * ⟨l, hl⟩ * ⟨k, hk⟩⁻¹ * ⟨l, hl⟩⁻¹,
        Or.inr ⟨⟨k, hk⟩, ⟨l, hl⟩, rfl⟩, rfl⟩
  · rintro ⟨x', hx', rfl⟩
    rcases hx' with ⟨k, rfl⟩ | ⟨k, l, rfl⟩
    · exact Or.inl ⟨k.1, k.2, rfl⟩
    · exact Or.inr ⟨k.1, k.2, l.1, l.2, rfl⟩

omit [Finite Y] in
/-- For `K ◁ Y`, `Φ(K)` is normal in `Y` (conjugation permutes the generating set). -/
theorem frattiniLike_normal (K : Subgroup Y) (hK : K.Normal) : (frattiniLike K).Normal := by
  refine ⟨fun n hn g => ?_⟩
  have himg : (frattiniLike K).map (MulAut.conj g).toMonoidHom ≤ frattiniLike K := by
    rw [frattiniLike, MonoidHom.map_closure]
    refine (Subgroup.closure_le _).mpr ?_
    rintro _ ⟨x, hx, rfl⟩
    rcases hx with ⟨k, hk, rfl⟩ | ⟨k, hk, l, hl, rfl⟩
    · refine Subgroup.subset_closure (Or.inl ⟨g * k * g⁻¹, hK.conj_mem k hk g, ?_⟩)
      show g * (k * k) * g⁻¹ = g * k * g⁻¹ * (g * k * g⁻¹)
      group
    · refine Subgroup.subset_closure
        (Or.inr ⟨g * k * g⁻¹, hK.conj_mem k hk g, g * l * g⁻¹, hK.conj_mem l hl g, ?_⟩)
      show g * (k * l * k⁻¹ * l⁻¹) * g⁻¹
        = g * k * g⁻¹ * (g * l * g⁻¹) * (g * k * g⁻¹)⁻¹ * (g * l * g⁻¹)⁻¹
      group
  exact himg ⟨n, hn, rfl⟩

/-- **The §7 minimal block** (§7 opening): `S ◁ P ◁ Y` with `P ≤ L`, everything below `S`
scalar, `V = P/S` a nontrivial simple `Y`-chief factor, and `K ◁ Y` minimal with `KS = P`. -/
structure MinimalBlock (L : Subgroup Y) where
  /-- The marked kernel is normal (a `GQ2.MarkedTarget` guarantee, carried so the block is
  self-contained).  [Field added in the P-15 pass, with `h2L`.] -/
  hL : L.Normal
  /-- The marked kernel is a 2-group — the paper's standing "marked normal **2**-subgroup"
  hypothesis.  [Field added in the P-15 pass: caught by attempting `lemma_7_1_head`, which is
  **false** without it (counterexample `Y = S₃`, `L = P = K = A₃`, `S = ⊥`: all other fields
  hold but `Φ(A₃) = A₃ ≰ K ⊓ S`).  Deviation ledger updated.] -/
  h2L : IsPGroup 2 L
  /-- The scalar socle `S`. -/
  S : Subgroup Y
  /-- The layer top `P`. -/
  P : Subgroup Y
  /-- The minimal generator `K`. -/
  K : Subgroup Y
  hS : S.Normal
  hP : P.Normal
  hK : K.Normal
  hPL : P ≤ L
  hSP : S < P
  /-- All chief factors below `S` are trivial. -/
  scalar_below : IsScalarStack S
  /-- `P/S` is a chief factor: no `Y`-normal subgroup strictly between. -/
  chief : ∀ X : Subgroup Y, X.Normal → S ≤ X → X ≤ P → X = S ∨ X = P
  /-- `V = P/S` is a **nontrivial** module: some `Y`-conjugation moves `P` nontrivially mod
  `S`. -/
  nontrivial_action : ∃ (y : Y) (p : Y), p ∈ P ∧ y * p * y⁻¹ * p⁻¹ ∉ S
  hKP : K ≤ P
  /-- `KS = P`. -/
  gen : K ⊔ S = P
  /-- Minimality of `K` among `Y`-normal subgroups with `K'S = P`. -/
  minimal : ∀ K' : Subgroup Y, K'.Normal → K' ≤ K → K' ⊔ S = P → K' = K

variable {L : Subgroup Y}

/-- `R = Φ(K)`. -/
def MinimalBlock.frattiniK (B : MinimalBlock L) : Subgroup Y := frattiniLike B.K

/-- **Existence of the block** (§7 opening, "Choose …"): if the marked kernel `L` (a normal
finite 2-group, `GQ2.MarkedTarget`'s `L_Y`) is not a scalar stack, a minimal block exists.
[P-14 statement; proof P-15.] -/
theorem exists_minimalBlock (hL : L.Normal) (h2 : IsPGroup 2 L)
    (h : ¬ IsScalarStack L) : Nonempty (MinimalBlock L) := by
  have : Finite (Subgroup Y) :=
    Finite.of_injective (fun H : Subgroup Y => (H : Set Y)) SetLike.coe_injective
  -- `S`: an inclusion-maximal `Y`-normal scalar stack inside `L` (`⊥` is one)
  have hbot :
      (⊥ : Subgroup Y) ∈ {T : Subgroup Y | T.Normal ∧ T ≤ L ∧ IsScalarStack T} := by
    refine ⟨Subgroup.normal_bot, bot_le, 0, fun _ => ⊥, rfl, rfl, fun _ => le_rfl,
      fun _ => Subgroup.normal_bot, ?_⟩
    intro i y x hx
    obtain rfl : x = 1 := by simpa using hx
    simp
  obtain ⟨S, hSmax⟩ := Set.Finite.exists_maximal (Set.toFinite _) ⟨⊥, hbot⟩
  obtain ⟨hSn, hSL, hSstack⟩ := hSmax.prop
  have hSltL : S < L := hSL.lt_of_ne fun hEq => h (hEq ▸ hSstack)
  -- `P`: an inclusion-minimal `Y`-normal subgroup strictly between `S` and `L`
  obtain ⟨P, hPmin⟩ := Set.Finite.exists_minimal
    (Set.toFinite {T : Subgroup Y | T.Normal ∧ S < T ∧ T ≤ L}) ⟨L, hL, hSltL, le_rfl⟩
  obtain ⟨hPn, hSltP, hPL⟩ := hPmin.prop
  -- minimality of `P` is the chief condition
  have hchief : ∀ X : Subgroup Y, X.Normal → S ≤ X → X ≤ P → X = S ∨ X = P := by
    intro X hXn hSX hXP
    rcases hSX.lt_or_eq with hlt | heq
    · exact Or.inr (hPmin.eq_of_le ⟨hXn, hlt, hXP.trans hPL⟩ hXP)
    · exact Or.inl heq.symm
  -- maximality of `S` is the nontriviality of the action on `P/S`
  have hnta : ∃ (y : Y) (p : Y), p ∈ P ∧ y * p * y⁻¹ * p⁻¹ ∉ S := by
    by_contra hall
    push Not at hall
    obtain ⟨n, c, hc0, hcn, hmono, hnorm, hcomm⟩ := hSstack
    -- otherwise `S`'s chain extends one level to `P`
    have hPstack : IsScalarStack P := by
      refine ⟨n + 1, fun i => if i ≤ n then c i else P, ?_, ?_, ?_, ?_, ?_⟩
      · dsimp only
        rwa [if_pos (Nat.zero_le n)]
      · dsimp only
        rw [if_neg (by omega : ¬ n + 1 ≤ n)]
      · intro i
        dsimp only
        by_cases hi : i + 1 ≤ n
        · rw [if_pos (by omega : i ≤ n), if_pos hi]
          exact hmono i
        · by_cases hi' : i ≤ n
          · rw [if_pos hi', if_neg hi]
            have hin : i = n := by omega
            subst hin
            rw [hcn]
            exact hSltP.le
          · rw [if_neg hi', if_neg hi]
      · intro i
        dsimp only
        by_cases hi : i ≤ n
        · rw [if_pos hi]
          exact hnorm i
        · rw [if_neg hi]
          exact hPn
      · intro i y x hx
        dsimp only at hx ⊢
        by_cases hi : i + 1 ≤ n
        · rw [if_pos hi] at hx
          rw [if_pos (by omega : i ≤ n)]
          exact hcomm i y x hx
        · rw [if_neg hi] at hx
          by_cases hi' : i ≤ n
          · have hin : i = n := by omega
            subst hin
            rw [if_pos le_rfl, hcn]
            exact hall y x hx
          · rw [if_neg hi']
            exact hSltP.le (hall y x hx)
    exact hSltP.ne (hSmax.eq_of_le ⟨hPn, hPL, hPstack⟩ hSltP.le)
  -- `K`: an inclusion-minimal `Y`-normal subgroup of `P` with `K ⊔ S = P`
  obtain ⟨K, hKmin⟩ := Set.Finite.exists_minimal
    (Set.toFinite {T : Subgroup Y | T.Normal ∧ T ≤ P ∧ T ⊔ S = P})
    ⟨P, hPn, le_rfl, sup_eq_left.mpr hSltP.le⟩
  obtain ⟨hKn, hKP, hKgen⟩ := hKmin.prop
  exact ⟨⟨hL, h2, S, P, K, hSn, hPn, hKn, hPL, hSltP, hSstack, hchief, hnta, hKP, hKgen,
    fun K' hK'n hK'K hK'gen => hKmin.eq_of_le ⟨hK'n, hK'K.trans hKP, hK'gen⟩ hK'K⟩⟩

/-! ## Lemma 7.1 (simple head) -/

/-- **Lemma 7.1, head clause** — recorded in its load-bearing form `R ≤ K ∩ S` (the paper's
"Since `K/(K∩S) ≅ V` is elementary abelian, `R ≤ K∩S`; the displayed sequence follows"): given
`gen : K ⊔ S = P`, the exact sequence `0 → T₀ → M → V → 0` and the head identification
`M/T₀ ≅ V` are then the second isomorphism theorem
(`QuotientGroup.quotientInfEquivProdNormalQuotient`), which Mathlib supplies — so the inclusion
is the §7-specific content.  [P-14 statement; proof P-15.] -/
theorem lemma_7_1_head (B : MinimalBlock L) : B.frattiniK ≤ B.K ⊓ B.S := by
  refine le_inf (frattiniLike_le B.K) ?_
  -- the `Y`-normal candidate `(Φ(P) ⊔ S) ⊓ P` between `S` and `P`
  have := frattiniLike_normal B.P B.hP
  have := B.hS
  have hXn : ((frattiniLike B.P ⊔ B.S) ⊓ B.P).Normal := by
    have hsup : (frattiniLike B.P ⊔ B.S).Normal := Subgroup.sup_normal _ _
    exact ⟨fun n hn y => Subgroup.mem_inf.mpr
      ⟨hsup.conj_mem _ (Subgroup.mem_inf.mp hn).1 y,
        B.hP.conj_mem _ (Subgroup.mem_inf.mp hn).2 y⟩⟩
  rcases B.chief _ hXn (le_inf le_sup_right B.hSP.le) inf_le_right with hX | hX
  · -- `X = S`: every square/commutator of `K ≤ P` lands in `S`
    refine (Subgroup.closure_le _).mpr ?_
    rintro x (⟨k, hk, rfl⟩ | ⟨k, hk, l, hl, rfl⟩)
    · have hmem : k * k ∈ (frattiniLike B.P ⊔ B.S) ⊓ B.P := Subgroup.mem_inf.mpr
        ⟨Subgroup.mem_sup_left (Subgroup.subset_closure (Or.inl ⟨k, B.hKP hk, rfl⟩)),
          B.P.mul_mem (B.hKP hk) (B.hKP hk)⟩
      rwa [hX] at hmem
    · have hmem : k * l * k⁻¹ * l⁻¹ ∈ (frattiniLike B.P ⊔ B.S) ⊓ B.P := Subgroup.mem_inf.mpr
        ⟨Subgroup.mem_sup_left
            (Subgroup.subset_closure (Or.inr ⟨k, B.hKP hk, l, B.hKP hl, rfl⟩)),
          B.P.mul_mem (B.P.mul_mem (B.P.mul_mem (B.hKP hk) (B.hKP hl))
            (B.P.inv_mem (B.hKP hk))) (B.P.inv_mem (B.hKP hl))⟩
      rwa [hX] at hmem
  · -- `X = P`: the finite-2-group Frattini contradiction
    exfalso
    have hPsub : ∀ p ∈ B.P, p ∈ frattiniLike B.P ⊔ B.S := by
      intro p hp
      have hmem : p ∈ (frattiniLike B.P ⊔ B.S) ⊓ B.P := by rw [hX]; exact hp
      exact (Subgroup.mem_inf.mp hmem).1
    -- the quotient `Q = ↥P ⧸ S` is a nontrivial finite 2-group…
    have : (B.S.subgroupOf B.P).Normal := B.hS.subgroupOf B.P
    have hP2 : IsPGroup 2 B.P := by
      intro g
      obtain ⟨n, hn⟩ := B.h2L ⟨g.1, B.hPL g.2⟩
      refine ⟨n, ?_⟩
      ext
      simpa using congrArg Subtype.val hn
    have : Fact (Nat.Prime 2) := Nat.fact_prime_two
    have hQ2 : IsPGroup 2 (↥B.P ⧸ B.S.subgroupOf B.P) := hP2.to_quotient _
    obtain ⟨p₀, hp₀P, hp₀S⟩ := SetLike.exists_of_lt B.hSP
    have : Nontrivial (↥B.P ⧸ B.S.subgroupOf B.P) := by
      refine ⟨⟨QuotientGroup.mk ⟨p₀, hp₀P⟩, 1, ?_⟩⟩
      rw [ne_eq, QuotientGroup.eq_one_iff]
      exact fun hmem => hp₀S (Subgroup.mem_subgroupOf.mp hmem)
    -- …generated by squares and commutators (through `P ≤ Φ(P)·S`)
    have htop : ∀ x : ↥B.P ⧸ B.S.subgroupOf B.P,
        x ∈ Subgroup.closure
          ({y | ∃ a, y = a * a} ∪ {y | ∃ a b, y = a * b * a⁻¹ * b⁻¹}) := by
      intro x
      obtain ⟨y, rfl⟩ := QuotientGroup.mk'_surjective (B.S.subgroupOf B.P) x
      have hy' : (y : Y) ∈ (frattiniLike B.P : Set Y) * (B.S : Set Y) := by
        rw [← Subgroup.mul_normal (frattiniLike B.P) B.S]
        exact hPsub y.1 y.2
      obtain ⟨f, hf, s, hs, hfs⟩ := hy'
      rw [frattiniLike_eq_map] at hf
      obtain ⟨f', hf', hf'val⟩ := hf
      have hmk : QuotientGroup.mk' (B.S.subgroupOf B.P) y
          = QuotientGroup.mk' (B.S.subgroupOf B.P) f' := by
        symm
        rw [QuotientGroup.mk'_eq_mk']
        refine ⟨⟨s, B.hSP.le hs⟩, Subgroup.mem_subgroupOf.mpr hs, ?_⟩
        ext
        show (f' : Y) * s = (y : Y)
        have hf'' : (f' : Y) = f := hf'val
        rwa [hf'']
      rw [hmk]
      have hmem := Subgroup.mem_map_of_mem (QuotientGroup.mk' (B.S.subgroupOf B.P)) hf'
      rw [MonoidHom.map_closure] at hmem
      refine (Subgroup.closure_le _).mpr ?_ hmem
      rintro _ ⟨z, hz, rfl⟩
      rcases hz with ⟨a, rfl⟩ | ⟨a, b, rfl⟩
      · exact Subgroup.subset_closure (Or.inl ⟨_, by rw [map_mul]⟩)
      · exact Subgroup.subset_closure
          (Or.inr ⟨_, _, by rw [map_mul, map_mul, map_mul, map_inv, map_inv]⟩)
    -- pass to the abelianization: every element is a square
    have habel : ∀ w : Abelianization (↥B.P ⧸ B.S.subgroupOf B.P),
        w ∈ Subgroup.closure {x | ∃ a, x = a * a} := by
      intro w
      obtain ⟨q, rfl⟩ := QuotientGroup.mk'_surjective _ w
      have hmem := Subgroup.mem_map_of_mem
        (Abelianization.of (G := ↥B.P ⧸ B.S.subgroupOf B.P)) (htop q)
      rw [MonoidHom.map_closure] at hmem
      have hcommW : ∀ u v : Abelianization (↥B.P ⧸ B.S.subgroupOf B.P),
          u * v * u⁻¹ * v⁻¹ = 1 := by
        intro u v
        rw [mul_comm u v, mul_assoc v u, mul_inv_cancel, mul_one, mul_inv_cancel]
      refine (Subgroup.closure_le _).mpr ?_ hmem
      rintro _ ⟨z, hz, rfl⟩
      rcases hz with ⟨a, rfl⟩ | ⟨a, b, rfl⟩
      · exact Subgroup.subset_closure ⟨_, by rw [map_mul]⟩
      · have h1 : Abelianization.of (a * b * a⁻¹ * b⁻¹) = 1 := by
          rw [map_mul, map_mul, map_mul, map_inv, map_inv, hcommW]
        rw [h1]
        exact one_mem _
    -- squaring is a surjective, hence injective, endomorphism of the finite abelianization
    have hsurj : Function.Surjective
        (powMonoidHom 2 : Abelianization (↥B.P ⧸ B.S.subgroupOf B.P) →* _) := by
      rw [← MonoidHom.range_eq_top, eq_top_iff]
      intro w _
      refine (Subgroup.closure_le _).mpr ?_ (habel w)
      rintro _ ⟨a, rfl⟩
      exact ⟨a, by rw [powMonoidHom_apply, pow_two]⟩
    have hinj : Function.Injective
        (powMonoidHom 2 : Abelianization (↥B.P ⧸ B.S.subgroupOf B.P) →* _) :=
      Finite.injective_iff_surjective.mpr hsurj
    by_cases hWt : Subsingleton (Abelianization (↥B.P ⧸ B.S.subgroupOf B.P))
    · -- trivial abelianization: `Q` is perfect, contradicting nilpotency of finite 2-groups
      have hcommQ : commutator (↥B.P ⧸ B.S.subgroupOf B.P) = ⊤ := by
        rw [eq_top_iff]
        intro q _
        have h1 : Abelianization.of q = 1 := Subsingleton.elim _ _
        exact (QuotientGroup.eq_one_iff q).mp h1
      have hnil := hQ2.isNilpotent
      obtain ⟨n, hn⟩ := Subgroup.nilpotent_iff_lowerCentralSeries.mp hnil
      have hall : ∀ m,
          Subgroup.lowerCentralSeries (⊤ : Subgroup (↥B.P ⧸ B.S.subgroupOf B.P)) m = ⊤ := by
        intro m
        induction m with
        | zero => rfl
        | succ m ih =>
          rwa [Subgroup.lowerCentralSeries_succ, ih, ← _root_.commutator_def]
      rw [hall n] at hn
      obtain ⟨q, hq⟩ := exists_ne (1 : ↥B.P ⧸ B.S.subgroupOf B.P)
      exact hq (Subgroup.mem_bot.mp (hn ▸ Subgroup.mem_top q))
    · -- nontrivial abelianization: an order-2 element dies under injective squaring
      classical
      rw [not_subsingleton_iff_nontrivial] at hWt
      obtain ⟨w, hw⟩ := exists_ne (1 : Abelianization (↥B.P ⧸ B.S.subgroupOf B.P))
      obtain ⟨n, hn⟩ := (hQ2.to_quotient (commutator _)) w
      have hex : ∃ j, w ^ (2 : ℕ) ^ j = 1 := ⟨n, hn⟩
      have hspec : w ^ (2 : ℕ) ^ Nat.find hex = 1 := Nat.find_spec hex
      have hm0 : Nat.find hex ≠ 0 := by
        intro h0
        rw [h0, pow_zero, pow_one] at hspec
        exact hw hspec
      have hw'1 : w ^ (2 : ℕ) ^ (Nat.find hex - 1) ≠ 1 :=
        Nat.find_min hex (Nat.sub_lt (Nat.pos_of_ne_zero hm0) one_pos)
      have hw'sq : (powMonoidHom 2 : Abelianization _ →* _) (w ^ (2 : ℕ) ^ (Nat.find hex - 1))
          = (powMonoidHom 2 : Abelianization _ →* _) 1 := by
        rw [map_one, powMonoidHom_apply, ← pow_mul]
        have harith : (2 : ℕ) ^ (Nat.find hex - 1) * 2 = 2 ^ Nat.find hex := by
          rw [← pow_succ]
          congr 1
          omega
        rw [harith, hspec]
      exact hw'1 (hinj hw'sq)

/-- **Lemma 7.1, radical clause**: `T₀ = (K ∩ S)·R` is the unique maximal `Y`-normal subgroup
of `K` above `R` — i.e. `T₀ = rad_{𝔽₂[C]} M` and `M/T₀` is the unique simple head.
[P-14 statement; proof P-15: the head clause collapses the right-hand side to `K ⊓ S`; the
chief dichotomy on `X ⊔ S` then leaves two branches — `= P` dies by `K`'s minimality, `= S`
pins `X = K ⊓ S` by `X`'s maximality (a strict inclusion would force `K ≤ S`, hence `P = S`).
Stated after the head clause, which it consumes.] -/
theorem lemma_7_1_radical (B : MinimalBlock L)
    (X : Subgroup Y) (hX : X.Normal) (_hRX : B.frattiniK ≤ X) (hXK : X < B.K)
    (hmax : ∀ X' : Subgroup Y, X'.Normal → X < X' → X' ≤ B.K → X' = B.K) :
    X = (B.K ⊓ B.S) ⊔ B.frattiniK := by
  -- by the head clause `R ≤ K ⊓ S`, the right-hand side is `K ⊓ S`
  rw [sup_eq_left.mpr (lemma_7_1_head B)]
  -- `K ≰ S` (else `P = K ⊔ S = S`, contradicting `S < P`)
  have hKnS : ¬ B.K ≤ B.S := by
    intro hKS
    have hPS : B.P = B.S := by
      rw [← B.gen]
      exact le_antisymm (sup_le hKS le_rfl) le_sup_right
    exact B.hSP.ne hPS.symm
  -- chief dichotomy on the `Y`-normal subgroup `X ⊔ S` between `S` and `P`
  have := B.hS
  have hXSn : (X ⊔ B.S).Normal := Subgroup.sup_normal X B.S
  have hle : X ⊔ B.S ≤ B.P := sup_le (hXK.le.trans B.hKP) B.hSP.le
  rcases B.chief _ hXSn le_sup_right hle with hXS | hXS
  · -- `X ⊔ S = S`: then `X ≤ K ⊓ S`, and maximality of `X` pins the equality
    have hXKS : X ≤ B.K ⊓ B.S := le_inf hXK.le (le_sup_left.trans hXS.le)
    rcases hXKS.lt_or_eq with hlt | heq
    · -- a strict inclusion would force `K ⊓ S = K`, i.e. `K ≤ S`
      exfalso
      have hKSn : (B.K ⊓ B.S).Normal := ⟨fun n hn y => Subgroup.mem_inf.mpr
        ⟨B.hK.conj_mem _ (Subgroup.mem_inf.mp hn).1 y,
          B.hS.conj_mem _ (Subgroup.mem_inf.mp hn).2 y⟩⟩
      have hKK : B.K ⊓ B.S = B.K := hmax _ hKSn hlt inf_le_left
      have : B.K ≤ B.S := by rw [← hKK]; exact inf_le_right
      exact hKnS this
    · exact heq
  · -- `X ⊔ S = P`: minimality of `K` forces `X = K`, contradicting `X < K`
    exact absurd (B.minimal X hX hXK.le hXS) hXK.ne

omit [Finite Y] in
/-- **Lemma 7.1, dual-invariants clause**: `(M^∨)^C = 0` — `K` has no `Y`-normal subgroup of
index 2 above `R` (a nonzero invariant functional on `M` would be its kernel).
[P-14 statement; proof P-15 — chief-dichotomy on `X ⊔ S` + minimality; the `X ⊔ S = S` branch
pins `|P/S| = 2`, whence the `Y`-action mod `S` is trivial, contradicting `nontrivial_action`.
Finiteness-free.] -/
theorem lemma_7_1_dual (B : MinimalBlock L) :
    ¬ ∃ X : Subgroup Y, X.Normal ∧ B.frattiniK ≤ X ∧ X ≤ B.K ∧ (X.subgroupOf B.K).index = 2 := by
  rintro ⟨X, hXn, hRX, hXK, hidx⟩
  -- `X ≠ K` (index 2 ≠ 1)
  have hXne : X ≠ B.K := by
    rintro rfl
    rw [Subgroup.subgroupOf_self, Subgroup.index_top] at hidx
    exact absurd hidx (by omega)
  -- dichotomy on the `Y`-normal subgroup `X ⊔ S` between `S` and `P`
  have := B.hS
  have hXSn : (X ⊔ B.S).Normal := Subgroup.sup_normal X B.S
  have hle : X ⊔ B.S ≤ B.P := sup_le (hXK.trans B.hKP) B.hSP.le
  rcases B.chief _ hXSn le_sup_right hle with hXS | hXS
  · -- `X ⊔ S = S`: then `X ≤ K ⊓ S`, and index 2 factors through `K ⊓ S`
    have hXS' : X ≤ B.S := le_sup_left.trans hXS.le
    have hXKS : X ≤ B.K ⊓ B.S := le_inf hXK hXS'
    have hrel : X.relIndex (B.K ⊓ B.S) * (B.K ⊓ B.S).relIndex B.K = 2 :=
      (Subgroup.relIndex_mul_relIndex X (B.K ⊓ B.S) B.K hXKS inf_le_left).trans hidx
    have hdvd : (B.K ⊓ B.S).relIndex B.K ∣ 2 := ⟨X.relIndex (B.K ⊓ B.S), by
      rw [← hrel]; ring⟩
    rcases (Nat.prime_two.eq_one_or_self_of_dvd _ hdvd) with h1 | h2
    · -- relindex 1: `K ≤ S`, so `P = K ⊔ S = S`, contradicting `S < P`
      have hKS : B.K ≤ B.K ⊓ B.S := Subgroup.relIndex_eq_one.mp h1
      have hPS : B.P = B.S := by
        rw [← B.gen]
        exact le_antisymm (sup_le (hKS.trans inf_le_right) le_rfl) le_sup_right
      exact absurd hPS.symm B.hSP.ne
    · -- relindex 2: `V = P/S` has order 2, so `Y` acts trivially mod `S` — contradiction
      -- with `nontrivial_action`.  Core: conjugation fixes `K` mod `S`…
      have hcomm : ∀ (y k : Y), k ∈ B.K → y * k * y⁻¹ * k⁻¹ ∈ B.S := by
        intro y k hk
        have hc : y * k * y⁻¹ ∈ B.K := B.hK.conj_mem k hk y
        by_cases hkS : k ∈ B.S
        · exact mul_mem (B.hS.conj_mem k hkS y) (inv_mem hkS)
        · have hcS : y * k * y⁻¹ ∉ B.S := by
            intro hc'
            apply hkS
            have h := B.hS.conj_mem _ hc' y⁻¹
            have heq : y⁻¹ * (y * k * y⁻¹) * y⁻¹⁻¹ = k := by group
            rwa [heq] at h
          have hu1 : (⟨y * k * y⁻¹, hc⟩ : B.K) ∉ (B.K ⊓ B.S).subgroupOf B.K := by
            intro hmem
            exact hcS (Subgroup.mem_subgroupOf.mp hmem).2
          have hu2 : (⟨k, hk⟩ : B.K)⁻¹ ∉ (B.K ⊓ B.S).subgroupOf B.K := by
            intro hmem
            rw [inv_mem_iff] at hmem
            exact hkS (Subgroup.mem_subgroupOf.mp hmem).2
          exact (Subgroup.mem_subgroupOf.mp
            (notMem_mul_mem (U := (B.K ⊓ B.S).subgroupOf B.K) h2 hu1 hu2)).2
      -- …and extends to `P = K·S`
      have hcommP : ∀ (y p : Y), p ∈ B.P → y * p * y⁻¹ * p⁻¹ ∈ B.S := by
        intro y p hp
        rw [← B.gen] at hp
        have hp' : p ∈ (B.K : Set Y) * (B.S : Set Y) := by
          rwa [← Subgroup.mul_normal B.K B.S]
        obtain ⟨k, hk, s, hs, rfl⟩ := hp'
        have heq : y * (k * s) * y⁻¹ * (k * s)⁻¹
            = (y * k * y⁻¹ * k⁻¹) * (k * ((y * s * y⁻¹) * s⁻¹) * k⁻¹) := by group
        rw [heq]
        exact mul_mem (hcomm y k hk)
          (B.hS.conj_mem _ (mul_mem (B.hS.conj_mem s hs y) (inv_mem hs)) k)
      obtain ⟨y, p, hpP, hnot⟩ := B.nontrivial_action
      exact hnot (hcommP y p hpP)
  · -- `X ⊔ S = P`: minimality forces `X = K`, contradicting index 2
    exact hXne (B.minimal X hXn hXK hXS)


end SectionSeven

end GQ2
