"""W50 -- an INDEPENDENT (non-Magma) implementation of the class-two layer of D_sq 1.

Model.  F/P_3 for the free pro-2 group F of rank 5 is the class-two group

    elements  (v, q),   v in (Z/4)^5,  q in Lambda^2(F_2^5) = F_2^10
    (v,q)(v',q') = (v+v', q+q'+ c(v,v')),      c(v,v') = sum_{i>j} v_i v'_j E_ij  (mod 2)

c is bilinear, hence a 2-cocycle; [x,y] = xbar ^ ybar; the group has order 4^5*2^10 = 2^20,
is generated by 5 elements and has exponent-2 class 2 -- so it IS F/P_3 (the largest such).

The relator's image R0 has R0^2 = 1 and [R0, F] = 1 (its abelian class 2*e_x1 is even), so
the normal closure of R0 is {1, R0} and  Q_2 = (F/P_3)/{1,R0}  has order 2^19 -- which is
exactly what Magma's pQuotient(G,2,2) reports.  Testing "R(m) = 1 in Q_2" is therefore
testing "R(m) in {1, R0}" here.

This file re-derives, with no group-theory library at all:
  * the level-one survivor set of the class-two balance gate,
  * the forced x0-slot dressing  a1 = U^-s V^t  (GradedTwo S6),
  * the GL_2(F_2) structure of the handle block.
"""

from itertools import product
from padic_c0 import c0

N = 5                                   # sigma, x0, x1, u, v
IDX = [(i, j) for i in range(N) for j in range(i)]      # i > j
POS = {p: k for k, p in enumerate(IDX)}


def cocycle(v, w):
    q = 0
    for i, j in IDX:
        if (v[i] & 1) and (w[j] & 1):
            q ^= 1 << POS[(i, j)]
    return q


def mul(x, y):
    v, q = x
    w, r = y
    return (tuple((v[k] + w[k]) % 4 for k in range(N)), q ^ r ^ cocycle(v, w))


ONE = ((0,) * N, 0)


def inv(x):
    v, q = x
    iv = tuple((-v[k]) % 4 for k in range(N))
    return (iv, q ^ cocycle(v, iv))          # since x*inv = (0, q ^ r ^ c(v,iv)) = ONE


def pw(x, n):
    n = int(n)
    if n < 0:
        x, n = inv(x), -n
    r = ONE
    for _ in range(n):
        r = mul(r, x)
    return r


def conj(x, g):
    return mul(mul(inv(g), x), g)


def comm(x, y):
    return mul(mul(inv(x), inv(y)), mul(x, y))


GEN = [(tuple([1 if k == i else 0 for k in range(N)]), 0) for i in range(N)]
assert [g[0] for g in GEN] == [(1, 0, 0, 0, 0), (0, 1, 0, 0, 0), (0, 0, 1, 0, 0),
                               (0, 0, 0, 1, 0), (0, 0, 0, 0, 1)]
S, X0, X1, U, V = GEN


def relword(m):
    """sqRelWord at h = 1, exactly as in GQ2/Dyadic/SqCore/Cores.lean."""
    s, x, y, u, v = m
    return mul(mul(mul(mul(inv(conj(x, s)), inv(pw(x, 3))), pw(y, 2)),
                   comm(y, conj(y, s))), comm(u, v))


R0 = relword(GEN)
assert mul(R0, R0) == ONE, "R0 is not an involution"
assert all(comm(R0, g) == ONE for g in GEN), "R0 is not central"
assert R0 != ONE


def dies(x):
    return x == ONE or x == R0                # trivial in Q_2 = (F/P_3)/{1,R0}


def frame(t, s, codes):
    """base = (sigma, x0, x1, U, V) with U = w^-t u, V = v w^-s, dressed by the codes."""
    w = mul(S, inv(pw(X0, c0 % 4)))
    Ub = mul(inv(pw(w, t)), U)
    Vb = mul(V, inv(pw(w, s)))
    tb = mul(inv(pw(X0, 2)), X1)
    base = [S, X0, X1, Ub, Vb]
    dress = [mul(mul(pw(Ub, a >> 2), pw(Vb, (a >> 1) & 1)), pw(tb, a & 1)) for a in range(8)]
    return [mul(base[i], dress[codes[i]]) for i in range(N)], (Ub, Vb, tb)


def indep(m):
    """SqModTwoIndep: the five abelian classes independent over F_2."""
    rows = [[(x[0][k]) & 1 for k in range(N)] for x in m]
    rk, piv = 0, []
    for col in range(N):
        r = next((i for i in range(rk, N) if rows[i][col]), None)
        if r is None:
            continue
        rows[rk], rows[r] = rows[r], rows[rk]
        for i in range(N):
            if i != rk and rows[i][col]:
                rows[i] = [a ^ b for a, b in zip(rows[i], rows[rk])]
        rk += 1
    return rk == N


NAMES = ["1", "t", "V", "Vt", "U", "Ut", "UV", "UVt"]

if __name__ == "__main__":
    print("independent class-two check (pure python, no group library)")
    print("relator image R0 nontrivial, central, of order 2 :  Q_2 has order 2^19  -- OK")
    print()
    allsurv = {}
    for t in range(4):
        for s in range(4):
            surv = []
            for codes in product(range(8), repeat=5):
                m, _ = frame(t, s, codes)
                if dies(relword(m)) and indep(m):
                    surv.append(codes)
            allsurv[(t, s)] = surv
            forced = 4 * (s % 2) + 2 * (t % 2)          # U^-s V^t mod squares
            x0set = {c[1] for c in surv}
            sset = {c[0] for c in surv}
            x1set = {c[2] for c in surv}
            # handle block as 2x2 matrices over F_2 acting on (Ubar, Vbar)
            mats = set()
            for c in surv:
                p, q = (c[3] >> 2) & 1, (c[3] >> 1) & 1
                p2, q2 = (c[4] >> 2) & 1, (c[4] >> 1) & 1
                mats.add(((1 ^ p, q), (p2, 1 ^ q2)))
            gl2 = {((a, b), (cc, d)) for a in range(2) for b in range(2)
                   for cc in range(2) for d in range(2) if (a * d - b * cc) % 2 == 1}
            print(f"(t,s)=({t},{s}) mod 4 : #surv {len(surv):3d} | sigma-codes {sorted(sset)}"
                  f" x0-codes {sorted(x0set)} (forced {forced}={NAMES[forced]})"
                  f" x1-codes {sorted(x1set)} | handle block = GL2(F2)? {mats == gl2}")
    sizes = {len(v) for v in allsurv.values()}
    print("\nsurvivor-set size, uniform over all 16 residues:", sizes)
