/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-4.8 and Fable-5
-/
import GQ2.Dyadic.LocalGauss.EulerShapiro
import GQ2.Dyadic.LocalGauss.Q0
import GQ2.Dyadic.TameQuotientK
import GQ2.Dyadic.Parameters
import GQ2.UnramifiedModel
import GQ2.GaussSignsRamified

/-!
# The unramified Gauss sign over a general base (LG3): `(−1)^n · 2^{n·d/2}`

Packet Prop. 6.8 / eq. (115) at a finite extension `K/ℚ₂` of degree `n`.  For a simple faithful
`𝔽₂[C]`-module `V` with `#V = 2^{2m}` at an **unramified** marking (`c(τ)` acts trivially), the
base determinant form `Q⁰_{K,V}` on `H¹(G_K, V)` has

  `arf (Q⁰) = n mod 2`,   `#(Q⁰)⁻¹(0) = 2^{2mn−1} + (−1)^n · 2^{mn−1}`,

i.e. the Gauss sign is `(−1)^n · 2^{n·dim V/2}`.  At `n = 1` this is the ℚ₂ statement
`GQ2.UnramifiedModel.prop_6_18_unramified` (§7 pins the regression).

## Proof route (owner-visible deviation from the packet — design memo §3, risk 7)

The packet proves Prop. 6.8 by Hermitian diagonalization of `H¹` over `E = End_H(V)`; the ℚ₂
model instead feeds the `⟨T⟩`-engine `GQ2.GaussSigns.arf_eq_s_ramified` with the **Schur
transfer** (`H¹ ≅ V` simple, `GQ2.UnramifiedModel.cCoeff_faithful_and_simple`) and `s = 1`.
Neither transfers verbatim to `n ≥ 2`: `H¹(G_K, V) ≅ V^n` is **not** a simple `C`-module, so the
Schur route is unavailable.

The route taken here is the general Arf-parity engine `GQ2.GaussSigns.arf_eq_of_free`
(`GQ2/GaussSigns.lean`) with `m' := m`, `s := n`, `U := C`:

* `#H¹ = (#V)^n = 2^{2(m·n)}` — the **only** place `n` enters — from LG2a's Euler characteristic
  (`GQ2.Dyadic.localEulerCharacteristic_open`) with `#H⁰ = #H² = 1` (§5);
* **freeness of `C` on `H¹ ∖ 0`** replaces the Schur transfer: `𝔽₂[C]` acts on `H¹` through
  `mapCoeff1`, and its image is the *field* `F = 𝔽₂⟨σ⟩ ⊆ End V` (Schur + little Wedderburn on
  the `V`-side only), so `H¹` is an `F`-vector space and freeness is field-linearity —
  `n`-independent (§3, §4);
* the arithmetic inputs `#C ∣ 2^{2m} − 1`, `#C ∤ 2^m − 1`, `#C > 2` are `V`-side facts about the
  irreducible operator `T` (§4), also `n`-independent;
* `C`-invariance of `Q⁰` is Lemma 6.14 naturality plus the explicit datum coboundary (§6),
  retyped from the ℚ₂ model.

The Hermitian-line file `GQ2/DeepPart/HermitianCount.lean` is ambient-free and untouched; it
remains the packet-faithful alternative and the `n = 1` cross-check.

## Contents

* §1 `c_cyclic_q`, `comm_of_cyclic` — the acting group is cyclic at every residue cardinality
  `q = q_K` (F3's `gen_tq_quotient` replaces `SectionThree.gen_ttame_quotient`).
* §2 `cCoeffK` / `cActionH1K` — the coefficient action of `C` on `H¹(Γ, V)` (clone of
  `GQ2.UnramifiedModel.{cCoeff, cActionH1}` against `GQ2.Dyadic.Q0loc`).
* §3 the `V`-side Schur/Wedderburn block: `𝔽₂⟨σ⟩` is a field.
* §4 `cCoeffK_free` (field-linearity ⇒ free action on `H¹ ∖ 0`) and `card_dvd_of_cyclic_simple`
  (the three arithmetic engine inputs).
* §5 the Euler collapse at a general `Γ`: `card_H0_eq_one_of_surjectiveK`,
  `card_H2_eq_one_of_card_H0_eq_oneK`, `card_H1_eq_two_pow_of_euler`.
* §6 `lemma_6_14K`, `graphPullback_comap_smul_sub_mem_B2K`, `Q0loc_smul_eqK` — `C`-invariance
  of `Q⁰`.
* §7 the headline theorems `arf_Q0loc_unramified_K`, `prop_6_18_unramified_K_even` /
  `prop_6_18_unramified_K_odd`, and the packaged `G_K`-level `prop_6_18_unramified_K` over F1's
  `FieldParameters` (where the AX3/AX4 binders enter).
* §8 the **`n = 1` regression** `prop_6_18_unramified_K_q2`, with a kernel statement pin against
  `GQ2.UnramifiedModel.prop_6_18_unramified`.

Axioms: every declaration is parametrized over the Tate-duality bundle `D`, so the `V`-side and
`H¹`-side algebra prints the standard three; the three theorems that consume LG2a's Euler
characteristic (`card_H1_eq_two_pow_of_euler`, `prop_6_18_unramified_K`,
`prop_6_18_unramified_K_q2`) print std-3 + **B7**, which is exactly the ℚ₂ model's set.  AX3/AX4
appear only as explicit hypothesis binders (`tameFK`, `htameFK`, `hfac`) — no census change.
-/

namespace GQ2.Dyadic

open GQ2 GQ2.ContCoh GQ2.QuadraticFp2

open scoped Classical

/-! ## §1 The acting group is cyclic at a general residue cardinality

`GQ2.UnramifiedModel.c_cyclic` (`GQ2/UnramifiedModel.lean`) is not `f = 1` mathematics; it is
`q = 2`-*typed*.  The general statement is its verbatim twin over F3's `T_q = ⟨σ, τ ∣ τ^σ = τ^q⟩`
(`GQ2/Dyadic/TameQuotientK.lean`), whose two-generator topological generation in discrete
quotients is `GQ2.Dyadic.gen_tq_quotient`. -/

section CCyclic

variable {C : Type} [Group C] [TopologicalSpace C] [DiscreteTopology C]
variable {V : Type} [AddCommGroup V] [DistribMulAction C V]

/-- **Step 1 of the unramified model at residue cardinality `q`**: the acting group `C` is
cyclic, generated by `c σ`.  Faithfulness (`hfaith`) upgrades the trivial *action* `hunram` to
the trivial *element* `c τ = 1`, then tame topological generation (`gen_tq_quotient`) collapses
the two generators to one.  The `q = 2` precedent is `GQ2.UnramifiedModel.c_cyclic`. -/
theorem c_cyclic_q {q : ℕ} (c : ContinuousMonoidHom (Tq q) C) (hc : Function.Surjective ⇑c)
    (hfaith : ∀ h : C, (∀ v : V, h • v = v) → h = 1)
    (hunram : ∀ v : V, c (tqTau q) • v = v) :
    ∀ x : C, x ∈ Subgroup.zpowers (c (tqSigma q)) := by
  have hcl : Subgroup.closure {c (tqSigma q), c (tqTau q)} = ⊤ :=
    gen_tq_quotient c.toMonoidHom c.continuous_toFun hc
  rw [hfaith (c (tqTau q)) hunram, Set.pair_comm, Subgroup.closure_insert_one,
    ← Subgroup.zpowers_eq_closure] at hcl
  intro x; rw [hcl]; trivial

end CCyclic

section Commuting

variable {C : Type*} [Group C]

/-- Commutativity of a cyclic `C` (generated by `t`): every element is a power of `t`. -/
theorem comm_of_cyclic (t : C) (hcyc : ∀ x : C, x ∈ Subgroup.zpowers t) (a b : C) :
    a * b = b * a := by
  obtain ⟨i, hi⟩ := Subgroup.mem_zpowers_iff.mp (hcyc a)
  obtain ⟨j, hj⟩ := Subgroup.mem_zpowers_iff.mp (hcyc b)
  rw [← hi, ← hj, ← zpow_add, ← zpow_add, add_comm]

end Commuting

/-! ## §2 The coefficient action of `C` on `H¹(Γ, V)`

Clone of `GQ2.UnramifiedModel.{cCoeff, cActionH1}` with the ambient `G_ℚ₂` replaced by a general
topological group `Γ` (design memo §2 #7: this block lives in LG3's file).  The functoriality of
`mapCoeff1` it descends from (`mapCoeff1_id`, `mapCoeff1_comp`, `GQ2/Cohomology.lean`) is already
ambient-generic. -/

section CoefficientAction

variable {Γ : Type} [Group Γ] [TopologicalSpace Γ] [IsTopologicalGroup Γ]
variable {C : Type} [Group C] [TopologicalSpace C]
variable {V : Type} [AddCommGroup V] [TopologicalSpace V] [DiscreteTopology V]
  [DistribMulAction Γ V] [ContinuousSMul Γ V] [DistribMulAction C V]

/-- **The coefficient endomorphism of `H¹(Γ, V)` attached to `c : C`** (for a `ρ`-factored
action with `C` commutative): `c • ·` is a `Γ`-equivariant additive endo of `V` — equivariance is
commutativity of `C` with the `ρ`-factored action — so it acts on `H¹` via `mapCoeff1`. -/
noncomputable def cCoeffK (ρ : ContinuousMonoidHom Γ C)
    (hρ : ∀ (g : Γ) (v : V), g • v = ρ g • v)
    (hCcomm : ∀ a b : C, a * b = b * a) (c : C) :
    H1 Γ V →+ H1 Γ V :=
  mapCoeff1 (DistribSMul.toAddMonoidHom V c) continuous_of_discreteTopology
    (fun g v => by
      show c • (g • v) = g • (c • v)
      rw [hρ g v, hρ g (c • v), ← mul_smul, ← mul_smul, hCcomm])

/-- **The coefficient action of a commutative `C` on `H¹(Γ, V)`**: the `DistribMulAction` axioms
for `cCoeffK` descend from `mapCoeff1` functoriality. -/
@[reducible] noncomputable def cActionH1K (ρ : ContinuousMonoidHom Γ C)
    (hρ : ∀ (g : Γ) (v : V), g • v = ρ g • v)
    (hCcomm : ∀ a b : C, a * b = b * a) : DistribMulAction C (H1 Γ V) where
  smul c := cCoeffK ρ hρ hCcomm c
  one_smul x := by
    induction x using QuotientAddGroup.induction_on with
    | _ z =>
      show mapCoeff1 (DistribSMul.toAddMonoidHom V (1 : C)) _ _ (H1mk Γ V z) = H1mk Γ V z
      rw [mapCoeff1_H1mk]
      congr 1
      exact Subtype.ext (funext fun g => one_smul _ _)
  mul_smul a b x := by
    induction x using QuotientAddGroup.induction_on with
    | _ z =>
      show mapCoeff1 (DistribSMul.toAddMonoidHom V (a * b)) _ _ (H1mk Γ V z)
        = mapCoeff1 (DistribSMul.toAddMonoidHom V a) _ _
            (mapCoeff1 (DistribSMul.toAddMonoidHom V b) _ _ (H1mk Γ V z))
      rw [mapCoeff1_H1mk, mapCoeff1_H1mk, mapCoeff1_H1mk]
      congr 1
      exact Subtype.ext (funext fun g => mul_smul a b _)
  smul_zero c := map_zero _
  smul_add c x y := map_add _ _ _

omit [IsTopologicalGroup Γ] [ContinuousSMul Γ V] in
/-- The action of `cActionH1K` is `cCoeffK`, by definition. -/
theorem cActionH1K_smul (ρ : ContinuousMonoidHom Γ C)
    (hρ : ∀ (g : Γ) (v : V), g • v = ρ g • v)
    (hCcomm : ∀ a b : C, a * b = b * a) (c : C) (x : H1 Γ V) :
    letI := cActionH1K ρ hρ hCcomm
    c • x = cCoeffK ρ hρ hCcomm c x := rfl

end CoefficientAction

/-! ## §3 The `V`-side Schur/Wedderburn block: `F = 𝔽₂⟨σ⟩` is a field

Ambient-free (no `Γ` appears): the `V`-side of `GQ2.UnramifiedModel.cCoeff_faithful_and_simple`,
re-proved here because the model's versions are `private`.  These are the *only* inputs the
freeness of §4 needs; the model's `H¹`-side simplicity conclusion (which needs `#H¹ = #V`, false
for `n ≥ 2`) is **not** reproduced. -/

section SchurField

variable {C : Type*} [Group C] [Finite C]
variable {V : Type*} [AddCommGroup V] [Finite V] [DistribMulAction C V]

omit [Finite V] in
/-- **Membership + `C`-equivariance**: for a cyclic `C = ⟨T⟩`, every `c : C` acts on `V` through
the subring `F := 𝔽₂⟨σ⟩ ⊆ End V` generated by `σ = ` the `T`-action, and every element of `F` is
`C`-equivariant (it commutes with `σ`, hence with every power of `σ`). -/
theorem endRing_mem_and_equiv (T : C) (hcyc : ∀ x : C, x ∈ Subgroup.zpowers T) :
    (∀ c : C, DistribMulAction.toAddMonoidEnd C V c
        ∈ Subring.closure {DistribMulAction.toAddMonoidEnd C V T}) ∧
    (∀ f ∈ Subring.closure {DistribMulAction.toAddMonoidEnd C V T},
        ∀ (c : C) (v : V), f (c • v) = c • f v) := by
  set σ : AddMonoid.End V := DistribMulAction.toAddMonoidEnd C V T with hσdef
  set F : Subring (AddMonoid.End V) := Subring.closure {σ} with hFdef
  have hfin : IsOfFinOrder T :=
    isOfFinOrder_iff_pow_eq_one.mpr ⟨orderOf T, orderOf_pos T, pow_orderOf_eq_one T⟩
  have hnatpow : ∀ g : C, ∃ k : ℕ, T ^ k = g := fun g =>
    (Submonoid.mem_powers_iff g T).mp (hfin.mem_powers_iff_mem_zpowers.mpr (hcyc g))
  have hactpow : ∀ c : C, ∃ k : ℕ, DistribMulAction.toAddMonoidEnd C V c = σ ^ k := by
    intro c
    obtain ⟨k, hk⟩ := hnatpow c
    exact ⟨k, by rw [← hk, map_pow]⟩
  have hmemAct : ∀ c : C, DistribMulAction.toAddMonoidEnd C V c ∈ F := by
    intro c
    obtain ⟨k, hk⟩ := hactpow c
    rw [hk]
    exact pow_mem (Subring.subset_closure (Set.mem_singleton σ)) k
  have hcommσ : ∀ f ∈ F, f * σ = σ * f := by
    intro f hf
    induction hf using Subring.closure_induction with
    | mem x hx => rw [Set.mem_singleton_iff.mp hx]
    | zero => rw [zero_mul, mul_zero]
    | one => rw [one_mul, mul_one]
    | add x y hx hy ihx ihy => rw [add_mul, mul_add, ihx, ihy]
    | neg x hx ih => rw [neg_mul, mul_neg, ih]
    | mul x y hx hy ihx ihy => rw [mul_assoc, ihy, ← mul_assoc, ihx, mul_assoc]
  have hCequivF : ∀ f ∈ F, ∀ (c : C) (v : V), f (c • v) = c • f v := by
    intro f hf c v
    obtain ⟨k, hk⟩ := hactpow c
    have hcomm : f * σ ^ k = σ ^ k * f := Commute.pow_right (hcommσ f hf) k
    have h1 : ∀ w : V, c • w = (σ ^ k) w := fun w => by rw [← hk]; rfl
    calc f (c • v) = f ((σ ^ k) v) := by rw [h1]
      _ = (f * σ ^ k) v := rfl
      _ = (σ ^ k * f) v := by rw [hcomm]
      _ = (σ ^ k) (f v) := rfl
      _ = c • f v := (h1 (f v)).symm
  exact ⟨hmemAct, hCequivF⟩

omit [Finite C] in
/-- **Schur bijectivity**: a nonzero element of `F = 𝔽₂⟨σ⟩ ⊆ End V` is bijective on `V`.  Its
kernel is a `C`-stable subgroup, hence `⊥` or `⊤` by simplicity; `⊤` is excluded by `f ≠ 0`, so
injectivity — and bijectivity, `V` being finite — follows. -/
theorem endRing_bijective_of_ne_zero (T : C)
    (hsimple : ∀ W : AddSubgroup V, (∀ (h : C), ∀ w ∈ W, h • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (hCequivF : ∀ f ∈ Subring.closure {DistribMulAction.toAddMonoidEnd C V T},
        ∀ (c : C) (v : V), f (c • v) = c • f v) :
    ∀ f ∈ Subring.closure {DistribMulAction.toAddMonoidEnd C V T}, f ≠ 0 →
      Function.Bijective f := by
  intro f hf hne
  let K : AddSubgroup V :=
    { carrier := {v | f v = 0}
      zero_mem' := map_zero f
      add_mem' := fun {a b} ha hb => by
        show f (a + b) = 0
        rw [map_add, show f a = 0 from ha, show f b = 0 from hb, add_zero]
      neg_mem' := fun {a} ha => by
        show f (-a) = 0
        rw [map_neg, show f a = 0 from ha, neg_zero] }
  have hKstab : ∀ (c : C), ∀ v ∈ K, c • v ∈ K := by
    intro c v hv
    show f (c • v) = 0
    rw [hCequivF f hf c v, show f v = 0 from hv, smul_zero]
  rcases hsimple K hKstab with hb | ht
  · refine Finite.injective_iff_bijective.mp (fun a b hab => ?_)
    have hmem : a - b ∈ K := by
      show f (a - b) = 0
      rw [map_sub, hab, sub_self]
    rw [hb, AddSubgroup.mem_bot] at hmem
    exact sub_eq_zero.mp hmem
  · refine absurd (AddMonoidHom.ext fun v => ?_) hne
    have hmem : v ∈ K := ht ▸ AddSubgroup.mem_top v
    exact hmem

omit [Finite C] in
/-- **`F` is a field**: `F = 𝔽₂⟨σ⟩` is a finite domain (nonzero elements are bijective, so
non-zero-divisors), hence a field by little Wedderburn. -/
theorem endRing_isField (T : C) (hVnt : Nontrivial V)
    (hbij : ∀ f ∈ Subring.closure {DistribMulAction.toAddMonoidEnd C V T}, f ≠ 0 →
      Function.Bijective f) :
    IsField (Subring.closure {DistribMulAction.toAddMonoidEnd C V T}) := by
  haveI := hVnt
  haveI : Finite (AddMonoid.End V) :=
    Finite.of_injective (fun f => (f : V → V)) DFunLike.coe_injective
  set F : Subring (AddMonoid.End V) := Subring.closure {DistribMulAction.toAddMonoidEnd C V T}
    with hFdef
  haveI : Nontrivial F := by
    refine ⟨0, 1, fun h => ?_⟩
    obtain ⟨v, hv⟩ := exists_ne (0 : V)
    apply hv
    have h2 : ((0 : F) : AddMonoid.End V) v = ((1 : F) : AddMonoid.End V) v := by rw [h]
    simpa using h2.symm
  haveI : NoZeroDivisors F := by
    refine ⟨fun {a b} hab => ?_⟩
    by_contra! hcon
    obtain ⟨ha, hb⟩ := hcon
    have hbbij : Function.Bijective (b : AddMonoid.End V) :=
      hbij b.1 b.2 (fun h0 => hb (Subtype.ext h0))
    have habij : Function.Bijective (a : AddMonoid.End V) :=
      hbij a.1 a.2 (fun h0 => ha (Subtype.ext h0))
    obtain ⟨v, hv⟩ := exists_ne (0 : V)
    have h0 : (a : AddMonoid.End V) ((b : AddMonoid.End V) v) = 0 := by
      have := congrArg (fun g : F => (g : AddMonoid.End V) v) hab
      simpa using this
    have hbv : (b : AddMonoid.End V) v = 0 := habij.1 (by rw [h0, map_zero])
    exact hv (hbbij.1 (by rw [hbv, map_zero]))
  haveI : IsDomain F := NoZeroDivisors.to_isDomain F
  exact Finite.isDomain_to_isField F

end SchurField

/-! ## §4 Freeness on `H¹ ∖ 0` and the arithmetic engine inputs

The two blocks that replace the ℚ₂ Schur transfer.  Both are `n`-independent: freeness is
field-linearity of the `F`-action on `H¹`, and the divisibility facts are statements about the
irreducible operator `T` on `V` alone. -/

section Freeness

variable {Γ : Type} [Group Γ] [TopologicalSpace Γ] [IsTopologicalGroup Γ]
variable {C : Type} [Group C] [TopologicalSpace C] [Finite C]
variable {V : Type} [AddCommGroup V] [TopologicalSpace V] [DiscreteTopology V] [Finite V]
  [DistribMulAction Γ V] [ContinuousSMul Γ V] [DistribMulAction C V]

omit [IsTopologicalGroup Γ] [ContinuousSMul Γ V] in
/-- **Freeness of the coefficient action on `H¹ ∖ 0`** — the replacement for the ℚ₂ Schur
transfer (`GQ2.UnramifiedModel.cCoeff_faithful_and_simple`), which is unavailable at `n ≥ 2`
because `H¹(G_K, V) ≅ V^n` is not a simple `C`-module.

`𝔽₂[C]` acts on `H¹` through `mapCoeff1`, additively and multiplicatively (`Φ` below), so the
action factors through the *field* `F = 𝔽₂⟨σ⟩ ⊆ End V` of §3.  If `u` fixes a nonzero class then
`Φ(u − 1)` kills it; were `u − 1` nonzero it would be invertible in `F`, forcing the class to
vanish.  So `u` acts trivially on `V`, hence `u = 1` by faithfulness.  **No hypothesis on
`#H¹`** — this is exactly why the route survives at every `n`. -/
theorem cCoeffK_free (ρ : ContinuousMonoidHom Γ C)
    (hρ : ∀ (g : Γ) (v : V), g • v = ρ g • v) (hCcomm : ∀ a b : C, a * b = b * a)
    (T : C) (hcyc : ∀ x : C, x ∈ Subgroup.zpowers T)
    (hfaith : ∀ h : C, (∀ v : V, h • v = v) → h = 1)
    (hsimple : ∀ W : AddSubgroup V, (∀ (h : C), ∀ w ∈ W, h • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (hVnt : Nontrivial V) (u : C) (x : H1 Γ V) (hx : x ≠ 0)
    (hux : cCoeffK ρ hρ hCcomm u x = x) : u = 1 := by
  classical
  set σ : AddMonoid.End V := DistribMulAction.toAddMonoidEnd C V T with hσdef
  set F : Subring (AddMonoid.End V) := Subring.closure {σ} with hFdef
  obtain ⟨hmemAct, hCequivF⟩ := endRing_mem_and_equiv (V := V) T hcyc
  have hbij := endRing_bijective_of_ne_zero (V := V) T hsimple hCequivF
  have hfield := endRing_isField (V := V) T hVnt hbij
  -- the transfer `Φ : F → End(H¹)` through `mapCoeff1`
  have hGequivF : ∀ f (hf : f ∈ F), ∀ (γ : Γ) (v : V), f (γ • v) = γ • f v := by
    intro f hf γ v
    rw [hρ γ v, hρ γ (f v)]
    exact hCequivF f hf (ρ γ) v
  set Φ : F → (H1 Γ V →+ H1 Γ V) := fun f =>
    mapCoeff1 (f : AddMonoid.End V) continuous_of_discreteTopology (hGequivF f.1 f.2)
    with hΦdef
  have hΦmul : ∀ (f g : F) (y : H1 Γ V), Φ (f * g) y = Φ f (Φ g y) := by
    intro f g y
    induction y using QuotientAddGroup.induction_on with
    | _ z => rfl
  have hΦadd : ∀ (f g : F) (y : H1 Γ V), Φ (f + g) y = Φ f y + Φ g y := by
    intro f g y
    induction y using QuotientAddGroup.induction_on with
    | _ z => rfl
  have hΦone : ∀ y : H1 Γ V, Φ 1 y = y := by
    intro y
    induction y using QuotientAddGroup.induction_on with
    | _ z => rfl
  have hΦzero : ∀ y : H1 Γ V, Φ 0 y = 0 := by
    intro y
    induction y using QuotientAddGroup.induction_on with
    | _ z => rfl
  have hΦsub : ∀ (f g : F) (y : H1 Γ V), Φ (f - g) y = Φ f y - Φ g y := by
    intro f g y
    have h1 := hΦadd (f - g) g y
    rw [sub_add_cancel] at h1
    rw [eq_sub_iff_add_eq, ← h1]
  have hcCoeffΦ : ∀ (c : C) (y : H1 Γ V),
      cCoeffK ρ hρ hCcomm c y = Φ ⟨DistribMulAction.toAddMonoidEnd C V c, hmemAct c⟩ y := by
    intro c y
    induction y using QuotientAddGroup.induction_on with
    | _ z => rfl
  -- `u − 1` kills `x`; if it were invertible, `x = 0`
  set w : F := ⟨DistribMulAction.toAddMonoidEnd C V u, hmemAct u⟩ - 1 with hwdef
  by_cases hw : w = 0
  · -- `u` acts trivially on `V`
    refine hfaith u fun v => ?_
    have h1 : (w : AddMonoid.End V) v = ((0 : F) : AddMonoid.End V) v := by rw [hw]
    have h2 : u • v - v = 0 := by
      have h3 : (w : AddMonoid.End V) v = u • v - v := rfl
      rw [← h3, h1]
      rfl
    exact sub_eq_zero.mp h2
  · exfalso
    obtain ⟨z, hz⟩ := hfield.mul_inv_cancel hw
    have hΦw : Φ w x = 0 := by
      rw [hwdef, hΦsub, ← hcCoeffΦ, hux, hΦone, sub_self]
    apply hx
    have hcm : w * z = z * w := hfield.mul_comm w z
    calc x = Φ 1 x := (hΦone x).symm
      _ = Φ (z * w) x := by rw [← hz, hcm]
      _ = Φ z (Φ w x) := hΦmul z w x
      _ = Φ z 0 := by rw [hΦw]
      _ = 0 := map_zero _

end Freeness

section Arithmetic

variable {C : Type*} [Group C] [Finite C]
variable {V : Type*} [AddCommGroup V] [Finite V] [DistribMulAction C V]

/-- **An order dividing `2^{2a} − 1` but not `2^a − 1` (`a ≥ 1`) exceeds `2`** (it is odd — else
`2 ∣ 2^{2a} − 1` — and it is not `1`).  Restatement of the private
`GQ2.GaussSigns.two_lt_orderOf`. -/
theorem two_lt_of_dvd_sub_one {N a : ℕ} (ha : 1 ≤ a) (hsub : N ∣ 2 ^ (2 * a) - 1)
    (hnot : ¬ N ∣ 2 ^ a - 1) : 2 < N := by
  have hne1 : N ≠ 1 := fun h1 => hnot (by rw [h1]; exact one_dvd _)
  have hodd : Odd N := by
    rcases Nat.even_or_odd N with h | h
    · exfalso
      have h2d : (2 : ℕ) ∣ 2 ^ (2 * a) - 1 := dvd_trans h.two_dvd hsub
      have hev : (2 : ℕ) ∣ 2 ^ (2 * a) := dvd_pow_self 2 (by omega)
      have h1le : 1 ≤ 2 ^ (2 * a) := Nat.one_le_two_pow
      omega
    · exact h
  rcases hodd with ⟨j, hj⟩; omega

/-- **The three arithmetic inputs of the Arf-parity engine**, all `V`-side and `n`-independent:
for a cyclic `C = ⟨T⟩` acting faithfully and simply on an exponent-2 `V` with `#V = 2^{2m}`,

  `#C ∣ 2^{2m} − 1`,  `#C ∤ 2^m − 1`,  `#C > 2`.

`T` acts irreducibly on the `2m`-dimensional `𝔽₂`-space `V`, so it is a unit of the field
`𝔽₂[T] ≅ 𝔽_{2^{2m}}` (`GQ2.GaussSigns.irreducible_operator_pow_card_sub_one`) and cannot satisfy
`T^{2^m − 1} = 1` (`GQ2.GaussSigns.irreducible_operator_pow_ne_one`). -/
theorem card_dvd_of_cyclic_simple (T : C) (hcyc : ∀ x : C, x ∈ Subgroup.zpowers T)
    (hfaith : ∀ h : C, (∀ v : V, h • v = v) → h = 1)
    (hsimple : ∀ W : AddSubgroup V, (∀ (h : C), ∀ w ∈ W, h • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (h2 : ∀ v : V, v + v = 0) (m : ℕ) (hm : 1 ≤ m) (hcard : Nat.card V = 2 ^ (2 * m)) :
    Nat.card C ∣ 2 ^ (2 * m) - 1 ∧ ¬ Nat.card C ∣ 2 ^ m - 1 ∧ 2 < Nat.card C := by
  classical
  letI : Module (ZMod 2) V :=
    AddCommGroup.zmodModule (n := 2) (fun v => by rw [two_nsmul]; exact h2 v)
  haveI : Module.Finite (ZMod 2) V := (Module.finite_iff_finite (R := ZMod 2)).mpr inferInstance
  -- `dim_{𝔽₂} V = 2m`, in particular `V` is nontrivial
  have hdim : Module.finrank (ZMod 2) V = 2 * m := by
    letI : Fintype V := Fintype.ofFinite V
    have hc := hcard
    have h1 : Fintype.card V = 2 ^ Module.finrank (ZMod 2) V := by
      rw [Module.card_eq_pow_finrank (K := ZMod 2), ZMod.card]
    rw [Nat.card_eq_fintype_card, h1] at hc
    exact Nat.pow_right_injective (le_refl 2) hc
  haveI hVnt : Nontrivial V := Module.nontrivial_of_finrank_pos (R := ZMod 2) (by rw [hdim]; omega)
  -- the operator `T_V = (T • ·)`
  let TV : Module.End (ZMod 2) V :=
    { toFun := fun v => T • v
      map_add' := fun x y => smul_add T x y
      map_smul' := fun c v => map_nsmul (DistribSMul.toAddMonoidHom V T) c.val v }
  have hTVapp : ∀ v, TV v = T • v := fun _ => rfl
  have hfin : IsOfFinOrder T :=
    isOfFinOrder_iff_pow_eq_one.mpr ⟨orderOf T, orderOf_pos T, pow_orderOf_eq_one T⟩
  have hnatpow : ∀ g : C, ∃ k : ℕ, T ^ k = g := fun g =>
    (Submonoid.mem_powers_iff g T).mp (hfin.mem_powers_iff_mem_zpowers.mpr (hcyc g))
  have hTVpowapp : ∀ (k : ℕ) (v : V), (TV ^ k) v = T ^ k • v := by
    intro k
    induction k with
    | zero => intro v; simp
    | succ k ih => intro v; rw [pow_succ, Module.End.mul_apply, hTVapp, ih, pow_succ, mul_smul]
  have hTVpow : ∀ k : ℕ, TV ^ k = 1 ↔ T ^ k = 1 := by
    intro k
    constructor
    · intro h
      refine hfaith _ fun v => ?_
      simpa [hTVpowapp] using DFunLike.congr_fun h v
    · intro h
      ext v
      rw [Module.End.one_apply, hTVpowapp, h, one_smul]
  -- irreducibility: a `TV`-invariant subspace is `C`-stable
  have hirr : ∀ W : Submodule (ZMod 2) V, W ≠ ⊥ → W ≠ ⊤ → ∃ v ∈ W, TV v ∉ W := by
    intro W hWb hWt
    by_contra hcon
    simp only [not_exists, not_and, not_not] at hcon
    have hpow : ∀ (k : ℕ) (w : V), w ∈ W → T ^ k • w ∈ W := by
      intro k
      induction k with
      | zero => intro w hw; simpa using hw
      | succ k ih =>
        intro w hw
        rw [pow_succ, mul_smul]
        exact ih (T • w) (hcon w hw)
    have hstab : ∀ (h : C), ∀ w ∈ W.toAddSubgroup, h • w ∈ W.toAddSubgroup := by
      intro h w hw
      obtain ⟨k, rfl⟩ := hnatpow h
      exact hpow k w hw
    rcases hsimple W.toAddSubgroup hstab with hb | ht
    · exact hWb (Submodule.toAddSubgroup_injective (hb.trans Submodule.bot_toAddSubgroup.symm))
    · exact hWt (Submodule.toAddSubgroup_injective (ht.trans Submodule.top_toAddSubgroup.symm))
  have hcardC : Nat.card C = orderOf T := by
    rw [← Nat.card_zpowers T]
    exact Nat.card_congr (Equiv.subtypeUnivEquiv hcyc).symm
  have hordsub : orderOf T ∣ 2 ^ (2 * m) - 1 :=
    orderOf_dvd_of_pow_eq_one ((hTVpow _).mp
      (GaussSigns.irreducible_operator_pow_card_sub_one m hdim TV inferInstance hirr))
  have hordnot : ¬ orderOf T ∣ 2 ^ m - 1 := by
    intro hd
    have hTk : T ^ (2 ^ m - 1) = 1 := orderOf_dvd_iff_pow_eq_one.mp hd
    rw [← hTVpow] at hTk
    exact GaussSigns.irreducible_operator_pow_ne_one m hm hdim TV hirr hTk
  exact ⟨by rw [hcardC]; exact hordsub, by rw [hcardC]; exact hordnot,
    by rw [hcardC]; exact two_lt_of_dvd_sub_one hm hordsub hordnot⟩

omit [Finite C] [Finite V] in
/-- **Some `C`-orbit is nontrivial**: for a simple `V` of cardinality `2^{2m}` with `m ≥ 1`, the
`C`-action moves some vector.  Otherwise the action is trivial, so `⟨v⟩ = ⊤` for any `v ≠ 0` by
simplicity forces `#V = 2`, contradicting `#V = 2^{2m} ≥ 4`.  (Clone of the private
`GQ2.UnramifiedModel.exists_smul_ne`; ambient-free.) -/
theorem exists_smul_neK
    (hsimple : ∀ W : AddSubgroup V, (∀ (h : C), ∀ w ∈ W, h • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (hV : ∃ v : V, v ≠ 0) (hV2 : ∀ v : V, v + v = 0)
    (m : ℕ) (hm : 1 ≤ m) (hcard : Nat.card V = 2 ^ (2 * m)) :
    ∃ (h₀ : C) (v : V), h₀ • v ≠ v := by
  by_contra! hcon
  obtain ⟨v, hv⟩ := hV
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  have hord : addOrderOf v = 2 := addOrderOf_eq_prime (by rw [two_nsmul]; exact hV2 v) hv
  have htop : AddSubgroup.zmultiples v = ⊤ := by
    refine (hsimple _ (fun h w hw => by rw [hcon]; exact hw)).resolve_left (fun h0 => hv ?_)
    have hmem : v ∈ AddSubgroup.zmultiples v := AddSubgroup.mem_zmultiples v
    rw [h0, AddSubgroup.mem_bot] at hmem; exact hmem
  have hcard2 : Nat.card V = 2 := by
    have h1 : Nat.card ↥(AddSubgroup.zmultiples v) = 2 := by rw [Nat.card_zmultiples, hord]
    rwa [htop, Nat.card_congr AddSubgroup.topEquiv.toEquiv] at h1
  rw [hcard] at hcard2
  have h4 : (4 : ℕ) ≤ 2 ^ (2 * m) :=
    calc (4 : ℕ) = 2 ^ 2 := by norm_num
      _ ≤ 2 ^ (2 * m) := Nat.pow_le_pow_right (by norm_num) (by omega)
  omega

end Arithmetic

/-! ## §5 The Euler collapse at a general ambient group

`#H¹(Γ, V) = (#V)^n`.  The `Γ`-generic form of the opening block of
`GQ2/DeepPart/MuTwoPolarDual.lean` (`card_H0_eq_one_of_surjective`,
`card_H2_eq_one_of_card_H0_eq_one`, `card_H1_eq_card_of_H0_H2_trivial`), with B7 replaced by
LG2a's `GQ2.Dyadic.localEulerCharacteristic_open`.  **This is the only place `n` enters the whole
unramified computation** (design memo §3, §4(c)). -/

section HZero

variable {Γ : Type} [Group Γ] [TopologicalSpace Γ] [IsTopologicalGroup Γ]
variable {M : Type} [AddCommGroup M] [DistribMulAction Γ M]

omit [TopologicalSpace Γ] [IsTopologicalGroup Γ] in
/-- `H⁰(Γ, M) = 0` (as `Nat.card = 1`) iff `M` has no nonzero `Γ`-fixed vector. -/
theorem card_H0_eq_one_iffK :
    Nat.card (H0 Γ M) = 1 ↔ ∀ m : M, (∀ g : Γ, g • m = m) → m = 0 := by
  rw [Nat.card_eq_one_iff_unique]
  constructor
  · rintro ⟨hsub, _⟩ m hm
    exact Subtype.ext_iff.mp (Subsingleton.elim (⟨m, hm⟩ : H0 Γ M) ⟨0, smul_zero⟩)
  · intro h
    refine ⟨⟨fun a b => Subtype.ext ?_⟩, ⟨0, smul_zero⟩⟩
    rw [h a.1 a.2, h b.1 b.2]

omit [TopologicalSpace Γ] [IsTopologicalGroup Γ] in
/-- **`H⁰`-vanishing**: if the `Γ`-action on `M` factors through a *surjective* `ρ : Γ →* C`, the
`C`-module `M` is simple, and some element of `C` moves some vector, then `#H⁰ = 1`. -/
theorem card_H0_eq_one_of_surjectiveK {C : Type*} [Group C] [DistribMulAction C M]
    (ρ : Γ →* C) (hρsurj : Function.Surjective ρ)
    (hρ : ∀ (g : Γ) (m : M), g • m = ρ g • m)
    (hsimple : ∀ W : AddSubgroup M, (∀ (h : C), ∀ w ∈ W, h • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (h₀ : C) (hmoves : ∃ m : M, h₀ • m ≠ m) :
    Nat.card (H0 Γ M) = 1 := by
  rw [card_H0_eq_one_iffK]
  intro m hm
  set W : AddSubgroup M :=
    { carrier := {x : M | ∀ h : C, h • x = x}
      zero_mem' := fun h => smul_zero h
      add_mem' := fun ha hb h => by rw [smul_add, ha h, hb h]
      neg_mem' := fun ha h => by rw [smul_neg, ha h] } with hWdef
  have hWmem : ∀ x : M, x ∈ W ↔ ∀ h : C, h • x = x := fun x => Iff.rfl
  have hstable : ∀ (h : C), ∀ w ∈ W, h • w ∈ W := by
    intro h w hw
    have hw' := (hWmem w).mp hw
    rw [hw' h]
    exact hw
  rcases hsimple W hstable with hbot | htop
  · have hmW : m ∈ W := by
      rw [hWmem]
      intro h
      obtain ⟨g, rfl⟩ := hρsurj h
      rw [← hρ g m]
      exact hm g
    rw [hbot, AddSubgroup.mem_bot] at hmW
    exact hmW
  · exfalso
    obtain ⟨m₀, hm₀⟩ := hmoves
    have hin : m₀ ∈ W := htop ▸ AddSubgroup.mem_top m₀
    exact hm₀ ((hWmem m₀).mp hin h₀)

omit [TopologicalSpace Γ] [IsTopologicalGroup Γ] in
/-- **Fixed-point transport**: an equivariant additive iso induces a cardinality equality of
`H⁰`s. -/
theorem card_H0_congrK {A B : Type*} [AddCommGroup A] [AddCommGroup B]
    [DistribMulAction Γ A] [DistribMulAction Γ B]
    (e : A ≃+ B) (he : ∀ (g : Γ) (a : A), e (g • a) = g • e a) :
    Nat.card (H0 Γ B) = Nat.card (H0 Γ A) := by
  have hesymm : ∀ (g : Γ) (b : B), e.symm (g • b) = g • e.symm b := by
    intro g b
    apply e.injective
    rw [he, e.apply_symm_apply, e.apply_symm_apply]
  refine Nat.card_congr ⟨fun y => ⟨e.symm y.1, fun g => ?_⟩,
    fun x => ⟨e x.1, fun g => ?_⟩, fun y => ?_, fun x => ?_⟩
  · rw [← hesymm g y.1, y.2 g]
  · rw [← he g x.1, x.2 g]
  · exact Subtype.ext (e.apply_symm_apply y.1)
  · exact Subtype.ext (e.symm_apply_apply x.1)

end HZero

section HTwo

variable {Γ : Type} [Group Γ] [TopologicalSpace Γ] [IsTopologicalGroup Γ]
  [DistribMulAction Γ (MuN 2)] [ContinuousSMul Γ (MuN 2)]
variable (V : Type) [AddCommGroup V] [TopologicalSpace V] [DiscreteTopology V]
  [DistribMulAction Γ V] [ContinuousSMul Γ V] [Finite V]

omit [TopologicalSpace Γ] [IsTopologicalGroup Γ] [ContinuousSMul Γ (MuN 2)]
  [TopologicalSpace V] [DiscreteTopology V] [ContinuousSMul Γ V] in
/-- **Polar self-duality at a general `Γ`**: a nonsingular `Γ`-invariant quadratic form on a
finite exponent-2 module gives an equivariant additive iso `V ≃+ Hom(V, μ₂)`.  (`μ₂` carries the
trivial `Γ`-action by `GQ2.Dyadic.smul_muTwo` — the ℚ₂ model's `rfl`-lemma
`GQ2.DeepPart.muTwo_smul_trivial` is `G_ℚ₂`-typed; LG2's smul trap.) -/
theorem exists_polarSelfDualK (q : V → ZMod 2) (hq : IsQuadraticFp2 q)
    (hns : Nonsingular q) (h2 : ∀ v : V, v + v = 0)
    (hqG : ∀ (g : Γ) (v : V), q (g • v) = q v) :
    ∃ e : V ≃+ MuDual 2 V, ∀ (g : Γ) (v : V), e (g • v) = g • e v := by
  classical
  set ε := DeepPart.zmodTwoEquivMuTwo with hε
  set Ψ : V →+ MuDual 2 V :=
    { toFun := fun v => (ε.toAddMonoidHom.comp (polarHom q hq v) : MuDual 2 V)
      map_zero' := by
        refine DFunLike.ext _ _ fun m => ?_
        show ε (polar q m 0) = (0 : MuDual 2 V) m
        rw [MuDual.zero_apply]
        have hpz : polar q m 0 = 0 := by
          unfold GQ2.QuadraticFp2.polar
          rw [add_zero, hq.map_zero, add_zero]
          exact CharTwo.add_self_eq_zero _
        rw [hpz, map_zero]
      map_add' := fun v w => by
        refine DFunLike.ext _ _ fun m => ?_
        show ε (polar q m (v + w)) = ε (polar q m v) + ε (polar q m w)
        rw [hq.polar_add_right, map_add] } with hΨ
  have hΨapply : ∀ (v m : V), Ψ v m = ε (polar q m v) := fun v m => rfl
  have hinj : Function.Injective Ψ := by
    rw [injective_iff_map_eq_zero]
    intro v hv
    by_contra hne
    obtain ⟨w, hw⟩ := hns v hne
    have h0 : ε (polar q w v) = 0 := by
      have := DFunLike.congr_fun hv w
      rwa [MuDual.zero_apply] at this
    have hp0 : polar q w v = 0 := ε.injective (by rw [h0, map_zero])
    exact hw (polar_comm q w v ▸ hp0)
  have hcards : Nat.card (MuDual 2 V) = Nat.card V := by
    have h1 : Nat.card (MuDual 2 V) = Nat.card (V →+ ZMod 2) := by
      refine Nat.card_congr ⟨fun f => ε.symm.toAddMonoidHom.comp (f : V →+ MuN 2),
        fun f => (ε.toAddMonoidHom.comp f : MuDual 2 V), fun f => ?_, fun f => ?_⟩
      · refine DFunLike.ext _ _ fun m => ?_
        show ε (ε.symm ((f : V →+ MuN 2) m)) = f m
        rw [ε.apply_symm_apply]
      · ext m
        show ε.symm (ε (f m)) = f m
        rw [ε.symm_apply_apply]
    rw [h1, card_addHom_zmod2 V h2]
  haveI : Fintype V := Fintype.ofFinite V
  haveI : Fintype (MuDual 2 V) := Fintype.ofFinite _
  have hbij : Function.Bijective Ψ := by
    rw [Fintype.bijective_iff_injective_and_card]
    refine ⟨hinj, ?_⟩
    rw [← Nat.card_eq_fintype_card, ← Nat.card_eq_fintype_card, hcards]
  refine ⟨AddEquiv.ofBijective Ψ hbij, fun g v => ?_⟩
  show Ψ (g • v) = g • Ψ v
  refine DFunLike.ext _ _ fun m => ?_
  rw [muDual_smul_apply, smul_muTwo, hΨapply, hΨapply]
  congr 1
  have hps := polar_smul_smul (Γ := Γ) q hqG g (g⁻¹ • m) v
  rw [smul_inv_smul] at hps
  exact hps

omit [IsTopologicalGroup Γ] [DistribMulAction Γ (MuN 2)] [ContinuousSMul Γ (MuN 2)]
  [ContinuousSMul Γ V] [Finite V] in
/-- `H²` of an exponent-2 module has exponent 2. -/
theorem h2_add_selfK (h2 : ∀ v : V, v + v = 0) (x : H2 Γ V) : x + x = 0 := by
  induction x using QuotientAddGroup.induction_on with
  | H z =>
    have hz : z + z = 0 := by
      apply Subtype.ext
      funext p
      exact h2 _
    show H2mk Γ V z + H2mk Γ V z = 0
    rw [← map_add, hz, map_zero]

/-- **`#H² = 1` from `#H⁰ = 1`** at a general `Γ` (the bundle's `(0,2)` clause through the polar
self-duality and exponent-2 Pontryagin duality). -/
theorem card_H2_eq_one_of_card_H0_eq_oneK (D : TateDualityG Γ 2)
    (q : V → ZMod 2) (hq : IsQuadraticFp2 q) (hns : Nonsingular q)
    (h2 : ∀ v : V, v + v = 0) (hqG : ∀ (g : Γ) (v : V), q (g • v) = q v)
    (hfin : Finite (H2 Γ V)) (hH0 : Nat.card (H0 Γ V) = 1) :
    Nat.card (H2 Γ V) = 1 := by
  have htor : ∀ x : V, (2 : ℕ) • x = 0 := fun x => (two_nsmul x).trans (h2 x)
  obtain ⟨e, he⟩ := exists_polarSelfDualK V q hq hns h2 hqG
  have hd : Nat.card (H0 Γ (MuDual 2 V)) = Nat.card (H0 Γ V) := card_H0_congrK e he
  have hdual : Nat.card (H0 Γ (MuDual 2 V)) = Nat.card (H2 Γ V →+ ZMod 2) :=
    Nat.card_congr (Equiv.ofBijective _ (D.perfect02 V htor))
  haveI := hfin
  have hhom := card_addHom_zmod2 (H2 Γ V) (h2_add_selfK V h2)
  calc Nat.card (H2 Γ V)
      = Nat.card (H2 Γ V →+ ZMod 2) := hhom.symm
    _ = Nat.card (H0 Γ (MuDual 2 V)) := hdual.symm
    _ = Nat.card (H0 Γ V) := hd
    _ = 1 := hH0

end HTwo

section EulerCollapse

/-- **The Euler collapse over `K`**: `#H¹(G_K, V) = (#V)^n = 2^{2mn}` for `#V = 2^{2m}` and
`n = [G_ℚ₂ : G_K]`, from LG2a's Euler characteristic
(`GQ2.Dyadic.localEulerCharacteristic_open`) with trivial `H⁰` and `H²`.

This is the single point at which the degree `n` enters the unramified computation. -/
theorem card_H1_eq_two_pow_of_euler (U : Subgroup AbsGalQ2) (hU : IsOpen (U : Set AbsGalQ2))
    [Finite (AbsGalQ2 ⧸ U)] (V : Type) [AddCommGroup V] [TopologicalSpace V]
    [DiscreteTopology V] [DistribMulAction ↥U V] [ContinuousSMul ↥U V] [Finite V]
    (hH0 : Nat.card (H0 ↥U V) = 1) (hH2 : Nat.card (H2 ↥U V) = 1)
    (m n : ℕ) (hn : U.index = n) (hcard : Nat.card V = 2 ^ (2 * m)) :
    Nat.card (H1 ↥U V) = 2 ^ (2 * (m * n)) := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  obtain ⟨-, -, -, heuler⟩ := localEulerCharacteristic_open U hU V
  rw [heuler, hH0, hH2, one_mul, one_mul, hcard, padicValNat.prime_pow, hn]
  congr 1
  ring

end EulerCollapse

/-! ## §6 `C`-invariance of `Q⁰` on `H¹`

Lemma 6.14 naturality along the coefficient map `i := (g₀ • ·)` plus the explicit datum
coboundary; the `Γ`-generic form of `GQ2.RepIndependence.lemma_6_14` and
`GQ2.UnramifiedModel.{graphPullback_comap_smul_sub_mem_B2, Q0loc_smul_eq}`. -/

section Invariance

variable {Γ : Type} [Group Γ] [TopologicalSpace Γ] [IsTopologicalGroup Γ]
  [DistribMulAction Γ (ZMod 2)] [ContinuousSMul Γ (ZMod 2)]
  [DistribMulAction Γ (MuN 2)] [ContinuousSMul Γ (MuN 2)]
variable {C : Type} [Group C] [TopologicalSpace C] [DiscreteTopology C] [Finite C]
variable {V : Type} [AddCommGroup V] [TopologicalSpace V] [DiscreteTopology V] [Finite V]
  [DistribMulAction Γ V] [ContinuousSMul Γ V] [DistribMulAction C V]
variable {W : Type} [AddCommGroup W] [TopologicalSpace W] [DiscreteTopology W] [Finite W]
  [DistribMulAction Γ W] [ContinuousSMul Γ W] [DistribMulAction C W]

omit [Finite V] [Finite C] [Finite W] in
/-- **Lemma 6.14 (regular-module realization), eq. (102), at a general `Γ`.** -/
theorem lemma_6_14K (D : TateDualityG Γ 2)
    (datW : FactorSet C W) (ρ : ContinuousMonoidHom Γ C)
    (i : V →+ W) (hic : Continuous i) (hicompat : ∀ (g : Γ) (v : V), i (g • v) = g • i v)
    {q : W → ZMod 2} (hdatW : IsEquivariantFactorSet q datW)
    (hiC : ∀ (c : C) (v : V), i (c • v) = c • i v)
    (hρW : ∀ (g : Γ) (w : W), g • w = ρ g • w)
    (x : H1 Γ V) :
    Q0loc D (datW.comap i) ρ x = Q0loc D datW ρ (mapCoeff1 i hic hicompat x) := by
  show iotaF D (H2ofFun Γ (graphPullback (datW.comap i) ρ (Quotient.out x).1))
      = iotaF D (H2ofFun Γ (graphPullback datW ρ
          (Quotient.out (mapCoeff1 i hic hicompat x)).1))
  refine congrArg (iotaF D) ?_
  set b₁ : Z1 Γ W :=
    Z1comap (ContinuousMonoidHom.id Γ) i hic (fun g n => hicompat g n) (Quotient.out x)
    with hb1def
  set b₂ : Z1 Γ W := Quotient.out (mapCoeff1 i hic hicompat x) with hb2def
  have hb1val : b₁.1 = fun g => i ((Quotient.out x).1 g) := rfl
  have hStepA : graphPullback (datW.comap i) ρ (Quotient.out x).1 = graphPullback datW ρ b₁.1 := by
    rw [hb1val]
    funext p
    simp only [graphPullback, FactorSet.comap]
    rw [hiC]
  rw [hStepA]
  refine repIndep datW hdatW ρ hρW b₁ b₂ ?_
  have h1 : mapCoeff1 i hic hicompat (H1mk Γ V (Quotient.out x)) = H1mk Γ W b₁ := by
    rw [hb1def]; rfl
  rw [← h1, H1mk_out, hb2def, H1mk_out]

omit [IsTopologicalGroup Γ] [ContinuousSMul Γ (ZMod 2)]
  [DiscreteTopology C] [Finite C] [Finite V] [ContinuousSMul Γ V]
  [DistribMulAction Γ (MuN 2)] [ContinuousSMul Γ (MuN 2)] [AddCommGroup W] [TopologicalSpace W]
  [DiscreteTopology W] [Finite W] [DistribMulAction Γ W] [ContinuousSMul Γ W]
  [DistribMulAction C W] in
/-- **The explicit datum coboundary** at a general `Γ`: for `g₀ : C` (abelian `C`), the graph
pullback along the `g₀`-comapped datum differs from the original by the 2-coboundary of the
continuous 1-cochain `γ ↦ m_{g₀}(b γ)`.  (`GQ2.absGal_smul_zmodTwo` is replaced by
`GQ2.Dyadic.smul_zmodTwo` — the LG2 smul trap.) -/
theorem graphPullback_comap_smul_sub_mem_B2K {q : V → ZMod 2} (dat : FactorSet C V)
    (hdat : IsEquivariantFactorSet q dat) (hCcomm : ∀ a b : C, a * b = b * a)
    (ρ : ContinuousMonoidHom Γ C) (hρ : ∀ (γ : Γ) (v : V), γ • v = ρ γ • v)
    (g₀ : C) (b : Z1 Γ V) :
    graphPullback (dat.comap (DistribSMul.toAddMonoidHom V g₀)) ρ b.1
      - graphPullback dat ρ b.1 ∈ B2 Γ (ZMod 2) := by
  obtain ⟨hbc, hb⟩ := mem_Z1_iff.mp b.2
  refine (AddSubgroup.mem_map).mpr ⟨fun γ => dat.m g₀ (b.1 γ), ?_, ?_⟩
  · exact mem_C1_iff.mpr ((continuous_of_discreteTopology (f := fun v : V => dat.m g₀ v)).comp hbc)
  · funext p
    obtain ⟨γ, γ'⟩ := p
    have hbg : b.1 (γ * γ') = b.1 γ + ρ γ • b.1 γ' := by rw [hb γ γ', hρ]
    have hgp1 : graphPullback (dat.comap (DistribSMul.toAddMonoidHom V g₀)) ρ b.1 (γ, γ')
        = dat.f (g₀ • b.1 γ) (g₀ • (ρ γ • b.1 γ')) + dat.m (ρ γ) (g₀ • b.1 γ') := rfl
    have hgp2 : graphPullback dat ρ b.1 (γ, γ')
        = dat.f (b.1 γ) (ρ γ • b.1 γ') + dat.m (ρ γ) (b.1 γ') := rfl
    have hA := hdat.m_quad g₀ (b.1 γ) (ρ γ • b.1 γ')
    have hB := hdat.m_mul (ρ γ) g₀ (b.1 γ')
    have hB' := hdat.m_mul g₀ (ρ γ) (b.1 γ')
    rw [hCcomm (ρ γ) g₀] at hB
    simp only [dOne, AddMonoidHom.coe_mk, ZeroHom.coe_mk, smul_zmodTwo, Pi.sub_apply,
      hgp1, hgp2, hbg]
    linear_combination (norm := (ring_nf; simp [CharTwo.two_eq_zero])) hA + hB + hB'

omit [Finite C] [Finite V] [AddCommGroup W] [TopologicalSpace W] [DiscreteTopology W] [Finite W]
  [DistribMulAction Γ W] [ContinuousSMul Γ W] [DistribMulAction C W] in
/-- **`Q⁰` is invariant under the coefficient action of `C` on `H¹`** at a general `Γ`: Lemma
6.14 naturality along `i := (g • ·)` plus the explicit datum coboundary. -/
theorem Q0loc_smul_eqK (D : TateDualityG Γ 2) (ρ : ContinuousMonoidHom Γ C)
    (hρ : ∀ (g : Γ) (v : V), g • v = ρ g • v) (hCcomm : ∀ a b : C, a * b = b * a)
    {q : V → ZMod 2} (dat : FactorSet C V) (hdat : IsEquivariantFactorSet q dat)
    (g : C) (x : H1 Γ V) :
    Q0loc D dat ρ (cCoeffK ρ hρ hCcomm g x) = Q0loc D dat ρ x := by
  have hicompat : ∀ (γ : Γ) (v : V),
      (DistribSMul.toAddMonoidHom V g) (γ • v) = γ • (DistribSMul.toAddMonoidHom V g) v := by
    intro γ v
    show g • (γ • v) = γ • (g • v)
    rw [hρ γ v, hρ γ (g • v), ← mul_smul, ← mul_smul, hCcomm]
  have hiC : ∀ (c : C) (v : V),
      (DistribSMul.toAddMonoidHom V g) (c • v) = c • (DistribSMul.toAddMonoidHom V g) v := by
    intro c v
    show g • (c • v) = c • (g • v)
    rw [← mul_smul, ← mul_smul, hCcomm]
  have h614 := lemma_6_14K D dat ρ (DistribSMul.toAddMonoidHom V g) continuous_of_discreteTopology
    hicompat hdat hiC hρ x
  have hB2 := graphPullback_comap_smul_sub_mem_B2K dat hdat hCcomm ρ hρ g (Quotient.out x)
  have hQeq : Q0loc D (dat.comap (DistribSMul.toAddMonoidHom V g)) ρ x = Q0loc D dat ρ x :=
    congrArg (iotaF D) (h2ofFun_eq_of_sub_mem_B2 hB2)
  have hsm : cCoeffK ρ hρ hCcomm g x
      = mapCoeff1 (DistribSMul.toAddMonoidHom V g) continuous_of_discreteTopology hicompat x := rfl
  rw [hsm, ← h614, hQeq]

end Invariance

/-! ## §7 The unramified Gauss sign `(−1)^n · 2^{n·dim V/2}`

Packet Prop. 6.8 / eq. (115).  `arf_Q0loc_unramified_K` is the engine-shaped statement (cyclic
generator `T` supplied directly); the two parity corollaries are marking-shaped, mirroring the
ℚ₂ `GQ2.UnramifiedModel.prop_6_18_unramified`.  `prop_6_18_unramified_K` packages both together
with the Euler discharge over `G_K = ↥U`, and is the LG5 entry point. -/

section Unramified

variable {Γ : Type} [Group Γ] [TopologicalSpace Γ] [IsTopologicalGroup Γ]
  [DistribMulAction Γ (ZMod 2)] [ContinuousSMul Γ (ZMod 2)]
  [DistribMulAction Γ (MuN 2)] [ContinuousSMul Γ (MuN 2)]
variable {C : Type} [Group C] [TopologicalSpace C] [DiscreteTopology C] [Finite C]
variable {V : Type} [AddCommGroup V] [TopologicalSpace V] [DiscreteTopology V] [Finite V]
  [DistribMulAction Γ V] [ContinuousSMul Γ V] [DistribMulAction C V]

/-- **The unramified Arf value at a general base**: `arf (Q⁰_{Γ,V}) = n (mod 2)`, where
`#H¹(Γ, V) = 2^{2mn}` and `#V = 2^{2m}`.

The general Arf-parity engine `GQ2.GaussSigns.arf_eq_of_free` at `m' := m`, `s := n`, `U := C`.
Its six inputs: the cardinality `hEuler` (the only `n`-dependence — LG2a's Euler
characteristic), the three arithmetic facts about `#C` (`card_dvd_of_cyclic_simple`, `V`-side),
`C`-invariance of `Q⁰` (`Q0loc_smul_eqK`), and freeness on `H¹ ∖ 0` (`cCoeffK_free`, by
field-linearity — this is what replaces the ℚ₂ Schur transfer, which is false at `n ≥ 2`). -/
theorem arf_Q0loc_unramified_K (D : TateDualityG Γ 2) (ρ : ContinuousMonoidHom Γ C)
    (hρ : ∀ (g : Γ) (v : V), g • v = ρ g • v)
    (T : C) (hcyc : ∀ x : C, x ∈ Subgroup.zpowers T)
    (hfaith : ∀ h : C, (∀ v : V, h • v = v) → h = 1)
    (hsimple : ∀ W : AddSubgroup V, (∀ (h : C), ∀ w ∈ W, h • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (q : V → ZMod 2) (hq : IsQuadraticFp2 q) (hns : Nonsingular q) (hinv : IsInvariant C q)
    (dat : FactorSet C V) (hdat : IsEquivariantFactorSet q dat)
    (m n : ℕ) (hm : 1 ≤ m) (hn : 1 ≤ n) (hcard : Nat.card V = 2 ^ (2 * m))
    (hEuler : Nat.card (H1 Γ V) = 2 ^ (2 * (m * n))) :
    arf (Q0loc D dat ρ (V := V)) = (n : ZMod 2) := by
  classical
  have hV2 : ∀ v : V, v + v = 0 := DeepPart.exp_two_of_simple_of_card hsimple m hm hcard
  have hqG : ∀ (g : Γ) (v : V), q (g • v) = q v := fun g v => by rw [hρ]; exact hinv _ v
  have hquad := isQuadraticFp2_Q0loc D q hq dat hdat ρ hρ hqG
  have hnons := nonsingular_Q0loc D q hq hns hV2 dat hdat ρ hρ hqG
  have hCcomm := comm_of_cyclic T hcyc
  haveI hVnt : Nontrivial V := by
    rw [← Finite.one_lt_card_iff_nontrivial, hcard]
    calc (1 : ℕ) < 2 ^ 2 := by norm_num
      _ ≤ 2 ^ (2 * m) := Nat.pow_le_pow_right (by norm_num) (by omega)
  haveI : Finite (H1 Γ V) := (Nat.card_ne_zero.mp (by rw [hEuler]; positivity)).2
  letI actH1 : DistribMulAction C (H1 Γ V) := cActionH1K ρ hρ hCcomm
  obtain ⟨hUsq, hUnot, hU2⟩ := card_dvd_of_cyclic_simple T hcyc hfaith hsimple hV2 m hm hcard
  exact GaussSigns.arf_eq_of_free (Q0loc D dat ρ (V := V)) hquad hnons m n hm hn hEuler
    (U := C) hUsq hUnot hU2 (fun u => smul_zero u)
    (fun u x => Q0loc_smul_eqK D ρ hρ hCcomm dat hdat u x)
    (fun u x hx hux => cCoeffK_free ρ hρ hCcomm T hcyc hfaith hsimple hVnt u x hx hux)

/-- **Packet Prop. 6.8, even degree**: `#(Q⁰)⁻¹(0) = 2^{2mn−1} + 2^{mn−1}` — Gauss sign `+`. -/
theorem prop_6_18_unramified_K_even {qK : ℕ} (D : TateDualityG Γ 2)
    (c : ContinuousMonoidHom (Tq qK) C) (hc : Function.Surjective ⇑c)
    (ρ : ContinuousMonoidHom Γ C) (hρ : ∀ (g : Γ) (v : V), g • v = ρ g • v)
    (hfaith : ∀ h : C, (∀ v : V, h • v = v) → h = 1)
    (hsimple : ∀ W : AddSubgroup V, (∀ (h : C), ∀ w ∈ W, h • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (hunram : ∀ v : V, c (tqTau qK) • v = v)
    (q : V → ZMod 2) (hq : IsQuadraticFp2 q) (hns : Nonsingular q) (hinv : IsInvariant C q)
    (dat : FactorSet C V) (hdat : IsEquivariantFactorSet q dat)
    (m n : ℕ) (hm : 1 ≤ m) (hn : 1 ≤ n) (hcard : Nat.card V = 2 ^ (2 * m))
    (hEuler : Nat.card (H1 Γ V) = 2 ^ (2 * (m * n))) (hpar : Even n) :
    Nat.card {x : H1 Γ V // Q0loc D dat ρ x = 0}
      = 2 ^ (2 * m * n - 1) + 2 ^ (m * n - 1) := by
  classical
  have hV2 : ∀ v : V, v + v = 0 := DeepPart.exp_two_of_simple_of_card hsimple m hm hcard
  have hqG : ∀ (g : Γ) (v : V), q (g • v) = q v := fun g v => by rw [hρ]; exact hinv _ v
  have hquad := isQuadraticFp2_Q0loc D q hq dat hdat ρ hρ hqG
  have hnons := nonsingular_Q0loc D q hq hns hV2 dat hdat ρ hρ hqG
  haveI : Finite (H1 Γ V) := (Nat.card_ne_zero.mp (by rw [hEuler]; positivity)).2
  haveI : Fintype (H1 Γ V) := Fintype.ofFinite _
  have hval : (n : ZMod 2) = 0 := by
    obtain ⟨j, rfl⟩ := hpar
    rw [Nat.cast_add, CharTwo.add_self_eq_zero]
  have harf : arf (Q0loc D dat ρ (V := V)) = 0 := by
    rw [arf_Q0loc_unramified_K D ρ hρ (c (tqSigma qK)) (c_cyclic_q c hc hfaith hunram) hfaith
      hsimple q hq hns hinv dat hdat m n hm hn hcard hEuler, hval]
  have hmn : 1 ≤ m * n := Nat.one_le_iff_ne_zero.mpr (Nat.mul_ne_zero (by omega) (by omega))
  have hcnt := zeroCount_of_arf_zero (Q0loc D dat ρ (V := V)) hquad hnons hmn
    (by rw [← Nat.card_eq_fintype_card]; exact hEuler) harf
  rw [show 2 * m * n = 2 * (m * n) from mul_assoc 2 m n]
  simpa only [zeroCount] using hcnt

/-- **Packet Prop. 6.8, odd degree**: `#(Q⁰)⁻¹(0) = 2^{2mn−1} − 2^{mn−1}` — Gauss sign `−`.  At
`n = 1` this is the ℚ₂ statement `GQ2.UnramifiedModel.prop_6_18_unramified` (§8). -/
theorem prop_6_18_unramified_K_odd {qK : ℕ} (D : TateDualityG Γ 2)
    (c : ContinuousMonoidHom (Tq qK) C) (hc : Function.Surjective ⇑c)
    (ρ : ContinuousMonoidHom Γ C) (hρ : ∀ (g : Γ) (v : V), g • v = ρ g • v)
    (hfaith : ∀ h : C, (∀ v : V, h • v = v) → h = 1)
    (hsimple : ∀ W : AddSubgroup V, (∀ (h : C), ∀ w ∈ W, h • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (hunram : ∀ v : V, c (tqTau qK) • v = v)
    (q : V → ZMod 2) (hq : IsQuadraticFp2 q) (hns : Nonsingular q) (hinv : IsInvariant C q)
    (dat : FactorSet C V) (hdat : IsEquivariantFactorSet q dat)
    (m n : ℕ) (hm : 1 ≤ m) (hn : 1 ≤ n) (hcard : Nat.card V = 2 ^ (2 * m))
    (hEuler : Nat.card (H1 Γ V) = 2 ^ (2 * (m * n))) (hpar : Odd n) :
    Nat.card {x : H1 Γ V // Q0loc D dat ρ x = 0}
      = 2 ^ (2 * m * n - 1) - 2 ^ (m * n - 1) := by
  classical
  have hV2 : ∀ v : V, v + v = 0 := DeepPart.exp_two_of_simple_of_card hsimple m hm hcard
  have hqG : ∀ (g : Γ) (v : V), q (g • v) = q v := fun g v => by rw [hρ]; exact hinv _ v
  have hquad := isQuadraticFp2_Q0loc D q hq dat hdat ρ hρ hqG
  have hnons := nonsingular_Q0loc D q hq hns hV2 dat hdat ρ hρ hqG
  haveI : Finite (H1 Γ V) := (Nat.card_ne_zero.mp (by rw [hEuler]; positivity)).2
  haveI : Fintype (H1 Γ V) := Fintype.ofFinite _
  have hval : (n : ZMod 2) = 1 := by
    obtain ⟨j, rfl⟩ := hpar
    push_cast [CharTwo.two_eq_zero]; ring
  have harf : arf (Q0loc D dat ρ (V := V)) = 1 := by
    rw [arf_Q0loc_unramified_K D ρ hρ (c (tqSigma qK)) (c_cyclic_q c hc hfaith hunram) hfaith
      hsimple q hq hns hinv dat hdat m n hm hn hcard hEuler, hval]
  have hmn : 1 ≤ m * n := Nat.one_le_iff_ne_zero.mpr (Nat.mul_ne_zero (by omega) (by omega))
  have hcnt := zeroCount_of_arf_one (Q0loc D dat ρ (V := V)) hquad hnons hmn
    (by rw [← Nat.card_eq_fintype_card]; exact hEuler) harf
  rw [show 2 * m * n = 2 * (m * n) from mul_assoc 2 m n]
  simpa only [zeroCount] using hcnt

end Unramified

/-! ### The packaged statement over `G_K = ↥U`

The Euler input is discharged here from LG2a (`localEulerCharacteristic_open`) plus the two
collapse clauses of §5; that discharge — and only it — consumes the AX3/AX4 field-side interface,
which is threaded as the three explicit binders `tameFK`, `htameFK`, `hfac` (board rule: no
census change until the AX flip; AX4 memo §0, LG3 row). -/

section Packaged

variable {C : Type} [Group C] [TopologicalSpace C] [DiscreteTopology C] [Finite C]

/-- **Packet Prop. 6.8 / eq. (115) over a finite extension `K/ℚ₂`** (the LG5 entry point).

For `G_K = ↥U` open of finite index `n = [K : ℚ₂]` in `G_ℚ₂`, an unramified marking
`c : T_{q_K} ↠ C` of a simple faithful `𝔽₂[C]`-module `V` with `#V = 2^{2m}`:

  `arf (Q⁰) = n mod 2`,   `#(Q⁰)⁻¹(0) = 2^{2mn−1} + (−1)^n 2^{mn−1}`,

i.e. the Gauss sign is `(−1)^n · 2^{n·dim V/2}`.  The numerical parameters come from F1's
`GQ2.Dyadic.FieldParameters` (`P.n`, `P.qK = 2^{P.f}`) — the campaign's single `n`. -/
theorem prop_6_18_unramified_K (P : FieldParameters) (U : Subgroup AbsGalQ2)
    (hU : IsOpen (U : Set AbsGalQ2)) [Finite (AbsGalQ2 ⧸ U)] (hindex : U.index = P.n)
    [DistribMulAction ↥U (ZMod 2)] [ContinuousSMul ↥U (ZMod 2)]
    [DistribMulAction ↥U (MuN 2)] [ContinuousSMul ↥U (MuN 2)]
    {V : Type} [AddCommGroup V] [TopologicalSpace V] [DiscreteTopology V] [Finite V]
    [DistribMulAction ↥U V] [ContinuousSMul ↥U V] [DistribMulAction C V]
    (D : TateDualityG ↥U 2)
    (tameFK : ContinuousMonoidHom ↥U (Tq P.qK)) (htameFK : Function.Surjective ⇑tameFK)
    (c : ContinuousMonoidHom (Tq P.qK) C) (hc : Function.Surjective ⇑c)
    (ρ : ContinuousMonoidHom ↥U C) (hfac : ∀ g, ρ g = c (tameFK g))
    (hρ : ∀ (g : ↥U) (v : V), g • v = ρ g • v)
    (hfaith : ∀ h : C, (∀ v : V, h • v = v) → h = 1)
    (hsimple : ∀ W : AddSubgroup V, (∀ (h : C), ∀ w ∈ W, h • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (hunram : ∀ v : V, c (tqTau P.qK) • v = v)
    (q : V → ZMod 2) (hq : IsQuadraticFp2 q) (hns : Nonsingular q) (hinv : IsInvariant C q)
    (dat : FactorSet C V) (hdat : IsEquivariantFactorSet q dat)
    (m : ℕ) (hm : 1 ≤ m) (hcard : Nat.card V = 2 ^ (2 * m)) :
    arf (Q0loc D dat ρ (V := V)) = (P.n : ZMod 2) ∧
      (Even P.n → Nat.card {x : H1 ↥U V // Q0loc D dat ρ x = 0}
        = 2 ^ (2 * m * P.n - 1) + 2 ^ (m * P.n - 1)) ∧
      (Odd P.n → Nat.card {x : H1 ↥U V // Q0loc D dat ρ x = 0}
        = 2 ^ (2 * m * P.n - 1) - 2 ^ (m * P.n - 1)) := by
  classical
  have hV2 : ∀ v : V, v + v = 0 := DeepPart.exp_two_of_simple_of_card hsimple m hm hcard
  have hqG : ∀ (g : ↥U) (v : V), q (g • v) = q v := fun g v => by rw [hρ]; exact hinv _ v
  haveI hVnt : Nontrivial V := by
    rw [← Finite.one_lt_card_iff_nontrivial, hcard]
    calc (1 : ℕ) < 2 ^ 2 := by norm_num
      _ ≤ 2 ^ (2 * m) := Nat.pow_le_pow_right (by norm_num) (by omega)
  have hρsurj : Function.Surjective ⇑ρ := by
    intro y
    obtain ⟨t, ht⟩ := hc y
    obtain ⟨g, hg⟩ := htameFK t
    exact ⟨g, by rw [hfac, hg, ht]⟩
  obtain ⟨h₀, hmoves⟩ := exists_smul_neK hsimple (exists_ne (0 : V)) hV2 m hm hcard
  have hH0 : Nat.card (H0 ↥U V) = 1 :=
    card_H0_eq_one_of_surjectiveK ρ.toMonoidHom hρsurj hρ hsimple h₀ hmoves
  have hH2 : Nat.card (H2 ↥U V) = 1 :=
    card_H2_eq_one_of_card_H0_eq_oneK V D q hq hns hV2 hqG
      (localEulerCharacteristic_open U hU V).2.2.1 hH0
  have hEuler : Nat.card (H1 ↥U V) = 2 ^ (2 * (m * P.n)) :=
    card_H1_eq_two_pow_of_euler U hU V hH0 hH2 m P.n hindex hcard
  refine ⟨arf_Q0loc_unramified_K D ρ hρ (c (tqSigma P.qK)) (c_cyclic_q c hc hfaith hunram)
      hfaith hsimple q hq hns hinv dat hdat m P.n hm P.one_le_n hcard hEuler,
    fun hpar => ?_, fun hpar => ?_⟩
  · exact prop_6_18_unramified_K_even D c hc ρ hρ hfaith hsimple hunram q hq hns hinv dat hdat
      m P.n hm P.one_le_n hcard hEuler hpar
  · exact prop_6_18_unramified_K_odd D c hc ρ hρ hfaith hsimple hunram q hq hns hinv dat hdat
      m P.n hm P.one_le_n hcard hEuler hpar

end Packaged

/-! ## §8 The `n = 1` regression

The general engine, run at `Γ := G_ℚ₂`, `q_K := 2`, `n := 1`, re-derives the ℚ₂ model statement
`GQ2.UnramifiedModel.prop_6_18_unramified` **verbatim** — same binders, same conclusion (the
`example` below is a kernel-level statement pin through `GQ2.Dyadic.Q0loc_absGalQ2`).  So the
packet's Hermitian route survives as the pinned special case of the parity route. -/

section Q2Regression

variable {C : Type} [Group C] [TopologicalSpace C] [DiscreteTopology C] [Finite C]
variable {V : Type} [AddCommGroup V] [TopologicalSpace V] [DiscreteTopology V] [Finite V]
  [DistribMulAction AbsGalQ2 V] [ContinuousSMul AbsGalQ2 V] [DistribMulAction C V]

/-- **The `n = 1` regression**: `GQ2.UnramifiedModel.prop_6_18_unramified` re-derived from the
general-`K` parity route (`prop_6_18_unramified_K_odd` at `q_K = 2`, `n = 1`, `Odd 1`), with the
Euler input supplied by the ℚ₂ collapse `GQ2.DeepPart.card_H1_eq_card_of_simple`.  Statement
identical to the model's (pinned below). -/
theorem prop_6_18_unramified_K_q2 (D : TateDuality 2) (B : BoundaryMaps)
    (c : ContinuousMonoidHom Ttame C)
    (hc : Function.Surjective ⇑c)
    (ρ : ContinuousMonoidHom AbsGalQ2 C) (hfac : ∀ g, ρ g = c (B.tameF g))
    (hρ : ∀ (g : AbsGalQ2) (v : V), g • v = ρ g • v)
    (hfaith : ∀ h : C, (∀ v : V, h • v = v) → h = 1)
    (hsimple : ∀ W : AddSubgroup V, (∀ (h : C), ∀ w ∈ W, h • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (hV : ∃ v : V, v ≠ 0)
    (hunram : ∀ v : V, c tameTau • v = v)
    (q : V → ZMod 2) (hq : IsQuadraticFp2 q) (hns : Nonsingular q) (hinv : IsInvariant C q)
    (dat : FactorSet C V) (hdat : IsEquivariantFactorSet q dat)
    (m : ℕ) (hm : 1 ≤ m) (hcard : Nat.card V = 2 ^ (2 * m)) :
    Nat.card {x : H1 AbsGalQ2 V // Q0loc D dat ρ x = 0}
      = 2 ^ (2 * m - 1) - 2 ^ (m - 1) := by
  classical
  have hV2 : ∀ v : V, v + v = 0 := DeepPart.exp_two_of_simple_of_card hsimple m hm hcard
  have hρsurj : Function.Surjective ⇑ρ := by
    intro y
    obtain ⟨t, ht⟩ := hc y
    obtain ⟨g, hg⟩ := B.tameF_surjective t
    exact ⟨g, by rw [hfac, hg, ht]⟩
  obtain ⟨h₀, hmoves⟩ := exists_smul_neK hsimple hV hV2 m hm hcard
  have hEuler : Nat.card (H1 AbsGalQ2 V) = 2 ^ (2 * (m * 1)) := by
    rw [DeepPart.card_H1_eq_card_of_simple V D ρ.toMonoidHom hρsurj hρ hsimple h₀ hmoves
      q hq hns hinv hV2, hcard, mul_one]
  have h := prop_6_18_unramified_K_odd (qK := 2) D c hc ρ hρ hfaith hsimple hunram
    q hq hns hinv dat hdat m 1 hm le_rfl hcard hEuler odd_one
  rwa [mul_one, mul_one] at h

/-- **Statement pin**: the regression theorem's type is *definitionally* the ℚ₂ model's
(`GQ2.Dyadic.Q0loc` at `Γ = G_ℚ₂` is `GQ2.SectionSix.Q0loc` on the nose — LG2's
`Q0loc_absGalQ2`).  If the general route ever drifted from the model statement, this line would
stop typechecking. -/
example : @prop_6_18_unramified_K_q2 = @GQ2.UnramifiedModel.prop_6_18_unramified := rfl

end Q2Regression

end GQ2.Dyadic
