/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-4.8 and Fable-5
-/
import GQ2.RadicalEdge.Bridge
import GQ2.FiniteGroupLemmas
import GQ2.Block.FrameImpl
import GQ2.SectionThreeMarked
import GQ2.KappaNormalForm
import GQ2.MStageCount
import GQ2.MStageCountGammaA
import Mathlib.GroupTheory.SchurZassenhaus

/-!
# The terminal-case infrastructure for Section 9

The odd-complement, fibre-product, correspondence, and source-independence layers.

See `GQ2.SectionNine` for the paper-facing overview, source citations, and deviations.
-/

namespace GQ2

open SectionEight QuadraticFp2

variable {H E : Type} [Group H] [TopologicalSpace H] [DiscreteTopology H] [Finite H]
  [CommGroup E] [TopologicalSpace E] [DiscreteTopology E] [Finite E]

namespace SectionNine

/-! ## Terminal-case group-theory foundation

The coprime-centralization mechanism behind Lemma 9.2's odd normal lift `Ñ ◁ Y`: an
odd-order subgroup acting on the scalar stack `L_Y` (a `Y`-central 2-group) centralizes it.
This is `GQ2.comm_bot_of_scalarChain` (the Lemma 7.2 proof) unpacked at the `IsScalarStack` datum. -/


/-- **Coprime centralization** (Lemma 9.2 mechanism, §9.1): an odd-order subgroup `N` acting
on a scalar stack `L` (a `Y`-central 2-group, `SectionSeven.IsScalarStack`) centralizes it —
`⁅N, L⁆ = ⊥`.  This is how the odd normal lift `Ñ` of Lemma 9.2 centralizes `L_Y` (its
uniqueness/normality then follow).  Proved from `comm_bot_of_scalarChain`; reusable by the
Lemma 9.2 structural subproof the §9 induction. -/
theorem scalarStack_centralized_of_coprime {Y : Type} [Group Y] [Finite Y]
    {L : Subgroup Y} (hstack : SectionSeven.IsScalarStack L) {N : Subgroup Y}
    (hcop : Nat.Coprime (Nat.card N) (Nat.card L)) : ⁅N, L⁆ = ⊥ := by
  obtain ⟨n, c, hc0, hcn, hmono, _, hcomm⟩ := hstack
  have h := comm_bot_of_scalarChain n N c hc0 hmono hcomm (by rw [hcn]; exact hcop)
  rwa [hcn] at h

/-! ## Tame 2-nilpotency

The gating foundation for Lemma 9.2: a finite quotient `H` of the tame group `Ttame`
(generated by `s, t` with `s⁻¹ t s = t²`) is 2-nilpotent — `O²(H)` has odd order.  `⟨t⟩` is
odd (`Tame.tame_odd_order`) and normal (`Tame.zpowers_normal_of_tame`), the quotient `H ⧸ ⟨t⟩`
is cyclic, and a finite group with an odd normal subgroup and cyclic quotient is 2-nilpotent
(the odd complement is the preimage of the odd part of the cyclic quotient).  This lets the §9 induction
build the odd normal lift `Ñ ◁ Y` via Schur–Zassenhaus (`oddOrder_twoQuotient_split`). -/

/-- A finite **cyclic** group `Q` has a normal subgroup `Q₀` of odd order (`= ⟨g^{2ᵃ}⟩`, the odd
part) such that the `2ᵃ`-power of every element lands in `Q₀` (i.e. `Q ⧸ Q₀` is a 2-group,
expressed membership-wise to avoid forming the quotient here). -/
theorem exists_normal_odd_pow_mem_of_cyclic {Q : Type*} [Group Q] [Finite Q]
    (hcyc : IsCyclic Q) :
    ∃ Q0 : Subgroup Q, Q0.Normal ∧ Odd (Nat.card Q0) ∧ ∀ x : Q, ∃ k : ℕ, x ^ 2 ^ k ∈ Q0 := by
  obtain ⟨g, hg⟩ := hcyc.exists_generator
  have hcomm : ∀ x y : Q, x * y = y * x := by
    intro x y
    obtain ⟨i, rfl⟩ := Subgroup.mem_zpowers_iff.mp (hg x)
    obtain ⟨j, rfl⟩ := Subgroup.mem_zpowers_iff.mp (hg y)
    exact (Commute.zpow_zpow (Commute.refl g) i j).eq
  have hgtop : Subgroup.zpowers g = ⊤ := by rw [eq_top_iff]; intro x _; exact hg x
  set n := Nat.card Q with hn
  have hnpos : 0 < n := Nat.card_pos
  have hord : orderOf g = n := by
    rw [← Nat.card_zpowers g, hgtop]; exact Nat.card_congr (Subgroup.topEquiv.toEquiv)
  set P2 := 2 ^ (n.factorization 2) with hP2
  have hP2pos : 0 < P2 := pow_pos (by norm_num) _
  have hsplit : P2 * (n / P2) = n := Nat.ordProj_mul_ordCompl_eq_self n 2
  have hdvd : P2 ∣ n := ⟨n / P2, hsplit.symm⟩
  have hbodd : ¬ 2 ∣ (n / P2) := Nat.not_dvd_ordCompl Nat.prime_two hnpos.ne'
  refine ⟨Subgroup.zpowers (g ^ P2), ?_, ?_, ?_⟩
  · refine ⟨fun w hw q => ?_⟩
    have hqw : q * w * q⁻¹ = w := by rw [hcomm q w]; group
    rw [hqw]; exact hw
  · rw [Nat.card_zpowers, orderOf_pow' g hP2pos.ne', hord, Nat.gcd_comm, Nat.gcd_eq_left hdvd]
    exact Nat.odd_iff.mpr (Nat.two_dvd_ne_zero.mp hbodd)
  · intro x
    refine ⟨n.factorization 2, ?_⟩
    obtain ⟨i, rfl⟩ := Subgroup.mem_zpowers_iff.mp (hg x)
    refine Subgroup.mem_zpowers_iff.mpr ⟨i, ?_⟩
    rw [← hP2, ← zpow_natCast (g ^ i) P2, ← zpow_natCast g P2, ← zpow_mul, ← zpow_mul, mul_comm]

/-- **2-nilpotency from a cyclic quotient.** A finite group `H` with a normal subgroup `C` of
odd order and *cyclic* quotient `H ⧸ C` has a normal subgroup `N` of odd order with 2-group
quotient (necessarily `N = O²(H)`): the preimage of the odd part of the cyclic `H ⧸ C`. -/
theorem exists_normal_odd_twoQuotient_of_cyclic_quotient {H : Type*} [Group H] [Finite H]
    (C : Subgroup H) [C.Normal] (hC : Odd (Nat.card C)) (hcyc : IsCyclic (H ⧸ C)) :
    ∃ N : Subgroup H, ∃ _ : N.Normal, Odd (Nat.card N) ∧ IsPGroup 2 (H ⧸ N) := by
  obtain ⟨Q0, hQ0norm, hQ0odd, hQ0pow⟩ := exists_normal_odd_pow_mem_of_cyclic hcyc
  set f : H →* H ⧸ C := QuotientGroup.mk' C with hf
  have hfsurj : Function.Surjective f := QuotientGroup.mk'_surjective C
  refine ⟨Q0.comap f, hQ0norm.comap f, ?_, ?_⟩
  · -- `Nat.card (comap f Q0) = card C * card Q0`, both odd, via index bookkeeping.
    have hidx : (Q0.comap f).index = Q0.index := Subgroup.index_comap_of_surjective Q0 hfsurj
    have hcardC : Nat.card C * C.index = Nat.card H := Subgroup.card_mul_index C
    have hCQ : C.index = Nat.card (H ⧸ C) := rfl
    have hcardN : Nat.card (Q0.comap f) * (Q0.comap f).index = Nat.card H :=
      Subgroup.card_mul_index _
    have hcardQ0 : Nat.card Q0 * Q0.index = Nat.card (H ⧸ C) := Subgroup.card_mul_index Q0
    have hNidx_pos : 0 < (Q0.comap f).index := Nat.pos_of_ne_zero Subgroup.index_ne_zero_of_finite
    have key : Nat.card (Q0.comap f) = Nat.card C * Nat.card Q0 := by
      apply Nat.eq_of_mul_eq_mul_right hNidx_pos
      rw [hcardN, hidx, mul_assoc, hcardQ0, ← hCQ, hcardC]
    rw [key]; exact hC.mul hQ0odd
  · -- `H ⧸ N` is a 2-group: every element's `2ᵏ`-power lifts into `Q0`.
    intro x
    obtain ⟨y, rfl⟩ := QuotientGroup.mk'_surjective (Q0.comap f) x
    obtain ⟨k, hk⟩ := hQ0pow (f y)
    refine ⟨k, ?_⟩
    rw [← map_pow, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff, Subgroup.mem_comap, map_pow]
    exact hk

/-- **Tame 2-nilpotency (Lemma 3.1 structural content).** A finite group generated by `s, t`
with the tame relation `s⁻¹ t s = t²` is 2-nilpotent: it has a normal subgroup `N` of odd order
with 2-group quotient (`N = O²(H)`).  `C = ⟨t⟩` is odd (`Tame.tame_odd_order`) and normal
(`Tame.zpowers_normal_of_tame`), and `H ⧸ C` is cyclic (generated by the image of `s`, since
`t ↦ 1`); apply `exists_normal_odd_twoQuotient_of_cyclic_quotient`.  This is the foundation
Lemma 9.2 rests on — the odd normal lift `Ñ` of the §9 induction lives over `O²(H)`. -/
theorem tame_two_nilpotent {H : Type*} [Group H] [Finite H] {s t : H}
    (hgen : Subgroup.closure {s, t} = ⊤) (h : s⁻¹ * t * s = t ^ 2) :
    ∃ N : Subgroup H, ∃ _ : N.Normal, Odd (Nat.card N) ∧ IsPGroup 2 (H ⧸ N) := by
  haveI hCnorm : (Subgroup.zpowers t).Normal := GQ2.Tame.zpowers_normal_of_tame hgen h
  have hCodd : Odd (Nat.card (Subgroup.zpowers t)) := by
    rw [Nat.card_zpowers]; exact GQ2.Tame.tame_odd_order (orderOf_pos s).ne' h
  have hcyc : IsCyclic (H ⧸ Subgroup.zpowers t) := by
    set φ := QuotientGroup.mk' (Subgroup.zpowers t) with hφ
    have hsup : Subgroup.zpowers t ⊔ Subgroup.zpowers s = ⊤ := by
      rw [eq_top_iff, ← hgen, Subgroup.closure_le]
      intro x hx
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
      rcases hx with rfl | rfl
      · exact SetLike.mem_coe.2 (Subgroup.mem_sup_right (Subgroup.mem_zpowers _))
      · exact SetLike.mem_coe.2 (Subgroup.mem_sup_left (Subgroup.mem_zpowers _))
    have htmk : φ t = 1 := by
      rw [hφ, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]; exact Subgroup.mem_zpowers t
    have htop : Subgroup.zpowers (φ s) = ⊤ := by
      have hm := congrArg (Subgroup.map φ) hsup
      rwa [Subgroup.map_sup, MonoidHom.map_zpowers, MonoidHom.map_zpowers, htmk,
        Subgroup.zpowers_one_eq_bot, bot_sup_eq,
        Subgroup.map_top_of_surjective _ (QuotientGroup.mk'_surjective _)] at hm
    exact ⟨⟨φ s, fun x => htop.ge (Subgroup.mem_top x)⟩⟩
  exact exists_normal_odd_twoQuotient_of_cyclic_quotient (Subgroup.zpowers t) hCodd hcyc

/-! ## Lemma 9.2 — the odd normal complement `Ñ ◁ Y`

For a terminal target `1 → L_Y → Y → H → 1` (`L_Y` a scalar-stack 2-group, `H` tame hence
2-nilpotent by `tame_two_nilpotent`), Schur–Zassenhaus inside `P = π_Y⁻¹(O²H)` produces an odd
complement `Ñ` to `L_Y`, which the scalar-stack centralization
(`scalarStack_centralized_of_coprime`)
forces to be *normal in `Y`* (`Ñ` = the odd-order elements of `P`).  The output bundle — `Ñ ◁ Y`
odd, `Y/Ñ` a 2-group, `Ñ ∩ L_Y = ⊥`, `π_Y(Ñ) = O²H`, `Ñ·L_Y = π_Y⁻¹(O²H)` — is exactly the data
the §9 induction feeds to `coprime_fiber_product` (Lemma 9.1) for `Y ≅ H ×_{H₂} (Y/Ñ)`. -/

/-- Odd divides odd. -/
private theorem odd_of_dvd {a b : ℕ} (hab : a ∣ b) (hb : Odd b) : Odd a := by
  rcases hab with ⟨c, rfl⟩; rw [Nat.odd_mul] at hb; exact hb.1

/-- Schur–Zassenhaus: the odd complement `Ñ` to `L` inside `P = π⁻¹(M)`, where `L = ker π` is a
2-group and `M ◁ H` is odd. -/
theorem sz_odd_complement {H Y : Type} [Group H] [Group Y] [Finite Y]
    (piY : Y →* H) (hpi : Function.Surjective piY)
    (L : Subgroup Y) (hkerL : piY.ker = L)
    (M : Subgroup H) [M.Normal]
    (hMcop : Nat.Coprime (Nat.card L) (Nat.card M)) :
    ∃ Ntil : Subgroup Y, Ntil ≤ M.comap piY ∧ Ntil ⊓ L = ⊥ ∧ Ntil ⊔ L = M.comap piY ∧
      Nat.card Ntil = Nat.card M := by
  haveI : Finite H := Finite.of_surjective piY hpi
  haveI hLn : L.Normal := hkerL ▸ piY.normal_ker
  set P := M.comap piY with hPdef
  have hLP : L ≤ P := by
    intro x hx
    rw [hPdef, Subgroup.mem_comap, ← hkerL, MonoidHom.mem_ker] at *
    rw [hx]; exact M.one_mem
  -- card P = card L * card M
  have hLindex : L.index = Nat.card H := by
    rw [Subgroup.index_eq_card, ← hkerL]
    exact Nat.card_congr (QuotientGroup.quotientKerEquivOfSurjective piY hpi).toEquiv
  have hPindex : P.index = M.index := Subgroup.index_comap_of_surjective M hpi
  have hcardY_L : Nat.card L * Nat.card H = Nat.card Y := by
    rw [← hLindex]; exact Subgroup.card_mul_index L
  have hcardH_M : Nat.card M * M.index = Nat.card H := Subgroup.card_mul_index M
  have hcardP : Nat.card P * M.index = Nat.card Y := by
    rw [← hPindex]; exact Subgroup.card_mul_index P
  have hMindex_pos : 0 < M.index := Nat.pos_of_ne_zero Subgroup.index_ne_zero_of_finite
  have hcardP_eq : Nat.card P = Nat.card L * Nat.card M := by
    apply Nat.eq_of_mul_eq_mul_right hMindex_pos
    rw [hcardP, mul_assoc, hcardH_M, hcardY_L]
  -- Work inside ↥P.
  haveI hNn : (L.subgroupOf P).Normal := hLn.subgroupOf P
  have hcardN : Nat.card (L.subgroupOf P) = Nat.card L :=
    Nat.card_congr (Subgroup.subgroupOfEquivOfLe hLP).toEquiv
  have hNidx : (L.subgroupOf P).index = Nat.card M := by
    have hmul := Subgroup.card_mul_index (L.subgroupOf P)
    rw [hcardN, hcardP_eq] at hmul
    exact Nat.eq_of_mul_eq_mul_left Nat.card_pos hmul
  have hcop : Nat.Coprime (Nat.card (L.subgroupOf P)) (L.subgroupOf P).index := by
    rw [hcardN, hNidx]; exact hMcop
  obtain ⟨K, hK⟩ := Subgroup.exists_right_complement'_of_coprime hcop
  set Ntil := K.map P.subtype with hNtil
  have hNleP : Ntil ≤ P := Subgroup.map_subtype_le K
  have hLeq : (L.subgroupOf P).map P.subtype = L := Subgroup.map_subgroupOf_eq_of_le hLP
  have hmaptop : Subgroup.map P.subtype ⊤ = P := by
    rw [← MonoidHom.range_eq_map]; exact P.range_subtype
  have hcardK : Nat.card K = Nat.card M := by
    have hcm := hK.card_mul
    rw [hcardN, hcardP_eq] at hcm
    exact Nat.eq_of_mul_eq_mul_left Nat.card_pos hcm
  refine ⟨Ntil, hNleP, ?_, ?_, ?_⟩
  · -- Ntil ⊓ L = ⊥
    rw [hNtil, ← hLeq, ← Subgroup.map_inf K (L.subgroupOf P) P.subtype P.subtype_injective,
      inf_comm, disjoint_iff.mp hK.disjoint, Subgroup.map_bot]
  · -- Ntil ⊔ L = P
    have hthis := congrArg (Subgroup.map P.subtype) hK.sup_eq_top
    rw [Subgroup.map_sup, hLeq, hmaptop] at hthis
    rw [hNtil, sup_comm]; exact hthis
  · -- card Ntil = card M
    rw [hNtil, ← Nat.card_congr
      (Subgroup.equivMapOfInjective K P.subtype P.subtype_injective).toEquiv, hcardK]

open scoped Pointwise commutatorElement in
/-- **Lemma 9.2 (structure).** For a marked target `1 → L → Y → H → 1` with `L = ker π` a
2-group *scalar stack* and `H` 2-nilpotent (`M = O²H` odd, `H/M` a 2-group), there is a unique
odd normal complement `Ñ ◁ Y` to `L` over `M`: `Ñ` is odd, `Y/Ñ` is a 2-group, `Ñ ∩ L = ⊥`,
`Ñ` centralizes `L`, `π(Ñ) = M`, and `Ñ · L = π⁻¹(M)`.  These are the fibre-product pieces
feeding `coprime_fiber_product` in the §9 induction. -/
theorem lemma_9_2_core {H Y : Type} [Group H] [Group Y] [Finite Y]
    (piY : Y →* H) (hpi : Function.Surjective piY)
    (L : Subgroup Y) (hkerL : piY.ker = L) (hL2 : IsPGroup 2 L)
    (hstack : SectionSeven.IsScalarStack L)
    (M : Subgroup H) [M.Normal] (hModd : Odd (Nat.card M)) (hMtwo : IsPGroup 2 (H ⧸ M)) :
    ∃ Ntil : Subgroup Y, ∃ _ : Ntil.Normal, Odd (Nat.card Ntil) ∧ IsPGroup 2 (Y ⧸ Ntil) ∧
      Ntil ⊓ L = ⊥ ∧ ⁅Ntil, L⁆ = ⊥ ∧ Ntil.map piY = M ∧ Ntil ⊔ L = M.comap piY := by
  haveI : Finite H := Finite.of_surjective piY hpi
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  haveI hLn : L.Normal := hkerL ▸ piY.normal_ker
  haveI hMcn : (M.comap piY).Normal := ‹M.Normal›.comap piY
  -- card L (a 2-power) is coprime to card M (odd)
  have hcop : Nat.Coprime (Nat.card L) (Nat.card M) := by
    obtain ⟨k, hk⟩ := hL2.exists_card_eq
    rw [hk]
    have hnd : ¬ (2 : ℕ) ∣ Nat.card M := by have := Nat.odd_iff.mp hModd; omega
    exact (Nat.prime_two.coprime_iff_not_dvd.mpr hnd).pow_left k
  obtain ⟨Ntil, hNleP, hNL_bot, hNL_sup, hcardNtil⟩ := sz_odd_complement piY hpi L hkerL M hcop
  -- `Ñ` centralizes `L` (odd group on a scalar stack)
  have hcentral : ⁅Ntil, L⁆ = ⊥ :=
    scalarStack_centralized_of_coprime hstack (by rw [hcardNtil]; exact hcop.symm)
  -- every element of `P = Ñ·L` factors as `ñ·ℓ`
  have hdecomp : ∀ p ∈ Ntil ⊔ L, ∃ ñ ∈ Ntil, ∃ ℓ ∈ L, ñ * ℓ = p := by
    intro p hp
    have hp' : p ∈ (Ntil : Set Y) * (L : Set Y) := by
      rw [← Subgroup.mul_normal Ntil L]; exact hp
    rw [Set.mem_mul] at hp'
    obtain ⟨ñ, hñ, ℓ, hℓ, hprod⟩ := hp'
    exact ⟨ñ, hñ, ℓ, hℓ, hprod⟩
  -- order in a subgroup equals order in `Y`
  have hoc : ∀ (S : Subgroup Y) (x : Y) (hx : x ∈ S), orderOf (⟨x, hx⟩ : S) = orderOf x :=
    fun S x hx => (orderOf_injective S.subtype Subtype.coe_injective ⟨x, hx⟩).symm
  -- the characterisation: `Ñ` = the odd-order elements of `P`
  have hkey : ∀ p : Y, p ∈ Ntil ⊔ L → Odd (orderOf p) → p ∈ Ntil := by
    intro p hpsup hpodd
    obtain ⟨ñ, hñ, ℓ, hℓ, hprod⟩ := hdecomp p hpsup
    have hcomm : Commute ñ ℓ := by
      have h1 : ⁅ñ, ℓ⁆ ∈ ⁅Ntil, L⁆ := Subgroup.commutator_mem_commutator hñ hℓ
      rw [hcentral, Subgroup.mem_bot] at h1
      exact commutatorElement_eq_one_iff_commute.mp h1
    have hñdvd : orderOf ñ ∣ Nat.card M := by
      rw [← hcardNtil, ← hoc Ntil ñ hñ]; exact orderOf_dvd_natCard _
    have hℓdvd : orderOf ℓ ∣ Nat.card L := by
      rw [← hoc L ℓ hℓ]; exact orderOf_dvd_natCard _
    have hcopñℓ : Nat.Coprime (orderOf ñ) (orderOf ℓ) :=
      (hcop.symm.coprime_dvd_left hñdvd).coprime_dvd_right hℓdvd
    have hordp : orderOf p = orderOf ñ * orderOf ℓ := by
      rw [← hprod]; exact hcomm.orderOf_mul_eq_mul_orderOf_of_coprime hcopñℓ
    rw [hordp] at hpodd
    have hℓodd : Odd (orderOf ℓ) := (Nat.odd_mul.mp hpodd).2
    obtain ⟨j, hj⟩ := IsPGroup.iff_orderOf.mp hL2 ⟨ℓ, hℓ⟩
    rw [hoc L ℓ hℓ] at hj
    rw [hj] at hℓodd
    have hj0 : j = 0 := by
      by_contra hjne
      have h2d : 2 ∣ 2 ^ j := dvd_pow_self 2 hjne
      have := Nat.odd_iff.mp hℓodd
      omega
    have hℓ1 : ℓ = 1 := orderOf_eq_one_iff.mp (by rw [hj, hj0, pow_zero])
    rw [← hprod, hℓ1, mul_one]; exact hñ
  -- normality of `Ñ` in `Y`
  have hNn : Ntil.Normal := by
    refine ⟨fun n hn y => ?_⟩
    apply hkey
    · rw [hNL_sup]; exact hMcn.conj_mem n (hNL_sup ▸ Subgroup.mem_sup_left hn) y
    · have hconj : orderOf (y * n * y⁻¹) = orderOf n := by
        have h := orderOf_injective (MulAut.conj y).toMonoidHom (MulAut.conj y).injective n
        simpa [MulAut.conj_apply] using h
      rw [hconj]
      exact odd_of_dvd (by rw [← hcardNtil, ← hoc Ntil n hn]; exact orderOf_dvd_natCard _) hModd
  -- `π(Ñ) = M`
  have hmapM : Ntil.map piY = M := by
    apply le_antisymm (Subgroup.map_le_iff_le_comap.mpr hNleP)
    intro m hm
    obtain ⟨y, rfl⟩ := hpi m
    have hyP : y ∈ Ntil ⊔ L := by rw [hNL_sup]; exact Subgroup.mem_comap.mpr hm
    obtain ⟨ñ, hñ, ℓ, hℓ, hprod⟩ := hdecomp y hyP
    have hpiy : piY y = piY ñ := by
      rw [← hprod, map_mul, show piY ℓ = 1 from (MonoidHom.mem_ker.mp (hkerL ▸ hℓ)), mul_one]
    rw [hpiy]; exact Subgroup.mem_map.mpr ⟨ñ, hñ, rfl⟩
  -- `Y/Ñ` is a 2-group
  haveI := hNn
  obtain ⟨kL, hkL⟩ := hL2.exists_card_eq
  obtain ⟨kH, hkH⟩ := hMtwo.exists_card_eq
  have hLindex2 : L.index = Nat.card H := by
    rw [Subgroup.index_eq_card, ← hkerL]
    exact Nat.card_congr (QuotientGroup.quotientKerEquivOfSurjective piY hpi).toEquiv
  have hcardYLH : Nat.card L * Nat.card H = Nat.card Y := by
    rw [← hLindex2]; exact Subgroup.card_mul_index L
  have hcardHM : Nat.card M * Nat.card (H ⧸ M) = Nat.card H := by
    rw [← Subgroup.index_eq_card]; exact Subgroup.card_mul_index M
  have hNtilindex : Ntil.index = 2 ^ kL * 2 ^ kH := by
    have hci : Nat.card Ntil * Ntil.index = Nat.card Y := Subgroup.card_mul_index Ntil
    rw [hcardNtil, ← hcardYLH, ← hcardHM, hkL, hkH] at hci
    have hre : 2 ^ kL * (Nat.card M * 2 ^ kH) = Nat.card M * (2 ^ kL * 2 ^ kH) := by ring
    rw [hre] at hci
    exact Nat.eq_of_mul_eq_mul_left Nat.card_pos hci
  have hYNtil2 : IsPGroup 2 (Y ⧸ Ntil) :=
    IsPGroup.of_card (n := kL + kH) (by rw [← Subgroup.index_eq_card, hNtilindex, pow_add])
  exact ⟨Ntil, hNn, by rw [hcardNtil]; exact hModd, hYNtil2, hNL_bot, hcentral, hmapM, hNL_sup⟩

/-- **The head of a boundary-framed target is 2-nilpotent.**  `H` is a finite tame quotient
`α : Ttame ↠ H` (the frame `α`), so its generators `α σ, α τ` satisfy the tame relation and
generate `H`; `tame_two_nilpotent` applies.  This discharges the `M` hypothesis of
`lemma_9_2_core` from the frame. -/
theorem head_two_nilpotent {H E : Type} [Group H] [TopologicalSpace H] [DiscreteTopology H]
    [Finite H] [CommGroup E] [TopologicalSpace E] [DiscreteTopology E] [Finite E]
    (F : BoundaryFrame H E) :
    ∃ M : Subgroup H, ∃ _ : M.Normal, Odd (Nat.card M) ∧ IsPGroup 2 (H ⧸ M) := by
  have hgen : Subgroup.closure {F.alpha tameSigma, F.alpha tameTau} = ⊤ :=
    GQ2.SectionThree.gen_ttame_quotient F.alpha.toMonoidHom F.alpha.continuous_toFun
      F.alpha_surjective
  have hrel : (F.alpha tameSigma)⁻¹ * F.alpha tameTau * F.alpha tameSigma
      = (F.alpha tameTau) ^ 2 := by
    have h := congrArg (⇑F.alpha) tame_relation
    rw [conjP, map_mul, map_mul, map_inv, map_pow] at h
    exact h
  exact tame_two_nilpotent hgen hrel

/-! ## Lemma 9.2 fibre-product infrastructure

The concrete tools the (144) correspondence runs on, all proved std-3:

* `odd_subgroup_le_ker_of_expTwo` — `θ_Y` (decoration to the exponent-2 group `E`) kills the odd
  complement `Ñ`, so it descends to `Q = Y/Ñ` (`L92.thetaBarQ`).  This is where `hE2` enters.
* `odd_mem_of_pTwo_quotient` — an odd-order element dies in a 2-group quotient (⟹ `H₂ = H/O²H`
  is cyclic, the engine of source-independence).
* `L92` — a bundle of the `lemma_9_2_core` outputs; `L92.fibreMulEquiv` is the fibre-product
  isomorphism `Y ≃* {(h,q) | κ h = λ q}` (eq. (143)), built from `coprime_fiber_product`.

Remaining for `terminal_count_eq` (the §9 induction): the boundary-lift ↔ Q-count bijection (two more
`coprime_fiber_product` applications for surjectivity) and source-independence of the Q-count
(the H₂-values factor through `ν_t`, so `compatA`/`compatF` make the two sources agree). -/

/-- **θ kills the odd complement.**  A homomorphism from a finite group to an exponent-2 group
vanishes on every odd-order normal subgroup.  (This is where `hE2` enters the terminal case:
`θ_Y` descends to `Q = Y/Ñ`.) -/
theorem odd_subgroup_le_ker_of_expTwo {Y E : Type} [Group Y] [Finite Y] [Group E]
    {N : Subgroup Y} (hodd : Odd (Nat.card N)) (hE2 : ∀ e : E, e ^ 2 = 1) (θ : Y →* E) :
    N ≤ θ.ker := by
  intro n hn
  rw [MonoidHom.mem_ker]
  have hno : Odd (orderOf n) := by
    have h1 : orderOf (⟨n, hn⟩ : N) ∣ Nat.card N := orderOf_dvd_natCard _
    have h2 : orderOf (⟨n, hn⟩ : N) = orderOf n :=
      (orderOf_injective N.subtype Subtype.coe_injective ⟨n, hn⟩).symm
    rw [h2] at h1
    exact odd_of_dvd h1 hodd
  have hd2 : orderOf (θ n) ∣ 2 := orderOf_dvd_of_pow_eq_one (hE2 (θ n))
  have hdn : orderOf (θ n) ∣ orderOf n := orderOf_map_dvd θ n
  have hodd' : Odd (orderOf (θ n)) := odd_of_dvd hdn hno
  rcases (Nat.dvd_prime Nat.prime_two).mp hd2 with h | h
  · exact orderOf_eq_one_iff.mp h
  · exact absurd (h ▸ hodd') (by decide)


/-- Bundle of the `lemma_9_2_core` outputs, to avoid threading a dozen hypotheses through the
fibre-product construction. -/
structure L92 (H Y : Type) [Group H] [Group Y] [Finite Y] where
  piY : Y →* H
  hpi : Function.Surjective piY
  L : Subgroup Y
  hkerL : piY.ker = L
  M : Subgroup H
  hMn : M.Normal
  hModd : Odd (Nat.card M)
  Ntil : Subgroup Y
  hNn : Ntil.Normal
  hNodd : Odd (Nat.card Ntil)
  hNL : Ntil ⊓ L = ⊥
  hmapM : Ntil.map piY = M
  hNLsup : Ntil ⊔ L = M.comap piY
  hQ2 : IsPGroup 2 (Y ⧸ Ntil)

namespace L92

variable {H Y : Type} [Group H] [Group Y] [Finite Y] (D : L92 H Y)

/-- `Q = Y / Ñ`. -/
abbrev Q := Y ⧸ D.Ntil

instance : (D.Ntil).Normal := D.hNn
instance : (D.M).Normal := D.hMn

/-- `Ntil ≤ ker (κ ∘ π_Y) = π_Y⁻¹(M)`. -/
theorem ntil_le_ker : D.Ntil ≤ ((QuotientGroup.mk' D.M).comp D.piY).ker := by
  intro n hn
  rw [MonoidHom.mem_ker, MonoidHom.comp_apply, QuotientGroup.mk'_apply,
    QuotientGroup.eq_one_iff]
  have : n ∈ D.M.comap D.piY := D.hNLsup ▸ Subgroup.mem_sup_left hn
  exact Subgroup.mem_comap.mp this

/-- The lower map `λ : Q ↠ H/M`, descending `κ ∘ π_Y`. -/
noncomputable def lamQ : D.Q →* H ⧸ D.M :=
  QuotientGroup.lift D.Ntil ((QuotientGroup.mk' D.M).comp D.piY) D.ntil_le_ker

@[simp] private theorem lamQ_mk (y : Y) :
    D.lamQ (QuotientGroup.mk y) = QuotientGroup.mk' D.M (D.piY y) := rfl

/-- The fibre product `{(h,q) | κ h = λ q} ≤ H × Q`. -/
noncomputable def fibreSub : Subgroup (H × D.Q) :=
  MonoidHom.eqLocus ((QuotientGroup.mk' D.M).comp (MonoidHom.fst H D.Q))
    (D.lamQ.comp (MonoidHom.snd H D.Q))

/-- `(π_Y y, mk' Ntil y)` lands in the fibre product. -/
theorem toFibre_mem (y : Y) : (D.piY y, (QuotientGroup.mk y : D.Q)) ∈ D.fibreSub := by
  show (QuotientGroup.mk' D.M) (D.piY y) = D.lamQ (QuotientGroup.mk y)
  rw [lamQ_mk]

/-- The map `Y → fibre product`, `y ↦ (π_Y y, mk' Ntil y)`. -/
noncomputable def toFibre : Y →* D.fibreSub :=
  (D.piY.prod (QuotientGroup.mk' D.Ntil)).codRestrict _ D.toFibre_mem

private theorem toFibre_injective : Function.Injective D.toFibre := by
  rw [injective_iff_map_eq_one]
  intro y hy
  have h1 : (D.piY y, (QuotientGroup.mk y : D.Q)) = 1 := by
    have := congrArg (Subtype.val) hy
    simpa [toFibre, MonoidHom.codRestrict] using this
  rw [Prod.ext_iff] at h1
  obtain ⟨hyH, hyQ⟩ := h1
  have hyL : y ∈ D.L := D.hkerL ▸ MonoidHom.mem_ker.mpr hyH
  have hyN : y ∈ D.Ntil := by rwa [← QuotientGroup.eq_one_iff]
  have : y ∈ D.Ntil ⊓ D.L := ⟨hyN, hyL⟩
  rw [D.hNL, Subgroup.mem_bot] at this
  exact this

private theorem lamQ_surjective : Function.Surjective D.lamQ := by
  intro z
  obtain ⟨y, hy⟩ := (QuotientGroup.mk'_surjective D.M).comp D.hpi z
  exact ⟨QuotientGroup.mk y, by rw [lamQ_mk]; exact hy⟩

private theorem toFibre_surjective : Function.Surjective D.toFibre := by
  haveI : Finite H := Finite.of_surjective D.piY D.hpi
  have hcop : Nat.Coprime (Nat.card (QuotientGroup.mk' D.M).ker) (Nat.card D.lamQ.ker) := by
    rw [QuotientGroup.ker_mk']
    have hpg : IsPGroup 2 (D.lamQ.ker) := fun x => by
      obtain ⟨k, hk⟩ := D.hQ2 (x : D.Q)
      exact ⟨k, by ext1; push_cast; exact hk⟩
    obtain ⟨k, hk⟩ := hpg.exists_card_eq
    rw [hk]
    have hnd : ¬ (2 : ℕ) ∣ Nat.card D.M := by have := Nat.odd_iff.mp D.hModd; omega
    exact ((Nat.prime_two.coprime_iff_not_dvd.mpr hnd).symm).pow_right k
  set J := (D.piY.prod (QuotientGroup.mk' D.Ntil)).range with hJdef
  have hJsub : ∀ p ∈ J, (QuotientGroup.mk' D.M) p.1 = D.lamQ p.2 := by
    rintro p ⟨y, rfl⟩
    show (QuotientGroup.mk' D.M) (D.piY y) = D.lamQ (QuotientGroup.mk y)
    rw [lamQ_mk]
  have hJA : Function.Surjective fun p : J => (p : H × D.Q).1 := by
    intro h; obtain ⟨y, hy⟩ := D.hpi h
    exact ⟨⟨(D.piY y, QuotientGroup.mk y), y, rfl⟩, hy⟩
  have hJB : Function.Surjective fun p : J => (p : H × D.Q).2 := by
    intro q; obtain ⟨y, hy⟩ := QuotientGroup.mk'_surjective D.Ntil q
    exact ⟨⟨(D.piY y, QuotientGroup.mk y), y, rfl⟩, hy⟩
  intro p
  have hp : (QuotientGroup.mk' D.M) (p : H × D.Q).1 = D.lamQ (p : H × D.Q).2 := p.2
  have hmem : (p : H × D.Q) ∈ J :=
    GQ2.FiniteGroup.coprime_fiber_product (QuotientGroup.mk' D.M) D.lamQ
      (QuotientGroup.mk'_surjective _) D.lamQ_surjective hcop J hJsub hJA hJB _ hp
  obtain ⟨y, hy⟩ := hmem
  exact ⟨y, Subtype.ext hy⟩

/-- **The fibre-product isomorphism** `Y ≃* {(h,q) | κ h = λ q}` (Lemma 9.2, eq. (143)). -/
noncomputable def fibreMulEquiv : Y ≃* D.fibreSub :=
  MulEquiv.ofBijective D.toFibre ⟨D.toFibre_injective, D.toFibre_surjective⟩

@[simp] private theorem fibreMulEquiv_apply (y : Y) :
    (D.fibreMulEquiv y : H × D.Q) = (D.piY y, QuotientGroup.mk y) := rfl

/-- A decoration `θ : Y →* E` to an exponent-2 group descends to `Q = Y/Ñ` (θ kills odd `Ñ`). -/
noncomputable def thetaBarQ {E : Type} [Group E] (θ : Y →* E) (hE2 : ∀ e : E, e ^ 2 = 1) :
    D.Q →* E :=
  QuotientGroup.lift D.Ntil θ (odd_subgroup_le_ker_of_expTwo D.hNodd hE2 θ)

@[simp] private theorem thetaBarQ_mk {E : Type} [Group E] (θ : Y →* E) (hE2 : ∀ e : E, e ^ 2 = 1)
    (y : Y) : D.thetaBarQ θ hE2 (QuotientGroup.mk y) = θ y := rfl

end L92

/-! ## The (144) correspondence

Lemma 9.2's fibre product identifies the boundary-framed lifts `Γ ↠ Y` with a Q-count set
(`boundaryLifts_equiv_qlifts`, source-generic); the maximal-pro-2 universal property then makes
that count source-independent (`qlifts_equiv_commonLifts`), routed through `ν`-compatibility and
`b`-surjectivity — no marked isomorphism is needed (only `prop_3_10_gammaA` and `ker_pro2F`). -/

section Correspondence

open SectionThree
open scoped Pointwise

variable {Y : Type} [Group Y] [TopologicalSpace Y] [DiscreteTopology Y] [Finite Y]

namespace L92

variable (D : L92 H Y)

omit [TopologicalSpace H] [DiscreteTopology H] [Finite H] in
/-- `Q = Y/Ñ` is discrete (quotient of a discrete group by an open subgroup). -/
theorem discreteTopology_Q : DiscreteTopology D.Q :=
  QuotientGroup.discreteTopology (isOpen_discrete _)

omit [TopologicalSpace H] [DiscreteTopology H] [Finite H] [TopologicalSpace Y]
  [DiscreteTopology Y] in
private theorem piY_symm (z : D.fibreSub) : D.piY (D.fibreMulEquiv.symm z) = (z : H × D.Q).1 := by
  have h := D.fibreMulEquiv_apply (D.fibreMulEquiv.symm z)
  rw [MulEquiv.apply_symm_apply] at h
  exact ((Prod.ext_iff.mp h).1).symm

omit [TopologicalSpace H] [DiscreteTopology H] [Finite H] [TopologicalSpace Y]
  [DiscreteTopology Y] in
private theorem mk_symm (z : D.fibreSub) :
    (QuotientGroup.mk (D.fibreMulEquiv.symm z) : D.Q) = (z : H × D.Q).2 := by
  have h := D.fibreMulEquiv_apply (D.fibreMulEquiv.symm z)
  rw [MulEquiv.apply_symm_apply] at h
  exact ((Prod.ext_iff.mp h).2).symm

/-- The quotient map `Y ↠ Q` as a continuous hom. -/
def mkCH : ContinuousMonoidHom Y D.Q := ⟨QuotientGroup.mk' D.Ntil, continuous_quotient_mk'⟩

omit [TopologicalSpace H] [DiscreteTopology H] [Finite H] [DiscreteTopology Y] in
@[simp] private theorem mkCH_apply (y : Y) : D.mkCH y = (QuotientGroup.mk y : D.Q) := rfl

end L92

variable {Γ : Type} [Group Γ] [TopologicalSpace Γ]

/-- **The Q-count set**: continuous surjections `Γ ↠ Q` satisfying the descended boundary
conditions (H-part through `λ`, θ-part through `θ̄`). -/
def QLifts (F : BoundaryFrame H E) (T : MarkedTarget H E Y) (hE2 : ∀ e : E, e ^ 2 = 1)
    (D : L92 H Y) (b : ContinuousMonoidHom Γ ↥boundarySubgroup) : Type :=
  { g : ContSurj Γ D.Q //
    (∀ γ, D.lamQ (g.1 γ) = QuotientGroup.mk' D.M (F.alpha (b γ).val.1)) ∧
    (∀ γ, D.thetaBarQ T.thetaY hE2 (g.1 γ) = F.psiBar (b γ).val.2) }

/-- The reconstruction of a boundary lift `f : Γ ↠ Y` from a Q-lift `g`, via the fibre product
`Y ≅ H ×_{H₂} Q`: `f γ := fibreMulEquiv.symm (F.alpha (b γ).1, g γ)`. -/
noncomputable def qliftHom (F : BoundaryFrame H E) (D : L92 H Y)
    (b : ContinuousMonoidHom Γ ↥boundarySubgroup) (g : ContSurj Γ D.Q)
    (h1 : ∀ γ, D.lamQ (g.1 γ) = QuotientGroup.mk' D.M (F.alpha (b γ).val.1)) :
    ContinuousMonoidHom Γ Y where
  toMonoidHom := D.fibreMulEquiv.symm.toMonoidHom.comp
    (((F.alpha.toMonoidHom.comp ((MonoidHom.fst Ttame PiBd).comp
      (boundarySubgroup.subtype.comp b.toMonoidHom))).prod g.1.toMonoidHom).codRestrict
      D.fibreSub (fun γ => (h1 γ).symm))
  continuous_toFun := by
    haveI hdQ : DiscreteTopology D.Q := D.discreteTopology_Q
    haveI : DiscreteTopology (H × D.Q) := inferInstance
    haveI : DiscreteTopology D.fibreSub := inferInstance
    have hφ : Continuous fun γ : Γ =>
        (⟨(F.alpha (b γ).val.1, g.1 γ), (h1 γ).symm⟩ : D.fibreSub) :=
      Continuous.subtype_mk ((F.alpha.continuous_toFun.comp (continuous_fst.comp
        (continuous_subtype_val.comp b.continuous_toFun))).prodMk g.1.continuous_toFun) _
    exact (continuous_of_discreteTopology (f := D.fibreMulEquiv.symm)).comp hφ

@[simp] private theorem qliftHom_piY (F : BoundaryFrame H E) (D : L92 H Y)
    (b : ContinuousMonoidHom Γ ↥boundarySubgroup) (g : ContSurj Γ D.Q)
    (h1 : ∀ γ, D.lamQ (g.1 γ) = QuotientGroup.mk' D.M (F.alpha (b γ).val.1)) (γ : Γ) :
    D.piY (qliftHom F D b g h1 γ) = F.alpha (b γ).val.1 := by
  rw [qliftHom]
  exact D.piY_symm _

@[simp] private theorem qliftHom_mk (F : BoundaryFrame H E) (D : L92 H Y)
    (b : ContinuousMonoidHom Γ ↥boundarySubgroup) (g : ContSurj Γ D.Q)
    (h1 : ∀ γ, D.lamQ (g.1 γ) = QuotientGroup.mk' D.M (F.alpha (b γ).val.1)) (γ : Γ) :
    (QuotientGroup.mk (qliftHom F D b g h1 γ) : D.Q) = g.1 γ := by
  rw [qliftHom]
  exact D.mk_symm _

/-- The reconstructed `f = qliftHom … g` is **surjective** (the "second `coprime_fiber_product`":
the range of `(γ ↦ (F.alpha (b γ).1, g γ))` is all of the fibre, since it projects onto both `H`
and `Q` which have coprime kernels).  Uses `hb` (surjectivity of `b`). -/
theorem qliftHom_surjective (F : BoundaryFrame H E) (D : L92 H Y)
    (b : ContinuousMonoidHom Γ ↥boundarySubgroup) (hb : Function.Surjective b)
    (g : ContSurj Γ D.Q)
    (h1 : ∀ γ, D.lamQ (g.1 γ) = QuotientGroup.mk' D.M (F.alpha (b γ).val.1)) :
    Function.Surjective (qliftHom F D b g h1) := by
  haveI : Finite H := Finite.of_surjective D.piY D.hpi
  have hHsurj : Function.Surjective fun γ : Γ => F.alpha (b γ).val.1 := by
    intro h
    obtain ⟨t, ht⟩ := F.alpha_surjective h
    obtain ⟨p, hp⟩ := nuTwo_surjective (nuT t)
    obtain ⟨γ, hγ⟩ := hb ⟨(t, p), hp.symm⟩
    refine ⟨γ, ?_⟩
    show F.alpha (b γ).val.1 = h
    rw [hγ]; exact ht
  have hcop : Nat.Coprime (Nat.card (QuotientGroup.mk' D.M).ker) (Nat.card D.lamQ.ker) := by
    rw [QuotientGroup.ker_mk']
    have hpg : IsPGroup 2 (D.lamQ.ker) := fun x => by
      obtain ⟨k, hk⟩ := D.hQ2 (x : D.Q)
      exact ⟨k, by ext1; push_cast; exact hk⟩
    obtain ⟨k, hk⟩ := hpg.exists_card_eq
    rw [hk]
    have hnd : ¬ (2 : ℕ) ∣ Nat.card D.M := by have := Nat.odd_iff.mp D.hModd; omega
    exact ((Nat.prime_two.coprime_iff_not_dvd.mpr hnd).symm).pow_right k
  set hHomM : Γ →* H := F.alpha.toMonoidHom.comp ((MonoidHom.fst Ttame PiBd).comp
    (boundarySubgroup.subtype.comp b.toMonoidHom)) with hHomMdef
  set J := (hHomM.prod g.1.toMonoidHom).range with hJdef
  have hJsub : ∀ p ∈ J, (QuotientGroup.mk' D.M) p.1 = D.lamQ p.2 := by
    rintro p ⟨γ, rfl⟩
    exact (h1 γ).symm
  have hJA : Function.Surjective fun p : J => (p : H × D.Q).1 := by
    intro h
    obtain ⟨γ, hγ⟩ := hHsurj h
    exact ⟨⟨(hHomM γ, g.1 γ), γ, rfl⟩, hγ⟩
  have hJB : Function.Surjective fun p : J => (p : H × D.Q).2 := by
    intro q
    obtain ⟨γ, hγ⟩ := g.2 q
    exact ⟨⟨(hHomM γ, g.1 γ), γ, rfl⟩, hγ⟩
  intro y
  have hz : (QuotientGroup.mk' D.M) (D.fibreMulEquiv y : H × D.Q).1
      = D.lamQ (D.fibreMulEquiv y : H × D.Q).2 := (D.fibreMulEquiv y).2
  obtain ⟨γ, hγ⟩ := GQ2.FiniteGroup.coprime_fiber_product (QuotientGroup.mk' D.M) D.lamQ
    (QuotientGroup.mk'_surjective _) D.lamQ_surjective hcop J hJsub hJA hJB _ hz
  refine ⟨γ, D.fibreMulEquiv.injective (Subtype.ext ?_)⟩
  rw [D.fibreMulEquiv_apply, qliftHom_piY, qliftHom_mk]
  exact hγ

/-- **Forward map** of the (144) correspondence: a boundary lift `f : Γ ↠ Y` descends to the
Q-lift `mk ∘ f`. -/
def blToQ (F : BoundaryFrame H E) (T : MarkedTarget H E Y) (hE2 : ∀ e : E, e ^ 2 = 1)
    (D : L92 H Y) (hDpi : D.piY = T.piY) (b : ContinuousMonoidHom Γ ↥boundarySubgroup)
    (x : BoundaryLifts b F T) : QLifts F T hE2 D b := by
  refine ⟨⟨D.mkCH.comp x.1.1, (QuotientGroup.mk'_surjective _).comp x.1.2⟩, ?_, ?_⟩
  · intro γ
    have hbl : T.piY (x.1.1 γ) = F.alpha (b γ).val.1 := congrArg Prod.fst (x.2 γ)
    show D.lamQ (D.mkCH (x.1.1 γ)) = QuotientGroup.mk' D.M (F.alpha (b γ).val.1)
    rw [D.mkCH_apply, D.lamQ_mk, hDpi, hbl]
  · intro γ
    have hbl : T.thetaY (x.1.1 γ) = F.psiBar (b γ).val.2 := congrArg Prod.snd (x.2 γ)
    show D.thetaBarQ T.thetaY hE2 (D.mkCH (x.1.1 γ)) = F.psiBar (b γ).val.2
    rw [D.mkCH_apply, D.thetaBarQ_mk, hbl]

/-- **Backward map** of the (144) correspondence: a Q-lift `g` reconstructs the boundary lift
`qliftHom … g` via the fibre product. -/
noncomputable def qToBl (F : BoundaryFrame H E) (T : MarkedTarget H E Y)
    (hE2 : ∀ e : E, e ^ 2 = 1) (D : L92 H Y) (hDpi : D.piY = T.piY)
    (b : ContinuousMonoidHom Γ ↥boundarySubgroup)
    (hb : Function.Surjective b) (g : QLifts F T hE2 D b) : BoundaryLifts b F T := by
  refine ⟨⟨qliftHom F D b g.1 g.2.1, qliftHom_surjective F D b hb g.1 g.2.1⟩, fun γ => ?_⟩
  refine Prod.ext ?_ ?_
  · show T.piY (qliftHom F D b g.1 g.2.1 γ) = F.alpha (b γ).val.1
    rw [← hDpi, qliftHom_piY]
  · show T.thetaY (qliftHom F D b g.1 g.2.1 γ) = F.psiBar (b γ).val.2
    rw [← D.thetaBarQ_mk T.thetaY hE2, qliftHom_mk]
    exact g.2.2 γ

/-- **(A) The (144) correspondence** (source-generic): the boundary-framed lifts `Γ ↠ Y` and the
Q-count set are in bijection, hence equinumerous.  Uses only surjectivity of `b`. -/
theorem boundaryLifts_equiv_qlifts (F : BoundaryFrame H E) (T : MarkedTarget H E Y)
    (hE2 : ∀ e : E, e ^ 2 = 1) (D : L92 H Y) (hDpi : D.piY = T.piY)
    (b : ContinuousMonoidHom Γ ↥boundarySubgroup) (hb : Function.Surjective b) :
    Nat.card (BoundaryLifts b F T) = Nat.card (QLifts F T hE2 D b) := by
  apply Nat.card_congr
  refine ⟨blToQ F T hE2 D hDpi b, qToBl F T hE2 D hDpi b hb, fun x => ?_, fun g => ?_⟩
  · -- left_inv
    apply Subtype.ext; apply Subtype.ext
    show qliftHom F D b (blToQ F T hE2 D hDpi b x).1 (blToQ F T hE2 D hDpi b x).2.1 = x.1.1
    ext γ
    have hpi : F.alpha (b γ).val.1 = D.piY (x.1.1 γ) := by
      rw [hDpi]; exact (congrArg Prod.fst (x.2 γ)).symm
    apply D.fibreMulEquiv.injective; apply Subtype.ext
    simp only [D.fibreMulEquiv_apply, qliftHom_piY, qliftHom_mk]
    exact Prod.ext hpi rfl
  · -- right_inv
    apply Subtype.ext; apply Subtype.ext; ext γ
    exact qliftHom_mk F D b g.1 g.2.1 γ

end Correspondence

section SourceIndependence

open SectionThree

/-- Precomposition with a topological iso is an equivalence of hom-sets. -/
def precompEquiv {A B Q : Type*} [Group A] [TopologicalSpace A] [Group B] [TopologicalSpace B]
    [Group Q] [TopologicalSpace Q] (ρ : ContinuousMulEquiv A B) :
    ContinuousMonoidHom B Q ≃ ContinuousMonoidHom A Q where
  toFun ψ := ψ.comp ⟨ρ.toMonoidHom, ρ.continuous_toFun⟩
  invFun φ := φ.comp ⟨ρ.symm.toMonoidHom, ρ.symm.continuous_toFun⟩
  left_inv ψ := by
    ext b
    exact congrArg ψ (ρ.apply_symm_apply b)
  right_inv φ := by
    ext a
    exact congrArg φ (ρ.symm_apply_apply a)

variable {Γ : Type} [Group Γ] [TopologicalSpace Γ] [IsTopologicalGroup Γ]
  [CompactSpace Γ] [T2Space Γ] [TotallyDisconnectedSpace Γ]

/-- The factoring of `pro2 : Γ ↠ Π` through the maximal pro-2 quotient of `Γ`
(`Π` is pro-2, `isProP_maxProPQuotient`). -/
noncomputable def pro2FactorHom (pro2 : ContinuousMonoidHom Γ PiBd) :
    ContinuousMonoidHom (maxProPQuotient 2 Γ) PiBd :=
  (maxProPHomEquiv (isProP_maxProPQuotient (G := profinitePresentation {piRelator}))).symm pro2

omit [T2Space Γ] in
private theorem pro2FactorHom_maxProPMk (pro2 : ContinuousMonoidHom Γ PiBd) (γ : Γ) :
    pro2FactorHom pro2 (maxProPMk 2 Γ γ) = pro2 γ :=
  DFunLike.congr_fun ((maxProPHomEquiv
    (isProP_maxProPQuotient (G := profinitePresentation {piRelator}))).apply_symm_apply pro2) γ

/-- The maximal pro-2 quotient of `Γ` is `Π` (`PiBd`), via a pro-2 quotient map `pro2` whose
kernel is exactly `proPKernel 2 Γ`. -/
noncomputable def pro2Iso (pro2 : ContinuousMonoidHom Γ PiBd) (hsurj : Function.Surjective pro2)
    (hker : pro2.toMonoidHom.ker = proPKernel 2 Γ) :
    ContinuousMulEquiv (maxProPQuotient 2 Γ) PiBd :=
  continuousMulEquivOfBijective (pro2FactorHom pro2)
    ⟨by
        rw [injective_iff_map_eq_one]
        intro x hx
        obtain ⟨γ, rfl⟩ := quotientMk_surjective (proPKernel 2 Γ) x
        have hx' : pro2 γ = 1 := by rw [← pro2FactorHom_maxProPMk pro2 γ]; exact hx
        exact (quotientMk_eq_one_iff _).mpr (hker ▸ MonoidHom.mem_ker.mpr hx'),
      fun p => by
        obtain ⟨γ, rfl⟩ := hsurj p
        exact ⟨maxProPMk 2 Γ γ, pro2FactorHom_maxProPMk pro2 γ⟩⟩

omit [T2Space Γ] in
private theorem pro2Iso_maxProPMk (pro2 : ContinuousMonoidHom Γ PiBd) (hsurj : Function.Surjective pro2)
    (hker : pro2.toMonoidHom.ker = proPKernel 2 Γ) (γ : Γ) :
    pro2Iso pro2 hsurj hker (maxProPMk 2 Γ γ) = pro2 γ :=
  pro2FactorHom_maxProPMk pro2 γ

/-- **Precomposition with the pro-2 quotient map** is a bijection of hom-sets into a pro-2 group
`Q`: every `g : Γ ↠ Q` factors uniquely through `Π`.  (The universal property of the maximal
pro-2 quotient, transported to `Π`.) -/
noncomputable def compPro2Equiv (pro2 : ContinuousMonoidHom Γ PiBd)
    (hsurj : Function.Surjective pro2) (hker : pro2.toMonoidHom.ker = proPKernel 2 Γ)
    {Q : Type} [Group Q] [TopologicalSpace Q] [IsTopologicalGroup Q] [CompactSpace Q] [T2Space Q]
    [TotallyDisconnectedSpace Q] (hQ : IsProP 2 Q) :
    ContinuousMonoidHom PiBd Q ≃ ContinuousMonoidHom Γ Q :=
  (precompEquiv (pro2Iso pro2 hsurj hker)).trans (maxProPHomEquiv hQ)

omit [T2Space Γ] in
private theorem compPro2Equiv_apply_apply (pro2 : ContinuousMonoidHom Γ PiBd)
    (hsurj : Function.Surjective pro2) (hker : pro2.toMonoidHom.ker = proPKernel 2 Γ)
    {Q : Type} [Group Q] [TopologicalSpace Q] [IsTopologicalGroup Q] [CompactSpace Q] [T2Space Q]
    [TotallyDisconnectedSpace Q] (hQ : IsProP 2 Q) (ψ : ContinuousMonoidHom PiBd Q) (γ : Γ) :
    compPro2Equiv pro2 hsurj hker hQ ψ γ = ψ (pro2 γ) := by
  show ψ (pro2Iso pro2 hsurj hker (maxProPMk 2 Γ γ)) = ψ (pro2 γ)
  rw [pro2Iso_maxProPMk]

variable {Y : Type} [Group Y] [TopologicalSpace Y] [DiscreteTopology Y] [Finite Y]

/-- **The common Q-count set on `Π`** (source-free): the H-condition is indexed by `∂bd`
(so it never mentions a source), the θ-condition ranges over all of `Π`. -/
def CommonLifts (F : BoundaryFrame H E) (T : MarkedTarget H E Y) (hE2 : ∀ e : E, e ^ 2 = 1)
    (D : L92 H Y) : Type :=
  { g : ContSurj PiBd D.Q //
    (∀ x : ↥boundarySubgroup, D.lamQ (g.1 x.val.2) = QuotientGroup.mk' D.M (F.alpha x.val.1)) ∧
    (∀ π : PiBd, D.thetaBarQ T.thetaY hE2 (g.1 π) = F.psiBar π) }

/-- **(B) Source-independence** (per source): the Q-count for a source `Γ` (with pro-2 quotient
map `pro2` presenting `Π`, `hker`) equals the source-free count on `Π`.  The H-condition
transports through surjectivity of `b` (`hbpro2`: the pro-2 component of `b` is `pro2`); the
θ-condition is already on `Π`. -/
theorem qlifts_equiv_commonLifts (F : BoundaryFrame H E) (T : MarkedTarget H E Y)
    (hE2 : ∀ e : E, e ^ 2 = 1) (D : L92 H Y)
    {Γ : Type} [Group Γ] [TopologicalSpace Γ] [IsTopologicalGroup Γ] [CompactSpace Γ] [T2Space Γ]
    [TotallyDisconnectedSpace Γ] (b : ContinuousMonoidHom Γ ↥boundarySubgroup)
    (hb : Function.Surjective b) (pro2 : ContinuousMonoidHom Γ PiBd)
    (hpro2 : Function.Surjective pro2) (hbpro2 : ∀ γ, (b γ).val.2 = pro2 γ)
    (hker : pro2.toMonoidHom.ker = proPKernel 2 Γ) :
    Nat.card (QLifts F T hE2 D b) = Nat.card (CommonLifts F T hE2 D) := by
  haveI hdQ : DiscreteTopology D.Q := D.discreteTopology_Q
  haveI : Finite D.Q := inferInstance
  have hQ : IsProP 2 D.Q := isProP_of_isPGroup D.hQ2
  set E' := compPro2Equiv pro2 hpro2 hker hQ with hE'def
  have happly : ∀ (ψ : ContinuousMonoidHom PiBd D.Q) (γ : Γ), E' ψ γ = ψ (pro2 γ) := by
    intro ψ γ; rw [hE'def]; exact compPro2Equiv_apply_apply pro2 hpro2 hker hQ ψ γ
  apply Nat.card_congr
  refine ⟨fun g => ⟨⟨E'.symm g.1.1, ?_⟩, ?_, ?_⟩, fun g => ⟨⟨E' g.1.1, ?_⟩, ?_, ?_⟩, ?_, ?_⟩
  · -- toFun surjective
    intro q
    obtain ⟨γ, hγ⟩ := g.1.2 q
    exact ⟨pro2 γ, by rw [← happly (E'.symm g.1.1) γ, E'.apply_symm_apply]; exact hγ⟩
  · -- toFun H-condition (indexed by ∂bd)
    intro x
    obtain ⟨γ, hγ⟩ := hb x
    have hx1 : (E'.symm g.1.1) x.val.2 = g.1.1 γ := by
      rw [show x.val.2 = pro2 γ by rw [← hγ]; exact hbpro2 γ,
        ← happly (E'.symm g.1.1) γ, E'.apply_symm_apply]
    rw [hx1, g.2.1 γ, hγ]
  · -- toFun θ-condition (indexed by Π)
    intro π
    obtain ⟨γ, hγ⟩ := hpro2 π
    have hπ : (E'.symm g.1.1) π = g.1.1 γ := by
      rw [← hγ, ← happly (E'.symm g.1.1) γ, E'.apply_symm_apply]
    rw [hπ, g.2.2 γ, hbpro2 γ, hγ]
  · -- invFun surjective
    intro q
    obtain ⟨π, hπ⟩ := g.1.2 q
    obtain ⟨γ, hγ⟩ := hpro2 π
    exact ⟨γ, by rw [happly g.1.1 γ, hγ]; exact hπ⟩
  · -- invFun H-condition (per γ)
    intro γ
    rw [happly g.1.1 γ]
    have h := g.2.1 (b γ)
    rw [hbpro2 γ] at h
    exact h
  · -- invFun θ-condition (per γ)
    intro γ
    rw [happly g.1.1 γ, g.2.2 (pro2 γ), hbpro2 γ]
  · -- left_inv
    intro g; apply Subtype.ext; apply Subtype.ext; exact E'.apply_symm_apply g.1.1
  · -- right_inv
    intro g; apply Subtype.ext; apply Subtype.ext; exact E'.symm_apply_apply g.1.1

end SourceIndependence

open SectionThree in
/-- `ker pro2A = proPKernel 2 Γ_A` for any `BoundaryMaps` `B`: `pro2A` agrees with the
`prop_3_10_gammaA` isomorphism `e ∘ maxProPMk` on the four marked topological generators, hence
equals it, and `e` is injective. -/
theorem ker_pro2A (B : BoundaryMaps) :
    B.pro2A.toMonoidHom.ker = proPKernel 2 GammaA := by
  obtain ⟨e, heσ, heτ, hex0, hex1⟩ := prop_3_10_gammaA
  set eHom : ContinuousMonoidHom GammaA PiBd :=
    (⟨e.toMonoidHom, e.continuous_toFun⟩ :
      ContinuousMonoidHom (maxProPQuotient 2 GammaA) PiBd).comp (maxProPMk 2 GammaA) with heHom
  have heq : ∀ g, B.pro2A g = eHom g := by
    apply monoidHom_eq_of_topGen B.pro2A.continuous_toFun eHom.continuous_toFun topGen_gammaA
    rintro z (rfl | rfl | rfl | rfl)
    · exact B.pro2A_sigma.trans heσ.symm
    · exact B.pro2A_tau.trans heτ.symm
    · exact B.pro2A_x0.trans hex0.symm
    · exact B.pro2A_x1.trans hex1.symm
  ext g
  constructor
  · intro hg
    have hg1 : eHom g = 1 := by rw [← heq g]; exact MonoidHom.mem_ker.mp hg
    have h2 : maxProPMk 2 GammaA g = 1 :=
      e.injective (by show e (maxProPMk 2 GammaA g) = e 1; rw [map_one]; exact hg1)
    exact (quotientMk_eq_one_iff (proPKernel 2 GammaA)).mp h2
  · intro hg
    have h2 : maxProPMk 2 GammaA g = 1 := (quotientMk_eq_one_iff (proPKernel 2 GammaA)).mpr hg
    have h3 : eHom g = 1 := by show e (maxProPMk 2 GammaA g) = 1; rw [h2, map_one]
    exact MonoidHom.mem_ker.mpr (by show B.pro2A g = 1; rw [heq g]; exact h3)

end SectionNine

end GQ2
