/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-4.8 and Fable-5
-/
import GQ2.GaussZ.FinalGammaA.Action

/-!
# Split-pack and final `Γ_A` Gauss-residue assembly

The split hypothesis package and the final discharge against the tame package.

See `GQ2.GaussZ.FinalGammaA` for the paper-facing overview, source citations, and deviations.
-/

namespace GQ2

namespace SectionEight

namespace AffineTLift

open CentralObstruction ContCoh WordCohBridge FoxH RStageGammaA WordCoh2 QuadraticFp2

/-! ## A-4.5c: the split hypothesis pack — `V^σ = 0` and the trivial `σ₂`-action

Unramified structure: with the acting group generated by `{s, t}` (`gen_ttame_quotient`
at the tame package) and inertia `t` acting trivially, every element acts as an integer
power of `s` — the action image is cyclic.  Fixed spaces of powers of `s` are therefore
invariant submodules, and simplicity forces the dichotomy: `V^s = 0` (else the whole
action is trivial, contradicting `hnt`), while the fixed space of the 2-primary part
`σ₂ = powOmega2 s` is NONZERO (a 2-group acting on a finite 2-group) hence everything.
These are the `hVS`/`hU` inputs of `lemma_5_13_split` / `x0Section_bijective_split` /
`liftMark_kappa0_wildValue_fib_split`. -/

section SplitPack

variable {C : Type*} [Group C] {V : Type*} [AddCommGroup V] [DistribMulAction C V]

/-- With `C = ⟨s, t⟩` and `t` acting trivially, every element acts as an integer power
of `s`. -/
theorem exists_zpow_smul_of_gen (s t : C) (hgen : Subgroup.closure ({s, t} : Set C) = ⊤)
    (htriv : ∀ v : V, t • v = v) (g : C) : ∃ n : ℤ, ∀ v : V, g • v = s ^ n • v := by
  have hg : g ∈ Subgroup.closure ({s, t} : Set C) := by rw [hgen]; trivial
  induction hg using Subgroup.closure_induction with
  | mem x hx =>
    rcases Set.mem_insert_iff.mp hx with rfl | hx'
    · exact ⟨1, fun v => by rw [zpow_one]⟩
    · rw [Set.mem_singleton_iff] at hx'
      subst hx'
      exact ⟨0, fun v => by rw [zpow_zero, one_smul]; exact htriv v⟩
  | one => exact ⟨0, fun v => by rw [zpow_zero, one_smul]⟩
  | mul x y hx hy ihx ihy =>
    obtain ⟨n, hn⟩ := ihx
    obtain ⟨k, hk⟩ := ihy
    exact ⟨n + k, fun v => by
      rw [mul_smul, hk v, hn (s ^ k • v), ← mul_smul, ← zpow_add]⟩
  | inv x hx ih =>
    obtain ⟨n, hn⟩ := ih
    refine ⟨-n, fun v => ?_⟩
    rw [inv_smul_eq_iff, hn, ← mul_smul, ← zpow_add, add_neg_cancel, zpow_zero, one_smul]

/-- The cyclic-image commutation: every element's action commutes with powers of `s`. -/
theorem smul_pow_comm_of_gen (s t : C) (hgen : Subgroup.closure ({s, t} : Set C) = ⊤)
    (htriv : ∀ v : V, t • v = v) (g : C) (e : ℕ) (v : V) :
    g • (s ^ e • v) = s ^ e • (g • v) := by
  obtain ⟨n, hn⟩ := exists_zpow_smul_of_gen s t hgen htriv g
  rw [hn (s ^ e • v), hn v, ← mul_smul, ← mul_smul]
  congr 1
  exact ((Commute.refl s).zpow_left n).pow_right e |>.eq

/-- **The split Frobenius-freeness (`hVS`)**: `V^s = 0` — the `s`-fixed space is an
invariant submodule (cyclic image), and `= ⊤` would make the whole action trivial,
contradicting `hnt`. -/
theorem sigma_fixed_eq_zero_of_gen (s t : C)
    (hgen : Subgroup.closure ({s, t} : Set C) = ⊤)
    (htriv : ∀ v : V, t • v = v)
    (hsimple : ∀ W : AddSubgroup V, (∀ g : C, ∀ w ∈ W, g • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (hnt : ∃ (g : C) (v : V), g • v ≠ v) :
    ∀ v : V, s • v = v → v = 0 := by
  set W : AddSubgroup V :=
    { carrier := {v : V | s • v = v}
      zero_mem' := smul_zero s
      add_mem' := fun {a b} ha hb => by
        show s • (a + b) = a + b
        rw [smul_add]
        exact congrArg₂ (· + ·) ha hb
      neg_mem' := fun {a} ha => by
        show s • (-a) = -a
        rw [smul_neg]
        exact congrArg Neg.neg ha } with hW
  have hstab : ∀ g : C, ∀ w ∈ W, g • w ∈ W := fun g w hw => by
    show s • (g • w) = g • w
    have hcomm := smul_pow_comm_of_gen s t hgen htriv g 1 w
    rw [pow_one] at hcomm
    rw [← hcomm]
    exact congrArg (g • ·) hw
  rcases hsimple W hstab with hbot | htop
  · exact fun v hv => AddSubgroup.mem_bot.mp (hbot ▸ (hv : v ∈ W))
  · exfalso
    obtain ⟨g, v, hgv⟩ := hnt
    obtain ⟨n, hn⟩ := exists_zpow_smul_of_gen s t hgen htriv g
    have hs : ∀ w : V, s • w = w := fun w => htop.ge (AddSubgroup.mem_top w)
    refine hgv ?_
    rw [hn v]
    exact Subgroup.zpow_mem _ (show s ∈ MulAction.stabilizer C v from hs v) n

/-- **The split `σ₂`-triviality (`hU`)**: the 2-primary part `powOmega2 s` acts trivially —
its fixed space is an invariant submodule (cyclic image), NONZERO because a 2-group acting
on a finite even-order module has even fixed count and fixes `0`, hence `⊤` by simplicity. -/
theorem powOmega2_smul_eq_of_gen [Finite C] [Finite V] (s t : C)
    (hgen : Subgroup.closure ({s, t} : Set C) = ⊤)
    (htriv : ∀ v : V, t • v = v)
    (hsimple : ∀ W : AddSubgroup V, (∀ g : C, ∀ w ∈ W, g • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (heven : 2 ∣ Nat.card V) :
    ∀ v : V, powOmega2 s • v = v := by
  classical
  letI : Fintype V := Fintype.ofFinite V
  -- the fixed space of `σ₂` as a submodule (`powOmega2 s` is literally a power of `s`)
  have hcm : ∀ (g : C) (v : V), g • (powOmega2 s • v) = powOmega2 s • (g • v) :=
    fun g v => smul_pow_comm_of_gen s t hgen htriv g (omega2Exp (orderOf s)) v
  set W : AddSubgroup V :=
    { carrier := {v : V | powOmega2 s • v = v}
      zero_mem' := smul_zero _
      add_mem' := fun {a b} ha hb => by
        show powOmega2 s • (a + b) = a + b
        rw [smul_add]
        exact congrArg₂ (· + ·) ha hb
      neg_mem' := fun {a} ha => by
        show powOmega2 s • (-a) = -a
        rw [smul_neg]
        exact congrArg Neg.neg ha } with hW
  have hstab : ∀ g : C, ∀ w ∈ W, g • w ∈ W := fun g w hw => by
    show powOmega2 s • (g • w) = g • w
    rw [← hcm g w]
    exact congrArg (g • ·) hw
  -- the 2-group `⟨σ₂⟩` and its fixed-point count
  letI : DistribMulAction ↥(Subgroup.zpowers (powOmega2 s)) V :=
    DistribMulAction.compHom V (Subgroup.zpowers (powOmega2 s)).subtype
  haveI : Fintype ↥(Subgroup.zpowers (powOmega2 s)) := Fintype.ofFinite _
  have hp2 : IsPGroup 2 ↥(Subgroup.zpowers (powOmega2 s)) := by
    obtain ⟨j, -, hj⟩ := (Nat.dvd_prime_pow Nat.prime_two).mp
      (orderOf_powOmega2_dvd_two_pow s)
    exact IsPGroup.of_card (n := j) (by rw [Nat.card_zpowers, hj])
  haveI : Fintype ↥(MulAction.fixedPoints ↥(Subgroup.zpowers (powOmega2 s)) V) :=
    Fintype.ofFinite _
  have hmod := hp2.card_modEq_card_fixedPoints V
  have h0mem : (0 : V) ∈ MulAction.fixedPoints ↥(Subgroup.zpowers (powOmega2 s)) V :=
    fun g => smul_zero g
  have hge1 : 1 ≤ Nat.card ↥(MulAction.fixedPoints ↥(Subgroup.zpowers (powOmega2 s)) V) :=
    Nat.one_le_iff_ne_zero.mpr (Nat.card_ne_zero.mpr ⟨⟨⟨0, h0mem⟩⟩, inferInstance⟩)
  have h2dvd : 2 ∣ Nat.card ↥(MulAction.fixedPoints ↥(Subgroup.zpowers (powOmega2 s)) V) := by
    have hV2 : Nat.card V ≡ 0 [MOD 2] := (Nat.modEq_zero_iff_dvd).mpr heven
    exact (Nat.modEq_zero_iff_dvd).mp (hmod.symm.trans hV2)
  have hgt : 1 < Fintype.card ↥(MulAction.fixedPoints ↥(Subgroup.zpowers (powOmega2 s)) V) := by
    rw [← Nat.card_eq_fintype_card]
    obtain ⟨k, hk⟩ := h2dvd
    omega
  -- a NONZERO fixed vector
  obtain ⟨x, hx⟩ := Fintype.exists_ne_of_one_lt_card hgt ⟨0, h0mem⟩
  have hwfix : powOmega2 s • (x : V) = (x : V) :=
    x.2 ⟨powOmega2 s, Subgroup.mem_zpowers _⟩
  have hwne : (x : V) ≠ 0 := fun h => hx (Subtype.ext h)
  -- the dichotomy: `W ≠ ⊥`, so `W = ⊤`
  rcases hsimple W hstab with hbot | htop
  · exact absurd (AddSubgroup.mem_bot.mp (hbot ▸ (hwfix : (x : V) ∈ W))) hwne
  · exact fun v => htop.ge (AddSubgroup.mem_top v)

/-- **The reverse tame conjugate is a `t`-power** (odd-order square root): if
`s⁻¹ * t * s = t²` and `t` has odd order `d`, then `s * t * s⁻¹` is the square root
`t^{(d+1)/2}` of `t` (squaring is invertible on the odd-order cyclic group `⟨t⟩`), hence
lies in `⟨t⟩`. -/
theorem conj_mem_zpowers_of_tameRel (s t : C) (hrel : s⁻¹ * t * s = t ^ 2)
    (hodd : Odd (orderOf t)) : s * t * s⁻¹ ∈ Subgroup.zpowers t := by
  have hsc : SemiconjBy s t (s * t * s⁻¹) := by
    show s * t = s * t * s⁻¹ * s
    group
  have hx2 : (s * t * s⁻¹) ^ 2 = t := by
    have h2 : (s * t * s⁻¹) ^ 2 = s * t ^ 2 * s⁻¹ := by
      rw [pow_two, pow_two]
      group
    rw [h2, ← hrel]
    group
  have horder : orderOf (s * t * s⁻¹) = orderOf t := hsc.orderOf_eq.symm
  obtain ⟨j, hj⟩ := hodd
  have hpow : s * t * s⁻¹ = t ^ (j + 1) := by
    have h1 : (s * t * s⁻¹) ^ (orderOf t + 1) = s * t * s⁻¹ := by
      rw [pow_succ, ← horder, pow_orderOf_eq_one, one_mul]
    calc s * t * s⁻¹ = (s * t * s⁻¹) ^ (orderOf t + 1) := h1.symm
      _ = ((s * t * s⁻¹) ^ 2) ^ (j + 1) := by
          rw [← pow_mul]
          congr 1
          omega
      _ = t ^ (j + 1) := by rw [hx2]
  rw [hpow]
  exact pow_mem (Subgroup.mem_zpowers t) (j + 1)

/-- **`⟨t⟩` is normalized by every group element** (both directions): with `C = ⟨s, t⟩`,
`s⁻¹ * t * s = t²`, and `t` of odd order, every `g` conjugates `t` into `⟨t⟩` from either
side, proved by closure induction over the generating set `{s, t}`. -/
theorem conj_mem_zpowers_of_gen (s t : C)
    (hgen : Subgroup.closure ({s, t} : Set C) = ⊤)
    (hrel : s⁻¹ * t * s = t ^ 2) (hodd : Odd (orderOf t)) :
    ∀ g : C, g⁻¹ * t * g ∈ Subgroup.zpowers t
      ∧ g * t * g⁻¹ ∈ Subgroup.zpowers t := by
  intro g
  have hg : g ∈ Subgroup.closure ({s, t} : Set C) := by rw [hgen]; trivial
  induction hg using Subgroup.closure_induction with
  | mem x hx =>
    rcases Set.mem_insert_iff.mp hx with rfl | hx'
    · refine ⟨?_, conj_mem_zpowers_of_tameRel x t hrel hodd⟩
      rw [hrel]
      exact pow_mem (Subgroup.mem_zpowers t) 2
    · rw [Set.mem_singleton_iff] at hx'
      subst hx'
      refine ⟨?_, ?_⟩
      · rw [show x⁻¹ * x * x = x from by group]
        exact Subgroup.mem_zpowers x
      · rw [show x * x * x⁻¹ = x from by group]
        exact Subgroup.mem_zpowers x
  | one =>
    refine ⟨?_, ?_⟩
    · rw [show (1 : C)⁻¹ * t * 1 = t from by group]
      exact Subgroup.mem_zpowers t
    · rw [show (1 : C) * t * 1⁻¹ = t from by group]
      exact Subgroup.mem_zpowers t
  | mul x y hx hy ihx ihy =>
    refine ⟨?_, ?_⟩
    · obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp ihx.1
      rw [show (x * y)⁻¹ * t * (x * y) = y⁻¹ * (x⁻¹ * t * x) * y from by group, ← hk,
        show y⁻¹ * t ^ k * y = (y⁻¹ * t * y) ^ k from by
          have h := map_zpow (MulAut.conj y⁻¹) t k
          simpa [MulAut.conj_apply, mul_assoc] using h]
      exact Subgroup.zpowers_le.mpr ihy.1 (zpow_mem (Subgroup.mem_zpowers _) k)
    · obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp ihy.2
      rw [show (x * y) * t * (x * y)⁻¹ = x * (y * t * y⁻¹) * x⁻¹ from by group, ← hk,
        show x * t ^ k * x⁻¹ = (x * t * x⁻¹) ^ k from by
          have h := map_zpow (MulAut.conj x) t k
          simpa [MulAut.conj_apply, mul_assoc] using h]
      exact Subgroup.zpowers_le.mpr ihx.2 (zpow_mem (Subgroup.mem_zpowers _) k)
  | inv x hx ih =>
    exact ⟨by rw [inv_inv]; exact ih.2, by rw [inv_inv]; exact ih.1⟩

/-- **The ramified inertia-freeness (`htauf`)**: with `C = ⟨s, t⟩`, the tame relation
`s⁻¹ts = t²`, and `t` of odd order, every conjugate of `t` is a power of `t`
(`⟨t⟩` is normal: `s`-conjugation squares, and the reverse conjugate is the square ROOT
`t^{(d+1)/2}` — odd order makes squaring invertible on `⟨t⟩`), so the `t`-fixed space is
an invariant submodule; if `t` moves anything, simplicity forces it to `⊥` — `V^t = 0`. -/
theorem tau_fixed_eq_zero_of_gen (s t : C)
    (hgen : Subgroup.closure ({s, t} : Set C) = ⊤)
    (hrel : s⁻¹ * t * s = t ^ 2)
    (hodd : Odd (orderOf t))
    (hsimple : ∀ W : AddSubgroup V, (∀ g : C, ∀ w ∈ W, g • w ∈ W) → W = ⊥ ∨ W = ⊤)
    (hmoved : ∃ v : V, t • v ≠ v) :
    ∀ v : V, t • v = v → v = 0 := by
  classical
  -- every element conjugates `t` into `⟨t⟩` (both directions), by closure induction
  have hconj := conj_mem_zpowers_of_gen s t hgen hrel hodd
  -- the `t`-fixed space is an invariant submodule; the dichotomy
  set W : AddSubgroup V :=
    { carrier := {v : V | t • v = v}
      zero_mem' := smul_zero t
      add_mem' := fun {a b} ha hb => by
        show t • (a + b) = a + b
        rw [smul_add]
        exact congrArg₂ (· + ·) ha hb
      neg_mem' := fun {a} ha => by
        show t • (-a) = -a
        rw [smul_neg]
        exact congrArg Neg.neg ha } with hW
  have hstab : ∀ g : C, ∀ w ∈ W, g • w ∈ W := fun g w hw => by
    show t • (g • w) = g • w
    obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp (hconj g).1
    have hfix : (g⁻¹ * t * g) • w = w := by
      rw [← hk]
      have htw : t ∈ MulAction.stabilizer C w := hw
      exact Subgroup.zpow_mem _ htw k
    calc t • (g • w) = (t * g) • w := (mul_smul t g w).symm
      _ = (g * (g⁻¹ * t * g)) • w := by
          rw [show t * g = g * (g⁻¹ * t * g) from by group]
      _ = g • ((g⁻¹ * t * g) • w) := mul_smul _ _ _
      _ = g • w := by rw [hfix]
  rcases hsimple W hstab with hbot | htop
  · exact fun v hv => AddSubgroup.mem_bot.mp (hbot ▸ (hv : v ∈ W))
  · exfalso
    obtain ⟨v, hv⟩ := hmoved
    exact hv (htop.ge (AddSubgroup.mem_top v))

end SplitPack

section Assembly

variable {H E : Type} [Group H] [TopologicalSpace H] [DiscreteTopology H] [Finite H]
  [CommGroup E] [TopologicalSpace E] [DiscreteTopology E] [Finite E]
variable {Y : Type} [Group Y] [TopologicalSpace Y] [DiscreteTopology Y] [Finite Y]
  {T : MarkedTarget H E Y} {Blk : SectionSeven.MinimalBlock T.LY}
variable {RF : RecursionFrame T Blk}
variable (B : BoundaryMaps) (F : BoundaryFrame H E) (En : RF.Enrichment)


/-! ## A-4.6: the G0-obtain discharge against the c3-G0 tame package

The ThmFourTwo `⟨G0, hGaussZA, hGaussZF⟩`-obtain, decomposed: everything except the
per-block tame-structure package is proved.  The package fields mirror the residue
theorems' `hpack` shapes VERBATIM (per-lift factorizations with the dichotomy clause);
`hfaith` is carried for the LOCAL twins only (the `Γ_A` twins run hfaith-free), and the
ramified flavor carries the orientation (provable only at the concrete
`boundaryMapsWitness` — `tameUnitOrientation_witness`). -/

/-- **The c3-G0 tame package, unramified flavor**: per-lift tame factorizations for both
sources with trivially-acting inertia, plus the form-level constants and the local-side
faithfulness. -/
structure TamePackageUnram (B : BoundaryMaps) (F : BoundaryFrame H E)
    (En : RF.Enrichment) where
  m : ℕ
  hm : 1 ≤ m
  hcard : Nat.card En.Vmod = 2 ^ (2 * m)
  hfaith : ∀ g : RF.YC, (∀ v : En.Vmod, g • v = v) → g = 1
  packA : ∀ ρ : BoundaryLifts B.bA F RF.TC, ∃ c : ContinuousMonoidHom Ttame RF.YC,
    Function.Surjective ⇑c ∧ (∀ g : GammaA, ρ.1.1 g = c (B.tameA g)) ∧
      ∀ v : En.Vmod, c tameTau • v = v
  packF : ∀ ρ : BoundaryLifts B.bF F RF.TC, ∃ c : ContinuousMonoidHom Ttame RF.YC,
    Function.Surjective ⇑c ∧ (∀ g : AbsGalQ2, ρ.1.1 g = c (B.tameF g)) ∧
      ∀ v : En.Vmod, c tameTau • v = v

/-- **The c3-G0 tame package, ramified flavor**: inertia moves the module; the local
side additionally needs the tame-unit orientation (at `R := localReciprocity`). -/
structure TamePackageRam (B : BoundaryMaps) (F : BoundaryFrame H E)
    (En : RF.Enrichment) where
  m : ℕ
  hm : 1 ≤ m
  hcard : Nat.card En.Vmod = 2 ^ (2 * m)
  hfaith : ∀ g : RF.YC, (∀ v : En.Vmod, g • v = v) → g = 1
  horient : TameUnitOrientation localReciprocity B.tameF
  packA : ∀ ρ : BoundaryLifts B.bA F RF.TC, ∃ c : ContinuousMonoidHom Ttame RF.YC,
    Function.Surjective ⇑c ∧ (∀ g : GammaA, ρ.1.1 g = c (B.tameA g)) ∧
      ∃ v : En.Vmod, c tameTau • v ≠ v
  packF : ∀ ρ : BoundaryLifts B.bF F RF.TC, ∃ c : ContinuousMonoidHom Ttame RF.YC,
    Function.Surjective ⇑c ∧ (∀ g : AbsGalQ2, ρ.1.1 g = c (B.tameF g)) ∧
      ∃ v : En.Vmod, c tameTau • v ≠ v


end Assembly

end AffineTLift

end SectionEight

end GQ2
