/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-4.8 and Fable-5
-/
import GQ2.Roe.Labute.StageLemma
import GQ2.Reconstruction
import GQ2.DyadicNielsen
import GQ2.Roe.DRAbelianization
import GQ2.Roe.MarkedPro2

/-!
# Assembly: levelwise nonemptiness → two epis → Hopfian → `bLab`  (ticket L1/L5)

**Statements final (ticket L1); fills ticket L5** (including the serialized
`GQ2/Reconstruction.lean` refactor).  Design record: `docs/orchestration/
labute-l1-design.md`; sources: `labute-plan.md` §2.1 (items 2–3), `labute-spike.md` §4.7.

The chain (plan §2.1, the "β-architecture" of the design memo — maximal reuse of the
in-tree König machinery):

1. `sPR0_nonempty`/`sPR2_nonempty`: the levelwise sets are nonempty at **every** level —
   base `k₀ = 3` (`Levelwise.lean`) + the stage step (`StageLemma.lean`) upward + the
   restriction maps downward.
2. `nonempty_contSurj_levelQuot_*`: for every open normal `U`, continuous surjections
   onto the finite quotient exist — the λ-tower is cofinal (`exists_twoCentralSeries_le`),
   a level-`k` triple is a hom by the universal properties `d0LiftHom`/`drLiftHom`
   (triples ⟺ homs, plan §2.1), generation mod `λₖ` is surjectivity, and quotients
   compose.
3. `exists_contSurj_of_levelwise_nonempty`: the generic König/Cantor assembly — **the
   exact statement whose proof is lines 224–309 of `exists_contSurj_of_card_le`**
   (`GQ2/Reconstruction.lean:213`) with the two `haveI`-inputs promoted to hypotheses.
   L5 protocol (byte-identical-consumers gate): prove this statement *in*
   `Reconstruction.lean` (module file, mathlib-only imports — the statement is expressible
   there verbatim), re-derive `exists_contSurj_of_card_le` from it through
   `contSurj_quotient_nonempty_finite` (line 119) so `reconstruction` /
   `reconstruction_of_equinum` and every consumer stay byte-identical, then discharge the
   sorry here by a one-line application of the Reconstruction-side lemma.  The statement
   below is the frozen consumer-facing form either way.
4. `bLab : BLabHypothesis` — **proved below** (not sorried): the two epis + the profinite
   Hopfian endgame, byte-for-byte the endgame of `reconstruction_of_equinum`
   (`GQ2/Reconstruction.lean:319`).  The four antecedents of `BLabHypothesis` are
   discarded: the pinned χ-data enters the proof through the levelwise sets (`chiR`,
   `chiD0pres`, tickets R10/R11), not through the abstract hypotheses — plan §1
   ("conveniences, not gates").

Census note (plan §8): this file imports `GQ2/Roe/MarkedPro2.lean` solely for the
**statement** `BLabHypothesis`; the proof chain (towers, levelwise sets, Reconstruction,
`dr_topGen`/`topGen_d0`) is axiom-file-free, and `lean_verify bLab` at L6 must report
std-3 + the interim sorries only.

The χ-intertwining bonus of spike §2.4 (the limit epi can be taken χ-compatible) is
deliberately **not** frozen — no `bLab`-consumer needs it; the design memo records the
α-architecture sketch for R15 should it ever be wanted.
-/

namespace GQ2.Roe.Labute

/-! ## Topological finite generation, `Finset`-packaged

The `Finset` forms consumed by `profinite_hopfian` and `finite_continuousMonoidHom`
(`GQ2/Reconstruction.lean:76,56`), discharged from the in-tree generator facts. -/

/-- `D_R` is topologically generated by the finite set `{s, x, y}` (packaging of
`dr_topGen`, `GQ2/Roe/DRAbelianization.lean:132`; smoke). -/
theorem drFinsetTopGen :
    ∃ s : Finset (DR : Type),
      (Subgroup.closure (s : Set (DR : Type))).topologicalClosure = ⊤ := by
  classical
  refine ⟨{drS, drX, drY}, ?_⟩
  have h : (({drS, drX, drY} : Finset (DR : Type)) : Set (DR : Type))
      = ({drS, drX, drY} : Set (DR : Type)) := by simp
  rw [h]
  exact dr_topGen

/-- `D₀` is topologically generated by the finite set `{A, S, Y}` (packaging of
`topGen_d0`, `GQ2/DyadicNielsen.lean:47`; smoke). -/
theorem d0FinsetTopGen :
    ∃ s : Finset (D0 : Type),
      (Subgroup.closure (s : Set (D0 : Type))).topologicalClosure = ⊤ := by
  classical
  refine ⟨{d0A, d0S, d0Y}, ?_⟩
  have h : (({d0A, d0S, d0Y} : Finset (D0 : Type)) : Set (D0 : Type))
      = ({d0A, d0S, d0Y} : Set (D0 : Type)) := by simp
  rw [h]
  exact SectionThree.topGen_d0

/-! ## The generic König/Cantor assembly (the L5 `Reconstruction.lean` refactor target) -/

/-- **Surjection assembly from levelwise nonemptiness** (plan §2.1 item 2): if `S`
continuously surjects onto every finite quotient of `R` in at least one and at most
finitely many ways, then `S` continuously surjects onto `R`.

This is `exists_contSurj_of_card_le` (`GQ2/Reconstruction.lean:213`) with the
`konigFunctor`-level inputs (`hne`, `hfin`) taken as hypotheses instead of being derived
from surjection counts; its proof is lines 224–309 of that lemma **verbatim**.  Fill: L5,
by the serialized `Reconstruction.lean` refactor described in the module docstring
(byte-identical-consumers regression gate). -/
theorem exists_contSurj_of_levelwise_nonempty
    {S R : Type} [Group S] [TopologicalSpace S] [IsTopologicalGroup S]
      [CompactSpace S] [TotallyDisconnectedSpace S]
    [Group R] [TopologicalSpace R] [IsTopologicalGroup R]
      [CompactSpace R] [TotallyDisconnectedSpace R]
    (hne : ∀ U : OpenNormalSubgroup (ProfiniteGrp.of R),
      Nonempty (ContSurj S (R ⧸ U.toSubgroup)))
    (hfin : ∀ U : OpenNormalSubgroup (ProfiniteGrp.of R),
      Finite (ContSurj S (R ⧸ U.toSubgroup))) :
    Nonempty (ContSurj S R) := by
  sorry

/-- Finiteness of the level sets from topological finite generation of the *source*
(the `hfin`-supplier; the `reconstruction_of_equinum` pattern, `Reconstruction.lean:330`;
smoke). -/
theorem finite_contSurj_quotient
    {S R : Type} [Group S] [TopologicalSpace S] [IsTopologicalGroup S]
      [CompactSpace S] [TotallyDisconnectedSpace S]
    [Group R] [TopologicalSpace R] [IsTopologicalGroup R]
      [CompactSpace R] [TotallyDisconnectedSpace R]
    (hSfg : ∃ s : Finset S, (Subgroup.closure (s : Set S)).topologicalClosure = ⊤)
    (U : OpenNormalSubgroup (ProfiniteGrp.of R)) :
    Finite (ContSurj S (R ⧸ U.toSubgroup)) := by
  haveI : Finite (R ⧸ U.toSubgroup) :=
    Subgroup.quotient_finite_of_isOpen U.toSubgroup U.isOpen'
  haveI := finite_continuousMonoidHom hSfg (R ⧸ U.toSubgroup)
  exact Subtype.finite

/-! ## Levelwise nonemptiness at every level -/

/-- Upward from the base level `3` by the stage step (direction 1). -/
private theorem sPR0_nonempty_of_three {k : ℕ} (hk : 3 ≤ k) : (sPR0 k).Nonempty := by
  induction k, hk using Nat.le_induction with
  | base => exact sPR0_three_nonempty
  | succ k hk ih => exact stageStepR0 k hk ih

/-- Upward from the base level `3` by the stage step (direction 2). -/
private theorem sPR2_nonempty_of_three {k : ℕ} (hk : 3 ≤ k) : (sPR2 k).Nonempty := by
  induction k, hk using Nat.le_induction with
  | base => exact sPR2_three_nonempty
  | succ k hk ih => exact stageStepR2 k hk ih

/-- Downward along the tower restrictions, `d` levels at a time (direction 1). -/
private theorem sPR0_nonempty_of_add :
    ∀ (d k : ℕ), (sPR0 (k + d)).Nonempty → (sPR0 k).Nonempty
  | 0, _, h => h
  | (d + 1), k, h =>
    sPR0_nonempty_of_add d k (h.elim fun _ hT => ⟨_, sPR0_levelProj hT⟩)

/-- Downward along the tower restrictions, `d` levels at a time (direction 2). -/
private theorem sPR2_nonempty_of_add :
    ∀ (d k : ℕ), (sPR2 (k + d)).Nonempty → (sPR2 k).Nonempty
  | 0, _, h => h
  | (d + 1), k, h =>
    sPR2_nonempty_of_add d k (h.elim fun _ hT => ⟨_, sPR2_levelProj hT⟩)

/-- **Levelwise nonemptiness, direction 1** (the mathematical core, assembled): `S^P_ₖ` is
nonempty for every `k` — upward from the base `sPR0_three_nonempty` by `stageStepR0`,
downward from level 3 by the restrictions `sPR0_levelProj`.  Fill: L5 (pure induction;
all inputs frozen). -/
theorem sPR0_nonempty (k : ℕ) : (sPR0 k).Nonempty :=
  sPR0_nonempty_of_add 3 k (sPR0_nonempty_of_three (Nat.le_add_left 3 k))

/-- Levelwise nonemptiness, direction 2.  Fill: L5. -/
theorem sPR2_nonempty (k : ℕ) : (sPR2 k).Nonempty :=
  sPR2_nonempty_of_add 3 k (sPR2_nonempty_of_three (Nat.le_add_left 3 k))

/-! ## From levelwise triples to surjections onto all finite quotients -/

section LiftValues

variable {H : Type} [Group H] [TopologicalSpace H] [IsTopologicalGroup H] [CompactSpace H]
  [T2Space H] [TotallyDisconnectedSpace H]

/-- Value of the `D₀`-lift on the marked generator `A` (binder-for-binder restatement of the
`private` `SectionThree.d0LiftHom_A`, which is not visible here; same three-line proof, the
`deriv0_d0A` pattern of `StageLemma.lean`). -/
private theorem d0LiftHom_d0A (hH : IsProP 2 H) (m : Fin 3 → H)
    (hrel : m 0 ^ 2 * m 1 ^ 4 * commP (m 1) (m 2) = 1) :
    SectionThree.d0LiftHom hH m hrel d0A = m 0 := by
  show ((maxProPHomEquiv hH).symm _) (maxProPMk 2 D0Full
    (quotientMk (relatorSubgroup {d0Relator}) (FreeProfiniteGroup.of 0))) = _
  rw [maxProPHomEquiv_symm_apply_maxProPMk]
  exact (quotientLift_quotientMk _ _ _ _).trans (FreeProfiniteGroup.homEquiv_symm_of _ _ _)

/-- Value of the `D₀`-lift on the marked generator `S` (restatement of the `private`
`SectionThree.d0LiftHom_S`). -/
private theorem d0LiftHom_d0S (hH : IsProP 2 H) (m : Fin 3 → H)
    (hrel : m 0 ^ 2 * m 1 ^ 4 * commP (m 1) (m 2) = 1) :
    SectionThree.d0LiftHom hH m hrel d0S = m 1 := by
  show ((maxProPHomEquiv hH).symm _) (maxProPMk 2 D0Full
    (quotientMk (relatorSubgroup {d0Relator}) (FreeProfiniteGroup.of 1))) = _
  rw [maxProPHomEquiv_symm_apply_maxProPMk]
  exact (quotientLift_quotientMk _ _ _ _).trans (FreeProfiniteGroup.homEquiv_symm_of _ _ _)

/-- Value of the `D₀`-lift on the marked generator `Y` (restatement of the `private`
`SectionThree.d0LiftHom_Y`). -/
private theorem d0LiftHom_d0Y (hH : IsProP 2 H) (m : Fin 3 → H)
    (hrel : m 0 ^ 2 * m 1 ^ 4 * commP (m 1) (m 2) = 1) :
    SectionThree.d0LiftHom hH m hrel d0Y = m 2 := by
  show ((maxProPHomEquiv hH).symm _) (maxProPMk 2 D0Full
    (quotientMk (relatorSubgroup {d0Relator}) (FreeProfiniteGroup.of 2))) = _
  rw [maxProPHomEquiv_symm_apply_maxProPMk]
  exact (quotientLift_quotientMk _ _ _ _).trans (FreeProfiniteGroup.homEquiv_symm_of _ _ _)

end LiftValues

/-- **The cofinality bridge, direction 1**: `D₀` continuously surjects onto every finite
quotient of `D_R`.  Route (plan §2.1): `U` contains some `λₖ` (`exists_twoCentralSeries_le`
with `drFinsetTopGen`, `isProP_DR`), a triple `T ∈ S⁰ₖ` is a continuous hom
`D₀ → Qₖ(D_R)` by `d0LiftHom` (at the finite 2-group `Qₖ`), generation makes it
surjective, and composing with `Qₖ(D_R) ↠ D_R/U` finishes.  Fill: L5. -/
theorem nonempty_contSurj_levelQuot_r0
    (U : OpenNormalSubgroup (ProfiniteGrp.of (DR : Type))) :
    Nonempty (ContSurj (D0 : Type) ((DR : Type) ⧸ U.toSubgroup)) := by
  classical
  -- Cofinality: `U` contains a tower level `λₖ`.
  obtain ⟨k, hk⟩ := exists_twoCentralSeries_le (DR : Type) drFinsetTopGen isProP_DR U.isOpen'
  -- Instance pack on the finite discrete target `Qₖ(D_R)`.
  haveI := discreteTopology_levelQuot (DR : Type) drFinsetTopGen isProP_DR k
  haveI : Finite (levelQuot (DR : Type) k) :=
    finite_levelQuot (DR : Type) drFinsetTopGen isProP_DR k
  have hproQ : IsProP 2 (levelQuot (DR : Type) k) :=
    isProP_of_isPGroup (isPGroup_levelQuot (DR : Type) drFinsetTopGen isProP_DR k)
  -- A level-`k` triple: relator-killing (⇒ a hom `D₀ → Qₖ`) and generating (⇒ onto).
  obtain ⟨T, ⟨hrel, hgen⟩, -⟩ := sPR0_nonempty k
  have hsurj : Function.Surjective (SectionThree.d0LiftHom hproQ T hrel).toMonoidHom := by
    rw [← MonoidHom.range_eq_top, ← top_le_iff, ← hgen, Subgroup.closure_le]
    rintro _ ⟨i, rfl⟩
    fin_cases i
    · exact ⟨d0A, d0LiftHom_d0A hproQ T hrel⟩
    · exact ⟨d0S, d0LiftHom_d0S hproQ T hrel⟩
    · exact ⟨d0Y, d0LiftHom_d0Y hproQ T hrel⟩
  -- Compose with the tower projection `Qₖ(D_R) ↠ D_R/U`.
  exact ⟨⟨(projMap hk).comp (SectionThree.d0LiftHom hproQ T hrel),
    (projMap_surjective hk).comp hsurj⟩⟩

/-- The cofinality bridge, direction 2: `D_R` continuously surjects onto every finite
quotient of `D₀` (via `drLiftHom` at `S⁰ₖ`-triples of the `D₀`-tower).  Fill: L5. -/
theorem nonempty_contSurj_levelQuot_r2
    (U : OpenNormalSubgroup (ProfiniteGrp.of (D0 : Type))) :
    Nonempty (ContSurj (DR : Type) ((D0 : Type) ⧸ U.toSubgroup)) := by
  classical
  obtain ⟨k, hk⟩ :=
    exists_twoCentralSeries_le (D0 : Type) d0FinsetTopGen SectionThree.d0_isProP U.isOpen'
  haveI := discreteTopology_levelQuot (D0 : Type) d0FinsetTopGen SectionThree.d0_isProP k
  haveI : Finite (levelQuot (D0 : Type) k) :=
    finite_levelQuot (D0 : Type) d0FinsetTopGen SectionThree.d0_isProP k
  have hproQ : IsProP 2 (levelQuot (D0 : Type) k) :=
    isProP_of_isPGroup
      (isPGroup_levelQuot (D0 : Type) d0FinsetTopGen SectionThree.d0_isProP k)
  obtain ⟨T, ⟨hrel, hgen⟩, -⟩ := sPR2_nonempty k
  have hsurj : Function.Surjective (drLiftHom hproQ T hrel).toMonoidHom := by
    rw [← MonoidHom.range_eq_top, ← top_le_iff, ← hgen, Subgroup.closure_le]
    rintro _ ⟨i, rfl⟩
    fin_cases i
    · exact ⟨drS, drLiftHom_S hproQ T hrel⟩
    · exact ⟨drX, drLiftHom_X hproQ T hrel⟩
    · exact ⟨drY, drLiftHom_Y hproQ T hrel⟩
  exact ⟨⟨(projMap hk).comp (drLiftHom hproQ T hrel),
    (projMap_surjective hk).comp hsurj⟩⟩

/-! ## The two epis and the Hopfian endgame -/

/-- The continuous epi `φ : D₀ ↠ D_R` (assembled; not a fill target — this composition is
part of the L1 elaboration certificate). -/
theorem nonempty_contSurj_D0_DR : Nonempty (ContSurj (D0 : Type) (DR : Type)) :=
  exists_contSurj_of_levelwise_nonempty
    (fun U => nonempty_contSurj_levelQuot_r0 U)
    (fun U => finite_contSurj_quotient d0FinsetTopGen U)

/-- The continuous epi `ψ : D_R ↠ D₀` (assembled; not a fill target). -/
theorem nonempty_contSurj_DR_D0 : Nonempty (ContSurj (DR : Type) (D0 : Type)) :=
  exists_contSurj_of_levelwise_nonempty
    (fun U => nonempty_contSurj_levelQuot_r2 U)
    (fun U => finite_contSurj_quotient drFinsetTopGen U)

/-- **The B-Lab classification instance, as a theorem** — the L-campaign deliverable
(plan §1: the exact interface of `GQ2/Roe/MarkedPro2.lean` `section Draft`, verbatim).

The proof is **complete here** modulo the upstream skeleton sorries: the four antecedents
are discarded (the pinned orientation data enters through the levelwise χ-clauses instead
— plan §1), the two epis come from the levelwise assembly above, and the endgame is
byte-for-byte the `reconstruction_of_equinum` endgame (`GQ2/Reconstruction.lean:350–354`):
`φ ∘ ψ : D_R ↠ D_R` is a continuous surjective endomorphism of a topologically f.g.
profinite group, hence injective (`profinite_hopfian`), so `ψ` is a continuous bijective
homomorphism, so a topological isomorphism (`continuousMulEquivOfBijective`). -/
theorem bLab : BLabHypothesis := by
  intro _ _ _ _
  obtain ⟨⟨φ, hφ⟩⟩ := nonempty_contSurj_D0_DR
  obtain ⟨⟨ψ, hψ⟩⟩ := nonempty_contSurj_DR_D0
  have hcomp : Function.Surjective (φ.comp ψ : ContinuousMonoidHom (DR : Type) (DR : Type)) :=
    hφ.comp hψ
  have hinj : Function.Injective (⇑φ ∘ ⇑ψ) :=
    profinite_hopfian drFinsetTopGen (φ.comp ψ) hcomp
  exact ⟨continuousMulEquivOfBijective ψ ⟨hinj.of_comp, hψ⟩⟩

end GQ2.Roe.Labute
