/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-4.8 and Fable-5
-/
import Mathlib.Algebra.Group.Commutator
import Mathlib.GroupTheory.Commutator.Basic
import Mathlib.NumberTheory.Padics.RingHoms
import GQ2.MaxProP
import GQ2.Words

/-!
# The lower 2-central tower `λₖ` of a topological group  (L-campaign ticket L1/L2)

**Statements final (ticket L1); fills ticket L2.**  Design record:
`docs/orchestration/labute-l1-design.md`; mathematical sources: `docs/orchestration/
labute-plan.md` §2.4 (Tier F) and `docs/orchestration/labute-spike.md` §1, §2.1, §4.1.

The **lower exponent-2 central series** (Serre, Bourbaki 252, §6–7: `F₁ = F`,
`F_{i+1} = (F_i)² (F, F_i)`; the spike's λ-series) of a topological group `G`:

* `λ₁ = G`, `λ_{k+1} = cl(λₖ² [λₖ, G])` — `twoCentralSeries G k`, **1-based** to match the
  memos' numerology (`k₀ = 3`, `m(k) = k`, calculus threshold `k ≥ 3`, `2^{k-1}`-tails).
  The index `0` is a junk value (`λ₀ := ⊤`) so that every statement at `k ≥ 1` reads
  exactly as in the memos.  All layers are closed by construction.
* `Qₖ = G/λₖ` — `levelQuot G k`, with projections `levelProj : Q_{k+1} →* Qₖ`, the
  canonical (non-homomorphic) section `canonLift`, and the two-index images
  `lambdaImage G j k = λⱼλₖ/λₖ ≤ Qₖ`.
* `Zₖ = λₖ/λ_{k+1}` — `zLayer G k := lambdaImage G k (k+1) ≤ Q_{k+1}`, central and
  elementary abelian (spike §2.1).
* For topologically f.g. pro-2 `G`: each `λₖ` is open, each `Qₖ` a finite 2-group, the
  tower is a neighborhood basis of `1`, and `⨅ λₖ = ⊥` (plan §2.4).  The categorical
  limit statement `G ≅ lim G/λₖ` of plan §2.4 is deliberately **not** frozen here: no
  L-campaign consumer needs it (the assembly runs through the cofinality statement
  `exists_twoCentralSeries_le` + `GQ2/Reconstruction.lean`) — see the design memo §3.
* Functoriality: the series is verbal, so continuous homs map `λₖ` into `λₖ`, with
  equality for continuous epis of compact groups.
* The **χ-shadow layer** (spike §2.7.5, §4.1): `λₖ(ℤ₂ˣ) ⊆ 1 + 2^{k+1}ℤ₂` for `k ≥ 2`
  (`twoCentralSeries_units_le`, stated as containment in the kernel of reduction mod
  `2^{k+1}`), and for any continuous `χ : G → ℤ₂ˣ` the level shadow
  `chiLevel χ k : Qₖ →* (ZMod 2^k)ˣ` — precision `2^k`, the modulus of the invariant `P`
  (`m(k) = k`, spike §2.4).  The spike's finer shadow `χ̂ₖ` (precision `2^{k+1}` on `Qₖ`)
  is *not* a frozen definition; fills needing the extra digit build it locally from
  `twoCentralSeries_units_le` (design memo §4).

## Commutator conventions (board §10; read before filling)

Two commutator conventions coexist in this development, **deliberately**:

* **Repo convention** (`GQ2/Words.lean`): `commP x y = x⁻¹y⁻¹xy`, `conjP x g = g⁻¹xg`.
  Every *word-shape* statement of the campaign — the relators `drWord`/`d0Word`, the
  defect, the shift formulas `dbarWordR0`/`dbarWordR2` (`StageLemma.lean`), and all
  LS-memo tables — is in `commP` form; L3/L4 consume the spike's data with **no sign
  translation**.
* **Mathlib convention**: `⁅g, h⁆ = g*h*g⁻¹*h⁻¹` (scoped instance `commutatorElement`),
  and the subgroup-level `⁅H, K⁆`.  It appears in exactly one place: the generating set
  of `twoCentralSucc` uses `⁅H, ⊤⁆`, to inherit mathlib's commutator-subgroup API
  (`Subgroup.map_commutator` etc.) for the functoriality fills.

The two choices generate the same subgroups: `commP v g = ⁅v⁻¹, g⁻¹⁆`, so with `v` ranging
over a subgroup both families give the same step — the **translation lemma** is
`commP_mem_twoCentralSucc` below (proved, not sorried).  λ-series statements are
convention-independent; only element-level formulas care, and those are all `commP`.

Skeleton discipline: `sorry`s below are the L2 fill contract (exact inventory in the
design memo); the non-`sorry` lemmas are L1 smoke tests.
-/

namespace GQ2.Roe.Labute

open scoped commutatorElement

/-! ## The series -/

section Series

variable {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- One step of the lower 2-central series: `H ↦ cl(H²[H, G])`, the topological closure of
the subgroup generated by the squares of `H` and the commutators `[H, G]`.  (Serre 252 §6:
`F_{i+1} = (F_i)^q (F, F_i)` at `q = 2`; spike §1.)  Mathlib's commutator subgroup
`⁅H, ⊤⁆` is used; it agrees with the subgroup generated by the repo-convention commutators
`commP v g` (`commP_mem_twoCentralSucc` below). -/
def twoCentralSucc (H : Subgroup G) : Subgroup G :=
  (Subgroup.closure ((fun v : G => v ^ 2) '' (H : Set G)) ⊔ ⁅H, (⊤ : Subgroup G)⁆).topologicalClosure

/-- A square from `H` lies in `twoCentralSucc H`. -/
theorem sq_mem_twoCentralSucc {H : Subgroup G} {v : G} (hv : v ∈ H) :
    v ^ 2 ∈ twoCentralSucc H := by
  apply Subgroup.le_topologicalClosure
  exact Subgroup.mem_sup_left
    (Subgroup.subset_closure (Set.mem_image_of_mem (fun v : G => v ^ 2) hv))

/-- A mathlib-convention commutator `⁅v, g⁆` with `v ∈ H` lies in `twoCentralSucc H`. -/
theorem commutator_mem_twoCentralSucc {H : Subgroup G} {v : G} (hv : v ∈ H) (g : G) :
    ⁅v, g⁆ ∈ twoCentralSucc H := by
  apply Subgroup.le_topologicalClosure
  exact Subgroup.mem_sup_right
    (Subgroup.commutator_mem_commutator hv (Subgroup.mem_top g))

/-- **Convention bridge** (smoke): a repo-convention commutator `commP v g = v⁻¹g⁻¹vg`
(`GQ2/Words.lean`) with `v ∈ H` lies in `twoCentralSucc H` — so the generating sets of the
memos (stated with `commP`) and the mathlib bracket generate the same step. -/
theorem commP_mem_twoCentralSucc {H : Subgroup G} {v : G} (hv : v ∈ H) (g : G) :
    commP v g ∈ twoCentralSucc H := by
  have h : commP v g = ⁅v⁻¹, g⁻¹⁆ := by
    simp only [commP, commutatorElement_def, inv_inv]
  rw [h]
  exact commutator_mem_twoCentralSucc (H.inv_mem hv) g⁻¹

omit [TopologicalSpace G] [IsTopologicalGroup G] in
/-- The subgroup of squares of a normal subgroup is normal (`(gvg⁻¹)² = gv²g⁻¹`). -/
theorem sqClosure_normal {H : Subgroup G} (hH : H.Normal) :
    (Subgroup.closure ((fun v : G => v ^ 2) '' (H : Set G))).Normal := by
  constructor
  intro n hn g
  have hmap : Subgroup.map (MulAut.conj g).toMonoidHom
      (Subgroup.closure ((fun v : G => v ^ 2) '' (H : Set G))) ≤
      Subgroup.closure ((fun v : G => v ^ 2) '' (H : Set G)) := by
    rw [MonoidHom.map_closure]
    refine Subgroup.closure_le _ |>.2 ?_
    rintro _ ⟨_, ⟨v, hv, rfl⟩, rfl⟩
    exact Subgroup.subset_closure ⟨g * v * g⁻¹, hH.conj_mem v hv g, by simp⟩
  exact hmap ⟨n, hn, rfl⟩

omit [TopologicalSpace G] [IsTopologicalGroup G] in
/-- The generating subgroup `H²[H, G]` of one step, before taking the closure. -/
theorem twoCentralSuccGen_normal {H : Subgroup G} (hH : H.Normal) :
    (Subgroup.closure ((fun v : G => v ^ 2) '' (H : Set G)) ⊔ ⁅H, (⊤ : Subgroup G)⁆).Normal := by
  haveI := hH
  haveI := sqClosure_normal hH
  infer_instance

/-- One step of the series preserves normality. -/
theorem twoCentralSucc_normal {H : Subgroup G} (hH : H.Normal) : (twoCentralSucc H).Normal := by
  haveI := twoCentralSuccGen_normal hH
  exact Subgroup.is_normal_topologicalClosure _

/-- One step of the series is contained in its input, for a closed normal subgroup. -/
theorem twoCentralSucc_le {H : Subgroup G} (hH : H.Normal) (hc : IsClosed (H : Set G)) :
    twoCentralSucc H ≤ H := by
  haveI := hH
  refine Subgroup.topologicalClosure_minimal _ (sup_le ?_ (Subgroup.commutator_le_left _ _)) hc
  refine Subgroup.closure_le _ |>.2 ?_
  rintro _ ⟨v, hv, rfl⟩
  exact pow_mem hv 2

/-- One step of the series is monotone in its input. -/
theorem twoCentralSucc_mono {H K : Subgroup G} (h : H ≤ K) :
    twoCentralSucc H ≤ twoCentralSucc K :=
  Subgroup.topologicalClosure_mono
    (sup_le_sup (Subgroup.closure_mono (Set.image_mono h)) (Subgroup.commutator_mono h le_rfl))

end Series

section Tower

variable (G : Type*) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- The **lower 2-central series** `λₖ` of `G`, 1-based as in the memos:
`λ₁ = G`, `λ_{k+1} = cl(λₖ²[λₖ, G])` (`twoCentralSucc`).  Index `0` is a junk value
(`λ₀ := ⊤ = λ₁`); the recursion genuinely starts at `k = 1`, so `twoCentralSeries_succ`
below carries the hypothesis `1 ≤ k`. -/
def twoCentralSeries : ℕ → Subgroup G
  | 0 => ⊤
  | 1 => ⊤
  | (k + 2) => twoCentralSucc (twoCentralSeries (k + 1))

@[simp] theorem twoCentralSeries_zero : twoCentralSeries G 0 = ⊤ := rfl

@[simp] theorem twoCentralSeries_one : twoCentralSeries G 1 = ⊤ := rfl

/-- The defining recursion, valid from `k = 1` (at `k = 0` the junk convention breaks it). -/
theorem twoCentralSeries_succ {k : ℕ} (hk : 1 ≤ k) :
    twoCentralSeries G (k + 1) = twoCentralSucc (twoCentralSeries G k) := by
  match k, hk with
  | (k + 1), _ => rfl

/-- Every layer is closed (`λ₁ = G` and closures thereafter). -/
theorem isClosed_twoCentralSeries (k : ℕ) :
    IsClosed ((twoCentralSeries G k : Subgroup G) : Set G) := by
  match k with
  | 0 => exact isClosed_univ
  | 1 => exact isClosed_univ
  | (k + 2) => exact isClosed_closure

/-- Each `λₖ` is a normal subgroup (it is verbal: generated by the values of the words
`v²`, `[v, g]` over `λ_{k-1} × G`, a conjugation-stable family).  Fill: L2. -/
theorem twoCentralSeries_normal (k : ℕ) : (twoCentralSeries G k).Normal := by
  induction k with
  | zero => exact Subgroup.normal_top
  | succ k ih =>
    match k, ih with
    | 0, _ => exact Subgroup.normal_top
    | (k + 1), ih => exact twoCentralSucc_normal ih

instance (k : ℕ) : (twoCentralSeries G k).Normal := twoCentralSeries_normal G k

/-- The series is decreasing: `λ_{k+1} ≤ λₖ` and generally antitone.  Fill: L2. -/
theorem twoCentralSeries_antitone : Antitone (twoCentralSeries G) := by
  refine antitone_nat_of_succ_le fun k => ?_
  match k with
  | 0 => exact le_top
  | (k + 1) =>
    exact twoCentralSucc_le (twoCentralSeries_normal G (k + 1))
      (isClosed_twoCentralSeries G (k + 1))

/-- Squares of `λₖ` land in `λ_{k+1}` (also at the junk index `k = 0`, where `λ₁ = ⊤`). -/
theorem sq_mem_twoCentralSeries_succ {k : ℕ} {v : G} (hv : v ∈ twoCentralSeries G k) :
    v ^ 2 ∈ twoCentralSeries G (k + 1) := by
  match k with
  | 0 => exact Subgroup.mem_top _
  | (k + 1) => exact sq_mem_twoCentralSucc hv

/-- Commutators `⁅λₖ, G⁆` land in `λ_{k+1}` (also at the junk index `k = 0`). -/
theorem commutator_mem_twoCentralSeries_succ {k : ℕ} {v : G} (hv : v ∈ twoCentralSeries G k)
    (g : G) : ⁅v, g⁆ ∈ twoCentralSeries G (k + 1) := by
  match k with
  | 0 => exact Subgroup.mem_top _
  | (k + 1) => exact commutator_mem_twoCentralSucc hv g

end Tower

/-! ## The level quotients `Qₖ`, projections, and layer images -/

section Level

variable (G : Type*) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- The level-`k` quotient `Qₖ = G/λₖ` of the memos (finite for topologically f.g. pro-2
`G`, `finite_levelQuot`).  `Q₀ = Q₁ = 1` by the junk convention. -/
abbrev levelQuot (k : ℕ) : Type _ := G ⧸ twoCentralSeries G k

/-- The canonical projection `G →* Qₖ`. -/
def levelMk (k : ℕ) : G →* levelQuot G k :=
  QuotientGroup.mk' (twoCentralSeries G k)

theorem levelMk_surjective (k : ℕ) : Function.Surjective (levelMk G k) :=
  QuotientGroup.mk'_surjective _

/-- The tower projection `Q_{k+1} →* Qₖ` (along `λ_{k+1} ≤ λₖ`). -/
def levelProj (k : ℕ) : levelQuot G (k + 1) →* levelQuot G k :=
  QuotientGroup.map _ _ (MonoidHom.id G)
    (by simpa using twoCentralSeries_antitone G (Nat.le_succ k))

@[simp] theorem levelProj_levelMk (k : ℕ) (g : G) :
    levelProj G k (levelMk G (k + 1) g) = levelMk G k g := rfl

theorem levelProj_surjective (k : ℕ) : Function.Surjective (levelProj G k) := by
  intro q
  obtain ⟨g, rfl⟩ := levelMk_surjective G k q
  exact ⟨levelMk G (k + 1) g, rfl⟩

/-- A canonical set-theoretic section `Qₖ → Q_{k+1}` of `levelProj` (not a homomorphism);
the *canonical lift* through which the defect and the stage lemma are stated
(`GQ2/Roe/Labute/Levelwise.lean`, `StageLemma.lean`).  Lift-independence of everything
built from it is part of the frozen contract (`defectR0_eq_of_lift` etc.). -/
noncomputable def canonLift (k : ℕ) : levelQuot G k → levelQuot G (k + 1) :=
  Function.surjInv (levelProj_surjective G k)

@[simp] theorem levelProj_canonLift (k : ℕ) (q : levelQuot G k) :
    levelProj G k (canonLift G k q) = q :=
  Function.surjInv_eq (levelProj_surjective G k) q

/-- The image `λⱼλₖ/λₖ` of `λⱼ` in the level-`k` quotient `Qₖ` (interesting for `j < k`).
For `j = k - 1` these are the **modification spaces** of the stage calculus (spike §2.1). -/
def lambdaImage (j k : ℕ) : Subgroup (levelQuot G k) :=
  (twoCentralSeries G j).map (levelMk G k)

/-- Projections respect the layer images (smoke). -/
theorem levelProj_mem_lambdaImage {j k : ℕ} {q : levelQuot G (k + 1)}
    (hq : q ∈ lambdaImage G j (k + 1)) : levelProj G k q ∈ lambdaImage G j k := by
  obtain ⟨g, hg, rfl⟩ := hq
  exact ⟨g, hg, rfl⟩

/-- **The graded layer** `Zₖ = λₖ/λ_{k+1}`, realized as a subgroup of `Q_{k+1}` (the
encoding in which the defect, the shift formulas, and the span theorem are stated). -/
abbrev zLayer (k : ℕ) : Subgroup (levelQuot G (k + 1)) := lambdaImage G k (k + 1)

/-- `Zₖ` is exactly the kernel of the tower projection.  Fill: L2. -/
theorem zLayer_eq_ker_levelProj (k : ℕ) : zLayer G k = (levelProj G k).ker := by
  refine le_antisymm ?_ ?_
  · rintro _ ⟨x, hx, rfl⟩
    rw [MonoidHom.mem_ker, levelProj_levelMk]
    exact (QuotientGroup.eq_one_iff x).mpr hx
  · intro q hq
    obtain ⟨g, rfl⟩ := levelMk_surjective G (k + 1) q
    rw [MonoidHom.mem_ker, levelProj_levelMk] at hq
    exact ⟨g, (QuotientGroup.eq_one_iff g).mp hq, rfl⟩

/-- `Zₖ` is central in `Q_{k+1}` (spike §2.1: `[λₖ, G] ⊆ λ_{k+1}`).  Fill: L2. -/
theorem zLayer_le_center (k : ℕ) : zLayer G k ≤ Subgroup.center (levelQuot G (k + 1)) := by
  rintro _ ⟨v, hv, rfl⟩
  rw [Subgroup.mem_center_iff]
  intro q
  obtain ⟨h, rfl⟩ := levelMk_surjective G (k + 1) q
  have h1 : ⁅levelMk G (k + 1) v, levelMk G (k + 1) h⁆ = 1 := by
    rw [← map_commutatorElement]
    exact (QuotientGroup.eq_one_iff _).mpr (commutator_mem_twoCentralSeries_succ G hv h)
  exact (commutatorElement_eq_one_iff_mul_comm.mp h1).symm

/-- `Zₖ` is elementary abelian: every element squares to `1` (spike §2.1:
`λₖ² ⊆ λ_{k+1}`).  Fill: L2. -/
theorem zLayer_sq {k : ℕ} {z : levelQuot G (k + 1)} (hz : z ∈ zLayer G k) : z ^ 2 = 1 := by
  obtain ⟨v, hv, rfl⟩ := hz
  rw [← map_pow]
  exact (QuotientGroup.eq_one_iff _).mpr (sq_mem_twoCentralSeries_succ G hv)

end Level

/-! ## Openness, finiteness, and the neighborhood basis (topologically f.g. pro-2 `G`) -/

section Profinite

variable (G : Type*) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G]

/-- For a topologically finitely generated pro-2 group, every `λₖ` is open.  (Openness at
each step: `λₖ/λ_{k+1}` is generated by finitely many square/commutator classes of
exponent 2 — plan §2.4.)  Fill: L2. -/
theorem isOpen_twoCentralSeries
    (hfg : ∃ s : Finset G, (Subgroup.closure (s : Set G)).topologicalClosure = ⊤)
    (hpro : IsProP 2 G) (k : ℕ) : IsOpen ((twoCentralSeries G k : Subgroup G) : Set G) := by
  sorry

/-- The level quotients of a topologically f.g. pro-2 group are finite.  Fill: L2. -/
theorem finite_levelQuot
    (hfg : ∃ s : Finset G, (Subgroup.closure (s : Set G)).topologicalClosure = ⊤)
    (hpro : IsProP 2 G) (k : ℕ) : Finite (levelQuot G k) := by
  sorry

/-- The level quotients are 2-groups.  Fill: L2. -/
theorem isPGroup_levelQuot
    (hfg : ∃ s : Finset G, (Subgroup.closure (s : Set G)).topologicalClosure = ⊤)
    (hpro : IsProP 2 G) (k : ℕ) : IsPGroup 2 (levelQuot G k) := by
  sorry

/-- **Neighborhood-basis / cofinality** (plan §2.1 item 2, §2.4): every open subgroup of a
topologically f.g. pro-2 group contains some `λₖ` (via: the finite 2-group `G/core` is
nilpotent with 2-central series reaching `1`).  This is the statement through which the
λ-tower levelwise data reaches *all* open normal subgroups in the assembly
(`GQ2/Roe/Labute/Assembly.lean`).  Fill: L2. -/
theorem exists_twoCentralSeries_le
    (hfg : ∃ s : Finset G, (Subgroup.closure (s : Set G)).topologicalClosure = ⊤)
    (hpro : IsProP 2 G) {U : Subgroup G} (hU : IsOpen (U : Set G)) :
    ∃ k, twoCentralSeries G k ≤ U := by
  sorry

/-- The tower separates points: `⨅ λₖ = ⊥` (plan §2.4's `⋂ λₖ = 1`).  Fill: L2. -/
theorem iInf_twoCentralSeries
    (hfg : ∃ s : Finset G, (Subgroup.closure (s : Set G)).topologicalClosure = ⊤)
    (hpro : IsProP 2 G) : ⨅ k, twoCentralSeries G k = ⊥ := by
  sorry

end Profinite

/-! ## Functoriality -/

section Functorial

variable {G H : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [Group H] [TopologicalSpace H] [IsTopologicalGroup H]

/-- One step of the series is functorial along a continuous homomorphism: if `φ` carries `A`
into `B`, it carries `cl(A²[A, G])` into `cl(B²[B, H])`. -/
theorem map_twoCentralSucc_le {A : Subgroup G} {B : Subgroup H} (φ : G →* H) (hφ : Continuous φ)
    (hAB : A.map φ ≤ B) : (twoCentralSucc A).map φ ≤ twoCentralSucc B := by
  set S : Subgroup G :=
    Subgroup.closure ((fun v : G => v ^ 2) '' (A : Set G)) ⊔ ⁅A, (⊤ : Subgroup G)⁆ with hSdef
  have hS : S.map φ ≤ twoCentralSucc B := by
    rw [hSdef, Subgroup.map_sup, MonoidHom.map_closure, Subgroup.map_commutator]
    refine sup_le (Subgroup.closure_le _ |>.2 ?_) ?_
    · rintro _ ⟨_, ⟨v, hv, rfl⟩, rfl⟩
      exact (map_pow φ v 2) ▸ sq_mem_twoCentralSucc (hAB ⟨v, hv, rfl⟩)
    · exact (Subgroup.commutator_mono hAB le_top).trans
        (le_sup_right.trans (Subgroup.le_topologicalClosure _))
  rintro _ ⟨x, hx, rfl⟩
  have hx' : φ x ∈ _root_.closure (φ '' (S : Set G)) :=
    image_closure_subset_closure_image hφ ⟨x, hx, rfl⟩
  refine closure_minimal ?_ (Subgroup.isClosed_topologicalClosure _) hx'
  rintro _ ⟨v, hv, rfl⟩
  exact hS ⟨v, hv, rfl⟩

/-- The series is verbal, hence functorial: a continuous homomorphism maps `λₖ` into `λₖ`.
Fill: L2. -/
theorem map_twoCentralSeries_le (φ : G →* H) (hφ : Continuous φ) (k : ℕ) :
    (twoCentralSeries G k).map φ ≤ twoCentralSeries H k := by
  induction k with
  | zero => exact le_top
  | succ k ih =>
    match k, ih with
    | 0, _ => exact le_top
    | (k + 1), ih => exact map_twoCentralSucc_le φ hφ ih

omit [IsTopologicalGroup G] [IsTopologicalGroup H] in
/-- The image of a closed subgroup of a compact group under a continuous homomorphism into a
Hausdorff group is closed. -/
theorem isClosed_map_of_isClosed [CompactSpace G] [T2Space H] {A : Subgroup G} (φ : G →* H)
    (hφ : Continuous φ) (hA : IsClosed (A : Set G)) :
    IsClosed ((A.map φ : Subgroup H) : Set H) :=
  (hA.isCompact.image hφ).isClosed

/-- Reverse containment for one step along a continuous epimorphism of a compact group onto a
Hausdorff group: `cl((φA)²[φA, H]) ≤ φ(cl(A²[A, G]))`. -/
theorem twoCentralSucc_map_le [CompactSpace G] [T2Space H] {A : Subgroup G} (φ : G →* H)
    (hφc : Continuous φ) (hφs : Function.Surjective φ) :
    twoCentralSucc (A.map φ) ≤ (twoCentralSucc A).map φ := by
  refine Subgroup.topologicalClosure_minimal _ (sup_le ?_ ?_)
    (isClosed_map_of_isClosed φ hφc (Subgroup.isClosed_topologicalClosure _))
  · refine Subgroup.closure_le _ |>.2 ?_
    rintro _ ⟨_, ⟨v, hv, rfl⟩, rfl⟩
    exact ⟨v ^ 2, sq_mem_twoCentralSucc hv, by rw [map_pow]⟩
  · rw [Subgroup.commutator_le]
    rintro _ ⟨v, hv, rfl⟩ w -
    obtain ⟨g, rfl⟩ := hφs w
    exact ⟨⁅v, g⁆, commutator_mem_twoCentralSucc hv g, map_commutatorElement φ v g⟩

/-- For a continuous **epimorphism** of a compact group onto a Hausdorff topological
group, the image of `λₖ` is exactly `λₖ` (verbal + closed map; the descent mechanism of
the span theorem, spike §2.3).  Fill: L2. -/
theorem map_twoCentralSeries_eq [CompactSpace G] [T2Space H]
    (φ : G →* H) (hφc : Continuous φ) (hφs : Function.Surjective φ) (k : ℕ) :
    (twoCentralSeries G k).map φ = twoCentralSeries H k := by
  refine le_antisymm (map_twoCentralSeries_le φ hφc k) ?_
  have htop : (⊤ : Subgroup G).map φ = ⊤ := Subgroup.map_top_of_surjective φ hφs
  induction k with
  | zero => exact htop.ge
  | succ k ih =>
    match k, ih with
    | 0, _ => exact htop.ge
    | (k + 1), ih =>
      exact (twoCentralSucc_mono ih).trans (twoCentralSucc_map_le φ hφc hφs)

end Functorial

/-! ## The χ-shadow layer (spike §2.7.5, §4.1)

The λ-series of `ℤ₂ˣ` sits inside the principal-unit filtration one step deeper than the
index (`λₖ(ℤ₂ˣ) = 1 + 2^{k+1}ℤ₂` for `k ≥ 2`; only `⊆` is frozen — the reverse inclusion
has no consumer).  Consequently every continuous character `χ : G → ℤ₂ˣ` has a level-`k`
shadow `Qₖ →* (ZMod 2^k)ˣ`: the invariant `P`'s χ-clause at modulus `2^k = 2^{m(k)}`
(spike §2.4) is stated through it. -/

section ChiShadow

/-- **The modulus lemma** (spike §2.4, "exact, elementary" — only the containment
direction is frozen): for `k ≥ 2`, `λₖ(ℤ₂ˣ) ⊆ 1 + 2^{k+1}ℤ₂`, encoded as the kernel of
the unit-group reduction mod `2^{k+1}`.  Fill: L2. -/
theorem twoCentralSeries_units_le (k : ℕ) (hk : 2 ≤ k) :
    twoCentralSeries ℤ_[2]ˣ k ≤
      (Units.map (PadicInt.toZModPow (k + 1)).toMonoidHom).ker := by
  sorry

variable {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- The λ-layers die in the mod-`2^k` shadow of any continuous character: for `g ∈ λₖ(G)`,
`χ g ≡ 1 (mod 2^k)`.  (For `k ≤ 1` the target `(ZMod 2^k)ˣ` is trivial; for `k ≥ 2` this
is `map_twoCentralSeries_le` + `twoCentralSeries_units_le` one precision step down.)
Fill: L2. -/
theorem chiShadow_eq_one_of_mem (χ : ContinuousMonoidHom G ℤ_[2]ˣ) (k : ℕ) {g : G}
    (hg : g ∈ twoCentralSeries G k) :
    Units.map (PadicInt.toZModPow k).toMonoidHom (χ g) = 1 := by
  sorry

/-- **The level-`k` χ-shadow** `χ̄ₖ : Qₖ →* (ZMod 2^k)ˣ` of a continuous character
`χ : G → ℤ₂ˣ` — precision `2^k`, the modulus `m(k) = k` of the invariant `P` (spike §2.4).
Total in `k` (no side condition): for `k ≤ 1` the target is trivial. -/
noncomputable def chiLevel (χ : ContinuousMonoidHom G ℤ_[2]ˣ) (k : ℕ) :
    levelQuot G k →* (ZMod (2 ^ k))ˣ :=
  QuotientGroup.lift (twoCentralSeries G k)
    ((Units.map (PadicInt.toZModPow k).toMonoidHom).comp χ.toMonoidHom)
    (fun _ hg => chiShadow_eq_one_of_mem χ k hg)

/-- Evaluation of the shadow on residues (smoke). -/
@[simp] theorem chiLevel_levelMk (χ : ContinuousMonoidHom G ℤ_[2]ˣ) (k : ℕ) (g : G) :
    chiLevel χ k (levelMk G k g) = Units.map (PadicInt.toZModPow k).toMonoidHom (χ g) :=
  rfl

/-- **Naturality of the shadows in `k`**: reading the level-`(k+1)` shadow mod `2^k`
recovers the level-`k` shadow through the tower projection.  (The mod-`2^{k+1}` clause of
`P` at level `k+1` *weakens* to the mod-`2^k` clause at level `k` — the restriction-map
direction of the levelwise sets.)  Fill: L2. -/
theorem chiLevel_levelProj (χ : ContinuousMonoidHom G ℤ_[2]ˣ) (k : ℕ)
    (q : levelQuot G (k + 1)) :
    chiLevel χ k (levelProj G k q) =
      Units.map (ZMod.castHom (pow_dvd_pow 2 (Nat.le_succ k)) (ZMod (2 ^ k))).toMonoidHom
        (chiLevel χ (k + 1) q) := by
  sorry

end ChiShadow

end GQ2.Roe.Labute
