/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-4.8 and Fable-5
-/
import Mathlib.Algebra.Group.Commutator
import Mathlib.GroupTheory.Commutator.Basic
import Mathlib.NumberTheory.Padics.RingHoms
import GQ2.MaxProP
import GQ2.Words

/-!
# The lower 2-central tower `λₖ` of a topological group  (L-campaign ticket L1/L2)

**Statements final (ticket L1); fills ticket L2.**  Design record:
`docs/orchestration/labute-l1-design.md`; mathematical sources: `docs/orchestration/
labute-plan.md` §2.4 (Tier F) and `docs/orchestration/labute-spike.md` §1, §2.1, §4.1.

The **lower exponent-2 central series** (Serre, Bourbaki 252, §6–7: `F₁ = F`,
`F_{i+1} = (F_i)² (F, F_i)`; the spike's λ-series) of a topological group `G`:

* `λ₁ = G`, `λ_{k+1} = cl(λₖ² [λₖ, G])` — `twoCentralSeries G k`, **1-based** to match the
  memos' numerology (`k₀ = 3`, `m(k) = k`, calculus threshold `k ≥ 3`, `2^{k-1}`-tails).
  The index `0` is a junk value (`λ₀ := ⊤`) so that every statement at `k ≥ 1` reads
  exactly as in the memos.  All layers are closed by construction.
* `Qₖ = G/λₖ` — `levelQuot G k`, with projections `levelProj : Q_{k+1} →* Qₖ`, the
  canonical (non-homomorphic) section `canonLift`, and the two-index images
  `lambdaImage G j k = λⱼλₖ/λₖ ≤ Qₖ`.
* `Zₖ = λₖ/λ_{k+1}` — `zLayer G k := lambdaImage G k (k+1) ≤ Q_{k+1}`, central and
  elementary abelian (spike §2.1).
* For topologically f.g. pro-2 `G`: each `λₖ` is open, each `Qₖ` a finite 2-group, the
  tower is a neighborhood basis of `1`, and `⨅ λₖ = ⊥` (plan §2.4).  The categorical
  limit statement `G ≅ lim G/λₖ` of plan §2.4 is deliberately **not** frozen here: no
  L-campaign consumer needs it (the assembly runs through the cofinality statement
  `exists_twoCentralSeries_le` + `GQ2/Reconstruction.lean`) — see the design memo §3.
* Functoriality: the series is verbal, so continuous homs map `λₖ` into `λₖ`, with
  equality for continuous epis of compact groups.
* The **χ-shadow layer** (spike §2.7.5, §4.1): `λₖ(ℤ₂ˣ) ⊆ 1 + 2^{k+1}ℤ₂` for `k ≥ 2`
  (`twoCentralSeries_units_le`, stated as containment in the kernel of reduction mod
  `2^{k+1}`), and for any continuous `χ : G → ℤ₂ˣ` the level shadow
  `chiLevel χ k : Qₖ →* (ZMod 2^k)ˣ` — precision `2^k`, the modulus of the invariant `P`
  (`m(k) = k`, spike §2.4).  The spike's finer shadow `χ̂ₖ` (precision `2^{k+1}` on `Qₖ`)
  is *not* a frozen definition; fills needing the extra digit build it locally from
  `twoCentralSeries_units_le` (design memo §4).

## Commutator conventions (board §10; read before filling)

Two commutator conventions coexist in this development, **deliberately**:

* **Repo convention** (`GQ2/Words.lean`): `commP x y = x⁻¹y⁻¹xy`, `conjP x g = g⁻¹xg`.
  Every *word-shape* statement of the campaign — the relators `drWord`/`d0Word`, the
  defect, the shift formulas `dbarWordR0`/`dbarWordR2` (`StageLemma.lean`), and all
  LS-memo tables — is in `commP` form; L3/L4 consume the spike's data with **no sign
  translation**.
* **Mathlib convention**: `⁅g, h⁆ = g*h*g⁻¹*h⁻¹` (scoped instance `commutatorElement`),
  and the subgroup-level `⁅H, K⁆`.  It appears in exactly one place: the generating set
  of `twoCentralSucc` uses `⁅H, ⊤⁆`, to inherit mathlib's commutator-subgroup API
  (`Subgroup.map_commutator` etc.) for the functoriality fills.

The two choices generate the same subgroups: `commP v g = ⁅v⁻¹, g⁻¹⁆`, so with `v` ranging
over a subgroup both families give the same step — the **translation lemma** is
`commP_mem_twoCentralSucc` below (proved, not sorried).  λ-series statements are
convention-independent; only element-level formulas care, and those are all `commP`.

Skeleton discipline: `sorry`s below are the L2 fill contract (exact inventory in the
design memo); the non-`sorry` lemmas are L1 smoke tests.
-/

namespace GQ2.Roe.Labute

open scoped commutatorElement

/-! ## The series -/

section Series

variable {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- One step of the lower 2-central series: `H ↦ cl(H²[H, G])`, the topological closure of
the subgroup generated by the squares of `H` and the commutators `[H, G]`.  (Serre 252 §6:
`F_{i+1} = (F_i)^q (F, F_i)` at `q = 2`; spike §1.)  Mathlib's commutator subgroup
`⁅H, ⊤⁆` is used; it agrees with the subgroup generated by the repo-convention commutators
`commP v g` (`commP_mem_twoCentralSucc` below). -/
def twoCentralSucc (H : Subgroup G) : Subgroup G :=
  (Subgroup.closure ((fun v : G => v ^ 2) '' (H : Set G)) ⊔ ⁅H, (⊤ : Subgroup G)⁆).topologicalClosure

/-- A square from `H` lies in `twoCentralSucc H`. -/
theorem sq_mem_twoCentralSucc {H : Subgroup G} {v : G} (hv : v ∈ H) :
    v ^ 2 ∈ twoCentralSucc H := by
  apply Subgroup.le_topologicalClosure
  exact Subgroup.mem_sup_left
    (Subgroup.subset_closure (Set.mem_image_of_mem (fun v : G => v ^ 2) hv))

/-- A mathlib-convention commutator `⁅v, g⁆` with `v ∈ H` lies in `twoCentralSucc H`. -/
theorem commutator_mem_twoCentralSucc {H : Subgroup G} {v : G} (hv : v ∈ H) (g : G) :
    ⁅v, g⁆ ∈ twoCentralSucc H := by
  apply Subgroup.le_topologicalClosure
  exact Subgroup.mem_sup_right
    (Subgroup.commutator_mem_commutator hv (Subgroup.mem_top g))

/-- **Convention bridge** (smoke): a repo-convention commutator `commP v g = v⁻¹g⁻¹vg`
(`GQ2/Words.lean`) with `v ∈ H` lies in `twoCentralSucc H` — so the generating sets of the
memos (stated with `commP`) and the mathlib bracket generate the same step. -/
theorem commP_mem_twoCentralSucc {H : Subgroup G} {v : G} (hv : v ∈ H) (g : G) :
    commP v g ∈ twoCentralSucc H := by
  have h : commP v g = ⁅v⁻¹, g⁻¹⁆ := by
    simp only [commP, commutatorElement_def, inv_inv]
  rw [h]
  exact commutator_mem_twoCentralSucc (H.inv_mem hv) g⁻¹

omit [TopologicalSpace G] [IsTopologicalGroup G] in
/-- The subgroup of squares of a normal subgroup is normal (`(gvg⁻¹)² = gv²g⁻¹`). -/
theorem sqClosure_normal {H : Subgroup G} (hH : H.Normal) :
    (Subgroup.closure ((fun v : G => v ^ 2) '' (H : Set G))).Normal := by
  constructor
  intro n hn g
  have hmap : Subgroup.map (MulAut.conj g).toMonoidHom
      (Subgroup.closure ((fun v : G => v ^ 2) '' (H : Set G))) ≤
      Subgroup.closure ((fun v : G => v ^ 2) '' (H : Set G)) := by
    rw [MonoidHom.map_closure]
    refine Subgroup.closure_le _ |>.2 ?_
    rintro _ ⟨_, ⟨v, hv, rfl⟩, rfl⟩
    exact Subgroup.subset_closure ⟨g * v * g⁻¹, hH.conj_mem v hv g, by simp⟩
  exact hmap ⟨n, hn, rfl⟩

omit [TopologicalSpace G] [IsTopologicalGroup G] in
/-- The generating subgroup `H²[H, G]` of one step, before taking the closure. -/
theorem twoCentralSuccGen_normal {H : Subgroup G} (hH : H.Normal) :
    (Subgroup.closure ((fun v : G => v ^ 2) '' (H : Set G)) ⊔ ⁅H, (⊤ : Subgroup G)⁆).Normal := by
  haveI := hH
  haveI := sqClosure_normal hH
  infer_instance

/-- One step of the series preserves normality. -/
theorem twoCentralSucc_normal {H : Subgroup G} (hH : H.Normal) : (twoCentralSucc H).Normal := by
  haveI := twoCentralSuccGen_normal hH
  exact Subgroup.is_normal_topologicalClosure _

/-- One step of the series is contained in its input, for a closed normal subgroup. -/
theorem twoCentralSucc_le {H : Subgroup G} (hH : H.Normal) (hc : IsClosed (H : Set G)) :
    twoCentralSucc H ≤ H := by
  haveI := hH
  refine Subgroup.topologicalClosure_minimal _ (sup_le ?_ (Subgroup.commutator_le_left _ _)) hc
  refine Subgroup.closure_le _ |>.2 ?_
  rintro _ ⟨v, hv, rfl⟩
  exact pow_mem hv 2

/-- One step of the series is monotone in its input. -/
theorem twoCentralSucc_mono {H K : Subgroup G} (h : H ≤ K) :
    twoCentralSucc H ≤ twoCentralSucc K :=
  Subgroup.topologicalClosure_mono
    (sup_le_sup (Subgroup.closure_mono (Set.image_mono h)) (Subgroup.commutator_mono h le_rfl))

end Series

section Tower

variable (G : Type*) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- The **lower 2-central series** `λₖ` of `G`, 1-based as in the memos:
`λ₁ = G`, `λ_{k+1} = cl(λₖ²[λₖ, G])` (`twoCentralSucc`).  Index `0` is a junk value
(`λ₀ := ⊤ = λ₁`); the recursion genuinely starts at `k = 1`, so `twoCentralSeries_succ`
below carries the hypothesis `1 ≤ k`. -/
def twoCentralSeries : ℕ → Subgroup G
  | 0 => ⊤
  | 1 => ⊤
  | (k + 2) => twoCentralSucc (twoCentralSeries (k + 1))

@[simp] theorem twoCentralSeries_zero : twoCentralSeries G 0 = ⊤ := rfl

@[simp] theorem twoCentralSeries_one : twoCentralSeries G 1 = ⊤ := rfl

/-- The defining recursion, valid from `k = 1` (at `k = 0` the junk convention breaks it). -/
theorem twoCentralSeries_succ {k : ℕ} (hk : 1 ≤ k) :
    twoCentralSeries G (k + 1) = twoCentralSucc (twoCentralSeries G k) := by
  match k, hk with
  | (k + 1), _ => rfl

/-- Every layer is closed (`λ₁ = G` and closures thereafter). -/
theorem isClosed_twoCentralSeries (k : ℕ) :
    IsClosed ((twoCentralSeries G k : Subgroup G) : Set G) := by
  match k with
  | 0 => exact isClosed_univ
  | 1 => exact isClosed_univ
  | (k + 2) => exact isClosed_closure

/-- Each `λₖ` is a normal subgroup (it is verbal: generated by the values of the words
`v²`, `[v, g]` over `λ_{k-1} × G`, a conjugation-stable family).  Fill: L2. -/
theorem twoCentralSeries_normal (k : ℕ) : (twoCentralSeries G k).Normal := by
  induction k with
  | zero => exact Subgroup.normal_top
  | succ k ih =>
    match k, ih with
    | 0, _ => exact Subgroup.normal_top
    | (k + 1), ih => exact twoCentralSucc_normal ih

instance (k : ℕ) : (twoCentralSeries G k).Normal := twoCentralSeries_normal G k

/-- The series is decreasing: `λ_{k+1} ≤ λₖ` and generally antitone.  Fill: L2. -/
theorem twoCentralSeries_antitone : Antitone (twoCentralSeries G) := by
  refine antitone_nat_of_succ_le fun k => ?_
  match k with
  | 0 => exact le_top
  | (k + 1) =>
    exact twoCentralSucc_le (twoCentralSeries_normal G (k + 1))
      (isClosed_twoCentralSeries G (k + 1))

/-- Squares of `λₖ` land in `λ_{k+1}` (also at the junk index `k = 0`, where `λ₁ = ⊤`). -/
theorem sq_mem_twoCentralSeries_succ {k : ℕ} {v : G} (hv : v ∈ twoCentralSeries G k) :
    v ^ 2 ∈ twoCentralSeries G (k + 1) := by
  match k with
  | 0 => exact Subgroup.mem_top _
  | (k + 1) => exact sq_mem_twoCentralSucc hv

/-- Commutators `⁅λₖ, G⁆` land in `λ_{k+1}` (also at the junk index `k = 0`). -/
theorem commutator_mem_twoCentralSeries_succ {k : ℕ} {v : G} (hv : v ∈ twoCentralSeries G k)
    (g : G) : ⁅v, g⁆ ∈ twoCentralSeries G (k + 1) := by
  match k with
  | 0 => exact Subgroup.mem_top _
  | (k + 1) => exact commutator_mem_twoCentralSucc hv g

end Tower

/-! ## The level quotients `Qₖ`, projections, and layer images -/

section Level

variable (G : Type*) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- The level-`k` quotient `Qₖ = G/λₖ` of the memos (finite for topologically f.g. pro-2
`G`, `finite_levelQuot`).  `Q₀ = Q₁ = 1` by the junk convention. -/
abbrev levelQuot (k : ℕ) : Type _ := G ⧸ twoCentralSeries G k

/-- The canonical projection `G →* Qₖ`. -/
def levelMk (k : ℕ) : G →* levelQuot G k :=
  QuotientGroup.mk' (twoCentralSeries G k)

theorem levelMk_surjective (k : ℕ) : Function.Surjective (levelMk G k) :=
  QuotientGroup.mk'_surjective _

/-- The tower projection `Q_{k+1} →* Qₖ` (along `λ_{k+1} ≤ λₖ`). -/
def levelProj (k : ℕ) : levelQuot G (k + 1) →* levelQuot G k :=
  QuotientGroup.map _ _ (MonoidHom.id G)
    (by simpa using twoCentralSeries_antitone G (Nat.le_succ k))

@[simp] theorem levelProj_levelMk (k : ℕ) (g : G) :
    levelProj G k (levelMk G (k + 1) g) = levelMk G k g := rfl

theorem levelProj_surjective (k : ℕ) : Function.Surjective (levelProj G k) := by
  intro q
  obtain ⟨g, rfl⟩ := levelMk_surjective G k q
  exact ⟨levelMk G (k + 1) g, rfl⟩

/-- A canonical set-theoretic section `Qₖ → Q_{k+1}` of `levelProj` (not a homomorphism);
the *canonical lift* through which the defect and the stage lemma are stated
(`GQ2/Roe/Labute/Levelwise.lean`, `StageLemma.lean`).  Lift-independence of everything
built from it is part of the frozen contract (`defectR0_eq_of_lift` etc.). -/
noncomputable def canonLift (k : ℕ) : levelQuot G k → levelQuot G (k + 1) :=
  Function.surjInv (levelProj_surjective G k)

@[simp] theorem levelProj_canonLift (k : ℕ) (q : levelQuot G k) :
    levelProj G k (canonLift G k q) = q :=
  Function.surjInv_eq (levelProj_surjective G k) q

/-- The image `λⱼλₖ/λₖ` of `λⱼ` in the level-`k` quotient `Qₖ` (interesting for `j < k`).
For `j = k - 1` these are the **modification spaces** of the stage calculus (spike §2.1). -/
def lambdaImage (j k : ℕ) : Subgroup (levelQuot G k) :=
  (twoCentralSeries G j).map (levelMk G k)

/-- Projections respect the layer images (smoke). -/
theorem levelProj_mem_lambdaImage {j k : ℕ} {q : levelQuot G (k + 1)}
    (hq : q ∈ lambdaImage G j (k + 1)) : levelProj G k q ∈ lambdaImage G j k := by
  obtain ⟨g, hg, rfl⟩ := hq
  exact ⟨g, hg, rfl⟩

/-- **The graded layer** `Zₖ = λₖ/λ_{k+1}`, realized as a subgroup of `Q_{k+1}` (the
encoding in which the defect, the shift formulas, and the span theorem are stated). -/
abbrev zLayer (k : ℕ) : Subgroup (levelQuot G (k + 1)) := lambdaImage G k (k + 1)

/-- `Zₖ` is exactly the kernel of the tower projection.  Fill: L2. -/
theorem zLayer_eq_ker_levelProj (k : ℕ) : zLayer G k = (levelProj G k).ker := by
  refine le_antisymm ?_ ?_
  · rintro _ ⟨x, hx, rfl⟩
    rw [MonoidHom.mem_ker, levelProj_levelMk]
    exact (QuotientGroup.eq_one_iff x).mpr hx
  · intro q hq
    obtain ⟨g, rfl⟩ := levelMk_surjective G (k + 1) q
    rw [MonoidHom.mem_ker, levelProj_levelMk] at hq
    exact ⟨g, (QuotientGroup.eq_one_iff g).mp hq, rfl⟩

/-- `Zₖ` is central in `Q_{k+1}` (spike §2.1: `[λₖ, G] ⊆ λ_{k+1}`).  Fill: L2. -/
theorem zLayer_le_center (k : ℕ) : zLayer G k ≤ Subgroup.center (levelQuot G (k + 1)) := by
  rintro _ ⟨v, hv, rfl⟩
  rw [Subgroup.mem_center_iff]
  intro q
  obtain ⟨h, rfl⟩ := levelMk_surjective G (k + 1) q
  have h1 : ⁅levelMk G (k + 1) v, levelMk G (k + 1) h⁆ = 1 := by
    rw [← map_commutatorElement]
    exact (QuotientGroup.eq_one_iff _).mpr (commutator_mem_twoCentralSeries_succ G hv h)
  exact (commutatorElement_eq_one_iff_mul_comm.mp h1).symm

/-- `Zₖ` is elementary abelian: every element squares to `1` (spike §2.1:
`λₖ² ⊆ λ_{k+1}`).  Fill: L2. -/
theorem zLayer_sq {k : ℕ} {z : levelQuot G (k + 1)} (hz : z ∈ zLayer G k) : z ^ 2 = 1 := by
  obtain ⟨v, hv, rfl⟩ := hz
  rw [← map_pow]
  exact (QuotientGroup.eq_one_iff _).mpr (sq_mem_twoCentralSeries_succ G hv)

/-- The residue of `g` in `Q_{k+1}` and the canonical lift of its residue in `Qₖ` differ by an
element of the central involutive layer `Zₖ`. -/
theorem levelMk_mul_canonLift_inv_mem_zLayer (k : ℕ) (g : G) :
    levelMk G (k + 1) g * (canonLift G k (levelMk G k g))⁻¹ ∈ zLayer G k := by
  rw [zLayer_eq_ker_levelProj, MonoidHom.mem_ker, map_mul, map_inv, levelProj_levelMk,
    levelProj_canonLift, mul_inv_cancel]

/-- Squaring in `Q_{k+1}` only depends on the class in `Qₖ` (`Zₖ` is central of exponent 2). -/
theorem sq_levelMk_eq_sq_canonLift (k : ℕ) (g : G) :
    levelMk G (k + 1) g ^ 2 = canonLift G k (levelMk G k g) ^ 2 := by
  set c := canonLift G k (levelMk G k g) with hc
  set z := levelMk G (k + 1) g * c⁻¹ with hz
  have hzm : z ∈ zLayer G k := levelMk_mul_canonLift_inv_mem_zLayer G k g
  have hzc : c * z = z * c := Subgroup.mem_center_iff.mp (zLayer_le_center G k hzm) c
  have hg : levelMk G (k + 1) g = z * c := by rw [hz, inv_mul_cancel_right]
  rw [hg, sq, sq]
  calc z * c * (z * c) = z * (c * z) * c := by group
    _ = z * (z * c) * c := by rw [hzc]
    _ = z ^ 2 * (c * c) := by rw [sq]; group
    _ = c * c := by rw [zLayer_sq G hzm, one_mul]

/-- Commutators in `Q_{k+1}` with a fixed second slot only depend on the class in `Qₖ`. -/
theorem commutator_levelMk_eq_commutator_canonLift (k : ℕ) (g : G) (y : levelQuot G (k + 1)) :
    ⁅levelMk G (k + 1) g, y⁆ = ⁅canonLift G k (levelMk G k g), y⁆ := by
  set c := canonLift G k (levelMk G k g) with hc
  set z := levelMk G (k + 1) g * c⁻¹ with hz
  have hzm : z ∈ zLayer G k := levelMk_mul_canonLift_inv_mem_zLayer G k g
  have hzc : ∀ w : levelQuot G (k + 1), w * z = z * w := fun w =>
    Subgroup.mem_center_iff.mp (zLayer_le_center G k hzm) w
  have hg : levelMk G (k + 1) g = z * c := by rw [hz, inv_mul_cancel_right]
  rw [hg, commutatorElement_def, commutatorElement_def]
  calc z * c * y * (z * c)⁻¹ * y⁻¹ = z * (c * y * c⁻¹) * z⁻¹ * y⁻¹ := by group
    _ = c * y * c⁻¹ * z * z⁻¹ * y⁻¹ := by rw [← hzc (c * y * c⁻¹)]
    _ = c * y * c⁻¹ * y⁻¹ := by group

end Level

/-! ## Finitely generated elementary abelian subgroups -/

section CentralInvolutions

variable {T : Type*} [Group T]

/-- The subgroup generated by finitely many central involutions is finite. -/
theorem finite_closure_of_central_sq {K : Subgroup T} (hKc : K ≤ Subgroup.center T)
    (hK2 : ∀ z ∈ K, z ^ 2 = 1) :
    ∀ F : Finset T, (F : Set T) ⊆ (K : Set T) →
      ((Subgroup.closure (F : Set T) : Subgroup T) : Set T).Finite := by
  classical
  intro F
  induction F using Finset.induction_on with
  | empty => intro _; simp
  | insert a F ha ih =>
    intro hsub
    have haK : a ∈ K := hsub (by simp)
    have hFK : (F : Set T) ⊆ (K : Set T) := fun x hx => hsub (by simp [hx])
    have hclos : Subgroup.closure (F : Set T) ≤ K := (Subgroup.closure_le K).2 hFK
    haveI : (Subgroup.closure (F : Set T)).Normal := by
      constructor
      intro n hn g
      rw [Subgroup.mem_center_iff.mp (hKc (hclos hn)) g, mul_inv_cancel_right]
      exact hn
    have hsingle : ((Subgroup.closure ({a} : Set T) : Subgroup T) : Set T).Finite := by
      rw [← Subgroup.zpowers_eq_closure]
      exact _root_.finite_zpowers.2 (isOfFinOrder_iff_pow_eq_one.2 ⟨2, two_pos, hK2 a haK⟩)
    have hins : ((insert a F : Finset T) : Set T) = ({a} : Set T) ∪ (F : Set T) := by simp
    rw [hins, Subgroup.closure_union, Subgroup.mul_normal]
    exact hsingle.mul (ih hFK)

end CentralInvolutions

/-! ## Functoriality -/

section Functorial

variable {G H : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [Group H] [TopologicalSpace H] [IsTopologicalGroup H]

/-- One step of the series is functorial along a continuous homomorphism: if `φ` carries `A`
into `B`, it carries `cl(A²[A, G])` into `cl(B²[B, H])`. -/
theorem map_twoCentralSucc_le {A : Subgroup G} {B : Subgroup H} (φ : G →* H) (hφ : Continuous φ)
    (hAB : A.map φ ≤ B) : (twoCentralSucc A).map φ ≤ twoCentralSucc B := by
  set S : Subgroup G :=
    Subgroup.closure ((fun v : G => v ^ 2) '' (A : Set G)) ⊔ ⁅A, (⊤ : Subgroup G)⁆ with hSdef
  have hS : S.map φ ≤ twoCentralSucc B := by
    rw [hSdef, Subgroup.map_sup, MonoidHom.map_closure, Subgroup.map_commutator]
    refine sup_le (Subgroup.closure_le _ |>.2 ?_) ?_
    · rintro _ ⟨_, ⟨v, hv, rfl⟩, rfl⟩
      exact (map_pow φ v 2) ▸ sq_mem_twoCentralSucc (hAB ⟨v, hv, rfl⟩)
    · exact (Subgroup.commutator_mono hAB le_top).trans
        (le_sup_right.trans (Subgroup.le_topologicalClosure _))
  rintro _ ⟨x, hx, rfl⟩
  have hx' : φ x ∈ _root_.closure (φ '' (S : Set G)) :=
    image_closure_subset_closure_image hφ ⟨x, hx, rfl⟩
  refine closure_minimal ?_ (Subgroup.isClosed_topologicalClosure _) hx'
  rintro _ ⟨v, hv, rfl⟩
  exact hS ⟨v, hv, rfl⟩

/-- The series is verbal, hence functorial: a continuous homomorphism maps `λₖ` into `λₖ`.
Fill: L2. -/
theorem map_twoCentralSeries_le (φ : G →* H) (hφ : Continuous φ) (k : ℕ) :
    (twoCentralSeries G k).map φ ≤ twoCentralSeries H k := by
  induction k with
  | zero => exact le_top
  | succ k ih =>
    match k, ih with
    | 0, _ => exact le_top
    | (k + 1), ih => exact map_twoCentralSucc_le φ hφ ih

omit [IsTopologicalGroup G] [IsTopologicalGroup H] in
/-- The image of a closed subgroup of a compact group under a continuous homomorphism into a
Hausdorff group is closed. -/
theorem isClosed_map_of_isClosed [CompactSpace G] [T2Space H] {A : Subgroup G} (φ : G →* H)
    (hφ : Continuous φ) (hA : IsClosed (A : Set G)) :
    IsClosed ((A.map φ : Subgroup H) : Set H) :=
  (hA.isCompact.image hφ).isClosed

/-- Reverse containment for one step along a continuous epimorphism of a compact group onto a
Hausdorff group: `cl((φA)²[φA, H]) ≤ φ(cl(A²[A, G]))`. -/
theorem twoCentralSucc_map_le [CompactSpace G] [T2Space H] {A : Subgroup G} (φ : G →* H)
    (hφc : Continuous φ) (hφs : Function.Surjective φ) :
    twoCentralSucc (A.map φ) ≤ (twoCentralSucc A).map φ := by
  refine Subgroup.topologicalClosure_minimal _ (sup_le ?_ ?_)
    (isClosed_map_of_isClosed φ hφc (Subgroup.isClosed_topologicalClosure _))
  · refine Subgroup.closure_le _ |>.2 ?_
    rintro _ ⟨_, ⟨v, hv, rfl⟩, rfl⟩
    exact ⟨v ^ 2, sq_mem_twoCentralSucc hv, by rw [map_pow]⟩
  · rw [Subgroup.commutator_le]
    rintro _ ⟨v, hv, rfl⟩ w -
    obtain ⟨g, rfl⟩ := hφs w
    exact ⟨⁅v, g⁆, commutator_mem_twoCentralSucc hv g, map_commutatorElement φ v g⟩

/-- For a continuous **epimorphism** of a compact group onto a Hausdorff topological
group, the image of `λₖ` is exactly `λₖ` (verbal + closed map; the descent mechanism of
the span theorem, spike §2.3).  Fill: L2. -/
theorem map_twoCentralSeries_eq [CompactSpace G] [T2Space H]
    (φ : G →* H) (hφc : Continuous φ) (hφs : Function.Surjective φ) (k : ℕ) :
    (twoCentralSeries G k).map φ = twoCentralSeries H k := by
  refine le_antisymm (map_twoCentralSeries_le φ hφc k) ?_
  have htop : (⊤ : Subgroup G).map φ = ⊤ := Subgroup.map_top_of_surjective φ hφs
  induction k with
  | zero => exact htop.ge
  | succ k ih =>
    match k, ih with
    | 0, _ => exact htop.ge
    | (k + 1), ih =>
      exact (twoCentralSucc_mono ih).trans (twoCentralSucc_map_le φ hφc hφs)

end Functorial

/-! ## Finite 2-groups: the tower reaches the trivial subgroup -/

section FiniteTwoGroup

/-- One step past a central subgroup of exponent 2 is trivial. -/
theorem twoCentralSucc_eq_bot_of_le_center {Q : Type*} [Group Q] [TopologicalSpace Q]
    [IsTopologicalGroup Q] [T1Space Q] {N : Subgroup Q} (hNc : N ≤ Subgroup.center Q)
    (hN2 : ∀ x ∈ N, x ^ 2 = 1) : twoCentralSucc N = ⊥ := by
  refine le_antisymm (Subgroup.topologicalClosure_minimal _ (sup_le ?_ ?_) ?_) bot_le
  · refine (Subgroup.closure_le _).2 ?_
    rintro _ ⟨v, hv, rfl⟩
    exact (Subgroup.mem_bot).2 (hN2 v hv)
  · rw [Subgroup.commutator_le]
    intro a ha b _
    refine (Subgroup.mem_bot).2 ?_
    exact commutatorElement_eq_one_iff_mul_comm.2 (Subgroup.mem_center_iff.mp (hNc ha) b).symm
  · simp only [Subgroup.coe_bot]
    exact isClosed_singleton

/-- **The tower of a finite discrete 2-group reaches `⊥`.**  Induction on the order: a nontrivial
finite 2-group has a central involution `w`; the tower of `Q ⧸ ⟨w⟩` reaches `⊥`, so the tower of
`Q` reaches `⟨w⟩` (central of exponent 2) and one further step kills it. -/
theorem exists_twoCentralSeries_eq_bot_aux (n : ℕ) : ∀ (Q : Type*) [Group Q] [TopologicalSpace Q]
    [IsTopologicalGroup Q] [DiscreteTopology Q] [Finite Q], IsPGroup 2 Q → Nat.card Q ≤ n →
    ∃ k, twoCentralSeries Q k = ⊥ := by
  induction n with
  | zero =>
    intro Q _ _ _ _ _ _ hcard
    exact absurd hcard (by simp [Nat.card_pos.ne'])
  | succ n ih =>
    intro Q _ _ _ _ _ hQ hcard
    rcases subsingleton_or_nontrivial Q with hs | hs
    · exact ⟨0, by ext x; simp [Subsingleton.elim x (1 : Q)]⟩
    -- a central involution
    classical
    obtain ⟨z, hzc, hz1⟩ : ∃ z : Q, z ∈ Subgroup.center Q ∧ z ≠ 1 := by
      haveI := hQ.center_nontrivial
      obtain ⟨⟨z, hzc⟩, hz1⟩ := exists_ne (1 : Subgroup.center Q)
      exact ⟨z, hzc, fun h => hz1 (Subtype.ext h)⟩
    have hex : ∃ m : ℕ, z ^ 2 ^ m = 1 := hQ z
    set m := Nat.find hex with hm
    have hmspec : z ^ 2 ^ m = 1 := Nat.find_spec hex
    have hmpos : 0 < m := Nat.pos_of_ne_zero fun h0 => hz1 (by simpa [h0] using hmspec)
    set w := z ^ 2 ^ (m - 1) with hw
    have hw1 : w ≠ 1 := Nat.find_min hex (by omega)
    have hw2 : w ^ 2 = 1 := by
      rw [hw, ← pow_mul, ← pow_succ, show m - 1 + 1 = m by omega]; exact hmspec
    have hwc : w ∈ Subgroup.center Q := pow_mem hzc _
    set N : Subgroup Q := Subgroup.zpowers w with hN
    have hNc : N ≤ Subgroup.center Q := Subgroup.zpowers_le.2 hwc
    have hN2 : ∀ x ∈ N, x ^ 2 = 1 := by
      rintro _ ⟨j, rfl⟩
      have hj : (w ^ j) ^ (2 : ℕ) = (w ^ (2 : ℕ)) ^ j := by
        rw [← zpow_natCast (w ^ j) 2, ← zpow_natCast w 2, ← zpow_mul, ← zpow_mul, mul_comm]
      rw [hj, hw2, one_zpow]
    haveI : N.Normal := ⟨fun x hx g => by
      rw [Subgroup.mem_center_iff.mp (hNc hx) g, mul_inv_cancel_right]; exact hx⟩
    haveI : DiscreteTopology (Q ⧸ N) := QuotientGroup.discreteTopology (isOpen_discrete _)
    -- the quotient is strictly smaller
    have hcard' : Nat.card (Q ⧸ N) ≤ n := by
      have h1 : Nat.card N * N.index = Nat.card Q := Subgroup.card_mul_index N
      haveI : Nontrivial N :=
        ⟨⟨⟨w, Subgroup.mem_zpowers w⟩, 1, fun h => hw1 (Subtype.ext_iff.1 h)⟩⟩
      have h2 : 2 ≤ Nat.card N := Finite.one_lt_card_iff_nontrivial.2 inferInstance
      have h3 : 0 < N.index := Nat.pos_of_ne_zero N.index_ne_zero_of_finite
      have h4 : 2 * N.index ≤ Nat.card N * N.index := Nat.mul_le_mul_right _ h2
      rw [← Subgroup.index_eq_card]
      omega
    obtain ⟨k, hk⟩ := ih (Q ⧸ N) (hQ.to_quotient N) hcard'
    have hkN : twoCentralSeries Q (k + 1) ≤ N := by
      have hmap : (twoCentralSeries Q (k + 1)).map (QuotientGroup.mk' N) ≤
          twoCentralSeries (Q ⧸ N) (k + 1) :=
        map_twoCentralSeries_le (QuotientGroup.mk' N) QuotientGroup.continuous_mk (k + 1)
      have hbot : twoCentralSeries (Q ⧸ N) (k + 1) = ⊥ :=
        le_antisymm (hk ▸ twoCentralSeries_antitone (Q ⧸ N) (Nat.le_succ k)) bot_le
      rw [hbot, le_bot_iff, Subgroup.map_eq_bot_iff, QuotientGroup.ker_mk'] at hmap
      exact hmap
    refine ⟨k + 2, le_antisymm ?_ bot_le⟩
    rw [twoCentralSeries_succ Q (Nat.le_add_left 1 k)]
    exact (twoCentralSucc_mono hkN).trans
      (le_of_eq (twoCentralSucc_eq_bot_of_le_center hNc hN2))

/-- **The tower of a finite discrete 2-group reaches `⊥`.** -/
theorem exists_twoCentralSeries_eq_bot (Q : Type*) [Group Q] [TopologicalSpace Q]
    [IsTopologicalGroup Q] [DiscreteTopology Q] [Finite Q] (hQ : IsPGroup 2 Q) :
    ∃ k, twoCentralSeries Q k = ⊥ :=
  exists_twoCentralSeries_eq_bot_aux (Nat.card Q) Q hQ le_rfl

end FiniteTwoGroup

/-! ## Openness, finiteness, and the neighborhood basis (topologically f.g. pro-2 `G`) -/

section Profinite

variable (G : Type*) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G]

omit [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G] in
/-- `Q_{k+1}` embeds into `Qₖ × Zₖ`, so it is finite as soon as both factors are. -/
theorem finite_levelQuot_succ (k : ℕ) (h1 : Finite (levelQuot G k)) (h2 : Finite (zLayer G k)) :
    Finite (levelQuot G (k + 1)) := by
  have hmem : ∀ x : levelQuot G (k + 1),
      x * (canonLift G k (levelProj G k x))⁻¹ ∈ zLayer G k := by
    intro x
    rw [zLayer_eq_ker_levelProj, MonoidHom.mem_ker, map_mul, map_inv, levelProj_canonLift,
      mul_inv_cancel]
  refine Finite.of_injective
    (fun x : levelQuot G (k + 1) => (levelProj G k x, (⟨_, hmem x⟩ : zLayer G k))) ?_
  intro x y hxy
  simp only [Prod.mk.injEq, Subtype.mk.injEq] at hxy
  obtain ⟨hp, hz⟩ := hxy
  rw [hp] at hz
  exact mul_right_cancel hz

omit [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G] in
/-- A subgroup of `Q_{k+1}` generated by a finite subset of the layer `Zₖ` is finite. -/
theorem finite_closure_subset_zLayer (k : ℕ) {F : Set (levelQuot G (k + 1))} (hFfin : F.Finite)
    (hFZ : F ⊆ (zLayer G k : Set (levelQuot G (k + 1)))) :
    ((Subgroup.closure F : Subgroup (levelQuot G (k + 1))) : Set (levelQuot G (k + 1))).Finite := by
  have h := finite_closure_of_central_sq (zLayer_le_center G k) (fun _ hz => zLayer_sq G hz)
    hFfin.toFinset (by simpa using hFZ)
  simpa using h

omit [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G] in
/-- A subgroup generated by a finite subset of `Zₖ` is closed in `Q_{k+1}`. -/
theorem isClosed_closure_subset_zLayer (k : ℕ) {F : Set (levelQuot G (k + 1))} (hFfin : F.Finite)
    (hFZ : F ⊆ (zLayer G k : Set (levelQuot G (k + 1)))) :
    IsClosed ((Subgroup.closure F : Subgroup (levelQuot G (k + 1))) :
      Set (levelQuot G (k + 1))) := by
  haveI : IsClosed ((twoCentralSeries G (k + 1) : Subgroup G) : Set G) :=
    isClosed_twoCentralSeries G (k + 1)
  exact (finite_closure_subset_zLayer G k hFfin hFZ).isClosed

omit [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G] in
/-- The preimage in `G` of a subgroup generated by a finite subset of `Zₖ` is closed. -/
theorem isClosed_comap_closure_zLayer (k : ℕ) {F : Set (levelQuot G (k + 1))} (hFfin : F.Finite)
    (hFZ : F ⊆ (zLayer G k : Set (levelQuot G (k + 1)))) :
    IsClosed ((Subgroup.comap (levelMk G (k + 1)) (Subgroup.closure F) : Subgroup G) : Set G) :=
  (isClosed_closure_subset_zLayer G k hFfin hFZ).preimage QuotientGroup.continuous_mk

omit [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G] in
/-- Transfer a containment of `λₖ` in a preimage to a containment of the layer `Zₖ`. -/
theorem zLayer_le_of_le_comap (k : ℕ) {K : Subgroup (levelQuot G (k + 1))}
    (h : twoCentralSeries G k ≤ Subgroup.comap (levelMk G (k + 1)) K) : zLayer G k ≤ K := by
  rintro _ ⟨v, hv, rfl⟩
  exact h hv

omit [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G] in
/-- For `v ∈ λₖ`, the values `⁅v, g⁆ mod λ_{k+2}` lie in the central layer `Z_{k+1}`. -/
theorem commutator_levelMk_mem_zLayer {k : ℕ} {v : G} (hv : v ∈ twoCentralSeries G k) (g : G) :
    levelMk G (k + 2) ⁅v, g⁆ ∈ zLayer G (k + 1) :=
  ⟨⁅v, g⁆, commutator_mem_twoCentralSeries_succ G hv g, rfl⟩

omit [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G] in
/-- Bilinearity of the commutator modulo `λ_{k+2}`: for `v ∈ λₖ` the map `g ↦ ⁅v, g⁆ mod λ_{k+2}`
is a homomorphism, because its values are central in `Q_{k+2}`. -/
theorem commLayerHom_mul {k : ℕ} {v : G} (hv : v ∈ twoCentralSeries G k) (a b : G) :
    levelMk G (k + 2) ⁅v, a * b⁆ = levelMk G (k + 2) ⁅v, a⁆ * levelMk G (k + 2) ⁅v, b⁆ := by
  have hcen := zLayer_le_center G (k + 1) (commutator_levelMk_mem_zLayer G hv b)
  rw [show ⁅v, a * b⁆ = ⁅v, a⁆ * (a * ⁅v, b⁆ * a⁻¹) by group, map_mul, map_mul, map_mul, map_inv,
    Subgroup.mem_center_iff.mp hcen (levelMk G (k + 2) a), mul_inv_cancel_right]

/-- The homomorphism `g ↦ ⁅v, g⁆ mod λ_{k+2}` attached to `v ∈ λₖ`. -/
def commLayerHom {k : ℕ} {v : G} (hv : v ∈ twoCentralSeries G k) : G →* levelQuot G (k + 2) :=
  MonoidHom.mk' (fun h => levelMk G (k + 2) ⁅v, h⁆) (commLayerHom_mul G hv)

omit [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G] in
@[simp] theorem commLayerHom_apply {k : ℕ} {v : G} (hv : v ∈ twoCentralSeries G k) (g : G) :
    commLayerHom G hv g = levelMk G (k + 2) ⁅v, g⁆ := rfl

omit [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G] in
theorem continuous_commLayerHom {k : ℕ} {v : G} (hv : v ∈ twoCentralSeries G k) :
    Continuous (commLayerHom G hv) := by
  have h : Continuous fun g : G => ⁅v, g⁆ := by
    simp only [commutatorElement_def]
    fun_prop
  exact QuotientGroup.continuous_mk.comp h

omit [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G] in
/-- Base of the finiteness induction: `Q₂ = G/λ₂` is generated by the residues of a topological
generating set, and is abelian of exponent 2, hence finite. -/
theorem finite_levelQuot_two
    (hfg : ∃ s : Finset G, (Subgroup.closure (s : Set G)).topologicalClosure = ⊤) :
    Finite (levelQuot G 2) := by
  obtain ⟨s, hs⟩ := hfg
  set F : Set (levelQuot G 2) := levelMk G 2 '' (s : Set G) with hF
  have hFfin : F.Finite := s.finite_toSet.image _
  have hFZ : F ⊆ (zLayer G 1 : Set (levelQuot G 2)) := by
    rintro _ ⟨x, _, rfl⟩
    exact ⟨x, Subgroup.mem_top x, rfl⟩
  have hgen : twoCentralSeries G 1 ≤ Subgroup.comap (levelMk G 2) (Subgroup.closure F) := by
    rw [show twoCentralSeries G 1 = (⊤ : Subgroup G) from rfl, ← hs]
    refine Subgroup.topologicalClosure_minimal _ ((Subgroup.closure_le _).2 fun x hx => ?_)
      (isClosed_comap_closure_zLayer G 1 hFfin hFZ)
    exact Subgroup.subset_closure ⟨x, hx, rfl⟩
  haveI : Subsingleton (levelQuot G 1) := QuotientGroup.subsingleton_quotient_top
  refine finite_levelQuot_succ G 1 ?_ ?_
  · exact Finite.of_subsingleton
  · exact ((finite_closure_subset_zLayer G 1 hFfin hFZ).subset
      (zLayer_le_of_le_comap G 1 hgen)).to_subtype

omit [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G] in
/-- Inductive step of the finiteness statement (`k ≥ 1`): the layer `Z_{k+1}` is generated by the
finitely many square- and commutator-classes coming from `Q_{k+1}` and the generating set. -/
theorem finite_levelQuot_step
    (hfg : ∃ s : Finset G, (Subgroup.closure (s : Set G)).topologicalClosure = ⊤)
    {k : ℕ} (hk : 1 ≤ k) (h : Finite (levelQuot G (k + 1))) : Finite (levelQuot G (k + 2)) := by
  obtain ⟨s, hs⟩ := hfg
  haveI := h
  set f₁ : levelQuot G (k + 1) → levelQuot G (k + 2) :=
    fun q => canonLift G (k + 1) q ^ 2 with hf₁
  set f₂ : levelQuot G (k + 1) × (s : Set G) → levelQuot G (k + 2) :=
    fun p => ⁅canonLift G (k + 1) p.1, levelMk G (k + 2) (p.2 : G)⁆ with hf₂
  set F : Set (levelQuot G (k + 2)) :=
    (Set.range f₁ ∪ Set.range f₂) ∩ (zLayer G (k + 1) : Set (levelQuot G (k + 2))) with hF
  set K : Subgroup (levelQuot G (k + 2)) := Subgroup.closure F with hK
  have hFfin : F.Finite :=
    ((Set.finite_range f₁).union (Set.finite_range f₂)).subset Set.inter_subset_left
  have hFZ : F ⊆ (zLayer G (k + 1) : Set (levelQuot G (k + 2))) := Set.inter_subset_right
  have hcl := isClosed_comap_closure_zLayer G (k + 1) hFfin hFZ
  have hgen : twoCentralSeries G (k + 1) ≤ Subgroup.comap (levelMk G (k + 2)) K := by
    rw [twoCentralSeries_succ G hk]
    refine Subgroup.topologicalClosure_minimal _ (sup_le ?_ ?_) hcl
    · refine (Subgroup.closure_le _).2 ?_
      rintro _ ⟨v, hv, rfl⟩
      rw [SetLike.mem_coe, Subgroup.mem_comap]
      refine Subgroup.subset_closure ⟨Or.inl ⟨levelMk G (k + 1) v, ?_⟩, ?_⟩
      · simp only [hf₁]
        rw [← sq_levelMk_eq_sq_canonLift G (k + 1) v, map_pow]
      · exact ⟨v ^ 2, sq_mem_twoCentralSeries_succ G hv, rfl⟩
    · rw [Subgroup.commutator_le]
      intro v hv g _
      have hcomm : (⊤ : Subgroup G) ≤
          Subgroup.comap (commLayerHom G hv) (Subgroup.closure F) := by
        rw [← hs]
        refine Subgroup.topologicalClosure_minimal _ ((Subgroup.closure_le _).2 fun x hx => ?_)
          ((isClosed_closure_subset_zLayer G (k + 1) hFfin hFZ).preimage
            (continuous_commLayerHom G hv))
        rw [SetLike.mem_coe, Subgroup.mem_comap, commLayerHom_apply]
        refine Subgroup.subset_closure ⟨Or.inr ⟨(levelMk G (k + 1) v, ⟨x, hx⟩), ?_⟩, ?_⟩
        · simp only [hf₂]
          rw [← commutator_levelMk_eq_commutator_canonLift G (k + 1) v, ← map_commutatorElement]
        · exact commutator_levelMk_mem_zLayer G hv x
      have hg := hcomm (Subgroup.mem_top g)
      rw [Subgroup.mem_comap, commLayerHom_apply] at hg
      rw [Subgroup.mem_comap, hK]
      exact hg
  exact finite_levelQuot_succ G (k + 1) h
    (((finite_closure_subset_zLayer G (k + 1) hFfin hFZ).subset
      (zLayer_le_of_le_comap G (k + 1) hgen)).to_subtype)

/-- The level quotients of a topologically f.g. pro-2 group are finite.  Fill: L2. -/
theorem finite_levelQuot
    (hfg : ∃ s : Finset G, (Subgroup.closure (s : Set G)).topologicalClosure = ⊤)
    (hpro : IsProP 2 G) (k : ℕ) : Finite (levelQuot G k) := by
  have _ := hpro
  -- the profinite pack is part of the frozen interface (design memo §3.7): retained even where
  -- the fill does not need it
  have _ := ‹CompactSpace G›
  have _ := ‹T2Space G›
  have _ := ‹TotallyDisconnectedSpace G›
  match k with
  | 0 =>
    haveI : Subsingleton (levelQuot G 0) := QuotientGroup.subsingleton_quotient_top
    exact Finite.of_subsingleton
  | 1 =>
    haveI : Subsingleton (levelQuot G 1) := QuotientGroup.subsingleton_quotient_top
    exact Finite.of_subsingleton
  | (k + 2) =>
    induction k with
    | zero => exact finite_levelQuot_two G hfg
    | succ k ih => exact finite_levelQuot_step G hfg (Nat.le_add_left 1 k) ih

/-- For a topologically finitely generated pro-2 group, every `λₖ` is open.  (Openness at
each step: `λₖ/λ_{k+1}` is generated by finitely many square/commutator classes of
exponent 2 — plan §2.4.)  Fill: L2. -/
theorem isOpen_twoCentralSeries
    (hfg : ∃ s : Finset G, (Subgroup.closure (s : Set G)).topologicalClosure = ⊤)
    (hpro : IsProP 2 G) (k : ℕ) : IsOpen ((twoCentralSeries G k : Subgroup G) : Set G) := by
  -- the profinite pack is part of the frozen interface (design memo §3.7): retained even where
  -- the fill does not need it
  have _ := ‹CompactSpace G›
  have _ := ‹T2Space G›
  have _ := ‹TotallyDisconnectedSpace G›
  haveI := finite_levelQuot G hfg hpro k
  haveI : (twoCentralSeries G k).FiniteIndex :=
    ⟨by simpa [Subgroup.index] using Nat.card_pos.ne'⟩
  exact (twoCentralSeries G k).isOpen_of_isClosed_of_finiteIndex (isClosed_twoCentralSeries G k)

/-- The level quotients are 2-groups.  Fill: L2. -/
theorem isPGroup_levelQuot
    (hfg : ∃ s : Finset G, (Subgroup.closure (s : Set G)).topologicalClosure = ⊤)
    (hpro : IsProP 2 G) (k : ℕ) : IsPGroup 2 (levelQuot G k) := by
  -- the profinite pack is part of the frozen interface (design memo §3.7): retained even where
  -- the fill does not need it
  have _ := ‹CompactSpace G›
  have _ := ‹T2Space G›
  have _ := ‹TotallyDisconnectedSpace G›
  have hopen := isOpen_twoCentralSeries G hfg hpro k
  exact hpro { toSubgroup := twoCentralSeries G k, isOpen' := hopen }

/-- **Neighborhood-basis / cofinality** (plan §2.1 item 2, §2.4): every open subgroup of a
topologically f.g. pro-2 group contains some `λₖ` (via: the finite 2-group `G/core` is
nilpotent with 2-central series reaching `1`).  This is the statement through which the
λ-tower levelwise data reaches *all* open normal subgroups in the assembly
(`GQ2/Roe/Labute/Assembly.lean`).  Fill: L2. -/
theorem exists_twoCentralSeries_le
    (hfg : ∃ s : Finset G, (Subgroup.closure (s : Set G)).topologicalClosure = ⊤)
    (hpro : IsProP 2 G) {U : Subgroup G} (hU : IsOpen (U : Set G)) :
    ∃ k, twoCentralSeries G k ≤ U := by
  have _ := hfg
  have _ := ‹T2Space G›
  obtain ⟨V, hVU⟩ := ProfiniteGrp.exist_openNormalSubgroup_sub_open_nhds_of_one hU (one_mem U)
  haveI : DiscreteTopology (G ⧸ V.toSubgroup) :=
    QuotientGroup.discreteTopology V.toOpenSubgroup.isOpen
  haveI : Finite (G ⧸ V.toSubgroup) := finite_of_compact_of_discrete
  obtain ⟨k, hk⟩ := exists_twoCentralSeries_eq_bot (G ⧸ V.toSubgroup) (hpro V)
  refine ⟨k, ?_⟩
  have hmap : (twoCentralSeries G k).map (QuotientGroup.mk' V.toSubgroup) ≤
      twoCentralSeries (G ⧸ V.toSubgroup) k :=
    map_twoCentralSeries_le _ QuotientGroup.continuous_mk k
  rw [hk, le_bot_iff, Subgroup.map_eq_bot_iff, QuotientGroup.ker_mk'] at hmap
  exact hmap.trans fun x hx => hVU hx

/-- The tower separates points: `⨅ λₖ = ⊥` (plan §2.4's `⋂ λₖ = 1`).  Fill: L2. -/
theorem iInf_twoCentralSeries
    (hfg : ∃ s : Finset G, (Subgroup.closure (s : Set G)).topologicalClosure = ⊤)
    (hpro : IsProP 2 G) : ⨅ k, twoCentralSeries G k = ⊥ := by
  refine le_antisymm (fun x hx => ?_) bot_le
  rw [Subgroup.mem_iInf] at hx
  refine (Subgroup.mem_bot).2 (eq_one_of_forall_mem_openNormalSubgroup fun V => ?_)
  obtain ⟨k, hk⟩ := exists_twoCentralSeries_le G hfg hpro V.toOpenSubgroup.isOpen
  exact hk (hx k)

end Profinite

/-! ## The χ-shadow layer (spike §2.7.5, §4.1)

The λ-series of `ℤ₂ˣ` sits inside the principal-unit filtration one step deeper than the
index (`λₖ(ℤ₂ˣ) = 1 + 2^{k+1}ℤ₂` for `k ≥ 2`; only `⊆` is frozen — the reverse inclusion
has no consumer).  Consequently every continuous character `χ : G → ℤ₂ˣ` has a level-`k`
shadow `Qₖ →* (ZMod 2^k)ˣ`: the invariant `P`'s χ-clause at modulus `2^k = 2^{m(k)}`
(spike §2.4) is stated through it. -/

section ChiShadow

/-- Membership in the mod-`2ⁿ` kernel of `ℤ₂ˣ`, spelled as a divisibility (`u ≡ 1 mod 2ⁿ`). -/
theorem mem_ker_units_toZModPow_iff {n : ℕ} {u : ℤ_[2]ˣ} :
    u ∈ (Units.map (PadicInt.toZModPow n).toMonoidHom).ker ↔
      ((2 : ℕ) : ℤ_[2]) ^ n ∣ (u : ℤ_[2]) - 1 := by
  rw [MonoidHom.mem_ker, Units.ext_iff, Units.coe_map, Units.val_one]
  show PadicInt.toZModPow n (u : ℤ_[2]) = 1 ↔ _
  rw [← sub_eq_zero, ← map_one (PadicInt.toZModPow (p := 2) n), ← map_sub, ← RingHom.mem_ker,
    PadicInt.ker_toZModPow, Ideal.mem_span_singleton]

/-- The mod-`2ⁿ` kernels of `ℤ₂ˣ` decrease with `n`. -/
theorem ker_units_toZModPow_antitone {m n : ℕ} (h : m ≤ n) {u : ℤ_[2]ˣ}
    (hu : u ∈ (Units.map (PadicInt.toZModPow n).toMonoidHom).ker) :
    u ∈ (Units.map (PadicInt.toZModPow m).toMonoidHom).ker := by
  rw [mem_ker_units_toZModPow_iff] at hu ⊢
  exact (pow_dvd_pow _ h).trans hu

/-- The mod-`2ⁿ` kernel of `ℤ₂ˣ` is closed: it is the preimage of a closed ball of `ℤ₂`. -/
theorem isClosed_ker_units_toZModPow (n : ℕ) :
    IsClosed (((Units.map (PadicInt.toZModPow n).toMonoidHom).ker : Subgroup ℤ_[2]ˣ) :
      Set ℤ_[2]ˣ) := by
  have hset : (((Units.map (PadicInt.toZModPow n).toMonoidHom).ker : Subgroup ℤ_[2]ˣ) :
      Set ℤ_[2]ˣ) = (Units.val : ℤ_[2]ˣ → ℤ_[2]) ⁻¹'
        Metric.closedBall (1 : ℤ_[2]) ((2 : ℕ) ^ (-(n : ℤ)) : ℝ) := by
    ext u
    simp only [Set.mem_preimage, Metric.mem_closedBall, dist_eq_norm, SetLike.mem_coe,
      mem_ker_units_toZModPow_iff]
    rw [PadicInt.norm_le_pow_iff_mem_span_pow, Ideal.mem_span_singleton]
  rw [hset]
  exact Metric.isClosed_closedBall.preimage Units.continuous_val

/-- **The modulus lemma** (spike §2.4, "exact, elementary" — only the containment
direction is frozen): for `k ≥ 2`, `λₖ(ℤ₂ˣ) ⊆ 1 + 2^{k+1}ℤ₂`, encoded as the kernel of
the unit-group reduction mod `2^{k+1}`.  Fill: L2. -/
theorem twoCentralSeries_units_le (k : ℕ) (hk : 2 ≤ k) :
    twoCentralSeries ℤ_[2]ˣ k ≤
      (Units.map (PadicInt.toZModPow (k + 1)).toMonoidHom).ker := by
  have hcomm : ∀ (n : ℕ) (a b : ℤ_[2]ˣ),
      ⁅a, b⁆ ∈ (Units.map (PadicInt.toZModPow n).toMonoidHom).ker := by
    intro n a b
    rw [commutatorElement_eq_one_iff_mul_comm.mpr (mul_comm a b)]
    exact one_mem _
  induction k, hk using Nat.le_induction with
  | base =>
    refine Subgroup.topologicalClosure_minimal _ (sup_le ?_ ?_) (isClosed_ker_units_toZModPow 3)
    · refine Subgroup.closure_le _ |>.2 ?_
      rintro _ ⟨v, -, rfl⟩
      have hsq : ∀ w : (ZMod (2 ^ 3))ˣ, w ^ 2 = 1 := by decide
      rw [SetLike.mem_coe, MonoidHom.mem_ker, map_pow]
      exact hsq _
    · rw [Subgroup.commutator_le]
      exact fun a _ b _ => hcomm 3 a b
  | succ k hk ih =>
    rw [twoCentralSeries_succ _ (by omega)]
    refine Subgroup.topologicalClosure_minimal _ (sup_le ?_ ?_)
      (isClosed_ker_units_toZModPow (k + 2))
    · refine Subgroup.closure_le _ |>.2 ?_
      rintro _ ⟨v, hv, rfl⟩
      have h1 : ((2 : ℕ) : ℤ_[2]) ^ (k + 1) ∣ (v : ℤ_[2]) - 1 :=
        mem_ker_units_toZModPow_iff.mp (ih hv)
      rw [SetLike.mem_coe, mem_ker_units_toZModPow_iff]
      have hfac : ((v ^ 2 : ℤ_[2]ˣ) : ℤ_[2]) - 1 = ((v : ℤ_[2]) - 1) * ((v : ℤ_[2]) + 1) := by
        push_cast; ring
      have h2 : ((2 : ℕ) : ℤ_[2]) ∣ (v : ℤ_[2]) + 1 := by
        obtain ⟨c, hc⟩ := (dvd_pow_self ((2 : ℕ) : ℤ_[2]) (Nat.succ_ne_zero k)).trans h1
        exact ⟨c + 1, by linear_combination hc⟩
      rw [hfac, pow_succ]
      exact mul_dvd_mul h1 h2
    · rw [Subgroup.commutator_le]
      exact fun a _ b _ => hcomm (k + 2) a b

variable {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- The λ-layers die in the mod-`2^k` shadow of any continuous character: for `g ∈ λₖ(G)`,
`χ g ≡ 1 (mod 2^k)`.  (For `k ≤ 1` the target `(ZMod 2^k)ˣ` is trivial; for `k ≥ 2` this
is `map_twoCentralSeries_le` + `twoCentralSeries_units_le` one precision step down.)
Fill: L2. -/
theorem chiShadow_eq_one_of_mem (χ : ContinuousMonoidHom G ℤ_[2]ˣ) (k : ℕ) {g : G}
    (hg : g ∈ twoCentralSeries G k) :
    Units.map (PadicInt.toZModPow k).toMonoidHom (χ g) = 1 := by
  match k, hg with
  | 0, _ =>
    haveI : Subsingleton ((ZMod (2 ^ 0))ˣ) := ⟨by decide⟩
    exact Subsingleton.elim _ _
  | 1, _ =>
    haveI : Subsingleton ((ZMod (2 ^ 1))ˣ) := ⟨by decide⟩
    exact Subsingleton.elim _ _
  | (k + 2), hg =>
    have h1 : χ g ∈ twoCentralSeries ℤ_[2]ˣ (k + 2) :=
      map_twoCentralSeries_le χ.toMonoidHom χ.continuous_toFun (k + 2) ⟨g, hg, rfl⟩
    exact MonoidHom.mem_ker.mp
      (ker_units_toZModPow_antitone (Nat.le_succ _)
        (twoCentralSeries_units_le (k + 2) (by omega) h1))

/-- **The level-`k` χ-shadow** `χ̄ₖ : Qₖ →* (ZMod 2^k)ˣ` of a continuous character
`χ : G → ℤ₂ˣ` — precision `2^k`, the modulus `m(k) = k` of the invariant `P` (spike §2.4).
Total in `k` (no side condition): for `k ≤ 1` the target is trivial. -/
noncomputable def chiLevel (χ : ContinuousMonoidHom G ℤ_[2]ˣ) (k : ℕ) :
    levelQuot G k →* (ZMod (2 ^ k))ˣ :=
  QuotientGroup.lift (twoCentralSeries G k)
    ((Units.map (PadicInt.toZModPow k).toMonoidHom).comp χ.toMonoidHom)
    (fun _ hg => chiShadow_eq_one_of_mem χ k hg)

/-- Evaluation of the shadow on residues (smoke). -/
@[simp] theorem chiLevel_levelMk (χ : ContinuousMonoidHom G ℤ_[2]ˣ) (k : ℕ) (g : G) :
    chiLevel χ k (levelMk G k g) = Units.map (PadicInt.toZModPow k).toMonoidHom (χ g) :=
  rfl

/-- **Naturality of the shadows in `k`**: reading the level-`(k+1)` shadow mod `2^k`
recovers the level-`k` shadow through the tower projection.  (The mod-`2^{k+1}` clause of
`P` at level `k+1` *weakens* to the mod-`2^k` clause at level `k` — the restriction-map
direction of the levelwise sets.)  Fill: L2. -/
theorem chiLevel_levelProj (χ : ContinuousMonoidHom G ℤ_[2]ˣ) (k : ℕ)
    (q : levelQuot G (k + 1)) :
    chiLevel χ k (levelProj G k q) =
      Units.map (ZMod.castHom (pow_dvd_pow 2 (Nat.le_succ k)) (ZMod (2 ^ k))).toMonoidHom
        (chiLevel χ (k + 1) q) := by
  obtain ⟨g, rfl⟩ := levelMk_surjective G (k + 1) q
  rw [levelProj_levelMk, chiLevel_levelMk, chiLevel_levelMk]
  ext
  simp

end ChiShadow

end GQ2.Roe.Labute
