/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Fable-5
-/
import GQ2.Dyadic.MarkedCore.Cores
import GQ2.Dyadic.MarkedCore.HandleMix
import GQ2.BoundaryFrame
import GQ2.Dyadic.Instances.KSupply
import GQ2.Dyadic.Count.ProTwo
import GQ2.Dyadic.Count.Routine
import GQ2.Dyadic.Count.WildDischarge
import GQ2.Dyadic.Count.Marking
import GQ2.Dyadic.Certificates.MpcStokes

/-!
# The branch-core layer: the `ν_P` witness at `D_M`  (dyadic campaign, ticket AS3-b)

The four packet-Thm-1.1 instance headlines (`GQ2/Dyadic/Instances/{Sqrt2,Sqrt5,Sqrt10,SqrtNeg10}
.lean`) each carry four binders `nuP`, `hnuSigma`, `hnuWild`, `hnuP` — F3's `prop_3_4_three`
normalization of the abstract slot `(P, ν_P)`, read through the row's alphabet ↔ core dictionary.
AS3 hand-verified that they are satisfiable but could not build the witness.  This file builds it,
once, for **every** row whose core is `D_M`: both AS3 dictionaries land there, and so does every
future compact-`M`/procyclic-`M` instance.

## The witness

`ν_P` is classified by a marking of `D_M` in `Z₂` killing the relator (`presLiftHom`).  Take the
marking to be **powers of a single element**, `μ_i ↦ ztwoOne^{e i}` for an integer vector `e`.
Then two things become free:

* the commutators of `M_α` die — powers of one element commute in *any* group, so no
  commutativity of `Z₂` is needed (`mRelWord_of_commute`, `mRelWord_zpow`); and
* the relator collapses to the single integer condition `2·e₀ + 2^α·e₂ = 0`, which is exactly the
  abelian relation vector `ρ_M = 2Ā + 2^α C̄₀` of `MarkedCore.mRelWord_comm`.

That is `dmNu`.  Surjectivity — the `hnuP` binder — is §1's procyclicity criterion
`surjective_of_ztwoOne_mem_range`: `D_M` is compact and `ztwoOne` is in the image as soon as some
`e i = 1`.

## ⚠ Finding: the commutativity lemma the ticket anticipated is **not needed**

AS3 reported the blocker as "constructing `ν` needs commutativity of `Ztwo`", and a
`maxProPQuotient p G`-is-commutative lemma was authorized as a new declaration in
`GQ2/MaxProP.lean` / `GQ2/BoundaryFrame.lean` — the ticket's one sanctioned exception to the
plan-A6 freeze of the `ℚ₂` development.  **It went unused, and the exception was not exercised**:
routing the marking through a *single* generator's powers replaces group commutativity by
`Commute.zpow_zpow`, which is unconditional.  No frozen file is touched by AS3-b.

## Homing (two recorded debts, both deliberate)

* `mRelWord_of_commute` is a `MarkedCore` fact and belongs beside `MarkedCore.mRelWord_comm`
  (`GQ2/Dyadic/MarkedCore/Cores.lean` §"Abelian collapse"); it is the `Commute`-hypothesis twin
  of that lemma, exactly as `MarkedCore.commP_eq_one_of_commute` is of `Roe.commP_eq_one`.
* §1's two `Z₂` facts belong beside `Ztwo` in `GQ2/BoundaryFrame.lean`.  They are stated here
  instead because that file is frozen (plan A6) and an addition to it forces a rebuild of the
  entire downstream tree for no mathematical gain; the Dyadic tree already proves `Ztwo`-valued
  facts freely (`GQ2/Dyadic/TameQuotientK.lean`'s `nuTq`, `GQ2/Dyadic/SqCore/Certificate.lean`'s
  `nuDR_sqEquivDRMarked`), so this is ordinary layering, not a duplicate.

Both are for a later dedup/hoist ticket that has the destination file in scope — the standing
`GQ2/Dyadic/Count/Scalar.lean` ruling.

## Axioms

`sorry`-free, no new axiom, no `decide`.  Every declaration prints exactly the standard three.
-/

namespace GQ2.Dyadic.Instances

open GQ2 GQ2.Dyadic GQ2.Dyadic.MarkedCore

namespace NuWitness

/-! ## §1 `Z₂` is procyclic, topologically generated by `ztwoOne`

`ℤ` is dense in `ℤ̂` (`Zhat.denseRange_ofInt`) and `Zhat.ofInt n = Zhat.ofInt 1 ^ n`, so the
powers of `ztwoOne` are dense in `Z₂ = maxProPQuotient 2 ℤ̂`.  The consequence used below is the
**surjectivity criterion**: a continuous homomorphism from a *compact* group into `Z₂` is onto as
soon as `ztwoOne` lies in its image — the image is then a closed set containing a dense one.
This is what discharges the `hnuP : Function.Surjective ν_P` binder of the four field headlines. -/

private theorem zhat_ofInt_neg (n : ℤ) : Zhat.ofInt (-n) = (Zhat.ofInt n)⁻¹ := by
  rw [eq_inv_iff_mul_eq_one, ← Zhat.ofInt_add, neg_add_cancel, Zhat.ofInt_zero]

private theorem zhat_ofInt_eq_zpow (n : ℤ) : Zhat.ofInt n = Zhat.ofInt 1 ^ n := by
  induction n using Int.induction_on with
  | zero => simp
  | succ k ih => rw [Zhat.ofInt_add, ih, zpow_add_one]
  | pred k ih =>
    rw [show (-(k : ℤ) - 1) = -(k : ℤ) + -1 by ring, Zhat.ofInt_add, ih, zpow_add, zhat_ofInt_neg,
      zpow_neg_one]

/-- **`Z₂` is procyclic**: the integer powers of `ztwoOne` are dense. -/
theorem denseRange_ztwoOne_zpow : DenseRange (fun n : ℤ => ztwoOne ^ n) := by
  have h : (fun n : ℤ => ztwoOne ^ n) = ⇑(maxProPMk 2 Zhat) ∘ Zhat.ofInt := by
    funext n
    show ztwoOne ^ n = maxProPMk 2 Zhat (Zhat.ofInt n)
    rw [zhat_ofInt_eq_zpow, map_zpow]
    rfl
  rw [h]
  exact DenseRange.comp (quotientMk_surjective (proPKernel 2 Zhat)).denseRange
    Zhat.denseRange_ofInt (maxProPMk 2 Zhat).continuous_toFun

/-- **The `Z₂`-surjectivity criterion.**  A continuous homomorphism out of a compact group whose
image contains `ztwoOne` is surjective.  (No hypothesis on the source beyond compactness — not
even that it is a topological group.) -/
theorem surjective_of_ztwoOne_mem_range {D : Type*} [Group D] [TopologicalSpace D]
    [CompactSpace D] (f : ContinuousMonoidHom D Ztwo) (hf : ztwoOne ∈ Set.range f) :
    Function.Surjective f := by
  obtain ⟨d, hd⟩ := hf
  have hcl : IsClosed (Set.range f) := (isCompact_range f.continuous_toFun).isClosed
  have hsub : Set.range (fun n : ℤ => ztwoOne ^ n) ⊆ Set.range f := by
    rintro _ ⟨n, rfl⟩
    exact ⟨d ^ n, by rw [map_zpow, hd]⟩
  rw [← Set.range_eq_univ, ← hcl.closure_eq, (denseRange_ztwoOne_zpow.mono hsub).closure_eq]

/-! ## §2 The relator at a marking by powers of one element -/

/-- **Abelian collapse of the `M_α` relator under a pointwise `Commute` hypothesis** — the twin of
`MarkedCore.mRelWord_comm` with the commutativity localised to the letters, so that it applies in
a group carrying no `CommGroup` instance (such as a `ProfiniteGrp` carrier). -/
theorem mRelWord_of_commute {G : Type*} [Group G] (α : ℕ) {h : ℕ} (c : Fin (coreRank h) → G)
    (hc : ∀ i j, Commute (c i) (c j)) : mRelWord α c = c 0 ^ 2 * c 2 ^ (2 ^ α) := by
  have hhandle : handleWord (fun j => c (handleIdxU j)) (fun j => c (handleIdxV j)) = 1 := by
    rw [handleWord, List.prod_eq_one]
    intro x hx
    obtain ⟨j, _, rfl⟩ := List.mem_map.mp hx
    exact commP_eq_one_of_commute (hc _ _)
  rw [mRelWord, hhandle, mul_one, mWord, commP_eq_one_of_commute (hc 0 1),
    commP_eq_one_of_commute (hc 2 3), mul_one, mul_assoc, one_mul]

/-- The `M_α` relator at a marking `μ_i = x^{e i}` by powers of a single element: the relation
vector `ρ_M = 2Ā + 2^α C̄₀` read as an integer. -/
theorem mRelWord_zpow {G : Type*} [Group G] (α : ℕ) {h : ℕ} (x : G) (e : Fin (coreRank h) → ℤ) :
    mRelWord α (fun i => x ^ e i) = x ^ (2 * e 0 + 2 ^ α * e 2) := by
  rw [mRelWord_of_commute α _ fun i j => (Commute.refl x).zpow_zpow _ _,
    ← zpow_natCast (x ^ e 0) 2, ← zpow_natCast (x ^ e 2) (2 ^ α), ← zpow_mul, ← zpow_mul,
    ← zpow_add]
  congr 1
  push_cast
  ring

/-! ## §3 The witness `ν_P : D_M → Z₂`

The **only** input is the integer condition `2·e₀ + 2^α·e₂ = 0`.  Nothing here is
branch-specific: a branch supplies its own `e` (compact-`M` and procyclic-`M` do so in
`GQ2/Dyadic/Instances/{Sqrt2,Sqrt10}.lean`), and the row's `hnuSigma`/`hnuWild` become
arithmetic in the exponents. -/

/-- **The `ν_P` witness at `D_M`**: the continuous homomorphism `D_M → Z₂` sending the marked
generator `μ_i` to `ztwoOne^{e i}`.  Well-defined exactly when the abelian relation vector
vanishes, `2·e₀ + 2^α·e₂ = 0`. -/
noncomputable def dmNu (α h : ℕ) (e : Fin (coreRank h) → ℤ) (he : 2 * e 0 + 2 ^ α * e 2 = 0) :
    ContinuousMonoidHom ((DM α h : ProfiniteGrp) : Type) Ztwo :=
  presLiftHom (mRelator α h) isProP_maxProPQuotient (fun i => ztwoOne ^ e i) (by
    have h1 : freeHomFin (fun i => ztwoOne ^ e i) (mRelator α h)
        = mRelWord α (fun i => ztwoOne ^ e i) := by
      rw [mRelator, map_mRelWord]
      exact congrArg (mRelWord α) (funext fun i => freeHomFin_of _ i)
    rw [h1, mRelWord_zpow, he, zpow_zero])

@[simp] theorem dmNu_dmGen (α h : ℕ) (e : Fin (coreRank h) → ℤ)
    (he : 2 * e 0 + 2 ^ α * e 2 = 0) (i : Fin (coreRank h)) :
    dmNu α h e he (dmGen α h i) = ztwoOne ^ e i :=
  presLiftHom_gen _ _ _ _ i

/-- **`hnuP` at the witness**: `ν_P` is surjective as soon as some marked generator carries
exponent `1`.  `D_M` is a `ProfiniteGrp`, hence compact, so `BoundaryFrame`'s procyclicity
criterion applies. -/
theorem dmNu_surjective (α h : ℕ) (e : Fin (coreRank h) → ℤ) (he : 2 * e 0 + 2 ^ α * e 2 = 0)
    {i : Fin (coreRank h)} (hi : e i = 1) : Function.Surjective (dmNu α h e he) :=
  surjective_of_ztwoOne_mem_range _ ⟨dmGen α h i, by rw [dmNu_dmGen, hi, zpow_one]⟩

end NuWitness

/-! # The compact-`M` branch layer

Hoisted verbatim from `GQ2/Dyadic/Instances/Sqrt2.lean` §1–§5 (ticket AS3-b, pure move: every
fully-qualified name is unchanged).  The `open`s below are that file's, so the block elaborates
in exactly its original scope. -/

section CompactM

open GQ2 GQ2.Dyadic GQ2.Dyadic.Count GQ2.Dyadic.MarkedCore GQ2.SectionEight
open GQ2.Dyadic.Words GQ2.Dyadic.Words.MCompact
open GQ2.Dyadic.Count.PilotN TameSpec
open SectionSeven AffineTLift CentralObstruction ContCoh FoxH
open GQ2.Dyadic.Certificates GQ2.Dyadic.Certificates.MCompact
open GQ2.Dyadic.Instances.NuWitness

/-! ## §1 The compact-`M` alphabet ↔ core dictionary

`Words/M0.lean`'s `eval_pro2_mCompact` reads the pro-`2` boundary of the compact-`M` word as
`MarkedCore.mWord α A₀ x₁ σ x₂ · handleWord …` with `A₀ = x₀⁻¹σ^{-m}`.  Against
`MarkedCore.mRelWord α μ = mWord α (μ 0) (μ 1) (μ 2) (μ 3) · handleWord …` that is the compact-`N`
letter table `nIdx` with slot `0` replaced by `A₀`; so the dictionary is `nReindex` composed with
the core-side change of variable below. -/

namespace MCompactCore

variable {G : Type*} [Group G]

/-- **The compact-`M` twist**: `μ₀ ↦ μ₀⁻¹ μ₂^{-m}`, identity on every other slot.  Applied to
the compact-`N` core marking `i ↦ t (nIdx h i)` it produces exactly the marking
`eval_pro2_mCompact` evaluates `mRelWord` at. -/
def mTwist (α h : ℕ) (c : Fin (coreRank h) → G) : Fin (coreRank h) → G :=
  fun i => if (i : ℕ) = 0 then (c i)⁻¹ * c 2 ^ (-(mOf α : ℤ)) else c i

/-- **The inverse change of variable**: `μ₀ ↦ (μ₀ μ₂^{m})⁻¹`. -/
def mUntwist (α h : ℕ) (c : Fin (coreRank h) → G) : Fin (coreRank h) → G :=
  fun i => if (i : ℕ) = 0 then (c i * c 2 ^ (mOf α : ℤ))⁻¹ else c i

theorem mTwist_apply_ne (α h : ℕ) (c : Fin (coreRank h) → G) {i : Fin (coreRank h)}
    (hi : (i : ℕ) ≠ 0) : mTwist α h c i = c i := if_neg hi

theorem mUntwist_apply_ne (α h : ℕ) (c : Fin (coreRank h) → G) {i : Fin (coreRank h)}
    (hi : (i : ℕ) ≠ 0) : mUntwist α h c i = c i := if_neg hi

theorem coreIdx_two_ne_zero (h : ℕ) : ((2 : Fin (coreRank h)) : ℕ) ≠ 0 := by
  rw [coreVal_two]; omega

@[simp] theorem mTwist_two (α h : ℕ) (c : Fin (coreRank h) → G) :
    mTwist α h c 2 = c 2 := mTwist_apply_ne α h c (coreIdx_two_ne_zero h)

@[simp] theorem mUntwist_two (α h : ℕ) (c : Fin (coreRank h) → G) :
    mUntwist α h c 2 = c 2 := mUntwist_apply_ne α h c (coreIdx_two_ne_zero h)

@[simp] theorem mTwist_one (α h : ℕ) (c : Fin (coreRank h) → G) :
    mTwist α h c 1 = c 1 := mTwist_apply_ne α h c (by rw [coreVal_one]; omega)

@[simp] theorem mTwist_three (α h : ℕ) (c : Fin (coreRank h) → G) :
    mTwist α h c 3 = c 3 := mTwist_apply_ne α h c (by rw [coreVal_three]; omega)

@[simp] theorem mTwist_handleIdxU (α h : ℕ) (c : Fin (coreRank h) → G) (j : Fin h) :
    mTwist α h c (handleIdxU j) = c (handleIdxU j) :=
  mTwist_apply_ne α h c (by rw [handleIdxU_val]; omega)

@[simp] theorem mTwist_handleIdxV (α h : ℕ) (c : Fin (coreRank h) → G) (j : Fin h) :
    mTwist α h c (handleIdxV j) = c (handleIdxV j) :=
  mTwist_apply_ne α h c (by rw [handleIdxV_val]; omega)

@[simp] theorem mTwist_zero (α h : ℕ) (c : Fin (coreRank h) → G) :
    mTwist α h c 0 = (c 0)⁻¹ * c 2 ^ (-(mOf α : ℤ)) := if_pos (coreVal_zero h)

@[simp] theorem mUntwist_zero (α h : ℕ) (c : Fin (coreRank h) → G) :
    mUntwist α h c 0 = (c 0 * c 2 ^ (mOf α : ℤ))⁻¹ := if_pos (coreVal_zero h)

theorem mTwist_mUntwist (α h : ℕ) (c : Fin (coreRank h) → G) :
    mTwist α h (mUntwist α h c) = c := by
  funext i
  by_cases h0 : (i : ℕ) = 0
  · have hi : i = 0 := Fin.ext (by rw [h0, coreVal_zero])
    subst hi
    rw [mTwist_zero, mUntwist_zero, mUntwist_two, inv_inv]
    group
  · rw [mTwist_apply_ne _ _ _ h0, mUntwist_apply_ne _ _ _ h0]

theorem mUntwist_mTwist (α h : ℕ) (c : Fin (coreRank h) → G) :
    mUntwist α h (mTwist α h c) = c := by
  funext i
  by_cases h0 : (i : ℕ) = 0
  · have hi : i = 0 := Fin.ext (by rw [h0, coreVal_zero])
    subst hi
    rw [mUntwist_zero, mTwist_zero, mTwist_two]
    group
  · rw [mUntwist_apply_ne _ _ _ h0, mTwist_apply_ne _ _ _ h0]

/-- Both changes of variable commute with any monoid hom — the naturality input for the two
`CoreReindex` naturality fields.  Stated at `MonoidHomClass` so that the `ContinuousMonoidHom`
the structure's fields quantify over is passed unbundled (the `.toMonoidHom` spelling is defeq
but *not* at `instances` transparency, AS4-b's friction). -/
theorem map_mTwist {H : Type*} [Group H] {F : Type*} [FunLike F G H] [MonoidHomClass F G H]
    (f : F) (α h : ℕ) (c : Fin (coreRank h) → G) :
    (fun i => f (mTwist α h c i)) = mTwist α h (fun i => f (c i)) := by
  funext i
  by_cases h0 : (i : ℕ) = 0
  · rw [show mTwist α h c i = (c i)⁻¹ * c 2 ^ (-(mOf α : ℤ)) from if_pos h0,
      show mTwist α h (fun i => f (c i)) i = (f (c i))⁻¹ * (f (c 2)) ^ (-(mOf α : ℤ)) from
        if_pos h0, map_mul, map_inv, map_zpow]
  · rw [mTwist_apply_ne _ _ _ h0,
      show mTwist α h (fun i => f (c i)) i = f (c i) from if_neg h0]

theorem map_mUntwist {H : Type*} [Group H] {F : Type*} [FunLike F G H] [MonoidHomClass F G H]
    (f : F) (α h : ℕ) (c : Fin (coreRank h) → G) :
    (fun i => f (mUntwist α h c i)) = mUntwist α h (fun i => f (c i)) := by
  funext i
  by_cases h0 : (i : ℕ) = 0
  · rw [show mUntwist α h c i = (c i * c 2 ^ (mOf α : ℤ))⁻¹ from if_pos h0,
      show mUntwist α h (fun i => f (c i)) i = (f (c i) * (f (c 2)) ^ (mOf α : ℤ))⁻¹ from
        if_pos h0, map_inv, map_mul, map_zpow]
  · rw [mUntwist_apply_ne _ _ _ h0,
      show mUntwist α h (fun i => f (c i)) i = f (c i) from if_neg h0]

/-- **The compact-`M` dictionary.**  `nReindex` conjugated by the triangular change of variable
of this section: the letter table is compact-`N`'s, slot `0` carries `A₀ = x₀⁻¹σ^{-m}`. -/
noncomputable def mReindex (α h : ℕ) : CoreReindex (2 + 2 * h) (Fin (coreRank h)) where
  toCore := fun t => mTwist α h ((nReindex h).toCore t)
  ofCore := fun m => (nReindex h).ofCore (mUntwist α h m)
  ofCore_tau := fun m => (nReindex h).ofCore_tau (mUntwist α h m)
  toCore_ofCore := fun m => by
    rw [(nReindex h).toCore_ofCore (mUntwist α h m), mTwist_mUntwist]
  ofCore_toCore := fun t ht => by
    rw [mUntwist_mTwist, (nReindex h).ofCore_toCore t ht]
  toCore_nat := fun f t k => by
    have hnat : (fun i => f ((nReindex h).toCore t i)) = (nReindex h).toCore (t.map ⇑f) :=
      funext fun i => (nReindex h).toCore_nat f t i
    calc f (mTwist α h ((nReindex h).toCore t) k)
        = mTwist α h (fun i => f ((nReindex h).toCore t i)) k :=
          congrFun (map_mTwist f α h ((nReindex h).toCore t)) k
      _ = mTwist α h ((nReindex h).toCore (t.map ⇑f)) k := by rw [hnat]
  ofCore_nat := fun f m g => by
    rw [(nReindex h).ofCore_nat f (mUntwist α h m) g]
    exact congrArg (fun c => (nReindex h).ofCore c g) (map_mUntwist f α h m)

/-- The compact-`M` core marking of an alphabet marking, in closed form and with **no**
topological hypotheses — which is what lets `WordCertificate.coreRel` (whose binder list has no
`T2Space`) be stated with it. -/
def mCoreMark (α h : ℕ) {G : Type*} [Group G] (t : Marking (2 + 2 * h) G) :
    Fin (coreRank h) → G :=
  mTwist α h (fun i => t (nIdx h i))

/-- **`WordCertificate.coreRel` at the compact-`M` row.** -/
def mCoreRel (α h : ℕ) (G : Type) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [TotallyDisconnectedSpace G] (t : Marking (2 + 2 * h) G) : G :=
  mRelWord α (mCoreMark α h t)

/-- **`WordCertificate.proTwoWord` at the compact-`M` row**, i.e. WM0-a's Gate-C headline
(`GQ2/Dyadic/Words/M0.lean:648`) read through §1's dictionary, at every handle count.  `1 ≤ α` is
genuine — WM0-a's own note: the third factor is `σ₂^{2m}` and `2m = 2^α` fails at `α = 0`. -/
theorem mProTwoWord (α h : ℕ) (hα : 1 ≤ α) (G : Type) [Group G] [TopologicalSpace G]
    [IsTopologicalGroup G] [CompactSpace G] [TotallyDisconnectedSpace G]
    (t : Marking (2 + 2 * h) G) :
    t.eval (pro2 (mCompactW α h)) = mCoreRel α h G t := by
  rw [eval_pro2_mCompact hα t]
  show _ = mRelWord α (mTwist α h (fun i => t (nIdx h i)))
  simp only [mRelWord, mTwist_zero, mTwist_one, mTwist_two, mTwist_three, mTwist_handleIdxU,
    mTwist_handleIdxV, nIdx_zero, nIdx_one, nIdx_two, nIdx_three, nIdx_handleIdxU,
    nIdx_handleIdxV, Marking.apply_sigma]

/-- The same statement in the shape `CorePresentation.ofPresentedBy` consumes. -/
theorem eval_pro2_mCompact_reindex (α h : ℕ) (hα : 1 ≤ α) {G : Type} [Group G]
    [TopologicalSpace G] [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    [TotallyDisconnectedSpace G] (t : Marking (2 + 2 * h) G) :
    t.eval (pro2 (mCompactW α h)) = (mNatWord α h).ev ((mReindex α h).toCore t) :=
  mProTwoWord α h hα G t

/-- **The compact-`M` core presentation.**  Inputs, all landed: `isProP_DM`, `presentedBy_DM`
(`MarkedCore/Certificate.lean:292`), `dm_relation`, and §1's dictionary against WM0-a's
`eval_pro2_mCompact`.  Note that `presentedBy_DM`/`dm_relation` are used, **not**
`markedRelator_DM`, so no `MMixHypothesis` and no Labute input is inherited — only WM0-a's own
`1 ≤ α`. -/
noncomputable def mCorePresentation (α h : ℕ) (hα : 1 ≤ α) :
    CorePresentation (2 + 2 * h) (mCompactW α h) (DM α h) :=
  CorePresentation.ofPresentedBy (isProP_DM α h) (presentedBy_DM α h) (dm_relation α h)
    (mReindex α h) (fun t => eval_pro2_mCompact_reindex α h hα t)

/-- The dictionary sends `σ` to core generator `2` — the slot `mWord`'s third letter occupies. -/
@[simp] theorem mCorePresentation_mark_sigma (α h : ℕ) (hα : 1 ≤ α) :
    (mCorePresentation α h hα).mark .sigma = dmGen α h 2 :=
  congrArg (dmGen α h) (Fin.ext (by rw [coreVal_two]; rfl))

/-- …and the wild letters to the *untwisted* core generators: `x₀ ↦ (μ₀ μ₂^{m})⁻¹` and
`x_j ↦ μ_{nWildIdx j}` for `j ≥ 1`.  This is what `hnuWild` below is a condition on. -/
@[simp] theorem mCorePresentation_mark_wild (α h : ℕ) (hα : 1 ≤ α)
    (j : Fin (2 + 2 * h + 1)) :
    (mCorePresentation α h hα).mark (.wild j) = mUntwist α h (dmGen α h) (nWildIdx h j) := rfl

/-! ## §3 The four pro-`2` fields

`Count.CorePresentation`'s bridge at §1's presentation.  Nothing branch-specific survives: the
`ℚ₂` ancestor is `GQ2.Roe.exists_pro2R`, which carries `BLabHypothesis`; this does not.

All parameters are explicit: `h` occurs in these statements only inside `GammaR`/`DM`, so with it
implicit the elaborator cannot solve for it at a use site such as
`Function.Surjective (mPro2 …)`. -/

section ProTwo

/-- **`WordCertificate.pro2`.** -/
noncomputable def mPro2 (α h q : ℕ) (hα : 1 ≤ α) (hq0 : q ≠ 0) (hqe : Even q) :
    ContinuousMonoidHom ((GammaR (2 + 2 * h) q (mCompactW α h)) : Type)
      ((DM α h : ProfiniteGrp) : Type) :=
  CorePresentation.coreHom (mCorePresentation α h hα) hq0 hqe

/-- **`WordCertificate.ker_pro2`.** -/
theorem ker_mPro2 (α h q : ℕ) (hα : 1 ≤ α) (hq0 : q ≠ 0) (hqe : Even q) :
    (mPro2 α h q hα hq0 hqe).toMonoidHom.ker
      = proPKernel 2 ((GammaR (2 + 2 * h) q (mCompactW α h)) : Type) :=
  CorePresentation.ker_coreHom (mCorePresentation α h hα) hq0 hqe

/-- **`WordCertificate.hpro2`.** -/
theorem mPro2_surjective (α h q : ℕ) (hα : 1 ≤ α) (hq0 : q ≠ 0) (hqe : Even q) :
    Function.Surjective (mPro2 α h q hα hq0 hqe) :=
  CorePresentation.coreHom_surjective (mCorePresentation α h hα) hq0 hqe

/-- **`WordCertificate.tameSpecialization` at the compact-`M` row** (CB-0's branch line). -/
theorem mTameSpecializes (α h q : ℕ) (hq0 : q ≠ 0) (hqe : Even q) :
    TameSpecializes (2 + 2 * h) q (mCompactW α h) :=
  Count.tameSpecializes_mCompact hq0 hqe α h

/-- **`WordCertificate.compat`**, against F3b's `tameOfSpec`.  The two `ν_P` conditions are F3's
`prop_3_4_three` normalization *at the dictionary's marking*; §1's two `mark` lemmas say what
they are in terms of `dmGen`. -/
theorem mCompat (α h q : ℕ) (hα : 1 ≤ α) (hq0 : q ≠ 0) (hqe : Even q)
    (hspec : TameSpecializes (2 + 2 * h) q (mCompactW α h))
    (nuP : ContinuousMonoidHom ((DM α h : ProfiniteGrp) : Type) Ztwo)
    (hnuSigma : nuP ((mCorePresentation α h hα).mark .sigma) = ztwoOne)
    (hnuWild : ∀ j : Fin (2 + 2 * h + 1),
      nuP ((mCorePresentation α h hα).mark (.wild j)) = 1)
    (g : ((GammaR (2 + 2 * h) q (mCompactW α h)) : Type)) :
    nuTq q (tameOfSpec (2 + 2 * h) q (mCompactW α h) hspec g)
      = nuP (mPro2 α h q hα hq0 hqe g) :=
  CorePresentation.nu_compat_coreHom (mCorePresentation α h hα) hq0 hqe hspec nuP hnuSigma
    hnuWild g

/-! ### The `ν_P` witness at the compact-`M` row  (ticket AS3-b)

The three `ν_P` conditions above are *satisfiable*, and here is the witness — so the row's
headline is demonstrably non-vacuous rather than conditionally stated.  The exponent vector is
`ν(μ₂) = 1`, `ν(μ₀) = −m`, all other slots `0`; the relator condition
`2·ν(μ₀) + 2^α·ν(μ₂) = 0` is exactly WM0-a's `two_mul_mOf` (`2m = 2^α`, hence the `1 ≤ α`), and
the wild conditions are the untwisting `x₀ ↦ (μ₀μ₂^m)⁻¹` cancelling `−m` against `m`.  The
machinery is in `GQ2/Dyadic/Instances/Cores.lean`; only the exponent vector is branch-specific. -/

/-- **The compact-`M` ν-exponent vector**: `ν(μ₂) = 1`, `ν(μ₀) = −m`, every other slot `0`. -/
def mNuExp (α h : ℕ) : Fin (coreRank h) → ℤ :=
  fun i => if (i : ℕ) = 0 then -(mOf α : ℤ) else if (i : ℕ) = 2 then 1 else 0

@[simp] theorem mNuExp_zero (α h : ℕ) : mNuExp α h 0 = -(mOf α : ℤ) := if_pos (coreVal_zero h)

@[simp] theorem mNuExp_two (α h : ℕ) : mNuExp α h 2 = 1 := by
  rw [mNuExp, if_neg (by rw [coreVal_two]; omega), if_pos (coreVal_two h)]

theorem mNuExp_eq_zero (α h : ℕ) {i : Fin (coreRank h)} (h0 : (i : ℕ) ≠ 0) (h2 : (i : ℕ) ≠ 2) :
    mNuExp α h i = 0 := by rw [mNuExp, if_neg h0, if_neg h2]

/-- The relation vector vanishes — WM0-a's `2m = 2^α`, and the row's only use of `1 ≤ α` here. -/
theorem mNuExp_rel (α h : ℕ) (hα : 1 ≤ α) : 2 * mNuExp α h 0 + 2 ^ α * mNuExp α h 2 = 0 := by
  have h2 : ((2 * mOf α : ℕ) : ℤ) = ((2 ^ α : ℕ) : ℤ) := congrArg _ (two_mul_mOf hα)
  push_cast at h2
  rw [mNuExp_zero, mNuExp_two, mul_one, mul_neg, ← h2]
  ring

/-- **The `ν_P` witness at the compact-`M` row.** -/
noncomputable def mNu (α h : ℕ) (hα : 1 ≤ α) :
    ContinuousMonoidHom ((DM α h : ProfiniteGrp) : Type) Ztwo :=
  dmNu α h (mNuExp α h) (mNuExp_rel α h hα)

/-- **`hnuSigma` at the witness**: the dictionary puts `σ` at core slot `2`, which carries `1`. -/
theorem mNu_sigma (α h : ℕ) (hα : 1 ≤ α) :
    mNu α h hα ((mCorePresentation α h hα).mark .sigma) = ztwoOne := by
  rw [mCorePresentation_mark_sigma, mNu, dmNu_dmGen, mNuExp_two, zpow_one]

/-- The wild letters never land on core slot `2`: `nWildIdx` skips it, which is the whole point of
the compact-`N` letter table. -/
theorem nWildIdx_val_ne_two (h : ℕ) (j : Fin (2 + 2 * h + 1)) :
    ((nWildIdx h j : Fin (coreRank h)) : ℕ) ≠ 2 := by
  simp only [nWildIdx]
  split <;> omega

/-- **`hnuWild` at the witness.**  Slot `0` is the untwisting `x₀ ↦ (μ₀μ₂^m)⁻¹`, whose exponent is
`−(−m + m) = 0`; every other wild slot carries exponent `0` outright. -/
theorem mNu_wild (α h : ℕ) (hα : 1 ≤ α) (j : Fin (2 + 2 * h + 1)) :
    mNu α h hα ((mCorePresentation α h hα).mark (.wild j)) = 1 := by
  rw [mCorePresentation_mark_wild]
  by_cases h0 : ((nWildIdx h j : Fin (coreRank h)) : ℕ) = 0
  · have hi : (nWildIdx h j : Fin (coreRank h)) = 0 := Fin.ext (by rw [h0, coreVal_zero])
    rw [hi, mUntwist_zero, mNu, map_inv, map_mul, map_zpow, dmNu_dmGen, dmNu_dmGen, mNuExp_zero,
      mNuExp_two, zpow_one, ← zpow_add, neg_add_cancel, zpow_zero, inv_one]
  · rw [mUntwist_apply_ne _ _ _ h0, mNu, dmNu_dmGen,
      mNuExp_eq_zero α h h0 (nWildIdx_val_ne_two h j), zpow_zero]

/-- **`hnuP` at the witness**: `ν(μ₂) = 1` puts `ztwoOne` in the image, and `D_M` is compact. -/
theorem mNu_surjective (α h : ℕ) (hα : 1 ≤ α) : Function.Surjective (mNu α h hα) :=
  dmNu_surjective α h _ _ (i := 2) (mNuExp_two α h)

end ProTwo

/-! ## §4 The compact-`M` word certificate, modulo AS1's four analytic clauses

Every field the landed stack proves is filled; `exactLifting`, `stokes`, `scalar` and
`determinant` are arguments, because the certificate ⇒ count bridge does not exist at the
candidate carrier (AS1 divergence 4).  This is the exact posture `KSupply` takes on the
arithmetic side, and it is what keeps the gap countable rather than hidden. -/

section Certificate

/-- **The compact-`M` word certificate.**  Thirteen of the seventeen fields are proved; the four
arguments are AS1's analytic clauses, stated at exactly the record's types (so that the elaborator
is the acceptance check — `determinant` depends on `tameSpecialization`, `pro2` and `compat`, and
only typechecks if this file's terms sit at the field's type). -/
noncomputable def mWordCertificate (α h q : ℕ) (hα : 1 ≤ α) (hq0 : q ≠ 0) (hqe : Even q)
    {SN : SourceNumerics (2 + 2 * h)}
    (nuP : ContinuousMonoidHom ((DM α h : ProfiniteGrp) : Type) Ztwo)
    (hnuSigma : nuP ((mCorePresentation α h hα).mark .sigma) = ztwoOne)
    (hnuWild : ∀ j : Fin (2 + 2 * h + 1),
      nuP ((mCorePresentation α h hα).mark (.wild j)) = 1)
    (exactLifting : ExactLiftingSemantics (GammaR (2 + 2 * h) q (mCompactW α h))
      (2 + 2 * h) q (DM α h) nuP SN)
    (stokes : StokesDualityCertificate (GammaR (2 + 2 * h) q (mCompactW α h)) (2 + 2 * h) q
      (DM α h) nuP SN (scalarActionZmodTwo _))
    (scalar : ScalarHilbertCertificate (GammaR (2 + 2 * h) q (mCompactW α h)) (2 + 2 * h) SN
      (scalarActionZmodTwo _))
    (determinant : AffineDeterminantCertificate (GammaR (2 + 2 * h) q (mCompactW α h))
      (2 + 2 * h) q (DM α h) nuP SN
      (tameOfSpec (2 + 2 * h) q (mCompactW α h) (mTameSpecializes α h q hq0 hqe))
      (mPro2 α h q hα hq0 hqe)
      (mCompat α h q hα hq0 hqe (mTameSpecializes α h q hq0 hqe) nuP hnuSigma hnuWild)
      (scalarActionZmodTwo _)) :
    WordCertificate (2 + 2 * h) q (mCompactW α h) (DM α h) (isProP_DM α h) nuP SN where
  tameSpecialization := mTameSpecializes α h q hq0 hqe
  coreRel := mCoreRel α h
  proTwoWord := fun G _ _ _ _ _ t => mProTwoWord α h hα G t
  pro2 := mPro2 α h q hα hq0 hqe
  ker_pro2 := ker_mPro2 α h q hα hq0 hqe
  hpro2 := mPro2_surjective α h q hα hq0 hqe
  compat := mCompat α h q hα hq0 hqe (mTameSpecializes α h q hq0 hqe) nuP hnuSigma hnuWild
  tfg := Count.gammaR_topologicallyFinitelyGenerated _ _ _
  smulZmod2 := scalarActionZmodTwo _
  contSMulZmod2 := scalarActionZmodTwo_continuousSMul _
  htriv := scalarActionZmodTwo_triv _
  exactLifting := exactLifting
  stokes := stokes
  scalar := scalar
  determinant := determinant
  htame := Count.htame_of_tameSpecializes _
  hwild := Count.hwild_mCompact _

end Certificate

/-! ## §5 The two `hsimp` fold-ins, compact-`M` row

Each frozen row carries a single per-simple-module Stokes-duality hypothesis `hsimp`
(`Certificates/M0.lean:833`), carried by all five closers and discharged by none; the owner's
ruling is that it stays an **explicit hypothesis binder**, never an axiom.  What AS3 owes is the
book-keeping: the two shapes the count lane's consumers actually ask for.

Both are one application of WM0-b's `mCompact_stokesDuality` at a different coefficient module,
and both are *derivations from `hsimp`*, not new assumptions. -/

section Hsimp

universe u

variable {C : Type*} [Group C] [Finite C] {α h q e : ℕ}

/-- **Fold-in (a): the `T`-payload**, in the shape `Count.hsepN_marking` / `hsep_field_goal_marking`
consume (`Count/Marking.lean:387,498` — the binder `hd : StokesDuality cM w (Additive ↥D.T)`).

`2`-torsion of `Additive ↥D.T` is a theorem (`Count.radT_add_self`), so the only inputs beyond
`hsimp` are the row's own gate-level relator values. -/
theorem mStokesDuality_T (t : Marking (2 + 2 * h) C) (hq : Even q) (he : Odd e)
    (hrt : PWord.evalZ ⇑t (fun _ => (e : ℤ)) (fun _ => (e : ℤ)) (tameRelW (2 + 2 * h) q) = 1)
    (hrw : PWord.evalZ ⇑t (fun _ => (e : ℤ)) (fun _ => (e : ℤ)) (mCompactW α h) = 1)
    (hsimp : ∀ (V : Type) [AddCommGroup V] [DistribMulAction C V] [Finite V],
      (∀ v : V, v + v = 0) → IsSimpleModTwo C V → StokesDuality ⇑t (mCompactFam α h q e) V)
    {Bg : Type} [Group Bg] [TopologicalSpace Bg] [DiscreteTopology Bg] [Finite Bg]
    (D : RadicalCoverData Bg) [DistribMulAction C (Additive ↥D.T)] :
    StokesDuality ⇑t (mCompactFam α h q e) (Additive ↥D.T) :=
  mCompact_stokesDuality t hq he hrt hrw hsimp _
    (Count.radT_add_self D)

/-- **Fold-in (b): the `Vmod`-payload**, in the shape `Count/Marking.lean` §5 consumes
(`isRightSeparating_vmod_mCompactFam`'s binder
`hsd : IsSelfDualN n c (mCompactFam α h q (omega2Exp (vmodLevel DD))) DD.Vmod`).

Two steps: `hsimp` gives `StokesDuality` at `DD.Vmod` (whose `2`-torsion is `Count.Vmod_exp2`),
then CB-S's `isSelfDualN_of_stokesDuality` promotes it, at the degree bookkeeping
`Count.nCompact_degree` — which is the *alphabet's* degree lemma, shared by every rank-`(4+2h)`
row, not a compact-`N` fact. -/
theorem mIsSelfDualN_Vmod (t : Marking (2 + 2 * h) C) (hq : Even q) (he : Odd e)
    (hrt : PWord.evalZ ⇑t (fun _ => (e : ℤ)) (fun _ => (e : ℤ)) (tameRelW (2 + 2 * h) q) = 1)
    (hrw : PWord.evalZ ⇑t (fun _ => (e : ℤ)) (fun _ => (e : ℤ)) (mCompactW α h) = 1)
    (hsimp : ∀ (V : Type) [AddCommGroup V] [DistribMulAction C V] [Finite V],
      (∀ v : V, v + v = 0) → IsSimpleModTwo C V → StokesDuality ⇑t (mCompactFam α h q e) V)
    {Bg : Type} [Group Bg] [TopologicalSpace Bg] [DiscreteTopology Bg] [Finite Bg]
    {D : RadicalCoverData Bg} (DD : DescData D) [DistribMulAction C DD.Vmod]
    (hr : ∀ k, FreeGroup.lift ⇑t (mCompactFam α h q e k) = 1) :
    IsSelfDualN (2 * h + 2) ⇑t (mCompactFam α h q e) DD.Vmod :=
  Count.isSelfDualN_of_stokesDuality (Count.nCompact_degree h)
    (mCompact_stokesDuality t hq he hrt hrw hsimp _ (Vmod_exp2 DD))
    hr (mCompact_isStokesEndpoint hq he)

end Hsimp

end MCompactCore

end CompactM

/-! # The procyclic-`M` branch layer

Hoisted verbatim from `GQ2/Dyadic/Instances/Sqrt10.lean` §1–§5 (ticket AS3-b, pure move). -/

section ProcyclicM

open GQ2 GQ2.Dyadic GQ2.Dyadic.Count GQ2.Dyadic.MarkedCore GQ2.SectionEight
open GQ2.Dyadic.Words GQ2.Dyadic.Words.Mpc
open GQ2.Dyadic.Count.PilotN TameSpec
open SectionSeven AffineTLift CentralObstruction ContCoh FoxH
open GQ2.Dyadic.Certificates GQ2.Dyadic.Certificates.MProcyclic
open GQ2.Dyadic.Instances.NuWitness

/-! ## §1 The procyclic-`M` alphabet ↔ core dictionary (at `η = 1`)

`Words/Mpc.lean`'s `eval_pro2_mpcW` reads the pro-`2` boundary as
`mWord α A B C₀ D · handleWord …` with `A = x₀⁻¹(x₂σ^s)^{-m}`, `B = x₁σ^p`, `C₀ = x₂σ^s`,
`D = σ^{η̂}`.  The letter table below is built from scratch — see the module docstring for why it
cannot be the compact one relabelled. -/

namespace MProcyclicCore

variable {G : Type*} [Group G]

/-! ### The dictionary is built at `h = 0`

Both AS3 procyclic rows are `h = 0` (`Words/Mpc.lean`'s `rawMpcSqrt10 = rawMpc 2 1 0 .one 0`
and `rawMpcSqrtNeg10 = rawMpc 2 1 1 .one 0`), so the dictionary is stated there.  That is not
only a convenience: at `h = 0` the core index type `Fin (coreRank 0)` is `Fin 4` on the nose and
the alphabet index type is `Fin 3`, so every `Fin` numeral reduces and the four `CoreReindex`
obligations are `fin_cases` plus `group`.  At symbolic `h` the same statements are blocked on
`(k : Fin (2 + 2h + 1)).val = k % (2h + 3)`, which does not reduce — the compact lane escapes
that only because it factors through `nReindex`, whose index lemmas were already paid for.
⚠ **Recorded for the board**: a general-`h` procyclic dictionary is a real (if routine) extra
cost, and no frozen instance needs it. -/

/-- **The procyclic-`M` core marking of an alphabet marking**, at the display `η = 1` and
`h = 0`: `(A, B, C₀, D) = (x₀⁻¹C₀^{-m}, x₁σ^p, x₂σ^s, σ)`.  Stated with no topological
hypotheses, so `WordCertificate.coreRel` can be built from it. -/
def mpcCoreMark (α r pp : ℕ) (t : Marking (2 + 2 * 0) G) : Fin (coreRank 0) → G :=
  ![(t.x 0)⁻¹ * ((t.x 2 * t.σ ^ s r) ^ m α)⁻¹, t.x 1 * t.σ ^ pp, t.x 2 * t.σ ^ s r, t.σ]

/-- **The inverse dictionary.**  `σ` is read off core slot `3` — which is exactly where `η = 1`
is used (`σ^{η̂} = σ`); `x₀, x₁, x₂` are then untwisted against it. -/
def mpcOfCore (α r pp : ℕ) (c : Fin (coreRank 0) → G) : Marking (2 + 2 * 0) G :=
  Marking.ofLetters (c 3) 1 ![(c 0 * c 2 ^ m α)⁻¹, c 1 * (c 3 ^ pp)⁻¹, c 2 * (c 3 ^ s r)⁻¹]

section Accessors

variable (α r pp : ℕ) (t : Marking (2 + 2 * 0) G) (c : Fin (coreRank 0) → G)

@[simp] theorem mpcCoreMark_zero :
    mpcCoreMark α r pp t 0 = (t.x 0)⁻¹ * ((t.x 2 * t.σ ^ s r) ^ m α)⁻¹ := rfl
@[simp] theorem mpcCoreMark_one : mpcCoreMark α r pp t 1 = t.x 1 * t.σ ^ pp := rfl
@[simp] theorem mpcCoreMark_two : mpcCoreMark α r pp t 2 = t.x 2 * t.σ ^ s r := rfl
@[simp] theorem mpcCoreMark_three : mpcCoreMark α r pp t 3 = t.σ := rfl

@[simp] theorem mpcOfCore_sigma : (mpcOfCore α r pp c).σ = c 3 := rfl
@[simp] theorem mpcOfCore_tau : (mpcOfCore α r pp c).τ = 1 := rfl
@[simp] theorem mpcOfCore_x_zero : (mpcOfCore α r pp c).x 0 = (c 0 * c 2 ^ m α)⁻¹ := rfl
@[simp] theorem mpcOfCore_x_one : (mpcOfCore α r pp c).x 1 = c 1 * (c 3 ^ pp)⁻¹ := rfl
@[simp] theorem mpcOfCore_x_two : (mpcOfCore α r pp c).x 2 = c 2 * (c 3 ^ s r)⁻¹ := rfl

end Accessors

/-- Core-index case split at `h = 0`: `coreRank 0 = 4`. -/
theorem coreIdx_cases (i : Fin (coreRank 0)) : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 := by
  have hlt : (i : ℕ) < 4 := by have := i.isLt; simpa only [coreRank] using this
  interval_cases hv : (i : ℕ)
  exacts [Or.inl (Fin.ext (by rw [hv]; rfl)), Or.inr (Or.inl (Fin.ext (by rw [hv]; rfl))),
    Or.inr (Or.inr (Or.inl (Fin.ext (by rw [hv]; rfl)))),
    Or.inr (Or.inr (Or.inr (Fin.ext (by rw [hv]; rfl))))]

/-- Alphabet wild-index case split at `h = 0`: `2 + 2·0 + 1 = 3`. -/
theorem wildIdx_cases (j : Fin (2 + 2 * 0 + 1)) : j = 0 ∨ j = 1 ∨ j = 2 := by
  have hlt : (j : ℕ) < 3 := j.isLt
  interval_cases hv : (j : ℕ)
  exacts [Or.inl (Fin.ext (by rw [hv]; rfl)), Or.inr (Or.inl (Fin.ext (by rw [hv]; rfl))),
    Or.inr (Or.inr (Fin.ext (by rw [hv]; rfl)))]

theorem mpcCoreMark_mpcOfCore (α r pp : ℕ) (c : Fin (coreRank 0) → G) :
    mpcCoreMark α r pp (mpcOfCore α r pp c) = c := by
  funext i
  obtain rfl | rfl | rfl | rfl := coreIdx_cases i
  · rw [mpcCoreMark_zero, mpcOfCore_x_zero, mpcOfCore_x_two, mpcOfCore_sigma]; group
  · rw [mpcCoreMark_one, mpcOfCore_x_one, mpcOfCore_sigma]; group
  · rw [mpcCoreMark_two, mpcOfCore_x_two, mpcOfCore_sigma]; group
  · rw [mpcCoreMark_three, mpcOfCore_sigma]

theorem mpcOfCore_mpcCoreMark (α r pp : ℕ) (t : Marking (2 + 2 * 0) G) (ht : t.τ = 1) :
    mpcOfCore α r pp (mpcCoreMark α r pp t) = t := by
  ext g
  cases g with
  | sigma =>
    show (mpcOfCore α r pp (mpcCoreMark α r pp t)).σ = t.σ
    rw [mpcOfCore_sigma, mpcCoreMark_three]
  | tau => exact ht.symm
  | wild j =>
    show (mpcOfCore α r pp (mpcCoreMark α r pp t)).x j = t.x j
    obtain rfl | rfl | rfl := wildIdx_cases j
    · rw [mpcOfCore_x_zero, mpcCoreMark_zero, mpcCoreMark_two]; group
    · rw [mpcOfCore_x_one, mpcCoreMark_one, mpcCoreMark_three]; group
    · rw [mpcOfCore_x_two, mpcCoreMark_two, mpcCoreMark_three]; group

theorem map_mpcCoreMark {H : Type*} [Group H] {F : Type*} [FunLike F G H] [MonoidHomClass F G H]
    (f : F) (α r pp : ℕ) (t : Marking (2 + 2 * 0) G) (k : Fin (coreRank 0)) :
    f (mpcCoreMark α r pp t k) = mpcCoreMark α r pp (t.map ⇑f) k := by
  obtain rfl | rfl | rfl | rfl := coreIdx_cases k
  · rw [mpcCoreMark_zero, mpcCoreMark_zero]
    simp only [Marking.map_σ, Marking.map_x, map_mul, map_inv, map_pow]
  · rw [mpcCoreMark_one, mpcCoreMark_one]
    simp only [Marking.map_σ, Marking.map_x, map_mul, map_pow]
  · rw [mpcCoreMark_two, mpcCoreMark_two]
    simp only [Marking.map_σ, Marking.map_x, map_mul, map_pow]
  · rw [mpcCoreMark_three, mpcCoreMark_three, Marking.map_σ]

theorem map_mpcOfCore {H : Type*} [Group H] {F : Type*} [FunLike F G H] [MonoidHomClass F G H]
    (f : F) (α r pp : ℕ) (c : Fin (coreRank 0) → G) (g : Generator (2 + 2 * 0)) :
    f (mpcOfCore α r pp c g) = mpcOfCore α r pp (fun k => f (c k)) g := by
  cases g with
  | sigma => rfl
  | tau => exact map_one f
  | wild j =>
    show f ((mpcOfCore α r pp c).x j) = (mpcOfCore α r pp fun k => f (c k)).x j
    obtain rfl | rfl | rfl := wildIdx_cases j
    · rw [mpcOfCore_x_zero, mpcOfCore_x_zero]; simp only [map_inv, map_mul, map_pow]
    · rw [mpcOfCore_x_one, mpcOfCore_x_one]; simp only [map_mul, map_inv, map_pow]
    · rw [mpcOfCore_x_two, mpcOfCore_x_two]; simp only [map_mul, map_inv, map_pow]

/-- **The procyclic-`M` dictionary**, at the display `η = 1` and `h = 0`. -/
noncomputable def mpcReindex (α r pp : ℕ) : CoreReindex (2 + 2 * 0) (Fin (coreRank 0)) where
  toCore := fun t => mpcCoreMark α r pp t
  ofCore := fun c => mpcOfCore α r pp c
  ofCore_tau := fun _ => rfl
  toCore_ofCore := fun c => mpcCoreMark_mpcOfCore α r pp c
  ofCore_toCore := fun t ht => mpcOfCore_mpcCoreMark α r pp t ht
  toCore_nat := fun f t k => map_mpcCoreMark f α r pp t k
  ofCore_nat := fun f c g => map_mpcOfCore f α r pp c g

/-! ## §2 The two word-level fields -/

/-- **`WordCertificate.coreRel` at the procyclic-`M` row.** -/
def mpcCoreRel (α r pp : ℕ) (G : Type) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [TotallyDisconnectedSpace G] (t : Marking (2 + 2 * 0) G) : G :=
  mRelWord α (mpcCoreMark α r pp t)

/-- **`WordCertificate.proTwoWord` at the procyclic-`M` row**, i.e. WMP-a's Gate-C headline
`eval_pro2_mpcW_zero` (`GQ2/Dyadic/Words/Mpc.lean`) read through §1's dictionary.  The `η = 1`
step is `Zhat.ofInt 1` followed by `zpow_one` — the one place the display's invertibility is
used. -/
theorem mpcProTwoWord (α r pp : ℕ) (hα : 1 ≤ α) (G : Type) [Group G] [TopologicalSpace G]
    [IsTopologicalGroup G] [CompactSpace G] [TotallyDisconnectedSpace G]
    (t : Marking (2 + 2 * 0) G) :
    t.eval (pro2 (mpcW α r pp .one 0)) = mpcCoreRel α r pp G t := by
  rw [eval_pro2_mpcW_zero hα r pp .one t]
  show _ = mRelWord α (mpcCoreMark α r pp t)
  rw [mRelWord, show handleWord (fun j : Fin 0 => mpcCoreMark α r pp t (handleIdxU j))
      (fun j : Fin 0 => mpcCoreMark α r pp t (handleIdxV j)) = 1 from rfl, mul_one]
  rw [mpcCoreMark_zero, mpcCoreMark_one, mpcCoreMark_two, mpcCoreMark_three]
  simp only [EtaDisplay.zhat, zpowHat_ofInt, zpow_one]

/-- The same statement in the shape `CorePresentation.ofPresentedBy` consumes. -/
theorem eval_pro2_mpcW_reindex (α r pp : ℕ) (hα : 1 ≤ α) {G : Type} [Group G]
    [TopologicalSpace G] [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    [TotallyDisconnectedSpace G] (t : Marking (2 + 2 * 0) G) :
    t.eval (pro2 (mpcW α r pp .one 0)) = (mNatWord α 0).ev ((mpcReindex α r pp).toCore t) :=
  mpcProTwoWord α r pp hα G t

/-- **The procyclic-`M` core presentation.**  Same core `D_M` as the compact row — both branches
specialize to `MarkedCore.mWord` — with §1's dictionary in place of the compact one. -/
noncomputable def mpcCorePresentation (α r pp : ℕ) (hα : 1 ≤ α) :
    CorePresentation (2 + 2 * 0) (mpcW α r pp .one 0) (DM α 0) :=
  CorePresentation.ofPresentedBy (isProP_DM α 0) (presentedBy_DM α 0) (dm_relation α 0)
    (mpcReindex α r pp) (fun t => eval_pro2_mpcW_reindex α r pp hα t)

/-- The dictionary sends `σ` to core generator **`3`** — not `2`, as in the compact row.  This is
the σ-offset convention, at the level of the marking, and it is why the procyclic Gram is 4×4
against the compact 5×5. -/
@[simp] theorem mpcCorePresentation_mark_sigma (α r pp : ℕ) (hα : 1 ≤ α) :
    (mpcCorePresentation α r pp hα).mark .sigma = dmGen α 0 3 := rfl

/-- …and the wild letters to the untwisted core generators: `x₀ ↦ (μ₀μ₂^m)⁻¹`, `x₁ ↦ μ₁μ₃^{-p}`,
`x₂ ↦ μ₂μ₃^{-s}`.  This is what `hnuWild` below is a condition on. -/
@[simp] theorem mpcCorePresentation_mark_wild (α r pp : ℕ) (hα : 1 ≤ α) (j : Fin (2 + 2 * 0 + 1)) :
    (mpcCorePresentation α r pp hα).mark (.wild j) = (mpcOfCore α r pp (dmGen α 0)).x j := rfl

/-! ## §3 The four pro-`2` fields -/

section ProTwo

/-- **`WordCertificate.pro2`.** -/
noncomputable def mpcPro2 (α r pp q : ℕ) (hα : 1 ≤ α) (hq0 : q ≠ 0) (hqe : Even q) :
    ContinuousMonoidHom ((GammaR (2 + 2 * 0) q (mpcW α r pp .one 0)) : Type)
      ((DM α 0 : ProfiniteGrp) : Type) :=
  CorePresentation.coreHom (mpcCorePresentation α r pp hα) hq0 hqe

/-- **`WordCertificate.ker_pro2`.** -/
theorem ker_mpcPro2 (α r pp q : ℕ) (hα : 1 ≤ α) (hq0 : q ≠ 0) (hqe : Even q) :
    (mpcPro2 α r pp q hα hq0 hqe).toMonoidHom.ker
      = proPKernel 2 ((GammaR (2 + 2 * 0) q (mpcW α r pp .one 0)) : Type) :=
  CorePresentation.ker_coreHom (mpcCorePresentation α r pp hα) hq0 hqe

/-- **`WordCertificate.hpro2`.** -/
theorem mpcPro2_surjective (α r pp q : ℕ) (hα : 1 ≤ α) (hq0 : q ≠ 0) (hqe : Even q) :
    Function.Surjective (mpcPro2 α r pp q hα hq0 hqe) :=
  CorePresentation.coreHom_surjective (mpcCorePresentation α r pp hα) hq0 hqe

/-- **`WordCertificate.tameSpecialization` at the procyclic-`M` row.**  ⚠ This is the branch
whose Gate-B line genuinely needs `1 ≤ α` (CB-0's note: "the only branch needing `1 ≤ α`"). -/
theorem mpcTameSpecializes (α r pp q : ℕ) (hα : 1 ≤ α) (hq0 : q ≠ 0) (hqe : Even q) :
    TameSpecializes (2 + 2 * 0) q (mpcW α r pp .one 0) :=
  Count.tameSpecializes_mpcW hq0 hqe hα r pp .one 0

/-- **`WordCertificate.compat`**, against F3b's `tameOfSpec`. -/
theorem mpcCompat (α r pp q : ℕ) (hα : 1 ≤ α) (hq0 : q ≠ 0) (hqe : Even q)
    (hspec : TameSpecializes (2 + 2 * 0) q (mpcW α r pp .one 0))
    (nuP : ContinuousMonoidHom ((DM α 0 : ProfiniteGrp) : Type) Ztwo)
    (hnuSigma : nuP ((mpcCorePresentation α r pp hα).mark .sigma) = ztwoOne)
    (hnuWild : ∀ j : Fin (2 + 2 * 0 + 1),
      nuP ((mpcCorePresentation α r pp hα).mark (.wild j)) = 1)
    (g : ((GammaR (2 + 2 * 0) q (mpcW α r pp .one 0)) : Type)) :
    nuTq q (tameOfSpec (2 + 2 * 0) q (mpcW α r pp .one 0) hspec g)
      = nuP (mpcPro2 α r pp q hα hq0 hqe g) :=
  CorePresentation.nu_compat_coreHom (mpcCorePresentation α r pp hα) hq0 hqe hspec nuP
    hnuSigma hnuWild g

/-! ### The `ν_P` witness at the procyclic-`M` row  (ticket AS3-b)

The procyclic twin of `MCompactCore`'s witness, and the σ-offset convention is visible in it: `σ`
sits at core slot **3**, so it is slot 3 that carries exponent `1`, and the *twisted* boundary
letter `C₀ = x₂σ^s` at slot 2 carries `s` rather than `1`.  The exponent vector is
`ν(μ₃, μ₂, μ₁, μ₀) = (1, s, p, −ms)`; the relation vector `2·(−ms) + 2^α·s = s(2^α − 2m)` vanishes
by `two_mul_m`, and the three wild conditions are the three untwistings cancelling exactly.
The machinery is in `GQ2/Dyadic/Instances/Cores.lean`. -/

/-- **The procyclic-`M` ν-exponent vector**: `ν(μ₃) = 1`, `ν(μ₂) = s`, `ν(μ₁) = p`,
`ν(μ₀) = −ms`. -/
def mpcNuExp (α r pp : ℕ) : Fin (coreRank 0) → ℤ :=
  ![-((m α : ℤ) * (s r : ℤ)), (pp : ℤ), (s r : ℤ), 1]

@[simp] theorem mpcNuExp_zero (α r pp : ℕ) : mpcNuExp α r pp 0 = -((m α : ℤ) * (s r : ℤ)) := rfl
@[simp] theorem mpcNuExp_one (α r pp : ℕ) : mpcNuExp α r pp 1 = (pp : ℤ) := rfl
@[simp] theorem mpcNuExp_two (α r pp : ℕ) : mpcNuExp α r pp 2 = (s r : ℤ) := rfl
@[simp] theorem mpcNuExp_three (α r pp : ℕ) : mpcNuExp α r pp 3 = 1 := rfl

/-- The relation vector vanishes — `2m = 2^α` scaled by `s`, so the branch's `1 ≤ α` is again the
only arithmetic input. -/
theorem mpcNuExp_rel (α r pp : ℕ) (hα : 1 ≤ α) :
    2 * mpcNuExp α r pp 0 + 2 ^ α * mpcNuExp α r pp 2 = 0 := by
  have h2 : ((2 * m α : ℕ) : ℤ) = ((2 ^ α : ℕ) : ℤ) := congrArg _ (two_mul_m hα)
  push_cast at h2
  rw [mpcNuExp_zero, mpcNuExp_two, mul_neg, ← h2]
  ring

/-- **The `ν_P` witness at the procyclic-`M` row.** -/
noncomputable def mpcNu (α r pp : ℕ) (hα : 1 ≤ α) :
    ContinuousMonoidHom ((DM α 0 : ProfiniteGrp) : Type) Ztwo :=
  dmNu α 0 (mpcNuExp α r pp) (mpcNuExp_rel α r pp hα)

/-- **`hnuSigma` at the witness** — core slot `3`, the σ-offset. -/
theorem mpcNu_sigma (α r pp : ℕ) (hα : 1 ≤ α) :
    mpcNu α r pp hα ((mpcCorePresentation α r pp hα).mark .sigma) = ztwoOne := by
  rw [mpcCorePresentation_mark_sigma, mpcNu, dmNu_dmGen, mpcNuExp_three, zpow_one]

/-- **`hnuWild` at the witness**: `x₀ ↦ (μ₀μ₂^m)⁻¹` gives `−(−ms + sm) = 0`, `x₁ ↦ μ₁μ₃^{−p}`
gives `p − p = 0`, and `x₂ ↦ μ₂μ₃^{−s}` gives `s − s = 0`. -/
theorem mpcNu_wild (α r pp : ℕ) (hα : 1 ≤ α) (j : Fin (2 + 2 * 0 + 1)) :
    mpcNu α r pp hα ((mpcCorePresentation α r pp hα).mark (.wild j)) = 1 := by
  rw [mpcCorePresentation_mark_wild]
  obtain rfl | rfl | rfl := wildIdx_cases j
  · rw [mpcOfCore_x_zero, mpcNu, map_inv, map_mul, map_pow, dmNu_dmGen, dmNu_dmGen,
      mpcNuExp_zero, mpcNuExp_two, ← zpow_natCast (ztwoOne ^ ((s r : ℤ))) (m α), ← zpow_mul,
      ← zpow_add, show -((m α : ℤ) * (s r : ℤ)) + (s r : ℤ) * ((m α : ℕ) : ℤ) = 0 by ring,
      zpow_zero, inv_one]
  · rw [mpcOfCore_x_one, mpcNu, map_mul, map_inv, map_pow, dmNu_dmGen, dmNu_dmGen,
      mpcNuExp_one, mpcNuExp_three, zpow_one, ← zpow_natCast ztwoOne pp, mul_inv_cancel]
  · rw [mpcOfCore_x_two, mpcNu, map_mul, map_inv, map_pow, dmNu_dmGen, dmNu_dmGen,
      mpcNuExp_two, mpcNuExp_three, zpow_one, ← zpow_natCast ztwoOne (s r), mul_inv_cancel]

/-- **`hnuP` at the witness**: `ν(μ₃) = 1` puts `ztwoOne` in the image. -/
theorem mpcNu_surjective (α r pp : ℕ) (hα : 1 ≤ α) : Function.Surjective (mpcNu α r pp hα) :=
  dmNu_surjective α 0 _ _ (i := 3) (mpcNuExp_three α r pp)

end ProTwo

/-! ## §4 The procyclic-`M` word certificate, modulo AS1's four analytic clauses -/

section Certificate

/-- **The procyclic-`M` word certificate** at the display `η = 1`, `h = 0`.  Thirteen of the
seventeen fields proved; the four arguments are AS1's analytic clauses at exactly the record's
types. -/
noncomputable def mpcWordCertificate (α r pp q : ℕ) (hα : 1 ≤ α) (hq0 : q ≠ 0) (hqe : Even q)
    {SN : SourceNumerics (2 + 2 * 0)}
    (nuP : ContinuousMonoidHom ((DM α 0 : ProfiniteGrp) : Type) Ztwo)
    (hnuSigma : nuP ((mpcCorePresentation α r pp hα).mark .sigma) = ztwoOne)
    (hnuWild : ∀ j : Fin (2 + 2 * 0 + 1),
      nuP ((mpcCorePresentation α r pp hα).mark (.wild j)) = 1)
    (exactLifting : ExactLiftingSemantics (GammaR (2 + 2 * 0) q (mpcW α r pp .one 0))
      (2 + 2 * 0) q (DM α 0) nuP SN)
    (stokes : StokesDualityCertificate (GammaR (2 + 2 * 0) q (mpcW α r pp .one 0)) (2 + 2 * 0) q
      (DM α 0) nuP SN (scalarActionZmodTwo _))
    (scalar : ScalarHilbertCertificate (GammaR (2 + 2 * 0) q (mpcW α r pp .one 0)) (2 + 2 * 0) SN
      (scalarActionZmodTwo _))
    (determinant : AffineDeterminantCertificate (GammaR (2 + 2 * 0) q (mpcW α r pp .one 0))
      (2 + 2 * 0) q (DM α 0) nuP SN
      (tameOfSpec (2 + 2 * 0) q (mpcW α r pp .one 0) (mpcTameSpecializes α r pp q hα hq0 hqe))
      (mpcPro2 α r pp q hα hq0 hqe)
      (mpcCompat α r pp q hα hq0 hqe (mpcTameSpecializes α r pp q hα hq0 hqe) nuP hnuSigma
        hnuWild)
      (scalarActionZmodTwo _)) :
    WordCertificate (2 + 2 * 0) q (mpcW α r pp .one 0) (DM α 0) (isProP_DM α 0) nuP SN where
  tameSpecialization := mpcTameSpecializes α r pp q hα hq0 hqe
  coreRel := mpcCoreRel α r pp
  proTwoWord := fun G _ _ _ _ _ t => mpcProTwoWord α r pp hα G t
  pro2 := mpcPro2 α r pp q hα hq0 hqe
  ker_pro2 := ker_mpcPro2 α r pp q hα hq0 hqe
  hpro2 := mpcPro2_surjective α r pp q hα hq0 hqe
  compat := mpcCompat α r pp q hα hq0 hqe (mpcTameSpecializes α r pp q hα hq0 hqe) nuP
    hnuSigma hnuWild
  tfg := Count.gammaR_topologicallyFinitelyGenerated _ _ _
  smulZmod2 := scalarActionZmodTwo _
  contSMulZmod2 := scalarActionZmodTwo_continuousSMul _
  htriv := scalarActionZmodTwo_triv _
  exactLifting := exactLifting
  stokes := stokes
  scalar := scalar
  determinant := determinant
  htame := Count.htame_of_tameSpecializes _
  hwild := Count.hwild_mpcW _

end Certificate

/-! ## §5 The two `hsimp` fold-ins, procyclic-`M` row

The procyclic twins of `MCompactCore`'s pair, through WMP-c's `mpc_stokesDuality`
(`Certificates/MpcStokes.lean:447`), whose `hsimp` slot is verbatim AS1's. -/

section Hsimp

variable {C : Type*} [Group C] [Finite C] {α r pp q e : ℕ}

/-- **Fold-in (a): the `T`-payload**, in the shape `Count.hsepN_marking` /
`hsep_field_goal_marking` consume. -/
theorem mpcStokesDuality_T (t : Marking (2 + 2 * 0) C) (hα : 1 ≤ α) (hq : Even q) (he : Odd e)
    (hrt : PWord.evalZ ⇑t (fun _ => (e : ℤ)) (fun _ => (e : ℤ)) (tameRelW (2 + 2 * 0) q) = 1)
    (hrw : PWord.evalZ ⇑t (fun _ => (e : ℤ)) (fun _ => (e : ℤ)) (mpcW α r pp .one 0) = 1)
    (hsimp : ∀ (V : Type) [AddCommGroup V] [DistribMulAction C V] [Finite V],
      (∀ v : V, v + v = 0) → IsSimpleModTwo C V →
        StokesDuality ⇑t (mpcFam α r pp 0 q e .one) V)
    {Bg : Type} [Group Bg] [TopologicalSpace Bg] [DiscreteTopology Bg] [Finite Bg]
    (D : RadicalCoverData Bg) [DistribMulAction C (Additive ↥D.T)] :
    StokesDuality ⇑t (mpcFam α r pp 0 q e .one) (Additive ↥D.T) :=
  mpc_stokesDuality t hα hq he hrt hrw hsimp _ (Count.radT_add_self D)

/-- **Fold-in (b): the `Vmod`-payload**, in the shape `Count/Marking.lean` §5 consumes
(`isRightSeparating_vmod_mpcFam`'s `hsd` binder). -/
theorem mpcIsSelfDualN_Vmod (t : Marking (2 + 2 * 0) C) (hα : 1 ≤ α) (hq : Even q) (he : Odd e)
    (hrt : PWord.evalZ ⇑t (fun _ => (e : ℤ)) (fun _ => (e : ℤ)) (tameRelW (2 + 2 * 0) q) = 1)
    (hrw : PWord.evalZ ⇑t (fun _ => (e : ℤ)) (fun _ => (e : ℤ)) (mpcW α r pp .one 0) = 1)
    (hsimp : ∀ (V : Type) [AddCommGroup V] [DistribMulAction C V] [Finite V],
      (∀ v : V, v + v = 0) → IsSimpleModTwo C V →
        StokesDuality ⇑t (mpcFam α r pp 0 q e .one) V)
    {Bg : Type} [Group Bg] [TopologicalSpace Bg] [DiscreteTopology Bg] [Finite Bg]
    {D : RadicalCoverData Bg} (DD : DescData D) [DistribMulAction C DD.Vmod]
    (hr : ∀ k, FreeGroup.lift ⇑t (mpcFam α r pp 0 q e .one k) = 1) :
    IsSelfDualN (2 * 0 + 2) ⇑t (mpcFam α r pp 0 q e .one) DD.Vmod :=
  Count.isSelfDualN_of_stokesDuality (Count.nCompact_degree 0)
    (mpc_stokesDuality t hα hq he hrt hrw hsimp _ (Vmod_exp2 DD)) hr
    (mpc_isStokesEndpoint hα hq he)

end Hsimp

end MProcyclicCore

end ProcyclicM

end GQ2.Dyadic.Instances
