/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Fable-5
-/
import GQ2.Dyadic.MarkedCore.Cores
import GQ2.Dyadic.MarkedCore.HandleMix
import GQ2.BoundaryFrame

/-!
# The branch-core layer: the `ν_P` witness at `D_M`  (dyadic campaign, ticket AS3-b)

The four packet-Thm-1.1 instance headlines (`GQ2/Dyadic/Instances/{Sqrt2,Sqrt5,Sqrt10,SqrtNeg10}
.lean`) each carry four binders `nuP`, `hnuSigma`, `hnuWild`, `hnuP` — F3's `prop_3_4_three`
normalization of the abstract slot `(P, ν_P)`, read through the row's alphabet ↔ core dictionary.
AS3 hand-verified that they are satisfiable but could not build the witness.  This file builds it,
once, for **every** row whose core is `D_M`: both AS3 dictionaries land there, and so does every
future compact-`M`/procyclic-`M` instance.

## The witness

`ν_P` is classified by a marking of `D_M` in `Z₂` killing the relator (`presLiftHom`).  Take the
marking to be **powers of a single element**, `μ_i ↦ ztwoOne^{e i}` for an integer vector `e`.
Then two things become free:

* the commutators of `M_α` die — powers of one element commute in *any* group, so no
  commutativity of `Z₂` is needed (`mRelWord_of_commute`, `mRelWord_zpow`); and
* the relator collapses to the single integer condition `2·e₀ + 2^α·e₂ = 0`, which is exactly the
  abelian relation vector `ρ_M = 2Ā + 2^α C̄₀` of `MarkedCore.mRelWord_comm`.

That is `dmNu`.  Surjectivity — the `hnuP` binder — is §1's procyclicity criterion
`surjective_of_ztwoOne_mem_range`: `D_M` is compact and `ztwoOne` is in the image as soon as some
`e i = 1`.

## ⚠ Finding: the commutativity lemma the ticket anticipated is **not needed**

AS3 reported the blocker as "constructing `ν` needs commutativity of `Ztwo`", and a
`maxProPQuotient p G`-is-commutative lemma was authorized as a new declaration in
`GQ2/MaxProP.lean` / `GQ2/BoundaryFrame.lean` — the ticket's one sanctioned exception to the
plan-A6 freeze of the `ℚ₂` development.  **It went unused, and the exception was not exercised**:
routing the marking through a *single* generator's powers replaces group commutativity by
`Commute.zpow_zpow`, which is unconditional.  No frozen file is touched by AS3-b.

## Homing (two recorded debts, both deliberate)

* `mRelWord_of_commute` is a `MarkedCore` fact and belongs beside `MarkedCore.mRelWord_comm`
  (`GQ2/Dyadic/MarkedCore/Cores.lean` §"Abelian collapse"); it is the `Commute`-hypothesis twin
  of that lemma, exactly as `MarkedCore.commP_eq_one_of_commute` is of `Roe.commP_eq_one`.
* §1's two `Z₂` facts belong beside `Ztwo` in `GQ2/BoundaryFrame.lean`.  They are stated here
  instead because that file is frozen (plan A6) and an addition to it forces a rebuild of the
  entire downstream tree for no mathematical gain; the Dyadic tree already proves `Ztwo`-valued
  facts freely (`GQ2/Dyadic/TameQuotientK.lean`'s `nuTq`, `GQ2/Dyadic/SqCore/Certificate.lean`'s
  `nuDR_sqEquivDRMarked`), so this is ordinary layering, not a duplicate.

Both are for a later dedup/hoist ticket that has the destination file in scope — the standing
`GQ2/Dyadic/Count/Scalar.lean` ruling.

## Axioms

`sorry`-free, no new axiom, no `decide`.  Every declaration prints exactly the standard three.
-/

namespace GQ2.Dyadic.Instances

open GQ2 GQ2.Dyadic GQ2.Dyadic.MarkedCore

namespace NuWitness

/-! ## §1 `Z₂` is procyclic, topologically generated by `ztwoOne`

`ℤ` is dense in `ℤ̂` (`Zhat.denseRange_ofInt`) and `Zhat.ofInt n = Zhat.ofInt 1 ^ n`, so the
powers of `ztwoOne` are dense in `Z₂ = maxProPQuotient 2 ℤ̂`.  The consequence used below is the
**surjectivity criterion**: a continuous homomorphism from a *compact* group into `Z₂` is onto as
soon as `ztwoOne` lies in its image — the image is then a closed set containing a dense one.
This is what discharges the `hnuP : Function.Surjective ν_P` binder of the four field headlines. -/

private theorem zhat_ofInt_neg (n : ℤ) : Zhat.ofInt (-n) = (Zhat.ofInt n)⁻¹ := by
  rw [eq_inv_iff_mul_eq_one, ← Zhat.ofInt_add, neg_add_cancel, Zhat.ofInt_zero]

private theorem zhat_ofInt_eq_zpow (n : ℤ) : Zhat.ofInt n = Zhat.ofInt 1 ^ n := by
  induction n using Int.induction_on with
  | zero => simp
  | succ k ih => rw [Zhat.ofInt_add, ih, zpow_add_one]
  | pred k ih =>
    rw [show (-(k : ℤ) - 1) = -(k : ℤ) + -1 by ring, Zhat.ofInt_add, ih, zpow_add, zhat_ofInt_neg,
      zpow_neg_one]

/-- **`Z₂` is procyclic**: the integer powers of `ztwoOne` are dense. -/
theorem denseRange_ztwoOne_zpow : DenseRange (fun n : ℤ => ztwoOne ^ n) := by
  have h : (fun n : ℤ => ztwoOne ^ n) = ⇑(maxProPMk 2 Zhat) ∘ Zhat.ofInt := by
    funext n
    show ztwoOne ^ n = maxProPMk 2 Zhat (Zhat.ofInt n)
    rw [zhat_ofInt_eq_zpow, map_zpow]
    rfl
  rw [h]
  exact DenseRange.comp (quotientMk_surjective (proPKernel 2 Zhat)).denseRange
    Zhat.denseRange_ofInt (maxProPMk 2 Zhat).continuous_toFun

/-- **The `Z₂`-surjectivity criterion.**  A continuous homomorphism out of a compact group whose
image contains `ztwoOne` is surjective.  (No hypothesis on the source beyond compactness — not
even that it is a topological group.) -/
theorem surjective_of_ztwoOne_mem_range {D : Type*} [Group D] [TopologicalSpace D]
    [CompactSpace D] (f : ContinuousMonoidHom D Ztwo) (hf : ztwoOne ∈ Set.range f) :
    Function.Surjective f := by
  obtain ⟨d, hd⟩ := hf
  have hcl : IsClosed (Set.range f) := (isCompact_range f.continuous_toFun).isClosed
  have hsub : Set.range (fun n : ℤ => ztwoOne ^ n) ⊆ Set.range f := by
    rintro _ ⟨n, rfl⟩
    exact ⟨d ^ n, by rw [map_zpow, hd]⟩
  rw [← Set.range_eq_univ, ← hcl.closure_eq, (denseRange_ztwoOne_zpow.mono hsub).closure_eq]

/-! ## §2 The relator at a marking by powers of one element -/

/-- **Abelian collapse of the `M_α` relator under a pointwise `Commute` hypothesis** — the twin of
`MarkedCore.mRelWord_comm` with the commutativity localised to the letters, so that it applies in
a group carrying no `CommGroup` instance (such as a `ProfiniteGrp` carrier). -/
theorem mRelWord_of_commute {G : Type*} [Group G] (α : ℕ) {h : ℕ} (c : Fin (coreRank h) → G)
    (hc : ∀ i j, Commute (c i) (c j)) : mRelWord α c = c 0 ^ 2 * c 2 ^ (2 ^ α) := by
  have hhandle : handleWord (fun j => c (handleIdxU j)) (fun j => c (handleIdxV j)) = 1 := by
    rw [handleWord, List.prod_eq_one]
    intro x hx
    obtain ⟨j, _, rfl⟩ := List.mem_map.mp hx
    exact commP_eq_one_of_commute (hc _ _)
  rw [mRelWord, hhandle, mul_one, mWord, commP_eq_one_of_commute (hc 0 1),
    commP_eq_one_of_commute (hc 2 3), mul_one, mul_assoc, one_mul]

/-- The `M_α` relator at a marking `μ_i = x^{e i}` by powers of a single element: the relation
vector `ρ_M = 2Ā + 2^α C̄₀` read as an integer. -/
theorem mRelWord_zpow {G : Type*} [Group G] (α : ℕ) {h : ℕ} (x : G) (e : Fin (coreRank h) → ℤ) :
    mRelWord α (fun i => x ^ e i) = x ^ (2 * e 0 + 2 ^ α * e 2) := by
  rw [mRelWord_of_commute α _ fun i j => (Commute.refl x).zpow_zpow _ _,
    ← zpow_natCast (x ^ e 0) 2, ← zpow_natCast (x ^ e 2) (2 ^ α), ← zpow_mul, ← zpow_mul,
    ← zpow_add]
  congr 1
  push_cast
  ring

/-! ## §3 The witness `ν_P : D_M → Z₂`

The **only** input is the integer condition `2·e₀ + 2^α·e₂ = 0`.  Nothing here is
branch-specific: a branch supplies its own `e` (compact-`M` and procyclic-`M` do so in
`GQ2/Dyadic/Instances/{Sqrt2,Sqrt10}.lean`), and the row's `hnuSigma`/`hnuWild` become
arithmetic in the exponents. -/

/-- **The `ν_P` witness at `D_M`**: the continuous homomorphism `D_M → Z₂` sending the marked
generator `μ_i` to `ztwoOne^{e i}`.  Well-defined exactly when the abelian relation vector
vanishes, `2·e₀ + 2^α·e₂ = 0`. -/
noncomputable def dmNu (α h : ℕ) (e : Fin (coreRank h) → ℤ) (he : 2 * e 0 + 2 ^ α * e 2 = 0) :
    ContinuousMonoidHom ((DM α h : ProfiniteGrp) : Type) Ztwo :=
  presLiftHom (mRelator α h) isProP_maxProPQuotient (fun i => ztwoOne ^ e i) (by
    have h1 : freeHomFin (fun i => ztwoOne ^ e i) (mRelator α h)
        = mRelWord α (fun i => ztwoOne ^ e i) := by
      rw [mRelator, map_mRelWord]
      exact congrArg (mRelWord α) (funext fun i => freeHomFin_of _ i)
    rw [h1, mRelWord_zpow, he, zpow_zero])

@[simp] theorem dmNu_dmGen (α h : ℕ) (e : Fin (coreRank h) → ℤ)
    (he : 2 * e 0 + 2 ^ α * e 2 = 0) (i : Fin (coreRank h)) :
    dmNu α h e he (dmGen α h i) = ztwoOne ^ e i :=
  presLiftHom_gen _ _ _ _ i

/-- **`hnuP` at the witness**: `ν_P` is surjective as soon as some marked generator carries
exponent `1`.  `D_M` is a `ProfiniteGrp`, hence compact, so `BoundaryFrame`'s procyclicity
criterion applies. -/
theorem dmNu_surjective (α h : ℕ) (e : Fin (coreRank h) → ℤ) (he : 2 * e 0 + 2 ^ α * e 2 = 0)
    {i : Fin (coreRank h)} (hi : e i = 1) : Function.Surjective (dmNu α h e he) :=
  surjective_of_ztwoOne_mem_range _ ⟨dmGen α h i, by rw [dmNu_dmGen, hi, zpow_one]⟩

end NuWitness

end GQ2.Dyadic.Instances
