/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using OpenAI Codex
-/
import GQ2.Dyadic.Instances.GammaLSylowPreimageFieldCore

/-!
# Finite-level assembly for the variable-rank square Labute presentation

This file isolates the part of the higher-rank Labute argument which is independent of the
rank-three defect calculation.  At every finite quotient of `G_K(2)`, suppose one has a
surjective marking by the generators of the improved presentation `DSq h`, with the three core
rows equal to the constructor table and the handle rows liftable to the cyclotomic kernel.

The finite sets of such markings form a cofiltered system.  König compactness chooses a coherent
family.  Compactness of `G_K(2)` then realizes the generator coordinates, proves the literal
`SqCore.sqRelWord` relation by separation through finite quotients, proves topological generation,
and keeps every handle in the cyclotomic kernel.  Thus no coherence, inverse-limit, density, or
orientation-limit work remains for a future variable-rank Labute stage theorem.
-/

namespace GQ2.Dyadic.LSquare

noncomputable section

open GQ2 CategoryTheory

local notation "ℚ̄₂" => AlgebraicClosure ℚ_[2]

variable {h : ℕ}

@[simp] private theorem projMap_quotientMk
    {G : Type} [Group G] [TopologicalSpace G]
    {U U' : Subgroup G} [U.Normal] [U'.Normal]
    [DiscreteTopology (G ⧸ U)] (hle : U ≤ U') (x : G) :
    projMap hle (QuotientGroup.mk x) = QuotientGroup.mk x :=
  rfl

@[simp] private theorem projMap_self
    {G : Type} [Group G] [TopologicalSpace G]
    {U : Subgroup G} [U.Normal] [DiscreteTopology (G ⧸ U)] (hle : U ≤ U) :
    projMap hle = ContinuousMonoidHom.id (G ⧸ U) := by
  exact ContinuousMonoidHom.ext fun y ↦ QuotientGroup.induction_on y fun _ ↦ rfl

@[simp] private theorem projMap_comp_apply
    {G : Type} [Group G] [TopologicalSpace G]
    {U U' U'' : Subgroup G} [U.Normal] [U'.Normal] [U''.Normal]
    [DiscreteTopology (G ⧸ U)] [DiscreteTopology (G ⧸ U')]
    (hle : U ≤ U') (hle' : U' ≤ U'') (y : G ⧸ U) :
    projMap hle' (projMap hle y) = projMap (hle.trans hle') y := by
  obtain ⟨x, rfl⟩ := QuotientGroup.mk_surjective y
  rfl

/-! ## Finite-level marked epimorphisms -/

/-- A finite-quotient output of the variable-rank Labute construction.  The homomorphism comes
from the improved presentation `DSq h`; the fields record its literal generator table.  The
handle clauses are deliberately existential: only liftability to `ker χ` is needed, and this
property is preserved on passing to a coarser quotient. -/
structure SqCyclotomicFiniteLevelEpiData
    {K : IntermediateField ℚ_[2] ℚ̄₂} [FiniteDimensional ℚ_[2] K]
    [CompactSpace (GalK K)] [T2Space (GalK K)] [TotallyDisconnectedSpace (GalK K)]
    (T : OddDegreeGalKSqCyclotomicCoreTable K) (h : ℕ)
    (U : OpenNormalSubgroup
      (ProfiniteGrp.of (maxProPQuotient 2 (GalK K)))) where
  epi : ContSurj (SqCore.DSq h : Type)
    ((maxProPQuotient 2 (GalK K)) ⧸ U.toSubgroup)
  sigma : epi.1 (SqCore.dsqSigma h) = QuotientGroup.mk T.sigma
  x0 : epi.1 (SqCore.dsqX0 h) = QuotientGroup.mk T.x0
  x1 : epi.1 (SqCore.dsqX1 h) = QuotientGroup.mk T.x1
  handleU : ∀ j : Fin h, ∃ x : maxProPQuotient 2 (GalK K),
    x ∈ (chiCycKTwo (K := K)).toMonoidHom.ker ∧
      epi.1 (SqCore.sqGen h (SqCore.sqHandleIdxU j)) = QuotientGroup.mk x
  handleV : ∀ j : Fin h, ∃ x : maxProPQuotient 2 (GalK K),
    x ∈ (chiCycKTwo (K := K)).toMonoidHom.ker ∧
      epi.1 (SqCore.sqGen h (SqCore.sqHandleIdxV j)) = QuotientGroup.mk x
  /-- The finite quotient is generated by the displayed improved-presentation tuple. -/
  topGen : Subgroup.closure
    (Set.range fun i ↦ epi.1 (SqCore.sqGen h i)) = ⊤
  /-- Regression field: the relation is literally the improved `sqRelWord`. -/
  relation : SqCore.sqRelWord (fun i ↦ epi.1 (SqCore.sqGen h i)) = 1

namespace SqCyclotomicFiniteLevelEpiData

variable {K : IntermediateField ℚ_[2] ℚ̄₂} [FiniteDimensional ℚ_[2] K]
  [CompactSpace (GalK K)] [T2Space (GalK K)]
  [TotallyDisconnectedSpace (GalK K)]
  {T : OddDegreeGalKSqCyclotomicCoreTable K}
  {U U' : OpenNormalSubgroup
    (ProfiniteGrp.of (maxProPQuotient 2 (GalK K)))}

@[ext] theorem ext
    {D E : SqCyclotomicFiniteLevelEpiData T h U}
    (hepi : D.epi = E.epi) : D = E := by
  cases D
  cases E
  cases hepi
  rfl

/-- Restrict finite-level data along a coarser quotient. -/
noncomputable def map (hle : U ≤ U')
    (D : SqCyclotomicFiniteLevelEpiData T h U) :
    SqCyclotomicFiniteLevelEpiData T h U' where
  epi := ⟨(projMap hle).comp D.epi.1, (projMap_surjective hle).comp D.epi.2⟩
  sigma := by
    change projMap hle (D.epi.1 (SqCore.dsqSigma h)) = QuotientGroup.mk T.sigma
    rw [D.sigma, projMap_quotientMk]
  x0 := by
    change projMap hle (D.epi.1 (SqCore.dsqX0 h)) = QuotientGroup.mk T.x0
    rw [D.x0, projMap_quotientMk]
  x1 := by
    change projMap hle (D.epi.1 (SqCore.dsqX1 h)) = QuotientGroup.mk T.x1
    rw [D.x1, projMap_quotientMk]
  handleU j := by
    obtain ⟨x, hx, hmap⟩ := D.handleU j
    refine ⟨x, hx, ?_⟩
    change projMap hle (D.epi.1 (SqCore.sqGen h (SqCore.sqHandleIdxU j))) =
      QuotientGroup.mk x
    rw [hmap, projMap_quotientMk]
  handleV j := by
    obtain ⟨x, hx, hmap⟩ := D.handleV j
    refine ⟨x, hx, ?_⟩
    change projMap hle (D.epi.1 (SqCore.sqGen h (SqCore.sqHandleIdxV j))) =
      QuotientGroup.mk x
    rw [hmap, projMap_quotientMk]
  topGen := by
    change Subgroup.closure
      (Set.range fun i ↦ projMap hle (D.epi.1 (SqCore.sqGen h i))) = ⊤
    have himage :
        Set.range (fun i ↦ projMap hle (D.epi.1 (SqCore.sqGen h i))) =
          projMap hle '' Set.range (fun i ↦ D.epi.1 (SqCore.sqGen h i)) := by
      ext y
      constructor
      · rintro ⟨i, rfl⟩
        exact ⟨_, ⟨i, rfl⟩, rfl⟩
      · rintro ⟨_, ⟨i, rfl⟩, rfl⟩
        exact ⟨i, rfl⟩
    rw [himage]
    calc
      Subgroup.closure
          (projMap hle '' Set.range (fun i ↦ D.epi.1 (SqCore.sqGen h i))) =
          Subgroup.map (projMap hle).toMonoidHom
            (Subgroup.closure (Set.range fun i ↦ D.epi.1 (SqCore.sqGen h i))) :=
        (MonoidHom.map_closure (projMap hle).toMonoidHom
          (Set.range fun i ↦ D.epi.1 (SqCore.sqGen h i))).symm
      _ = Subgroup.map (projMap hle).toMonoidHom ⊤ := by rw [D.topGen]
      _ = ⊤ := Subgroup.map_top_of_surjective _ (projMap_surjective hle)
  relation := by
    change SqCore.sqRelWord
      (fun i ↦ projMap hle (D.epi.1 (SqCore.sqGen h i))) = 1
    rw [← SqCore.map_sqRelWord (projMap hle)
      (fun i ↦ D.epi.1 (SqCore.sqGen h i)), D.relation, map_one]

/-- Finite-level markings form a cofiltered functor under quotient restriction. -/
noncomputable def functor
    (T : OddDegreeGalKSqCyclotomicCoreTable K) (h : ℕ) :
    OpenNormalSubgroup (ProfiniteGrp.of (maxProPQuotient 2 (GalK K))) ⥤ Type where
  obj U := SqCyclotomicFiniteLevelEpiData T h U
  map {U U'} f := ↾(map (leOfHom f))
  map_id U := by
    apply ConcreteCategory.hom_ext
    intro D
    apply ext
    apply Subtype.ext
    ext x
    simp [map]
  map_comp {U U' U''} f g := by
    apply ConcreteCategory.hom_ext
    intro D
    apply ext
    apply Subtype.ext
    ext x
    simp [map]

/-- Each finite-level data type is finite: it injects into the finite set of continuous
homomorphisms from the topologically finitely generated `DSq h` to the finite quotient. -/
instance finite (T : OddDegreeGalKSqCyclotomicCoreTable K) (h : ℕ)
    (U : OpenNormalSubgroup
      (ProfiniteGrp.of (maxProPQuotient 2 (GalK K)))) :
    Finite (SqCyclotomicFiniteLevelEpiData T h U) := by
  haveI : Finite ((maxProPQuotient 2 (GalK K)) ⧸ U.toSubgroup) :=
    Subgroup.quotient_finite_of_isOpen U.toSubgroup U.isOpen'
  haveI := finite_continuousMonoidHom (dsqFinsetTopGen h)
    ((maxProPQuotient 2 (GalK K)) ⧸ U.toSubgroup)
  exact Finite.of_injective (fun D ↦ D.epi.1) fun D E he ↦
    ext (Subtype.ext he)

end SqCyclotomicFiniteLevelEpiData

/-! ## Compact realization lemmas -/

/-- A closed subgroup of a profinite group contains any element which can be approximated by
that subgroup in every finite quotient. -/
private theorem mem_closedSubgroup_of_finiteQuotient_approximations
    {G : Type} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G]
    (H : Subgroup G) (hH : IsClosed (H : Set G)) (x : G)
    (happrox : ∀ U : OpenNormalSubgroup (ProfiniteGrp.of G),
      ∃ y : G, y ∈ H ∧ QuotientGroup.mk y =
        (QuotientGroup.mk x : G ⧸ U.toSubgroup)) :
    x ∈ H := by
  letI : CompactSpace H := isCompact_iff_compactSpace.mp hH.isCompact
  haveI : Nonempty (OpenNormalSubgroup (ProfiniteGrp.of G)) :=
    ⟨⟨⊤, Subgroup.normal_top⟩⟩
  haveI hdisc : ∀ U : OpenNormalSubgroup (ProfiniteGrp.of G),
      DiscreteTopology (G ⧸ U.toSubgroup) := fun U ↦ inferInstance
  have hnonempty :
      (⋂ U : OpenNormalSubgroup (ProfiniteGrp.of G),
        {y : H | QuotientGroup.mk y.1 =
          (QuotientGroup.mk x : G ⧸ U.toSubgroup)}).Nonempty := by
    apply IsCompact.nonempty_iInter_of_directed_nonempty_isCompact_isClosed
    · intro U U'
      refine ⟨U ⊓ U', fun y hy ↦ ?_, fun y hy ↦ ?_⟩ <;>
        simp only [Set.mem_setOf_eq] at hy ⊢
      · rw [QuotientGroup.eq] at hy ⊢
        exact (show (U ⊓ U').toSubgroup ≤ U.toSubgroup from inf_le_left) hy
      · rw [QuotientGroup.eq] at hy ⊢
        exact (show (U ⊓ U').toSubgroup ≤ U'.toSubgroup from inf_le_right) hy
    · intro U
      obtain ⟨y, hyH, hy⟩ := happrox U
      exact ⟨⟨y, hyH⟩, hy⟩
    · intro U
      exact (isClosed_singleton.preimage
        (continuous_quotient_mk'.comp continuous_subtype_val)).isCompact
    · intro U
      exact isClosed_singleton.preimage
        (continuous_quotient_mk'.comp continuous_subtype_val)
  obtain ⟨y, hy⟩ := hnonempty
  have hyx : y.1 = x := by
    rw [← inv_mul_eq_one]
    apply eq_one_of_forall_mem_openNormalSubgroup
    intro U
    have hq : QuotientGroup.mk y.1 =
        (QuotientGroup.mk x : G ⧸ U.toSubgroup) := Set.mem_iInter.mp hy U
    rw [QuotientGroup.eq] at hq
    exact hq
  rw [← hyx]
  exact y.property

/-! ## König assembly -/

/-- **Finite-level forward assembly.**  Pointwise nonemptiness of the finite improved-relator
marking sets is enough to construct the full cyclotomic forward-generator package.  König's
lemma supplies all compatibility; compactness supplies the global tuple; finite-quotient
separation supplies its relation and topological generation. -/
theorem forwardGeneratorData_of_finiteLevel
    {K : IntermediateField ℚ_[2] ℚ̄₂} [FiniteDimensional ℚ_[2] K]
    [CompactSpace (GalK K)] [T2Space (GalK K)]
    [TotallyDisconnectedSpace (GalK K)]
    (T : OddDegreeGalKSqCyclotomicCoreTable K) (h : ℕ)
    (hne : ∀ U : OpenNormalSubgroup
      (ProfiniteGrp.of (maxProPQuotient 2 (GalK K))),
      Nonempty (SqCyclotomicFiniteLevelEpiData T h U)) :
    Nonempty (SqCyclotomicForwardGeneratorData h (chiCycKTwo (K := K))) := by
  classical
  let Q := maxProPQuotient 2 (GalK K)
  let F := SqCyclotomicFiniteLevelEpiData.functor T h
  haveI hne' : ∀ U : OpenNormalSubgroup (ProfiniteGrp.of Q),
      Nonempty (F.obj U) := hne
  haveI hfin' : ∀ U : OpenNormalSubgroup (ProfiniteGrp.of Q),
      Finite (F.obj U) := fun U ↦ by
    change Finite (SqCyclotomicFiniteLevelEpiData T h U)
    infer_instance
  obtain ⟨sec, hsec⟩ := nonempty_sections_of_finite_cofiltered_system F
  let D : ∀ U : OpenNormalSubgroup (ProfiniteGrp.of Q),
      SqCyclotomicFiniteLevelEpiData T h U := fun U ↦ sec U
  have hcompat : ∀ {U U' : OpenNormalSubgroup (ProfiniteGrp.of Q)} (hle : U ≤ U')
      (i : Fin (SqCore.sqRank h)),
      projMap hle ((D U).epi.1 (SqCore.sqGen h i)) =
        (D U').epi.1 (SqCore.sqGen h i) := by
    intro U U' hle i
    have hs := hsec hle.hom
    exact congrArg
      (fun E : SqCyclotomicFiniteLevelEpiData T h U' ↦
        E.epi.1 (SqCore.sqGen h i)) hs
  haveI : Nonempty (OpenNormalSubgroup (ProfiniteGrp.of Q)) :=
    ⟨⟨⊤, Subgroup.normal_top⟩⟩
  haveI hdisc : ∀ U : OpenNormalSubgroup (ProfiniteGrp.of Q),
      DiscreteTopology (Q ⧸ U.toSubgroup) := fun U ↦ inferInstance
  have hrealise : ∀ i : Fin (SqCore.sqRank h), ∃ g : Q, ∀ U,
      QuotientGroup.mk g = (sec U).epi.1 (SqCore.sqGen h i) := by
    intro i
    have hmeet :
        (⋂ U : OpenNormalSubgroup (ProfiniteGrp.of Q),
          {g : Q | QuotientGroup.mk g =
            (D U).epi.1 (SqCore.sqGen h i)}).Nonempty := by
      apply IsCompact.nonempty_iInter_of_directed_nonempty_isCompact_isClosed
      · intro U U'
        refine ⟨U ⊓ U', fun g hg ↦ ?_, fun g hg ↦ ?_⟩ <;>
          simp only [Set.mem_setOf_eq] at hg ⊢
        · have hle : U ⊓ U' ≤ U := inf_le_left
          rw [← hcompat hle i, ← hg, projMap_quotientMk]
        · have hle : U ⊓ U' ≤ U' := inf_le_right
          rw [← hcompat hle i, ← hg, projMap_quotientMk]
      · intro U
        exact QuotientGroup.mk_surjective ((D U).epi.1 (SqCore.sqGen h i))
      · intro U
        exact (isClosed_singleton.preimage continuous_quotient_mk').isCompact
      · intro U
        exact isClosed_singleton.preimage continuous_quotient_mk'
    obtain ⟨g, hg⟩ := hmeet
    exact ⟨g, fun U ↦ Set.mem_iInter.mp hg U⟩
  let generators : Fin (SqCore.sqRank h) → Q := fun i ↦ (hrealise i).choose
  have hgenerators (U : OpenNormalSubgroup (ProfiniteGrp.of Q))
      (i : Fin (SqCore.sqRank h)) :
      QuotientGroup.mk (generators i) = (D U).epi.1 (SqCore.sqGen h i) :=
    (hrealise i).choose_spec U
  have heq_of_quotients {x y : Q}
      (heq : ∀ U : OpenNormalSubgroup (ProfiniteGrp.of Q),
        (QuotientGroup.mk x : Q ⧸ U.toSubgroup) = QuotientGroup.mk y) : x = y := by
    rw [← inv_mul_eq_one]
    apply eq_one_of_forall_mem_openNormalSubgroup
    intro U
    have hq := heq U
    rw [QuotientGroup.eq] at hq
    exact hq
  have hsigma : generators 0 = T.sigma := by
    apply heq_of_quotients
    intro U
    rw [hgenerators U 0]
    simpa [SqCore.dsqSigma] using (D U).sigma
  have hx0 : generators 1 = T.x0 := by
    apply heq_of_quotients
    intro U
    rw [hgenerators U 1]
    simpa [SqCore.dsqX0] using (D U).x0
  have hx1 : generators 2 = T.x1 := by
    apply heq_of_quotients
    intro U
    rw [hgenerators U 2]
    simpa [SqCore.dsqX1] using (D U).x1
  have hhandleU : ∀ j : Fin h,
      generators (SqCore.sqHandleIdxU j) ∈
        (chiCycKTwo (K := K)).toMonoidHom.ker := by
    intro j
    apply mem_closedSubgroup_of_finiteQuotient_approximations
      (chiCycKTwo (K := K)).toMonoidHom.ker
      (isClosed_singleton.preimage (chiCycKTwo (K := K)).continuous_toFun)
    intro U
    obtain ⟨x, hxker, hx⟩ := (D U).handleU j
    exact ⟨x, hxker, hx.symm.trans (hgenerators U _).symm⟩
  have hhandleV : ∀ j : Fin h,
      generators (SqCore.sqHandleIdxV j) ∈
        (chiCycKTwo (K := K)).toMonoidHom.ker := by
    intro j
    apply mem_closedSubgroup_of_finiteQuotient_approximations
      (chiCycKTwo (K := K)).toMonoidHom.ker
      (isClosed_singleton.preimage (chiCycKTwo (K := K)).continuous_toFun)
    intro U
    obtain ⟨x, hxker, hx⟩ := (D U).handleV j
    exact ⟨x, hxker, hx.symm.trans (hgenerators U _).symm⟩
  have hrelation : SqCore.sqRelWord generators = 1 := by
    apply eq_one_of_forall_mem_openNormalSubgroup
    intro U
    apply (QuotientGroup.eq_one_iff _).mp
    calc
      QuotientGroup.mk (SqCore.sqRelWord generators) =
          SqCore.sqRelWord (fun i ↦ QuotientGroup.mk (generators i)) :=
        SqCore.map_sqRelWord (QuotientGroup.mk' U.toSubgroup) generators
      _ = SqCore.sqRelWord (fun i ↦ (D U).epi.1 (SqCore.sqGen h i)) := by
        congr 1
        funext i
        exact hgenerators U i
      _ = 1 := (D U).relation
  let A : Subgroup Q := Subgroup.closure (Set.range generators)
  let H : Subgroup Q := A.topologicalClosure
  have hHclosed : IsClosed (H : Set Q) := by
    dsimp [H]
    exact Subgroup.isClosed_topologicalClosure A
  have htopGen : H = ⊤ := by
    rw [eq_top_iff]
    intro y _
    apply mem_closedSubgroup_of_finiteQuotient_approximations H hHclosed y
    intro U
    have hy : (QuotientGroup.mk y : Q ⧸ U.toSubgroup) ∈
        Subgroup.closure (Set.range fun i ↦
          (D U).epi.1 (SqCore.sqGen h i)) := by
      rw [(D U).topGen]
      trivial
    have himage :
        Set.range (fun i ↦ (D U).epi.1 (SqCore.sqGen h i)) =
          QuotientGroup.mk' U.toSubgroup '' Set.range generators := by
      ext z
      constructor
      · rintro ⟨i, rfl⟩
        exact ⟨generators i, ⟨i, rfl⟩, hgenerators U i⟩
      · rintro ⟨_, ⟨i, rfl⟩, rfl⟩
        exact ⟨i, (hgenerators U i).symm⟩
    rw [himage, ← MonoidHom.map_closure] at hy
    obtain ⟨z, hzA, hz⟩ := hy
    exact ⟨z, Subgroup.le_topologicalClosure A hzA, hz⟩
  refine ⟨T.toForwardGeneratorData h generators hsigma hx0 hx1 hhandleU hhandleV
    hrelation ?_⟩
  exact htopGen

/-! ## Exact field-level reduction -/

/-- The finite-level theorem which remains for an odd-degree field.  Unlike the earlier
generator-presentation seam, this premise contains no global tuple and no map to `G_K(2)`.
It asks only for nonempty finite sets of improved-relator epimorphisms at every finite quotient,
plus the reverse finite quotients used by the Hopfian endgame.  Marked reciprocity is existential
and explicit, so this interface introduces no axiom and does not name the census supplier. -/
def OddDegreeGalKSqCyclotomicFiniteLevelPresentation : Prop :=
  ∀ (K : IntermediateField ℚ_[2] ℚ̄₂) [FiniteDimensional ℚ_[2] K]
    [CompactSpace (GalK K)] [T2Space (GalK K)]
    [TotallyDisconnectedSpace (GalK K)],
    (hodd : Odd (Module.finrank ℚ_[2] K)) →
      demushkinQ (maxProPQuotient 2 (GalK K)) = 2 →
        ∃ (R : LocalReciprocity) (B : MarkedRecip R K),
          let h := (Module.finrank ℚ_[2] K - 1) / 2
          let T := oddDegreeGalKSqCyclotomicCoreTable K B hodd
          (∀ U : OpenNormalSubgroup
              (ProfiniteGrp.of (maxProPQuotient 2 (GalK K))),
              Nonempty (SqCyclotomicFiniteLevelEpiData T h U)) ∧
            (∀ V : OpenNormalSubgroup (ProfiniteGrp.of (SqCore.DSq h : Type)),
              Nonempty (ContSurj (maxProPQuotient 2 (GalK K))
                ((SqCore.DSq h : Type) ⧸ V.toSubgroup)))

/-- The finite-level presentation supplies the full oriented odd-degree classification.  The
forward inverse limit is `forwardGeneratorData_of_finiteLevel`; the reverse inverse limit and
Hopfian step are the already-proved generic bridges in `GammaLSylowPreimageFieldCore`. -/
theorem oddDegreeGalKSqOrientedLabuteClassification_of_finiteLevelPresentation
    (hfinite : OddDegreeGalKSqCyclotomicFiniteLevelPresentation) :
    OddDegreeGalKSqOrientedLabuteClassification := by
  intro K _ _ _ _ hodd hq
  obtain ⟨R, B, hforward, hbackward⟩ := hfinite K hodd hq
  let h := (Module.finrank ℚ_[2] K - 1) / 2
  let T := oddDegreeGalKSqCyclotomicCoreTable K B hodd
  obtain ⟨D⟩ := forwardGeneratorData_of_finiteLevel T h hforward
  obtain ⟨E⟩ := D.toBiEpiData_of_finiteQuotientSurjections
    isProP_maxProPQuotient hbackward
  exact ⟨orientedEquivSq_of_biEpiData (chiCycKTwo (K := K)) E⟩

/-- Generator-presentation form of the same finite-level reduction. -/
theorem oddDegreeGalKSqGeneratorPresentation_of_finiteLevelPresentation
    (hfinite : OddDegreeGalKSqCyclotomicFiniteLevelPresentation) :
    OddDegreeGalKSqCyclotomicGeneratorPresentation :=
  oddDegreeGalKSqGeneratorPresentation_of_orientedLabuteClassification
    (oddDegreeGalKSqOrientedLabuteClassification_of_finiteLevelPresentation hfinite)

/-! ## Literal constructor and regression -/

/-- Construct one finite-level datum directly from a tuple killing the literal improved
relator.  This is the endpoint expected from a parameterized Labute stage calculation. -/
noncomputable def OddDegreeGalKSqCyclotomicCoreTable.toFiniteLevelEpiData
    {K : IntermediateField ℚ_[2] ℚ̄₂} [FiniteDimensional ℚ_[2] K]
    [CompactSpace (GalK K)] [T2Space (GalK K)]
    [TotallyDisconnectedSpace (GalK K)]
    (T : OddDegreeGalKSqCyclotomicCoreTable K) (h : ℕ)
    (U : OpenNormalSubgroup
      (ProfiniteGrp.of (maxProPQuotient 2 (GalK K))))
    (generators : Fin (SqCore.sqRank h) →
      (maxProPQuotient 2 (GalK K) ⧸ U.toSubgroup))
    (hsigma : generators 0 = QuotientGroup.mk T.sigma)
    (hx0 : generators 1 = QuotientGroup.mk T.x0)
    (hx1 : generators 2 = QuotientGroup.mk T.x1)
    (hhandleU : ∀ j : Fin h, ∃ x : maxProPQuotient 2 (GalK K),
      x ∈ (chiCycKTwo (K := K)).toMonoidHom.ker ∧
        generators (SqCore.sqHandleIdxU j) = QuotientGroup.mk x)
    (hhandleV : ∀ j : Fin h, ∃ x : maxProPQuotient 2 (GalK K),
      x ∈ (chiCycKTwo (K := K)).toMonoidHom.ker ∧
        generators (SqCore.sqHandleIdxV j) = QuotientGroup.mk x)
    (hrelation : SqCore.sqRelWord generators = 1)
    (htopGen : Subgroup.closure (Set.range generators) = ⊤) :
    SqCyclotomicFiniteLevelEpiData T h U := by
  let Q := maxProPQuotient 2 (GalK K) ⧸ U.toSubgroup
  have hproQ : IsProP 2 Q := isProP_of_isPGroup (isProP_maxProPQuotient U)
  let f : ContinuousMonoidHom (SqCore.DSq h : Type) Q :=
    SqCore.sqLiftHom h hproQ generators hrelation
  have hfgen (i : Fin (SqCore.sqRank h)) : f (SqCore.sqGen h i) = generators i :=
    SqCore.sqLiftHom_gen h hproQ generators hrelation i
  have hfsurj : Function.Surjective f := by
    intro y
    have hle : Subgroup.closure (Set.range generators) ≤ f.toMonoidHom.range := by
      rw [Subgroup.closure_le]
      rintro _ ⟨i, rfl⟩
      exact ⟨SqCore.sqGen h i, hfgen i⟩
    exact hle (by rw [htopGen]; trivial)
  exact
    { epi := ⟨f, hfsurj⟩
      sigma := by
        change f (SqCore.sqGen h 0) = QuotientGroup.mk T.sigma
        rw [hfgen, hsigma]
      x0 := by
        change f (SqCore.sqGen h 1) = QuotientGroup.mk T.x0
        rw [hfgen, hx0]
      x1 := by
        change f (SqCore.sqGen h 2) = QuotientGroup.mk T.x1
        rw [hfgen, hx1]
      handleU := by
        intro j
        obtain ⟨x, hx, heq⟩ := hhandleU j
        exact ⟨x, hx, by rw [hfgen, heq]⟩
      handleV := by
        intro j
        obtain ⟨x, hx, heq⟩ := hhandleV j
        exact ⟨x, hx, by rw [hfgen, heq]⟩
      topGen := by simpa only [hfgen] using htopGen
      relation := by simpa only [hfgen] using hrelation }

/-- Improved-relator regression for the finite-level constructor. -/
theorem OddDegreeGalKSqCyclotomicCoreTable.toFiniteLevelEpiData_sqRelWord_regression
    {K : IntermediateField ℚ_[2] ℚ̄₂} [FiniteDimensional ℚ_[2] K]
    [CompactSpace (GalK K)] [T2Space (GalK K)]
    [TotallyDisconnectedSpace (GalK K)]
    (T : OddDegreeGalKSqCyclotomicCoreTable K) (h : ℕ)
    (U : OpenNormalSubgroup
      (ProfiniteGrp.of (maxProPQuotient 2 (GalK K))))
    (generators : Fin (SqCore.sqRank h) →
      (maxProPQuotient 2 (GalK K) ⧸ U.toSubgroup))
    (hsigma : generators 0 = QuotientGroup.mk T.sigma)
    (hx0 : generators 1 = QuotientGroup.mk T.x0)
    (hx1 : generators 2 = QuotientGroup.mk T.x1)
    (hhandleU : ∀ j : Fin h, ∃ x : maxProPQuotient 2 (GalK K),
      x ∈ (chiCycKTwo (K := K)).toMonoidHom.ker ∧
        generators (SqCore.sqHandleIdxU j) = QuotientGroup.mk x)
    (hhandleV : ∀ j : Fin h, ∃ x : maxProPQuotient 2 (GalK K),
      x ∈ (chiCycKTwo (K := K)).toMonoidHom.ker ∧
        generators (SqCore.sqHandleIdxV j) = QuotientGroup.mk x)
    (hrelation : SqCore.sqRelWord generators = 1)
    (htopGen : Subgroup.closure (Set.range generators) = ⊤) :
    SqCore.sqRelWord
      ((T.toFiniteLevelEpiData h U generators hsigma hx0 hx1 hhandleU hhandleV
        hrelation htopGen).epi.1 ∘ SqCore.sqGen h) = 1 :=
  (T.toFiniteLevelEpiData h U generators hsigma hx0 hx1 hhandleU hhandleV
    hrelation htopGen).relation

#print axioms forwardGeneratorData_of_finiteLevel
#print axioms oddDegreeGalKSqOrientedLabuteClassification_of_finiteLevelPresentation
#print axioms oddDegreeGalKSqGeneratorPresentation_of_finiteLevelPresentation
#print axioms OddDegreeGalKSqCyclotomicCoreTable.toFiniteLevelEpiData
#print axioms OddDegreeGalKSqCyclotomicCoreTable.toFiniteLevelEpiData_sqRelWord_regression

end

end GQ2.Dyadic.LSquare
