/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using OpenAI Codex
-/
import GQ2.Dyadic.Instances.GammaLSylowPreimageFieldLabuteForwardSpanAudit

/-!
# The literal arithmetic bracket span for the variable-rank Labute stage

The abstract coordinate span is generated by five explicit families.  For a neutral depth
element `p` in the kernel of the sharp cyclotomic row, the three core coordinates contribute

* `[p,x₀]`,
* `[p,σ]`, and
* `p²[p,x₁]`,

while the two coordinates of the `j`-th improved hyperbolic handle contribute `[p,V_j]` and
`[p,U_j]`.  This file identifies the full neutral-shift range with the subgroup generated by
exactly these literal atoms, and isolates residual membership in that subgroup as the minimal
remaining arithmetic statement.
-/

namespace GQ2.Dyadic.LSquare

noncomputable section

open GQ2
open GQ2.Roe.Labute

local notation "ℚ̄₂" => AlgebraicClosure ℚ_[2]

namespace SqCyclotomicStageTuple

variable {K : IntermediateField ℚ_[2] ℚ̄₂} [FiniteDimensional ℚ_[2] K]
  [CompactSpace (GalK K)] [T2Space (GalK K)]
  [TotallyDisconnectedSpace (GalK K)]

/-- The coordinate-image set phrased through the canonical one-coordinate homomorphisms. -/
def sharpNeutralCoordinateHomImageSet {h k : ℕ}
    (T : SqCyclotomicStageTuple K h k) (hk : 3 ≤ k) :
    Set (zLayer (maxProPQuotient 2 (GalK K)) k) :=
  {z | ∃ (i : Fin (SqCore.sqRank h))
      (p : sharpNeutralCoordinateSubgroup (K := K)
        (le_trans (by decide : 1 ≤ 3) hk)),
    z = sharpNeutralCoordinateShiftHom T hk i p}

/-- Taking the `i`-th coordinate of a neutral correction and reinserting it gives its
one-coordinate part. -/
theorem SharpNeutralCorrection.single_eq_coordinateHom {h k : ℕ}
    {T : SqCyclotomicStageTuple K h k} {hk : 1 ≤ k}
    (V : SharpNeutralCorrection T hk) (i : Fin (SqCore.sqRank h)) :
    V.single i = sharpNeutralCoordinateHom T hk i
      ⟨V.correction i, ⟨V.depth i, MonoidHom.mem_ker.mpr (V.sharpKernel i)⟩⟩ := by
  apply SharpNeutralCorrection.ext
  funext j
  by_cases hji : j = i
  · subst j
    simp [SharpNeutralCorrection.single]
  · simp [SharpNeutralCorrection.single, sharpNeutralCoordinateHom_correction, hji]

/-- A correction inserted in one coordinate is unchanged by retaining that coordinate. -/
theorem sharpNeutralCoordinateHom_single {h k : ℕ}
    (T : SqCyclotomicStageTuple K h k) (hk : 1 ≤ k)
    (i : Fin (SqCore.sqRank h))
    (p : sharpNeutralCoordinateSubgroup (K := K) hk) :
    (sharpNeutralCoordinateHom T hk i p).single i =
      sharpNeutralCoordinateHom T hk i p := by
  apply SharpNeutralCorrection.ext
  funext j
  by_cases hji : j = i
  · subst j
    simp [SharpNeutralCorrection.single]
  · simp [SharpNeutralCorrection.single, sharpNeutralCoordinateHom_correction, hji]

/-- The earlier coordinate-image set and the homomorphism-based version coincide. -/
theorem sharpNeutralCoordinateImageSet_eq_coordinateHomImageSet {h k : ℕ}
    (T : SqCyclotomicStageTuple K h k) (hk : 3 ≤ k) :
    sharpNeutralCoordinateImageSet T hk =
      sharpNeutralCoordinateHomImageSet T hk := by
  ext z
  constructor
  · rintro ⟨V, i, rfl⟩
    let p : sharpNeutralCoordinateSubgroup (K := K)
        (le_trans (by decide : 1 ≤ 3) hk) :=
      ⟨V.correction i, ⟨V.depth i, MonoidHom.mem_ker.mpr (V.sharpKernel i)⟩⟩
    refine ⟨i, p, ?_⟩
    rw [V.single_eq_coordinateHom i]
    rfl
  · rintro ⟨i, p, rfl⟩
    let V := sharpNeutralCoordinateHom T
      (le_trans (by decide : 1 ≤ 3) hk) i p
    refine ⟨V, i, ?_⟩
    change sharpNeutralShiftHom T hk V = sharpNeutralShiftHom T hk (V.single i)
    rw [sharpNeutralCoordinateHom_single]

/-- The five literal bracket families contributed by the improved square presentation. -/
def sharpNeutralBracketAtomSet {h k : ℕ}
    (T : SqCyclotomicStageTuple K h k) (hk : 3 ≤ k) :
    Set (zLayer (maxProPQuotient 2 (GalK K)) k) :=
  {z |
    (∃ p : sharpNeutralCoordinateSubgroup (K := K)
        (le_trans (by decide : 1 ≤ 3) hk),
      z.1 = commP p.1
        (canonLift (maxProPQuotient 2 (GalK K)) k (T.generators 1))) ∨
    (∃ p : sharpNeutralCoordinateSubgroup (K := K)
        (le_trans (by decide : 1 ≤ 3) hk),
      z.1 = commP p.1
        (canonLift (maxProPQuotient 2 (GalK K)) k (T.generators 0))) ∨
    (∃ p : sharpNeutralCoordinateSubgroup (K := K)
        (le_trans (by decide : 1 ≤ 3) hk),
      z.1 = p.1 ^ 2 * commP p.1
        (canonLift (maxProPQuotient 2 (GalK K)) k (T.generators 2))) ∨
    (∃ (j : Fin h) (p : sharpNeutralCoordinateSubgroup (K := K)
        (le_trans (by decide : 1 ≤ 3) hk)),
      z.1 = commP p.1 (canonLift (maxProPQuotient 2 (GalK K)) k
        (T.generators (SqCore.sqHandleIdxV j)))) ∨
    ∃ (j : Fin h) (p : sharpNeutralCoordinateSubgroup (K := K)
        (le_trans (by decide : 1 ≤ 3) hk)),
      z.1 = commP p.1 (canonLift (maxProPQuotient 2 (GalK K)) k
        (T.generators (SqCore.sqHandleIdxU j)))}

/-- The canonical coordinate images are exactly the five literal bracket families. -/
theorem sharpNeutralCoordinateHomImageSet_eq_bracketAtomSet {h k : ℕ}
    (T : SqCyclotomicStageTuple K h k) (hk : 3 ≤ k) :
    sharpNeutralCoordinateHomImageSet T hk = sharpNeutralBracketAtomSet T hk := by
  ext z
  constructor
  · rintro ⟨i, p, rfl⟩
    rcases SqCore.sqIdx_cases i with rfl | rfl | rfl | ⟨j, rfl⟩ | ⟨j, rfl⟩
    · exact Or.inl ⟨p, sharpNeutralCoordinateShiftHom_zero_apply T hk p⟩
    · exact Or.inr (Or.inl ⟨p, sharpNeutralCoordinateShiftHom_one_apply T hk p⟩)
    · exact Or.inr (Or.inr (Or.inl
        ⟨p, sharpNeutralCoordinateShiftHom_two_apply T hk p⟩))
    · exact Or.inr (Or.inr (Or.inr (Or.inl
        ⟨j, p, sharpNeutralCoordinateShiftHom_handleU_apply T hk j p⟩)))
    · exact Or.inr (Or.inr (Or.inr (Or.inr
        ⟨j, p, sharpNeutralCoordinateShiftHom_handleV_apply T hk j p⟩)))
  · rintro (⟨p, hz⟩ | ⟨p, hz⟩ | ⟨p, hz⟩ | ⟨j, p, hz⟩ | ⟨j, p, hz⟩)
    · refine ⟨0, p, ?_⟩
      apply Subtype.ext
      exact hz.trans (sharpNeutralCoordinateShiftHom_zero_apply T hk p).symm
    · refine ⟨1, p, ?_⟩
      apply Subtype.ext
      exact hz.trans (sharpNeutralCoordinateShiftHom_one_apply T hk p).symm
    · refine ⟨2, p, ?_⟩
      apply Subtype.ext
      exact hz.trans (sharpNeutralCoordinateShiftHom_two_apply T hk p).symm
    · refine ⟨SqCore.sqHandleIdxU j, p, ?_⟩
      apply Subtype.ext
      exact hz.trans (sharpNeutralCoordinateShiftHom_handleU_apply T hk j p).symm
    · refine ⟨SqCore.sqHandleIdxV j, p, ?_⟩
      apply Subtype.ext
      exact hz.trans (sharpNeutralCoordinateShiftHom_handleV_apply T hk j p).symm

/-- The literal bracket span dictated by the improved presentation. -/
def sharpNeutralBracketSpan {h k : ℕ}
    (T : SqCyclotomicStageTuple K h k) (hk : 3 ≤ k) :
    Subgroup (zLayer (maxProPQuotient 2 (GalK K)) k) :=
  Subgroup.closure (sharpNeutralBracketAtomSet T hk)

/-- The abstract coordinate span is definitionally accounted for by the five literal bracket
families. -/
theorem sharpNeutralCoordinateSpan_eq_bracketSpan {h k : ℕ}
    (T : SqCyclotomicStageTuple K h k) (hk : 3 ≤ k) :
    sharpNeutralCoordinateSpan T hk = sharpNeutralBracketSpan T hk := by
  unfold sharpNeutralCoordinateSpan sharpNeutralBracketSpan
  apply congrArg Subgroup.closure
  exact (sharpNeutralCoordinateImageSet_eq_coordinateHomImageSet T hk).trans
    (sharpNeutralCoordinateHomImageSet_eq_bracketAtomSet T hk)

/-- The full neutral-shift range is exactly the literal arithmetic bracket span. -/
theorem sharpNeutralShiftHom_range_eq_bracketSpan {h k : ℕ}
    (T : SqCyclotomicStageTuple K h k) (hk : 3 ≤ k) :
    (sharpNeutralShiftHom T hk).range = sharpNeutralBracketSpan T hk :=
  (sharpNeutralShiftHom_range_eq_coordinateSpan T hk).trans
    (sharpNeutralCoordinateSpan_eq_bracketSpan T hk)

/-- Residual reachability is precisely membership in the literal bracket span. -/
theorem sharpNeutralResidualReachable_iff_mem_bracketSpan
    {h k : ℕ} {T : SqCyclotomicStageTuple K h k} {hk : 3 ≤ k}
    (W : SharpAdmissibleCorrection T (by omega)) :
    SharpNeutralResidualReachable T hk W ↔
      sharpNeutralResidualElement T hk W ∈ sharpNeutralBracketSpan T hk := by
  rw [sharpNeutralResidualReachable_iff_mem_range,
    sharpNeutralShiftHom_range_eq_bracketSpan]

/-- The affine actual-defect theorem is equivalent to literal bracket-span membership. -/
theorem nonempty_coreHandleSharpActualDefectSupply_iff_mem_bracketSpan
    {h k : ℕ} {T : SqCyclotomicStageTuple K h k} {hk : 3 ≤ k}
    (W : SharpAdmissibleCorrection T (by omega)) :
    Nonempty (CoreHandleSharpActualDefectSupply T hk) ↔
      sharpNeutralResidualElement T hk W ∈ sharpNeutralBracketSpan T hk := by
  rw [nonempty_coreHandleSharpActualDefectSupply_iff_neutralResidual,
    sharpNeutralResidualReachable_iff_mem_bracketSpan]

/-- The minimal arithmetic proposition, independent of a preselected affine base point. -/
def SharpNeutralBracketSpanSupply {h k : ℕ}
    (T : SqCyclotomicStageTuple K h k) (hk : 3 ≤ k) : Prop :=
  ∃ W : SharpAdmissibleCorrection T (by omega),
    sharpNeutralResidualElement T hk W ∈ sharpNeutralBracketSpan T hk

/-- The minimal literal bracket-span proposition is equivalent to the exact correction supply
consumed by the stage argument. -/
theorem sharpNeutralBracketSpanSupply_iff_nonempty_actualDefectSupply
    {h k : ℕ} {T : SqCyclotomicStageTuple K h k} {hk : 3 ≤ k} :
    SharpNeutralBracketSpanSupply T hk ↔
      Nonempty (CoreHandleSharpActualDefectSupply T hk) := by
  constructor
  · rintro ⟨W, hW⟩
    exact (nonempty_coreHandleSharpActualDefectSupply_iff_mem_bracketSpan W).mpr hW
  · rintro hS
    let W : SharpAdmissibleCorrection T (by omega) :=
      Classical.choice (sharpAdmissibleCorrection_nonempty T (by omega))
    exact ⟨W,
      (nonempty_coreHandleSharpActualDefectSupply_iff_mem_bracketSpan W).mp hS⟩

end SqCyclotomicStageTuple

#print axioms SqCyclotomicStageTuple.sharpNeutralCoordinateHomImageSet_eq_bracketAtomSet
#print axioms SqCyclotomicStageTuple.sharpNeutralShiftHom_range_eq_bracketSpan
#print axioms SqCyclotomicStageTuple.sharpNeutralResidualReachable_iff_mem_bracketSpan
#print axioms SqCyclotomicStageTuple.sharpNeutralBracketSpanSupply_iff_nonempty_actualDefectSupply

end


end GQ2.Dyadic.LSquare
