/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using OpenAI Codex
-/
import GQ2.Dyadic.Instances.GammaLFieldPresentationRightExact
import GQ2.Dyadic.Instances.GammaLSylowPreimageFieldVariableCoreRigidity

/-!
# Pointwise field Tate adapter for variable GammaL Sylow cores

The corrected Sylow-preimage route must not identify every odd-index preimage with the fixed
ambient square core.  The minimal Tate proof, for each simultaneous coefficient action:

1. chooses one Sylow preimage `U` whose maximal-pro-two kernel has vanishing finite-elementary
   `H²`;
2. identifies that same `U` with the absolute Galois group of its own finite dyadic field `K`;
3. uses B6 on `G_K`, automatic maximal-pro-two H² inflation injectivity, and the supplied
   scalar-kernel H² vanishing to prove the finite-elementary right-exactness tail on `U(2)`;
4. feeds the resulting honest kernel/CD₂ package to the existing Sylow devissage.

A separate campaign-composition regression additionally uses forward Demushkin rigidity to
record the square presentation at the variable handle count dictated by `[GammaL : U]`.  That
presentation is correct and useful, but is not logically needed once `U ≃ G_K` transports B6.

The primary premise is `GammaLOddIndexOpenSubgroupFieldIdentificationSupply`, not
`GammaLFieldRealization`.  A realization wrapper is provided only as optional Krull plumbing;
it never calls the Tate bundle already stored by the realization API.
-/

set_option autoImplicit false

namespace GQ2.Dyadic.LSquare

noncomputable section

open GQ2 GQ2.ContCoh

local notation "ℚ̄₂" => AlgebraicClosure ℚ_[2]

/-! ## Minimal uniform residual statements -/

/-- For each simultaneous finite coefficient action, one may choose a Sylow preimage whose
maximal-pro-two kernel has the honest finite-elementary `H²`-vanishing supply. -/
noncomputable abbrev GammaLSylowPreimageKernelH2Supply (h q : ℕ) : Prop :=
  ∀ (A B : Type) [AddCommGroup A] [TopologicalSpace A]
    [IsTopologicalAddGroup A] [DiscreteTopology A] [Finite A]
    [DistribMulAction (gamma h q : Type) A] [ContinuousSMul (gamma h q : Type) A]
    [AddCommGroup B] [TopologicalSpace B]
    [IsTopologicalAddGroup B] [DiscreteTopology B] [Finite B]
    [DistribMulAction (gamma h q : Type) B] [ContinuousSMul (gamma h q : Type) B],
      ∃ P : Sylow 2
          (PairFiniteActionImage (h := h) (q := q) (A := A) (B := B)),
        GammaLSylowPreimageKernelH2VanishesSupply P

/-- Scalar `H²` vanishes on the maximal-pro-two kernel of every odd-degree finite dyadic
field.  This is the minimal field-side premise used by the pointwise B6 transport below. -/
def OddDegreeGalKMaxProTwoKernelScalarH2VanishesSupply : Prop :=
  ∀ (K : IntermediateField ℚ_[2] ℚ̄₂) [FiniteDimensional ℚ_[2] K]
    [CompactSpace (GalK K)] [T2Space (GalK K)] [TotallyDisconnectedSpace (GalK K)],
    Odd (Module.finrank ℚ_[2] K) →
      MaxProTwoKernelScalarH2Vanishes (G := GalK K)

/-- Literature-facing sufficient premise: scalar degree-two cohomology over the canonical
maximal-pro-two fixed field `K(2)` is generated by degree-one cup products, uniformly for
odd-degree finite dyadic `K`. -/
def OddDegreeGalKMaxProTwoFixedFieldScalarH2CupGeneratedSupply : Prop :=
  ∀ (K : IntermediateField ℚ_[2] ℚ̄₂) [FiniteDimensional ℚ_[2] K]
    [CompactSpace (GalK K)] [T2Space (GalK K)] [TotallyDisconnectedSpace (GalK K)],
    Odd (Module.finrank ℚ_[2] K) →
      GalKMaxProTwoFixedFieldScalarH2CupGenerated (K := K)

/-- Fixed-field cup-generation supplies the minimal scalar kernel-vanishing premise. -/
theorem oddDegreeGalKMaxProTwoKernelScalarH2VanishesSupply_of_fixedField_cupGenerated
    (S : OddDegreeGalKMaxProTwoFixedFieldScalarH2CupGeneratedSupply) :
    OddDegreeGalKMaxProTwoKernelScalarH2VanishesSupply := by
  intro K _ _ _ _ hodd
  let Q := maxProPQuotient 2 (GalK K)
  letI : DistribMulAction Q (ZMod 2) := scalarActionZmodTwo Q
  letI : ContinuousSMul Q (ZMod 2) := scalarActionZmodTwo_continuousSMul Q
  exact galKMaxProTwoKernelScalarH2Vanishes_of_fixedField_cupGenerated (S K hodd)

/-! ## Pointwise field CD₂ and the minimal uniform Tate supply -/

/-- B6 and scalar kernel `H²`-vanishing prove the right-exactness tail on the maximal pro-two
quotient of one identified open subgroup.  Maximal-pro-two inflation injectivity is automatic
inside the field theorem; no presentation of the quotient is used. -/
theorem finiteElementaryH2RightExactSupply_maxProTwo_of_fieldIdentification_kernelScalarH2
    {h q : ℕ} (U' : Subgroup (gamma h q : Type)) [CompactSpace U']
    (F : GammaLOpenSubgroupFieldIdentification U')
    (hscalar :
      letI : FiniteDimensional ℚ_[2] F.K := F.finiteDimensional
      letI : CompactSpace (GalK F.K) := F.compactSpace
      letI : T2Space (GalK F.K) := F.t2Space
      letI : TotallyDisconnectedSpace (GalK F.K) := F.totallyDisconnectedSpace
      MaxProTwoKernelScalarH2Vanishes (G := GalK F.K)) :
    FiniteElementaryH2RightExactSupply (maxProPQuotient 2 U') := by
  letI : FiniteDimensional ℚ_[2] F.K := F.finiteDimensional
  letI : CompactSpace (GalK F.K) := F.compactSpace
  letI : T2Space (GalK F.K) := F.t2Space
  letI : TotallyDisconnectedSpace (GalK F.K) := F.totallyDisconnectedSpace
  have hfieldCDTwo : GalKMaxProTwoH2RightExactSupply F.K :=
    galKMaxProTwoH2RightExactSupply_of_B6_of_kernelScalarH2Vanishes F.K hscalar
  exact finiteTwoH2RightExactSupply_congr
    (maxProPQuotientCongr F.equivGalK) hfieldCDTwo

/-- The truly minimal pointwise supply consumed by the Tate proof.  For the same chosen Sylow
preimage it stores outer maximal-pro-two-kernel `H²`-vanishing and the field-derived CD₂ tail
on that preimage's own maximal pro-two quotient. -/
noncomputable abbrev GammaLSylowPreimageKernelH2FieldCDTwoSupply (h q : ℕ) : Prop :=
  ∀ (A B : Type) [AddCommGroup A] [TopologicalSpace A]
    [IsTopologicalAddGroup A] [DiscreteTopology A] [Finite A]
    [DistribMulAction (gamma h q : Type) A] [ContinuousSMul (gamma h q : Type) A]
    [AddCommGroup B] [TopologicalSpace B]
    [IsTopologicalAddGroup B] [DiscreteTopology B] [Finite B]
    [DistribMulAction (gamma h q : Type) B] [ContinuousSMul (gamma h q : Type) B],
      ∃ P : Sylow 2
          (PairFiniteActionImage (h := h) (q := q) (A := A) (B := B)),
        GammaLSylowPreimageKernelH2VanishesSupply P ∧
          FiniteElementaryH2RightExactSupply
            (maxProPQuotient 2 (sylowTwoPreimage
              (pairFiniteActionImageHom (h := h) (q := q) (A := A) (B := B)) P))

/-- Construct the minimal Tate supply pointwise from open-subgroup field identifications and
the scalar kernel theorem for odd-degree dyadic fields. -/
theorem gammaLSylowPreimageKernelH2FieldCDTwoSupply_of_field
    {h q : ℕ}
    (hkernel : GammaLSylowPreimageKernelH2Supply h q)
    (hfield : GammaLOddIndexOpenSubgroupFieldIdentificationSupply h q)
    (hfieldH2 : OddDegreeGalKMaxProTwoKernelScalarH2VanishesSupply) :
    GammaLSylowPreimageKernelH2FieldCDTwoSupply h q := by
  intro A B _ _ _ _ _ _ _ _ _ _ _ _ _ _
  obtain ⟨P, hkernelP⟩ := hkernel A B
  let rho := pairFiniteActionImageHom (h := h) (q := q) (A := A) (B := B)
  let U' := sylowTwoPreimage rho P
  have hUopen : IsOpen (U' : Set (gamma h q : Type)) :=
    isOpen_sylowTwoPreimage rho P
  have hUodd : Odd U'.index :=
    odd_sylowTwoPreimage_index rho pairFiniteActionImageHom_surjective P
  obtain ⟨F⟩ := hfield U' hUopen hUodd
  letI : FiniteDimensional ℚ_[2] F.K := F.finiteDimensional
  letI : CompactSpace (GalK F.K) := F.compactSpace
  letI : T2Space (GalK F.K) := F.t2Space
  letI : TotallyDisconnectedSpace (GalK F.K) := F.totallyDisconnectedSpace
  have hdegreeOdd : Odd (Module.finrank ℚ_[2] F.K) := by
    rw [F.degree_eq]
    exact hUodd.mul ⟨h, by omega⟩
  have hcd : FiniteElementaryH2RightExactSupply (maxProPQuotient 2 U') :=
    finiteElementaryH2RightExactSupply_maxProTwo_of_fieldIdentification_kernelScalarH2
      U' F (hfieldH2 F.K hdegreeOdd)
  exact ⟨P, hkernelP, hcd⟩

/-! ## The combined variable-core and pointwise field package -/

/-- At every coefficient action, retain all three facts for the same chosen Sylow preimage:
outer maximal-pro-two-kernel `H²`-vanishing, the corrected variable-rank square presentation,
and the finite-elementary right-exactness tail on that preimage's own maximal pro-two quotient.

The presentation field is not needed to fake a fixed-core equality; it records the corrected
rank statement supplied by forward rigidity alongside the field-derived CD₂ tail. -/
noncomputable abbrev GammaLSylowPreimageKernelH2VariableCoreFieldCDTwoSupply
    (h q : ℕ) : Prop :=
  ∀ (A B : Type) [AddCommGroup A] [TopologicalSpace A]
    [IsTopologicalAddGroup A] [DiscreteTopology A] [Finite A]
    [DistribMulAction (gamma h q : Type) A] [ContinuousSMul (gamma h q : Type) A]
    [AddCommGroup B] [TopologicalSpace B]
    [IsTopologicalAddGroup B] [DiscreteTopology B] [Finite B]
    [DistribMulAction (gamma h q : Type) B] [ContinuousSMul (gamma h q : Type) B],
      ∃ P : Sylow 2
          (PairFiniteActionImage (h := h) (q := q) (A := A) (B := B)),
        GammaLSylowPreimageKernelH2VanishesSupply P ∧
          GammaLSylowPreimageVariableCorePresentation P ∧
          FiniteElementaryH2RightExactSupply
            (maxProPQuotient 2 (sylowTwoPreimage
              (pairFiniteActionImageHom (h := h) (q := q) (A := A) (B := B)) P))

/-- Pointwise field construction of the combined corrected package.  B6 is used only on the
field `F.K` attached to the chosen Sylow preimage; the right-exactness tail is transported back
along `maxProPQuotientCongr F.equivGalK`. -/
theorem gammaLSylowPreimageKernelH2VariableCoreFieldCDTwoSupply_of_field_forward
    {h q : ℕ}
    (hkernel : GammaLSylowPreimageKernelH2Supply h q)
    (hfield : GammaLOddIndexOpenSubgroupFieldIdentificationSupply h q)
    (hforward : OddDegreeGalKSqOrientedForwardClassification)
    (hfieldH2 : OddDegreeGalKMaxProTwoKernelScalarH2VanishesSupply) :
    GammaLSylowPreimageKernelH2VariableCoreFieldCDTwoSupply h q := by
  intro A B _ _ _ _ _ _ _ _ _ _ _ _ _ _
  obtain ⟨P, hkernelP⟩ := hkernel A B
  let rho := pairFiniteActionImageHom (h := h) (q := q) (A := A) (B := B)
  let U' := sylowTwoPreimage rho P
  have hUopen : IsOpen (U' : Set (gamma h q : Type)) :=
    isOpen_sylowTwoPreimage rho P
  have hUodd : Odd U'.index :=
    odd_sylowTwoPreimage_index rho pairFiniteActionImageHom_surjective P
  obtain ⟨F⟩ := hfield U' hUopen hUodd
  letI : FiniteDimensional ℚ_[2] F.K := F.finiteDimensional
  letI : CompactSpace (GalK F.K) := F.compactSpace
  letI : T2Space (GalK F.K) := F.t2Space
  letI : TotallyDisconnectedSpace (GalK F.K) := F.totallyDisconnectedSpace
  have hdegreeOdd : Odd (Module.finrank ℚ_[2] F.K) := by
    rw [F.degree_eq]
    exact hUodd.mul ⟨h, by omega⟩
  have hpresentation : GammaLSylowPreimageVariableCorePresentation P :=
    gammaLOpenSubgroupVariableCorePresentation_of_fieldIdentification_forward
      U' hUodd F hforward
  have hfieldCDTwo : GalKMaxProTwoH2RightExactSupply F.K :=
    galKMaxProTwoH2RightExactSupply_of_B6_of_kernelScalarH2Vanishes
      F.K (hfieldH2 F.K hdegreeOdd)
  have hUCDTwo : FiniteElementaryH2RightExactSupply (maxProPQuotient 2 U') :=
    finiteTwoH2RightExactSupply_congr (maxProPQuotientCongr F.equivGalK) hfieldCDTwo
  exact ⟨P, hkernelP, hpresentation, hUCDTwo⟩

/-- Forward generator tables feed the preceding constructor through the proved rigidity
classification. -/
theorem gammaLSylowPreimageKernelH2VariableCoreFieldCDTwoSupply_of_field_forwardGenerators
    {h q : ℕ}
    (hkernel : GammaLSylowPreimageKernelH2Supply h q)
    (hfield : GammaLOddIndexOpenSubgroupFieldIdentificationSupply h q)
    (hforward : OddDegreeGalKSqForwardGeneratorSupply)
    (hfieldH2 : OddDegreeGalKMaxProTwoKernelScalarH2VanishesSupply) :
    GammaLSylowPreimageKernelH2VariableCoreFieldCDTwoSupply h q :=
  gammaLSylowPreimageKernelH2VariableCoreFieldCDTwoSupply_of_field_forward
    hkernel hfield
    (oddDegreeGalKSqOrientedForwardClassification_of_forwardGeneratorSupply hforward)
    hfieldH2

/-! ## Adapters to the existing variable-core and Sylow devissages -/

/-- Forget the field-derived CD₂ tail to recover the corrected variable-core residual supply. -/
theorem gammaLSylowPreimageKernelH2AndVariableCoreSupply_of_fieldCDTwo
    {h q : ℕ} (S : GammaLSylowPreimageKernelH2VariableCoreFieldCDTwoSupply h q) :
    GammaLSylowPreimageKernelH2AndVariableCoreSupply h q := by
  intro A B _ _ _ _ _ _ _ _ _ _ _ _ _ _
  obtain ⟨P, hkernel, hpresentation, _hcd⟩ := S A B
  exact ⟨P, hkernel, hpresentation⟩

/-- Forget the variable-core regression and retain the genuinely minimal field CD₂ package. -/
theorem gammaLSylowPreimageKernelH2FieldCDTwoSupply_of_variableCore
    {h q : ℕ} (S : GammaLSylowPreimageKernelH2VariableCoreFieldCDTwoSupply h q) :
    GammaLSylowPreimageKernelH2FieldCDTwoSupply h q := by
  intro A B _ _ _ _ _ _ _ _ _ _ _ _ _ _
  obtain ⟨P, hkernel, _hpresentation, hcd⟩ := S A B
  exact ⟨P, hkernel, hcd⟩

/-- The minimal pointwise package fills the honest kernel-one-two/CD₂ supply consumed by the
Sylow Tate devissage.  Kernel transgression is the existing unconditional theorem. -/
theorem gammaLSylowPreimageMaxProTwoKernelOneTwoCDTwoSupply_of_fieldCDTwo
    {h q : ℕ} (S : GammaLSylowPreimageKernelH2FieldCDTwoSupply h q) :
    GammaLSylowPreimageMaxProTwoKernelOneTwoCDTwoSupply h q := by
  intro A B _ _ _ _ _ _ _ _ _ _ _ _ _ _
  obtain ⟨P, hkernel, hcd⟩ := S A B
  let U' := sylowTwoPreimage
    (pairFiniteActionImageHom (h := h) (q := q) (A := A) (B := B)) P
  have hinflationKernel : FiniteElementaryMaxProTwoKernelOneTwoSupply (G := U') :=
    finiteElementaryMaxProTwoKernelOneTwoSupply_of_h2Vanishes_transgression hkernel
      (finiteElementaryMaxProTwoKernelTransgression (G := U'))
  exact ⟨P, { inflationKernel := hinflationKernel, cdTwo := hcd }⟩

/-- Minimal corrected Tate capstone from pointwise field CD₂.  It uses neither any square-core
presentation nor the generally false fixed-core equality. -/
noncomputable def tateDualityG_of_sylowPreimageFieldCDTwo
    {h q : ℕ} (hqe : Even q)
    [DistribMulAction (gamma h q : Type) (MuN 2)]
    [ContinuousSMul (gamma h q : Type) (MuN 2)]
    (S : GammaLSylowPreimageKernelH2FieldCDTwoSupply h q) :
    TateDualityG (gamma h q : Type) 2 :=
  tateDualityG_of_sylowPreimageMaxProTwoKernelOneTwoCDTwo hqe
    (gammaLSylowPreimageMaxProTwoKernelOneTwoCDTwoSupply_of_fieldCDTwo S)

/-- Corrected variable-rank Tate capstone from the combined pointwise field package.  It uses
neither the generally false fixed-core equality nor a pre-existing Tate bundle on `GammaL`. -/
noncomputable def tateDualityG_of_sylowPreimageFieldVariableCoreCDTwo
    {h q : ℕ} (hqe : Even q)
    [DistribMulAction (gamma h q : Type) (MuN 2)]
    [ContinuousSMul (gamma h q : Type) (MuN 2)]
    (S : GammaLSylowPreimageKernelH2VariableCoreFieldCDTwoSupply h q) :
    TateDualityG (gamma h q : Type) 2 :=
  tateDualityG_of_sylowPreimageMaxProTwoKernelOneTwoCDTwo hqe
    (gammaLSylowPreimageMaxProTwoKernelOneTwoCDTwoSupply_of_fieldCDTwo
      (gammaLSylowPreimageKernelH2FieldCDTwoSupply_of_variableCore S))

/-- Primary noncircular capstone.  Open-subgroup field identifications, Sylow-preimage kernel
`H²`-vanishing, and odd-degree field scalar kernel `H²`-vanishing are the complete explicit
premises.  No forward presentation theorem is logically needed. -/
noncomputable def tateDualityG_of_fieldIdentification_kernelScalarH2
    {h q : ℕ} (hqe : Even q)
    [DistribMulAction (gamma h q : Type) (MuN 2)]
    [ContinuousSMul (gamma h q : Type) (MuN 2)]
    (hkernel : GammaLSylowPreimageKernelH2Supply h q)
    (hfield : GammaLOddIndexOpenSubgroupFieldIdentificationSupply h q)
    (hfieldH2 : OddDegreeGalKMaxProTwoKernelScalarH2VanishesSupply) :
    TateDualityG (gamma h q : Type) 2 :=
  tateDualityG_of_sylowPreimageFieldCDTwo hqe
    (gammaLSylowPreimageKernelH2FieldCDTwoSupply_of_field hkernel hfield hfieldH2)

/-- Literature-facing primary capstone, replacing scalar field-kernel `H²`-vanishing by
cup-generation over every canonical odd-degree fixed field `K(2)`. -/
noncomputable def tateDualityG_of_fieldIdentification_fixedFieldCupGenerated
    {h q : ℕ} (hqe : Even q)
    [DistribMulAction (gamma h q : Type) (MuN 2)]
    [ContinuousSMul (gamma h q : Type) (MuN 2)]
    (hkernel : GammaLSylowPreimageKernelH2Supply h q)
    (hfield : GammaLOddIndexOpenSubgroupFieldIdentificationSupply h q)
    (hcup : OddDegreeGalKMaxProTwoFixedFieldScalarH2CupGeneratedSupply) :
    TateDualityG (gamma h q : Type) 2 :=
  tateDualityG_of_fieldIdentification_kernelScalarH2 hqe hkernel hfield
    (oddDegreeGalKMaxProTwoKernelScalarH2VanishesSupply_of_fixedField_cupGenerated hcup)

/-- Campaign-composition regression.  In addition to the minimal Tate inputs, forward
generator tables construct and retain the corrected variable-rank square core for every chosen
Sylow preimage. -/
noncomputable def tateDualityG_of_fieldIdentification_forwardGenerators_kernelScalarH2
    {h q : ℕ} (hqe : Even q)
    [DistribMulAction (gamma h q : Type) (MuN 2)]
    [ContinuousSMul (gamma h q : Type) (MuN 2)]
    (hkernel : GammaLSylowPreimageKernelH2Supply h q)
    (hfield : GammaLOddIndexOpenSubgroupFieldIdentificationSupply h q)
    (hforward : OddDegreeGalKSqForwardGeneratorSupply)
    (hfieldH2 : OddDegreeGalKMaxProTwoKernelScalarH2VanishesSupply) :
    TateDualityG (gamma h q : Type) 2 :=
  tateDualityG_of_sylowPreimageFieldVariableCoreCDTwo hqe
    (gammaLSylowPreimageKernelH2VariableCoreFieldCDTwoSupply_of_field_forwardGenerators
      hkernel hfield hforward hfieldH2)

/-- Literature-facing campaign-composition regression retaining the forward variable cores. -/
noncomputable def tateDualityG_of_fieldIdentification_forwardGenerators_fixedFieldCupGenerated
    {h q : ℕ} (hqe : Even q)
    [DistribMulAction (gamma h q : Type) (MuN 2)]
    [ContinuousSMul (gamma h q : Type) (MuN 2)]
    (hkernel : GammaLSylowPreimageKernelH2Supply h q)
    (hfield : GammaLOddIndexOpenSubgroupFieldIdentificationSupply h q)
    (hforward : OddDegreeGalKSqForwardGeneratorSupply)
    (hcup : OddDegreeGalKMaxProTwoFixedFieldScalarH2CupGeneratedSupply) :
    TateDualityG (gamma h q : Type) 2 :=
  tateDualityG_of_fieldIdentification_forwardGenerators_kernelScalarH2 hqe
    hkernel hfield hforward
    (oddDegreeGalKMaxProTwoKernelScalarH2VanishesSupply_of_fixedField_cupGenerated hcup)

/-! ## Optional field-realization plumbing -/

/-- Secondary wrapper using `GammaLFieldRealization` only to construct the open-subgroup field
identifications by Krull correspondence.  The proof deliberately does not invoke
`gammaL_tateDualityG` or `LocalFieldRealization.tateDualityG`. -/
noncomputable def tateDualityG_of_fieldRealizationIdentification_fixedFieldCupGenerated
    {h q : ℕ} (hqe : Even q)
    [DistribMulAction (gamma h q : Type) (MuN 2)]
    [ContinuousSMul (gamma h q : Type) (MuN 2)]
    (R : GammaLFieldRealization h q)
    (hkernel : GammaLSylowPreimageKernelH2Supply h q)
    (hcup : OddDegreeGalKMaxProTwoFixedFieldScalarH2CupGeneratedSupply) :
    TateDualityG (gamma h q : Type) 2 :=
  tateDualityG_of_fieldIdentification_fixedFieldCupGenerated hqe hkernel
    (gammaLOddIndexOpenSubgroupFieldIdentificationSupply_of_fieldRealization R) hcup

/-- Secondary campaign-regression wrapper which additionally constructs the forward variable
cores.  As above, the realization is used only for subgroup-to-field identification. -/
noncomputable def tateDualityG_of_fieldRealizationIdentification_forwardGenerators_fixedFieldCupGenerated
    {h q : ℕ} (hqe : Even q)
    [DistribMulAction (gamma h q : Type) (MuN 2)]
    [ContinuousSMul (gamma h q : Type) (MuN 2)]
    (R : GammaLFieldRealization h q)
    (hkernel : GammaLSylowPreimageKernelH2Supply h q)
    (hforward : OddDegreeGalKSqForwardGeneratorSupply)
    (hcup : OddDegreeGalKMaxProTwoFixedFieldScalarH2CupGeneratedSupply) :
    TateDualityG (gamma h q : Type) 2 :=
  tateDualityG_of_fieldIdentification_forwardGenerators_fixedFieldCupGenerated hqe
    hkernel (gammaLOddIndexOpenSubgroupFieldIdentificationSupply_of_fieldRealization R)
    hforward hcup

#print axioms finiteElementaryH2RightExactSupply_maxProTwo_of_fieldIdentification_kernelScalarH2
#print axioms tateDualityG_of_fieldIdentification_kernelScalarH2
#print axioms tateDualityG_of_fieldIdentification_fixedFieldCupGenerated
#print axioms tateDualityG_of_fieldIdentification_forwardGenerators_kernelScalarH2
#print axioms tateDualityG_of_fieldRealizationIdentification_fixedFieldCupGenerated

end

end GQ2.Dyadic.LSquare
