/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using OpenAI Codex
-/
import GQ2.Dyadic.Instances.GammaLSylowPreimageFieldLabuteStageHandles

/-!
# Coordinate reduction for the variable-rank sharp-neutral span problem

The existing rank-three graded span theorems do not directly identify their source map with
`SqCyclotomicStageTuple.sharpNeutralShiftHom`: the latter has variable rank, includes all
hyperbolic-handle coordinates, and restricts every correction to the kernel of the sharp
cyclotomic character.  This file records the exact reduction that is available without such
an identification.

Every sharp-neutral correction is a finite product of corrections supported at one generator
coordinate.  Since `sharpNeutralShiftHom` is a homomorphism, its range is therefore precisely
the subgroup generated by the images of those one-coordinate corrections.  In particular,
the remaining concrete residual theorem can be stated as membership in that coordinate span.
-/

namespace GQ2.Dyadic.LSquare

noncomputable section

open GQ2
open GQ2.Roe.Labute

local notation "ℚ̄₂" => AlgebraicClosure ℚ_[2]

namespace SqCyclotomicStageTuple

variable {K : IntermediateField ℚ_[2] ℚ̄₂} [FiniteDimensional ℚ_[2] K]
  [CompactSpace (GalK K)] [T2Space (GalK K)]
  [TotallyDisconnectedSpace (GalK K)]

/-! ## Corrections supported at one coordinate -/

/-- Retain just one coordinate of a sharp-neutral correction. -/
noncomputable def SharpNeutralCorrection.single {h k : ℕ}
    {T : SqCyclotomicStageTuple K h k} {hk : 1 ≤ k}
    (V : SharpNeutralCorrection T hk) (i : Fin (SqCore.sqRank h)) :
    SharpNeutralCorrection T hk where
  correction j := if j = i then V.correction j else 1
  depth j := by
    by_cases hji : j = i
    · simpa [hji] using V.depth j
    · simp [hji]
  sharpKernel j := by
    by_cases hji : j = i
    · simpa [hji] using V.sharpKernel j
    · simp [hji]

@[simp] theorem SharpNeutralCorrection.single_correction_same {h k : ℕ}
    {T : SqCyclotomicStageTuple K h k} {hk : 1 ≤ k}
    (V : SharpNeutralCorrection T hk) (i : Fin (SqCore.sqRank h)) :
    (V.single i).correction i = V.correction i := by
  simp [SharpNeutralCorrection.single]

@[simp] theorem SharpNeutralCorrection.single_correction_of_ne {h k : ℕ}
    {T : SqCyclotomicStageTuple K h k} {hk : 1 ≤ k}
    (V : SharpNeutralCorrection T hk) {i j : Fin (SqCore.sqRank h)}
    (hji : j ≠ i) :
    (V.single i).correction j = 1 := by
  simp [SharpNeutralCorrection.single, hji]

/-- Evaluation at one generator coordinate is a homomorphism. -/
noncomputable def sharpNeutralCorrectionEvalHom {h k : ℕ}
    {T : SqCyclotomicStageTuple K h k} {hk : 1 ≤ k}
    (i : Fin (SqCore.sqRank h)) :
    SharpNeutralCorrection T hk →*
      levelQuot (maxProPQuotient 2 (GalK K)) (k + 1) where
  toFun V := V.correction i
  map_one' := rfl
  map_mul' _ _ := rfl

/-- In an ordered product indexed by `Fin n`, a family which is `1` away from one index
multiplies to its value at that index.  No commutativity hypothesis is needed. -/
private theorem list_prod_ite_single {M : Type*} [Monoid M] {n : ℕ}
    (a : M) (j : Fin n) :
    (List.ofFn fun i : Fin n ↦ if j = i then a else 1).prod = a := by
  induction n with
  | zero => exact Fin.elim0 j
  | succ n ih =>
      refine Fin.cases ?_ (fun j' ↦ ?_) j
      · have hne (i : Fin n) : (0 : Fin (n + 1)) ≠ i.succ :=
          Ne.symm (Fin.succ_ne_zero i)
        simp [List.ofFn_succ, hne]
      · simp [List.ofFn_succ, ih]

/-- A sharp-neutral correction is the product of its one-coordinate parts. -/
theorem SharpNeutralCorrection.prod_single {h k : ℕ}
    {T : SqCyclotomicStageTuple K h k} {hk : 1 ≤ k}
    (V : SharpNeutralCorrection T hk) :
    (List.ofFn fun i : Fin (SqCore.sqRank h) ↦ V.single i).prod = V := by
  apply SharpNeutralCorrection.ext
  funext j
  change sharpNeutralCorrectionEvalHom j
      (List.ofFn fun i : Fin (SqCore.sqRank h) ↦ V.single i).prod = V.correction j
  rw [map_list_prod, List.map_ofFn]
  change (List.ofFn fun i : Fin (SqCore.sqRank h) ↦
    if j = i then V.correction j else 1).prod = V.correction j
  exact list_prod_ite_single (V.correction j) j

/-! ## The exact coordinate-span target -/

/-- Images of sharp-neutral shifts supported at a single generator coordinate. -/
def sharpNeutralCoordinateImageSet {h k : ℕ}
    (T : SqCyclotomicStageTuple K h k) (hk : 3 ≤ k) :
    Set (zLayer (maxProPQuotient 2 (GalK K)) k) :=
  {z | ∃ (V : SharpNeutralCorrection T (by omega))
      (i : Fin (SqCore.sqRank h)),
    z = sharpNeutralShiftHom T hk (V.single i)}

/-- The subgroup generated by the shifts of one-coordinate sharp-neutral corrections. -/
def sharpNeutralCoordinateSpan {h k : ℕ}
    (T : SqCyclotomicStageTuple K h k) (hk : 3 ≤ k) :
    Subgroup (zLayer (maxProPQuotient 2 (GalK K)) k) :=
  Subgroup.closure (sharpNeutralCoordinateImageSet T hk)

/-- The full sharp-neutral shift range is exactly the coordinate span. -/
theorem sharpNeutralShiftHom_range_eq_coordinateSpan {h k : ℕ}
    (T : SqCyclotomicStageTuple K h k) (hk : 3 ≤ k) :
    (sharpNeutralShiftHom T hk).range = sharpNeutralCoordinateSpan T hk := by
  apply le_antisymm
  · rintro z ⟨V, rfl⟩
    rw [← V.prod_single, map_list_prod]
    apply Subgroup.list_prod_mem
    intro z hz
    rw [List.mem_map] at hz
    obtain ⟨Vi, hVi, rfl⟩ := hz
    rw [List.mem_ofFn] at hVi
    obtain ⟨i, rfl⟩ := hVi
    exact Subgroup.subset_closure ⟨V, i, rfl⟩
  · rw [sharpNeutralCoordinateSpan, Subgroup.closure_le]
    rintro z ⟨V, i, rfl⟩
    exact ⟨V.single i, rfl⟩

/-- The residual sought by the variable-rank stage argument is reachable exactly when it lies
in the subgroup generated by the individually supported sharp-neutral shifts. -/
theorem sharpNeutralResidualReachable_iff_mem_coordinateSpan
    {h k : ℕ} {T : SqCyclotomicStageTuple K h k} {hk : 3 ≤ k}
    (W : SharpAdmissibleCorrection T (by omega)) :
    SharpNeutralResidualReachable T hk W ↔
      sharpNeutralResidualElement T hk W ∈ sharpNeutralCoordinateSpan T hk := by
  rw [sharpNeutralResidualReachable_iff_mem_range,
    sharpNeutralShiftHom_range_eq_coordinateSpan]

/-- Equivalently, the affine actual-defect supply is reduced to the same concrete
coordinate-span membership statement. -/
theorem nonempty_coreHandleSharpActualDefectSupply_iff_mem_coordinateSpan
    {h k : ℕ} {T : SqCyclotomicStageTuple K h k} {hk : 3 ≤ k}
    (W : SharpAdmissibleCorrection T (by omega)) :
    Nonempty (CoreHandleSharpActualDefectSupply T hk) ↔
      sharpNeutralResidualElement T hk W ∈ sharpNeutralCoordinateSpan T hk := by
  rw [nonempty_coreHandleSharpActualDefectSupply_iff_neutralResidual,
    sharpNeutralResidualReachable_iff_mem_coordinateSpan]

end SqCyclotomicStageTuple

#print axioms SqCyclotomicStageTuple.SharpNeutralCorrection.prod_single
#print axioms SqCyclotomicStageTuple.sharpNeutralShiftHom_range_eq_coordinateSpan
#print axioms SqCyclotomicStageTuple.sharpNeutralResidualReachable_iff_mem_coordinateSpan
#print axioms SqCyclotomicStageTuple.nonempty_coreHandleSharpActualDefectSupply_iff_mem_coordinateSpan

end

end GQ2.Dyadic.LSquare
