/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-5
-/
import GQ2.Dyadic.Instances.GammaLOddDegreeGrandAssembly
import GQ2.Dyadic.Instances.GammaLSylowPreimageFieldLabuteLevelThreeBase

/-!
# Halving the frame residual: topological generation is free

`MarkedFrame.SqCupAdaptedFramePresentation K` is a conjunction of two clauses about an
arbitrary cup-adapted Frattini frame `F` of `G_K(2)`:

1. `SqCore.sqRelWord F.generators = 1` — the improved relator vanishes globally on `F`;
2. `(Subgroup.closure (Set.range F.generators)).topologicalClosure = ⊤` — `F` generates.

Clause 2 is not a residual at all: it is the Frattini/Burnside basis theorem for pro-`2`
groups, and a `SqCyclotomicFrattiniFrame` carries generation in `G/λ₂` (`levelTwoGen`) by
definition.  This file proves it for *every* frame (cup-adaptation is never used) and therefore
reduces the stage lane's residual to the single clause `SqCupAdaptedFrameRelator K`.

The proof of the general lemma `topologicalClosure_closure_range_eq_top_of_levelTwo` is the
standard two-step:

* level-two generation propagates up the two-central tower, because `λ₂/λ_{k+1}` is contained in
  the Frattini subgroup of the finite `2`-group `G/λ_{k+1}` (`eq_top_of_map_levelProj_eq_top`);
* the tower is cofinal in the open subgroups (`exists_twoCentralSeries_le`), so the abstract
  subgroup generated by the tuple meets every neighbourhood of every point.

## What this does *not* close

Clause 1 remains open, and its level-three shadow is exactly the boundary:
`oddDegreeSqLevelThreeRelationRealization` proves `F.LevelThreeRelation` for every cup-adapted
frame, i.e. the relator dies modulo `λ₃` **on `F`'s own generators**
(`levelThreeRelation_of_isCupAdapted` below).  What the forward chain cannot do is propagate
that to level four: `SqCyclotomicStageTuple.DefectReachable.toNext` kills the stage defect by
multiplying the generators by a correction of depth `k − 1`, which at `k = 3` already moves the
tuple inside `λ₂/λ₃`.  So `stage_nonempty_three_add` propagates *nonemptiness* of the stage
tower only, `finiteLevelEpiData_nonempty_of_base_and_corrections` then picks an unrelated
high-level tuple, and `forwardGeneratorData_of_finiteLevel` re-selects the global generators by
König plus compactness.  The frame is erased at the very first correction step, which is why the
relator clause has to be stated frame-first rather than extracted from the chain.
-/

namespace GQ2.Dyadic.LSquare

noncomputable section

open GQ2 GQ2.Roe.Labute

local notation "ℚ̄₂" => AlgebraicClosure ℚ_[2]

/-! ## §1 The pro-2 Frattini generation lemma -/

section Generation

variable {G : Type} [Group G] [TopologicalSpace G] [IsTopologicalGroup G] [CompactSpace G]
  [T2Space G] [TotallyDisconnectedSpace G]

/-- **Level-two generation propagates up the two-central tower.**  Each layer `λ₂/λ_{k+1}` sits
inside the Frattini subgroup of the finite `2`-group `G/λ_{k+1}`, so a subgroup surjecting onto
`G/λ_k` is everything. -/
theorem closure_range_levelMk_eq_top_of_levelTwo
    (hfg : ∃ s : Finset G, (Subgroup.closure (s : Set G)).topologicalClosure = ⊤)
    (hpro : IsProP 2 G) {ι : Type*} (gens : ι → G)
    (hgen : Subgroup.closure (Set.range fun i ↦ levelMk G 2 (gens i)) = ⊤) (k : ℕ)
    (hk : 2 ≤ k) : Subgroup.closure (Set.range fun i ↦ levelMk G k (gens i)) = ⊤ := by
  induction k, hk using Nat.le_induction with
  | base => exact hgen
  | succ k hk ih =>
      have himage : (levelProj G k) '' (Set.range fun i ↦ levelMk G (k + 1) (gens i)) =
          Set.range fun i ↦ levelMk G k (gens i) := by
        rw [← Set.range_comp]
        exact congrArg Set.range (funext fun i ↦ levelProj_levelMk G k (gens i))
      refine eq_top_of_map_levelProj_eq_top G hfg hpro hk ?_
      rw [MonoidHom.map_closure, himage]
      exact ih

/-- **The Frattini/Burnside basis theorem in the form the frame lane needs.**  A tuple of
elements of a topologically finitely generated pro-`2` group whose images generate `G/λ₂`
generates `G` topologically.  No relation, no orientation, no cup datum is used. -/
theorem topologicalClosure_closure_range_eq_top_of_levelTwo
    (hfg : ∃ s : Finset G, (Subgroup.closure (s : Set G)).topologicalClosure = ⊤)
    (hpro : IsProP 2 G) {ι : Type*} (gens : ι → G)
    (hgen : Subgroup.closure (Set.range fun i ↦ levelMk G 2 (gens i)) = ⊤) :
    (Subgroup.closure (Set.range gens)).topologicalClosure = ⊤ := by
  set A : Subgroup G := Subgroup.closure (Set.range gens) with hA
  have happrox : ∀ (k : ℕ), 2 ≤ k → ∀ y : G, ∃ a ∈ A, a⁻¹ * y ∈ twoCentralSeries G k := by
    intro k hk y
    have hmap : A.map (levelMk G k) = ⊤ := by
      rw [hA, MonoidHom.map_closure, ← Set.range_comp]
      exact closure_range_levelMk_eq_top_of_levelTwo hfg hpro gens hgen k hk
    have hy : levelMk G k y ∈ A.map (levelMk G k) := by rw [hmap]; trivial
    obtain ⟨a, haA, hay⟩ := hy
    exact ⟨a, haA, QuotientGroup.eq.mp hay⟩
  rw [Subgroup.eq_top_iff']
  intro y
  show y ∈ closure (A : Set G)
  rw [mem_closure_iff]
  intro V hV hyV
  have hWopen : IsOpen ((fun w : G ↦ y * w) ⁻¹' V) :=
    hV.preimage (continuous_const.mul continuous_id)
  have h1W : (1 : G) ∈ (fun w : G ↦ y * w) ⁻¹' V := by simpa using hyV
  obtain ⟨W, hW⟩ := ProfiniteGrp.exist_openNormalSubgroup_sub_open_nhds_of_one hWopen h1W
  obtain ⟨k₀, hk₀⟩ := exists_twoCentralSeries_le G hfg hpro W.toOpenSubgroup.isOpen
  obtain ⟨a, haA, hay⟩ := happrox (max k₀ 2) (le_max_right _ _) y
  have hmem : (a⁻¹ * y)⁻¹ ∈ W.toSubgroup :=
    inv_mem (hk₀ (twoCentralSeries_antitone G (le_max_left k₀ 2) hay))
  have haV : a ∈ V := by
    have := hW hmem
    rw [Set.mem_preimage] at this
    rwa [show y * (a⁻¹ * y)⁻¹ = a from by group] at this
  exact ⟨a, haV, haA⟩

end Generation

/-! ## §2 The frame residual, halved -/

section Frame

variable {K : IntermediateField ℚ_[2] ℚ̄₂} [FiniteDimensional ℚ_[2] K]
  [CompactSpace (GalK K)] [T2Space (GalK K)] [TotallyDisconnectedSpace (GalK K)]

/-- **Every Frattini frame generates topologically.**  This is the second clause of
`SqCupAdaptedFramePresentation`, unconditionally and without cup-adaptation. -/
theorem sqCyclotomicFrattiniFrame_topologicalClosure_eq_top {h : ℕ}
    (F : SqCyclotomicFrattiniFrame K h) :
    (Subgroup.closure (Set.range F.generators)).topologicalClosure = ⊤ :=
  topologicalClosure_closure_range_eq_top_of_levelTwo
    (maxProTwoGalK_isTopologicallyFinGen K) isProP_maxProPQuotient F.generators F.levelTwoGen

/-- **The stage lane's residual, halved**: the improved relator vanishes globally on every
cup-adapted Frattini frame.  This is `SqCupAdaptedFramePresentation` with the generation clause
deleted. -/
def SqCupAdaptedFrameRelator (K : IntermediateField ℚ_[2] ℚ̄₂) [FiniteDimensional ℚ_[2] K]
    [CompactSpace (GalK K)] [T2Space (GalK K)] [TotallyDisconnectedSpace (GalK K)] : Prop :=
  ∀ (h : ℕ) (F : SqCyclotomicFrattiniFrame K h), F.IsCupAdapted →
    SqCore.sqRelWord F.generators = 1

/-- The relator clause alone implies the full presentation clause. -/
theorem sqCupAdaptedFramePresentation_of_relator (hrel : SqCupAdaptedFrameRelator K) :
    MarkedFrame.SqCupAdaptedFramePresentation K :=
  fun h F hcup ↦ ⟨hrel h F hcup, sqCyclotomicFrattiniFrame_topologicalClosure_eq_top F⟩

/-- **The level-three shadow of the residual is a theorem**, and it is frame-tracked: the
improved word dies modulo `λ₃` on the frame's *own* generators.  The gap is entirely above
level three. -/
theorem levelThreeRelation_of_isCupAdapted (hodd : Odd (Module.finrank ℚ_[2] K))
    (F : SqCyclotomicFrattiniFrame K ((Module.finrank ℚ_[2] K - 1) / 2))
    (hcup : F.IsCupAdapted) : F.LevelThreeRelation :=
  oddDegreeSqLevelThreeRelationRealization K hodd F hcup

end Frame

/-! ## §3 The endpoints restated over the halved residual -/

section Endpoints

variable {Rec : LocalReciprocity} {K : IntermediateField ℚ_[2] ℚ̄₂} [FiniteDimensional ℚ_[2] K]
  [CompactSpace (GalK K)] [T2Space (GalK K)] [TotallyDisconnectedSpace (GalK K)]
  [CompactSpace AbsGalQ2] [TotallyDisconnectedSpace AbsGalQ2]

/-- The odd-degree pro-2 block over the halved residual. -/
theorem markedCoreRealization_of_finrank_of_relator (B : MarkedRecip Rec K)
    (FF : DyadicUnitFiltration K) {h : ℕ} (hdeg : Module.finrank ℚ_[2] K = 2 * h + 1)
    (hclear : SqCore.SqNuClearHypothesis h) (hrel : SqCupAdaptedFrameRelator K) :
    Nonempty (MarkedCoreRealization (K := K) (B := B) (SqCore.DSq h)
      (Instances.LSquareCore.lNu h)) :=
  markedCoreRealization_of_finrank B FF hdeg hclear
    (sqCupAdaptedFramePresentation_of_relator hrel)

/-- **The grand assembly over the halved residual.**  `Γ_{R_K} ≅ G_K` for every odd-degree
ramified `K`, over the χ-free clearing binder and the relator clause alone. -/
theorem gammaR_lSq_equiv_galK_oddDegree_of_relator (B : MarkedRecip Rec K)
    {FF : DyadicUnitFiltration K} (T : OrientedTameQuotientK B FF)
    (D : FiniteDyadicParameters K FF) {h : ℕ}
    (hdeg : Module.finrank ℚ_[2] K = 2 * h + 1) (hclear : SqCore.SqNuClearHypothesis h)
    (hrel : SqCupAdaptedFrameRelator K)
    (ramifiedData : ∀ {Dg : Type} [Group Dg] [TopologicalSpace Dg] [DiscreteTopology Dg]
      [Finite Dg] (W : Type) [AddCommGroup W] [DistribMulAction Dg W]
      (cc : ContinuousMonoidHom (Tq D.params.qK) Dg)
      (rho : ContinuousMonoidHom (GalK K) Dg),
      (∃ v : W, cc (tqTau D.params.qK) • v ≠ v) →
        Nonempty (RamifiedCertificate D.params (GalKsub K) W cc rho)) :
    Nonempty (ContinuousMulEquiv (gamma h (qOf K FF) : Type) (GalK K)) :=
  gammaR_lSq_equiv_galK_oddDegree B T D hdeg hclear
    (sqCupAdaptedFramePresentation_of_relator hrel) ramifiedData

/-- The `h = 0` full circle over the halved residual. -/
theorem gammaR_lSq_equiv_galK_degreeOne_of_relator (B : MarkedRecip Rec K)
    {FF : DyadicUnitFiltration K} (T : OrientedTameQuotientK B FF)
    (D : FiniteDyadicParameters K FF) (hdeg : Module.finrank ℚ_[2] K = 1)
    (hrel : SqCupAdaptedFrameRelator K)
    (ramifiedData : ∀ {Dg : Type} [Group Dg] [TopologicalSpace Dg] [DiscreteTopology Dg]
      [Finite Dg] (W : Type) [AddCommGroup W] [DistribMulAction Dg W]
      (cc : ContinuousMonoidHom (Tq D.params.qK) Dg)
      (rho : ContinuousMonoidHom (GalK K) Dg),
      (∃ v : W, cc (tqTau D.params.qK) • v ≠ v) →
        Nonempty (RamifiedCertificate D.params (GalKsub K) W cc rho)) :
    Nonempty (ContinuousMulEquiv (gamma 0 (qOf K FF) : Type) (GalK K)) :=
  gammaR_lSq_equiv_galK_degreeOne B T D hdeg
    (sqCupAdaptedFramePresentation_of_relator hrel) ramifiedData

end Endpoints

end

#print axioms GQ2.Dyadic.LSquare.closure_range_levelMk_eq_top_of_levelTwo
#print axioms GQ2.Dyadic.LSquare.topologicalClosure_closure_range_eq_top_of_levelTwo
#print axioms GQ2.Dyadic.LSquare.sqCyclotomicFrattiniFrame_topologicalClosure_eq_top
#print axioms GQ2.Dyadic.LSquare.sqCupAdaptedFramePresentation_of_relator
#print axioms GQ2.Dyadic.LSquare.levelThreeRelation_of_isCupAdapted
#print axioms GQ2.Dyadic.LSquare.gammaR_lSq_equiv_galK_oddDegree_of_relator
#print axioms GQ2.Dyadic.LSquare.gammaR_lSq_equiv_galK_degreeOne_of_relator

end GQ2.Dyadic.LSquare
