/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-5
-/
import GQ2.Dyadic.Instances.N0M0ScalarStokes
import GQ2.Dyadic.Instances.N0ActionImageDevissage
import GQ2.Dyadic.Instances.M0ActionImageDevissage

/-!
# The compact-row simple-Stokes branch theorems

`N0ActionImageDevissage` and `M0ActionImageDevissage` reduce the compact even rows' uniform
Stokes residue to four named propositions — one per row, one per branch of the `tau` dichotomy.
This file discharges three of them and records what the fourth still needs.

| row | branch | status |
|---|---|---|
| `N` | ramified | `NCompact.ramifiedSimpleStokes` — proved |
| `N` | unramified | `NCompact.unramifiedSimpleStokes` — proved |
| `M` | unramified | `MCompact.unramifiedSimpleStokes` — proved |
| `M` | ramified | open; see `MCompact.RamifiedSimpleStokes` and the note below |

The two unramified branches need one structural fact that the word-generic action-image package
did not yet contain: on an unramified simple coefficient the action image is generated by the
image of `sigma` alone, so the `sigma`-fixed subspace is a submodule and `sigma` either acts
trivially or acts without nonzero fixed vectors.  Both halves are supplied here
(`actionImage_sigma_split_or_fixedPointFree`), together with the `sigma`-analogue of
`actionImage_tau_powOmega2_smul_trivial`, which is what turns the compact-`M` rows into the
compact-`N` rows on a simple unramified coefficient.

**What the compact-`M` ramified branch still needs.**  Everything in the normal-form route is in
place for it (`evenNormalStokesDuality`, the `x₂`-pivot row `foxD_mCompact_ram`, the normal
coordinates and the pairing separation): the single missing input is the *second-order* value

`heisZ_mCompact_ram : (heisEvalZ ⇑t x y E E₂ (mCompactW α h)).z = …`

on offsets vanishing at `sigma`, `tau` and `x₂`, in the ramified class.  Unlike the compact-`N`
row, that value is **not** the sum of jet-zero factors: with `tau` ramified the `σ₂`-twist
survives, because `powOmega2 t.σ` need not act trivially on a ramified simple module (an
explicit witness: `C = ⟨τ⟩ ⋊ ⟨σ⟩` with `τ` of order `3`, `σ` of order `2` acting by inversion,
`A = 𝔽₄` with `σ` the Frobenius — `τ` is fixed-point free, `powOmega2 τ = 1`, and
`powOmega2 σ = σ` acts nontrivially).  So the `A₀²`, `[A₀,x₁]` and `𝓔`-block contributions each
carry the operator `S₂^{−m}` and must be shown to cancel over `𝔽₂`, exactly as they already do
at first order in `foxD_mCompact_ram`.
-/

namespace GQ2.Dyadic

noncomputable section

open GQ2 GQ2.FoxH
open Count Certificates Words RowActionImage

/-! ## The `sigma` dichotomy on an unramified simple coefficient -/

set_option maxHeartbeats 1200000 in
/-- On a simple elementary coefficient on which `tau` acts trivially, the `2`-primary part of
`sigma` acts trivially.  Its fixed space is stable under `sigma` by commutation and under every
other generator because those act trivially. -/
theorem actionImage_sigma_powOmega2_smul_trivial
    {n q : ℕ} {R : PWord (Generator n)} {M : Type}
    [AddCommGroup M] [TopologicalSpace M] [DiscreteTopology M]
    [DistribMulAction ((GammaR n q R : Type)) M]
    [ContinuousSMul ((GammaR n q R : Type)) M] [Finite M]
    (hM₂ : ∀ m : M, m + m = 0) (hsimple : IsSimpleModTwo (GammaR n q R : Type) M)
    (hτ : ∀ m : M, gammaGen n q R .tau • m = m) :
    ∀ m : M, powOmega2 (actionImageMarking n q R M).σ • m = m := by
  let t := actionImageMarking n q R M
  have hwild : ∀ (i : Fin (n + 1)) (m : M), t.x i • m = m :=
    actionImage_wild_smul hM₂ hsimple
  have hτ' : ∀ m : M, t.τ • m = m := fun m ↦ hτ m
  refine pow2_smul_trivial_of_stable hM₂ (isSimpleModTwo_actionImage hsimple)
    (powOmega2 t.σ) (isPGroup_zpowers_powOmega2 t.σ) ?_
  have hσ : ∀ v : M, powOmega2 t.σ • v = v → powOmega2 t.σ • (t.σ • v) = t.σ • v := by
    intro v hv
    have hcomm : powOmega2 t.σ * t.σ = t.σ * powOmega2 t.σ := by
      rw [powOmega2]
      exact ((Commute.refl t.σ).pow_left _).eq
    rw [← mul_smul, hcomm, mul_smul, hv]
  let S : Subgroup (ActionImage n q R M) :=
    { carrier := {c | ∀ v : M, powOmega2 t.σ • v = v → powOmega2 t.σ • (c • v) = c • v}
      one_mem' := fun v hv ↦ by rwa [one_smul]
      mul_mem' := fun {a b} ha hb v hv ↦ by rw [mul_smul]; exact ha _ (hb v hv)
      inv_mem' := fun {a} ha v hv ↦ by
        let W : AddSubgroup M :=
          { carrier := {w | powOmega2 t.σ • w = w}
            zero_mem' := smul_zero _
            add_mem' := fun {x y} hx hy ↦ by
              show powOmega2 t.σ • (x + y) = x + y
              rw [smul_add, hx, hy]
            neg_mem' := fun {x} hx ↦ by
              show powOmega2 t.σ • (-x) = -x
              rw [smul_neg, hx] }
        have hφinj : Function.Injective (fun u : W ↦ (⟨a • u.1, ha u.1 u.2⟩ : W)) := by
          intro x y hxy
          exact Subtype.ext (MulAction.injective a (congrArg Subtype.val hxy))
        obtain ⟨⟨u, hu⟩, hux⟩ := (Finite.injective_iff_surjective.mp hφinj) ⟨v, hv⟩
        have huv : a • u = v := congrArg Subtype.val hux
        rw [show a⁻¹ • v = u from by rw [← huv, inv_smul_smul]]
        exact hu }
  have hgenS : Subgroup.closure (Set.range (actionImageGenerators n q R M)) ≤ S := by
    rw [Subgroup.closure_le]
    rintro _ ⟨g, rfl⟩
    cases g with
    | sigma => exact hσ
    | tau =>
        intro v hv
        change powOmega2 t.σ • (t.τ • v) = t.τ • v
        rw [hτ' v]
        exact hv
    | wild i =>
        intro v hv
        change powOmega2 t.σ • (t.x i • v) = t.x i • v
        rw [hwild i v]
        exact hv
  rw [actionImageGenerators_generate] at hgenS
  exact fun c ↦ hgenS (Subgroup.mem_top c)

set_option maxHeartbeats 1200000 in
/-- On a simple elementary coefficient on which `tau` acts trivially, `sigma` either acts
trivially as well — and then the whole action image does — or has no nonzero fixed vector.  This
is the second dichotomy of the unramified branch. -/
theorem actionImage_sigma_split_or_fixedPointFree
    {n q : ℕ} {R : PWord (Generator n)} {M : Type}
    [AddCommGroup M] [TopologicalSpace M] [DiscreteTopology M]
    [DistribMulAction ((GammaR n q R : Type)) M]
    [ContinuousSMul ((GammaR n q R : Type)) M] [Finite M]
    (hM₂ : ∀ m : M, m + m = 0) (hsimple : IsSimpleModTwo (GammaR n q R : Type) M)
    (hτ : ∀ m : M, gammaGen n q R .tau • m = m) :
    (∀ m : M, (actionImageMarking n q R M).σ • m = m) ∨
      (∀ m : M, (actionImageMarking n q R M).σ • m = m → m = 0) := by
  let t := actionImageMarking n q R M
  have hwild : ∀ (i : Fin (n + 1)) (m : M), t.x i • m = m :=
    actionImage_wild_smul hM₂ hsimple
  have hτ' : ∀ m : M, t.τ • m = m := fun m ↦ hτ m
  let W : AddSubgroup M :=
    { carrier := {m | t.σ • m = m}
      zero_mem' := smul_zero _
      add_mem' := fun {a b} ha hb ↦ by
        change t.σ • (a + b) = a + b
        rw [smul_add, ha, hb]
      neg_mem' := fun {a} ha ↦ by
        change t.σ • (-a) = -a
        rw [smul_neg, ha] }
  let S : Subgroup (ActionImage n q R M) :=
    { carrier := {c | ∀ m : M, m ∈ W → c • m ∈ W}
      one_mem' := fun m hm ↦ by simpa using hm
      mul_mem' := fun {a b} ha hb m hm ↦ by rw [mul_smul]; exact ha _ (hb m hm)
      inv_mem' := fun {a} ha m hm ↦ by
        have hφinj : Function.Injective (fun u : W ↦ (⟨a • u.1, ha u.1 u.2⟩ : W)) := by
          intro x y hxy
          exact Subtype.ext (MulAction.injective a (congrArg Subtype.val hxy))
        obtain ⟨⟨u, hu⟩, hux⟩ := (Finite.injective_iff_surjective.mp hφinj) ⟨m, hm⟩
        have hum : a • u = m := congrArg Subtype.val hux
        show t.σ • (a⁻¹ • m) = a⁻¹ • m
        rw [show a⁻¹ • m = u from by rw [← hum, inv_smul_smul]]
        exact hu }
  have hσS : t.σ ∈ S := by
    intro m hm
    change t.σ • m = m at hm
    show t.σ • (t.σ • m) = t.σ • m
    exact congrArg (fun x ↦ t.σ • x) hm
  have hτS : t.τ ∈ S := by
    intro m hm
    change t.σ • m = m at hm
    show t.σ • (t.τ • m) = t.τ • m
    rw [hτ' m]
    exact hm
  have hxS : ∀ i, t.x i ∈ S := by
    intro i m hm
    change t.σ • m = m at hm
    show t.σ • (t.x i • m) = t.x i • m
    rw [hwild i m]
    exact hm
  have hgenS : Subgroup.closure (Set.range (actionImageGenerators n q R M)) ≤ S := by
    rw [Subgroup.closure_le]
    rintro _ ⟨g, rfl⟩
    cases g with
    | sigma => exact hσS
    | tau => exact hτS
    | wild i => exact hxS i
  rw [actionImageGenerators_generate] at hgenS
  have hstable : ∀ (c : ActionImage n q R M) (m : M), m ∈ W → c • m ∈ W := fun c ↦
    hgenS (Subgroup.mem_top c)
  rcases (isSimpleModTwo_actionImage hsimple).2 W hstable with hbot | htop
  · right
    intro m hm
    have hmW : m ∈ W := hm
    rw [hbot, AddSubgroup.mem_bot] at hmW
    exact hmW
  · left
    intro m
    have hmW : m ∈ W := by rw [htop]; exact AddSubgroup.mem_top m
    exact hmW

end

end GQ2.Dyadic

namespace GQ2.Dyadic.NCompact

noncomputable section

open GQ2 GQ2.FoxH
open GQ2.Dyadic GQ2.Dyadic.Count GQ2.Dyadic.RowActionImage
open GQ2.Dyadic.Words GQ2.Dyadic.Certificates

set_option maxHeartbeats 1600000 in
/-- **The compact-`N` ramified branch.** -/
theorem ramifiedSimpleStokes {α h q : ℕ} (hα : 2 ≤ α) (hq : Even q) :
    RamifiedSimpleStokes α h q := by
  intro M _ _ _ _ _ _ hM₂ hsimple hτfpf
  let t := actionImageMarking (2 + 2 * h) q (nCompactW α h) M
  have ht : t.TameRelAt q := actionImage_nCompact_tameRelAt
  have hwild : ∀ (i : Fin (2 + 2 * h + 1)) (m : M), t.x i • m = m :=
    actionImage_wild_smul hM₂ hsimple
  have hτfpf' : ∀ m : M, t.τ • m = m → m = 0 := fun m hm ↦ hτfpf m hm
  have hTodd : ∀ m : M, powOmega2 t.τ • m = m :=
    actionImage_tau_powOmega2_smul_trivial hM₂ hsimple
  exact nCompactStokesDuality_ramified t hM₂ hq ht hwild hτfpf' hTodd hα
    actionImage_nCompact_relator_death_resolved

set_option maxHeartbeats 1600000 in
/-- **The compact-`N` unramified branch**, both `sigma` sub-branches. -/
theorem unramifiedSimpleStokes {α h q : ℕ} (hα : 2 ≤ α) (hq : Even q) :
    UnramifiedSimpleStokes α h q := by
  intro M _ _ _ _ _ _ hM₂ hsimple hτ
  let t := actionImageMarking (2 + 2 * h) q (nCompactW α h) M
  have ht : t.TameRelAt q := actionImage_nCompact_tameRelAt
  have hwild : ∀ (i : Fin (2 + 2 * h + 1)) (m : M), t.x i • m = m :=
    actionImage_wild_smul hM₂ hsimple
  have hτ' : ∀ m : M, t.τ • m = m := fun m ↦ hτ m
  rcases actionImage_sigma_split_or_fixedPointFree
    (n := 2 + 2 * h) (q := q) (R := nCompactW α h) hM₂ hsimple hτ with hσ | hσfpf
  · exact nCompactStokesDuality_scalar t hM₂ hq ht hwild hτ' hσ hα
      actionImage_nCompact_relator_death_resolved
  · exact nCompactStokesDuality_unramified t hM₂ hq ht hwild hτ' hσfpf hα
      actionImage_nCompact_relator_death_resolved

set_option maxHeartbeats 2400000 in
/-- **The compact-`N` uniform pushed Stokes residue, unconditionally.** -/
theorem uniformPushedHsimp {α h q : ℕ} (hα : 2 ≤ α) (hq : Even q) :
    UniformPushedHsimp α h q :=
  uniformPushedHsimp_of_actionImage (unramifiedSimpleStokes hα hq)
    (ramifiedSimpleStokes hα hq) (by omega) hq

set_option maxHeartbeats 2400000 in
/-- **Corrected exact lifting for the compact-`N` presentation, unconditionally.** -/
theorem exactLiftingRN_unconditional {α h q : ℕ} (hα : 2 ≤ α) (hq0 : q ≠ 0) (hqe : Even q)
    {P : ProfiniteGrp} (nuP : ContinuousMonoidHom P Ztwo) :
    ExactLiftingSemanticsRN (gamma α h q) (2 * h + 2) q P nuP
      (standardNumerics (2 * h + 2)) :=
  exactLiftingRN_of_actionImage (unramifiedSimpleStokes hα hqe)
    (ramifiedSimpleStokes hα hqe) (by omega) hq0 hqe nuP

end

end GQ2.Dyadic.NCompact

namespace GQ2.Dyadic.MCompact

noncomputable section

open GQ2 GQ2.FoxH
open GQ2.Dyadic GQ2.Dyadic.Count GQ2.Dyadic.RowActionImage
open GQ2.Dyadic.Words GQ2.Dyadic.Words.MCompact
open GQ2.Dyadic.Certificates GQ2.Dyadic.Certificates.MCompact

set_option maxHeartbeats 1600000 in
/-- **The compact-`M` unramified branch**, both `sigma` sub-branches.  The `σ₂`-triviality of a
simple unramified coefficient is what makes the compact-`M` rows equal to the compact-`N`
ones. -/
theorem unramifiedSimpleStokes {α h q : ℕ} (hα : 2 ≤ α) (hq : Even q) :
    UnramifiedSimpleStokes α h q := by
  intro M _ _ _ _ _ _ hM₂ hsimple hτ
  let t := actionImageMarking (2 + 2 * h) q (mCompactW α h) M
  have ht : t.TameRelAt q := actionImage_mCompact_tameRelAt
  have hwild : ∀ (i : Fin (2 + 2 * h + 1)) (m : M), t.x i • m = m :=
    actionImage_wild_smul hM₂ hsimple
  have hτ' : ∀ m : M, t.τ • m = m := fun m ↦ hτ m
  have hS₂ : ∀ m : M, powOmega2 t.σ • m = m :=
    actionImage_sigma_powOmega2_smul_trivial hM₂ hsimple hτ
  rcases actionImage_sigma_split_or_fixedPointFree
    (n := 2 + 2 * h) (q := q) (R := mCompactW α h) hM₂ hsimple hτ with hσ | hσfpf
  · exact mCompactStokesDuality_scalar t hM₂ hq ht hwild hτ' hσ hα
      actionImage_mCompact_relator_death_resolved
  · exact mCompactStokesDuality_unramified t hM₂ hq ht hwild hτ' hS₂ hσfpf hα
      actionImage_mCompact_relator_death_resolved

set_option maxHeartbeats 2400000 in
/-- **The compact-`M` uniform pushed Stokes residue**, reduced to the single remaining ramified
branch. -/
theorem uniformPushedHsimp_of_ramified {α h q : ℕ} (hα : 2 ≤ α) (hq : Even q)
    (hram : RamifiedSimpleStokes α h q) : UniformPushedHsimp α h q :=
  uniformPushedHsimp_of_actionImage (unramifiedSimpleStokes hα hq) hram hq

set_option maxHeartbeats 2400000 in
/-- **Corrected exact lifting for the compact-`M` presentation**, reduced to the single
remaining ramified branch. -/
theorem exactLiftingRN_of_ramified {α h q : ℕ} (hα : 2 ≤ α) (hq0 : q ≠ 0) (hqe : Even q)
    (hram : RamifiedSimpleStokes α h q)
    {P : ProfiniteGrp} (nuP : ContinuousMonoidHom P Ztwo) :
    ExactLiftingSemanticsRN (gamma α h q) (2 * h + 2) q P nuP
      (standardNumerics (2 * h + 2)) :=
  exactLiftingRN_of_actionImage (unramifiedSimpleStokes hα hqe) hram (by omega) hq0 hqe nuP

end

end GQ2.Dyadic.MCompact
