/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-5
-/
import GQ2.Dyadic.Instances.N0M0UnramifiedStokes

/-!
# The scalar sub-branch of the unramified compact even rows

In the unramified branch every wild letter and `tau` act trivially, so the action image is
generated by the image of `sigma` alone and the `sigma`-fixed subspace is a submodule.  Either
`sigma` acts without nonzero fixed vectors — the sub-branch settled in `N0M0UnramifiedStokes` —
or `sigma` acts trivially, and then the *whole* action image does.

This file settles that residual case.  With a completely trivial action the two compact even
rows again coincide: both wild rows degenerate to the `tau`-pivot (`foxD_nCompact_split`,
`foxD_mCompact_split`), the tame row does too, and the complex is no longer acyclic at its
ends: `d⁰ = 0`, and `d¹` has rank one.  Middle cohomology is therefore *larger* than in the
generic sub-branch — its normal coordinates are `sigma, x₀, x₁, x₂` and the `h` handle pairs,
five blocks rather than three — and the traced pairing acquires the extra hyperbolic pair
`(sigma, x₂)` in place of the `(1 + S)`-atom, which is exactly what degenerates when `S = 1`.

The three cohomology clauses are proved directly: `η⁰` and `η²` are the evaluation map
`A → A^{∨∨}` in disguise, and `η¹` is again a normal-form count.
-/

namespace GQ2.Dyadic

noncomputable section

open GQ2 GQ2.FoxH
open Count Certificates Words Certificates.MProcyclic

variable {h α q : ℕ}

/-! ## Biduality for a finite elementary module -/

/-- Evaluation of an elementary module into its double dual. -/
def elemDualEval {A : Type*} [AddCommGroup A] : A →+ ElemDual (ElemDual A) :=
  AddMonoidHom.mk'
    (fun a ↦ (AddMonoidHom.mk' (fun lam : ElemDual A ↦ lam a) (fun _ _ ↦ rfl) :
      ElemDual (ElemDual A)))
    (fun a b ↦ by
      apply ElemDual.ext
      intro lam
      exact map_add lam a b)

@[simp] theorem elemDualEval_apply {A : Type*} [AddCommGroup A] (a : A) (lam : ElemDual A) :
    elemDualEval a lam = lam a := rfl

theorem elemDualEval_injective {A : Type*} [AddCommGroup A] [Finite A]
    (hA₂ : ∀ a : A, a + a = 0) : Function.Injective (elemDualEval (A := A)) := by
  rw [injective_iff_map_eq_zero]
  intro a ha
  by_contra hne
  obtain ⟨lam, hlam⟩ := elemDual_separates hA₂ hne
  exact hlam (DFunLike.congr_fun ha lam)

theorem elemDualEval_bijective {A : Type*} [AddCommGroup A] [Finite A]
    (hA₂ : ∀ a : A, a + a = 0) : Function.Bijective (elemDualEval (A := A)) := by
  rw [Nat.bijective_iff_injective_and_card]
  refine ⟨elemDualEval_injective hA₂, ?_⟩
  rw [card_elemDual (fun lam : ElemDual A ↦ lam.add_self_eq_zero), card_elemDual hA₂]

/-! ## Scalar normal cochains -/

/-- An offset vector on the degree-`2` core with arbitrary `sigma` and wild coordinates and
zero `tau` coordinate. -/
def evenScalarCoreOffsets {A : Type*} [AddCommGroup A] (aσ : A) (d : Fin 3 → A) :
    Generator 2 → A
  | .sigma => aσ
  | .tau => 0
  | .wild i => d i

/-- A scalar normal cochain: every coordinate except `tau` is free. -/
def evenScalarNormal (h : ℕ) {A : Type*} [AddCommGroup A]
    (aσ d₀ d₁ d₂ : A) (z : Fin h × Fin 2 → A) : Generator (2 + 2 * h) → A :=
  (EvenCore.coreHandleAddEquiv h A).symm (evenScalarCoreOffsets aσ ![d₀, d₁, d₂], z)

@[simp] theorem evenScalarNormal_core (h : ℕ) {A : Type*} [AddCommGroup A]
    (aσ d₀ d₁ d₂ : A) (z : Fin h × Fin 2 → A) :
    EvenCore.coreRestrict h A (evenScalarNormal h aσ d₀ d₁ d₂ z)
      = evenScalarCoreOffsets aσ ![d₀, d₁, d₂] := by
  rw [← EvenCore.coreHandleAddEquiv_fst]
  simp [evenScalarNormal]

@[simp] theorem evenScalarNormal_sigma (h : ℕ) {A : Type*} [AddCommGroup A]
    (aσ d₀ d₁ d₂ : A) (z : Fin h × Fin 2 → A) :
    evenScalarNormal h aσ d₀ d₁ d₂ z .sigma = aσ :=
  congrFun (evenScalarNormal_core h aσ d₀ d₁ d₂ z) Generator.sigma

@[simp] theorem evenScalarNormal_tau (h : ℕ) {A : Type*} [AddCommGroup A]
    (aσ d₀ d₁ d₂ : A) (z : Fin h × Fin 2 → A) :
    evenScalarNormal h aσ d₀ d₁ d₂ z .tau = 0 :=
  congrFun (evenScalarNormal_core h aσ d₀ d₁ d₂ z) Generator.tau

@[simp] theorem evenScalarNormal_coreLetter (h : ℕ) {A : Type*} [AddCommGroup A]
    (aσ d₀ d₁ d₂ : A) (z : Fin h × Fin 2 → A) (i : Fin 3) :
    evenScalarNormal h aσ d₀ d₁ d₂ z (coreLetter h i) = ![d₀, d₁, d₂] i :=
  congrFun (evenScalarNormal_core h aσ d₀ d₁ d₂ z) (Generator.wild i)

@[simp] theorem evenScalarNormal_handleU {h : ℕ} {A : Type*} [AddCommGroup A]
    (aσ d₀ d₁ d₂ : A) (z : Fin h × Fin 2 → A) (j : Fin h) :
    evenScalarNormal h aσ d₀ d₁ d₂ z (handleU j) = z (j, 0) := by
  have hh := congrArg (fun p : (Generator 2 → A) × (Fin h × Fin 2 → A) ↦ p.2 (j, 0))
    ((EvenCore.coreHandleAddEquiv h A).apply_symm_apply
      (evenScalarCoreOffsets aσ ![d₀, d₁, d₂], z))
  change ((EvenCore.coreHandleAddEquiv h A)
    (evenScalarNormal h aσ d₀ d₁ d₂ z)).2 (j, 0) = z (j, 0) at hh
  rw [EvenCore.coreHandleAddEquiv_snd_zero] at hh
  exact hh

@[simp] theorem evenScalarNormal_handleV {h : ℕ} {A : Type*} [AddCommGroup A]
    (aσ d₀ d₁ d₂ : A) (z : Fin h × Fin 2 → A) (j : Fin h) :
    evenScalarNormal h aσ d₀ d₁ d₂ z (handleV j) = z (j, 1) := by
  have hh := congrArg (fun p : (Generator 2 → A) × (Fin h × Fin 2 → A) ↦ p.2 (j, 1))
    ((EvenCore.coreHandleAddEquiv h A).apply_symm_apply
      (evenScalarCoreOffsets aσ ![d₀, d₁, d₂], z))
  change ((EvenCore.coreHandleAddEquiv h A)
    (evenScalarNormal h aσ d₀ d₁ d₂ z)).2 (j, 1) = z (j, 1) at hh
  rw [EvenCore.coreHandleAddEquiv_snd_one] at hh
  exact hh

@[simp] theorem evenScalarNormal_zero (h : ℕ) {A : Type*} [AddCommGroup A] :
    evenScalarNormal h (0 : A) 0 0 0 (0 : Fin h × Fin 2 → A) = 0 := by
  have hd : (![(0 : A), 0, 0] : Fin 3 → A) = 0 := by
    funext i
    fin_cases i <;> rfl
  have hc : evenScalarCoreOffsets (0 : A) ![(0 : A), 0, 0] = 0 := by
    rw [hd]
    funext g
    cases g <;> rfl
  rw [evenScalarNormal, hc]
  exact (EvenCore.coreHandleAddEquiv h A).symm.map_zero

/-- The scalar normal parameter, packed. -/
abbrev ScalarParam (h : ℕ) (A : Type*) [AddCommGroup A] : Type _ :=
  A × A × A × A × (Fin h × Fin 2 → A)

/-- The scalar normal cochain of a packed parameter. -/
def evenScalarNormalP (h : ℕ) {A : Type*} [AddCommGroup A] (p : ScalarParam h A) :
    Generator (2 + 2 * h) → A :=
  evenScalarNormal h p.1 p.2.1 p.2.2.1 p.2.2.2.1 p.2.2.2.2

@[simp] theorem evenScalarNormalP_zero (h : ℕ) {A : Type*} [AddCommGroup A] :
    evenScalarNormalP h (0 : ScalarParam h A) = 0 :=
  evenScalarNormal_zero h

theorem card_scalarParam (h : ℕ) {A : Type*} [AddCommGroup A] [Finite A]
    (hA₂ : ∀ a : A, a + a = 0) :
    Nat.card (ScalarParam h A) = Nat.card (ScalarParam h (ElemDual A)) := by
  simp only [ScalarParam, Nat.card_prod, Nat.card_fun, card_elemDual hA₂]

/-! ## Middle bijectivity from a normal form, in general -/

set_option maxHeartbeats 3200000 in
/-- **`H¹` is bijective as soon as the middle cohomology is freely parametrised and the traced
pairing separates the parameters.**  Extracted from the ramified assembly so that the scalar
sub-branch, whose ends are *not* acyclic, can reuse it. -/
theorem stokesH1Map_bijective_of_normalForm
    {C A : Type*} [Group C] [AddCommGroup A] [Finite A] [DistribMulAction C A]
    {P PD : Type*} [Zero P] [Finite P] [Finite PD]
    (t : Marking (2 + 2 * h) C) (w : Fin 2 → FreeGroup (Generator (2 + 2 * h)))
    (hr : ∀ k, FreeGroup.lift ⇑t (w k) = 1) (hend : IsStokesEndpoint w)
    (normalA : P → (Generator (2 + 2 * h) → A))
    (normalD : PD → (Generator (2 + 2 * h) → ElemDual A))
    (hnormalA0 : normalA 0 = 0)
    (hmemA : ∀ p, heisD1 ⇑t w (normalA p) = 0)
    (hmemD : ∀ r, heisD1 ⇑t w (normalD r) = 0)
    (hnfA : ∀ x, heisD1 (A := A) ⇑t w x = 0 →
      ∃! p : P, x - normalA p ∈ Set.range (heisD0 ⇑t))
    (hnfD : ∀ y, heisD1 (A := ElemDual A) ⇑t w y = 0 →
      ∃! r : PD, y - normalD r ∈ Set.range (heisD0 ⇑t))
    (hsep : ∀ p : P, p ≠ 0 → ∃ r : PD, heisEta1 ⇑t w (normalA p) (normalD r) ≠ 0)
    (hcard : Nat.card P = Nat.card PD) :
    Function.Bijective (stokesH1Map (stokes_square₀ (A := A) ⇑t w hr hend)
      (stokes_square₁ (A := A) ⇑t w hr hend)) := by
  classical
  have hs₀ := stokes_square₀ (A := A) (⇑t) w hr hend
  have hs₁ := stokes_square₁ (A := A) (⇑t) w hr hend
  have h1inj : Function.Injective (stokesH1Map hs₀ hs₁) := by
    rw [injective_iff_map_eq_zero]
    intro H hH
    obtain ⟨x, rfl⟩ := stokesH1Mk_surjective
      (heisD0 (A := A) (⇑t)) (heisD1 (⇑t) w) H
    obtain ⟨p, hp, -⟩ := hnfA x.val (AddMonoidHom.mem_ker.mp x.2)
    by_cases hp0 : p = 0
    · rw [hp0, hnormalA0, sub_zero] at hp
      exact (stokesH1Mk_eq_zero_iff
        (heisD0 (A := A) (⇑t)) (heisD1 (⇑t) w) x).mpr hp
    · obtain ⟨r, hpair⟩ := hsep p hp0
      have hy : heisD1 (A := ElemDual A) (⇑t) w (normalD r) = 0 := hmemD r
      rw [stokesH1Mk, stokesH1Map, QuotientAddGroup.map_mk,
        QuotientAddGroup.eq_zero_iff, AddSubgroup.mem_addSubgroupOf] at hH
      obtain ⟨xi, hxi⟩ := AddMonoidHom.mem_range.mp hH
      have hvan : heisEta1 (⇑t) w x.val (normalD r) = 0 := by
        have heq := DFunLike.congr_fun hxi (normalD r)
        rw [dualMap_apply, hy, map_zero] at heq
        exact heq.symm
      obtain ⟨v, hv⟩ := hp
      have hxrepr : x.val = normalA p + heisD0 (⇑t) v := by rw [hv]; abel
      have hsame : heisEta1 (⇑t) w x.val (normalD r) =
          heisEta1 (⇑t) w (normalA p) (normalD r) := by
        rw [hxrepr, map_add]
        change heisEta1 (⇑t) w (normalA p) (normalD r) +
          heisEta1 (⇑t) w (heisD0 (⇑t) v) (normalD r) =
            heisEta1 (⇑t) w (normalA p) (normalD r)
        rw [heisEta1_comp_d0 (⇑t) w hr hend v (normalD r), hy, map_zero]
        simp
      exact (hpair (hsame ▸ hvan)).elim
  have hcardA : Nat.card (StokesH1 (heisD0 (A := A) (⇑t)) (heisD1 (⇑t) w)) = Nat.card P :=
    card_stokesH1_of_normalForm _ _ normalA hmemA hnfA
  have hcardD : Nat.card
      (StokesH1 (heisD0 (A := ElemDual A) (⇑t))
        (heisD1 (A := ElemDual A) (⇑t) w)) = Nat.card PD :=
    card_stokesH1_of_normalForm _ _ normalD hmemD hnfD
  have htargetCard : Nat.card
      (StokesH1 (dualMap (heisD1 (A := ElemDual A) (⇑t) w))
        (dualMap (heisD0 (A := ElemDual A) (⇑t)))) =
      Nat.card (StokesH1 (heisD0 (A := ElemDual A) (⇑t))
        (heisD1 (A := ElemDual A) (⇑t) w)) := by
    rw [Nat.card_eq_of_bijective _ (wordH1_target_uc (A := A) (⇑t) w hr),
      card_elemDual (stokesH1_two_torsion _ _ wordDual_two_torsion)]
  rw [Nat.bijective_iff_injective_and_card]
  exact ⟨h1inj, hcardA.trans (hcard.trans (hcardD.symm.trans htargetCard.symm))⟩

/-! ## The scalar assembly

With a completely trivial action the two ends of the complex carry cohomology.  Both `η⁰` and
`η²` are then the biduality map `A → A^{∨∨}`, and `η¹` is a normal-form count as before. -/

variable {C A : Type*} [Group C] [AddCommGroup A] [Finite A] [DistribMulAction C A]

omit [Finite A] in
/-- With a trivial action every scalar normal cochain is a cocycle. -/
theorem heisD1_evenScalarNormal_eq_zero_of_tauRow
    (t : Marking (2 + 2 * h) C) (w : Fin 2 → FreeGroup (Generator (2 + 2 * h)))
    (hd1A : ∀ x : Generator (2 + 2 * h) → A, heisD1 ⇑t w x = ![x .tau, x .tau])
    (p : ScalarParam h A) : heisD1 ⇑t w (evenScalarNormalP h p) = 0 := by
  rw [hd1A]
  funext k
  fin_cases k <;> simp [evenScalarNormalP]

omit [Finite A] in
/-- With a trivial action and the `tau`-row, every cocycle *is* its own scalar normal
representative. -/
theorem evenScalarNormalForm_of_tauRow
    (t : Marking (2 + 2 * h) C) (w : Fin 2 → FreeGroup (Generator (2 + 2 * h)))
    (hd0A : ∀ a : A, heisD0 (A := A) ⇑t a = 0)
    (hd1A : ∀ x : Generator (2 + 2 * h) → A, heisD1 ⇑t w x = ![x .tau, x .tau]) :
    ∀ x, heisD1 (A := A) ⇑t w x = 0 →
      ∃! p : ScalarParam h A, x - evenScalarNormalP h p ∈ Set.range (heisD0 ⇑t) := by
  intro x hx
  rw [hd1A] at hx
  have hxτ : x .tau = 0 := by simpa using congrFun hx 0
  have hrange : ∀ u : Generator (2 + 2 * h) → A,
      u ∈ Set.range (heisD0 (A := A) ⇑t) ↔ u = 0 := by
    intro u
    constructor
    · rintro ⟨a, rfl⟩
      exact hd0A a
    · rintro rfl
      exact ⟨0, hd0A 0⟩
  let z := (EvenCore.coreHandleAddEquiv h A x).2
  let p₀ : ScalarParam h A :=
    (x .sigma, x (coreLetter h 0), x (coreLetter h 1), x (coreLetter h 2), z)
  have hnormal : evenScalarNormalP h p₀ = x := by
    apply (EvenCore.coreHandleAddEquiv h A).injective
    apply Prod.ext
    · funext g
      cases g with
      | sigma => simp [p₀, evenScalarNormalP]
      | tau => simpa [p₀, evenScalarNormalP] using hxτ.symm
      | wild i =>
          fin_cases i
          · simp [p₀, evenScalarNormalP]
          · simp [p₀, evenScalarNormalP]
          · simp [p₀, evenScalarNormalP]
    · funext jk
      rcases jk with ⟨j, k⟩
      fin_cases k
      · simp [p₀, z, evenScalarNormalP]
      · simp [p₀, z, evenScalarNormalP]
  refine ⟨p₀, (hrange _).mpr (by rw [hnormal, sub_self]), ?_⟩
  intro p hp
  have hpx : evenScalarNormalP h p = x := by
    have := (hrange _).mp hp
    have h' : x - evenScalarNormalP h p = 0 := this
    rw [sub_eq_zero] at h'
    exact h'.symm
  have hfun : evenScalarNormalP h p = evenScalarNormalP h p₀ := by rw [hpx, hnormal]
  refine Prod.ext ?_ (Prod.ext ?_ (Prod.ext ?_ (Prod.ext ?_ ?_)))
  · simpa [evenScalarNormalP] using congrFun hfun Generator.sigma
  · simpa [evenScalarNormalP] using congrFun hfun (coreLetter h 0)
  · simpa [evenScalarNormalP] using congrFun hfun (coreLetter h 1)
  · simpa [evenScalarNormalP] using congrFun hfun (coreLetter h 2)
  · funext jk
    rcases jk with ⟨j, k⟩
    fin_cases k
    · simpa [evenScalarNormalP] using congrFun hfun (handleU j)
    · simpa [evenScalarNormalP] using congrFun hfun (handleV j)

omit [Finite A] in
/-- The scalar pairing separates every nonzero primal parameter: on top of the `(x₀,x₁)` core it
carries the extra hyperbolic pair `(sigma, x₂)`, which is what replaces the `(1 + S)`-atom when
`S = 1`. -/
theorem evenScalarNormal_pairing_separates_left
    (t : Marking (2 + 2 * h) C) (w : Fin 2 → FreeGroup (Generator (2 + 2 * h)))
    (hA₂ : ∀ a : A, a + a = 0) [Finite A]
    (hpair : ∀ (p : ScalarParam h A) (r : ScalarParam h (ElemDual A)),
      heisEta1 ⇑t w (evenScalarNormalP h p) (evenScalarNormalP h r)
        = r.2.1 (p.2.1 + p.2.2.1) + r.2.2.1 p.2.1 + r.1 p.2.2.2.1 + r.2.2.2.1 p.1
          + ∑ j, (r.2.2.2.2 (j, 0) (p.2.2.2.2 (j, 1))
            + r.2.2.2.2 (j, 1) (p.2.2.2.2 (j, 0))))
    (p : ScalarParam h A) (hp : p ≠ 0) :
    ∃ r : ScalarParam h (ElemDual A),
      heisEta1 ⇑t w (evenScalarNormalP h p) (evenScalarNormalP h r) ≠ 0 := by
  classical
  by_cases hd₀ : p.2.1 = 0
  · by_cases hd₁ : p.2.2.1 = 0
    · by_cases hd₂ : p.2.2.2.1 = 0
      · by_cases hσ : p.1 = 0
        · have hz : p.2.2.2.2 ≠ 0 := by
            intro hz
            exact hp (Prod.ext hσ (Prod.ext hd₀ (Prod.ext hd₁ (Prod.ext hd₂
              (by simpa using hz)))))
          obtain ⟨⟨j, k⟩, hjk⟩ := Function.ne_iff.mp hz
          obtain ⟨lam, hlam⟩ := elemDual_separates hA₂ hjk
          fin_cases k
          · refine ⟨(0, 0, 0, 0, Pi.single (j, 1) lam), ?_⟩
            rw [hpair, hd₀, hd₁, hd₂, hσ]
            have hsum : ∑ b, ((Pi.single (j, 1) lam : Fin h × Fin 2 → ElemDual A) (b, 0)
                  (p.2.2.2.2 (b, 1))
                + (Pi.single (j, 1) lam : Fin h × Fin 2 → ElemDual A) (b, 1)
                  (p.2.2.2.2 (b, 0))) = lam (p.2.2.2.2 (j, 0)) := by
              rw [Finset.sum_eq_single j]
              · simp
              · intro b _ hbj
                simp [hbj]
              · simp
            rw [hsum]
            simpa using hlam
          · refine ⟨(0, 0, 0, 0, Pi.single (j, 0) lam), ?_⟩
            rw [hpair, hd₀, hd₁, hd₂, hσ]
            have hsum : ∑ b, ((Pi.single (j, 0) lam : Fin h × Fin 2 → ElemDual A) (b, 0)
                  (p.2.2.2.2 (b, 1))
                + (Pi.single (j, 0) lam : Fin h × Fin 2 → ElemDual A) (b, 1)
                  (p.2.2.2.2 (b, 0))) = lam (p.2.2.2.2 (j, 1)) := by
              rw [Finset.sum_eq_single j]
              · simp
              · intro b _ hbj
                simp [hbj]
              · simp
            rw [hsum]
            simpa using hlam
        · obtain ⟨lam, hlam⟩ := elemDual_separates hA₂ hσ
          refine ⟨(0, 0, 0, lam, 0), ?_⟩
          rw [hpair, hd₀, hd₁, hd₂]
          simpa using hlam
      · obtain ⟨lam, hlam⟩ := elemDual_separates hA₂ hd₂
        refine ⟨(lam, 0, 0, 0, 0), ?_⟩
        rw [hpair, hd₀, hd₁]
        simpa using hlam
    · obtain ⟨lam, hlam⟩ := elemDual_separates hA₂ hd₁
      refine ⟨(0, lam, 0, 0, 0), ?_⟩
      rw [hpair, hd₀]
      simpa using hlam
  · obtain ⟨lam, hlam⟩ := elemDual_separates hA₂ hd₀
    refine ⟨(0, 0, lam, 0, 0), ?_⟩
    rw [hpair]
    simpa using hlam

/-! ## The two end clauses at a trivial action -/

omit [Finite A] [DistribMulAction C A] in
/-- `η⁰` is injective on every finite elementary module. -/
theorem heisEta0_injective_elem [Finite A] (hA₂ : ∀ a : A, a + a = 0) :
    Function.Injective (heisEta0 : A →+ ElemDual (Fin 2 → ElemDual A)) := by
  rw [injective_iff_map_eq_zero]
  intro a ha
  by_contra hne
  obtain ⟨lam, hlam⟩ := elemDual_separates hA₂ hne
  apply hlam
  have hz := DFunLike.congr_fun ha (![lam, 0] : Fin 2 → ElemDual A)
  rw [heisEta0_apply, Fin.sum_univ_two] at hz
  simpa using hz

set_option maxHeartbeats 3200000 in
/-- **Stokes duality of the even word complex at a completely trivial action**, from the
`tau`-row, the scalar normal form and the scalar pairing formula. -/
theorem evenScalarStokesDuality
    (t : Marking (2 + 2 * h) C) (w : Fin 2 → FreeGroup (Generator (2 + 2 * h)))
    (hA₂ : ∀ a : A, a + a = 0)
    (hr : ∀ k, FreeGroup.lift ⇑t (w k) = 1) (hend : IsStokesEndpoint w)
    (hd0A : ∀ a : A, heisD0 (A := A) ⇑t a = 0)
    (hd0D : ∀ lam : ElemDual A, heisD0 (A := ElemDual A) ⇑t lam = 0)
    (hd1A : ∀ x : Generator (2 + 2 * h) → A, heisD1 ⇑t w x = ![x .tau, x .tau])
    (hd1D : ∀ y : Generator (2 + 2 * h) → ElemDual A, heisD1 ⇑t w y = ![y .tau, y .tau])
    (hpairA : ∀ (p : ScalarParam h A) (r : ScalarParam h (ElemDual A)),
      heisEta1 ⇑t w (evenScalarNormalP h p) (evenScalarNormalP h r)
        = r.2.1 (p.2.1 + p.2.2.1) + r.2.2.1 p.2.1 + r.1 p.2.2.2.1 + r.2.2.2.1 p.1
          + ∑ j, (r.2.2.2.2 (j, 0) (p.2.2.2.2 (j, 1))
            + r.2.2.2.2 (j, 1) (p.2.2.2.2 (j, 0)))) :
    StokesDuality ⇑t w A := by
  classical
  apply (stokesDuality_iff_cohomologyBijections (⇑t) w A hr hend).mpr
  refine ⟨?_, ?_, ?_⟩
  · constructor
    · intro a b hab
      apply Subtype.ext
      have hval : (heisEta0 (A := A) a.val : ElemDual (Fin 2 → ElemDual A))
          = heisEta0 b.val := congrArg Subtype.val hab
      have hsub : (heisEta0 : A →+ ElemDual (Fin 2 → ElemDual A)) (a.val - b.val) = 0 := by
        rw [map_sub, hval, sub_self]
      exact sub_eq_zero.mp ((injective_iff_map_eq_zero _).mp
        (heisEta0_injective_elem (A := A) hA₂) _ hsub)
    · intro y
      have hker : ∀ u : ElemDual A,
          (y.val : ElemDual (Fin 2 → ElemDual A)) (![u, u]) = 0 := by
        intro u
        have hy := DFunLike.congr_fun (AddMonoidHom.mem_ker.mp y.2)
          (Pi.single (Generator.tau : Generator (2 + 2 * h)) u)
        rw [dualMap_apply, hd1D] at hy
        simpa using hy
      let φ : ElemDual A →+ (Fin 2 → ElemDual A) :=
        AddMonoidHom.mk' (fun u ↦ ![u, 0]) (by
          intro u v
          funext k
          fin_cases k <;> simp)
      obtain ⟨a, ha⟩ := (elemDualEval_bijective hA₂).2
        ((y.val : ElemDual (Fin 2 → ElemDual A)).comp φ)
      have hL : ∀ u : ElemDual A,
          (y.val : ElemDual (Fin 2 → ElemDual A)) (![u, 0]) = u a := by
        intro u
        exact (DFunLike.congr_fun ha u).symm
      have hR : ∀ u : ElemDual A,
          (y.val : ElemDual (Fin 2 → ElemDual A)) (![0, u]) = u a := by
        intro u
        have hsum : (![u, u] : Fin 2 → ElemDual A) = ![u, 0] + ![0, u] := by
          funext k
          fin_cases k <;> simp
        have h1 := hker u
        rw [hsum, map_add, hL u] at h1
        exact (eq_neg_of_add_eq_zero_right h1).trans (CharTwo.neg_eq _)
      refine ⟨⟨a, AddMonoidHom.mem_ker.mpr (hd0A a)⟩, ?_⟩
      apply Subtype.ext
      apply ElemDual.ext
      intro ξ
      have hsplit : ξ = ![ξ 0, 0] + ![0, ξ 1] := by
        funext k
        fin_cases k <;> simp
      show heisEta0 a ξ = (y.val : ElemDual (Fin 2 → ElemDual A)) ξ
      rw [heisEta0_apply, Fin.sum_univ_two]
      conv_rhs => rw [hsplit]
      rw [map_add, hL (ξ 0), hR (ξ 1)]
  · exact stokesH1Map_bijective_of_normalForm t w hr hend
      (evenScalarNormalP h) (evenScalarNormalP h) (evenScalarNormalP_zero h)
      (heisD1_evenScalarNormal_eq_zero_of_tauRow t w hd1A)
      (heisD1_evenScalarNormal_eq_zero_of_tauRow (A := ElemDual A) t w hd1D)
      (evenScalarNormalForm_of_tauRow t w hd0A hd1A)
      (evenScalarNormalForm_of_tauRow (A := ElemDual A) t w hd0D hd1D)
      (evenScalarNormal_pairing_separates_left t w hA₂ hpairA)
      (card_scalarParam h hA₂)
  · constructor
    · rw [injective_iff_map_eq_zero]
      intro V hV
      obtain ⟨v, rfl⟩ := QuotientAddGroup.mk_surjective V
      rw [stokesH2Map, QuotientAddGroup.map_mk, QuotientAddGroup.eq_zero_iff,
        AddMonoidHom.mem_range] at hV
      obtain ⟨lam, hlam⟩ := hV
      have hzero : (heisEta2 : (Fin 2 → A) →+ ElemDual (ElemDual A)) v = 0 := by
        rw [← hlam]
        apply ElemDual.ext
        intro mu
        rw [dualMap_apply, hd0D, map_zero]
        rfl
      have hvsum : v 0 + v 1 = 0 := by
        by_contra hne
        obtain ⟨mu, hmu⟩ := elemDual_separates hA₂ hne
        apply hmu
        have := DFunLike.congr_fun hzero mu
        rw [heisEta2_apply, Fin.sum_univ_two] at this
        simpa using this
      have hv : v = ![v 0, v 0] := by
        funext k
        fin_cases k
        · simp
        · have hneg : v 1 = -(v 0) := eq_neg_of_add_eq_zero_right hvsum
          have h20 : -(v 0) = v 0 := neg_eq_of_add_eq_zero_left (hA₂ (v 0))
          simp [hneg, h20]
      refine (QuotientAddGroup.eq_zero_iff _).mpr (AddMonoidHom.mem_range.mpr
        ⟨Pi.single (Generator.tau : Generator (2 + 2 * h)) (v 0), ?_⟩)
      rw [hd1A]
      simpa using hv.symm
    · intro W
      obtain ⟨lam, rfl⟩ := QuotientAddGroup.mk_surjective W
      obtain ⟨a, ha⟩ := (elemDualEval_bijective hA₂).2 lam
      refine ⟨QuotientAddGroup.mk (![a, 0] : Fin 2 → A), ?_⟩
      rw [stokesH2Map, QuotientAddGroup.map_mk]
      congr 1
      apply ElemDual.ext
      intro mu
      rw [heisEta2_apply, Fin.sum_univ_two]
      simp only [Matrix.cons_val_zero, Matrix.cons_val_one, add_zero]
      exact DFunLike.congr_fun ha mu

/-! ## The two scalar branch theorems -/

omit [Finite A] in
/-- Every generator of a marking acts trivially once `sigma`, `tau` and the wild letters do. -/
theorem marking_smul_trivial_of_split
    (t : Marking (2 + 2 * h) C)
    (hwild : ∀ (i : Fin (2 + 2 * h + 1)) (a : A), t.x i • a = a)
    (hτ : ∀ a : A, t.τ • a = a) (hσ : ∀ a : A, t.σ • a = a) :
    ∀ (g : Generator (2 + 2 * h)) (a : A), t g • a = a := by
  intro g a
  cases g with
  | sigma => exact hσ a
  | tau => exact hτ a
  | wild i => exact hwild i a

omit [Finite A] in
/-- With every generator acting trivially the bottom differential vanishes. -/
theorem heisD0_eq_zero_of_split
    (t : Marking (2 + 2 * h) C) (htriv : ∀ (g : Generator (2 + 2 * h)) (a : A), t g • a = a)
    (a : A) : heisD0 (A := A) ⇑t a = 0 := by
  funext i
  show t i • a - a = 0
  rw [htriv i a, sub_self]

/-- **The `tau`-row of the uniform compact-`N` family at a completely trivial action.**  Both
rows of the resolved family degenerate to the mod-2 exponent vector's single `tau` entry. -/
theorem heisD1_nCompactFam_tauRow_of_split [Finite C]
    (t : Marking (2 + 2 * h) C) (hA₂ : ∀ a : A, a + a = 0)
    (hwild : ∀ (i : Fin (2 + 2 * h + 1)) (a : A), t.x i • a = a)
    (hτ : ∀ a : A, t.τ • a = a) (hσ : ∀ a : A, t.σ • a = a)
    (hσinv : ∀ a : A, t.σ⁻¹ • a = a) (hq : Even q) (hα : 1 ≤ α)
    (x : Generator (2 + 2 * h) → A) :
    heisD1 ⇑t (nCompactFam α h q (omega2Exp (4 * Monoid.exponent C))) x
      = ![x .tau, x .tau] := by
  funext k
  fin_cases k
  · change
      (FreeGroup.lift (heisGen (⇑t) x 0)
        (heisToFree
          (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
          (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
          (tameRelW (2 + 2 * h) q))).a = x .tau
    rw [← heisEvalZ_eq_lift,
      heisEvalZ_a_eq_foxD (resolverLifts_uniformWordLift_ramified hA₂),
      Certificates.foxD_tameRelW_unram t _ _ hA₂ hτ hq]
    exact hσinv _
  · change
      (FreeGroup.lift (heisGen (⇑t) x 0)
        (heisToFree
          (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
          (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
          (nCompactW α h))).a = x .tau
    rw [← heisEvalZ_eq_lift,
      heisEvalZ_a_eq_foxD (resolverLifts_uniformWordLift_ramified hA₂),
      Certificates.foxD_nCompact_split t _ _ hA₂ hwild hτ hσ hα]

/-- **The `tau`-row of the uniform compact-`M` family at a completely trivial action.** -/
theorem heisD1_mCompactFam_tauRow_of_split [Finite C]
    (t : Marking (2 + 2 * h) C) (hA₂ : ∀ a : A, a + a = 0)
    (hwild : ∀ (i : Fin (2 + 2 * h + 1)) (a : A), t.x i • a = a)
    (hτ : ∀ a : A, t.τ • a = a) (hσ : ∀ a : A, t.σ • a = a)
    (hσinv : ∀ a : A, t.σ⁻¹ • a = a) (hq : Even q)
    (x : Generator (2 + 2 * h) → A) :
    heisD1 ⇑t (MCompact.mCompactFam α h q (omega2Exp (4 * Monoid.exponent C))) x
      = ![x .tau, x .tau] := by
  funext k
  fin_cases k
  · change
      (FreeGroup.lift (heisGen (⇑t) x 0)
        (heisToFree
          (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
          (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
          (tameRelW (2 + 2 * h) q))).a = x .tau
    rw [← heisEvalZ_eq_lift,
      heisEvalZ_a_eq_foxD (resolverLifts_uniformWordLift_ramified hA₂),
      Certificates.foxD_tameRelW_unram t _ _ hA₂ hτ hq]
    exact hσinv _
  · change
      (FreeGroup.lift (heisGen (⇑t) x 0)
        (heisToFree
          (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
          (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
          (Words.MCompact.mCompactW α h))).a = x .tau
    rw [← heisEvalZ_eq_lift,
      heisEvalZ_a_eq_foxD (resolverLifts_uniformWordLift_ramified hA₂),
      Certificates.MCompact.foxD_mCompact_split t _ _ hA₂ hwild hτ hσ]

set_option maxHeartbeats 3200000 in
/-- **Scalar Stokes duality for the uniform compact-`N` presentation**: the residual unramified
sub-branch, where `sigma` acts trivially as well. -/
theorem nCompactStokesDuality_scalar [Finite C]
    (t : Marking (2 + 2 * h) C) (hA₂ : ∀ a : A, a + a = 0)
    (hq : Even q) (ht : t.TameRelAt q)
    (hwild : ∀ (i : Fin (2 + 2 * h + 1)) (a : A), t.x i • a = a)
    (hτ : ∀ a : A, t.τ • a = a) (hσ : ∀ a : A, t.σ • a = a) (hα : 2 ≤ α)
    (hN : PWord.evalZ ⇑t
      (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
      (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ)) (nCompactW α h) = 1) :
    StokesDuality ⇑t (nCompactFam α h q (omega2Exp (4 * Monoid.exponent C))) A := by
  have hA₂D : ∀ lam : ElemDual A, lam + lam = 0 := fun lam ↦ lam.add_self_eq_zero
  have hwildD : ∀ (i : Fin (2 + 2 * h + 1)) (lam : ElemDual A), t.x i • lam = lam :=
    fun i lam ↦ elemDual_smul_eq_self (hwild i) lam
  have hτD : ∀ lam : ElemDual A, t.τ • lam = lam := fun lam ↦ elemDual_smul_eq_self hτ lam
  have hσD : ∀ lam : ElemDual A, t.σ • lam = lam := fun lam ↦ elemDual_smul_eq_self hσ lam
  have hσinv : ∀ a : A, t.σ⁻¹ • a = a :=
    fun a ↦ mem_trivAct.mp (inv_mem (mem_trivAct.mpr hσ)) a
  have hσinvD : ∀ lam : ElemDual A, t.σ⁻¹ • lam = lam :=
    fun lam ↦ mem_trivAct.mp (inv_mem (mem_trivAct.mpr hσD)) lam
  have hr : ∀ k, FreeGroup.lift (⇑t)
      (nCompactFam α h q (omega2Exp (4 * Monoid.exponent C)) k) = 1 := by
    intro k
    fin_cases k
    · exact (lift_heisToFree_eq_one_iff ⇑t _ _ _).mpr
        (evalZ_tameRelW_eq_one_of_tameRelAt t _ _ ht)
    · exact (lift_heisToFree_eq_one_iff ⇑t _ _ _).mpr hN
  have he : Odd (omega2Exp (4 * Monoid.exponent C)) :=
    odd_omega2Exp (fourMulExponent_ne_zero_and_even C).1
      (fourMulExponent_ne_zero_and_even C).2
  refine evenScalarStokesDuality t _ hA₂ hr
    (Certificates.nCompact_isStokesEndpoint (by omega) hq he)
    (heisD0_eq_zero_of_split t (marking_smul_trivial_of_split t hwild hτ hσ))
    (heisD0_eq_zero_of_split t (marking_smul_trivial_of_split t hwildD hτD hσD))
    (heisD1_nCompactFam_tauRow_of_split t hA₂ hwild hτ hσ hσinv hq (by omega))
    (heisD1_nCompactFam_tauRow_of_split (A := ElemDual A) t hA₂D hwildD hτD hσD hσinvD hq
      (by omega)) ?_
  intro p r
  have htame : (heisEvalZ ⇑t (evenScalarNormalP h p) (evenScalarNormalP h r)
      (fun _ ↦ ((omega2Exp (4 * Monoid.exponent C) : ℕ) : ℤ))
      (fun _ ↦ ((omega2Exp (4 * Monoid.exponent C) : ℕ) : ℤ))
      (tameRelW (2 + 2 * h) q)).z = 0 := by
    rw [Certificates.heisZ_tameRelW_unram t _ _ _ _ hA₂ hτ hq]
    simp [evenScalarNormalP]
  rw [Certificates.heisEta1_nCompactFam_apply t _ _, htame, zero_add,
    Certificates.heisZ_nCompact_scalar t _ _ _ _ hA₂ hwild hτ hσ hα rfl
      (omega2Exp_fourMulExponent_mod_four C)]
  simp only [evenScalarNormalP, evenScalarNormal_coreLetter, evenScalarNormal_sigma,
    evenScalarNormal_handleU, evenScalarNormal_handleV, Matrix.cons_val_zero,
    Matrix.cons_val_one, Matrix.cons_val_two, Matrix.tail_cons, Matrix.head_cons, map_add]
  abel

set_option maxHeartbeats 3200000 in
/-- **Scalar Stokes duality for the uniform compact-`M` presentation**: the residual unramified
sub-branch.  With the whole tame quotient acting trivially the compact-`M` rows are again the
compact-`N` ones. -/
theorem mCompactStokesDuality_scalar [Finite C]
    (t : Marking (2 + 2 * h) C) (hA₂ : ∀ a : A, a + a = 0)
    (hq : Even q) (ht : t.TameRelAt q)
    (hwild : ∀ (i : Fin (2 + 2 * h + 1)) (a : A), t.x i • a = a)
    (hτ : ∀ a : A, t.τ • a = a) (hσ : ∀ a : A, t.σ • a = a) (hα : 2 ≤ α)
    (hM : PWord.evalZ ⇑t
      (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
      (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
      (Words.MCompact.mCompactW α h) = 1) :
    StokesDuality ⇑t
      (MCompact.mCompactFam α h q (omega2Exp (4 * Monoid.exponent C))) A := by
  have hA₂D : ∀ lam : ElemDual A, lam + lam = 0 := fun lam ↦ lam.add_self_eq_zero
  have hwildD : ∀ (i : Fin (2 + 2 * h + 1)) (lam : ElemDual A), t.x i • lam = lam :=
    fun i lam ↦ elemDual_smul_eq_self (hwild i) lam
  have hτD : ∀ lam : ElemDual A, t.τ • lam = lam := fun lam ↦ elemDual_smul_eq_self hτ lam
  have hσD : ∀ lam : ElemDual A, t.σ • lam = lam := fun lam ↦ elemDual_smul_eq_self hσ lam
  have hσinv : ∀ a : A, t.σ⁻¹ • a = a :=
    fun a ↦ mem_trivAct.mp (inv_mem (mem_trivAct.mpr hσ)) a
  have hσinvD : ∀ lam : ElemDual A, t.σ⁻¹ • lam = lam :=
    fun lam ↦ mem_trivAct.mp (inv_mem (mem_trivAct.mpr hσD)) lam
  have hr : ∀ k, FreeGroup.lift (⇑t)
      (MCompact.mCompactFam α h q (omega2Exp (4 * Monoid.exponent C)) k) = 1 := by
    intro k
    fin_cases k
    · exact (lift_heisToFree_eq_one_iff ⇑t _ _ _).mpr
        (evalZ_tameRelW_eq_one_of_tameRelAt t _ _ ht)
    · exact (lift_heisToFree_eq_one_iff ⇑t _ _ _).mpr hM
  have he : Odd (omega2Exp (4 * Monoid.exponent C)) :=
    odd_omega2Exp (fourMulExponent_ne_zero_and_even C).1
      (fourMulExponent_ne_zero_and_even C).2
  refine evenScalarStokesDuality t _ hA₂ hr
    (Certificates.MCompact.mCompact_isStokesEndpoint hq he)
    (heisD0_eq_zero_of_split t (marking_smul_trivial_of_split t hwild hτ hσ))
    (heisD0_eq_zero_of_split t (marking_smul_trivial_of_split t hwildD hτD hσD))
    (heisD1_mCompactFam_tauRow_of_split t hA₂ hwild hτ hσ hσinv hq)
    (heisD1_mCompactFam_tauRow_of_split (A := ElemDual A) t hA₂D hwildD hτD hσD hσinvD hq) ?_
  intro p r
  have hS₂Z : ∀ v : A, (Certificates.MCompact.sigma2Z t (evenScalarNormalP h p)
      (evenScalarNormalP h r)
      (fun _ ↦ ((omega2Exp (4 * Monoid.exponent C) : ℕ) : ℤ))
      (fun _ ↦ ((omega2Exp (4 * Monoid.exponent C) : ℕ) : ℤ))).g • v = v := by
    intro v
    rw [Certificates.MCompact.sigma2Z_g]
    exact mem_trivAct.mp (zpow_mem (mem_trivAct.mpr hσ) _) v
  have htame : (heisEvalZ ⇑t (evenScalarNormalP h p) (evenScalarNormalP h r)
      (fun _ ↦ ((omega2Exp (4 * Monoid.exponent C) : ℕ) : ℤ))
      (fun _ ↦ ((omega2Exp (4 * Monoid.exponent C) : ℕ) : ℤ))
      (tameRelW (2 + 2 * h) q)).z = 0 := by
    rw [Certificates.heisZ_tameRelW_unram t _ _ _ _ hA₂ hτ hq]
    simp [evenScalarNormalP]
  rw [Certificates.MCompact.heisEta1_mCompactFam_apply t _ _, htame, zero_add,
    Certificates.MCompact.heisZ_mCompact_res_one t _ _ _ _ hA₂ hwild hτ hS₂Z hα
      (by simp [evenScalarNormalP]) (by simp [evenScalarNormalP]) rfl
      (omega2Exp_fourMulExponent_mod_four C)]
  have hz : ∀ v : A, v + t.σ • v = 0 := by
    intro v
    rw [hσ v]
    exact hA₂ v
  simp only [evenScalarNormalP, evenScalarNormal_coreLetter, evenScalarNormal_sigma,
    evenScalarNormal_handleU, evenScalarNormal_handleV, Matrix.cons_val_zero,
    Matrix.cons_val_one, Matrix.cons_val_two, Matrix.tail_cons, Matrix.head_cons, hz,
    map_add, map_zero, add_zero]
  abel

end

end GQ2.Dyadic
