/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-5
-/
import GQ2.Dyadic.Instances.N0RamifiedStokes
import GQ2.Dyadic.Instances.N0M0UniformHeisenbergResolver

/-!
# Unramified Stokes duality for the two uniform compact even words

On a simple elementary coefficient on which `tau` acts trivially, both compact even words have
the **same** first Fox row `a(τ) + (1 − S⁻¹)·a(x₂)` (`foxD_nCompact_unram`,
`foxD_mCompact_unram_simple`) and the same second-order row
(`heisZ_nCompact_res_one`, `heisZ_mCompact_res_one`).  So the two rows are treated here in
parallel, through one abstract assembly theorem.

The unramified branch splits once more.  With `tau` and every wild letter acting trivially, the
action image is generated by the image of `sigma` alone, so the `sigma`-fixed subspace is a
submodule: either `sigma` acts trivially (and then the whole action image does, so the
coefficient is the scalar module) or `sigma` has no nonzero fixed vector.  This file settles the
second, *generic* sub-branch, where the complex is acyclic at both ends and the normal
coordinates are the same `A × A × (Fin h × Fin 2 → A)` as in the ramified row.

The residual scalar sub-branch is isolated as `EvenScalarStokes`, a statement about the
completely trivial action which no longer mentions either word.
-/

namespace GQ2.Dyadic

noncomputable section

open GQ2 GQ2.FoxH
open Count Certificates Words Certificates.MProcyclic

variable {h α q : ℕ}

/-! ## An abstract assembly for the even normal coordinates

Both compact even rows, in both ramification classes, reach Stokes duality through the same
five inputs: the complex is acyclic at both ends, the middle cocycles have unique normal
representatives, those representatives are cocycles, and the traced pairing separates the normal
coordinates on the primal side.  Only the *left* separation is needed: the right-hand
nondegeneracy is supplied by the middle cardinality count. -/

set_option maxHeartbeats 3200000 in
/-- **Stokes duality from even normal coordinates.**  An acyclic-ends complex on the even
alphabet whose middle cohomology is freely parametrised by `A × A × (Fin h × Fin 2 → A)`, with a
left-separating traced pairing, satisfies Stokes duality. -/
theorem evenNormalStokesDuality
    {C A : Type*} [Group C] [AddCommGroup A] [Finite A] [DistribMulAction C A]
    (t : Marking (2 + 2 * h) C) (w : Fin 2 → FreeGroup (Generator (2 + 2 * h)))
    (hA₂ : ∀ a : A, a + a = 0)
    (hr : ∀ k, FreeGroup.lift ⇑t (w k) = 1) (hend : IsStokesEndpoint w)
    (hd₀A : Function.Injective (heisD0 (A := A) ⇑t))
    (hd₀D : Function.Injective (heisD0 (A := ElemDual A) ⇑t))
    (hd₁A : Function.Surjective (heisD1 (A := A) ⇑t w))
    (hd₁D : Function.Surjective (heisD1 (A := ElemDual A) ⇑t w))
    (hmemA : ∀ p : A × A × (Fin h × Fin 2 → A),
      heisD1 ⇑t w (evenNormal h p.1 p.2.1 p.2.2) = 0)
    (hmemD : ∀ r : ElemDual A × ElemDual A × (Fin h × Fin 2 → ElemDual A),
      heisD1 ⇑t w (evenNormal h r.1 r.2.1 r.2.2) = 0)
    (hnfA : ∀ x, heisD1 (A := A) ⇑t w x = 0 → ∃! p : A × A × (Fin h × Fin 2 → A),
      x - evenNormal h p.1 p.2.1 p.2.2 ∈ Set.range (heisD0 ⇑t))
    (hnfD : ∀ y, heisD1 (A := ElemDual A) ⇑t w y = 0 →
      ∃! r : ElemDual A × ElemDual A × (Fin h × Fin 2 → ElemDual A),
        y - evenNormal h r.1 r.2.1 r.2.2 ∈ Set.range (heisD0 ⇑t))
    (hsep : ∀ p : A × A × (Fin h × Fin 2 → A), p ≠ 0 →
      ∃ r : ElemDual A × ElemDual A × (Fin h × Fin 2 → ElemDual A),
        heisEta1 ⇑t w (evenNormal h p.1 p.2.1 p.2.2)
          (evenNormal h r.1 r.2.1 r.2.2) ≠ 0) :
    StokesDuality ⇑t w A := by
  classical
  have hs₀ := stokes_square₀ (A := A) (⇑t) w hr hend
  have hs₁ := stokes_square₁ (A := A) (⇑t) w hr hend
  apply (stokesDuality_iff_cohomologyBijections (⇑t) w A hr hend).mpr
  refine ⟨?_, ?_, ?_⟩
  · have htargetInj : Function.Injective
        (dualMap (heisD1 (A := ElemDual A) (⇑t) w)) :=
      dualMap_injective _ hd₁D
    constructor
    · intro a b _
      apply Subtype.ext
      have ha0 : a.val = 0 := hd₀A (by rw [AddMonoidHom.mem_ker.mp a.2, map_zero])
      have hb0 : b.val = 0 := hd₀A (by rw [AddMonoidHom.mem_ker.mp b.2, map_zero])
      rw [ha0, hb0]
    · intro y
      have hy0 : y.val = 0 := htargetInj (by rw [AddMonoidHom.mem_ker.mp y.2, map_zero])
      refine ⟨0, ?_⟩
      apply Subtype.ext
      simp [hy0]
  · have h1inj : Function.Injective (stokesH1Map hs₀ hs₁) := by
      rw [injective_iff_map_eq_zero]
      intro H hH
      obtain ⟨x, rfl⟩ := stokesH1Mk_surjective
        (heisD0 (A := A) (⇑t)) (heisD1 (⇑t) w) H
      obtain ⟨p, hp, -⟩ := hnfA x.val (AddMonoidHom.mem_ker.mp x.2)
      by_cases hp0 : p = 0
      · rw [hp0] at hp
        simp only [Prod.fst_zero, Prod.snd_zero, evenNormal_zero, sub_zero] at hp
        exact (stokesH1Mk_eq_zero_iff
          (heisD0 (A := A) (⇑t)) (heisD1 (⇑t) w) x).mpr hp
      · obtain ⟨r, hpair⟩ := hsep p hp0
        let y := evenNormal h r.1 r.2.1 r.2.2
        have hy : heisD1 (A := ElemDual A) (⇑t) w y = 0 := hmemD r
        rw [stokesH1Mk, stokesH1Map, QuotientAddGroup.map_mk,
          QuotientAddGroup.eq_zero_iff, AddSubgroup.mem_addSubgroupOf] at hH
        obtain ⟨xi, hxi⟩ := AddMonoidHom.mem_range.mp hH
        have hvan : heisEta1 (⇑t) w x.val y = 0 := by
          have heq := DFunLike.congr_fun hxi y
          rw [dualMap_apply, hy, map_zero] at heq
          exact heq.symm
        obtain ⟨v, hv⟩ := hp
        have hxrepr : x.val = evenNormal h p.1 p.2.1 p.2.2 + heisD0 (⇑t) v := by
          rw [hv]; abel
        have hsame : heisEta1 (⇑t) w x.val y =
            heisEta1 (⇑t) w (evenNormal h p.1 p.2.1 p.2.2) y := by
          rw [hxrepr, map_add]
          change heisEta1 (⇑t) w (evenNormal h p.1 p.2.1 p.2.2) y +
            heisEta1 (⇑t) w (heisD0 (⇑t) v) y =
              heisEta1 (⇑t) w (evenNormal h p.1 p.2.1 p.2.2) y
          rw [heisEta1_comp_d0 (⇑t) w hr hend v y, hy, map_zero]
          simp
        exact (hpair (hsame ▸ hvan)).elim
    have hcardA : Nat.card (StokesH1 (heisD0 (A := A) (⇑t)) (heisD1 (⇑t) w)) =
        Nat.card (A × A × (Fin h × Fin 2 → A)) :=
      card_stokesH1_of_normalForm _ _
        (fun p : A × A × (Fin h × Fin 2 → A) ↦ evenNormal h p.1 p.2.1 p.2.2) hmemA hnfA
    have hcardD : Nat.card
        (StokesH1 (heisD0 (A := ElemDual A) (⇑t))
          (heisD1 (A := ElemDual A) (⇑t) w)) =
        Nat.card (ElemDual A × ElemDual A × (Fin h × Fin 2 → ElemDual A)) :=
      card_stokesH1_of_normalForm _ _
        (fun r : ElemDual A × ElemDual A × (Fin h × Fin 2 → ElemDual A) ↦
          evenNormal h r.1 r.2.1 r.2.2) hmemD hnfD
    have hcoordCard : Nat.card (A × A × (Fin h × Fin 2 → A)) =
        Nat.card (ElemDual A × ElemDual A × (Fin h × Fin 2 → ElemDual A)) := by
      rw [Nat.card_prod, Nat.card_prod, Nat.card_prod, Nat.card_prod,
        Nat.card_fun, Nat.card_fun, card_elemDual hA₂]
    have htargetCard : Nat.card
        (StokesH1 (dualMap (heisD1 (A := ElemDual A) (⇑t) w))
          (dualMap (heisD0 (A := ElemDual A) (⇑t)))) =
        Nat.card (StokesH1 (heisD0 (A := ElemDual A) (⇑t))
          (heisD1 (A := ElemDual A) (⇑t) w)) := by
      rw [Nat.card_eq_of_bijective _ (wordH1_target_uc (A := A) (⇑t) w hr),
        card_elemDual (stokesH1_two_torsion _ _ wordDual_two_torsion)]
    rw [Nat.bijective_iff_injective_and_card]
    exact ⟨h1inj, hcardA.trans (hcoordCard.trans (hcardD.symm.trans htargetCard.symm))⟩
  · have htargetSurj : Function.Surjective
        (dualMap (heisD0 (A := ElemDual A) (⇑t))) :=
      dualMap_surjective wordDual_two_torsion _ hd₀D
    have hsourceZero : ∀ z : StokesH2 (heisD1 (A := A) (⇑t) w), z = 0 := by
      intro z
      obtain ⟨a, rfl⟩ := QuotientAddGroup.mk_surjective z
      exact (QuotientAddGroup.eq_zero_iff _).mpr (AddMonoidHom.mem_range.mpr (hd₁A a))
    have htargetZero : ∀ z : StokesH2
        (dualMap (heisD0 (A := ElemDual A) (⇑t))), z = 0 := by
      intro z
      obtain ⟨a, rfl⟩ := QuotientAddGroup.mk_surjective z
      exact (QuotientAddGroup.eq_zero_iff _).mpr
        (AddMonoidHom.mem_range.mpr (htargetSurj a))
    constructor
    · intro a b _
      rw [hsourceZero a, hsourceZero b]
    · intro y
      refine ⟨0, ?_⟩
      rw [map_zero, htargetZero y]

/-! ## The `sigma`-ramified end conditions -/

/-- Fixed-point-free `sigma` makes the bottom differential injective — the unramified twin of
`heisD0_injective_of_tau_fixedPointFree`. -/
theorem heisD0_injective_of_sigma_fixedPointFree
    {n : ℕ} {C A : Type*} [Group C] [AddCommGroup A] [DistribMulAction C A]
    (t : Marking n C) (hσfpf : ∀ a : A, t.σ • a = a → a = 0) :
    Function.Injective (heisD0 (A := A) ⇑t) := by
  rw [injective_iff_map_eq_zero]
  intro a ha
  apply hσfpf a
  have hcoord := congrFun ha Generator.sigma
  change t.σ • a - a = 0 at hcoord
  exact sub_eq_zero.mp hcoord

/-- If `sigma` has no nonzero fixed vector then neither does `sigma⁻¹`. -/
theorem sigmaInv_fixedPointFree
    {n : ℕ} {C A : Type*} [Group C] [AddCommGroup A] [DistribMulAction C A]
    (t : Marking n C) (hσfpf : ∀ a : A, t.σ • a = a → a = 0) :
    ∀ a : A, t.σ⁻¹ • a = a → a = 0 := by
  intro a ha
  have hs : t.σ • (t.σ⁻¹ • a) = t.σ • a := congrArg (fun v : A ↦ t.σ • v) ha
  rw [smul_inv_smul] at hs
  exact hσfpf a hs.symm

/-- The `x₂`-column of the unramified wild row is a pivot on every `sigma`-ramified module. -/
theorem oneSubSigmaInv_surjective_of_fixedPointFree
    {n : ℕ} {C A : Type*} [Group C] [AddCommGroup A] [Finite A] [DistribMulAction C A]
    (t : Marking n C) (hσfpf : ∀ a : A, t.σ • a = a → a = 0) :
    Function.Surjective (fun u : A ↦ u - t.σ⁻¹ • u) := by
  have hs : Function.Surjective (fun u : A ↦ t.σ⁻¹ • u - u) :=
    surjective_smul_sub_of_fixedPointFree (sigmaInv_fixedPointFree t hσfpf)
  intro a
  obtain ⟨u, hu⟩ := hs (-a)
  refine ⟨u, ?_⟩
  change u - t.σ⁻¹ • u = a
  change t.σ⁻¹ • u - u = -a at hu
  rw [← neg_sub, hu, neg_neg]

/-! ## The compact-`N` unramified rows -/

set_option maxHeartbeats 800000 in
/-- The complete first differential of the uniform compact-`N` word on an unramified elementary
module: the tame `sigma⁻¹`-pivot on `tau`, and the wild row `a(τ) + (1 − S⁻¹)a(x₂)`. -/
theorem heisD1_nCompactFam_unramified_apply
    {C A : Type*} [Group C] [Finite C] [AddCommGroup A] [Finite A] [DistribMulAction C A]
    (t : Marking (2 + 2 * h) C) (hA₂ : ∀ a : A, a + a = 0)
    (hwild : ∀ (i : Fin (2 + 2 * h + 1)) (a : A), t.x i • a = a)
    (hτ : ∀ a : A, t.τ • a = a) (hq : Even q) (hα : 1 ≤ α)
    (x : Generator (2 + 2 * h) → A) :
    heisD1 ⇑t (nCompactFam α h q (omega2Exp (4 * Monoid.exponent C))) x
      = ![t.σ⁻¹ • x .tau,
          x .tau + (x (coreLetter h 2) - t.σ⁻¹ • x (coreLetter h 2))] := by
  funext k
  fin_cases k
  · change
      (FreeGroup.lift (heisGen (⇑t) x 0)
        (heisToFree
          (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
          (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
          (tameRelW (2 + 2 * h) q))).a = t.σ⁻¹ • x .tau
    rw [← heisEvalZ_eq_lift,
      heisEvalZ_a_eq_foxD (resolverLifts_uniformWordLift_ramified hA₂),
      Certificates.foxD_tameRelW_unram t _ _ hA₂ hτ hq]
  · change
      (FreeGroup.lift (heisGen (⇑t) x 0)
        (heisToFree
          (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
          (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
          (nCompactW α h))).a =
        x .tau + (x (coreLetter h 2) - t.σ⁻¹ • x (coreLetter h 2))
    rw [← heisEvalZ_eq_lift,
      heisEvalZ_a_eq_foxD (resolverLifts_uniformWordLift_ramified hA₂),
      Certificates.foxD_nCompact_unram t _ _ hA₂ hwild hτ hα]

set_option maxHeartbeats 800000 in
/-- The complete first differential of the uniform compact-`M` word on an unramified **simple**
elementary module.  Literally the compact-`N` row: the `σ₂`-triviality of a simple unramified
module erases every trace of `α` from the compact-`M` Fox row. -/
theorem heisD1_mCompactFam_unramified_apply
    {C A : Type*} [Group C] [Finite C] [AddCommGroup A] [Finite A] [DistribMulAction C A]
    (t : Marking (2 + 2 * h) C) (hA₂ : ∀ a : A, a + a = 0)
    (hwild : ∀ (i : Fin (2 + 2 * h + 1)) (a : A), t.x i • a = a)
    (hτ : ∀ a : A, t.τ • a = a) (hS₂ : ∀ a : A, powOmega2 t.σ • a = a) (hq : Even q)
    (x : Generator (2 + 2 * h) → A) :
    heisD1 ⇑t (MCompact.mCompactFam α h q (omega2Exp (4 * Monoid.exponent C))) x
      = ![t.σ⁻¹ • x .tau,
          x .tau + (x (coreLetter h 2) - t.σ⁻¹ • x (coreLetter h 2))] := by
  funext k
  fin_cases k
  · change
      (FreeGroup.lift (heisGen (⇑t) x 0)
        (heisToFree
          (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
          (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
          (tameRelW (2 + 2 * h) q))).a = t.σ⁻¹ • x .tau
    rw [← heisEvalZ_eq_lift,
      heisEvalZ_a_eq_foxD (resolverLifts_uniformWordLift_ramified hA₂),
      Certificates.foxD_tameRelW_unram t _ _ hA₂ hτ hq]
  · change
      (FreeGroup.lift (heisGen (⇑t) x 0)
        (heisToFree
          (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
          (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
          (Words.MCompact.mCompactW α h))).a =
        x .tau + (x (coreLetter h 2) - t.σ⁻¹ • x (coreLetter h 2))
    rw [← heisEvalZ_eq_lift,
      heisEvalZ_a_eq_foxD (resolverLifts_uniformWordLift_ramified hA₂),
      Certificates.MCompact.foxD_mCompact_unram_simple t _ _ hA₂ hwild hτ hS₂]

/-! ## The unramified normal form, `sigma`-ramified sub-branch

The two rows enter only through the shared shape `![S⁻¹a(τ), a(τ) + (1 − S⁻¹)a(x₂)]`, so the
following three lemmas are stated once, for an arbitrary resolved family with that row. -/

variable {C A : Type*} [Group C] [AddCommGroup A] [Finite A] [DistribMulAction C A]

/-- Surjectivity of a differential with the shared unramified row, on a `sigma`-ramified
module. -/
theorem heisD1_surjective_of_unramified_row
    (t : Marking (2 + 2 * h) C) (w : Fin 2 → FreeGroup (Generator (2 + 2 * h)))
    (hrow : ∀ x : Generator (2 + 2 * h) → A, heisD1 ⇑t w x
      = ![t.σ⁻¹ • x .tau, x .tau + (x (coreLetter h 2) - t.σ⁻¹ • x (coreLetter h 2))])
    (hσfpf : ∀ a : A, t.σ • a = a → a = 0) :
    Function.Surjective (heisD1 (A := A) ⇑t w) := by
  classical
  intro r
  obtain ⟨u, hu⟩ := oneSubSigmaInv_surjective_of_fixedPointFree t hσfpf
    (r 1 - t.σ • r 0)
  let x : Generator (2 + 2 * h) → A := fun g ↦
    if g = .tau then t.σ • r 0 else if g = coreLetter h 2 then u else 0
  have hτx2 : (.tau : Generator (2 + 2 * h)) ≠ coreLetter h 2 :=
    Certificates.tau_ne_coreLetter_two h
  have hxτ : x .tau = t.σ • r 0 := by simp [x]
  have hxx2 : x (coreLetter h 2) = u := by simp [x, hτx2.symm]
  refine ⟨x, ?_⟩
  rw [hrow x]
  funext k
  fin_cases k
  · change t.σ⁻¹ • x .tau = r 0
    rw [hxτ, inv_smul_smul]
  · change x .tau + (x (coreLetter h 2) - t.σ⁻¹ • x (coreLetter h 2)) = r 1
    rw [hxτ, hxx2]
    change u - t.σ⁻¹ • u = r 1 - t.σ • r 0 at hu
    rw [hu]
    abel

omit [Finite A] in
/-- Every normal cochain is a cocycle for the shared unramified row. -/
theorem heisD1_evenNormal_eq_zero_of_unramified_row
    (t : Marking (2 + 2 * h) C) (w : Fin 2 → FreeGroup (Generator (2 + 2 * h)))
    (hrow : ∀ x : Generator (2 + 2 * h) → A, heisD1 ⇑t w x
      = ![t.σ⁻¹ • x .tau, x .tau + (x (coreLetter h 2) - t.σ⁻¹ • x (coreLetter h 2))])
    (d₀ d₁ : A) (z : Fin h × Fin 2 → A) :
    heisD1 ⇑t w (evenNormal h d₀ d₁ z) = 0 := by
  rw [hrow]
  funext k
  fin_cases k <;> simp

set_option maxHeartbeats 1600000 in
/-- The unramified normal form on a `sigma`-ramified module: the tame row kills `tau`, the wild
pivot kills `x₂`, and a coboundary kills `sigma`. -/
theorem evenNormalForm_of_unramified_row
    (t : Marking (2 + 2 * h) C) (w : Fin 2 → FreeGroup (Generator (2 + 2 * h)))
    (hrow : ∀ x : Generator (2 + 2 * h) → A, heisD1 ⇑t w x
      = ![t.σ⁻¹ • x .tau, x .tau + (x (coreLetter h 2) - t.σ⁻¹ • x (coreLetter h 2))])
    (hwild : ∀ (i : Fin (2 + 2 * h + 1)) (a : A), t.x i • a = a)
    (hτ : ∀ a : A, t.τ • a = a)
    (hσfpf : ∀ a : A, t.σ • a = a → a = 0)
    (_hr : ∀ k, FreeGroup.lift ⇑t (w k) = 1) :
    ∀ x, heisD1 (A := A) ⇑t w x = 0 → ∃! p : A × A × (Fin h × Fin 2 → A),
      x - evenNormal h p.1 p.2.1 p.2.2 ∈ Set.range (heisD0 ⇑t) := by
  have hSsurj : Function.Surjective (fun v : A ↦ t.σ • v - v) :=
    surjective_smul_sub_of_fixedPointFree hσfpf
  have hcoreTriv : ∀ (i : Fin 3) (a : A), t (coreLetter h i) • a = a := fun i a ↦ hwild _ a
  have hhandleUTriv : ∀ (j : Fin h) (a : A), t (handleU j) • a = a := fun j a ↦ hwild _ a
  have hhandleVTriv : ∀ (j : Fin h) (a : A), t (handleV j) • a = a := fun j a ↦ hwild _ a
  intro x hx
  rw [hrow x] at hx
  have hxτ : x .tau = 0 := by
    have hz : t.σ⁻¹ • x .tau = 0 := by simpa using congrFun hx 0
    rw [← smul_inv_smul t.σ (x .tau), hz, smul_zero]
  have hxcore2 : x (coreLetter h 2) = 0 := by
    have hz : x .tau + (x (coreLetter h 2) - t.σ⁻¹ • x (coreLetter h 2)) = 0 := by
      simpa using congrFun hx 1
    rw [hxτ, zero_add, sub_eq_zero] at hz
    exact sigmaInv_fixedPointFree t hσfpf _ hz.symm
  obtain ⟨v, hv⟩ := hSsurj (x .sigma)
  let x' := x - heisD0 (⇑t) v
  have hx'σ : x' .sigma = 0 := by
    simp [x', heisD0_apply, hv]
  have hx'τ : x' .tau = 0 := by
    simp [x', heisD0_apply, hτ, hxτ]
  have hx'core2 : x' (coreLetter h 2) = 0 := by
    simp [x', heisD0_apply, hcoreTriv, hxcore2]
  let z := (EvenCore.coreHandleAddEquiv h A x).2
  let p₀ : A × A × (Fin h × Fin 2 → A) := (x (coreLetter h 0), x (coreLetter h 1), z)
  have hnormal : evenNormal h p₀.1 p₀.2.1 p₀.2.2 = x' := by
    apply (EvenCore.coreHandleAddEquiv h A).injective
    apply Prod.ext
    · funext g
      cases g with
      | sigma => simpa [p₀] using hx'σ.symm
      | tau => simpa [p₀] using hx'τ.symm
      | wild i =>
          fin_cases i
          · simp [p₀, x', heisD0_apply, hcoreTriv]
          · simp [p₀, x', heisD0_apply, hcoreTriv]
          · simpa [p₀] using hx'core2.symm
    · funext jk
      rcases jk with ⟨j, k⟩
      fin_cases k
      · simp [p₀, z, x', heisD0_apply, hhandleUTriv]
      · simp [p₀, z, x', heisD0_apply, hhandleVTriv]
  refine ⟨p₀, ?_, ?_⟩
  · refine ⟨v, ?_⟩
    rw [hnormal]
    simp [x']
  · intro p hp
    obtain ⟨u, hu⟩ := hp
    apply Prod.ext
    · have hc := congrFun hu (coreLetter h 0)
      rw [heisD0_apply, hcoreTriv, sub_self] at hc
      simp only [Pi.sub_apply, evenNormal_coreLetter, Matrix.cons_val_zero] at hc
      exact (sub_eq_zero.mp hc.symm).symm
    · apply Prod.ext
      · have hc := congrFun hu (coreLetter h 1)
        rw [heisD0_apply, hcoreTriv, sub_self] at hc
        simp only [Pi.sub_apply, evenNormal_coreLetter, Matrix.cons_val_one,
          Matrix.cons_val_zero] at hc
        exact (sub_eq_zero.mp hc.symm).symm
      · funext jk
        rcases jk with ⟨j, k⟩
        fin_cases k
        · have hc := congrFun hu (handleU j)
          rw [heisD0_apply, hhandleUTriv, sub_self] at hc
          simp only [Pi.sub_apply, evenNormal_handleU] at hc
          have hpj := (sub_eq_zero.mp hc.symm).symm
          simpa [p₀, z] using hpj
        · have hc := congrFun hu (handleV j)
          rw [heisD0_apply, hhandleVTriv, sub_self] at hc
          simp only [Pi.sub_apply, evenNormal_handleV] at hc
          have hpj := (sub_eq_zero.mp hc.symm).symm
          simpa [p₀, z] using hpj

omit [Finite A] in
/-- The normal-coordinate pairing separates every nonzero primal coordinate, from the core
formula alone. -/
theorem evenNormal_pairing_separates_left_of_formula
    (t : Marking (2 + 2 * h) C) (w : Fin 2 → FreeGroup (Generator (2 + 2 * h)))
    (hA₂ : ∀ a : A, a + a = 0)
    (hpair : ∀ (d₀ d₁ : A) (z : Fin h × Fin 2 → A) (lam₀ lam₁ : ElemDual A)
      (mu : Fin h × Fin 2 → ElemDual A),
      heisEta1 ⇑t w (evenNormal h d₀ d₁ z) (evenNormal h lam₀ lam₁ mu)
        = lam₀ (d₀ + d₁) + lam₁ d₀ + ∑ j, (mu (j, 0) (z (j, 1)) + mu (j, 1) (z (j, 0))))
    (p : A × A × (Fin h × Fin 2 → A)) (hp : p ≠ 0) :
    ∃ r : ElemDual A × ElemDual A × (Fin h × Fin 2 → ElemDual A),
      heisEta1 ⇑t w (evenNormal h p.1 p.2.1 p.2.2)
        (evenNormal h r.1 r.2.1 r.2.2) ≠ 0 := by
  classical
  by_cases hd₀ : p.1 = 0
  · by_cases hd₁ : p.2.1 = 0
    · have hz : p.2.2 ≠ 0 := by
        intro hz
        exact hp (Prod.ext hd₀ (Prod.ext hd₁ (by simpa using hz)))
      obtain ⟨⟨j, k⟩, hjk⟩ := Function.ne_iff.mp hz
      obtain ⟨lam, hlam⟩ := elemDual_separates hA₂ hjk
      fin_cases k
      · refine ⟨(0, 0, Pi.single (j, 1) lam), ?_⟩
        rw [hpair, hd₀, hd₁]
        have hsum : ∑ b, ((Pi.single (j, 1) lam : Fin h × Fin 2 → ElemDual A) (b, 0)
              (p.2.2 (b, 1))
            + (Pi.single (j, 1) lam : Fin h × Fin 2 → ElemDual A) (b, 1) (p.2.2 (b, 0)))
            = lam (p.2.2 (j, 0)) := by
          rw [Finset.sum_eq_single j]
          · simp
          · intro b _ hbj
            simp [hbj]
          · simp
        rw [hsum]
        simpa using hlam
      · refine ⟨(0, 0, Pi.single (j, 0) lam), ?_⟩
        rw [hpair, hd₀, hd₁]
        have hsum : ∑ b, ((Pi.single (j, 0) lam : Fin h × Fin 2 → ElemDual A) (b, 0)
              (p.2.2 (b, 1))
            + (Pi.single (j, 0) lam : Fin h × Fin 2 → ElemDual A) (b, 1) (p.2.2 (b, 0)))
            = lam (p.2.2 (j, 1)) := by
          rw [Finset.sum_eq_single j]
          · simp
          · intro b _ hbj
            simp [hbj]
          · simp
        rw [hsum]
        simpa using hlam
    · obtain ⟨lam, hlam⟩ := elemDual_separates hA₂ hd₁
      refine ⟨(lam, 0, 0), ?_⟩
      rw [hpair, hd₀]
      simpa using hlam
  · obtain ⟨lam, hlam⟩ := elemDual_separates hA₂ hd₀
    refine ⟨(0, lam, 0), ?_⟩
    rw [hpair]
    simpa using hlam

set_option maxHeartbeats 3200000 in
/-- **Stokes duality for a shared-row even complex on a `sigma`-ramified unramified module.**
The word enters only through its first Fox row and the core pairing formula. -/
theorem evenUnramifiedStokesDuality_of_row
    (t : Marking (2 + 2 * h) C) (w : Fin 2 → FreeGroup (Generator (2 + 2 * h)))
    (hA₂ : ∀ a : A, a + a = 0)
    (hr : ∀ k, FreeGroup.lift ⇑t (w k) = 1) (hend : IsStokesEndpoint w)
    (hrowA : ∀ x : Generator (2 + 2 * h) → A, heisD1 ⇑t w x
      = ![t.σ⁻¹ • x .tau, x .tau + (x (coreLetter h 2) - t.σ⁻¹ • x (coreLetter h 2))])
    (hrowD : ∀ y : Generator (2 + 2 * h) → ElemDual A, heisD1 ⇑t w y
      = ![t.σ⁻¹ • y .tau, y .tau + (y (coreLetter h 2) - t.σ⁻¹ • y (coreLetter h 2))])
    (hpairA : ∀ (d₀ d₁ : A) (z : Fin h × Fin 2 → A) (lam₀ lam₁ : ElemDual A)
      (mu : Fin h × Fin 2 → ElemDual A),
      heisEta1 ⇑t w (evenNormal h d₀ d₁ z) (evenNormal h lam₀ lam₁ mu)
        = lam₀ (d₀ + d₁) + lam₁ d₀ + ∑ j, (mu (j, 0) (z (j, 1)) + mu (j, 1) (z (j, 0))))
    (hwild : ∀ (i : Fin (2 + 2 * h + 1)) (a : A), t.x i • a = a)
    (hτ : ∀ a : A, t.τ • a = a)
    (hσfpf : ∀ a : A, t.σ • a = a → a = 0) :
    StokesDuality ⇑t w A := by
  have hA₂D : ∀ lam : ElemDual A, lam + lam = 0 := fun lam ↦ lam.add_self_eq_zero
  have hwildD : ∀ (i : Fin (2 + 2 * h + 1)) (lam : ElemDual A), t.x i • lam = lam :=
    fun i lam ↦ elemDual_smul_eq_self (hwild i) lam
  have hτD : ∀ lam : ElemDual A, t.τ • lam = lam := fun lam ↦ elemDual_smul_eq_self hτ lam
  have hσfpfD : ∀ lam : ElemDual A, t.σ • lam = lam → lam = 0 :=
    fun lam hlam ↦ elemDual_fpf hσfpf lam hlam
  exact evenNormalStokesDuality t w hA₂ hr hend
    (heisD0_injective_of_sigma_fixedPointFree t hσfpf)
    (heisD0_injective_of_sigma_fixedPointFree (A := ElemDual A) t hσfpfD)
    (heisD1_surjective_of_unramified_row t w hrowA hσfpf)
    (heisD1_surjective_of_unramified_row (A := ElemDual A) t w hrowD hσfpfD)
    (fun p ↦ heisD1_evenNormal_eq_zero_of_unramified_row t w hrowA p.1 p.2.1 p.2.2)
    (fun r ↦ heisD1_evenNormal_eq_zero_of_unramified_row (A := ElemDual A) t w hrowD
      r.1 r.2.1 r.2.2)
    (evenNormalForm_of_unramified_row t w hrowA hwild hτ hσfpf hr)
    (evenNormalForm_of_unramified_row (A := ElemDual A) t w hrowD hwildD hτD hσfpfD hr)
    (evenNormal_pairing_separates_left_of_formula t w hA₂ hpairA)

/-! ## The compact-`M` middle pairing on normal coordinates -/

set_option maxHeartbeats 1600000 in
/-- On normal coordinates the compact-`M` middle Stokes map is the same constant unimodular core
matrix `((1,1),(1,0))` plus `h` standard hyperbolic planes as the compact-`N` one.  The `e % 4 = 1`
side condition of the compact-`M` second-order row is discharged at the uniform resolver by
`omega2Exp_fourMulExponent_mod_four`. -/
theorem heisEta1_mCompactFam_normal
    {C A : Type*} [Group C] [Finite C] [AddCommGroup A] [DistribMulAction C A]
    (t : Marking (2 + 2 * h) C) (hA₂ : ∀ a : A, a + a = 0)
    (hwild : ∀ (i : Fin (2 + 2 * h + 1)) (a : A), t.x i • a = a)
    (hτ : ∀ a : A, t.τ • a = a) (hS₂ : ∀ a : A, powOmega2 t.σ • a = a) (hα : 2 ≤ α)
    (d₀ d₁ : A) (z : Fin h × Fin 2 → A)
    (lam₀ lam₁ : ElemDual A) (mu : Fin h × Fin 2 → ElemDual A) :
    heisEta1 ⇑t (MCompact.mCompactFam α h q (omega2Exp (4 * Monoid.exponent C)))
        (evenNormal h d₀ d₁ z) (evenNormal h lam₀ lam₁ mu)
      = lam₀ (d₀ + d₁) + lam₁ d₀
        + ∑ j, (mu (j, 0) (z (j, 1)) + mu (j, 1) (z (j, 0))) := by
  have hpow : (t.σ ^ (((omega2Exp (4 * Monoid.exponent C) : ℕ)) : ℤ)) = powOmega2 t.σ := by
    rw [zpow_natCast]
    exact powOmega2_pow_eq t.σ
      ((Monoid.order_dvd_exponent t.σ).trans (dvd_mul_left (Monoid.exponent C) 4))
      (fourMulExponent_ne_zero_and_even C).1
  have hS₂Z : ∀ v : A, (Certificates.MCompact.sigma2Z t (evenNormal h d₀ d₁ z)
      (evenNormal h lam₀ lam₁ mu)
      (fun _ ↦ ((omega2Exp (4 * Monoid.exponent C) : ℕ) : ℤ))
      (fun _ ↦ ((omega2Exp (4 * Monoid.exponent C) : ℕ) : ℤ))).g • v = v := by
    intro v
    rw [Certificates.MCompact.sigma2Z_g, hpow]
    exact hS₂ v
  have htame : (heisEvalZ ⇑t (evenNormal h d₀ d₁ z) (evenNormal h lam₀ lam₁ mu)
      (fun _ ↦ ((omega2Exp (4 * Monoid.exponent C) : ℕ) : ℤ))
      (fun _ ↦ ((omega2Exp (4 * Monoid.exponent C) : ℕ) : ℤ))
      (tameRelW (2 + 2 * h) q)).z = 0 := by
    apply heisZ_tameRelW_eq_zero_of_tame_offsets_zero <;> simp
  rw [Certificates.MCompact.heisEta1_mCompactFam_apply t _ _, htame, zero_add,
    Certificates.MCompact.heisZ_mCompact_res_one t _ _ _ _ hA₂ hwild hτ hS₂Z hα
      (by simp) (by simp) rfl (omega2Exp_fourMulExponent_mod_four C)]
  simp only [evenNormal_coreLetter, evenNormal_sigma,
    evenNormal_handleU, evenNormal_handleV, Matrix.cons_val_zero, Matrix.cons_val_one,
    Matrix.cons_val_two, Matrix.tail_cons, Matrix.head_cons, map_add, map_zero, smul_zero,
    add_zero]
  abel

/-! ## The two unramified branch theorems, `sigma`-ramified sub-branch -/

set_option maxHeartbeats 3200000 in
/-- **Unramified Stokes duality for the uniform compact-`N` presentation**, on a coefficient on
which `sigma` has no nonzero fixed vector. -/
theorem nCompactStokesDuality_unramified
    {C A : Type*} [Group C] [Finite C] [AddCommGroup A] [Finite A] [DistribMulAction C A]
    (t : Marking (2 + 2 * h) C) (hA₂ : ∀ a : A, a + a = 0)
    (hq : Even q) (ht : t.TameRelAt q)
    (hwild : ∀ (i : Fin (2 + 2 * h + 1)) (a : A), t.x i • a = a)
    (hτ : ∀ a : A, t.τ • a = a)
    (hσfpf : ∀ a : A, t.σ • a = a → a = 0) (hα : 2 ≤ α)
    (hN : PWord.evalZ ⇑t
      (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
      (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ)) (nCompactW α h) = 1) :
    StokesDuality ⇑t (nCompactFam α h q (omega2Exp (4 * Monoid.exponent C))) A := by
  have hA₂D : ∀ lam : ElemDual A, lam + lam = 0 := fun lam ↦ lam.add_self_eq_zero
  have hwildD : ∀ (i : Fin (2 + 2 * h + 1)) (lam : ElemDual A), t.x i • lam = lam :=
    fun i lam ↦ elemDual_smul_eq_self (hwild i) lam
  have hτD : ∀ lam : ElemDual A, t.τ • lam = lam := fun lam ↦ elemDual_smul_eq_self hτ lam
  have hr : ∀ k, FreeGroup.lift (⇑t)
      (nCompactFam α h q (omega2Exp (4 * Monoid.exponent C)) k) = 1 := by
    intro k
    fin_cases k
    · exact (lift_heisToFree_eq_one_iff ⇑t _ _ _).mpr
        (evalZ_tameRelW_eq_one_of_tameRelAt t _ _ ht)
    · exact (lift_heisToFree_eq_one_iff ⇑t _ _ _).mpr hN
  have he : Odd (omega2Exp (4 * Monoid.exponent C)) :=
    odd_omega2Exp (fourMulExponent_ne_zero_and_even C).1
      (fourMulExponent_ne_zero_and_even C).2
  exact evenUnramifiedStokesDuality_of_row t _ hA₂ hr
    (Certificates.nCompact_isStokesEndpoint (by omega) hq he)
    (heisD1_nCompactFam_unramified_apply t hA₂ hwild hτ hq (by omega))
    (heisD1_nCompactFam_unramified_apply (A := ElemDual A) t hA₂D hwildD hτD hq (by omega))
    (fun d₀ d₁ z lam₀ lam₁ mu ↦ heisEta1_nCompactFam_normal (q := q)
      (e := omega2Exp (4 * Monoid.exponent C)) t hA₂ hwild hα d₀ d₁ z lam₀ lam₁ mu)
    hwild hτ hσfpf

set_option maxHeartbeats 3200000 in
/-- **Unramified Stokes duality for the uniform compact-`M` presentation**, on a coefficient on
which `sigma` has no nonzero fixed vector.  The `σ₂`-triviality hypothesis is what a simple
unramified module supplies, and it is what erases every trace of `α` from the compact-`M`
rows. -/
theorem mCompactStokesDuality_unramified
    {C A : Type*} [Group C] [Finite C] [AddCommGroup A] [Finite A] [DistribMulAction C A]
    (t : Marking (2 + 2 * h) C) (hA₂ : ∀ a : A, a + a = 0)
    (hq : Even q) (ht : t.TameRelAt q)
    (hwild : ∀ (i : Fin (2 + 2 * h + 1)) (a : A), t.x i • a = a)
    (hτ : ∀ a : A, t.τ • a = a) (hS₂ : ∀ a : A, powOmega2 t.σ • a = a)
    (hσfpf : ∀ a : A, t.σ • a = a → a = 0) (hα : 2 ≤ α)
    (hM : PWord.evalZ ⇑t
      (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
      (fun _ ↦ (omega2Exp (4 * Monoid.exponent C) : ℤ))
      (Words.MCompact.mCompactW α h) = 1) :
    StokesDuality ⇑t
      (MCompact.mCompactFam α h q (omega2Exp (4 * Monoid.exponent C))) A := by
  have hA₂D : ∀ lam : ElemDual A, lam + lam = 0 := fun lam ↦ lam.add_self_eq_zero
  have hwildD : ∀ (i : Fin (2 + 2 * h + 1)) (lam : ElemDual A), t.x i • lam = lam :=
    fun i lam ↦ elemDual_smul_eq_self (hwild i) lam
  have hτD : ∀ lam : ElemDual A, t.τ • lam = lam := fun lam ↦ elemDual_smul_eq_self hτ lam
  have hS₂D : ∀ lam : ElemDual A, powOmega2 t.σ • lam = lam :=
    fun lam ↦ elemDual_smul_eq_self hS₂ lam
  have hr : ∀ k, FreeGroup.lift (⇑t)
      (MCompact.mCompactFam α h q (omega2Exp (4 * Monoid.exponent C)) k) = 1 := by
    intro k
    fin_cases k
    · exact (lift_heisToFree_eq_one_iff ⇑t _ _ _).mpr
        (evalZ_tameRelW_eq_one_of_tameRelAt t _ _ ht)
    · exact (lift_heisToFree_eq_one_iff ⇑t _ _ _).mpr hM
  have he : Odd (omega2Exp (4 * Monoid.exponent C)) :=
    odd_omega2Exp (fourMulExponent_ne_zero_and_even C).1
      (fourMulExponent_ne_zero_and_even C).2
  exact evenUnramifiedStokesDuality_of_row t _ hA₂ hr
    (Certificates.MCompact.mCompact_isStokesEndpoint hq he)
    (heisD1_mCompactFam_unramified_apply t hA₂ hwild hτ hS₂ hq)
    (heisD1_mCompactFam_unramified_apply (A := ElemDual A) t hA₂D hwildD hτD hS₂D hq)
    (heisEta1_mCompactFam_normal t hA₂ hwild hτ hS₂ hα) hwild hτ hσfpf

end

end GQ2.Dyadic
