/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-5
-/
import GQ2.Dyadic.Instances.EvenPhiNormalStokes
import GQ2.Dyadic.Instances.NpcRamifiedBranch

/-!
# The procyclic target of the unramified branch

On the unramified branch of a fixed-word action-image devissage `tau` and every wild letter act
trivially, so the action image is generated by `sigma` alone
(`RowActionImage.actionImage_unramified_closure_sigma`).  This file extracts the three
arithmetic facts that branch then supplies, none of which is word-specific.

* **`sigma` has odd order.**  Its `2`-part generates a `2`-group whose fixed space is stable
  (the image is procyclic, hence abelian), so `pow2_smul_trivial_of_stable` makes the `2`-part
  act trivially, and faithfulness of the action image makes it *equal* to `1`.
* **The `η̂`-conjugator `A = σ^{η̂}` is `σ` itself.**  `η̂` has odd components `1`
  (`zpowHat_etaHatZ_of_odd`), so on a procyclic target of odd order the profinite `η̂`-power is
  the identity operation — and the resolver value is that same power
  (`zpowHat_etaHatZ_zpow`).  This is what makes the unramified `x₀`-block `A⁻¹ + 1` invertible
  on the generic sub-branch, and it is the fact the recorded devissage argument leaves implicit.
* **The boundary conjugator `B = σ^{2^r}` is fixed-point free** whenever `sigma` is: `2^r` is
  invertible modulo the (odd) order of `sigma`, so `sigma` is itself a power of `B`.

Together they say: on the unramified branch the wild row of *any* `η̂`-conjugated word is read
with `A = σ`, and both its blocks `1 − A⁻¹` and `1 − B⁻¹` are invertible as soon as `sigma`
itself is fixed-point free.
-/

namespace GQ2.Dyadic.RowActionImage

noncomputable section

open GQ2 GQ2.FoxH
open GQ2.Dyadic.Count GQ2.Dyadic.Certificates

attribute [local instance] GQ2.Dyadic.Count.heisTopologicalSpace
  GQ2.Dyadic.Count.heisDiscreteTopology

variable {n q : ℕ} {R : PWord (Generator n)} {M : Type}
  [AddCommGroup M] [TopologicalSpace M] [DiscreteTopology M]
  [DistribMulAction ((GammaR n q R : Type)) M]
  [ContinuousSMul ((GammaR n q R : Type)) M] [Finite M]

/-- On the unramified branch every element of the action image is a `ℤ`-power of `sigma`. -/
theorem actionImage_unramified_mem_zpowers
    (hM₂ : ∀ m : M, m + m = 0) (hsimple : IsSimpleModTwo (GammaR n q R : Type) M)
    (hτ : ∀ m : M, gammaGen n q R .tau • m = m) (c : ActionImage n q R M) :
    c ∈ Subgroup.zpowers (actionImageMarking n q R M).σ := by
  rw [Subgroup.zpowers_eq_closure, actionImage_unramified_closure_sigma hM₂ hsimple hτ]
  trivial

/-- Every power of `sigma` stabilises the fixed space of every other power: the action image is
procyclic, hence abelian. -/
theorem actionImage_unramified_stable
    (hM₂ : ∀ m : M, m + m = 0) (hsimple : IsSimpleModTwo (GammaR n q R : Type) M)
    (hτ : ∀ m : M, gammaGen n q R .tau • m = m) (k : ℕ)
    (c : ActionImage n q R M) (v : M)
    (hv : ((actionImageMarking n q R M).σ ^ k) • v = v) :
    ((actionImageMarking n q R M).σ ^ k) • (c • v) = c • v := by
  obtain ⟨j, rfl⟩ := actionImage_unramified_mem_zpowers hM₂ hsimple hτ c
  have hc : Commute ((actionImageMarking n q R M).σ ^ (j : ℤ))
      ((actionImageMarking n q R M).σ ^ k) :=
    ((Commute.refl _).zpow_left j).pow_right k
  rw [smul_smul, ← hc.eq, ← smul_smul, hv]

set_option maxHeartbeats 800000 in
/-- **On the unramified branch `sigma` has odd order in the action image.**  Its `2`-part acts
trivially by the stable fixed-point lemma, and the action image is faithful. -/
theorem actionImage_unramified_orderOf_sigma_odd
    (hM₂ : ∀ m : M, m + m = 0) (hsimple : IsSimpleModTwo (GammaR n q R : Type) M)
    (hτ : ∀ m : M, gammaGen n q R .tau • m = m) :
    Odd (orderOf (actionImageMarking n q R M).σ) := by
  set t := actionImageMarking n q R M with ht
  have hnn0 : orderOf t.σ ≠ 0 := by
    rw [ne_eq, orderOf_eq_zero_iff, not_not]
    exact isOfFinOrder_of_finite t.σ
  obtain ⟨a, mm, hmodd, hprod⟩ := Nat.exists_eq_two_pow_mul_odd hnn0
  have hmdvd : mm ∣ orderOf t.σ := ⟨2 ^ a, by rw [hprod]; ring⟩
  have hm0 : mm ≠ 0 := by
    intro hz
    rw [hz, mul_zero] at hprod
    exact hnn0 hprod
  have hord : orderOf (t.σ ^ mm) = 2 ^ a := by
    rw [orderOf_pow_of_dvd hm0 hmdvd]
    conv_lhs => rw [hprod]
    exact Nat.mul_div_cancel _ (Nat.pos_of_ne_zero hm0)
  have hpow : IsPGroup 2 (Subgroup.zpowers (t.σ ^ mm)) :=
    IsPGroup.of_card (by rw [Nat.card_zpowers, hord])
  have htriv := pow2_smul_trivial_of_stable hM₂ (isSimpleModTwo_actionImage hsimple)
    (t.σ ^ mm) hpow (actionImage_unramified_stable hM₂ hsimple hτ mm)
  have h1 : t.σ ^ mm = 1 := actionImage_eq_one_of_smul_eq _ htriv
  have hdvd : orderOf t.σ ∣ mm := orderOf_dvd_of_pow_eq_one h1
  have heq : orderOf t.σ = mm := Nat.dvd_antisymm hdvd hmdvd
  rw [heq]
  exact hmodd

/-- **The `η̂`-conjugator is `sigma` on the unramified branch.**  `η̂` fixes every element of odd
order, and the resolver value of `η̂` at a level killing the target *is* the profinite `η̂`-power,
so the whole `η̂`-datum disappears from the unramified row. -/
theorem actionImage_unramified_sigma_etaPow
    (hM₂ : ∀ m : M, m + m = 0) (hsimple : IsSimpleModTwo (GammaR n q R : Type) M)
    (hτ : ∀ m : M, gammaGen n q R .tau • m = m) (d : EtaData) {N : ℕ} (hN : N ≠ 0)
    (hord : orderOf (actionImageMarking n q R M).σ ∣ N) :
    (actionImageMarking n q R M).σ ^ (npcResolver N d) d.toZhat
      = (actionImageMarking n q R M).σ := by
  set t := actionImageMarking n q R M with ht
  have hodd : Odd (orderOf t.σ) :=
    actionImage_unramified_orderOf_sigma_odd hM₂ hsimple hτ
  have h1 : t.σ ^ᶻ d.toZhat = t.σ ^ ((1 + padicOmega2Exp (d.toPadic - 1) N : ℕ)) := by
    rw [EtaData.toZhat, zpowHat_etaHatZ_zpow hN hord]
  have h2 : t.σ ^ᶻ d.toZhat = t.σ := by
    rw [EtaData.toZhat]
    exact zpowHat_etaHatZ_of_odd hodd
  rw [npcResolver_toZhat, zpow_natCast, ← h1, h2]

/-- **The boundary conjugator is fixed-point free on the generic sub-branch.**  `2^r` is a unit
modulo the odd order of `sigma`, so `sigma` is a power of `B = σ^{2^r}` and inherits its fixed
vectors. -/
theorem actionImage_unramified_sigmaPow_fixedPointFree
    (hM₂ : ∀ m : M, m + m = 0) (hsimple : IsSimpleModTwo (GammaR n q R : Type) M)
    (hτ : ∀ m : M, gammaGen n q R .tau • m = m)
    (hσfpf : ∀ m : M, (actionImageMarking n q R M).σ • m = m → m = 0) (r : ℕ) :
    ∀ m : M, ((actionImageMarking n q R M).σ ^ ((2 : ℤ) ^ r)) • m = m → m = 0 := by
  set t := actionImageMarking n q R M with ht
  have hodd : Odd (orderOf t.σ) :=
    actionImage_unramified_orderOf_sigma_odd hM₂ hsimple hτ
  have hpowNat : t.σ ^ ((2 : ℤ) ^ r) = t.σ ^ (2 ^ r : ℕ) := by
    rw [← zpow_natCast]
    norm_num
  intro m hm
  rw [hpowNat] at hm
  rcases eq_or_ne t.σ 1 with h1 | h1
  · exact hσfpf m (by rw [h1, one_smul])
  · have hnn0 : orderOf t.σ ≠ 0 := by
      rw [ne_eq, orderOf_eq_zero_iff, not_not]
      exact isOfFinOrder_of_finite t.σ
    have hnn1 : 1 < orderOf t.σ := by
      have hne : orderOf t.σ ≠ 1 := fun hc ↦ h1 (orderOf_eq_one_iff.mp hc)
      omega
    have h2 : ¬ (2 ∣ orderOf t.σ) := by
      rw [Nat.two_dvd_ne_zero]
      exact Nat.odd_iff.mp hodd
    have hcop : Nat.Coprime (2 ^ r) (orderOf t.σ) :=
      Nat.Coprime.pow_left r ((Nat.Prime.coprime_iff_not_dvd Nat.prime_two).mpr h2)
    have hnnpow : t.σ ^ ((orderOf t.σ : ℕ) : ℤ) = 1 := by
      rw [zpow_natCast, pow_orderOf_eq_one]
    have hbez : ((2 ^ r : ℕ) : ℤ) * Nat.gcdA (2 ^ r) (orderOf t.σ)
        + ((orderOf t.σ : ℕ) : ℤ) * Nat.gcdB (2 ^ r) (orderOf t.σ) = 1 := by
      have hg := Nat.gcd_eq_gcd_ab (2 ^ r) (orderOf t.σ)
      rw [show Nat.gcd (2 ^ r) (orderOf t.σ) = 1 from hcop] at hg
      push_cast at hg ⊢
      linarith
    have hkey : (t.σ ^ (2 ^ r : ℕ)) ^ Nat.gcdA (2 ^ r) (orderOf t.σ) = t.σ := by
      rw [← zpow_natCast t.σ (2 ^ r), ← zpow_mul,
        show ((2 ^ r : ℕ) : ℤ) * Nat.gcdA (2 ^ r) (orderOf t.σ)
          = 1 - ((orderOf t.σ : ℕ) : ℤ) * Nat.gcdB (2 ^ r) (orderOf t.σ) from by linarith,
        zpow_sub, zpow_one, zpow_mul, hnnpow, one_zpow, inv_one, mul_one]
    refine hσfpf m ?_
    rw [← hkey]
    exact MulAction.mem_stabilizer_iff.mp
      (zpow_mem (MulAction.mem_stabilizer_iff.mpr hm) _)

end

end GQ2.Dyadic.RowActionImage

namespace GQ2.Dyadic.NProcyclicUnram

noncomputable section

open GQ2 GQ2.FoxH
open GQ2.Dyadic GQ2.Dyadic.Words GQ2.Dyadic.Certificates
open GQ2.Dyadic.Certificates.MProcyclic
open GQ2.Dyadic.Count GQ2.Dyadic.RowActionImage

attribute [local instance] GQ2.Dyadic.Count.heisTopologicalSpace
  GQ2.Dyadic.Count.heisDiscreteTopology

/-! ## The solution operator of the unramified cocycle equation -/

section Phi

variable {C A : Type*} [Group C] [AddCommGroup A] [Finite A] [DistribMulAction C A]

/-- The additive map `a ↦ a − c·a`. -/
def oneSubHom (c : C) : A →+ A :=
  AddMonoidHom.mk' (fun a ↦ a - c • a) (by
    intro a b
    rw [smul_add]
    abel)

omit [Finite A] in
@[simp] theorem oneSubHom_apply (c : C) (a : A) : oneSubHom c a = a - c • a := rfl

/-- On a finite module a fixed-point-free `c` makes `1 − c` bijective. -/
theorem oneSubHom_bijective {c : C} (hc : ∀ a : A, c • a = a → a = 0) :
    Function.Bijective (oneSubHom (A := A) c) := by
  rw [Nat.bijective_iff_injective_and_card]
  refine ⟨?_, rfl⟩
  rw [injective_iff_map_eq_zero]
  intro a ha
  exact hc a (sub_eq_zero.mp ha).symm

/-- **The solution operator** `Φ = (1 − u)⁻¹(1 − g)` of the unramified cocycle equation.  It is
an additive endomorphism, never the action of a group element — which is exactly why the
ramified two-entry lane does not cover the unramified row. -/
def unramPhi (g : C) {u : C} (hu : ∀ a : A, u • a = a → a = 0) : A →+ A :=
  ((AddEquiv.ofBijective (oneSubHom (A := A) u) (oneSubHom_bijective hu)).symm : A →+ A).comp
    (oneSubHom (A := A) g)

/-- `Φ` solves the cocycle equation, by construction. -/
theorem unramPhi_spec (g : C) {u : C} (hu : ∀ a : A, u • a = a → a = 0) (a : A) :
    unramPhi (A := A) g hu a - u • unramPhi (A := A) g hu a = a - g • a :=
  (AddEquiv.ofBijective (oneSubHom (A := A) u)
    (oneSubHom_bijective hu)).apply_symm_apply (oneSubHom (A := A) g a)

/-- `Φ` is injective as soon as `g` is fixed-point free: it is a composite of two bijections. -/
theorem unramPhi_injective {g u : C} (hg : ∀ a : A, g • a = a → a = 0)
    (hu : ∀ a : A, u • a = a → a = 0) :
    Function.Injective (unramPhi (A := A) g hu) := by
  intro a b hab
  have ha := unramPhi_spec (A := A) g hu a
  have hb := unramPhi_spec (A := A) g hu b
  rw [hab] at ha
  exact (oneSubHom_bijective hg).1 (ha.symm.trans hb)

/-- Hence `Φ` is bijective on a finite module. -/
theorem unramPhi_bijective {g u : C} (hg : ∀ a : A, g • a = a → a = 0)
    (hu : ∀ a : A, u • a = a → a = 0) :
    Function.Bijective (unramPhi (A := A) g hu) :=
  (Nat.bijective_iff_injective_and_card _).mpr ⟨unramPhi_injective hg hu, rfl⟩

end Phi

/-! ## The unramified first differential of the procyclic-`N` family -/

section Row

variable {h α r q : ℕ} {C : Type*} [Group C] [Finite C] {A : Type*} [AddCommGroup A] [Finite A]
  [DistribMulAction C A] (t : Marking (2 + 2 * h) C)

set_option maxHeartbeats 800000 in
/-- **The complete unramified first differential of the corrected procyclic-`N` family.**  The
tame row is the `σ⁻¹`-pivot on `τ`; the wild row is the three-entry row
`(A⁻¹ − 1)a(x₀) + a(τ) + (1 − B⁻¹)a(x₂)`, in the shape `EvenPhiNormalStokes` consumes.  On the
action image of the unramified branch `A = σ` by
`RowActionImage.actionImage_unramified_sigma_etaPow`, so both blocks are invertible as soon as
`sigma` is fixed-point free. -/
theorem isPhiUnramRow_npc (hA₂ : ∀ a : A, a + a = 0) (hq : Even q) (hα : 1 ≤ α)
    (hwild : ∀ (i : Fin (2 + 2 * h + 1)) (a : A), t.x i • a = a)
    (hτ : ∀ a : A, t.τ • a = a) (d : EtaData) (N : ℕ)
    (hres : ResolverLifts (npcResolver N d) (WordLift A C)) :
    IsPhiUnramRow t (NProcyclic.resolvedFamily α r h q d N)
      ((t.σ ^ (npcResolver N d) d.toZhat)⁻¹) ((t.σ ^ ((2 : ℤ) ^ r))⁻¹) A := by
  intro x
  funext k
  fin_cases k
  · change
      (FreeGroup.lift (heisGen (⇑t) x 0)
        (heisToFree (npcResolver N d) (fun _ ↦ (0 : ℤ))
          (Certificates.tameRelW (2 + 2 * h) q))).a = t.σ⁻¹ • x .tau
    rw [← heisEvalZ_eq_lift, heisEvalZ_a_eq_foxD hres,
      Certificates.foxD_tameRelW_unram t _ _ hA₂ hτ hq]
  · change
      (FreeGroup.lift (heisGen (⇑t) x 0)
        (heisToFree (npcResolver N d) (fun _ ↦ (0 : ℤ))
          (Words.Npc.npcW α r h d))).a =
        ((t.σ ^ (npcResolver N d) d.toZhat)⁻¹ • x (coreLetter h 0) - x (coreLetter h 0))
          + x .tau
          + (x (coreLetter h 2) - (t.σ ^ ((2 : ℤ) ^ r))⁻¹ • x (coreLetter h 2))
    rw [← heisEvalZ_eq_lift, heisEvalZ_a_eq_foxD hres,
      Certificates.Npc.foxD_npc_unram t _ _ hA₂ hwild hτ hα d]
    abel

set_option maxHeartbeats 3200000 in
/-- **The generic unramified sub-branch of the procyclic-`N` row, reduced to one separation
statement.**  Every first-order ingredient is discharged: the row is three-entry with both
blocks invertible, so the middle is freely parametrised by `A × A × (Fin h × Fin 2 → A)` through
the solution operator `Φ = (1 − B⁻¹)⁻¹(1 − A⁻¹)`, and the ends are acyclic.  `hsep` is exactly
left nondegeneracy of the traced pairing on those coordinates. -/
theorem stokesDuality_npc_unramified_generic (hA₂ : ∀ a : A, a + a = 0) (hq : Even q)
    (hα : 1 ≤ α)
    (hwild : ∀ (i : Fin (2 + 2 * h + 1)) (a : A), t.x i • a = a)
    (hτ : ∀ a : A, t.τ • a = a)
    (hσfpf : ∀ a : A, t.σ • a = a → a = 0)
    (hufpf : ∀ a : A, ((t.σ ^ ((2 : ℤ) ^ r))⁻¹ : C) • a = a → a = 0)
    (d : EtaData) (N : ℕ)
    (hresA : ResolverLifts (npcResolver N d) (WordLift A C))
    (hresD : ResolverLifts (npcResolver N d) (WordLift (ElemDual A) C))
    (hr : ∀ k, FreeGroup.lift ⇑t (NProcyclic.resolvedFamily α r h q d N k) = 1)
    (hend : IsStokesEndpoint (NProcyclic.resolvedFamily α r h q d N))
    (hsep : ∀ p : A × A × (Fin h × Fin 2 → A), p ≠ 0 →
      ∃ rr : ElemDual A × ElemDual A × (Fin h × Fin 2 → ElemDual A),
        heisEta1 ⇑t (NProcyclic.resolvedFamily α r h q d N)
            (evenPhiNormal h
              (unramPhi (A := A) ((t.σ ^ (npcResolver N d) d.toZhat)⁻¹) hufpf)
              p.1 p.2.1 p.2.2)
            (evenPhiNormal h
              (unramPhi (A := ElemDual A) ((t.σ ^ (npcResolver N d) d.toZhat)⁻¹)
                (fun lam hlam ↦ elemDual_fpf hufpf lam hlam))
              rr.1 rr.2.1 rr.2.2) ≠ 0) :
    StokesDuality ⇑t (NProcyclic.resolvedFamily α r h q d N) A := by
  have hA₂D : ∀ lam : ElemDual A, lam + lam = 0 := fun lam ↦ lam.add_self_eq_zero
  have hwildD : ∀ (i : Fin (2 + 2 * h + 1)) (lam : ElemDual A), t.x i • lam = lam :=
    fun i lam ↦ elemDual_smul_eq_self (hwild i) lam
  have hτD : ∀ lam : ElemDual A, t.τ • lam = lam := fun lam ↦ elemDual_smul_eq_self hτ lam
  have hufpfD : ∀ lam : ElemDual A, ((t.σ ^ ((2 : ℤ) ^ r))⁻¹ : C) • lam = lam → lam = 0 :=
    fun lam hlam ↦ elemDual_fpf hufpf lam hlam
  exact evenPhiStokesDuality_of_row
    ((t.σ ^ (npcResolver N d) d.toZhat)⁻¹) ((t.σ ^ ((2 : ℤ) ^ r))⁻¹) t _ hA₂ hr hend
    (isPhiUnramRow_npc (α := α) (r := r) t hA₂ hq hα hwild hτ d N hresA)
    (isPhiUnramRow_npc (A := ElemDual A) (α := α) (r := r) t hA₂D hq hα hwildD hτD d N hresD)
    (unramPhi (A := A) ((t.σ ^ (npcResolver N d) d.toZhat)⁻¹) hufpf)
    (unramPhi (A := ElemDual A) ((t.σ ^ (npcResolver N d) d.toZhat)⁻¹) hufpfD)
    (unramPhi_spec (A := A) _ hufpf) (unramPhi_spec (A := ElemDual A) _ hufpfD)
    hufpf hwild hτ hσfpf hsep

end Row

end

end GQ2.Dyadic.NProcyclicUnram

/-! ## Axiom audit -/

section AxiomAudit

#print axioms GQ2.Dyadic.RowActionImage.actionImage_unramified_mem_zpowers
#print axioms GQ2.Dyadic.RowActionImage.actionImage_unramified_stable
#print axioms GQ2.Dyadic.RowActionImage.actionImage_unramified_orderOf_sigma_odd
#print axioms GQ2.Dyadic.RowActionImage.actionImage_unramified_sigma_etaPow
#print axioms GQ2.Dyadic.RowActionImage.actionImage_unramified_sigmaPow_fixedPointFree
#print axioms GQ2.Dyadic.NProcyclicUnram.oneSubHom_bijective
#print axioms GQ2.Dyadic.NProcyclicUnram.unramPhi_spec
#print axioms GQ2.Dyadic.NProcyclicUnram.unramPhi_bijective
#print axioms GQ2.Dyadic.NProcyclicUnram.isPhiUnramRow_npc
#print axioms GQ2.Dyadic.NProcyclicUnram.stokesDuality_npc_unramified_generic

end AxiomAudit
