/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-5
-/
import GQ2.Dyadic.Instances.StageAbstractionEvenFrameCore

/-!
# W51-EV3C2E, part 1: the even Frattini-frame supply at the `M` row

Ticket **EV-3c**, `M`-row half (`EV-3c2`), of `docs/dyadic/ev4b-stage-abstraction.md` §4.  The
core-agnostic scaffolding is `GQ2/Dyadic/Instances/StageAbstractionEvenFrameCore.lean` and the
template is the landed `N`-row instance
`GQ2/Dyadic/Instances/StageAbstractionEvenFrattiniFrameN.lean`; this file adds only what mentions
`MarkedCore.mUnit`, the value `−1`, and the committed `M` row table `StageGeneric.vM`.

## Board crux (ii): the `M` mod-sixteen bridge table

The `M`-word table is `(A, B, C₀, D) ↦ (1, −1, 1, mUnit α)` with handles `1`, so it has **two**
nontrivial entries, at two different letters, where the `N` table had one.  From the committed
defining relation `mUnit α · (1 − 2 ^ α) = 1` (`MarkedCore.mUnit_mul`), for `α ≥ 2`:

| entry | letter | `α` | `1 − 2 ^ α` mod 16 | value mod 16 | mod 8 | mod 4 | parity | `ω` |
|---|---|---|---|---|---|---|---|---|
| `−1` | `B` (index `1`) | any | | `15` | `7` | `3` | **`1`** | **`0`** |
| `mUnit α` | `D` (index `3`) | `2` | `13` | **`5`** | `5` | `1` | `0` | **`1`** |
| `mUnit α` | `D` (index `3`) | `3` | `9` | **`9`** | `1` | `1` | `0` | **`0`** |
| `mUnit α` | `D` (index `3`) | `≥ 4` | `1` | **`1`** | `1` | `1` | `0` | **`0`** |

Three things fall out, and all three are campaign checkpoints.

**(a) The parity column is again the indicator of the letter at index `1`.**  For `M` that letter
is `B`, carrying `−1 ≡ 3 (mod 4)`; the depth unit `mUnit α ≡ 1 (mod 4)` contributes nothing.  So
by the scaffolding's §1.5, where the model forces the mod-four class `κ` to the frame coordinate
vector supported at index `1`, the parity half of the `M` bridge table matches with no hypothesis
on `K` at all, exactly as at the `N` row but for a different arithmetic reason.

**(b) The `ω` column is `α`-dependent, nonzero exactly at `α = 2`**, where `mUnit 2 ≡ 5 (mod 8)`
and `ω(5) = 1`.  This is the `M` analogue of the `N` row's one-bit `α`-dependence, and it says the
same thing: `α` is `K`'s orientation invariant, at least mod eight.

**(c) The `M` `ω` entry sits at a different letter from the `M` parity entry**, namely at `D`
(index `3`) rather than at `B` (index `1`).  **This is where the `M` row genuinely departs from the
`N` row**, and it is not a labelling accident: at the `N` row both nontrivial shadows live at the
single letter `x₁`, so the whole `ω` table is a scalar multiple of the parity table and the frame
follows from the class identity `τ = c • κ` alone (`evenFrame_of_kappaPin`).  At the `M` row that
is true only when the `ω` table vanishes, i.e. when `α ≥ 3`, where the scalar is `0`.  At `α = 2`
**no scalar `c` works**: at index `1` the table forces `c · 1 = ω(−1) = 0`, hence `c = 0`, while at
index `3` it forces `c · 0 = ω(mUnit 2) = 1`.  Machine-checked as
`evenDegreeM_no_omegaScalar_two` (§3.3), so this is an obstruction, not a proof-search failure.

Consequently `α = 2` is served by the more primitive `evenFrame_of_adapted`, with a second Witt
refinement placing `Φ τ` on the `(2,3)` plane (§4): the even route's own version of the odd
route's "put the `ω` vector on the diagonal of the first hyperbolic plane" step, which the
`N` row never needed.

## Board crux (iii): the rows and `im χ`

The `M` row's values are `1`, `−1` (at `B`) and `mUnit α` (at `D`).  Membership of `−1` and of
`mUnit α` in `im χ_cyc` is **not** proved here and **not** assumed as a bare range fact: it is
subsumed in the carried `RowExactLevelFibreLiftSupply (vM α)` binder, ticket EV-4a's deliverable,
which is unsatisfiable without it.  For `M` the `−1` row is exactly the "`−1 ∈ im χ`" branch
condition of board note (iii), and `MarkedCore.neg_one_notMem_imChiN` shows the `N` and `M` images
genuinely differ, so this is the one row datum that could not have been inherited from the `N`
file.  §3's `EvenDegreeMModEightImage` is correspondingly the mod-eight shadow of the subgroup
generated by the `M` row values, a **four**-element set `{1, −1, mUnit α, −mUnit α}`, not the
`N` file's two.

## What is proved and what is owed

Proved: the bridge table at both entries, both shadow tables of `vM α`, the impossibility of an
`α = 2` scalar, the class pin at `α ≥ 3`, the second Witt refinement at `α = 2`, and the supply
theorem for **every** `α ≥ 2` (both branches; nothing is gated out).  Owed, as explicit binders of
the supply: the EV-4a row lift supply, the ramified-`i` binder `κ ≠ 0`, `EvenDegreeMModEightImage`
(consumed only at `α ≥ 3`), and at `α = 2` the two seams of §4.3.  No `sorry`, no new axiom.
-/

namespace GQ2.Dyadic.StageGeneric

noncomputable section

open GQ2 ContCoh
open GQ2.Roe.Labute
open GQ2.HilbertSymbol
open GQ2.Dyadic.LSquare
open GQ2.Dyadic.LSquare.FrattiniFrameSupply

local notation "ℚ̄₂" => AlgebraicClosure ℚ_[2]

/-! ## §1 The mod-sixteen bridge table at the `M` row values

Everything comes from the committed defining relation `MarkedCore.mUnit_mul`, pushed through
`PadicInt.toZModPow` and solved in the (tiny, closed) residue ring, plus the two residues of `−1`.
No mod-eight or mod-sixteen value of `mUnit` existed in the repo before this section. -/

/-- The defining relation of the `M` row's depth unit, reduced mod `2 ^ k`.  Note the shape
differs from the `N` row's `nUnit α · (1 + 2 ^ α) = −1`: here the sign is inside and the product
is `1`, since `mUnit α = (1 − 2 ^ α)⁻¹`. -/
theorem evenBridgeM_mUnit_mul (k : ℕ) {α : ℕ} (hα : 1 ≤ α) :
    (PadicInt.toZModPow k ((MarkedCore.mUnit α : ℤ_[2]ˣ) : ℤ_[2])) * (1 - 2 ^ α) = 1 := by
  have h := congrArg (PadicInt.toZModPow (p := 2) k) (MarkedCore.mUnit_mul (α := α) hα)
  simpa [map_ofNat] using h

/-- Solving the reduced relation mod eight at `α = 2` (`x · (1 − 4) = 1` in `ZMod 8`). -/
theorem evenBridgeM_solve_modEight {x : ZMod (2 ^ 3)} (h : x * (1 - 2 ^ 2) = 1) : x = 5 := by
  revert x
  decide

/-- Solving the reduced relation mod sixteen at `α = 2` (`x · (1 − 4) = 1` in `ZMod 16`). -/
theorem evenBridgeM_solve_modSixteen_two {x : ZMod (2 ^ 4)} (h : x * (1 - 2 ^ 2) = 1) :
    x = 5 := by
  revert x
  decide

/-- Solving the reduced relation mod sixteen at `α = 3` (`x · (1 − 8) = 1` in `ZMod 16`). -/
theorem evenBridgeM_solve_modSixteen_three {x : ZMod (2 ^ 4)} (h : x * (1 - 2 ^ 3) = 1) :
    x = 9 := by
  revert x
  decide

/-- **`mUnit α ≡ 1 (mod 4)` for `α ≥ 2`**, the parity entry of the depth unit, constant in `α`
and *trivial*, where the `N` row's was `3`.  (Agrees with the committed
`MarkedCore.mUnit_toZModPow_two`; re-derived here from the same defining relation the rest of the
table comes from, so that the whole table has one source.) -/
theorem evenBridgeM_mUnit_modFour {α : ℕ} (hα : 2 ≤ α) :
    PadicInt.toZModPow 2 ((MarkedCore.mUnit α : ℤ_[2]ˣ) : ℤ_[2]) = 1 := by
  have h := evenBridgeM_mUnit_mul 2 (α := α) (by omega)
  have h2 : (2 : ZMod (2 ^ 2)) ^ α = 0 := by
    obtain ⟨t, rfl⟩ : ∃ t, α = 2 + t := ⟨α - 2, by omega⟩
    rw [pow_add, show ((2 : ZMod (2 ^ 2)) ^ 2 = 0) from by decide, zero_mul]
  rw [h2, sub_zero, mul_one] at h
  exact h

/-- **`mUnit 2 ≡ 5 (mod 8)`**, the only `α` at which the `M` `ω` entry is nonzero. -/
theorem evenBridgeM_mUnit_modEight_two :
    PadicInt.toZModPow 3 ((MarkedCore.mUnit 2 : ℤ_[2]ˣ) : ℤ_[2]) = 5 :=
  evenBridgeM_solve_modEight (evenBridgeM_mUnit_mul 3 (α := 2) (by omega))

/-- **`mUnit α ≡ 1 (mod 8)` for `α ≥ 3`**: the `M` `ω` entry vanishes from `α = 3` on.  (The `N`
row's unit is `≡ 7` there; both have `ω = 0`, but the `M` unit is trivial mod eight, which is why
the whole `M` `ω` table vanishes rather than merely becoming a multiple of the parity table.) -/
theorem evenBridgeM_mUnit_modEight_ge {α : ℕ} (hα : 3 ≤ α) :
    PadicInt.toZModPow 3 ((MarkedCore.mUnit α : ℤ_[2]ˣ) : ℤ_[2]) = 1 := by
  have h := evenBridgeM_mUnit_mul 3 (α := α) (by omega)
  have h2 : (2 : ZMod (2 ^ 3)) ^ α = 0 := by
    obtain ⟨t, rfl⟩ : ∃ t, α = 3 + t := ⟨α - 3, by omega⟩
    rw [pow_add, show ((2 : ZMod (2 ^ 3)) ^ 3 = 0) from by decide, zero_mul]
  rw [h2, sub_zero, mul_one] at h
  exact h

/-! ### §1.1 The mod-sixteen row of the table

Recorded at the same modulus as the odd route's `S ≡ 13`, `X ≡ 5`, `Y ≡ 7` and the `N` row's
`3, 7, 15`, for the campaign record.  Only the mod-eight reductions are consumed downstream. -/

/-- **`mUnit 2 ≡ 5 (mod 16)`.** -/
theorem evenBridgeM_mUnit_modSixteen_two :
    PadicInt.toZModPow 4 ((MarkedCore.mUnit 2 : ℤ_[2]ˣ) : ℤ_[2]) = 5 :=
  evenBridgeM_solve_modSixteen_two (evenBridgeM_mUnit_mul 4 (α := 2) (by omega))

/-- **`mUnit 3 ≡ 9 (mod 16)`.** -/
theorem evenBridgeM_mUnit_modSixteen_three :
    PadicInt.toZModPow 4 ((MarkedCore.mUnit 3 : ℤ_[2]ˣ) : ℤ_[2]) = 9 :=
  evenBridgeM_solve_modSixteen_three (evenBridgeM_mUnit_mul 4 (α := 3) (by omega))

/-- **`mUnit α ≡ 1 (mod 16)` for `α ≥ 4`**: the table is constant from `α = 4` on, since `2 ^ α`
then dies mod sixteen.  (`N`'s constant tail is `15`; `M`'s is `1`.) -/
theorem evenBridgeM_mUnit_modSixteen_ge {α : ℕ} (hα : 4 ≤ α) :
    PadicInt.toZModPow 4 ((MarkedCore.mUnit α : ℤ_[2]ˣ) : ℤ_[2]) = 1 := by
  have h := evenBridgeM_mUnit_mul 4 (α := α) (by omega)
  have h2 : (2 : ZMod (2 ^ 4)) ^ α = 0 := by
    obtain ⟨t, rfl⟩ : ∃ t, α = 4 + t := ⟨α - 4, by omega⟩
    rw [pow_add, show ((2 : ZMod (2 ^ 4)) ^ 4 = 0) from by decide, zero_mul]
  rw [h2, sub_zero, mul_one] at h
  exact h

/-! ### §1.2 The `−1` row

The entry the `N` row does not have (board note (iii)).  Its two residues are `α`-free. -/

/-- `−1 ≡ 3 (mod 4)`: the `M` parity entry, at the letter `B`. -/
theorem evenBridgeM_negOne_modFour :
    PadicInt.toZModPow 2 (((-1 : ℤ_[2]ˣ) : ℤ_[2])) = 3 := by
  rw [Units.val_neg, Units.val_one, map_neg, map_one]
  decide

/-- `−1 ≡ 7 (mod 8)`: the `M` `ω` entry at the letter `B` vanishes, for every `α`. -/
theorem evenBridgeM_negOne_modEight :
    PadicInt.toZModPow 3 (((-1 : ℤ_[2]ˣ) : ℤ_[2])) = 7 := by
  rw [Units.val_neg, Units.val_one, map_neg, map_one]
  decide

/-- `−1 ≡ 15 (mod 16)`, for the record. -/
theorem evenBridgeM_negOne_modSixteen :
    PadicInt.toZModPow 4 (((-1 : ℤ_[2]ˣ) : ℤ_[2])) = 15 := by
  rw [Units.val_neg, Units.val_one, map_neg, map_one]
  decide

/-! ### §1.3 The four shadows of the two row values -/

/-- **The `ω` scalar of the `M` row**: `1` at `α = 2` and `0` at `α ≥ 3`.  As at the `N` row the
whole `α`-dependence of the even `M` bridge table is this one bit; **unlike** the `N` row it is
*not* a scalar relating the `ω` table to the parity table, because the two tables are supported at
different letters (§3.3).  It is the value of the `ω` table at the letter `D`. -/
def evenDegreeMOmegaScalar (α : ℕ) : ZMod 2 := if α = 2 then 1 else 0

/-- The mod-four parity shadow of the depth unit is `0`, for every `α ≥ 2`. -/
theorem evenDegreeM_parity_mUnit {α : ℕ} (hα : 2 ≤ α) :
    Multiplicative.toAdd (unitsModFourParity
      (Units.map (PadicInt.toZModPow 2).toMonoidHom (MarkedCore.mUnit α))) = 0 :=
  frattiniFrame_parity_of_val_one (evenBridgeM_mUnit_modFour hα)

/-- The mod-eight `ω` shadow of the depth unit is `evenDegreeMOmegaScalar α`. -/
theorem evenDegreeM_omega_mUnit {α : ℕ} (hα : 2 ≤ α) :
    Multiplicative.toAdd (unitsModEightOmega
      (Units.map (PadicInt.toZModPow 3).toMonoidHom (MarkedCore.mUnit α))) =
        evenDegreeMOmegaScalar α := by
  rcases eq_or_lt_of_le hα with hα2 | hα3
  · subst hα2
    rw [frattiniFrame_omega_of_val evenBridgeM_mUnit_modEight_two, omegaResidue_table.2.2.1,
      evenDegreeMOmegaScalar, if_pos rfl]
  · rw [frattiniFrame_omega_of_val (evenBridgeM_mUnit_modEight_ge (by omega)),
      omegaResidue_table.1, evenDegreeMOmegaScalar, if_neg (by omega)]

/-- The mod-four parity shadow of `−1` is `1`. -/
theorem evenDegreeM_parity_negOne :
    Multiplicative.toAdd (unitsModFourParity
      (Units.map (PadicInt.toZModPow 2).toMonoidHom (-1 : ℤ_[2]ˣ))) = 1 :=
  frattiniFrame_parity_of_val_three evenBridgeM_negOne_modFour

/-- The mod-eight `ω` shadow of `−1` is `0`. -/
theorem evenDegreeM_omega_negOne :
    Multiplicative.toAdd (unitsModEightOmega
      (Units.map (PadicInt.toZModPow 3).toMonoidHom (-1 : ℤ_[2]ˣ))) = 0 := by
  rw [frattiniFrame_omega_of_val evenBridgeM_negOne_modEight, omegaResidue_table.2.2.2]

/-! ## §2 The two shadow tables of the `M` row

The mod-four parity table of `vM α` is the indicator of the letter at index `1` (as at the `N`
row, so `evenFrame_of_kappaPin`'s parity hypothesis is met for every `α ≥ 2`), while the mod-eight
`ω` table is `evenDegreeMOmegaScalar α` times the indicator of the letter at index **`3`**. -/

/-- **The `M` parity table**: `1` at the letter `B` (index `1`) and `0` at every other letter,
the same shape as the `N` row's.  This is the table the model's Labute vector already realises,
so it costs no hypothesis on `K`. -/
theorem evenDegreeM_parity_table {α h : ℕ} (hα : 2 ≤ α) (i : Fin (MarkedCore.coreRank h)) :
    Multiplicative.toAdd (unitsModFourParity
      (Units.map (PadicInt.toZModPow 2).toMonoidHom (vM α i))) =
        if (i : ℕ) = 1 then 1 else 0 := by
  refine evenIndex_cases
    (P := fun i ↦ Multiplicative.toAdd (unitsModFourParity
      (Units.map (PadicInt.toZModPow 2).toMonoidHom (vM α i))) =
        if (i : ℕ) = 1 then 1 else 0) ?_ ?_ ?_ ?_ ?_ ?_ i
  · rw [vM_zero, map_one, map_one, toAdd_one,
      if_neg (by rw [MarkedCore.coreVal_zero]; omega)]
  · rw [vM_one, evenDegreeM_parity_negOne, if_pos (MarkedCore.coreVal_one h)]
  · rw [vM_two, map_one, map_one, toAdd_one, if_neg (by rw [MarkedCore.coreVal_two]; omega)]
  · rw [vM_three, evenDegreeM_parity_mUnit hα,
      if_neg (by rw [MarkedCore.coreVal_three]; omega)]
  · intro j
    rw [vM_handleU, map_one, map_one, toAdd_one,
      if_neg (by rw [MarkedCore.handleIdxU_val]; omega)]
  · intro j
    rw [vM_handleV, map_one, map_one, toAdd_one,
      if_neg (by rw [MarkedCore.handleIdxV_val]; omega)]

/-- **The `M` `ω` table**: `evenDegreeMOmegaScalar α` at the letter `D` (index `3`) and `0`
elsewhere.  The support is at index `3`, not index `1`: this is board crux (c) of the module
docstring, and the reason the `M` row needs §4. -/
theorem evenDegreeM_omega_table {α h : ℕ} (hα : 2 ≤ α) (i : Fin (MarkedCore.coreRank h)) :
    Multiplicative.toAdd (unitsModEightOmega
      (Units.map (PadicInt.toZModPow 3).toMonoidHom (vM α i))) =
        evenDegreeMOmegaScalar α * (if (i : ℕ) = 3 then 1 else 0) := by
  refine evenIndex_cases
    (P := fun i ↦ Multiplicative.toAdd (unitsModEightOmega
      (Units.map (PadicInt.toZModPow 3).toMonoidHom (vM α i))) =
        evenDegreeMOmegaScalar α * (if (i : ℕ) = 3 then 1 else 0)) ?_ ?_ ?_ ?_ ?_ ?_ i
  · rw [vM_zero, map_one, map_one, toAdd_one,
      if_neg (by rw [MarkedCore.coreVal_zero]; omega), mul_zero]
  · rw [vM_one, evenDegreeM_omega_negOne, if_neg (by rw [MarkedCore.coreVal_one]; omega),
      mul_zero]
  · rw [vM_two, map_one, map_one, toAdd_one,
      if_neg (by rw [MarkedCore.coreVal_two]; omega), mul_zero]
  · rw [vM_three, evenDegreeM_omega_mUnit hα, if_pos (MarkedCore.coreVal_three h), mul_one]
  · intro j
    rw [vM_handleU, map_one, map_one, toAdd_one,
      if_neg (by rw [MarkedCore.handleIdxU_val]; omega), mul_zero]
  · intro j
    rw [vM_handleV, map_one, map_one, toAdd_one,
      if_neg (by rw [MarkedCore.handleIdxV_val]; omega), mul_zero]

/-! ### §2.1 The `α = 2` obstruction to the `N`-row route

The scaffolding's `evenFrame_of_kappaPin` asks for a single scalar `c` with `ω`-table
`= c · (parity table)`, i.e. `c` times the indicator of index `1`.  At the `M` row that request is
**refutable** at `α = 2`, and the refutation is one line of the table: the `ω` value at the letter
`D` is `1`, while `c · (indicator of index 1)` is `c · 0 = 0` there, for every `c`.

This is the machine-checked form of the `N` agent's warning, and it is what forces §4. -/

/-- **No `ω` scalar exists at the `M` row when `α = 2`.**  Hence `evenFrame_of_kappaPin`, which is
the whole of the `N` row's frame construction, cannot be used at `M` for `α = 2`: not because a
proof was not found, but because its hypothesis is false there.  (For `α ≥ 3` the scalar is `0`
and the route works; see §3.) -/
theorem evenDegreeM_no_omegaScalar_two {h : ℕ} :
    ¬ ∃ c : ZMod 2, ∀ i : Fin (MarkedCore.coreRank h),
      Multiplicative.toAdd (unitsModEightOmega
        (Units.map (PadicInt.toZModPow 3).toMonoidHom (vM 2 i))) =
          c * (if (i : ℕ) = 1 then 1 else 0) := by
  rintro ⟨c, hc⟩
  have h3 := hc 3
  rw [evenDegreeM_omega_table (by omega) 3, if_pos (MarkedCore.coreVal_three h),
    if_neg (by rw [MarkedCore.coreVal_three]; omega), mul_one, mul_zero,
    evenDegreeMOmegaScalar, if_pos rfl] at h3
  exact one_ne_zero h3

/-! ## §3 The mod-eight orientation hypotheses, and the `ω`-class pin at `α ≥ 3`

The priced seams of this ticket, in the house pattern: named `Prop`s, discharged nowhere here.
There are two, because the `M` row's `ω` entry can be nonzero.  §3 asks that the mod-eight image
be no larger than the row values generate (consumed at `α ≥ 3`, where it forces `τ = 0`); §3.1
asks that the depth row value actually be attained (consumed at `α = 2`, where it forces `τ` to be
independent of `κ`).  Both are consequences of the image identity
`MonoidHom.range chiCycKTwo = MarkedCore.imChiM α`, and each is vacuous where the other bites. -/

section EvenFieldM

variable {K : IntermediateField ℚ_[2] ℚ̄₂} [FiniteDimensional ℚ_[2] K]
  [CompactSpace (GalK K)] [T2Space (GalK K)] [TotallyDisconnectedSpace (GalK K)]

local instance mEvenFrameScalar : DistribMulAction (maxProPQuotient 2 (GalK K)) (ZMod 2) :=
  scalarActionZmodTwo _

local instance mEvenFrameContinuousScalar :
    ContinuousSMul (maxProPQuotient 2 (GalK K)) (ZMod 2) :=
  scalarActionZmodTwo_continuousSMul _

/-- **The even `M`-row mod-eight orientation hypothesis.**  Every cyclotomic value of `G_K(2)`
reduces mod eight into `{1, −1, mUnit α, −mUnit α}`.

This is the mod-eight half of `MonoidHom.range chiCycKTwo = MarkedCore.imChiM α`.  Where the `N`
row's twin has a two-element set, this one has four: the `M` image is generated by **two** row
values, `−1` and `mUnit α`, so its mod-eight shadow is closed under multiplication by `−1`.  At
`α ≥ 3` the set collapses to `{1, −1}` (§1), which is what makes the `ω` class vanish; at `α = 2`
it is all of `(ZMod 8)ˣ` and the hypothesis says nothing, which is why `α = 2` needs §3.1 instead.

It is *not* discharged in this lane: the forward route deliberately avoids assuming the range
identity (`EvenForwardRouteSkeleton.lean:20–28`), so a consumer that has the range identity
supplies this, and a consumer that does not must obtain it another way. -/
def EvenDegreeMModEightImage (α : ℕ) : Prop :=
  ∀ g : maxProPQuotient 2 (GalK K),
    PadicInt.toZModPow 3 ((chiCycKTwo (K := K) g : ℤ_[2]ˣ) : ℤ_[2]) = 1 ∨
      PadicInt.toZModPow 3 ((chiCycKTwo (K := K) g : ℤ_[2]ˣ) : ℤ_[2]) = -1 ∨
      PadicInt.toZModPow 3 ((chiCycKTwo (K := K) g : ℤ_[2]ˣ) : ℤ_[2]) =
        PadicInt.toZModPow 3 ((MarkedCore.mUnit α : ℤ_[2]ˣ) : ℤ_[2]) ∨
      PadicInt.toZModPow 3 ((chiCycKTwo (K := K) g : ℤ_[2]ˣ) : ℤ_[2]) =
        -PadicInt.toZModPow 3 ((MarkedCore.mUnit α : ℤ_[2]ˣ) : ℤ_[2])

omit [FiniteDimensional ℚ_[2] K] [T2Space (GalK K)] in
/-- **The `ω`-class pin at the `M` row, for `α ≥ 3`.**  There the mod-eight orientation hypothesis
forces `τ = 0 = evenDegreeMOmegaScalar α • κ`: every cyclotomic value is `≡ ±1 (mod 8)`, where `ω`
vanishes.  Compare the `N` row, where the pin is nontrivial at every `α`; here the pin says the
`ω` class *itself* dies, which is stronger, and is exactly what the vanishing `M` `ω` table
demands. -/
theorem evenDegreeM_omegaPin_of_modEightImage {α : ℕ} (hα : 3 ≤ α)
    (himg : EvenDegreeMModEightImage (K := K) α) :
    cyclotomicModEightOmegaClassKTwo (K := K) =
      evenDegreeMOmegaScalar α • cyclotomicModFourClassKTwo (K := K) := by
  have hscal : evenDegreeMOmegaScalar α = 0 := by
    rw [evenDegreeMOmegaScalar, if_neg (by omega)]
  have hm : PadicInt.toZModPow 3 ((MarkedCore.mUnit α : ℤ_[2]ˣ) : ℤ_[2]) = 1 :=
    evenBridgeM_mUnit_modEight_ge hα
  have homegaOne : omegaResidue 1 = 0 := omegaResidue_table.1
  have homegaNeg : omegaResidue (-1) = 0 := by decide
  refine evenFrameOmegaPin_of_pointwise _ fun g ↦ ?_
  rw [hscal, zero_mul]
  rcases himg g with h1 | h2 | h3 | h4
  · rw [frattiniFrame_omega_of_val h1, homegaOne]
  · rw [frattiniFrame_omega_of_val h2, homegaNeg]
  · rw [hm] at h3
    rw [frattiniFrame_omega_of_val h3, homegaOne]
  · rw [hm] at h4
    rw [frattiniFrame_omega_of_val h4, homegaNeg]

/-! ### §3.1 The attained-row hypothesis, the `α = 2` seam -/

/-- **The even `M`-row attainment hypothesis**: the depth row value `mUnit α` is realised mod
eight by some cyclotomic value.

This is the mod-eight half of `mUnit α ∈ MonoidHom.range chiCycKTwo`, i.e. of the `D`-row
membership that the `M` row needs anyway (board note (iii)).  It cannot be extracted from the
carried `RowExactLevelFibreLiftSupply` binder, which lifts *given* level classes of the right
shadow rather than asserting that any exist, so it is stated separately.

At `α ≥ 3` it is free (`evenDegreeM_rowAttained_of_ge`); at `α = 2` it is the whole content of the
`α = 2` branch, since it is what makes the `ω` class nonzero and independent of `κ`. -/
def EvenDegreeMModEightRowAttained (α : ℕ) : Prop :=
  ∃ g : maxProPQuotient 2 (GalK K),
    PadicInt.toZModPow 3 ((chiCycKTwo (K := K) g : ℤ_[2]ˣ) : ℤ_[2]) =
      PadicInt.toZModPow 3 ((MarkedCore.mUnit α : ℤ_[2]ˣ) : ℤ_[2])

omit [FiniteDimensional ℚ_[2] K] [T2Space (GalK K)] in
/-- At `α ≥ 3` the attainment hypothesis costs nothing: the depth unit is `≡ 1 (mod 8)` there and
the identity element witnesses it.  So the `α = 2` branch is the only place a consumer pays. -/
theorem evenDegreeM_rowAttained_of_ge {α : ℕ} (hα : 3 ≤ α) :
    EvenDegreeMModEightRowAttained (K := K) α :=
  ⟨1, by rw [map_one, Units.val_one, map_one, evenBridgeM_mUnit_modEight_ge hα]⟩

end EvenFieldM

end

end GQ2.Dyadic.StageGeneric
