/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-5
-/
import GQ2.Dyadic.Instances.StageAbstractionEvenFrameCore

/-!
# W51-EV3C2E, part 1: the even Frattini-frame supply at the `M` row

Ticket **EV-3c**, `M`-row half (`EV-3c2`), of `docs/dyadic/ev4b-stage-abstraction.md` §4.  The
core-agnostic scaffolding is `GQ2/Dyadic/Instances/StageAbstractionEvenFrameCore.lean` and the
template is the landed `N`-row instance
`GQ2/Dyadic/Instances/StageAbstractionEvenFrattiniFrameN.lean`; this file adds only what mentions
`MarkedCore.mUnit`, the value `−1`, and the committed `M` row table `StageGeneric.vM`.

## Board crux (ii): the `M` mod-sixteen bridge table

The `M`-word table is `(A, B, C₀, D) ↦ (1, −1, 1, mUnit α)` with handles `1`, so it has **two**
nontrivial entries, at two different letters, where the `N` table had one.  From the committed
defining relation `mUnit α · (1 − 2 ^ α) = 1` (`MarkedCore.mUnit_mul`), for `α ≥ 2`:

| entry | letter | `α` | `1 − 2 ^ α` mod 16 | value mod 16 | mod 8 | mod 4 | parity | `ω` |
|---|---|---|---|---|---|---|---|---|
| `−1` | `B` (index `1`) | any | | `15` | `7` | `3` | **`1`** | **`0`** |
| `mUnit α` | `D` (index `3`) | `2` | `13` | **`5`** | `5` | `1` | `0` | **`1`** |
| `mUnit α` | `D` (index `3`) | `3` | `9` | **`9`** | `1` | `1` | `0` | **`0`** |
| `mUnit α` | `D` (index `3`) | `≥ 4` | `1` | **`1`** | `1` | `1` | `0` | **`0`** |

Three things fall out, and all three are campaign checkpoints.

**(a) The parity column is again the indicator of the letter at index `1`.**  For `M` that letter
is `B`, carrying `−1 ≡ 3 (mod 4)`; the depth unit `mUnit α ≡ 1 (mod 4)` contributes nothing.  So
by the scaffolding's §1.5, where the model forces the mod-four class `κ` to the frame coordinate
vector supported at index `1`, the parity half of the `M` bridge table matches with no hypothesis
on `K` at all, exactly as at the `N` row but for a different arithmetic reason.

**(b) The `ω` column is `α`-dependent, nonzero exactly at `α = 2`**, where `mUnit 2 ≡ 5 (mod 8)`
and `ω(5) = 1`.  This is the `M` analogue of the `N` row's one-bit `α`-dependence, and it says the
same thing: `α` is `K`'s orientation invariant, at least mod eight.

**(c) The `M` `ω` entry sits at a different letter from the `M` parity entry**, namely at `D`
(index `3`) rather than at `B` (index `1`).  **This is where the `M` row genuinely departs from the
`N` row**, and it is not a labelling accident: at the `N` row both nontrivial shadows live at the
single letter `x₁`, so the whole `ω` table is a scalar multiple of the parity table and the frame
follows from the class identity `τ = c • κ` alone (`evenFrame_of_kappaPin`).  At the `M` row that
is true only when the `ω` table vanishes, i.e. when `α ≥ 3`, where the scalar is `0`.  At `α = 2`
**no scalar `c` works**: at index `1` the table forces `c · 1 = ω(−1) = 0`, hence `c = 0`, while at
index `3` it forces `c · 0 = ω(mUnit 2) = 1`.  Machine-checked as
`evenDegreeM_no_omegaScalar_two` (§3.3), so this is an obstruction, not a proof-search failure.

Consequently `α = 2` is served by the more primitive `evenFrame_of_adapted`, with a second Witt
refinement placing `Φ τ` on the `(2,3)` plane (§4): the even route's own version of the odd
route's "put the `ω` vector on the diagonal of the first hyperbolic plane" step, which the
`N` row never needed.

## Board crux (iii): the rows and `im χ`

The `M` row's values are `1`, `−1` (at `B`) and `mUnit α` (at `D`).  Membership of `−1` and of
`mUnit α` in `im χ_cyc` is **not** proved here and **not** assumed as a bare range fact: it is
subsumed in the carried `RowExactLevelFibreLiftSupply (vM α)` binder, ticket EV-4a's deliverable,
which is unsatisfiable without it.  For `M` the `−1` row is exactly the "`−1 ∈ im χ`" branch
condition of board note (iii), and `MarkedCore.neg_one_notMem_imChiN` shows the `N` and `M` images
genuinely differ, so this is the one row datum that could not have been inherited from the `N`
file.  §3's `EvenDegreeMModEightImage` is correspondingly the mod-eight shadow of the subgroup
generated by the `M` row values, a **four**-element set `{1, −1, mUnit α, −mUnit α}`, not the
`N` file's two.

## What is proved and what is owed

Proved: the bridge table at both entries, both shadow tables of `vM α`, the impossibility of an
`α = 2` scalar, the class pin at `α ≥ 3`, the second Witt refinement at `α = 2`, and the supply
theorem for **every** `α ≥ 2` (both branches; nothing is gated out).  Owed, as explicit binders of
the supply: the EV-4a row lift supply, the ramified-`i` binder `κ ≠ 0`, `EvenDegreeMModEightImage`
(consumed only at `α ≥ 3`), and at `α = 2` the two seams of §4.3.  No `sorry`, no new axiom.
-/

namespace GQ2.Dyadic.StageGeneric

noncomputable section

open GQ2 ContCoh
open GQ2.Roe.Labute
open GQ2.HilbertSymbol
open GQ2.Dyadic.Certificates.LSqStokes
open GQ2.Dyadic.LSquare
open GQ2.Dyadic.LSquare.FrattiniFrameSupply

local notation "ℚ̄₂" => AlgebraicClosure ℚ_[2]

/-! ## §1 The mod-sixteen bridge table at the `M` row values

Everything comes from the committed defining relation `MarkedCore.mUnit_mul`, pushed through
`PadicInt.toZModPow` and solved in the (tiny, closed) residue ring, plus the two residues of `−1`.
No mod-eight or mod-sixteen value of `mUnit` existed in the repo before this section. -/

/-- The defining relation of the `M` row's depth unit, reduced mod `2 ^ k`.  Note the shape
differs from the `N` row's `nUnit α · (1 + 2 ^ α) = −1`: here the sign is inside and the product
is `1`, since `mUnit α = (1 − 2 ^ α)⁻¹`. -/
theorem evenBridgeM_mUnit_mul (k : ℕ) {α : ℕ} (hα : 1 ≤ α) :
    (PadicInt.toZModPow k ((MarkedCore.mUnit α : ℤ_[2]ˣ) : ℤ_[2])) * (1 - 2 ^ α) = 1 := by
  have h := congrArg (PadicInt.toZModPow (p := 2) k) (MarkedCore.mUnit_mul (α := α) hα)
  simpa [map_ofNat] using h

/-- Solving the reduced relation mod eight at `α = 2` (`x · (1 − 4) = 1` in `ZMod 8`). -/
theorem evenBridgeM_solve_modEight {x : ZMod (2 ^ 3)} (h : x * (1 - 2 ^ 2) = 1) : x = 5 := by
  revert x
  decide

/-- Solving the reduced relation mod sixteen at `α = 2` (`x · (1 − 4) = 1` in `ZMod 16`). -/
theorem evenBridgeM_solve_modSixteen_two {x : ZMod (2 ^ 4)} (h : x * (1 - 2 ^ 2) = 1) :
    x = 5 := by
  revert x
  decide

/-- Solving the reduced relation mod sixteen at `α = 3` (`x · (1 − 8) = 1` in `ZMod 16`). -/
theorem evenBridgeM_solve_modSixteen_three {x : ZMod (2 ^ 4)} (h : x * (1 - 2 ^ 3) = 1) :
    x = 9 := by
  revert x
  decide

/-- **`mUnit α ≡ 1 (mod 4)` for `α ≥ 2`**, the parity entry of the depth unit, constant in `α`
and *trivial*, where the `N` row's was `3`.  (Agrees with the committed
`MarkedCore.mUnit_toZModPow_two`; re-derived here from the same defining relation the rest of the
table comes from, so that the whole table has one source.) -/
theorem evenBridgeM_mUnit_modFour {α : ℕ} (hα : 2 ≤ α) :
    PadicInt.toZModPow 2 ((MarkedCore.mUnit α : ℤ_[2]ˣ) : ℤ_[2]) = 1 := by
  have h := evenBridgeM_mUnit_mul 2 (α := α) (by omega)
  have h2 : (2 : ZMod (2 ^ 2)) ^ α = 0 := by
    obtain ⟨t, rfl⟩ : ∃ t, α = 2 + t := ⟨α - 2, by omega⟩
    rw [pow_add, show ((2 : ZMod (2 ^ 2)) ^ 2 = 0) from by decide, zero_mul]
  rw [h2, sub_zero, mul_one] at h
  exact h

/-- **`mUnit 2 ≡ 5 (mod 8)`**, the only `α` at which the `M` `ω` entry is nonzero. -/
theorem evenBridgeM_mUnit_modEight_two :
    PadicInt.toZModPow 3 ((MarkedCore.mUnit 2 : ℤ_[2]ˣ) : ℤ_[2]) = 5 :=
  evenBridgeM_solve_modEight (evenBridgeM_mUnit_mul 3 (α := 2) (by omega))

/-- **`mUnit α ≡ 1 (mod 8)` for `α ≥ 3`**: the `M` `ω` entry vanishes from `α = 3` on.  (The `N`
row's unit is `≡ 7` there; both have `ω = 0`, but the `M` unit is trivial mod eight, which is why
the whole `M` `ω` table vanishes rather than merely becoming a multiple of the parity table.) -/
theorem evenBridgeM_mUnit_modEight_ge {α : ℕ} (hα : 3 ≤ α) :
    PadicInt.toZModPow 3 ((MarkedCore.mUnit α : ℤ_[2]ˣ) : ℤ_[2]) = 1 := by
  have h := evenBridgeM_mUnit_mul 3 (α := α) (by omega)
  have h2 : (2 : ZMod (2 ^ 3)) ^ α = 0 := by
    obtain ⟨t, rfl⟩ : ∃ t, α = 3 + t := ⟨α - 3, by omega⟩
    rw [pow_add, show ((2 : ZMod (2 ^ 3)) ^ 3 = 0) from by decide, zero_mul]
  rw [h2, sub_zero, mul_one] at h
  exact h

/-! ### §1.1 The mod-sixteen row of the table

Recorded at the same modulus as the odd route's `S ≡ 13`, `X ≡ 5`, `Y ≡ 7` and the `N` row's
`3, 7, 15`, for the campaign record.  Only the mod-eight reductions are consumed downstream. -/

/-- **`mUnit 2 ≡ 5 (mod 16)`.** -/
theorem evenBridgeM_mUnit_modSixteen_two :
    PadicInt.toZModPow 4 ((MarkedCore.mUnit 2 : ℤ_[2]ˣ) : ℤ_[2]) = 5 :=
  evenBridgeM_solve_modSixteen_two (evenBridgeM_mUnit_mul 4 (α := 2) (by omega))

/-- **`mUnit 3 ≡ 9 (mod 16)`.** -/
theorem evenBridgeM_mUnit_modSixteen_three :
    PadicInt.toZModPow 4 ((MarkedCore.mUnit 3 : ℤ_[2]ˣ) : ℤ_[2]) = 9 :=
  evenBridgeM_solve_modSixteen_three (evenBridgeM_mUnit_mul 4 (α := 3) (by omega))

/-- **`mUnit α ≡ 1 (mod 16)` for `α ≥ 4`**: the table is constant from `α = 4` on, since `2 ^ α`
then dies mod sixteen.  (`N`'s constant tail is `15`; `M`'s is `1`.) -/
theorem evenBridgeM_mUnit_modSixteen_ge {α : ℕ} (hα : 4 ≤ α) :
    PadicInt.toZModPow 4 ((MarkedCore.mUnit α : ℤ_[2]ˣ) : ℤ_[2]) = 1 := by
  have h := evenBridgeM_mUnit_mul 4 (α := α) (by omega)
  have h2 : (2 : ZMod (2 ^ 4)) ^ α = 0 := by
    obtain ⟨t, rfl⟩ : ∃ t, α = 4 + t := ⟨α - 4, by omega⟩
    rw [pow_add, show ((2 : ZMod (2 ^ 4)) ^ 4 = 0) from by decide, zero_mul]
  rw [h2, sub_zero, mul_one] at h
  exact h

/-! ### §1.2 The `−1` row

The entry the `N` row does not have (board note (iii)).  Its two residues are `α`-free. -/

/-- `−1 ≡ 3 (mod 4)`: the `M` parity entry, at the letter `B`. -/
theorem evenBridgeM_negOne_modFour :
    PadicInt.toZModPow 2 (((-1 : ℤ_[2]ˣ) : ℤ_[2])) = 3 := by
  rw [Units.val_neg, Units.val_one, map_neg, map_one]
  decide

/-- `−1 ≡ 7 (mod 8)`: the `M` `ω` entry at the letter `B` vanishes, for every `α`. -/
theorem evenBridgeM_negOne_modEight :
    PadicInt.toZModPow 3 (((-1 : ℤ_[2]ˣ) : ℤ_[2])) = 7 := by
  rw [Units.val_neg, Units.val_one, map_neg, map_one]
  decide

/-- `−1 ≡ 15 (mod 16)`, for the record. -/
theorem evenBridgeM_negOne_modSixteen :
    PadicInt.toZModPow 4 (((-1 : ℤ_[2]ˣ) : ℤ_[2])) = 15 := by
  rw [Units.val_neg, Units.val_one, map_neg, map_one]
  decide

/-! ### §1.3 The four shadows of the two row values -/

/-- **The `ω` scalar of the `M` row**: `1` at `α = 2` and `0` at `α ≥ 3`.  As at the `N` row the
whole `α`-dependence of the even `M` bridge table is this one bit; **unlike** the `N` row it is
*not* a scalar relating the `ω` table to the parity table, because the two tables are supported at
different letters (§3.3).  It is the value of the `ω` table at the letter `D`. -/
def evenDegreeMOmegaScalar (α : ℕ) : ZMod 2 := if α = 2 then 1 else 0

/-- The mod-four parity shadow of the depth unit is `0`, for every `α ≥ 2`. -/
theorem evenDegreeM_parity_mUnit {α : ℕ} (hα : 2 ≤ α) :
    Multiplicative.toAdd (unitsModFourParity
      (Units.map (PadicInt.toZModPow 2).toMonoidHom (MarkedCore.mUnit α))) = 0 :=
  frattiniFrame_parity_of_val_one (evenBridgeM_mUnit_modFour hα)

/-- The mod-eight `ω` shadow of the depth unit is `evenDegreeMOmegaScalar α`. -/
theorem evenDegreeM_omega_mUnit {α : ℕ} (hα : 2 ≤ α) :
    Multiplicative.toAdd (unitsModEightOmega
      (Units.map (PadicInt.toZModPow 3).toMonoidHom (MarkedCore.mUnit α))) =
        evenDegreeMOmegaScalar α := by
  rcases eq_or_lt_of_le hα with hα2 | hα3
  · subst hα2
    rw [frattiniFrame_omega_of_val evenBridgeM_mUnit_modEight_two, omegaResidue_table.2.2.1,
      evenDegreeMOmegaScalar, if_pos rfl]
  · rw [frattiniFrame_omega_of_val (evenBridgeM_mUnit_modEight_ge (by omega)),
      omegaResidue_table.1, evenDegreeMOmegaScalar, if_neg (by omega)]

/-- The mod-four parity shadow of `−1` is `1`. -/
theorem evenDegreeM_parity_negOne :
    Multiplicative.toAdd (unitsModFourParity
      (Units.map (PadicInt.toZModPow 2).toMonoidHom (-1 : ℤ_[2]ˣ))) = 1 :=
  frattiniFrame_parity_of_val_three evenBridgeM_negOne_modFour

/-- The mod-eight `ω` shadow of `−1` is `0`. -/
theorem evenDegreeM_omega_negOne :
    Multiplicative.toAdd (unitsModEightOmega
      (Units.map (PadicInt.toZModPow 3).toMonoidHom (-1 : ℤ_[2]ˣ))) = 0 := by
  rw [frattiniFrame_omega_of_val evenBridgeM_negOne_modEight, omegaResidue_table.2.2.2]

/-! ## §2 The two shadow tables of the `M` row

The mod-four parity table of `vM α` is the indicator of the letter at index `1` (as at the `N`
row, so `evenFrame_of_kappaPin`'s parity hypothesis is met for every `α ≥ 2`), while the mod-eight
`ω` table is `evenDegreeMOmegaScalar α` times the indicator of the letter at index **`3`**. -/

/-- **The `M` parity table**: `1` at the letter `B` (index `1`) and `0` at every other letter,
the same shape as the `N` row's.  This is the table the model's Labute vector already realises,
so it costs no hypothesis on `K`. -/
theorem evenDegreeM_parity_table {α h : ℕ} (hα : 2 ≤ α) (i : Fin (MarkedCore.coreRank h)) :
    Multiplicative.toAdd (unitsModFourParity
      (Units.map (PadicInt.toZModPow 2).toMonoidHom (vM α i))) =
        if (i : ℕ) = 1 then 1 else 0 := by
  refine evenIndex_cases
    (P := fun i ↦ Multiplicative.toAdd (unitsModFourParity
      (Units.map (PadicInt.toZModPow 2).toMonoidHom (vM α i))) =
        if (i : ℕ) = 1 then 1 else 0) ?_ ?_ ?_ ?_ ?_ ?_ i
  · rw [vM_zero, map_one, map_one, toAdd_one,
      if_neg (by rw [MarkedCore.coreVal_zero]; omega)]
  · rw [vM_one, evenDegreeM_parity_negOne, if_pos (MarkedCore.coreVal_one h)]
  · rw [vM_two, map_one, map_one, toAdd_one, if_neg (by rw [MarkedCore.coreVal_two]; omega)]
  · rw [vM_three, evenDegreeM_parity_mUnit hα,
      if_neg (by rw [MarkedCore.coreVal_three]; omega)]
  · intro j
    rw [vM_handleU, map_one, map_one, toAdd_one,
      if_neg (by rw [MarkedCore.handleIdxU_val]; omega)]
  · intro j
    rw [vM_handleV, map_one, map_one, toAdd_one,
      if_neg (by rw [MarkedCore.handleIdxV_val]; omega)]

/-- **The `M` `ω` table**: `evenDegreeMOmegaScalar α` at the letter `D` (index `3`) and `0`
elsewhere.  The support is at index `3`, not index `1`: this is board crux (c) of the module
docstring, and the reason the `M` row needs §4. -/
theorem evenDegreeM_omega_table {α h : ℕ} (hα : 2 ≤ α) (i : Fin (MarkedCore.coreRank h)) :
    Multiplicative.toAdd (unitsModEightOmega
      (Units.map (PadicInt.toZModPow 3).toMonoidHom (vM α i))) =
        evenDegreeMOmegaScalar α * (if (i : ℕ) = 3 then 1 else 0) := by
  refine evenIndex_cases
    (P := fun i ↦ Multiplicative.toAdd (unitsModEightOmega
      (Units.map (PadicInt.toZModPow 3).toMonoidHom (vM α i))) =
        evenDegreeMOmegaScalar α * (if (i : ℕ) = 3 then 1 else 0)) ?_ ?_ ?_ ?_ ?_ ?_ i
  · rw [vM_zero, map_one, map_one, toAdd_one,
      if_neg (by rw [MarkedCore.coreVal_zero]; omega), mul_zero]
  · rw [vM_one, evenDegreeM_omega_negOne, if_neg (by rw [MarkedCore.coreVal_one]; omega),
      mul_zero]
  · rw [vM_two, map_one, map_one, toAdd_one,
      if_neg (by rw [MarkedCore.coreVal_two]; omega), mul_zero]
  · rw [vM_three, evenDegreeM_omega_mUnit hα, if_pos (MarkedCore.coreVal_three h), mul_one]
  · intro j
    rw [vM_handleU, map_one, map_one, toAdd_one,
      if_neg (by rw [MarkedCore.handleIdxU_val]; omega), mul_zero]
  · intro j
    rw [vM_handleV, map_one, map_one, toAdd_one,
      if_neg (by rw [MarkedCore.handleIdxV_val]; omega), mul_zero]

/-! ### §2.1 The `α = 2` obstruction to the `N`-row route

The scaffolding's `evenFrame_of_kappaPin` asks for a single scalar `c` with `ω`-table
`= c · (parity table)`, i.e. `c` times the indicator of index `1`.  At the `M` row that request is
**refutable** at `α = 2`, and the refutation is one line of the table: the `ω` value at the letter
`D` is `1`, while `c · (indicator of index 1)` is `c · 0 = 0` there, for every `c`.

This is the machine-checked form of the `N` agent's warning, and it is what forces §4. -/

/-- **No `ω` scalar exists at the `M` row when `α = 2`.**  Hence `evenFrame_of_kappaPin`, which is
the whole of the `N` row's frame construction, cannot be used at `M` for `α = 2`: not because a
proof was not found, but because its hypothesis is false there.  (For `α ≥ 3` the scalar is `0`
and the route works; see §3.) -/
theorem evenDegreeM_no_omegaScalar_two {h : ℕ} :
    ¬ ∃ c : ZMod 2, ∀ i : Fin (MarkedCore.coreRank h),
      Multiplicative.toAdd (unitsModEightOmega
        (Units.map (PadicInt.toZModPow 3).toMonoidHom (vM 2 i))) =
          c * (if (i : ℕ) = 1 then 1 else 0) := by
  rintro ⟨c, hc⟩
  have h3 := hc 3
  rw [evenDegreeM_omega_table (by omega) 3, if_pos (MarkedCore.coreVal_three h),
    if_neg (by rw [MarkedCore.coreVal_three]; omega), mul_one, mul_zero,
    evenDegreeMOmegaScalar, if_pos rfl] at h3
  exact one_ne_zero h3

/-! ## §3 The mod-eight orientation hypotheses, and the `ω`-class pin at `α ≥ 3`

The priced seams of this ticket, in the house pattern: named `Prop`s, discharged nowhere here.
There are two, because the `M` row's `ω` entry can be nonzero.  §3 asks that the mod-eight image
be no larger than the row values generate (consumed at `α ≥ 3`, where it forces `τ = 0`); §3.1
asks that the depth row value actually be attained (consumed at `α = 2`, where it forces `τ` to be
independent of `κ`).  Both are consequences of the image identity
`MonoidHom.range chiCycKTwo = MarkedCore.imChiM α`, and each is vacuous where the other bites. -/

section EvenFieldM

variable {K : IntermediateField ℚ_[2] ℚ̄₂} [FiniteDimensional ℚ_[2] K]
  [CompactSpace (GalK K)] [T2Space (GalK K)] [TotallyDisconnectedSpace (GalK K)]

local instance mEvenFrameScalar : DistribMulAction (maxProPQuotient 2 (GalK K)) (ZMod 2) :=
  scalarActionZmodTwo _

local instance mEvenFrameContinuousScalar :
    ContinuousSMul (maxProPQuotient 2 (GalK K)) (ZMod 2) :=
  scalarActionZmodTwo_continuousSMul _

/-- **The even `M`-row mod-eight orientation hypothesis.**  Every cyclotomic value of `G_K(2)`
reduces mod eight into `{1, −1, mUnit α, −mUnit α}`.

This is the mod-eight half of `MonoidHom.range chiCycKTwo = MarkedCore.imChiM α`.  Where the `N`
row's twin has a two-element set, this one has four: the `M` image is generated by **two** row
values, `−1` and `mUnit α`, so its mod-eight shadow is closed under multiplication by `−1`.  At
`α ≥ 3` the set collapses to `{1, −1}` (§1), which is what makes the `ω` class vanish; at `α = 2`
it is all of `(ZMod 8)ˣ` and the hypothesis says nothing, which is why `α = 2` needs §3.1 instead.

It is *not* discharged in this lane: the forward route deliberately avoids assuming the range
identity (`EvenForwardRouteSkeleton.lean:20–28`), so a consumer that has the range identity
supplies this, and a consumer that does not must obtain it another way. -/
def EvenDegreeMModEightImage (α : ℕ) : Prop :=
  ∀ g : maxProPQuotient 2 (GalK K),
    PadicInt.toZModPow 3 ((chiCycKTwo (K := K) g : ℤ_[2]ˣ) : ℤ_[2]) = 1 ∨
      PadicInt.toZModPow 3 ((chiCycKTwo (K := K) g : ℤ_[2]ˣ) : ℤ_[2]) = -1 ∨
      PadicInt.toZModPow 3 ((chiCycKTwo (K := K) g : ℤ_[2]ˣ) : ℤ_[2]) =
        PadicInt.toZModPow 3 ((MarkedCore.mUnit α : ℤ_[2]ˣ) : ℤ_[2]) ∨
      PadicInt.toZModPow 3 ((chiCycKTwo (K := K) g : ℤ_[2]ˣ) : ℤ_[2]) =
        -PadicInt.toZModPow 3 ((MarkedCore.mUnit α : ℤ_[2]ˣ) : ℤ_[2])

omit [FiniteDimensional ℚ_[2] K] [T2Space (GalK K)] in
/-- **The `ω`-class pin at the `M` row, for `α ≥ 3`.**  There the mod-eight orientation hypothesis
forces `τ = 0 = evenDegreeMOmegaScalar α • κ`: every cyclotomic value is `≡ ±1 (mod 8)`, where `ω`
vanishes.  Compare the `N` row, where the pin is nontrivial at every `α`; here the pin says the
`ω` class *itself* dies, which is stronger, and is exactly what the vanishing `M` `ω` table
demands. -/
theorem evenDegreeM_omegaPin_of_modEightImage {α : ℕ} (hα : 3 ≤ α)
    (himg : EvenDegreeMModEightImage (K := K) α) :
    cyclotomicModEightOmegaClassKTwo (K := K) =
      evenDegreeMOmegaScalar α • cyclotomicModFourClassKTwo (K := K) := by
  have hscal : evenDegreeMOmegaScalar α = 0 := by
    rw [evenDegreeMOmegaScalar, if_neg (by omega)]
  have hm : PadicInt.toZModPow 3 ((MarkedCore.mUnit α : ℤ_[2]ˣ) : ℤ_[2]) = 1 :=
    evenBridgeM_mUnit_modEight_ge hα
  have homegaOne : omegaResidue 1 = 0 := omegaResidue_table.1
  have homegaNeg : omegaResidue (-1) = 0 := by decide
  refine evenFrameOmegaPin_of_pointwise _ fun g ↦ ?_
  rw [hscal, zero_mul]
  rcases himg g with h1 | h2 | h3 | h4
  · rw [frattiniFrame_omega_of_val h1, homegaOne]
  · rw [frattiniFrame_omega_of_val h2, homegaNeg]
  · rw [hm] at h3
    rw [frattiniFrame_omega_of_val h3, homegaOne]
  · rw [hm] at h4
    rw [frattiniFrame_omega_of_val h4, homegaNeg]

/-! ### §3.1 The attained-row hypothesis, the `α = 2` seam -/

/-- **The even `M`-row attainment hypothesis**: the depth row value `mUnit α` is realised mod
eight by some cyclotomic value.

This is the mod-eight half of `mUnit α ∈ MonoidHom.range chiCycKTwo`, i.e. of the `D`-row
membership that the `M` row needs anyway (board note (iii)).  It cannot be extracted from the
carried `RowExactLevelFibreLiftSupply` binder, which lifts *given* level classes of the right
shadow rather than asserting that any exist, so it is stated separately.

At `α ≥ 3` it is free (`evenDegreeM_rowAttained_of_ge`); at `α = 2` it is the whole content of the
`α = 2` branch, since it is what makes the `ω` class nonzero and independent of `κ`. -/
def EvenDegreeMModEightRowAttained (α : ℕ) : Prop :=
  ∃ g : maxProPQuotient 2 (GalK K),
    PadicInt.toZModPow 3 ((chiCycKTwo (K := K) g : ℤ_[2]ˣ) : ℤ_[2]) =
      PadicInt.toZModPow 3 ((MarkedCore.mUnit α : ℤ_[2]ˣ) : ℤ_[2])

omit [FiniteDimensional ℚ_[2] K] [T2Space (GalK K)] in
/-- At `α ≥ 3` the attainment hypothesis costs nothing: the depth unit is `≡ 1 (mod 8)` there and
the identity element witnesses it.  So the `α = 2` branch is the only place a consumer pays. -/
theorem evenDegreeM_rowAttained_of_ge {α : ℕ} (hα : 3 ≤ α) :
    EvenDegreeMModEightRowAttained (K := K) α :=
  ⟨1, by rw [map_one, Units.val_one, map_one, evenBridgeM_mUnit_modEight_ge hα]⟩

/-! ## §4 The second Witt refinement, for `α = 2`

§2.1 rules out the `N` row's route at `α = 2`, so this section supplies what
`evenFrame_of_adapted` needs directly: an adapted coordinate system placing **two** classes, `κ`
at the letter `B` (index `1`, forced by the model, §1.5 of the scaffolding) and `τ` at the letter
`D` (index `3`, the `(2,3)` plane).  This is the even route's analogue of the odd route's second
Witt step, which puts the `ω` vector on the diagonal of the first hyperbolic plane; the `N` row
avoided it because its `ω` table is a multiple of its parity table.

The mechanism is a Witt-type transitivity that the repository did not have: *the isometry group of
an `𝔽₂` cup form acts transitively on the isotropic vectors outside `{0, κ}`*.  It is proved here
by transvections `z ↦ z + b(z,v)·v` at isotropic `v`, which are isometries, are involutions, and
**automatically fix `κ`** — because `b(κ,v) = b(v,v) = 0` is exactly the Labute identity.  Two of
them suffice, through a common vector obtained by an elementary separation argument; no Witt
extension theorem and no symplectic-basis surgery is needed.

Everything in §4.1–§4.4 is core-agnostic and `K`-free linear algebra. -/

/-! ### §4.1 The target vector -/

/-- The model vector `τ` must be carried to: the second coordinate of the first hyperbolic plane,
i.e. the frame coordinate vector supported at the letter `D` (index `3`).  Compare
`evenFrameKappaVec`, supported at index `1`; the two are what the `M` shadow tables of §2
demand. -/
def mEvenFrameTauVec (h : ℕ) : evenFrameModel h := (0, Pi.single 0 (0, 1))

/-- **The `τ` row of the `M` bridge table, model side**: the target vector has frame coordinate
`1` at the letter `D` and `0` at every other letter. -/
theorem mEvenFrameCoord_tauVec {h : ℕ} (i : Fin (MarkedCore.coreRank h)) :
    evenFrameCoord i (mEvenFrameTauVec h) = if (i : ℕ) = 3 then 1 else 0 := by
  refine evenIndex_cases
    (P := fun i ↦ evenFrameCoord i (mEvenFrameTauVec h) = if (i : ℕ) = 3 then 1 else 0)
    ?_ ?_ ?_ ?_ ?_ ?_ i
  · rw [evenFrameCoord_zero, if_neg (by rw [MarkedCore.coreVal_zero]; omega)]
    rfl
  · rw [evenFrameCoord_one, if_neg (by rw [MarkedCore.coreVal_one]; omega)]
    rfl
  · rw [evenFrameCoord_two, if_neg (by rw [MarkedCore.coreVal_two]; omega)]
    simp [mEvenFrameTauVec]
  · rw [evenFrameCoord_three, if_pos (MarkedCore.coreVal_three h)]
    simp [mEvenFrameTauVec]
  · intro j
    rw [evenFrameCoord_handleU, if_neg (by rw [MarkedCore.handleIdxU_val]; omega)]
    simp [mEvenFrameTauVec]
  · intro j
    rw [evenFrameCoord_handleV, if_neg (by rw [MarkedCore.handleIdxV_val]; omega)]
    simp [mEvenFrameTauVec]

/-- The target vector is isotropic, as any vector orthogonal to the Labute vector must be. -/
theorem mEvenFrameTauVec_self (h : ℕ) :
    evenFrameGramModel h (mEvenFrameTauVec h) (mEvenFrameTauVec h) = 0 := by
  rw [evenFrameGramModel_self, mEvenFrameCoord_tauVec,
    if_neg (by rw [MarkedCore.coreVal_zero]; omega)]

/-- The target vector is nonzero. -/
theorem mEvenFrameTauVec_ne_zero (h : ℕ) : mEvenFrameTauVec h ≠ 0 := by
  intro hzero
  have hc := congrArg (evenFrameCoord (3 : Fin (MarkedCore.coreRank h))) hzero
  rw [mEvenFrameCoord_tauVec, if_pos (MarkedCore.coreVal_three h),
    evenFrameCoord_zero_vec] at hc
  exact one_ne_zero hc

/-- The target vector is not the Labute vector: they are supported at different letters, which is
the whole point of §2.1. -/
theorem mEvenFrameTauVec_ne_kappaVec (h : ℕ) : mEvenFrameTauVec h ≠ evenFrameKappaVec h := by
  intro hzero
  have hc := congrArg (evenFrameCoord (3 : Fin (MarkedCore.coreRank h))) hzero
  rw [mEvenFrameCoord_tauVec, if_pos (MarkedCore.coreVal_three h), evenFrameCoord_kappaVec,
    if_neg (by rw [MarkedCore.coreVal_three]; omega)] at hc
  exact one_ne_zero hc

/-! ### §4.2 Transvections at isotropic vectors -/

section Transvection

variable {W : Type*} [AddCommGroup W] [Module (ZMod 2) W] {b : W → W → ZMod 2}

/-- **The transvection at an isotropic vector**, `z ↦ z + b(z,v)·v`.  Over `𝔽₂` it is its own
inverse, so it is packaged directly as a linear equivalence. -/
def mEvenFrameTransvection (hb : IsCupFormFp2 b) {v : W} (hv : b v v = 0) : W ≃ₗ[ZMod 2] W where
  toFun z := z + b z v • v
  map_add' z z' := by
    show (z + z') + b (z + z') v • v = (z + b z v • v) + (z' + b z' v • v)
    rw [hb.add_left, add_smul]
    abel
  map_smul' c z := by
    show c • z + b (c • z) v • v = c • (z + b z v • v)
    rw [hb.smul_left, smul_add, smul_smul]
  invFun z := z + b z v • v
  left_inv z := by
    show z + b z v • v + b (z + b z v • v) v • v = z
    rw [hb.add_left, hb.smul_left, hv, mul_zero, add_zero, add_assoc, ← add_smul,
      CharTwo.add_self_eq_zero, zero_smul, add_zero]
  right_inv z := by
    show z + b z v • v + b (z + b z v • v) v • v = z
    rw [hb.add_left, hb.smul_left, hv, mul_zero, add_zero, add_assoc, ← add_smul,
      CharTwo.add_self_eq_zero, zero_smul, add_zero]

@[simp] theorem mEvenFrameTransvection_apply (hb : IsCupFormFp2 b) {v : W} (hv : b v v = 0)
    (z : W) : mEvenFrameTransvection hb hv z = z + b z v • v := rfl

/-- **A transvection at an isotropic vector is an isometry.**  The two cross terms cancel in
characteristic two; isotropy of `v` kills the remaining one. -/
theorem mEvenFrameTransvection_isometry (hb : IsCupFormFp2 b) {v : W} (hv : b v v = 0)
    (z z' : W) :
    b (mEvenFrameTransvection hb hv z) (mEvenFrameTransvection hb hv z') = b z z' := by
  have hchar : ∀ x y : ZMod 2, x * y + y * x = 0 := by decide
  show b (z + b z v • v) (z' + b z' v • v) = b z z'
  rw [hb.add_left, hb.add_right, hb.add_right, hb.smul_left, hb.smul_left, hb.smul_right,
    hb.smul_right, hv, mul_zero, mul_zero, add_zero, hb.symm v z', add_assoc, hchar, add_zero]

/-- **A transvection at an isotropic vector fixes the Labute vector**, for free: the Labute
identity turns `b(e, v)` into `b(v, v)`, which is `0`.  This is why no bookkeeping is needed to
keep `κ` in place while `τ` is moved. -/
theorem mEvenFrameTransvection_fix (hb : IsCupFormFp2 b) {v : W} (hv : b v v = 0) {e : W}
    (he : ∀ w, b e w = b w w) : mEvenFrameTransvection hb hv e = e := by
  show e + b e v • v = e
  rw [he v, hv, zero_smul, add_zero]

/-- **The transvection at `x + y` carries `x` to `y`**, when `x` is isotropic and pairs to `1`
with `y`. -/
theorem mEvenFrameTransvection_swap (hb : IsCupFormFp2 b) {x y : W} (hx : b x x = 0)
    (hxy : b x y = 1) (hv : b (x + y) (x + y) = 0) :
    mEvenFrameTransvection hb hv x = y := by
  have h2 : ∀ w : W, w + w = 0 := GQ2.Dyadic.Certificates.module_zmod2_two_torsion
  show x + b x (x + y) • (x + y) = y
  rw [hb.add_right, hx, hxy, zero_add, one_smul, ← add_assoc, h2, zero_add]

/-! ### §4.3 Separation

Two elementary consequences of nondegeneracy.  No dimension count and no dual basis: over `𝔽₂` a
vector paired `1` with `x` and `0` with `e` is produced from any two nontrivial pairings by
adding them, and the same trick then serves two vectors at once. -/

omit [Module (ZMod 2) W] in
/-- Nondegeneracy, in the form used below. -/
theorem mEvenFrameExists_pairOne (hnd : NondegFp2 b) {x : W} (hx : x ≠ 0) : ∃ z, b x z = 1 := by
  by_contra hcon
  refine hx (hnd x fun w ↦ ?_)
  rcases ZMod.eq_zero_or_eq_one (b x w) with h | h
  · exact h
  · exact absurd ⟨w, h⟩ hcon

/-- **Separation from the Labute vector**: for `x` outside `{0, e}` there is an `z` pairing `1`
with `x` and `0` with `e`; by the Labute identity such an `z` is automatically isotropic. -/
theorem mEvenFrameExists_sep (hb : IsCupFormFp2 b) (hnd : NondegFp2 b) {e : W} {x : W}
    (hx0 : x ≠ 0) (hxe : x ≠ e) : ∃ z, b e z = 0 ∧ b x z = 1 := by
  have h2 : ∀ w : W, w + w = 0 := GQ2.Dyadic.Certificates.module_zmod2_two_torsion
  obtain ⟨z₀, hz₀⟩ := mEvenFrameExists_pairOne hnd hx0
  have hxe0 : x + e ≠ 0 := by
    intro hcon
    refine hxe ?_
    have hc := congrArg (fun w ↦ w + e) hcon
    simpa [add_assoc, h2] using hc
  obtain ⟨z₁, hz₁⟩ := mEvenFrameExists_pairOne hnd hxe0
  rcases ZMod.eq_zero_or_eq_one (b e z₀) with h0 | h0
  · exact ⟨z₀, h0, hz₀⟩
  rw [hb.add_left] at hz₁
  rcases ZMod.eq_zero_or_eq_one (b e z₁) with h1 | h1
  · refine ⟨z₁, h1, ?_⟩
    rw [h1, add_zero] at hz₁
    exact hz₁
  · rcases ZMod.eq_zero_or_eq_one (b x z₁) with hx1 | hx1
    · exact ⟨z₀ + z₁, by rw [hb.add_right, h0, h1]; decide,
        by rw [hb.add_right, hz₀, hx1, add_zero]⟩
    · rw [hx1, h1] at hz₁
      exact absurd hz₁ (by decide)

/-- **Simultaneous separation**: one vector isotropic and pairing `1` with each of two given
vectors outside `{0, e}`.  If the two separators of the previous lemma do not already work, their
sum does. -/
theorem mEvenFrameExists_common (hb : IsCupFormFp2 b) (hnd : NondegFp2 b) {e x y : W}
    (hx0 : x ≠ 0) (hxe : x ≠ e) (hy0 : y ≠ 0) (hye : y ≠ e) :
    ∃ z, b e z = 0 ∧ b x z = 1 ∧ b y z = 1 := by
  obtain ⟨z₁, hz₁e, hz₁x⟩ := mEvenFrameExists_sep hb hnd hx0 hxe
  obtain ⟨z₂, hz₂e, hz₂y⟩ := mEvenFrameExists_sep hb hnd hy0 hye
  rcases ZMod.eq_zero_or_eq_one (b y z₁) with hy1 | hy1
  · rcases ZMod.eq_zero_or_eq_one (b x z₂) with hx2 | hx2
    · exact ⟨z₁ + z₂, by rw [hb.add_right, hz₁e, hz₂e, add_zero],
        by rw [hb.add_right, hz₁x, hx2, add_zero],
        by rw [hb.add_right, hy1, hz₂y, zero_add]⟩
    · exact ⟨z₂, hz₂e, hx2, hz₂y⟩
  · exact ⟨z₁, hz₁e, hz₁x, hy1⟩

/-! ### §4.4 Witt transitivity on isotropic vectors -/

/-- **The isometry group of an `𝔽₂` cup form acts transitively on the isotropic vectors outside
`{0, κ}`**, by isometries fixing `κ`.

This is the Witt-type statement the repository lacked, and it is what the odd route's second
refinement amounts to.  The proof is two transvections through a common separator: `x ↦ z ↦ y`.
Every vector involved is isotropic, hence orthogonal to `κ` by the Labute identity, hence every
transvection used fixes `κ`. -/
theorem mEvenFrameIsometry_of_isotropic (hb : IsCupFormFp2 b) (hnd : NondegFp2 b) {e : W}
    (he : ∀ w, b e w = b w w) {x y : W} (hx : b x x = 0) (hy : b y y = 0)
    (hx0 : x ≠ 0) (hxe : x ≠ e) (hy0 : y ≠ 0) (hye : y ≠ e) :
    ∃ S : W ≃ₗ[ZMod 2] W, (∀ u w, b (S u) (S w) = b u w) ∧ S e = e ∧ S x = y := by
  obtain ⟨z, hze, hzx, hzy⟩ := mEvenFrameExists_common hb hnd hx0 hxe hy0 hye
  have hzz : b z z = 0 := by rw [← he z]; exact hze
  have hzy' : b z y = 1 := by rw [hb.symm]; exact hzy
  have hv₁ : b (x + z) (x + z) = 0 := by
    rw [← he (x + z), hb.add_right, he x, he z, hx, hzz, add_zero]
  have hv₂ : b (z + y) (z + y) = 0 := by
    rw [← he (z + y), hb.add_right, he z, he y, hzz, hy, add_zero]
  refine ⟨(mEvenFrameTransvection hb hv₁).trans (mEvenFrameTransvection hb hv₂),
    fun u w ↦ ?_, ?_, ?_⟩
  · show b (mEvenFrameTransvection hb hv₂ (mEvenFrameTransvection hb hv₁ u))
      (mEvenFrameTransvection hb hv₂ (mEvenFrameTransvection hb hv₁ w)) = b u w
    rw [mEvenFrameTransvection_isometry hb hv₂, mEvenFrameTransvection_isometry hb hv₁]
  · show mEvenFrameTransvection hb hv₂ (mEvenFrameTransvection hb hv₁ e) = e
    rw [mEvenFrameTransvection_fix hb hv₁ he, mEvenFrameTransvection_fix hb hv₂ he]
  · show mEvenFrameTransvection hb hv₂ (mEvenFrameTransvection hb hv₁ x) = y
    rw [mEvenFrameTransvection_swap hb hx hzx hv₁,
      mEvenFrameTransvection_swap hb hzz hzy' hv₂]

end Transvection

/-! ### §4.5 The doubly adapted normal form -/

/-- **The even adapted normal form, with the `ω` vector placed as well.**  The refinement of
`evenFrameAdaptedModelEquiv` that the `M` row needs at `α = 2`: an isometry to the even coordinate
model carrying the Labute vector `e` to the letter `B` **and** a second isotropic vector `t`,
independent of `e`, to the letter `D`.

The hypotheses on `t` are exactly the necessary ones: the model forces `b(κ, Φ⁻¹τ) = 0` and
`τ ∉ {0, κ}` for any such placement, and by the Labute identity `b(κ, t) = b(t, t)`, so
isotropy of `t` is the whole of the first condition. -/
theorem mEvenFrameAdaptedModelEquiv {W : Type*} [AddCommGroup W] [Module (ZMod 2) W] [Finite W]
    {b : W → W → ZMod 2} (hb : IsCupFormFp2 b) (hnd : NondegFp2 b) {e t : W}
    (he : ∀ w, b e w = b w w) (he0 : b e e = 0) (hne : e ≠ 0)
    (ht : b t t = 0) (ht0 : t ≠ 0) (hte : t ≠ e)
    {h : ℕ} (hcard : Nat.card W = 2 ^ (2 * h + 4)) :
    ∃ Φ : W ≃ₗ[ZMod 2] evenFrameModel h,
      (∀ x y, b x y = evenFrameGramModel h (Φ x) (Φ y)) ∧ Φ e = evenFrameKappaVec h ∧
        Φ t = mEvenFrameTauVec h := by
  obtain ⟨Φ₀, hgram, hkap⟩ := evenFrameAdaptedModelEquiv hb hnd he he0 hne hcard
  set t' : W := Φ₀.symm (mEvenFrameTauVec h) with ht'
  have hΦt' : Φ₀ t' = mEvenFrameTauVec h := Φ₀.apply_symm_apply _
  have ht'self : b t' t' = 0 := by rw [hgram, hΦt', mEvenFrameTauVec_self]
  have ht'0 : t' ≠ 0 := by
    intro hcon
    refine mEvenFrameTauVec_ne_zero h ?_
    rw [← hΦt', hcon, map_zero]
  have ht'e : t' ≠ e := by
    intro hcon
    refine mEvenFrameTauVec_ne_kappaVec h ?_
    rw [← hΦt', hcon, hkap]
  obtain ⟨S, hS, hSe, hSt⟩ :=
    mEvenFrameIsometry_of_isotropic hb hnd he ht ht'self ht0 hte ht'0 ht'e
  refine ⟨S.trans Φ₀, fun x y ↦ ?_, ?_, ?_⟩
  · show b x y = evenFrameGramModel h (Φ₀ (S x)) (Φ₀ (S y))
    rw [← hgram, hS]
  · show Φ₀ (S e) = evenFrameKappaVec h
    rw [hSe, hkap]
  · show Φ₀ (S t) = mEvenFrameTauVec h
    rw [hSt, hΦt']

end EvenFieldM

end

end GQ2.Dyadic.StageGeneric
