/-
Copyright (c) 2026 David Roe. All rights reserved.
Released under the Apache 2.0 license as described in the file LICENSE.
Authors: David Roe, roed@mit.edu, using Claude Opus-5
-/
import GQ2.Dyadic.Instances.StageAbstractionEvenSharpHandles

/-!
# W51-EV3F2 §B: the even bracket span

Ticket **EV-3f** of `docs/dyadic/ev4b-stage-abstraction.md` §4, assembly half, cut against
`docs/dyadic/w51-ev3f-seam.md` §2.  The even clone of the L template's
`GammaLSylowPreimageFieldLabuteForwardSpanAudit.lean` and
`GammaLSylowPreimageFieldLabuteBracketSpan.lean`, which the seam note §4.1 assigns to this
half because every declaration in them is stated against the character.

The content is one identification.  §A §7 reduced the existence of an actual-defect supply to
the reachability of a residual by a *neutral* correction, that is, to membership in the image
of a homomorphism.  Here that image is computed: it is the subgroup generated by six explicit
families of atoms, read off from F1's six exact coordinate rows
(`evenRawDepthShiftHom_{zero,one,two,three,handleU,handleV}_apply`) with the coordinate
restricted to run over neutral elements only.

The even atom table differs from the L one exactly as the seam note §3 predicts:

| coordinate | L atom | even atom |
|---|---|---|
| 0 | `[p, base 1]` | `p² · [p, base 0] · [p, base 1]` |
| 1 | `[p, base 0]` | `[p, base 0]` |
| 2 | `p² · [p, base 2]` | `[p, base 3]` |
| 3 | — (rank 3) | `[p, base 2]` |
| `U_j` | `[p, base (V_j)]` | `[p, base (V_j)]` |
| `V_j` | `[p, base (U_j)]` | `[p, base (U_j)]` |

so the diagonal square has moved from coordinate `2` to coordinate `0` and has acquired a
second bracket partner.  That is the whole even-specific content of this file, and it shows up
in exactly one place: the regrouping of §5, where the coordinate-`0` and coordinate-`1` letters
of the literal word must be separated before the atoms can be recognised.

## Numbering

1. the neutral coordinates, as a subgroup;
2. the one-coordinate neutral corrections;
3. the neutral shift homomorphism;
4. the atom set and the bracket span;
5. the image of the neutral shift is the bracket span;
6. the reachability criterion as a membership.
-/

namespace GQ2.Dyadic.StageGeneric

noncomputable section

open GQ2
open GQ2.Roe.Labute
open GQ2.Dyadic.EvenRowSupply

/-! ## §1 The neutral coordinates

The clone of `sharpNeutralCoordinateSubgroup` (L template, line 647).  A coordinate is
available to a neutral correction when it has depth `k-1` and a representative of trivial
character to `s` fresh digits; both conditions are closed under the group operations, so the
available coordinates form a subgroup of `Q_{k+1}`. -/

section NeutralSubgroup

variable {G : Type} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
variable {chi : ContinuousMonoidHom G ℤ_[2]ˣ}

/-- The coordinates a depth-`s` neutral correction may use. -/
def evenBracketNeutralSubgroup (s : ℕ) (G : Type) [Group G] [TopologicalSpace G]
    [IsTopologicalGroup G] (chi : ContinuousMonoidHom G ℤ_[2]ˣ) (k : ℕ) :
    Subgroup (levelQuot G (k + 1)) where
  carrier := {p | p ∈ lambdaImage G (k - 1) (k + 1) ∧ ∃ g : G, p = levelMk G (k + 1) g ∧
    Units.map (PadicInt.toZModPow (k + 1 + s)).toMonoidHom (chi g) = 1}
  mul_mem' := by
    intro a b ha hb
    obtain ⟨hda, ga, hga, hgachi⟩ := ha
    obtain ⟨hdb, gb, hgb, hgbchi⟩ := hb
    exact ⟨Subgroup.mul_mem _ hda hdb, ga * gb, by rw [hga, hgb, map_mul],
      by rw [map_mul, map_mul, hgachi, hgbchi, one_mul]⟩
  one_mem' := ⟨Subgroup.one_mem _, 1, (map_one (levelMk G (k + 1))).symm,
    by rw [map_one, map_one]⟩
  inv_mem' := by
    intro a ha
    obtain ⟨hda, ga, hga, hgachi⟩ := ha
    exact ⟨Subgroup.inv_mem _ hda, ga⁻¹, by rw [hga, map_inv],
      by rw [map_inv, map_inv, hgachi, inv_one]⟩

@[simp] theorem evenBracket_mem_neutralSubgroup {s k : ℕ} {p : levelQuot G (k + 1)} :
    p ∈ evenBracketNeutralSubgroup s G chi k ↔
      p ∈ lambdaImage G (k - 1) (k + 1) ∧ ∃ g : G, p = levelMk G (k + 1) g ∧
        Units.map (PadicInt.toZModPow (k + 1 + s)).toMonoidHom (chi g) = 1 :=
  Iff.rfl

/-- A neutral coordinate has depth `k-1`; this is the projection §5 hands to F1's rows. -/
theorem evenBracketNeutral_depth {s k : ℕ} (p : evenBracketNeutralSubgroup s G chi k) :
    p.1 ∈ lambdaImage G (k - 1) (k + 1) := p.2.1

end NeutralSubgroup

/-! ## §2 One-coordinate neutral corrections

The clone of `SharpNeutralCorrection.single` (L template, `ForwardSpanAudit.lean` line 41).
Its underlying raw correction is *definitionally* F1's `evenRawDepthCoordinateCorrection`, so
the six coordinate rows apply to it verbatim; that is the whole reason §5 is short. -/

section Single

variable {G : Type} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
variable {chi : ContinuousMonoidHom G ℤ_[2]ˣ} {s h k : ℕ}

/-- The neutral correction carrying `p` at coordinate `i` and `1` elsewhere. -/
def EvenSharpNeutralCorrection.single (i : Fin (MarkedCore.coreRank h))
    (p : evenBracketNeutralSubgroup s G chi k) : EvenSharpNeutralCorrection s G chi h k where
  correction j := if j = i then p.1 else 1
  depth j := by
    by_cases hji : j = i
    · rw [if_pos hji]; exact p.2.1
    · rw [if_neg hji]; exact Subgroup.one_mem _
  neutral j := by
    by_cases hji : j = i
    · rw [if_pos hji]; exact p.2.2
    · exact ⟨1, by rw [if_neg hji, map_one], by rw [map_one, map_one]⟩

@[simp] theorem EvenSharpNeutralCorrection.single_correction
    (i j : Fin (MarkedCore.coreRank h)) (p : evenBracketNeutralSubgroup s G chi k) :
    (EvenSharpNeutralCorrection.single (h := h) i p).correction j =
      if j = i then p.1 else 1 := rfl

/-- The raw shadow of a one-coordinate neutral correction is F1's one-coordinate raw
correction, on the nose. -/
theorem EvenSharpNeutralCorrection.toRaw_single (i : Fin (MarkedCore.coreRank h))
    (p : evenBracketNeutralSubgroup s G chi k) :
    (EvenSharpNeutralCorrection.single (h := h) i p).toRaw =
      evenRawDepthCoordinateCorrection i ⟨p.1, p.2.1⟩ := rfl

end Single

/-! ## §3 The neutral shift homomorphism

The clone of `sharpNeutralShiftHom` (L template, line 618), obtained by restricting F1's raw
shift homomorphism along the forgetful map of §A §2. -/

section ShiftHom

variable {G : Type} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
variable [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G]
variable {chi : ContinuousMonoidHom G ℤ_[2]ˣ} {s h k : ℕ}

/-- The literal even shift word, restricted to depth-`s` neutral corrections. -/
def evenSharpNeutralShiftHom (base : Fin (MarkedCore.coreRank h) → levelQuot G (k + 1))
    (hk : 3 ≤ k) : EvenSharpNeutralCorrection s G chi h k →* zLayer G k :=
  (evenRawDepthShiftHom base hk).comp EvenSharpNeutralCorrection.toRawHom

@[simp] theorem evenSharpNeutralShiftHom_apply
    (base : Fin (MarkedCore.coreRank h) → levelQuot G (k + 1)) (hk : 3 ≤ k)
    (N : EvenSharpNeutralCorrection s G chi h k) :
    (evenSharpNeutralShiftHom base hk N).1 = evenRawDbarWord base N.correction := rfl

end ShiftHom

/-! ## §4 The atom set and the bracket span

The clone of `sharpNeutralBracketAtomSet` and `sharpNeutralBracketSpan` (L template, lines 98
and 157).  Six families, not five: the even core has rank four. -/

section AtomSet

variable {G : Type} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
variable {chi : ContinuousMonoidHom G ℤ_[2]ˣ} {s h k : ℕ}

/-- **The six even bracket atoms.**  Each family is the value of one exact coordinate row of
F1's raw shift homomorphism, with the coordinate restricted to the neutral subgroup.  Family
`0` is the only one carrying a square, and it carries *two* bracket partners: that is the even
lane's displacement of the L template's diagonal atom. -/
def evenBracketAtomSet (s : ℕ) (chi : ContinuousMonoidHom G ℤ_[2]ˣ)
    (base : Fin (MarkedCore.coreRank h) → levelQuot G (k + 1)) : Set (levelQuot G (k + 1)) :=
  {z | (∃ p : evenBracketNeutralSubgroup s G chi k,
          z = p.1 ^ 2 * commP p.1 (base 0) * commP p.1 (base 1)) ∨
       (∃ p : evenBracketNeutralSubgroup s G chi k, z = commP p.1 (base 0)) ∨
       (∃ p : evenBracketNeutralSubgroup s G chi k, z = commP p.1 (base 3)) ∨
       (∃ p : evenBracketNeutralSubgroup s G chi k, z = commP p.1 (base 2)) ∨
       (∃ (j : Fin h) (p : evenBracketNeutralSubgroup s G chi k),
          z = commP p.1 (base (MarkedCore.handleIdxV j))) ∨
       (∃ (j : Fin h) (p : evenBracketNeutralSubgroup s G chi k),
          z = commP p.1 (base (MarkedCore.handleIdxU j)))}

/-- **The even bracket span.** -/
def evenBracketSpan (s : ℕ) (chi : ContinuousMonoidHom G ℤ_[2]ˣ)
    (base : Fin (MarkedCore.coreRank h) → levelQuot G (k + 1)) :
    Subgroup (levelQuot G (k + 1)) :=
  Subgroup.closure (evenBracketAtomSet s chi base)

end AtomSet

/-! ## §5 The image of the neutral shift is the bracket span

The clone of `sharpNeutralShiftHom_range_eq_bracketSpan` (L template, line 173).

The inclusion `⊇` is the six coordinate rows, one line each.  The inclusion `⊆` is where the
even lane differs from the L one: the literal word groups its letters by *generator*, not by
*coordinate*, and at the even core the coordinate-`0` letters `p² · [p, base 0]` and
`[p, base 1]` are separated in the word by the coordinate-`1` letter `[p', base 0]`.  So one
transposition is needed before the atoms are visible, and it is legal because every letter is
central.  This is the same asymmetry the seam note §3(c),(d) records one level down. -/

section RangeEqSpan

variable {G : Type} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
variable [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G]
variable {chi : ContinuousMonoidHom G ℤ_[2]ˣ} {s h k : ℕ}

/-- The one transposition the even core word needs: a central letter may be moved across its
neighbour so that the two coordinate-`0` letters become adjacent. -/
private theorem evenBracketRegroup {H : Type*} [Group H] (A C D X : H) (hCD : Commute C D) :
    A * (C * D) * X = A * D * C * X := by
  rw [hCD.eq, ← mul_assoc]

/-- **The image of the neutral shift homomorphism is the bracket span.** -/
theorem evenSharpNeutralShiftHom_range_eq_bracketSpan
    (base : Fin (MarkedCore.coreRank h) → levelQuot G (k + 1)) (hk : 3 ≤ k) :
    Subgroup.map (zLayer G k).subtype
        (evenSharpNeutralShiftHom (s := s) (chi := chi) base hk).range =
      evenBracketSpan s chi base := by
  refine le_antisymm ?_ ?_
  · rintro _ ⟨_, ⟨N, rfl⟩, rfl⟩
    show evenRawDbarWord base N.correction ∈ evenBracketSpan s chi base
    have hatom : ∀ (i : Fin (MarkedCore.coreRank h)),
        (⟨N.correction i, N.depth i, N.neutral i⟩ :
          evenBracketNeutralSubgroup s G chi k).1 = N.correction i := fun _ ↦ rfl
    have hcore : evenRawCoreDbarWord base N.correction ∈ evenBracketSpan s chi base := by
      rw [evenRawCoreDbarWord,
        evenBracketRegroup _ (commP (N.correction 1) (base 0))
          (commP (N.correction 0) (base 1)) _
          (zLayer_commute (commP_mem_zLayer k hk (N.depth 1) (base 0)) _)]
      refine Subgroup.mul_mem _ (Subgroup.mul_mem _ ?_ ?_) (Subgroup.mul_mem _ ?_ ?_) <;>
        refine Subgroup.subset_closure ?_
      · exact Or.inl ⟨⟨N.correction 0, N.depth 0, N.neutral 0⟩, rfl⟩
      · exact Or.inr (Or.inl ⟨⟨N.correction 1, N.depth 1, N.neutral 1⟩, rfl⟩)
      · exact Or.inr (Or.inr (Or.inr (Or.inl
          ⟨⟨N.correction 3, N.depth 3, N.neutral 3⟩, rfl⟩)))
      · exact Or.inr (Or.inr (Or.inl ⟨⟨N.correction 2, N.depth 2, N.neutral 2⟩, rfl⟩))
    have hhandle : evenRawHandleDbarWord base N.correction ∈ evenBracketSpan s chi base := by
      rw [evenRawHandleDbarWord]
      refine Subgroup.list_prod_mem _ ?_
      intro z hz
      simp only [List.mem_map] at hz
      obtain ⟨j, _, rfl⟩ := hz
      refine Subgroup.mul_mem _ (Subgroup.subset_closure ?_) (Subgroup.subset_closure ?_)
      · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr
          ⟨j, ⟨N.correction (MarkedCore.handleIdxV j), N.depth _, N.neutral _⟩, rfl⟩))))
      · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl
          ⟨j, ⟨N.correction (MarkedCore.handleIdxU j), N.depth _, N.neutral _⟩, rfl⟩))))
    exact Subgroup.mul_mem _ hcore hhandle
  · rw [evenBracketSpan, Subgroup.closure_le]
    rintro z (⟨p, rfl⟩ | ⟨p, rfl⟩ | ⟨p, rfl⟩ | ⟨p, rfl⟩ | ⟨j, p, rfl⟩ | ⟨j, p, rfl⟩)
    · exact ⟨_, ⟨EvenSharpNeutralCorrection.single 0 p, rfl⟩,
        evenRawDepthShiftHom_zero_apply base hk ⟨p.1, p.2.1⟩⟩
    · exact ⟨_, ⟨EvenSharpNeutralCorrection.single 1 p, rfl⟩,
        evenRawDepthShiftHom_one_apply base hk ⟨p.1, p.2.1⟩⟩
    · exact ⟨_, ⟨EvenSharpNeutralCorrection.single 2 p, rfl⟩,
        evenRawDepthShiftHom_two_apply base hk ⟨p.1, p.2.1⟩⟩
    · exact ⟨_, ⟨EvenSharpNeutralCorrection.single 3 p, rfl⟩,
        evenRawDepthShiftHom_three_apply base hk ⟨p.1, p.2.1⟩⟩
    · exact ⟨_, ⟨EvenSharpNeutralCorrection.single (MarkedCore.handleIdxU j) p, rfl⟩,
        evenRawDepthShiftHom_handleU_apply base hk j ⟨p.1, p.2.1⟩⟩
    · exact ⟨_, ⟨EvenSharpNeutralCorrection.single (MarkedCore.handleIdxV j) p, rfl⟩,
        evenRawDepthShiftHom_handleV_apply base hk j ⟨p.1, p.2.1⟩⟩

end RangeEqSpan

/-! ## §6 The criterion as a membership

The clone of `sharpNeutralResidualReachable_iff_mem_bracketSpan` and of the crossing endpoint
`nonempty_coreHandleSharpActualDefectSupply_iff_mem_bracketSpan` (L template, lines 375 and
384).  This is the statement the derivation-family station consumes. -/

section Criterion

variable {G : Type} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
variable [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G]
variable {chi : ContinuousMonoidHom G ℤ_[2]ˣ} {s h k : ℕ}
variable {W : StageWord (MarkedCore.coreRank h)} {v : Fin (MarkedCore.coreRank h) → ℤ_[2]ˣ}
variable {T : Tuple W v G chi k}

/-- Reachability of the residual is membership in the bracket span. -/
theorem evenSharpNeutralResidualReachable_iff_mem_bracketSpan (hk : 3 ≤ k)
    (Wc : DeepSharpAdmissibleCorrection s T) :
    EvenSharpNeutralResidualReachable Wc ↔
      evenSharpNeutralResidualElement Wc ∈
        evenBracketSpan s chi (fun i ↦ canonLift G k (T.generators i)) := by
  rw [← evenSharpNeutralShiftHom_range_eq_bracketSpan
    (s := s) (chi := chi) (fun i ↦ canonLift G k (T.generators i)) hk]
  constructor
  · rintro ⟨N, hN⟩
    exact ⟨_, ⟨N, rfl⟩, hN⟩
  · rintro ⟨_, ⟨N, rfl⟩, hz⟩
    exact ⟨N, hz⟩

/-- **The crossing endpoint of the span half.**  An actual-defect supply exists exactly when
the residual of any depth-`s` correction lies in the even bracket span. -/
theorem nonempty_evenSharpActualDefectSupply_iff_mem_bracketSpan (hk : 3 ≤ k)
    (Wc : DeepSharpAdmissibleCorrection s T) :
    Nonempty (EvenSharpActualDefectSupply s T) ↔
      evenSharpNeutralResidualElement Wc ∈
        evenBracketSpan s chi (fun i ↦ canonLift G k (T.generators i)) := by
  rw [nonempty_evenSharpActualDefectSupply_iff_residual hk Wc,
    evenSharpNeutralResidualReachable_iff_mem_bracketSpan hk Wc]

end Criterion

end

end GQ2.Dyadic.StageGeneric

/-! ## §7 Axiom pins

Every public declaration of this file, printed.  All are expected at std-3,
`[propext, Classical.choice, Quot.sound]`, matching all thirteen pins of the two L template
files this one clones (`ForwardSpanAudit.lean` four, `BracketSpan.lean` nine). -/

section AxiomPins

open GQ2.Dyadic.StageGeneric

-- §1 the neutral coordinates
#print axioms evenBracketNeutralSubgroup
#print axioms evenBracket_mem_neutralSubgroup
#print axioms evenBracketNeutral_depth

-- §2 the one-coordinate corrections
#print axioms EvenSharpNeutralCorrection.single
#print axioms EvenSharpNeutralCorrection.single_correction
#print axioms EvenSharpNeutralCorrection.toRaw_single

-- §3 the neutral shift homomorphism
#print axioms evenSharpNeutralShiftHom
#print axioms evenSharpNeutralShiftHom_apply

-- §4 the atoms and the span
#print axioms evenBracketAtomSet
#print axioms evenBracketSpan

-- §5 the identification
#print axioms evenSharpNeutralShiftHom_range_eq_bracketSpan

-- §6 the criterion
#print axioms evenSharpNeutralResidualReachable_iff_mem_bracketSpan
#print axioms nonempty_evenSharpActualDefectSupply_iff_mem_bracketSpan

end AxiomPins
